package com.autonoma.erp.modules.hr.asset.controller;

import com.autonoma.erp.security.RequirePagePermission;
import com.autonoma.erp.modules.hr.asset.entity.AssetType;
import com.autonoma.erp.modules.hr.asset.service.AssetTypeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/asset-type")
public class AssetTypeController {

    @Autowired
    private AssetTypeService service;

    @RequirePagePermission(pageCode = "M2520")
    @GetMapping
    public List<AssetType> getAll() {
        return service.getAll();
    }

    @RequirePagePermission(pageCode = "M2520")
    @GetMapping("/active")
    public List<AssetType> getActive() {
        return service.getActive();
    }

    @RequirePagePermission(pageCode = "M2520")
    @GetMapping("/group/{groupId}")
    public List<AssetType> getByGroupId(@PathVariable Long groupId) {
        return service.getByGroupId(groupId);
    }

    @RequirePagePermission(pageCode = "M2520")
    @GetMapping("/{id}")
    public ResponseEntity<AssetType> getById(@PathVariable Long id) {
        return service.findById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @RequirePagePermission(pageCode = "M2520")
    @PostMapping
    public AssetType create(@RequestBody AssetType entity) {
        return service.save(entity);
    }

    @RequirePagePermission(pageCode = "M2520")
    @PutMapping("/{id}")
    public ResponseEntity<AssetType> update(@PathVariable Long id, @RequestBody AssetType entity) {
        return service.findById(id)
                .map(existing -> {
                    existing.setGroupId(entity.getGroupId());
                    existing.setType(entity.getType());
                    existing.setIsAutoGeneratedCode(entity.getIsAutoGeneratedCode());
                    existing.setTypePrefix(entity.getTypePrefix());
                    existing.setStatus(entity.getStatus());
                    return ResponseEntity.ok(service.save(existing));
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @RequirePagePermission(pageCode = "M2520")
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        return service.findById(id)
                .map(existing -> {
                    service.delete(id);
                    return ResponseEntity.ok().<Void>build();
                })
                .orElse(ResponseEntity.notFound().build());
    }
}
