-- ==============================================================================
-- Migration Script: V353.0 Create Asset Group, Type, and Sub Type Tables
-- Description: Creates ASSET_GROUP, ASSET_TYPE, and ASSET_SUB_TYPE tables and registers pages.
-- ==============================================================================

-- 1. Register Asset Submodule under Masters (mod_id = 1) if not exists
SET IDENTITY_INSERT bos_sub_modules ON;
IF NOT EXISTS (SELECT 1 FROM bos_sub_modules WHERE sub_mod_id = 70)
BEGIN
    INSERT INTO bos_sub_modules (sub_mod_id, mod_id, parent_sub_mod_id, sub_mod_code, sub_mod_name)
    VALUES (70, 1, NULL, 'M7000', 'Asset');
END
SET IDENTITY_INSERT bos_sub_modules OFF;
GO

-- 2. Register Pages in bos_pages
IF NOT EXISTS (SELECT 1 FROM bos_pages WHERE page_code = 'HR_AST')
BEGIN
    INSERT INTO bos_pages (mod_id, sub_mod_id, page_code, page_name, enabled, page_url, icon)
    VALUES (1, 70, 'HR_AST', 'Asset Collapse', 1, NULL, NULL);
END
GO

IF NOT EXISTS (SELECT 1 FROM bos_pages WHERE page_code = 'HR_AST_01')
BEGIN
    INSERT INTO bos_pages (mod_id, sub_mod_id, page_code, page_name, enabled, page_url, icon)
    VALUES (1, 70, 'HR_AST_01', 'Asset Group', 1, '/master/hr/asset/group', 'IconReportAnalytics');
END
GO

IF NOT EXISTS (SELECT 1 FROM bos_pages WHERE page_code = 'HR_AST_02')
BEGIN
    INSERT INTO bos_pages (mod_id, sub_mod_id, page_code, page_name, enabled, page_url, icon)
    VALUES (1, 70, 'HR_AST_02', 'Asset Type', 1, '/master/hr/asset/type', 'IconReportAnalytics');
END
GO

IF NOT EXISTS (SELECT 1 FROM bos_pages WHERE page_code = 'HR_AST_03')
BEGIN
    INSERT INTO bos_pages (mod_id, sub_mod_id, page_code, page_name, enabled, page_url, icon)
    VALUES (1, 70, 'HR_AST_03', 'Asset Sub Type', 1, '/master/hr/asset/subtype', 'IconReportAnalytics');
END
GO

-- 3. Grant default access permissions to all existing users
INSERT INTO bos_user_page_auth (user_id, page_id, sub_mod_id, mod_id, enable, read_acs, [write], delete_acs, export, approval, manager, additional1, additional2, add_task_enable)
SELECT 
    u.user_id, 
    p.page_id, 
    p.sub_mod_id, 
    p.mod_id, 
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1
FROM bos_pages p
CROSS JOIN ad_user_credential u
WHERE p.page_code IN ('HR_AST', 'HR_AST_01', 'HR_AST_02', 'HR_AST_03')
  AND NOT EXISTS (
      SELECT 1 FROM bos_user_page_auth a 
      WHERE a.user_id = u.user_id AND a.page_id = p.page_id
  );
GO

-- 4. Drop old tables if they exist to prevent schema pollution
IF OBJECT_ID('dbo.HR_ASSET_SUB_TYPE', 'U') IS NOT NULL DROP TABLE dbo.HR_ASSET_SUB_TYPE;
IF OBJECT_ID('dbo.HR_ASSET_TYPE', 'U') IS NOT NULL DROP TABLE dbo.HR_ASSET_TYPE;
IF OBJECT_ID('dbo.HR_ASSET_GROUP', 'U') IS NOT NULL DROP TABLE dbo.HR_ASSET_GROUP;
GO

-- 5. Create ASSET_GROUP table
IF OBJECT_ID('dbo.ASSET_GROUP', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ASSET_GROUP (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        GROUP_NAME NVARCHAR(100) NOT NULL,
        STATUS BIT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT PK_ASSET_GROUP PRIMARY KEY (ID),
        CONSTRAINT UQ_ASSET_GROUP_NAME UNIQUE (GROUP_NAME),
        CONSTRAINT FK_ASSET_GROUP_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_ASSET_GROUP_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
GO

-- 6. Create ASSET_TYPE table
IF OBJECT_ID('dbo.ASSET_TYPE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ASSET_TYPE (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        GROUP_ID BIGINT NOT NULL,
        TYPE NVARCHAR(100) NOT NULL,
        IS_AUTO_GENERATED_CODE BIT NOT NULL DEFAULT 0,
        TYPE_PREFIX NVARCHAR(10) NULL,
        STATUS BIT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT PK_ASSET_TYPE PRIMARY KEY (ID),
        CONSTRAINT UQ_ASSET_TYPE UNIQUE (TYPE),
        CONSTRAINT FK_ASSET_TYPE_GROUP FOREIGN KEY (GROUP_ID) REFERENCES ASSET_GROUP(ID),
        CONSTRAINT FK_ASSET_TYPE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_ASSET_TYPE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT CHK_ASSET_TYPE_PREFIX CHECK (IS_AUTO_GENERATED_CODE = 0 OR (IS_AUTO_GENERATED_CODE = 1 AND TYPE_PREFIX IS NOT NULL AND TYPE_PREFIX <> ''))
    );
    CREATE INDEX IX_ASSET_TYPE_GROUP ON ASSET_TYPE(GROUP_ID);
END
GO

-- 7. Create ASSET_SUB_TYPE table
IF OBJECT_ID('dbo.ASSET_SUB_TYPE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ASSET_SUB_TYPE (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        GROUP_ID BIGINT NOT NULL,
        TYPE_ID BIGINT NOT NULL,
        SUB_TYPE_NAME NVARCHAR(100) NOT NULL,
        STATUS BIT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT PK_ASSET_SUB_TYPE PRIMARY KEY (ID),
        CONSTRAINT UQ_ASSET_SUB_TYPE UNIQUE (SUB_TYPE_NAME),
        CONSTRAINT FK_ASSET_SUB_TYPE_GROUP FOREIGN KEY (GROUP_ID) REFERENCES ASSET_GROUP(ID),
        CONSTRAINT FK_ASSET_SUB_TYPE_TYPE FOREIGN KEY (TYPE_ID) REFERENCES ASSET_TYPE(ID),
        CONSTRAINT FK_ASSET_SUB_TYPE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_ASSET_SUB_TYPE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_ASSET_SUB_TYPE_GROUP ON ASSET_SUB_TYPE(GROUP_ID);
    CREATE INDEX IX_ASSET_SUB_TYPE_TYPE ON ASSET_SUB_TYPE(TYPE_ID);
END
GO

-- 8. Ensure Check Constraint on ASSET_TYPE exists
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CHK_ASSET_TYPE_PREFIX' AND parent_object_id = OBJECT_ID('dbo.ASSET_TYPE'))
BEGIN
    ALTER TABLE dbo.ASSET_TYPE ADD CONSTRAINT CHK_ASSET_TYPE_PREFIX CHECK (IS_AUTO_GENERATED_CODE = 0 OR (IS_AUTO_GENERATED_CODE = 1 AND TYPE_PREFIX IS NOT NULL AND TYPE_PREFIX <> ''));
END
GO

-- 9. Ensure Foreign Keys on ASSET_GROUP exist
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ASSET_GROUP_CREATED_BY' AND parent_object_id = OBJECT_ID('dbo.ASSET_GROUP'))
    ALTER TABLE dbo.ASSET_GROUP ADD CONSTRAINT FK_ASSET_GROUP_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ASSET_GROUP_UPDATED_BY' AND parent_object_id = OBJECT_ID('dbo.ASSET_GROUP'))
    ALTER TABLE dbo.ASSET_GROUP ADD CONSTRAINT FK_ASSET_GROUP_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);
GO

-- 10. Ensure Foreign Keys on ASSET_TYPE exist
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ASSET_TYPE_GROUP' AND parent_object_id = OBJECT_ID('dbo.ASSET_TYPE'))
    ALTER TABLE dbo.ASSET_TYPE ADD CONSTRAINT FK_ASSET_TYPE_GROUP FOREIGN KEY (GROUP_ID) REFERENCES dbo.ASSET_GROUP(ID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ASSET_TYPE_CREATED_BY' AND parent_object_id = OBJECT_ID('dbo.ASSET_TYPE'))
    ALTER TABLE dbo.ASSET_TYPE ADD CONSTRAINT FK_ASSET_TYPE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ASSET_TYPE_UPDATED_BY' AND parent_object_id = OBJECT_ID('dbo.ASSET_TYPE'))
    ALTER TABLE dbo.ASSET_TYPE ADD CONSTRAINT FK_ASSET_TYPE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);
GO

-- 11. Ensure Foreign Keys on ASSET_SUB_TYPE exist
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ASSET_SUB_TYPE_GROUP' AND parent_object_id = OBJECT_ID('dbo.ASSET_SUB_TYPE'))
    ALTER TABLE dbo.ASSET_SUB_TYPE ADD CONSTRAINT FK_ASSET_SUB_TYPE_GROUP FOREIGN KEY (GROUP_ID) REFERENCES dbo.ASSET_GROUP(ID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ASSET_SUB_TYPE_TYPE' AND parent_object_id = OBJECT_ID('dbo.ASSET_SUB_TYPE'))
    ALTER TABLE dbo.ASSET_SUB_TYPE ADD CONSTRAINT FK_ASSET_SUB_TYPE_TYPE FOREIGN KEY (TYPE_ID) REFERENCES dbo.ASSET_TYPE(ID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ASSET_SUB_TYPE_CREATED_BY' AND parent_object_id = OBJECT_ID('dbo.ASSET_SUB_TYPE'))
    ALTER TABLE dbo.ASSET_SUB_TYPE ADD CONSTRAINT FK_ASSET_SUB_TYPE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ASSET_SUB_TYPE_UPDATED_BY' AND parent_object_id = OBJECT_ID('dbo.ASSET_SUB_TYPE'))
    ALTER TABLE dbo.ASSET_SUB_TYPE ADD CONSTRAINT FK_ASSET_SUB_TYPE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);
GO
