-- ===================================================================================
-- Migration: 20260801_V1105.0__Seed_LOP_And_OT_Calculation_Preferences.sql
-- Module: HR / Payroll Calculation Policies (LOP & Overtime)
-- Purpose: Seed LOP_MODE, LOP_IS_FIXED, LOP_FIXED_AMOUNT, LOP_FORMULA,
--          OT_MODE, OT_IS_FIXED, OT_FIXED_AMOUNT, OT_FORMULA in AD_APP_PREFERENCE
-- ===================================================================================

-- 1. LOP (Loss of Pay) Preferences
IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'LOP_MODE')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LOP_MODE', 'FORMULA', 'Loss of Pay calculation mode: FORMULA or FIXED', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'LOP_IS_FIXED')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LOP_IS_FIXED', 'false', 'Flag indicating if LOP is fixed daily rate (true/false)', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'LOP_FIXED_AMOUNT')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LOP_FIXED_AMOUNT', '500.00', 'Fixed daily Loss of Pay deduction amount', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'LOP_FORMULA')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LOP_FORMULA', '(GROSS / TOTAL_DAYS) * LOP_DAYS', 'Loss of Pay calculation formula expression', 'HRA', 'SYSTEM', GETDATE());
END

-- 2. OT (Overtime) Preferences
IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OT_MODE')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('OT_MODE', 'FORMULA', 'Overtime calculation mode: FORMULA or FIXED', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OT_IS_FIXED')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('OT_IS_FIXED', 'false', 'Flag indicating if OT is fixed hourly rate (true/false)', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OT_FIXED_AMOUNT')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('OT_FIXED_AMOUNT', '150.00', 'Fixed hourly overtime rate amount', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OT_FORMULA')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('OT_FORMULA', '((BASIC / 26) / 8) * 1.5 * OT_HOURS', 'Overtime calculation formula expression', 'HRA', 'SYSTEM', GETDATE());
END
