CREATE TABLE PP_PURCHASE_SCHEDULE (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    SUPPLIER_ID BIGINT,
    PO_ID BIGINT,
    PO_ITEM_ID BIGINT,
    SCHEDULE_QTY DECIMAL(12,2),
    SCHEDULE_DATE DATETIME,
    RECEIVE_QTY DECIMAL(12,2) DEFAULT 0,
    ASN_QTY DECIMAL(12,2) DEFAULT 0,
    STATUS BIGINT,
    CREATED_BY NVARCHAR(50),
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    CONSTRAINT FK_PP_PURCHASE_SCHEDULE_STATUS FOREIGN KEY (STATUS) REFERENCES AD_STATUS_MASTER(ID),
    CONSTRAINT FK_PP_PURCHASE_SCHEDULE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_PP_PURCHASE_SCHEDULE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);
GO
