-- V1030.0: Rename HR_LEAVE_APPLICATION to HR_LEAVE_DETAILS and add WHERE_FROM column

-- 1. Rename table
IF OBJECT_ID('HR_LEAVE_APPLICATION', 'U') IS NOT NULL AND OBJECT_ID('HR_LEAVE_DETAILS', 'U') IS NULL
BEGIN
    EXEC sp_rename 'HR_LEAVE_APPLICATION', 'HR_LEAVE_DETAILS';
    PRINT 'Renamed HR_LEAVE_APPLICATION to HR_LEAVE_DETAILS';
END

-- 2. Add WHERE_FROM column
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_LEAVE_DETAILS' AND COLUMN_NAME = 'WHERE_FROM'
)
BEGIN
    ALTER TABLE HR_LEAVE_DETAILS ADD [WHERE_FROM] NVARCHAR(100) NULL;
    PRINT 'Added WHERE_FROM column to HR_LEAVE_DETAILS';
END
