-- ====================================================================================
-- Migration: Create Login Access Security Module Tables and Indexes (AD_ Prefix)
-- Version: V1168.0
-- Target Database: AT_NUTECH
-- Author: Senior Enterprise ERP Architect & Security Engineer
-- ====================================================================================

-- 1. Rename existing SEC_ tables to AD_ if they already exist
IF OBJECT_ID(N'[dbo].[SEC_LOGIN_ACCESS_CONFIG]', N'U') IS NOT NULL AND OBJECT_ID(N'[dbo].[AD_LOGIN_ACCESS_CONFIG]', N'U') IS NULL
BEGIN
    EXEC sp_rename N'[dbo].[SEC_LOGIN_ACCESS_CONFIG]', N'AD_LOGIN_ACCESS_CONFIG';
END;
GO

IF OBJECT_ID(N'[dbo].[SEC_ALLOWED_IP]', N'U') IS NOT NULL AND OBJECT_ID(N'[dbo].[AD_ALLOWED_IP]', N'U') IS NULL
BEGIN
    EXEC sp_rename N'[dbo].[SEC_ALLOWED_IP]', N'AD_ALLOWED_IP';
END;
GO

IF OBJECT_ID(N'[dbo].[SEC_ALLOWED_DEVICE]', N'U') IS NOT NULL AND OBJECT_ID(N'[dbo].[AD_ALLOWED_DEVICE]', N'U') IS NULL
BEGIN
    EXEC sp_rename N'[dbo].[SEC_ALLOWED_DEVICE]', N'AD_ALLOWED_DEVICE';
END;
GO

IF OBJECT_ID(N'[dbo].[SEC_LOGIN_ACCESS_LOG]', N'U') IS NOT NULL AND OBJECT_ID(N'[dbo].[AD_LOGIN_ACCESS_LOG]', N'U') IS NULL
BEGIN
    EXEC sp_rename N'[dbo].[SEC_LOGIN_ACCESS_LOG]', N'AD_LOGIN_ACCESS_LOG';
END;
GO

IF OBJECT_ID(N'[dbo].[SEC_LOGIN_SECURITY_AUDIT]', N'U') IS NOT NULL AND OBJECT_ID(N'[dbo].[AD_LOGIN_SECURITY_AUDIT]', N'U') IS NULL
BEGIN
    EXEC sp_rename N'[dbo].[SEC_LOGIN_SECURITY_AUDIT]', N'AD_LOGIN_SECURITY_AUDIT';
END;
GO

-- 2. AD_LOGIN_ACCESS_CONFIG: Company-level Login Security configuration
IF OBJECT_ID(N'[dbo].[AD_LOGIN_ACCESS_CONFIG]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AD_LOGIN_ACCESS_CONFIG] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [COMPANY_ID] BIGINT NOT NULL,
        [SECURITY_ENABLED] BIT NOT NULL CONSTRAINT [DF_AD_SEC_CONFIG_ENABLED] DEFAULT 0,
        [ACCESS_CONTROL_METHOD] NVARCHAR(50) NOT NULL CONSTRAINT [DF_AD_SEC_CONFIG_METHOD] DEFAULT 'IP', -- 'IP', 'DEVICE', 'IP_DEVICE'
        [STATUS] BIT NOT NULL CONSTRAINT [DF_AD_SEC_CONFIG_STATUS] DEFAULT 1,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL CONSTRAINT [DF_AD_SEC_CONFIG_CR_DATE] DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_AD_LOGIN_ACCESS_CONFIG] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [UQ_AD_LOGIN_ACCESS_CONFIG_COMPANY] UNIQUE NONCLUSTERED ([COMPANY_ID] ASC)
    );

    IF OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]', N'U') IS NOT NULL
    BEGIN
        ALTER TABLE [dbo].[AD_LOGIN_ACCESS_CONFIG] WITH CHECK
            ADD CONSTRAINT [FK_AD_SEC_CONFIG_COMPANY] FOREIGN KEY ([COMPANY_ID]) REFERENCES [dbo].[AD_COMPANY_CREDENTIAL] ([ID]) ON DELETE CASCADE;
    END;
END
ELSE
BEGIN
    -- Idempotent column check: Ensure STATUS is BIT
    IF EXISTS (
        SELECT 1 FROM sys.columns c
        JOIN sys.tables t ON c.object_id = t.object_id
        JOIN sys.types ty ON c.user_type_id = ty.user_type_id
        WHERE t.name = 'AD_LOGIN_ACCESS_CONFIG' AND c.name = 'STATUS' AND ty.name IN ('nvarchar', 'varchar')
    )
    BEGIN
        DECLARE @defConfigName NVARCHAR(256);
        SELECT @defConfigName = d.name FROM sys.default_constraints d
        JOIN sys.columns c ON d.parent_column_id = c.column_id AND d.parent_object_id = c.object_id
        WHERE d.parent_object_id = OBJECT_ID('AD_LOGIN_ACCESS_CONFIG') AND c.name = 'STATUS';
        IF @defConfigName IS NOT NULL
            EXEC('ALTER TABLE [dbo].[AD_LOGIN_ACCESS_CONFIG] DROP CONSTRAINT [' + @defConfigName + ']');

        EXEC('UPDATE [dbo].[AD_LOGIN_ACCESS_CONFIG] SET [STATUS] = CASE WHEN UPPER(TRIM([STATUS])) = ''ACTIVE'' OR [STATUS] = ''1'' THEN 1 ELSE 0 END');
        ALTER TABLE [dbo].[AD_LOGIN_ACCESS_CONFIG] ALTER COLUMN [STATUS] BIT NOT NULL;
        ALTER TABLE [dbo].[AD_LOGIN_ACCESS_CONFIG] ADD CONSTRAINT [DF_AD_SEC_CONFIG_STATUS] DEFAULT 1 FOR [STATUS];
    END;
END;
GO

-- 3. AD_ALLOWED_IP: Allowed IP Addresses per Company
IF OBJECT_ID(N'[dbo].[AD_ALLOWED_IP]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AD_ALLOWED_IP] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [COMPANY_ID] BIGINT NOT NULL,
        [IP_ADDRESS] NVARCHAR(100) NOT NULL,
        [DESCRIPTION] NVARCHAR(255) NULL,
        [STATUS] BIT NOT NULL CONSTRAINT [DF_AD_ALLOWED_IP_STATUS] DEFAULT 1,
        [VALID_FROM] DATETIME NULL,
        [VALID_TO] DATETIME NULL,
        [REMARKS] NVARCHAR(500) NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL CONSTRAINT [DF_AD_ALLOWED_IP_CR_DATE] DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_AD_ALLOWED_IP] PRIMARY KEY CLUSTERED ([ID] ASC)
    );

    IF OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]', N'U') IS NOT NULL
    BEGIN
        ALTER TABLE [dbo].[AD_ALLOWED_IP] WITH CHECK
            ADD CONSTRAINT [FK_AD_ALLOWED_IP_COMPANY] FOREIGN KEY ([COMPANY_ID]) REFERENCES [dbo].[AD_COMPANY_CREDENTIAL] ([ID]) ON DELETE CASCADE;
    END;
END
ELSE
BEGIN
    -- Idempotent column check: Ensure STATUS is BIT
    IF EXISTS (
        SELECT 1 FROM sys.columns c
        JOIN sys.tables t ON c.object_id = t.object_id
        JOIN sys.types ty ON c.user_type_id = ty.user_type_id
        WHERE t.name = 'AD_ALLOWED_IP' AND c.name = 'STATUS' AND ty.name IN ('nvarchar', 'varchar')
    )
    BEGIN
        DECLARE @defIpName NVARCHAR(256);
        SELECT @defIpName = d.name FROM sys.default_constraints d
        JOIN sys.columns c ON d.parent_column_id = c.column_id AND d.parent_object_id = c.object_id
        WHERE d.parent_object_id = OBJECT_ID('AD_ALLOWED_IP') AND c.name = 'STATUS';
        IF @defIpName IS NOT NULL
            EXEC('ALTER TABLE [dbo].[AD_ALLOWED_IP] DROP CONSTRAINT [' + @defIpName + ']');

        IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AD_ALLOWED_IP_COMP_IP' AND object_id = OBJECT_ID('AD_ALLOWED_IP'))
            DROP INDEX [IDX_AD_ALLOWED_IP_COMP_IP] ON [dbo].[AD_ALLOWED_IP];

        EXEC('UPDATE [dbo].[AD_ALLOWED_IP] SET [STATUS] = CASE WHEN UPPER(TRIM([STATUS])) = ''ACTIVE'' OR [STATUS] = ''1'' THEN 1 ELSE 0 END');
        ALTER TABLE [dbo].[AD_ALLOWED_IP] ALTER COLUMN [STATUS] BIT NOT NULL;
        ALTER TABLE [dbo].[AD_ALLOWED_IP] ADD CONSTRAINT [DF_AD_ALLOWED_IP_STATUS] DEFAULT 1 FOR [STATUS];
    END;
END;
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'IDX_AD_ALLOWED_IP_COMP_IP' AND object_id = OBJECT_ID(N'[dbo].[AD_ALLOWED_IP]'))
BEGIN
    CREATE NONCLUSTERED INDEX [IDX_AD_ALLOWED_IP_COMP_IP]
        ON [dbo].[AD_ALLOWED_IP] ([COMPANY_ID] ASC, [IP_ADDRESS] ASC, [STATUS] ASC);
END;
GO

-- 4. AD_ALLOWED_DEVICE: Registered / Authorized Devices per Company
IF OBJECT_ID(N'[dbo].[AD_ALLOWED_DEVICE]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AD_ALLOWED_DEVICE] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [COMPANY_ID] BIGINT NOT NULL,
        [DEVICE_CODE] NVARCHAR(50) NOT NULL,
        [DEVICE_NAME] NVARCHAR(100) NOT NULL,
        [DEVICE_IDENTIFIER] NVARCHAR(255) NOT NULL,
        [MAC_ADDRESS] NVARCHAR(100) NULL,
        [IP_ADDRESS] NVARCHAR(100) NULL,
        [USER_ID] NVARCHAR(50) NULL,
        [STATUS] BIT NOT NULL CONSTRAINT [DF_AD_ALLOWED_DEVICE_STATUS] DEFAULT 1,
        [VALID_FROM] DATETIME NULL,
        [VALID_TO] DATETIME NULL,
        [REMARKS] NVARCHAR(500) NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL CONSTRAINT [DF_AD_ALLOWED_DEVICE_CR_DATE] DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_AD_ALLOWED_DEVICE] PRIMARY KEY CLUSTERED ([ID] ASC)
    );

    IF OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]', N'U') IS NOT NULL
    BEGIN
        ALTER TABLE [dbo].[AD_ALLOWED_DEVICE] WITH CHECK
            ADD CONSTRAINT [FK_AD_ALLOWED_DEVICE_COMPANY] FOREIGN KEY ([COMPANY_ID]) REFERENCES [dbo].[AD_COMPANY_CREDENTIAL] ([ID]) ON DELETE CASCADE;
    END;
END
ELSE
BEGIN
    -- Idempotent column check: Ensure STATUS is BIT
    IF EXISTS (
        SELECT 1 FROM sys.columns c
        JOIN sys.tables t ON c.object_id = t.object_id
        JOIN sys.types ty ON c.user_type_id = ty.user_type_id
        WHERE t.name = 'AD_ALLOWED_DEVICE' AND c.name = 'STATUS' AND ty.name IN ('nvarchar', 'varchar')
    )
    BEGIN
        DECLARE @defDevName NVARCHAR(256);
        SELECT @defDevName = d.name FROM sys.default_constraints d
        JOIN sys.columns c ON d.parent_column_id = c.column_id AND d.parent_object_id = c.object_id
        WHERE d.parent_object_id = OBJECT_ID('AD_ALLOWED_DEVICE') AND c.name = 'STATUS';
        IF @defDevName IS NOT NULL
            EXEC('ALTER TABLE [dbo].[AD_ALLOWED_DEVICE] DROP CONSTRAINT [' + @defDevName + ']');

        IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AD_ALLOWED_DEVICE_LOOKUP' AND object_id = OBJECT_ID('AD_ALLOWED_DEVICE'))
            DROP INDEX [IDX_AD_ALLOWED_DEVICE_LOOKUP] ON [dbo].[AD_ALLOWED_DEVICE];
        IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AD_ALLOWED_DEVICE_MAC' AND object_id = OBJECT_ID('AD_ALLOWED_DEVICE'))
            DROP INDEX [IDX_AD_ALLOWED_DEVICE_MAC] ON [dbo].[AD_ALLOWED_DEVICE];

        EXEC('UPDATE [dbo].[AD_ALLOWED_DEVICE] SET [STATUS] = CASE WHEN UPPER(TRIM([STATUS])) = ''ACTIVE'' OR [STATUS] = ''1'' THEN 1 ELSE 0 END');
        ALTER TABLE [dbo].[AD_ALLOWED_DEVICE] ALTER COLUMN [STATUS] BIT NOT NULL;
        ALTER TABLE [dbo].[AD_ALLOWED_DEVICE] ADD CONSTRAINT [DF_AD_ALLOWED_DEVICE_STATUS] DEFAULT 1 FOR [STATUS];
    END;
END;
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'IDX_AD_ALLOWED_DEVICE_LOOKUP' AND object_id = OBJECT_ID(N'[dbo].[AD_ALLOWED_DEVICE]'))
BEGIN
    CREATE NONCLUSTERED INDEX [IDX_AD_ALLOWED_DEVICE_LOOKUP]
        ON [dbo].[AD_ALLOWED_DEVICE] ([COMPANY_ID] ASC, [DEVICE_IDENTIFIER] ASC, [STATUS] ASC);
END;
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'IDX_AD_ALLOWED_DEVICE_MAC' AND object_id = OBJECT_ID(N'[dbo].[AD_ALLOWED_DEVICE]'))
BEGIN
    CREATE NONCLUSTERED INDEX [IDX_AD_ALLOWED_DEVICE_MAC]
        ON [dbo].[AD_ALLOWED_DEVICE] ([COMPANY_ID] ASC, [MAC_ADDRESS] ASC, [STATUS] ASC)
        WHERE [MAC_ADDRESS] IS NOT NULL;
END;
GO

-- 5. AD_LOGIN_ACCESS_LOG: Login Security Attempt Audit Log
IF OBJECT_ID(N'[dbo].[AD_LOGIN_ACCESS_LOG]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AD_LOGIN_ACCESS_LOG] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [USER_ID] NVARCHAR(50) NULL,
        [USERNAME] NVARCHAR(100) NULL,
        [COMPANY_ID] BIGINT NULL,
        [LOGIN_DATE_TIME] DATETIME NOT NULL CONSTRAINT [DF_AD_SEC_LOG_DATE] DEFAULT GETDATE(),
        [SOURCE_IP] NVARCHAR(100) NULL,
        [DEVICE_IDENTIFIER] NVARCHAR(255) NULL,
        [MAC_ADDRESS] NVARCHAR(100) NULL,
        [ACCESS_CONTROL_METHOD] NVARCHAR(50) NULL,
        [LOGIN_STATUS] NVARCHAR(50) NOT NULL, -- 'ALLOWED', 'BLOCKED'
        [FAILURE_REASON] NVARCHAR(100) NULL,
        [USER_AGENT] NVARCHAR(500) NULL,
        [CREATED_DATE] DATETIME NOT NULL CONSTRAINT [DF_AD_SEC_LOG_CR_DATE] DEFAULT GETDATE(),
        CONSTRAINT [PK_AD_LOGIN_ACCESS_LOG] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END;
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'IDX_AD_LOGIN_ACCESS_LOG_COMP_DATE' AND object_id = OBJECT_ID(N'[dbo].[AD_LOGIN_ACCESS_LOG]'))
BEGIN
    CREATE NONCLUSTERED INDEX [IDX_AD_LOGIN_ACCESS_LOG_COMP_DATE]
        ON [dbo].[AD_LOGIN_ACCESS_LOG] ([COMPANY_ID] ASC, [LOGIN_DATE_TIME] DESC);
END;
GO

-- 6. AD_LOGIN_SECURITY_AUDIT: Configuration Change Audit Trail
IF OBJECT_ID(N'[dbo].[AD_LOGIN_SECURITY_AUDIT]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AD_LOGIN_SECURITY_AUDIT] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [COMPANY_ID] BIGINT NOT NULL,
        [ACTION] NVARCHAR(100) NOT NULL,
        [OLD_VALUE] NVARCHAR(MAX) NULL,
        [NEW_VALUE] NVARCHAR(MAX) NULL,
        [REMARKS] NVARCHAR(500) NULL,
        [CHANGED_BY] NVARCHAR(50) NOT NULL,
        [CHANGED_DATE] DATETIME NOT NULL CONSTRAINT [DF_AD_SEC_AUDIT_DATE] DEFAULT GETDATE(),
        CONSTRAINT [PK_AD_LOGIN_SECURITY_AUDIT] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END;
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'IDX_AD_LOGIN_SECURITY_AUDIT_COMP' AND object_id = OBJECT_ID(N'[dbo].[AD_LOGIN_SECURITY_AUDIT]'))
BEGIN
    CREATE NONCLUSTERED INDEX [IDX_AD_LOGIN_SECURITY_AUDIT_COMP]
        ON [dbo].[AD_LOGIN_SECURITY_AUDIT] ([COMPANY_ID] ASC, [CHANGED_DATE] DESC);
END;
GO
