-- =======================================================================================
-- MIGRATION SCRIPT: Add missing columns to Gate Entry Head
-- DB TYPE: Microsoft SQL Server
-- VERSION: 1093.1
-- =======================================================================================

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PP_GATE_ENTRY_HEAD' AND COLUMN_NAME = 'VEHICLE_NO')
BEGIN
    ALTER TABLE PP_GATE_ENTRY_HEAD ADD VEHICLE_NO NVARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PP_GATE_ENTRY_HEAD' AND COLUMN_NAME = 'LR_NO')
BEGIN
    ALTER TABLE PP_GATE_ENTRY_HEAD ADD LR_NO NVARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PP_GATE_ENTRY_HEAD' AND COLUMN_NAME = 'LR_DATE')
BEGIN
    ALTER TABLE PP_GATE_ENTRY_HEAD ADD LR_DATE DATE NULL;
END
GO
