-- ==============================================================================
-- Migration Script: V357.0 Create QMT Machine Criterial Spares Table
-- Description: Creates QMT_MACHINE_CRITERIAL_SPARES child table.
-- ==============================================================================

-- 1. Create QMT_MACHINE_CRITERIAL_SPARES table
IF OBJECT_ID('QMT_MACHINE_CRITERIAL_SPARES', 'U') IS NULL
BEGIN
    CREATE TABLE QMT_MACHINE_CRITERIAL_SPARES (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        MACHINE_ID BIGINT NOT NULL,
        ITEM_CODE NVARCHAR(50) NOT NULL,
        ITEM_NAME NVARCHAR(100) NOT NULL,
        SUPPLIER NVARCHAR(100) NULL,
        RATE DECIMAL(18,2) NULL,
        QTY INT NULL,
        UOM NVARCHAR(30) NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT PK_QMT_MACHINE_CRITERIAL_SPARES PRIMARY KEY (ID),
        CONSTRAINT FK_QMT_MACHINE_CRITERIAL_SPARES_MACHINE_ID FOREIGN KEY (MACHINE_ID) REFERENCES QMT_MACHINE(ID) ON DELETE CASCADE,
        CONSTRAINT FK_QMT_MACHINE_CRITERIAL_SPARES_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_QMT_MACHINE_CRITERIAL_SPARES_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_QMT_MACHINE_CRITERIAL_SPARES_MACHINE_ID ON QMT_MACHINE_CRITERIAL_SPARES(MACHINE_ID);
END
GO
