-- Create SM_INVOICE_ADD_CHARGES table
IF OBJECT_ID('SM_INVOICE_ADD_CHARGES', 'U') IS NULL
BEGIN
    CREATE TABLE SM_INVOICE_ADD_CHARGES (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        INVOICE_REF_ID BIGINT NOT NULL,
        CHARGES_ID BIGINT NULL,
        AMOUNT NUMERIC(12,2) NULL,
        TAX_APPLICABLE BIT NULL DEFAULT 0,
        CGST_PER NUMERIC(12,2) NULL,
        CGST_VALUE NUMERIC(12,2) NULL,
        SGST_PER NUMERIC(12,2) NULL,
        SGST_VALUE NUMERIC(12,2) NULL,
        IGST_PER NUMERIC(12,2) NULL,
        IGST_VALUE NUMERIC(12,2) NULL,
        TOTAL_VALUE NUMERIC(12,2) NULL,
        STATUS BIT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NULL,
        CREATED_DATE DATETIME NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_SM_INVOICE_ADD_CHARGES_INVOICE FOREIGN KEY (INVOICE_REF_ID) REFERENCES SM_INVOICE_HEADER(ID) ON DELETE CASCADE,
        CONSTRAINT FK_SM_INVOICE_ADD_CHARGES_MASTER FOREIGN KEY (CHARGES_ID) REFERENCES SM_ADDITIONAL_CHARGES(ID),
        CONSTRAINT FK_SM_INV_CHARGES_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SM_INV_CHARGES_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
GO

-- Add ROUND_OFF and ADDITIONAL_CHARGES columns to SM_INVOICE_HEADER table
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SM_INVOICE_HEADER') AND name = 'ROUND_OFF')
BEGIN
    ALTER TABLE SM_INVOICE_HEADER ADD ROUND_OFF NUMERIC(12, 2) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SM_INVOICE_HEADER') AND name = 'ADDITIONAL_CHARGES')
BEGIN
    ALTER TABLE SM_INVOICE_HEADER ADD ADDITIONAL_CHARGES NUMERIC(12, 2) NULL;
END
GO
