-- Alter table SCHEDULE_CONFIGURATION to add standard audit columns and ACTIVE_STATUS to comply with SOP Rule 16
-- Created: 2026-07-02

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[SCHEDULE_CONFIGURATION]') AND name = 'CREATED_BY')
BEGIN
    ALTER TABLE [dbo].[SCHEDULE_CONFIGURATION] ADD [CREATED_BY] VARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[SCHEDULE_CONFIGURATION]') AND name = 'CREATED_DATE')
BEGIN
    ALTER TABLE [dbo].[SCHEDULE_CONFIGURATION] ADD [CREATED_DATE] DATETIME NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[SCHEDULE_CONFIGURATION]') AND name = 'UPDATED_BY')
BEGIN
    ALTER TABLE [dbo].[SCHEDULE_CONFIGURATION] ADD [UPDATED_BY] VARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[SCHEDULE_CONFIGURATION]') AND name = 'UPDATED_DATE')
BEGIN
    ALTER TABLE [dbo].[SCHEDULE_CONFIGURATION] ADD [UPDATED_DATE] DATETIME NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[SCHEDULE_CONFIGURATION]') AND name = 'ACTIVE_STATUS')
BEGIN
    ALTER TABLE [dbo].[SCHEDULE_CONFIGURATION] ADD [ACTIVE_STATUS] VARCHAR(20) NULL;
END
GO

-- Seed default values for existing records
UPDATE [dbo].[SCHEDULE_CONFIGURATION]
SET [CREATED_BY] = 'SYSTEM',
    [CREATED_DATE] = GETDATE(),
    [ACTIVE_STATUS] = 'Active'
WHERE [CREATED_BY] IS NULL;
GO
