
IF OBJECT_ID('FA_FINANACE_OUTSTANDING', 'U') IS NULL
BEGIN
    CREATE TABLE FA_FINANACE_OUTSTANDING (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        TRANS_DATE DATETIME NOT NULL,
        TRANS_TYPE NVARCHAR(50) NOT NULL,
        PARTY_ID bigint NOT NULL ,
        VR_NO NVARCHAR(50) NOT NULL,
        PARTY_BILL_NO NVARCHAR(50) NOT NULL,
        PARTY_BILL_DATE DATE NOT NULL,
        DR_AMT NUMERIC(18,2),
        CR_AMT NUMERIC(18,2),
        CHEQUE_NO NVARCHAR(50),
        CHEQUE_DATE DATE,
        ON_ACCOUNT BIT DEFAULT 0,
        STATUS bigint NOT NULL,
        DIVISION bigint NOT NULL,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME,
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME,
        CONSTRAINT FK_FA_OUTSTANDING_PARTY FOREIGN KEY (PARTY_ID) REFERENCES FA_ACCOUNT_LEDGER(ID),
        CONSTRAINT FK_FA_OUTSTANDING_STATUS FOREIGN KEY (STATUS) REFERENCES AD_STATUS_MASTER(ID),
        CONSTRAINT FK_FA_OUTSTANDING_DIVISION FOREIGN KEY (DIVISION) REFERENCES AD_DIVISION(ID),
        CONSTRAINT FK_FA_OUTSTANDING_CB FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_FA_OUTSTANDING_UB FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_FA_OUTSTANDING_PARTY' AND object_id = OBJECT_ID('FA_FINANACE_OUTSTANDING'))
BEGIN
    CREATE INDEX IX_FA_OUTSTANDING_PARTY ON FA_FINANACE_OUTSTANDING(PARTY_ID);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_FA_OUTSTANDING_BILL' AND object_id = OBJECT_ID('FA_FINANACE_OUTSTANDING'))
BEGIN
    CREATE INDEX IX_FA_OUTSTANDING_BILL ON FA_FINANACE_OUTSTANDING(PARTY_BILL_NO);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_FA_OUTSTANDING_DIV' AND object_id = OBJECT_ID('FA_FINANACE_OUTSTANDING'))
BEGIN
    CREATE INDEX IX_FA_OUTSTANDING_DIV ON FA_FINANACE_OUTSTANDING(DIVISION);
END
GO



IF OBJECT_ID('FA_FINANACE_TRANSACTION', 'U') IS NULL
BEGIN
    CREATE TABLE FA_FINANACE_TRANSACTION (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        TRANS_DATE DATETIME NOT NULL,
        TRANS_TYPE NVARCHAR(50) NOT NULL,
        REF_ID INT,
        VR_NAME NVARCHAR(50) NOT NULL,
        VR_NO NVARCHAR(50) NOT NULL,
        HEAD_ID bigint NOT NULL,
        HEAD_NAME NVARCHAR(250) NOT NULL,
        DR_AMT NUMERIC(18,2),
        CR_AMT NUMERIC(18,2),
        TAXABLE_AMT NUMERIC(18,2),
        BILL_AMT NUMERIC(18,2),
        NARRATION NVARCHAR(500),
        PARTY_BILL_NO NVARCHAR(50),
        PARTY_BILL_DATE DATE,
        TRANS_MODE NVARCHAR(50),
        CHEQUE_NO NVARCHAR(50),
        CHEQUE_DATE DATE,
        DUE_DATE DATE,
        PARTY_ID bigint NOT NULL,
        RECO_DONE BIT DEFAULT 0,
        BILL_OUTSTANDING_ID BIGINT,
        DIVISION bigint NOT NULL,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME,
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME,
        CONSTRAINT FK_FA_TRANS_HEAD FOREIGN KEY (HEAD_ID) REFERENCES FA_ACCOUNT_LEDGER(ID),
        CONSTRAINT FK_FA_TRANS_PARTY FOREIGN KEY (PARTY_ID) REFERENCES FA_ACCOUNT_LEDGER(ID),
        CONSTRAINT FK_FA_TRANS_OUTSTANDING FOREIGN KEY (BILL_OUTSTANDING_ID) REFERENCES FA_FINANACE_OUTSTANDING(ID),
        CONSTRAINT FK_FA_TRANS_DIVISION FOREIGN KEY (DIVISION) REFERENCES AD_DIVISION(ID),
        CONSTRAINT FK_FA_TRANS_CB FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_FA_TRANS_UB FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_FA_TRANS_PARTY' AND object_id = OBJECT_ID('FA_FINANACE_TRANSACTION'))
BEGIN
    CREATE INDEX IX_FA_TRANS_PARTY ON FA_FINANACE_TRANSACTION(PARTY_ID);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_FA_TRANS_TYPE' AND object_id = OBJECT_ID('FA_FINANACE_TRANSACTION'))
BEGIN
    CREATE INDEX IX_FA_TRANS_TYPE ON FA_FINANACE_TRANSACTION(TRANS_TYPE);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_FA_TRANS_DIV' AND object_id = OBJECT_ID('FA_FINANACE_TRANSACTION'))
BEGIN
    CREATE INDEX IX_FA_TRANS_DIV ON FA_FINANACE_TRANSACTION(DIVISION);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_FA_TRANS_OUT' AND object_id = OBJECT_ID('FA_FINANACE_TRANSACTION'))
BEGIN
    CREATE INDEX IX_FA_TRANS_OUT ON FA_FINANACE_TRANSACTION(BILL_OUTSTANDING_ID);
END
GO
