-- Index on HR_EMPLOYEE_MANAGER_MAPPING
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_EMPLOYEE_MANAGER_MAPPING_VERTICAL_HEAD_ID' AND object_id = OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING'))
    CREATE INDEX IX_HR_EMPLOYEE_MANAGER_MAPPING_VERTICAL_HEAD_ID ON HR_EMPLOYEE_MANAGER_MAPPING (VERTICAL_HEAD_ID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_EMPLOYEE_MANAGER_MAPPING_HOME_MANAGER_ID' AND object_id = OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING'))
    CREATE INDEX IX_HR_EMPLOYEE_MANAGER_MAPPING_HOME_MANAGER_ID ON HR_EMPLOYEE_MANAGER_MAPPING (HOME_MANAGER_ID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_EMPLOYEE_MANAGER_MAPPING_BUSINESS_MANAGER_ID' AND object_id = OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING'))
    CREATE INDEX IX_HR_EMPLOYEE_MANAGER_MAPPING_BUSINESS_MANAGER_ID ON HR_EMPLOYEE_MANAGER_MAPPING (BUSINESS_MANAGER_ID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_EMPLOYEE_MANAGER_MAPPING_HR_ID' AND object_id = OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING'))
    CREATE INDEX IX_HR_EMPLOYEE_MANAGER_MAPPING_HR_ID ON HR_EMPLOYEE_MANAGER_MAPPING (HR_ID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_EMPLOYEE_MANAGER_MAPPING_STATUS' AND object_id = OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING'))
    CREATE INDEX IX_HR_EMPLOYEE_MANAGER_MAPPING_STATUS ON HR_EMPLOYEE_MANAGER_MAPPING (STATUS);

-- Index on AD_USER_COMPANY_MAPPING
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_AD_USER_COMPANY_MAPPING_COMPANY_ID' AND object_id = OBJECT_ID('AD_USER_COMPANY_MAPPING'))
    CREATE INDEX IX_AD_USER_COMPANY_MAPPING_COMPANY_ID ON AD_USER_COMPANY_MAPPING (COMPANY_ID);

-- Index on BOS_PDF_TEMPLATE
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_BOS_PDF_TEMPLATE_COMPANY_ID' AND object_id = OBJECT_ID('BOS_PDF_TEMPLATE'))
    CREATE INDEX IX_BOS_PDF_TEMPLATE_COMPANY_ID ON BOS_PDF_TEMPLATE (COMPANY_ID);
