-- Add new configuration columns to existing QMT_MACHINE_INTEGRATION table

-- Read column selection (ordered comma-separated)
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'READ_COLUMNS')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD READ_COLUMNS NVARCHAR(2000) NULL;
END
GO

-- SQL query to run on our internal DB for SEND jobs
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'SEND_SQL_QUERY')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD SEND_SQL_QUERY NVARCHAR(MAX) NULL;
END
GO

-- Write mode: TABLE or FILE
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'WRITE_MODE')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD WRITE_MODE NVARCHAR(10) NOT NULL DEFAULT 'TABLE';
END
GO

-- Target: table name (TABLE mode) or file path (FILE mode)
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'TARGET_DESTINATION')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD TARGET_DESTINATION NVARCHAR(1000) NULL;
END
GO

-- Schedule: is auto-sync enabled?
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'SCHEDULE_ENABLED')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD SCHEDULE_ENABLED BIT NOT NULL DEFAULT 0;
END
GO

-- Schedule: interval in seconds (e.g. 30, 60, 300)
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'SCHEDULE_INTERVAL_SECONDS')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD SCHEDULE_INTERVAL_SECONDS INT NOT NULL DEFAULT 60;
END
GO

-- Last time the scheduler ran this integration
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'LAST_RUN_DATE')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD LAST_RUN_DATE DATETIME NULL;
END
GO

-- Add Read Scheduler columns to QMT_MACHINE_INTEGRATION

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'READ_SCHEDULE_ENABLED')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD READ_SCHEDULE_ENABLED BIT NOT NULL DEFAULT 0;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'READ_SCHEDULE_INTERVAL_SECONDS')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD READ_SCHEDULE_INTERVAL_SECONDS INT NOT NULL DEFAULT 60;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'READ_LAST_RUN_DATE')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD READ_LAST_RUN_DATE DATETIME NULL;
END
GO

-- Migration Script: V1156.0 Alter Machine Integration to add Custom Read Query support

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'READ_SQL_QUERY')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD READ_SQL_QUERY NVARCHAR(MAX) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'QMT_MACHINE_INTEGRATION') AND name = 'CUSTOM_READ_QUERY_ENABLED')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD CUSTOM_READ_QUERY_ENABLED BIT NOT NULL DEFAULT 0;
END
GO


