-- V1027.0: Remove LEAVE_STATUS column from HR_LEAVE_APPLICATION

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_LEAVE_APPLICATION' AND COLUMN_NAME = 'LEAVE_STATUS'
)
BEGIN
    ALTER TABLE HR_LEAVE_APPLICATION DROP COLUMN [LEAVE_STATUS];
    PRINT 'Dropped LEAVE_STATUS column from HR_LEAVE_APPLICATION';
END
