-- SQL Migration: 20260725_V1060.0__Create_CLI_NOTIFICATION_MASTER_And_LOG.sql

-- 1. Create CLI_NOTIFICATION_MASTER Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLI_NOTIFICATION_MASTER]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[CLI_NOTIFICATION_MASTER] (
        [NOTIFICATION_ID] BIGINT IDENTITY(1,1) NOT NULL,
        [TITLE] NVARCHAR(200) NOT NULL,
        [MESSAGE] NVARCHAR(MAX) NOT NULL,
        [TYPE] VARCHAR(50) NOT NULL, -- INFORMATION, ALERT, WARNING, CRITICAL, MAINTENANCE, BUILD_UPDATE, WISHES
        [PRIORITY] VARCHAR(20) NOT NULL, -- LOW, MEDIUM, HIGH, URGENT
        [COLOR_HEX] VARCHAR(20) NOT NULL,
        [ICON_NAME] VARCHAR(50) NOT NULL,
        [TARGET_TYPE] VARCHAR(20) NOT NULL, -- ALL_CLIENTS, SELECTED_CLIENTS
        [TARGET_CLIENT_CODES] NVARCHAR(MAX) NULL, -- Comma-separated list or JSON array of target Client Codes
        [START_DATE_TIME] DATETIME2 NOT NULL,
        [END_DATE_TIME] DATETIME2 NOT NULL,
        [STATUS] VARCHAR(20) NOT NULL, -- DRAFT, SCHEDULED, ACTIVE, EXPIRED, CANCELLED
        [IS_MANDATORY_ACK] BIT NOT NULL DEFAULT 0,
        [CREATED_BY] NVARCHAR(100) NULL,
        [CREATED_DATE] DATETIME2 NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(100) NULL,
        [UPDATED_DATE] DATETIME2 NULL,
        CONSTRAINT [PK_CLI_NOTIFICATION_MASTER] PRIMARY KEY CLUSTERED ([NOTIFICATION_ID] ASC)
    );
END
GO

-- 2. Create CLI_NOTIFICATION_LOG Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLI_NOTIFICATION_LOG]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[CLI_NOTIFICATION_LOG] (
        [LOG_ID] BIGINT IDENTITY(1,1) NOT NULL,
        [NOTIFICATION_ID] BIGINT NOT NULL,
        [CLIENT_CODE] NVARCHAR(50) NOT NULL,
        [USER_ID] NVARCHAR(100) NULL,
        [VIEWED_AT] DATETIME2 NULL,
        [ACKNOWLEDGED_AT] DATETIME2 NULL,
        [STATUS] VARCHAR(20) NOT NULL, -- DELIVERED, VIEWED, ACKNOWLEDGED
        [CREATED_DATE] DATETIME2 NOT NULL DEFAULT GETDATE(),
        CONSTRAINT [PK_CLI_NOTIFICATION_LOG] PRIMARY KEY CLUSTERED ([LOG_ID] ASC),
        CONSTRAINT [FK_CLI_NOTIFICATION_LOG_MASTER] FOREIGN KEY ([NOTIFICATION_ID]) REFERENCES [dbo].[CLI_NOTIFICATION_MASTER] ([NOTIFICATION_ID]) ON DELETE CASCADE
    );
END
GO

-- 3. Create Indexes for High Performance Scheduler & Querying
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_CLI_NOTIFICATION_MASTER_STATUS_DATES')
BEGIN
    CREATE INDEX [IX_CLI_NOTIFICATION_MASTER_STATUS_DATES] ON [dbo].[CLI_NOTIFICATION_MASTER] ([STATUS], [START_DATE_TIME], [END_DATE_TIME]);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_CLI_NOTIFICATION_LOG_NOTIFICATION_CLIENT')
BEGIN
    CREATE INDEX [IX_CLI_NOTIFICATION_LOG_NOTIFICATION_CLIENT] ON [dbo].[CLI_NOTIFICATION_LOG] ([NOTIFICATION_ID], [CLIENT_CODE]);
END
GO

-- 4. Register BOS Page for Notification Management
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BOS_PAGES]') AND type in (N'U'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[BOS_PAGES] WHERE [PAGE_CODE] = 'CLI_NOTIFICATION_MGMT')
    BEGIN
        INSERT INTO [dbo].[BOS_PAGES] ([PAGE_CODE], [PAGE_NAME], [MODULE_NAME], [SUBMODULE_NAME], [PAGE_URL], [IS_ACTIVE], [CREATED_DATE])
        VALUES ('CLI_NOTIFICATION_MGMT', 'Client Notification Management', 'Client Management', 'Notifications', '/client-management/notifications', 1, GETDATE());
    END
END
GO
