-- Rename the existing LEDGER_TYPE column to CATEGORY
EXEC sp_rename 'FA_ACCOUNT_LEDGER.LEDGER_TYPE', 'CATEGORY', 'COLUMN';
GO

-- Add the new LEDGER_TYPE column
ALTER TABLE FA_ACCOUNT_LEDGER ADD LEDGER_TYPE VARCHAR(25);
GO

-- Backfill the new LEDGER_TYPE column based on existing boolean flags
UPDATE FA_ACCOUNT_LEDGER 
SET LEDGER_TYPE = 'CUSTOMER' 
WHERE IS_CUSTOMER = 1;
GO

UPDATE FA_ACCOUNT_LEDGER 
SET LEDGER_TYPE = 'SUPPLIER' 
WHERE IS_SUPPLIER = 1;
GO

UPDATE FA_ACCOUNT_LEDGER 
SET LEDGER_TYPE = 'FINANCE' 
WHERE IS_FINANCE = 1 AND IS_CUSTOMER = 0 AND IS_SUPPLIER = 0;
GO

UPDATE FA_ACCOUNT_LEDGER 
SET LEDGER_TYPE = 'TAX' 
WHERE TAX_TYPE IS NOT NULL OR TAX_PERCENTAGE IS NOT NULL;
GO
UPDATE FA_ACCOUNT_LEDGER 
SET CATEGORY = 'GST' 
WHERE LEDGER_TYPE = 'TAX' AND (LEDGER_NAME LIKE '%GST %' OR TAX_TYPE IN ('CGST', 'SGST', 'IGST'));
GO

UPDATE FA_ACCOUNT_LEDGER 
SET CATEGORY = 'TDS' 
WHERE LEDGER_TYPE = 'TAX' AND (LEDGER_NAME LIKE '%TDS %' OR TAX_TYPE = 'TDS');
GO

UPDATE FA_ACCOUNT_LEDGER 
SET CATEGORY = 'TCS' 
WHERE LEDGER_TYPE = 'TAX' AND (LEDGER_NAME LIKE '%TCS %' OR TAX_TYPE = 'TCS');
GO
