-- Create HR_EMPLOYEE_BIRTHDAY_WISH table if it does not exist
IF OBJECT_ID('dbo.HR_EMPLOYEE_BIRTHDAY_WISH', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.HR_EMPLOYEE_BIRTHDAY_WISH (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        RECIPIENT_EMPLOYEE_ID BIGINT NOT NULL,
        SENDER_EMPLOYEE_ID BIGINT NOT NULL,
        WISH_YEAR INT NOT NULL,
        MESSAGE NVARCHAR(500) NOT NULL,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_BIRTHDAY_WISH_RECIPIENT FOREIGN KEY (RECIPIENT_EMPLOYEE_ID) REFERENCES dbo.HR_EMPLOYEE(ID),
        CONSTRAINT FK_BIRTHDAY_WISH_SENDER FOREIGN KEY (SENDER_EMPLOYEE_ID) REFERENCES dbo.HR_EMPLOYEE(ID),
        CONSTRAINT FK_BIRTHDAY_WISH_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_BIRTHDAY_WISH_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    PRINT 'Created HR_EMPLOYEE_BIRTHDAY_WISH table successfully.';
END
ELSE
BEGIN
    PRINT 'HR_EMPLOYEE_BIRTHDAY_WISH table already exists.';
END
