IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE Name = N'SUPPLIER_REF_NO' 
    AND Object_ID = Object_ID(N'PP_QUOTATION_HEAD')
)
BEGIN
    ALTER TABLE PP_QUOTATION_HEAD ADD SUPPLIER_REF_NO VARCHAR(100);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE Name = N'SUPPLIER_REF_DATE' 
    AND Object_ID = Object_ID(N'PP_QUOTATION_HEAD')
)
BEGIN
    ALTER TABLE PP_QUOTATION_HEAD ADD SUPPLIER_REF_DATE DATE;
END
GO


