CREATE TABLE PP_QUOTATION_NEGOTIATION_HEAD (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NEGOTIATION_NO NVARCHAR(50) NOT NULL,
    NEGOTIATION_ROUND INT NOT NULL DEFAULT 1,
    NEGOTIATION_DATE DATETIME NOT NULL,
    QUOTATION_ID BIGINT NOT NULL,
    RFQ_ID BIGINT NOT NULL,
    SUPPLIER_ID BIGINT NOT NULL,
    BUYER_ID BIGINT NOT NULL,
    DIVISION BIGINT NOT NULL,
    
    ORIGINAL_TOTAL DECIMAL(18,2),
    NEGOTIATED_TOTAL DECIMAL(18,2),
    TOTAL_SAVINGS DECIMAL(18,2),
    
    NEGOTIATION_REMARKS NVARCHAR(MAX),
    SUPPLIER_REMARKS NVARCHAR(MAX),
    
    STATUS_ID BIGINT NOT NULL,
    
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    ACTIVE_STATUS INT DEFAULT 1,
    
    CONSTRAINT FK_QT_NEG_QT FOREIGN KEY (QUOTATION_ID) REFERENCES PP_QUOTATION_HEAD(ID),
    CONSTRAINT FK_QT_NEG_RFQ FOREIGN KEY (RFQ_ID) REFERENCES PP_RFQ_HEAD(ID),
    CONSTRAINT FK_QT_NEG_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES FA_ACCOUNT_LEDGER(ID),
    CONSTRAINT FK_QT_NEG_BUYER FOREIGN KEY (BUYER_ID) REFERENCES HR_EMPLOYEE(ID),
    CONSTRAINT FK_QT_NEG_STATUS FOREIGN KEY (STATUS_ID) REFERENCES AD_STATUS_MASTER(ID)
);

CREATE TABLE PP_QUOTATION_NEGOTIATION_TRANS (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NEGOTIATION_HEAD_ID BIGINT NOT NULL,
    QUOTATION_DETAIL_ID BIGINT NOT NULL,
    
    ITEM_ID BIGINT NOT NULL,
    QTY DECIMAL(18,3) NOT NULL,
    
    ORIGINAL_PRICE DECIMAL(18,2),
    NEGOTIATED_PRICE DECIMAL(18,2),
    SAVINGS DECIMAL(18,2),
    
    ORIGINAL_DELIVERY_DAYS INT,
    NEGOTIATED_DELIVERY_DAYS INT,
    
    ORIGINAL_WARRANTY NVARCHAR(255),
    NEGOTIATED_WARRANTY NVARCHAR(255),
    
    REMARKS NVARCHAR(MAX),
    
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    ACTIVE_STATUS INT DEFAULT 1,
    
    CONSTRAINT FK_QT_NEG_TRANS_HEAD FOREIGN KEY (NEGOTIATION_HEAD_ID) REFERENCES PP_QUOTATION_NEGOTIATION_HEAD(ID),
    CONSTRAINT FK_QT_NEG_TRANS_QTD FOREIGN KEY (QUOTATION_DETAIL_ID) REFERENCES PP_QUOTATION_DETAIL(ID),
    CONSTRAINT FK_QT_NEG_TRANS_ITEM FOREIGN KEY (ITEM_ID) REFERENCES NPD_PRODUCT_MASTER(ID)
);

CREATE TABLE PP_QUOTATION_NEGOTIATION_HISTORY (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NEGOTIATION_HEAD_ID BIGINT NOT NULL,
    ACTION_DATE DATETIME NOT NULL,
    ACTION_TYPE NVARCHAR(100) NOT NULL,
    USER_ID NVARCHAR(50) NOT NULL,
    REMARKS NVARCHAR(MAX),
    
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    ACTIVE_STATUS INT DEFAULT 1,
    
    CONSTRAINT FK_QT_NEG_HIST_HEAD FOREIGN KEY (NEGOTIATION_HEAD_ID) REFERENCES PP_QUOTATION_NEGOTIATION_HEAD(ID)
);

-- Ensure Statuses
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(NAME) = 'OPEN')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME, DESCRIPTION, ACTIVE_STATUS) VALUES ('OPEN', 'Open', 1);
END
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(NAME) = 'IN DISCUSSION')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME, DESCRIPTION, ACTIVE_STATUS) VALUES ('IN DISCUSSION', 'In Discussion', 1);
END
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(NAME) = 'AGREED')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME, DESCRIPTION, ACTIVE_STATUS) VALUES ('AGREED', 'Agreed', 1);
END
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(NAME) = 'REJECTED')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME, DESCRIPTION, ACTIVE_STATUS) VALUES ('REJECTED', 'Rejected', 1);
END
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(NAME) = 'CLOSED')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME, DESCRIPTION, ACTIVE_STATUS) VALUES ('CLOSED', 'Closed', 1);
END
