-- 1. Add ISD column to MST_COUNTRY
IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID('MST_COUNTRY') 
    AND name = 'ISD'
)
BEGIN
    ALTER TABLE [dbo].[MST_COUNTRY] ADD [ISD] NVARCHAR(10) NULL;
END
GO

-- 2. Add Country ID reference columns to HR_EMPLOYEE_SELF_ASSESSMENT
IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') 
    AND name = 'MGR_COUNTRY_ID'
)
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [MGR_COUNTRY_ID] BIGINT NULL;
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD CONSTRAINT [FK_HR_EMPLOYEE_SELF_ASSESSMENT_MGR_COUNTRY] FOREIGN KEY ([MGR_COUNTRY_ID]) REFERENCES [dbo].[MST_COUNTRY]([ROW_ID]);
END
GO

IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') 
    AND name = 'VERT_HEAD_COUNTRY_ID'
)
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [VERT_HEAD_COUNTRY_ID] BIGINT NULL;
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD CONSTRAINT [FK_HR_EMPLOYEE_SELF_ASSESSMENT_VERT_HEAD_COUNTRY] FOREIGN KEY ([VERT_HEAD_COUNTRY_ID]) REFERENCES [dbo].[MST_COUNTRY]([ROW_ID]);
END
GO
