-- Organization: Nutech Wind Parts Pvt Ltd
-- Owner: Nutech
-- Created At: 2026-09-05
-- Description: Add PROCESS_ID column to NPD_BOM_PROCESS_MATERIAL, NPD_BOM_PROCESS_MACHINE, and NPD_BOM_PROCESS_TOOL tables

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NPD_BOM_PROCESS_MATERIAL')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'PROCESS_ID' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_MATERIAL'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_MATERIAL ADD PROCESS_ID BIGINT NULL;
        PRINT 'Added PROCESS_ID column to NPD_BOM_PROCESS_MATERIAL.';
    END
END;
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NPD_BOM_PROCESS_MACHINE')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'PROCESS_ID' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_MACHINE'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_MACHINE ADD PROCESS_ID BIGINT NULL;
        PRINT 'Added PROCESS_ID column to NPD_BOM_PROCESS_MACHINE.';
    END
END;
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NPD_BOM_PROCESS_TOOL')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'PROCESS_ID' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_TOOL'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_TOOL ADD PROCESS_ID BIGINT NULL;
        PRINT 'Added PROCESS_ID column to NPD_BOM_PROCESS_TOOL.';
    END
END;
GO
