IF OBJECT_ID('SM_CUSTOMER_ORDER_HEADER', 'U') IS NULL
BEGIN
    CREATE TABLE SM_CUSTOMER_ORDER_HEADER (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        ORDER_NO NVARCHAR(50) NOT NULL,
        ORDER_DATE DATETIME NULL,
        ORDER_REC_DATE DATETIME NULL,
        PAYMENT_TERMS NVARCHAR(50) NULL,
        CURRENCY_CODE NVARCHAR(15) NULL,
        EXCHANGE_RATE NVARCHAR(15) NULL,
        QUOTATION_NO NVARCHAR(25) NULL,
        QUOTATION_DATE DATETIME NULL,
        MODE_OF_DESPATCH NVARCHAR(20) NULL,
        SUPPLY_CONDITION NVARCHAR(30) NULL,
        DELIVERY_TERMS NVARCHAR(50) NULL,
        CUST_ID BIGINT NULL,
        BILL_CUST_ID BIGINT NULL,
        BILL_ADDRESS NVARCHAR(250) NULL,
        SHIP_CUST_ID BIGINT NULL,
        SHIP_ADDRESS NVARCHAR(250) NULL,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_SM_CUST_ORD_HDR_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SM_CUST_ORD_HDR_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END

IF OBJECT_ID('SM_CUSTOMER_ORDER_DETAIL', 'U') IS NULL
BEGIN
    CREATE TABLE SM_CUSTOMER_ORDER_DETAIL (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        ORDER_REF_ID BIGINT NOT NULL,
        PART_NO NVARCHAR(50) NULL,
        PART_NAME NVARCHAR(100) NULL,
        QUOTATION_NO NVARCHAR(50) NULL,
        HSN_CODE NVARCHAR(50) NULL,
        UOM NVARCHAR(20) NULL,
        STOCK NUMERIC(12,2) NULL,
        QTY INT NULL,
        PRICE NUMERIC(12,2) NULL,
        ORDER_PRICE NUMERIC(12,2) NULL,
        ORDER_WEIGHT NUMERIC(12,2) NULL,
        DISCOUNT_PER NUMERIC(12,2) NULL,
        CGST_PER NUMERIC(12,2) NULL,
        SGST_PER NUMERIC(12,2) NULL,
        IGST_PER NUMERIC(12,2) NULL,
        FREIGHT_PER NUMERIC(12,2) NULL,
        APPROVAL_STATUS BIT NULL,
        STATUS BIT NULL,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_SM_CUSTOMER_ORDER_DETAIL_HEADER FOREIGN KEY (ORDER_REF_ID) REFERENCES SM_CUSTOMER_ORDER_HEADER(ID),
        CONSTRAINT FK_SM_CUST_ORD_DTL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SM_CUST_ORD_DTL_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
