-- ============================================================================
-- V367.0 Create Product Bundle Module
-- Date: 2026-06-26
-- ============================================================================

-- 1. Create Product Bundle Master Table
CREATE TABLE NPD_PRODUCT_BUNDLE_MASTER (
    ID BIGINT IDENTITY(1,1) NOT NULL,
    BUNDLE_CODE NVARCHAR(100) NOT NULL,
    BUNDLE_NAME NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(MAX),
    BUNDLE_TYPE NVARCHAR(50),
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    IS_ACTIVE BIT DEFAULT 1,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    CONSTRAINT PK_NPD_PRODUCT_BUNDLE_MASTER PRIMARY KEY (ID),
    CONSTRAINT UQ_NPD_PRODUCT_BUNDLE_CODE UNIQUE (BUNDLE_CODE),
    CONSTRAINT FK_PRODUCT_BUNDLE_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_PRODUCT_BUNDLE_MASTER_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);
GO

-- 2. Create Product Bundle Detail Table
CREATE TABLE NPD_PRODUCT_BUNDLE_DETAIL (
    ID BIGINT IDENTITY(1,1) NOT NULL,
    BUNDLE_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QTY FLOAT NOT NULL,
    NORMAL_RATE FLOAT,
    BUNDLE_RATE FLOAT,
    DISCOUNT_PERCENT FLOAT,
    DISCOUNT_AMOUNT FLOAT,
    IS_ACTIVE BIT DEFAULT 1,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    CONSTRAINT PK_NPD_PRODUCT_BUNDLE_DETAIL PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_BUNDLE_MASTER FOREIGN KEY (BUNDLE_ID) REFERENCES NPD_PRODUCT_BUNDLE_MASTER(ID),
    CONSTRAINT FK_PRODUCT_BUNDLE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES NPD_PRODUCT_MASTER(ID),
    CONSTRAINT FK_PRODUCT_BUNDLE_DETAIL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_PRODUCT_BUNDLE_DETAIL_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);
GO

-- 3. Add Prefix Credentials for Product Bundle
ALTER TABLE AD_PREFIX_CREDENTIALS ADD PRODUCT_BUNDLE_PREFIX NVARCHAR(20);
ALTER TABLE AD_PREFIX_CREDENTIALS ADD PRODUCT_BUNDLE_SUFFIX NVARCHAR(20);
ALTER TABLE AD_PREFIX_CREDENTIALS ADD PRODUCT_BUNDLE_DIGIT INT;
GO

-- Set default values for existing rows
UPDATE AD_PREFIX_CREDENTIALS SET PRODUCT_BUNDLE_PREFIX = 'BNDL', PRODUCT_BUNDLE_DIGIT = 5;
GO


-- 5. Register Page in BOS_PAGES
DECLARE @modId INT, @subModId INT;
-- Find MOD_ID and SUB_MOD_ID using existing DD1110 (Product BOM)
SELECT @modId = MOD_ID, @subModId = SUB_MOD_ID FROM BOS_PAGES WHERE PAGE_CODE = 'DD1110';

-- Fallback if DD1110 doesn't exist for some reason
IF @modId IS NULL OR @subModId IS NULL
BEGIN
    -- Just use some fallback. (Design & Development is usually Mod 14 or similar, we'll try to find any DD page)
    SELECT TOP 1 @modId = MOD_ID, @subModId = SUB_MOD_ID FROM BOS_PAGES WHERE PAGE_CODE LIKE 'DD%';
END

IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'DD1112')
BEGIN
    INSERT INTO BOS_PAGES (MOD_ID, SUB_MOD_ID, PAGE_CODE, PAGE_NAME, ENABLED, PAGE_URL, ICON)
    VALUES (ISNULL(@modId, 0), ISNULL(@subModId, 0), 'DD1112', 'Product Bundle', 1, '/dd/product-bundle', 'IconPackage');
    PRINT 'Page DD1112 (Product Bundle) registered in BOS_PAGES.';
END
ELSE
BEGIN
    PRINT 'Page DD1112 already exists in BOS_PAGES — skipped.';
END
GO

-- 5. Grant Admin access to the new page
DECLARE @newPageId INT;
SELECT @newPageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'DD1112';

IF @newPageId IS NOT NULL
BEGIN
    -- We grant to all users who currently have access to DD1110
    DECLARE @refPageId INT;
    SELECT @refPageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'DD1110';

    IF @refPageId IS NOT NULL
    BEGIN
        INSERT INTO BOS_USER_PAGE_AUTH
            (USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, READ_ACS, WRITE, DELETE_ACS,
             EXPORT, APPROVAL, MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, CREATED_BY, CREATED_DATE)
        SELECT
            USER_ID, @newPageId, SUB_MOD_ID, MOD_ID,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'SYSTEM', SYSDATETIME()
        FROM BOS_USER_PAGE_AUTH
        WHERE PAGE_ID = @refPageId
          AND USER_ID NOT IN (
              SELECT USER_ID FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = @newPageId
          );
        PRINT 'Access grants for DD1112 seeded based on DD1110 users.';
    END
END
GO
