-- Migration V1213.0: Add SECONDARY_EMPLOYEE_ID and TERTIARY_EMPLOYEE_ID to QMS_MEETING_PARTICIPANT_MAPPING
-- Description: Adds Secondary and Tertiary participant mapping columns with performance indexes for dynamic leave fallback.

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_PARTICIPANT_MAPPING') AND name = 'SECONDARY_EMPLOYEE_ID')
BEGIN
    ALTER TABLE QMS_MEETING_PARTICIPANT_MAPPING ADD SECONDARY_EMPLOYEE_ID BIGINT NULL;
    PRINT 'Added SECONDARY_EMPLOYEE_ID column to QMS_MEETING_PARTICIPANT_MAPPING';
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_PARTICIPANT_MAPPING') AND name = 'TERTIARY_EMPLOYEE_ID')
BEGIN
    ALTER TABLE QMS_MEETING_PARTICIPANT_MAPPING ADD TERTIARY_EMPLOYEE_ID BIGINT NULL;
    PRINT 'Added TERTIARY_EMPLOYEE_ID column to QMS_MEETING_PARTICIPANT_MAPPING';
END
GO

-- Add Non-Clustered Indexes for High-Performance Querying & Fallback Lookups
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_MEETING_PARTICIPANT_MAPPING') AND name = 'IX_QMS_MEETING_PARTICIPANT_MAPPING_SECONDARY_EMPLOYEE_ID')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MEETING_PARTICIPANT_MAPPING_SECONDARY_EMPLOYEE_ID
    ON QMS_MEETING_PARTICIPANT_MAPPING (SECONDARY_EMPLOYEE_ID)
    WHERE SECONDARY_EMPLOYEE_ID IS NOT NULL;
    PRINT 'Created index IX_QMS_MEETING_PARTICIPANT_MAPPING_SECONDARY_EMPLOYEE_ID';
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_MEETING_PARTICIPANT_MAPPING') AND name = 'IX_QMS_MEETING_PARTICIPANT_MAPPING_TERTIARY_EMPLOYEE_ID')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MEETING_PARTICIPANT_MAPPING_TERTIARY_EMPLOYEE_ID
    ON QMS_MEETING_PARTICIPANT_MAPPING (TERTIARY_EMPLOYEE_ID)
    WHERE TERTIARY_EMPLOYEE_ID IS NOT NULL;
    PRINT 'Created index IX_QMS_MEETING_PARTICIPANT_MAPPING_TERTIARY_EMPLOYEE_ID';
END
GO
