-- Add Q37_PREV_REPORTING_TO if missing
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q37_PREV_REPORTING_TO')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q37_PREV_REPORTING_TO] NVARCHAR(255) NULL;
END
GO

-- Add Q38_HANDLE_MISTAKE if missing
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q38_HANDLE_MISTAKE')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q38_HANDLE_MISTAKE] NVARCHAR(MAX) NULL;
END
GO

-- Add Q39_HANDLE_OPINION_DIFFERENCE if missing
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q39_HANDLE_OPINION_DIFFERENCE')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q39_HANDLE_OPINION_DIFFERENCE] NVARCHAR(MAX) NULL;
END
GO

-- Add Q40_COMPUTER_SELF_RATING if missing
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q40_COMPUTER_SELF_RATING')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q40_COMPUTER_SELF_RATING] VARCHAR(50) NULL;
END
GO

-- Add Q41_REP_MGR_NAME if missing
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q41_REP_MGR_NAME')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q41_REP_MGR_NAME] NVARCHAR(255) NULL;
END
GO

-- Add Q42_REP_MGR_EMAIL if missing
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q42_REP_MGR_EMAIL')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q42_REP_MGR_EMAIL] NVARCHAR(255) NULL;
END
GO

-- Add Q43_REP_MGR_PHONE if missing
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q43_REP_MGR_PHONE')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q43_REP_MGR_PHONE] NVARCHAR(50) NULL;
END
GO

-- Add Q44_VERT_HEAD_NAME if missing
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q44_VERT_HEAD_NAME')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q44_VERT_HEAD_NAME] NVARCHAR(255) NULL;
END
GO

-- Add Q45_VERT_HEAD_EMAIL if missing
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q45_VERT_HEAD_EMAIL')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q45_VERT_HEAD_EMAIL] NVARCHAR(255) NULL;
END
GO

-- Add Q46_VERT_HEAD_PHONE if missing
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q46_VERT_HEAD_PHONE')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q46_VERT_HEAD_PHONE] NVARCHAR(50) NULL;
END
GO
