IF OBJECT_ID('SM_CUST_ORDER_SCHEDULE', 'U') IS NULL
BEGIN
    CREATE TABLE SM_CUST_ORDER_SCHEDULE (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        CUSTOMER_ID BIGINT NULL,
        PO_ID BIGINT NULL,
        PO_ITEM_ID BIGINT NULL,
        SCHEDULE_QTY NUMERIC(12,2) NULL,
        SCHEDULE_DATE DATETIME NULL,
        STATUS BIGINT NULL,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL
    );
END

IF OBJECT_ID('FK_SM_CUST_ORD_SCH_CUST', 'F') IS NULL
BEGIN
    ALTER TABLE SM_CUST_ORDER_SCHEDULE ADD CONSTRAINT FK_SM_CUST_ORD_SCH_CUST FOREIGN KEY (CUSTOMER_ID) REFERENCES ACCOUNT_LEDGER(ID);
END

IF OBJECT_ID('FK_SM_CUST_ORD_SCH_PO', 'F') IS NULL
BEGIN
    ALTER TABLE SM_CUST_ORDER_SCHEDULE ADD CONSTRAINT FK_SM_CUST_ORD_SCH_PO FOREIGN KEY (PO_ID) REFERENCES SM_CUSTOMER_ORDER_HEADER(ID);
END

IF OBJECT_ID('FK_SM_CUST_ORD_SCH_PO_ITEM', 'F') IS NULL
BEGIN
    ALTER TABLE SM_CUST_ORDER_SCHEDULE ADD CONSTRAINT FK_SM_CUST_ORD_SCH_PO_ITEM FOREIGN KEY (PO_ITEM_ID) REFERENCES SM_CUSTOMER_ORDER_DETAIL(ID);
END

IF OBJECT_ID('FK_SM_CUST_ORD_SCH_STATUS', 'F') IS NULL
BEGIN
    ALTER TABLE SM_CUST_ORDER_SCHEDULE ADD CONSTRAINT FK_SM_CUST_ORD_SCH_STATUS FOREIGN KEY (STATUS) REFERENCES AD_STATUS_MASTER(ID);
END

IF OBJECT_ID('FK_SM_CUST_ORD_SCH_CREATED_BY', 'F') IS NULL
BEGIN
    ALTER TABLE SM_CUST_ORDER_SCHEDULE ADD CONSTRAINT FK_SM_CUST_ORD_SCH_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);
END

IF OBJECT_ID('FK_SM_CUST_ORD_SCH_UPDATED_BY', 'F') IS NULL
BEGIN
    ALTER TABLE SM_CUST_ORDER_SCHEDULE ADD CONSTRAINT FK_SM_CUST_ORD_SCH_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);
END
