-- Migration Script: Alter OM_VISITOR_GATE_PASS table image and attachment columns to NVARCHAR(MAX)
-- Prevents SQL Server 'String or binary data would be truncated' exceptions when saving visitor gate pass images and paths.

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'OM_VISITOR_GATE_PASS') AND name = N'CHECK_IN_IMG')
BEGIN
    ALTER TABLE OM_VISITOR_GATE_PASS ALTER COLUMN CHECK_IN_IMG NVARCHAR(MAX);
END
GO

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'OM_VISITOR_GATE_PASS') AND name = N'CHECK_OUT_IMG')
BEGIN
    ALTER TABLE OM_VISITOR_GATE_PASS ALTER COLUMN CHECK_OUT_IMG NVARCHAR(MAX);
END
GO

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'OM_VISITOR_GATE_PASS') AND name = N'CAPTURE_FILE_NAME')
BEGIN
    ALTER TABLE OM_VISITOR_GATE_PASS ALTER COLUMN CAPTURE_FILE_NAME NVARCHAR(MAX);
END
GO

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'OM_VISITOR_GATE_PASS') AND name = N'FILE_NAME')
BEGIN
    ALTER TABLE OM_VISITOR_GATE_PASS ALTER COLUMN FILE_NAME NVARCHAR(MAX);
END
GO
