-- Add IS_ACTIVE column to QMS_AUDIT_SCHEDULE table if missing
IF OBJECT_ID('[dbo].[QMS_AUDIT_SCHEDULE]', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[QMS_AUDIT_SCHEDULE]') AND name = 'IS_ACTIVE')
    BEGIN
        ALTER TABLE [dbo].[QMS_AUDIT_SCHEDULE] ADD [IS_ACTIVE] BIT DEFAULT 1;
        PRINT 'Added column IS_ACTIVE to QMS_AUDIT_SCHEDULE';
    END
END
GO

IF OBJECT_ID('[dbo].[QMS_AUDIT_SCHEDULE]', 'U') IS NOT NULL
BEGIN
    IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[QMS_AUDIT_SCHEDULE]') AND name = 'IS_ACTIVE')
    BEGIN
        EXEC('UPDATE [dbo].[QMS_AUDIT_SCHEDULE] SET [IS_ACTIVE] = 1 WHERE [IS_ACTIVE] IS NULL');
    END
END
GO
