-- Add ALLOW_RIGHT_CLICK column to AD_COMPANY_CREDENTIAL
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ALLOW_RIGHT_CLICK')
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL]
    ADD [ALLOW_RIGHT_CLICK] BIT NOT NULL DEFAULT 1;
END
GO
