-- =============================================================================
-- Organization: Nutech Wind Parts Pvt Ltd
-- Owner: Yuvanesh M
-- Created At: 2026-09-01
-- Description: V1226.0 - Normalize HRA_OFFER_LETTERS schema, add NOTICE_PERIOD,
--              backfill notice period from FORM_DATA, and drop obsolete company,
--              signatory, and dead columns.
-- =============================================================================

SET NOCOUNT ON;
GO

-- 1. ADD NOTICE_PERIOD COLUMN (IDEMPOTENT)
IF COL_LENGTH('dbo.HRA_OFFER_LETTERS', 'NOTICE_PERIOD') IS NULL
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [NOTICE_PERIOD] NVARCHAR(50) NULL;
END;
GO

-- 2. DEFENSIVE NOTICE_PERIOD BACKFILL FROM FORM_DATA (DYNAMIC SQL TO PREVENT COMPILE-TIME BINDING FAILURE)
IF COL_LENGTH('dbo.HRA_OFFER_LETTERS', 'NOTICE_PERIOD') IS NOT NULL
BEGIN
    EXEC sp_executesql N'
    UPDATE [dbo].[HRA_OFFER_LETTERS]
    SET [NOTICE_PERIOD] = LTRIM(RTRIM(JSON_VALUE([FORM_DATA], ''$.terms.noticePeriod'')))
    WHERE [NOTICE_PERIOD] IS NULL 
      AND [FORM_DATA] IS NOT NULL
      AND ISJSON([FORM_DATA]) = 1
      AND JSON_VALUE([FORM_DATA], ''$.terms.noticePeriod'') IS NOT NULL;';
END;
GO

-- 3. DROP DEAD TEMPLATE_ID COLUMN
IF COL_LENGTH('dbo.HRA_OFFER_LETTERS', 'TEMPLATE_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] DROP COLUMN [TEMPLATE_ID];
END;
GO

-- 4. DROP OBSOLETE COMPANY & SIGNATORY COLUMNS
IF COL_LENGTH('dbo.HRA_OFFER_LETTERS', 'COMPANY_NAME') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] DROP COLUMN [COMPANY_NAME];
END;
GO

IF COL_LENGTH('dbo.HRA_OFFER_LETTERS', 'COMPANY_ADDRESS') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] DROP COLUMN [COMPANY_ADDRESS];
END;
GO

IF COL_LENGTH('dbo.HRA_OFFER_LETTERS', 'SIGNATORY_NAME') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] DROP COLUMN [SIGNATORY_NAME];
END;
GO

IF COL_LENGTH('dbo.HRA_OFFER_LETTERS', 'SIGNATORY_DESIGNATION') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] DROP COLUMN [SIGNATORY_DESIGNATION];
END;
GO
