-- Migration: Add Layout Option Columns to HR_EMAIL_CONTENT table
-- Date: 2026-07-20

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMAIL_CONTENT') 
    AND name = 'INCLUDE_COMPANY_FOOTER'
)
BEGIN
    ALTER TABLE HR_EMAIL_CONTENT ADD INCLUDE_COMPANY_FOOTER BIT NULL DEFAULT 1;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMAIL_CONTENT') 
    AND name = 'INCLUDE_WEBSITE'
)
BEGIN
    ALTER TABLE HR_EMAIL_CONTENT ADD INCLUDE_WEBSITE BIT NULL DEFAULT 0;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMAIL_CONTENT') 
    AND name = 'INCLUDE_LOCATION'
)
BEGIN
    ALTER TABLE HR_EMAIL_CONTENT ADD INCLUDE_LOCATION BIT NULL DEFAULT 0;
END;
GO

-- Ensure all existing rows have explicit default values
UPDATE HR_EMAIL_CONTENT
SET INCLUDE_COMPANY_FOOTER = 1
WHERE INCLUDE_COMPANY_FOOTER IS NULL;

UPDATE HR_EMAIL_CONTENT
SET INCLUDE_WEBSITE = 0
WHERE INCLUDE_WEBSITE IS NULL;

UPDATE HR_EMAIL_CONTENT
SET INCLUDE_LOCATION = 0
WHERE INCLUDE_LOCATION IS NULL;
