-- SQL Migration script V1156.0: Add FILE_LOG_PATH column to QMT_MACHINE_INTEGRATION

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE_INTEGRATION') AND name = 'FILE_LOG_PATH')
BEGIN
    ALTER TABLE QMT_MACHINE_INTEGRATION ADD FILE_LOG_PATH NVARCHAR(1000) NULL;
END
GO
