-- ==============================================================================
-- Migration Script: V390.0 Enhance BOS Notebook with Document Intelligence,
--                   Shared Notebooks, Tags, and Enterprise Knowledge Base
-- Author: Antigravity AI
-- Date: 2026-07-03
-- ==============================================================================

-- 1. Enhance SYS_NOTEBOOK_SOURCE with document content extraction fields
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_NOTEBOOK_SOURCE' AND COLUMN_NAME='EXTRACTED_CONTENT')
BEGIN
    ALTER TABLE dbo.SYS_NOTEBOOK_SOURCE ADD EXTRACTED_CONTENT NVARCHAR(MAX) NULL;
    PRINT 'Added EXTRACTED_CONTENT to SYS_NOTEBOOK_SOURCE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_NOTEBOOK_SOURCE' AND COLUMN_NAME='EXTRACTION_STATUS')
BEGIN
    ALTER TABLE dbo.SYS_NOTEBOOK_SOURCE ADD EXTRACTION_STATUS VARCHAR(20) NULL DEFAULT 'NONE';
    -- NONE | PENDING | DONE | FAILED
    PRINT 'Added EXTRACTION_STATUS to SYS_NOTEBOOK_SOURCE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_NOTEBOOK_SOURCE' AND COLUMN_NAME='FILE_SIZE_KB')
BEGIN
    ALTER TABLE dbo.SYS_NOTEBOOK_SOURCE ADD FILE_SIZE_KB INT NULL;
    PRINT 'Added FILE_SIZE_KB to SYS_NOTEBOOK_SOURCE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_NOTEBOOK_SOURCE' AND COLUMN_NAME='SOURCE_URL')
BEGIN
    ALTER TABLE dbo.SYS_NOTEBOOK_SOURCE ADD SOURCE_URL NVARCHAR(1000) NULL;
    PRINT 'Added SOURCE_URL to SYS_NOTEBOOK_SOURCE';
END;

-- 2. Add TAGS support to SYS_NOTEBOOK
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_NOTEBOOK' AND COLUMN_NAME='TAGS')
BEGIN
    ALTER TABLE dbo.SYS_NOTEBOOK ADD TAGS NVARCHAR(500) NULL;
    -- Comma-separated tags: 'QMS,HR,Finance'
    PRINT 'Added TAGS to SYS_NOTEBOOK';
END;

-- 3. Create SYS_NOTEBOOK_SHARE — shared access table
IF OBJECT_ID('dbo.SYS_NOTEBOOK_SHARE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SYS_NOTEBOOK_SHARE (
        ID                  BIGINT IDENTITY(1,1)    NOT NULL,
        NOTEBOOK_ID         BIGINT                  NOT NULL,
        SHARED_WITH_EMP_ID  BIGINT                  NOT NULL, -- FK -> HR_EMPLOYEE.ID
        PERMISSION_LEVEL    VARCHAR(20)             NOT NULL DEFAULT 'VIEW', -- VIEW | COMMENT | EDIT
        SHARED_BY_EMP_ID    BIGINT                  NOT NULL,
        CREATED_BY          NVARCHAR(50)            NOT NULL,
        CREATED_DATE        DATETIME                NOT NULL DEFAULT GETDATE(),
        ACTIVE_STATUS       CHAR(1)                 NOT NULL DEFAULT 'Y',
        CONSTRAINT PK_SYS_NOTEBOOK_SHARE PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT FK_SYS_NB_SHARE_NOTEBOOK FOREIGN KEY (NOTEBOOK_ID) REFERENCES dbo.SYS_NOTEBOOK(ID) ON DELETE CASCADE,
        CONSTRAINT FK_SYS_NB_SHARE_EMP FOREIGN KEY (SHARED_WITH_EMP_ID) REFERENCES dbo.HR_EMPLOYEE(ID),
        CONSTRAINT FK_SYS_NB_SHARE_BY FOREIGN KEY (SHARED_BY_EMP_ID) REFERENCES dbo.HR_EMPLOYEE(ID),
        CONSTRAINT FK_SYS_NB_SHARE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT UQ_SYS_NB_SHARE UNIQUE (NOTEBOOK_ID, SHARED_WITH_EMP_ID)
    );
    CREATE NONCLUSTERED INDEX IX_SYS_NB_SHARE_NOTEBOOK ON dbo.SYS_NOTEBOOK_SHARE(NOTEBOOK_ID);
    CREATE NONCLUSTERED INDEX IX_SYS_NB_SHARE_EMP ON dbo.SYS_NOTEBOOK_SHARE(SHARED_WITH_EMP_ID);
    CREATE NONCLUSTERED INDEX IX_SYS_NB_SHARE_ACTIVE ON dbo.SYS_NOTEBOOK_SHARE(ACTIVE_STATUS);
    PRINT 'Created SYS_NOTEBOOK_SHARE table';
END;

-- 4. Create SYS_ENTERPRISE_KNOWLEDGE — admin-managed global knowledge base
IF OBJECT_ID('dbo.SYS_ENTERPRISE_KNOWLEDGE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE (
        ID                  BIGINT IDENTITY(1,1)    NOT NULL,
        TITLE               NVARCHAR(255)           NOT NULL,
        CATEGORY            NVARCHAR(50)            NOT NULL, -- HR | QMS | SALES | FINANCE | GENERAL
        SOURCE_TYPE         VARCHAR(20)             NOT NULL, -- PDF | URL | TEXT | POLICY | MANUAL
        EXTRACTED_CONTENT   NVARCHAR(MAX)           NOT NULL,
        FILE_PATH           NVARCHAR(500)           NULL,
        SOURCE_URL          NVARCHAR(1000)          NULL,
        FILE_SIZE_KB        INT                     NULL,
        COMPANY_ID          BIGINT                  NOT NULL,
        CREATED_BY          NVARCHAR(50)            NOT NULL,
        CREATED_DATE        DATETIME                NOT NULL DEFAULT GETDATE(),
        UPDATED_BY          NVARCHAR(50)            NULL,
        UPDATED_DATE        DATETIME                NULL,
        ACTIVE_STATUS       CHAR(1)                 NOT NULL DEFAULT 'Y',
        CONSTRAINT PK_SYS_ENTERPRISE_KNOWLEDGE PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT FK_SYS_EK_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SYS_EK_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE NONCLUSTERED INDEX IX_SYS_EK_CATEGORY ON dbo.SYS_ENTERPRISE_KNOWLEDGE(CATEGORY);
    CREATE NONCLUSTERED INDEX IX_SYS_EK_COMPANY ON dbo.SYS_ENTERPRISE_KNOWLEDGE(COMPANY_ID);
    CREATE NONCLUSTERED INDEX IX_SYS_EK_ACTIVE ON dbo.SYS_ENTERPRISE_KNOWLEDGE(ACTIVE_STATUS);
    PRINT 'Created SYS_ENTERPRISE_KNOWLEDGE table';
END;

PRINT 'V390.0 migration completed successfully.';
