-- Migration Script to create CUSTOMER_EMAIL_MAPPING, CUSTOMER_DOMAIN_MAPPING, and PUBLIC_EMAIL_PROVIDER tables

-- 1. Create PUBLIC_EMAIL_PROVIDER table
IF OBJECT_ID('dbo.PUBLIC_EMAIL_PROVIDER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PUBLIC_EMAIL_PROVIDER (
        ID bigint IDENTITY(1,1) PRIMARY KEY NOT NULL,
        DOMAIN_NAME nvarchar(100) NOT NULL UNIQUE,
        ACTIVE_STATUS bit NOT NULL DEFAULT 1,
        CREATED_BY nvarchar(50) NOT NULL,
        CREATED_DATE datetime NOT NULL,
        UPDATED_BY nvarchar(50),
        UPDATED_DATE datetime,
        CONSTRAINT FK_PUBLIC_EMAIL_PROVIDER_USER_CREATED FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_PUBLIC_EMAIL_PROVIDER_USER_UPDATED FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
    PRINT 'Created table PUBLIC_EMAIL_PROVIDER';
END
GO

-- 2. Seed PUBLIC_EMAIL_PROVIDER table (idempotent)
IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID('dbo.PUBLIC_EMAIL_PROVIDER') AND type = 'U')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM dbo.PUBLIC_EMAIL_PROVIDER WHERE DOMAIN_NAME = 'gmail.com')
        INSERT INTO dbo.PUBLIC_EMAIL_PROVIDER (DOMAIN_NAME, CREATED_BY, CREATED_DATE, ACTIVE_STATUS) VALUES ('gmail.com', 'SUPER BOSS', GETDATE(), 1);
    IF NOT EXISTS (SELECT 1 FROM dbo.PUBLIC_EMAIL_PROVIDER WHERE DOMAIN_NAME = 'yahoo.com')
        INSERT INTO dbo.PUBLIC_EMAIL_PROVIDER (DOMAIN_NAME, CREATED_BY, CREATED_DATE, ACTIVE_STATUS) VALUES ('yahoo.com', 'SUPER BOSS', GETDATE(), 1);
    IF NOT EXISTS (SELECT 1 FROM dbo.PUBLIC_EMAIL_PROVIDER WHERE DOMAIN_NAME = 'outlook.com')
        INSERT INTO dbo.PUBLIC_EMAIL_PROVIDER (DOMAIN_NAME, CREATED_BY, CREATED_DATE, ACTIVE_STATUS) VALUES ('outlook.com', 'SUPER BOSS', GETDATE(), 1);
    IF NOT EXISTS (SELECT 1 FROM dbo.PUBLIC_EMAIL_PROVIDER WHERE DOMAIN_NAME = 'hotmail.com')
        INSERT INTO dbo.PUBLIC_EMAIL_PROVIDER (DOMAIN_NAME, CREATED_BY, CREATED_DATE, ACTIVE_STATUS) VALUES ('hotmail.com', 'SUPER BOSS', GETDATE(), 1);
    IF NOT EXISTS (SELECT 1 FROM dbo.PUBLIC_EMAIL_PROVIDER WHERE DOMAIN_NAME = 'live.com')
        INSERT INTO dbo.PUBLIC_EMAIL_PROVIDER (DOMAIN_NAME, CREATED_BY, CREATED_DATE, ACTIVE_STATUS) VALUES ('live.com', 'SUPER BOSS', GETDATE(), 1);
    IF NOT EXISTS (SELECT 1 FROM dbo.PUBLIC_EMAIL_PROVIDER WHERE DOMAIN_NAME = 'icloud.com')
        INSERT INTO dbo.PUBLIC_EMAIL_PROVIDER (DOMAIN_NAME, CREATED_BY, CREATED_DATE, ACTIVE_STATUS) VALUES ('icloud.com', 'SUPER BOSS', GETDATE(), 1);
    IF NOT EXISTS (SELECT 1 FROM dbo.PUBLIC_EMAIL_PROVIDER WHERE DOMAIN_NAME = 'proton.me')
        INSERT INTO dbo.PUBLIC_EMAIL_PROVIDER (DOMAIN_NAME, CREATED_BY, CREATED_DATE, ACTIVE_STATUS) VALUES ('proton.me', 'SUPER BOSS', GETDATE(), 1);
    IF NOT EXISTS (SELECT 1 FROM dbo.PUBLIC_EMAIL_PROVIDER WHERE DOMAIN_NAME = 'protonmail.com')
        INSERT INTO dbo.PUBLIC_EMAIL_PROVIDER (DOMAIN_NAME, CREATED_BY, CREATED_DATE, ACTIVE_STATUS) VALUES ('protonmail.com', 'SUPER BOSS', GETDATE(), 1);
    IF NOT EXISTS (SELECT 1 FROM dbo.PUBLIC_EMAIL_PROVIDER WHERE DOMAIN_NAME = 'aol.com')
        INSERT INTO dbo.PUBLIC_EMAIL_PROVIDER (DOMAIN_NAME, CREATED_BY, CREATED_DATE, ACTIVE_STATUS) VALUES ('aol.com', 'SUPER BOSS', GETDATE(), 1);
    PRINT 'Seeded table PUBLIC_EMAIL_PROVIDER';
END
GO

-- 3. Create CUSTOMER_EMAIL_MAPPING table
IF OBJECT_ID('dbo.CUSTOMER_EMAIL_MAPPING', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CUSTOMER_EMAIL_MAPPING (
        ID bigint IDENTITY(1,1) PRIMARY KEY NOT NULL,
        CUSTOMER_ID bigint NOT NULL,
        EMAIL_ADDRESS nvarchar(255) NOT NULL UNIQUE,
        IS_PRIMARY bit NOT NULL DEFAULT 0,
        ACTIVE_STATUS bit NOT NULL DEFAULT 1,
        CREATED_BY nvarchar(50) NOT NULL,
        CREATED_DATE datetime NOT NULL,
        UPDATED_BY nvarchar(50),
        UPDATED_DATE datetime,
        CONSTRAINT FK_CUSTOMER_EMAIL_MAPPING_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES FA_ACCOUNT_LEDGER(ID),
        CONSTRAINT FK_CUSTOMER_EMAIL_MAPPING_USER_CREATED FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_CUSTOMER_EMAIL_MAPPING_USER_UPDATED FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
    PRINT 'Created table CUSTOMER_EMAIL_MAPPING';
END
GO

-- 4. Create CUSTOMER_DOMAIN_MAPPING table
IF OBJECT_ID('dbo.CUSTOMER_DOMAIN_MAPPING', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CUSTOMER_DOMAIN_MAPPING (
        ID bigint IDENTITY(1,1) PRIMARY KEY NOT NULL,
        CUSTOMER_ID bigint NOT NULL,
        DOMAIN_NAME nvarchar(100) NOT NULL UNIQUE,
        ACTIVE_STATUS bit NOT NULL DEFAULT 1,
        CREATED_BY nvarchar(50) NOT NULL,
        CREATED_DATE datetime NOT NULL,
        UPDATED_BY nvarchar(50),
        UPDATED_DATE datetime,
        CONSTRAINT FK_CUSTOMER_DOMAIN_MAPPING_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES FA_ACCOUNT_LEDGER(ID),
        CONSTRAINT FK_CUSTOMER_DOMAIN_MAPPING_USER_CREATED FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_CUSTOMER_DOMAIN_MAPPING_USER_UPDATED FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
    PRINT 'Created table CUSTOMER_DOMAIN_MAPPING';
END
GO
