-- Dynamically drop all foreign keys referencing VND_VENDOR or VND_CUSTOMER_MAPPING
DECLARE @fk_name NVARCHAR(256), @parent_table NVARCHAR(256), @sql NVARCHAR(MAX);
DECLARE fk_cursor CURSOR FOR
    SELECT fk.name, OBJECT_NAME(fk.parent_object_id)
    FROM sys.foreign_keys fk
    WHERE fk.referenced_object_id IN (OBJECT_ID(N'[dbo].[VND_VENDOR]'), OBJECT_ID(N'[dbo].[VND_CUSTOMER_MAPPING]'));

OPEN fk_cursor;
FETCH NEXT FROM fk_cursor INTO @fk_name, @parent_table;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @sql = 'ALTER TABLE [dbo].' + QUOTENAME(@parent_table) + ' DROP CONSTRAINT ' + QUOTENAME(@fk_name);
    EXEC sp_executesql @sql;
    FETCH NEXT FROM fk_cursor INTO @fk_name, @parent_table;
END

CLOSE fk_cursor;
DEALLOCATE fk_cursor;
GO

-- Add new constraints pointing to FA_ACCOUNT_LEDGER
IF OBJECT_ID(N'[dbo].[PP_QUOTATION_COMPARISON_DECISION]', N'U') IS NOT NULL AND NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PP_COMP_DEC_REC_ACCOUNT_LEDGER]') AND parent_object_id = OBJECT_ID(N'[dbo].[PP_QUOTATION_COMPARISON_DECISION]'))
BEGIN
    ALTER TABLE [dbo].[PP_QUOTATION_COMPARISON_DECISION] WITH NOCHECK ADD CONSTRAINT [FK_PP_COMP_DEC_REC_ACCOUNT_LEDGER] FOREIGN KEY([RECOMMENDED_SUPPLIER_ID]) REFERENCES [dbo].[FA_ACCOUNT_LEDGER] ([ID]);
END
GO

IF OBJECT_ID(N'[dbo].[PP_QUOTATION_COMPARISON_DECISION]', N'U') IS NOT NULL AND NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PP_COMP_DEC_SEL_ACCOUNT_LEDGER]') AND parent_object_id = OBJECT_ID(N'[dbo].[PP_QUOTATION_COMPARISON_DECISION]'))
BEGIN
    ALTER TABLE [dbo].[PP_QUOTATION_COMPARISON_DECISION] WITH NOCHECK ADD CONSTRAINT [FK_PP_COMP_DEC_SEL_ACCOUNT_LEDGER] FOREIGN KEY([SELECTED_SUPPLIER_ID]) REFERENCES [dbo].[FA_ACCOUNT_LEDGER] ([ID]);
END
GO

IF OBJECT_ID(N'[dbo].[PP_SUPPLIER_PERFORMANCE]', N'U') IS NOT NULL AND NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PP_SUP_PERF_ACCOUNT_LEDGER]') AND parent_object_id = OBJECT_ID(N'[dbo].[PP_SUPPLIER_PERFORMANCE]'))
BEGIN
    ALTER TABLE [dbo].[PP_SUPPLIER_PERFORMANCE] WITH NOCHECK ADD CONSTRAINT [FK_PP_SUP_PERF_ACCOUNT_LEDGER] FOREIGN KEY([SUPPLIER_ID]) REFERENCES [dbo].[FA_ACCOUNT_LEDGER] ([ID]);
END
GO

-- Clean up orphaned records before adding foreign keys
IF OBJECT_ID(N'[dbo].[VENDOR_SATISFACTION_MAPPING]', N'U') IS NOT NULL
BEGIN
    DELETE FROM [dbo].[VENDOR_SATISFACTION_MAPPING] WHERE [VENDOR_ID] IS NOT NULL AND [VENDOR_ID] NOT IN (SELECT [ID] FROM [dbo].[FA_ACCOUNT_LEDGER]);
END

IF OBJECT_ID(N'[dbo].[VENDOR_SATISFACTION_MAPPING]', N'U') IS NOT NULL AND NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_VSM_ACCOUNT_LEDGER]') AND parent_object_id = OBJECT_ID(N'[dbo].[VENDOR_SATISFACTION_MAPPING]'))
BEGIN
    ALTER TABLE [dbo].[VENDOR_SATISFACTION_MAPPING] WITH NOCHECK ADD CONSTRAINT [FK_VSM_ACCOUNT_LEDGER] FOREIGN KEY([VENDOR_ID]) REFERENCES [dbo].[FA_ACCOUNT_LEDGER] ([ID]) ON DELETE CASCADE;
END
GO

IF OBJECT_ID(N'[dbo].[VENDOR_SATISFACTION_REMINDER_LOG]', N'U') IS NOT NULL
BEGIN
    DELETE FROM [dbo].[VENDOR_SATISFACTION_REMINDER_LOG] WHERE [VENDOR_ID] IS NOT NULL AND [VENDOR_ID] NOT IN (SELECT [ID] FROM [dbo].[FA_ACCOUNT_LEDGER]);
END

IF OBJECT_ID(N'[dbo].[VENDOR_SATISFACTION_REMINDER_LOG]', N'U') IS NOT NULL AND NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_VSRL_ACCOUNT_LEDGER]') AND parent_object_id = OBJECT_ID(N'[dbo].[VENDOR_SATISFACTION_REMINDER_LOG]'))
BEGIN
    ALTER TABLE [dbo].[VENDOR_SATISFACTION_REMINDER_LOG] WITH NOCHECK ADD CONSTRAINT [FK_VSRL_ACCOUNT_LEDGER] FOREIGN KEY([VENDOR_ID]) REFERENCES [dbo].[FA_ACCOUNT_LEDGER] ([ID]);
END
GO

-- Drop tables
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VND_CUSTOMER_MAPPING]') AND type in (N'U'))
BEGIN
    DROP TABLE [dbo].[VND_CUSTOMER_MAPPING];
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VND_VENDOR]') AND type in (N'U'))
BEGIN
    DROP TABLE [dbo].[VND_VENDOR];
END
GO
