-- Migration: 20260802_V1110.0__Alter_Mom_Detail_Id_Type_In_Mapping.sql
-- Purpose: Alter column MOM_DETAIL_ID in QMS_MOM_DETAILS_MATERIAL_MAPPING to BIGINT to match QMS_MOM_DETAILS.ID.

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MOM_DETAILS_MATERIAL_MAPPING') AND name = 'MOM_DETAIL_ID')
BEGIN
    ALTER TABLE QMS_MOM_DETAILS_MATERIAL_MAPPING ALTER COLUMN MOM_DETAIL_ID BIGINT NULL;
END
GO
