IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_TRANSACTION]') AND name = 'IS_REJECTION')
BEGIN
    ALTER TABLE [dbo].[ITEM_TRANSACTION]
    ADD [IS_REJECTION] BIT DEFAULT 0;
END
GO
