-- Alter columns in HR_EMPLOYEE_ABILITY to support longer values (MAX)
ALTER TABLE [dbo].[HR_EMPLOYEE_ABILITY] ALTER COLUMN [AUDITOR_TYPE] NVARCHAR(MAX) NULL;
ALTER TABLE [dbo].[HR_EMPLOYEE_ABILITY] ALTER COLUMN [AUDITEE_TYPE] NVARCHAR(MAX) NULL;
ALTER TABLE [dbo].[HR_EMPLOYEE_ABILITY] ALTER COLUMN [NCR_APPROVER_TYPE] NVARCHAR(MAX) NULL;
ALTER TABLE [dbo].[HR_EMPLOYEE_ABILITY] ALTER COLUMN [TASK_VERIFIER_TYPE] NVARCHAR(MAX) NULL;
ALTER TABLE [dbo].[HR_EMPLOYEE_ABILITY] ALTER COLUMN [TASK_TESTER_TYPE] NVARCHAR(MAX) NULL;
ALTER TABLE [dbo].[HR_EMPLOYEE_ABILITY] ALTER COLUMN [CHAIRED_TYPE] NVARCHAR(MAX) NULL;
ALTER TABLE [dbo].[HR_EMPLOYEE_ABILITY] ALTER COLUMN [HOST_TYPE] NVARCHAR(MAX) NULL;
ALTER TABLE [dbo].[HR_EMPLOYEE_ABILITY] ALTER COLUMN [PARTICIPANTS_TYPE] NVARCHAR(MAX) NULL;
