SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

-- 1. Add ATS configuration columns to AD_PREFIX_CREDENTIALS
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_PREFIX_CREDENTIALS]') AND name = 'ATS_PREFIX')
BEGIN
    ALTER TABLE [dbo].[AD_PREFIX_CREDENTIALS] ADD [ATS_PREFIX] NVARCHAR(20) NULL;
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_PREFIX_CREDENTIALS]') AND name = 'ATS_SUFFIX')
BEGIN
    ALTER TABLE [dbo].[AD_PREFIX_CREDENTIALS] ADD [ATS_SUFFIX] NVARCHAR(20) NULL;
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_PREFIX_CREDENTIALS]') AND name = 'ATS_DIGIT')
BEGIN
    ALTER TABLE [dbo].[AD_PREFIX_CREDENTIALS] ADD [ATS_DIGIT] INT NULL;
END;
GO

-- 2. Create AD_DOCUMENT_SEQUENCE table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AD_DOCUMENT_SEQUENCE]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[AD_DOCUMENT_SEQUENCE] (
        [ACCOUNT_YEAR] NVARCHAR(20) NOT NULL,
        [DOCUMENT_TYPE] NVARCHAR(50) NOT NULL,
        [CURRENT_NUMBER] INT NOT NULL DEFAULT 0,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_AD_DOCUMENT_SEQUENCE] PRIMARY KEY CLUSTERED ([ACCOUNT_YEAR], [DOCUMENT_TYPE])
    );
END;
GO

-- 3. Create unique filtered index on HR_EMPLOYEE.APPLICANT_CODE
-- Since there are no duplicate applicant codes in the DB, this is safe to execute.
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_HR_EMPLOYEE_APPLICANT_CODE' AND object_id = OBJECT_ID(N'[dbo].[HR_EMPLOYEE]'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UX_HR_EMPLOYEE_APPLICANT_CODE]
    ON [dbo].[HR_EMPLOYEE]([APPLICANT_CODE])
    WHERE [APPLICANT_CODE] IS NOT NULL;
END;
GO
