-- 1. Metadata Schema Audit (Governance)
CREATE TABLE BOS_AI_METADATA_AUDIT (
    ID              BIGINT IDENTITY(1,1) PRIMARY KEY,
    METADATA_TABLE  NVARCHAR(50)  NOT NULL,
    RECORD_ID       BIGINT        NOT NULL,
    ACTION_TYPE     NVARCHAR(10)  NOT NULL, -- INSERT, UPDATE, DELETE
    OLD_VALUE_JSON  NVARCHAR(MAX) NULL,
    NEW_VALUE_JSON  NVARCHAR(MAX) NULL,
    CHANGED_BY      NVARCHAR(50)  NOT NULL,
    CHANGED_DATE    DATETIME      DEFAULT GETDATE(),
    VERSION_NO      INT           DEFAULT 1
);

-- 2. AI Observability & Performance Metrics
CREATE TABLE BOS_AI_METRICS (
    ID                BIGINT IDENTITY(1,1) PRIMARY KEY,
    SESSION_ID        NVARCHAR(100) NOT NULL,
    PROMPT_TOKENS     INT           NOT NULL,
    COMPLETION_TOKENS INT           NOT NULL,
    DB_LATENCY_MS     INT           NOT NULL,
    LLM_LATENCY_MS    INT           NOT NULL,
    CACHE_HIT         NCHAR(1)      DEFAULT 'N',
    SKILLS_TRIGGERED  NVARCHAR(500) NULL,
    STATUS            NVARCHAR(20)  DEFAULT 'SUCCESS', -- SUCCESS, FAILURE, RATE_LIMITED
    ERROR_MSG         NVARCHAR(MAX) NULL,
    COST              DECIMAL(10,5) DEFAULT 0.0,
    CREATED_DATE      DATETIME      DEFAULT GETDATE()
);
