-- Alter tables to add CURRENCY_CODE
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[HR_LOAN_ISSUE]') AND name = 'CURRENCY_CODE')
BEGIN
    ALTER TABLE [dbo].[HR_LOAN_ISSUE] ADD [CURRENCY_CODE] NVARCHAR(10) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[HR_LOAN_APPLICATION]') AND name = 'CURRENCY_CODE')
BEGIN
    ALTER TABLE [dbo].[HR_LOAN_APPLICATION] ADD [CURRENCY_CODE] NVARCHAR(10) NULL;
END
GO

-- Update existing records to default to 'INR'
UPDATE [dbo].[HR_LOAN_ISSUE] SET [CURRENCY_CODE] = 'INR' WHERE [CURRENCY_CODE] IS NULL;
UPDATE [dbo].[HR_LOAN_APPLICATION] SET [CURRENCY_CODE] = 'INR' WHERE [CURRENCY_CODE] IS NULL;
GO

-- Set default constraint to 'INR'
IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE name = 'DF_HR_LOAN_ISSUE_CURRENCY_CODE')
BEGIN
    ALTER TABLE [dbo].[HR_LOAN_ISSUE] ADD CONSTRAINT [DF_HR_LOAN_ISSUE_CURRENCY_CODE] DEFAULT ('INR') FOR [CURRENCY_CODE];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE name = 'DF_HR_LOAN_APPLICATION_CURRENCY_CODE')
BEGIN
    ALTER TABLE [dbo].[HR_LOAN_APPLICATION] ADD CONSTRAINT [DF_HR_LOAN_APPLICATION_CURRENCY_CODE] DEFAULT ('INR') FOR [CURRENCY_CODE];
END
GO
