-- ============================================================================
-- V1205.0 - Fix HR_EMPLOYEE ATS Status Columns (Proper Flow Mapping)
-- 
-- ATS Valid Flow: PENDING → SENT → TO BE VERIFY → VERIFIED → REJECTED
--
-- Problem:
--   Migrated HR_EMPLOYEE records have legacy text or out-of-flow status values
--   (e.g., 'SUBMITTED', 'DRAFT', 'IN_PROGRESS', 'APPROVED', 'CONFIRM',
--    'CANCELLED', 'EXPIRED') which break the current ATS workflow and cause:
--     java.lang.NumberFormatException: For input string: "SUBMITTED"
--     SQLServerException: An error occurred while converting the nvarchar value
--                         to JDBC data type BIGINT.
--   Also, PHOTO/RESUME/PAYSLIP/AADHAR_VERIFIED_STATUS were NVARCHAR(50) instead
--   of BIGINT, mismatching the JPA @ManyToOne FK mapping.
--
-- Solution:
--   1. Ensure ONLY valid ATS flow statuses exist (Pending, SENT, TO BE VERIFY,
--      Verified, Rejected). Do NOT add SUBMITTED/DRAFT/IN_PROGRESS etc.
--   2. Remap text status values to nearest valid flow equivalent.
--   3. Remap numeric IDs for out-of-flow statuses to valid flow IDs.
--   4. ALTER nvarchar verified-status columns to BIGINT.
--   5. Add FK constraints.
-- ============================================================================

-- Step 1: Ensure ONLY valid ATS flow statuses exist in AD_STATUS_MASTER
BEGIN TRY IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PENDING')    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Pending');    END TRY BEGIN CATCH END CATCH;
BEGIN TRY IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'SENT')       INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('SENT');       END TRY BEGIN CATCH END CATCH;
BEGIN TRY IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'TO BE VERIFY') INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('TO BE VERIFY'); END TRY BEGIN CATCH END CATCH;
BEGIN TRY IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'VERIFIED')   INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Verified');   END TRY BEGIN CATCH END CATCH;
BEGIN TRY IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'REJECTED')   INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Rejected');   END TRY BEGIN CATCH END CATCH;
GO

-- Step 2: Remap text status values in all status columns to valid ATS flow IDs
-- Mapping logic:
--   SUBMITTED    -> TO BE VERIFY  (submitted = awaiting verification, closest fit)
--   DRAFT        -> Pending       (not started)
--   IN_PROGRESS  -> Pending       (still pending)
--   APPROVED     -> Verified      (approved = verified)
--   CONFIRM      -> TO BE VERIFY  (confirm = needs verification)
--   TO BE VERIFIED -> TO BE VERIFY (canonical rename)
--   CANCELLED    -> Rejected      (cancelled = rejected)
--   EXPIRED      -> Rejected      (expired = rejected)
--   Others       -> match by name if possible, else leave (will be caught by Step 3)

DECLARE @remapByName NVARCHAR(MAX);
SET @remapByName = '
UPDATE e SET e.{col} = (
    SELECT TOP 1 s2.ID FROM AD_STATUS_MASTER s2 WHERE s2.NAME =
    CASE UPPER(TRIM(CAST(e.{col} AS VARCHAR(100))))
        WHEN ''SUBMITTED''     THEN ''TO BE VERIFY''
        WHEN ''DRAFT''         THEN ''Pending''
        WHEN ''IN_PROGRESS''   THEN ''Pending''
        WHEN ''APPROVED''      THEN ''Verified''
        WHEN ''CONFIRM''       THEN ''TO BE VERIFY''
        WHEN ''TO BE VERIFIED'' THEN ''TO BE VERIFY''
        WHEN ''CANCELLED''     THEN ''Rejected''
        WHEN ''EXPIRED''       THEN ''Rejected''
        ELSE NULL
    END
)
FROM HR_EMPLOYEE e
WHERE TRY_CAST(e.{col} AS BIGINT) IS NULL AND e.{col} IS NOT NULL
';

BEGIN TRY EXEC(REPLACE(@remapByName, '{col}', 'STATUS'));                       PRINT 'STATUS text remapped'; END TRY BEGIN CATCH PRINT 'Warning STATUS: ' + ERROR_MESSAGE(); END CATCH;
GO
DECLARE @remapByName NVARCHAR(MAX);
SET @remapByName = 'UPDATE e SET e.{col} = (SELECT TOP 1 s2.ID FROM AD_STATUS_MASTER s2 WHERE s2.NAME = CASE UPPER(TRIM(CAST(e.{col} AS VARCHAR(100)))) WHEN ''SUBMITTED'' THEN ''TO BE VERIFY'' WHEN ''DRAFT'' THEN ''Pending'' WHEN ''IN_PROGRESS'' THEN ''Pending'' WHEN ''APPROVED'' THEN ''Verified'' WHEN ''CONFIRM'' THEN ''TO BE VERIFY'' WHEN ''TO BE VERIFIED'' THEN ''TO BE VERIFY'' WHEN ''CANCELLED'' THEN ''Rejected'' WHEN ''EXPIRED'' THEN ''Rejected'' ELSE NULL END) FROM HR_EMPLOYEE e WHERE TRY_CAST(e.{col} AS BIGINT) IS NULL AND e.{col} IS NOT NULL';
BEGIN TRY EXEC(REPLACE(@remapByName, '{col}', 'CALL_STATUS'));                  PRINT 'CALL_STATUS text remapped'; END TRY BEGIN CATCH PRINT 'Warning CALL_STATUS: ' + ERROR_MESSAGE(); END CATCH;
BEGIN TRY EXEC(REPLACE(@remapByName, '{col}', 'INTERVIEW_STATUS'));             PRINT 'INTERVIEW_STATUS text remapped'; END TRY BEGIN CATCH PRINT 'Warning INTERVIEW_STATUS: ' + ERROR_MESSAGE(); END CATCH;
BEGIN TRY EXEC(REPLACE(@remapByName, '{col}', 'OFFER_STATUS'));                 PRINT 'OFFER_STATUS text remapped'; END TRY BEGIN CATCH PRINT 'Warning OFFER_STATUS: ' + ERROR_MESSAGE(); END CATCH;
BEGIN TRY EXEC(REPLACE(@remapByName, '{col}', 'VERIFICATION_STATUS'));          PRINT 'VERIFICATION_STATUS text remapped'; END TRY BEGIN CATCH PRINT 'Warning VERIFICATION_STATUS: ' + ERROR_MESSAGE(); END CATCH;
BEGIN TRY EXEC(REPLACE(@remapByName, '{col}', 'BACKGROUND_VERIFICATION_STATUS')); PRINT 'BG_VER_STATUS text remapped'; END TRY BEGIN CATCH PRINT 'Warning BG_VER_STATUS: ' + ERROR_MESSAGE(); END CATCH;
BEGIN TRY EXEC(REPLACE(@remapByName, '{col}', 'ATS_OVERALL_STATUS'));           PRINT 'ATS_OVERALL_STATUS text remapped'; END TRY BEGIN CATCH PRINT 'Warning ATS_OVERALL_STATUS: ' + ERROR_MESSAGE(); END CATCH;
GO

-- Step 3: Remap numeric IDs pointing to out-of-flow statuses -> valid flow IDs
-- Covers: SUBMITTED, DRAFT, IN_PROGRESS, APPROVED, CONFIRM, TO BE VERIFIED, CANCELLED, EXPIRED
BEGIN TRY
    UPDATE HR_EMPLOYEE SET CALL_STATUS = CASE CALL_STATUS
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='SUBMITTED')    THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='DRAFT')        THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Pending')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='IN_PROGRESS')  THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Pending')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='APPROVED')     THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Verified')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='CONFIRM')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFIED')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='CANCELLED')    THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Rejected')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='EXPIRED')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Rejected')
        ELSE CALL_STATUS END
    WHERE CALL_STATUS IS NOT NULL
      AND CALL_STATUS NOT IN (SELECT ID FROM AD_STATUS_MASTER WHERE NAME IN ('Pending','SENT','TO BE VERIFY','Verified','Rejected'));
    PRINT 'CALL_STATUS IDs remapped: ' + CAST(@@ROWCOUNT AS VARCHAR);
END TRY BEGIN CATCH PRINT 'Warning CALL_STATUS ID remap: ' + ERROR_MESSAGE(); END CATCH;
GO

BEGIN TRY
    UPDATE HR_EMPLOYEE SET INTERVIEW_STATUS = CASE INTERVIEW_STATUS
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='SUBMITTED')    THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='DRAFT')        THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Pending')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='IN_PROGRESS')  THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Pending')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='APPROVED')     THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Verified')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='CONFIRM')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFIED')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='CANCELLED')    THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Rejected')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='EXPIRED')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Rejected')
        ELSE INTERVIEW_STATUS END
    WHERE INTERVIEW_STATUS IS NOT NULL
      AND INTERVIEW_STATUS NOT IN (SELECT ID FROM AD_STATUS_MASTER WHERE NAME IN ('Pending','SENT','TO BE VERIFY','Verified','Rejected'));
    PRINT 'INTERVIEW_STATUS IDs remapped: ' + CAST(@@ROWCOUNT AS VARCHAR);
END TRY BEGIN CATCH PRINT 'Warning INTERVIEW_STATUS ID remap: ' + ERROR_MESSAGE(); END CATCH;
GO

BEGIN TRY
    UPDATE HR_EMPLOYEE SET OFFER_STATUS = CASE OFFER_STATUS
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='SUBMITTED')    THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='DRAFT')        THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Pending')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='IN_PROGRESS')  THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Pending')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='APPROVED')     THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Verified')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='CONFIRM')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFIED')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='CANCELLED')    THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Rejected')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='EXPIRED')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Rejected')
        ELSE OFFER_STATUS END
    WHERE OFFER_STATUS IS NOT NULL
      AND OFFER_STATUS NOT IN (SELECT ID FROM AD_STATUS_MASTER WHERE NAME IN ('Pending','SENT','TO BE VERIFY','Verified','Rejected'));
    PRINT 'OFFER_STATUS IDs remapped: ' + CAST(@@ROWCOUNT AS VARCHAR);
END TRY BEGIN CATCH PRINT 'Warning OFFER_STATUS ID remap: ' + ERROR_MESSAGE(); END CATCH;
GO

BEGIN TRY
    UPDATE HR_EMPLOYEE SET VERIFICATION_STATUS = CASE VERIFICATION_STATUS
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='SUBMITTED')    THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='DRAFT')        THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Pending')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='IN_PROGRESS')  THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Pending')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='APPROVED')     THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Verified')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='CONFIRM')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFIED')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='CANCELLED')    THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Rejected')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='EXPIRED')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Rejected')
        ELSE VERIFICATION_STATUS END
    WHERE VERIFICATION_STATUS IS NOT NULL
      AND VERIFICATION_STATUS NOT IN (SELECT ID FROM AD_STATUS_MASTER WHERE NAME IN ('Pending','SENT','TO BE VERIFY','Verified','Rejected'));
    PRINT 'VERIFICATION_STATUS IDs remapped: ' + CAST(@@ROWCOUNT AS VARCHAR);
END TRY BEGIN CATCH PRINT 'Warning VERIFICATION_STATUS ID remap: ' + ERROR_MESSAGE(); END CATCH;
GO

BEGIN TRY
    UPDATE HR_EMPLOYEE SET ATS_OVERALL_STATUS = CASE ATS_OVERALL_STATUS
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='SUBMITTED')    THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='DRAFT')        THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Pending')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='IN_PROGRESS')  THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Pending')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='APPROVED')     THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Verified')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='CONFIRM')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFIED')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='TO BE VERIFY')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='CANCELLED')    THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Rejected')
        WHEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='EXPIRED')      THEN (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME='Rejected')
        ELSE ATS_OVERALL_STATUS END
    WHERE ATS_OVERALL_STATUS IS NOT NULL
      AND ATS_OVERALL_STATUS NOT IN (SELECT ID FROM AD_STATUS_MASTER WHERE NAME IN ('Pending','SENT','TO BE VERIFY','Verified','Rejected'));
    PRINT 'ATS_OVERALL_STATUS IDs remapped: ' + CAST(@@ROWCOUNT AS VARCHAR);
END TRY BEGIN CATCH PRINT 'Warning ATS_OVERALL_STATUS ID remap: ' + ERROR_MESSAGE(); END CATCH;
GO

-- Step 4: Fix nvarchar PHOTO/RESUME/PAYSLIP/AADHAR_VERIFIED_STATUS columns
-- These must be BIGINT to match the JPA @ManyToOne FK mapping

BEGIN TRY
    -- Fix text values first (same mapping)
    UPDATE e SET e.PHOTO_VERIFIED_STATUS = CAST(s.ID AS NVARCHAR(50))
    FROM HR_EMPLOYEE e INNER JOIN AD_STATUS_MASTER s
        ON UPPER(TRIM(s.NAME)) = UPPER(TRIM(e.PHOTO_VERIFIED_STATUS))
    WHERE TRY_CAST(e.PHOTO_VERIFIED_STATUS AS BIGINT) IS NULL AND e.PHOTO_VERIFIED_STATUS IS NOT NULL;

    UPDATE e SET e.RESUME_VERIFIED_STATUS = CAST(s.ID AS NVARCHAR(50))
    FROM HR_EMPLOYEE e INNER JOIN AD_STATUS_MASTER s
        ON UPPER(TRIM(s.NAME)) = UPPER(TRIM(e.RESUME_VERIFIED_STATUS))
    WHERE TRY_CAST(e.RESUME_VERIFIED_STATUS AS BIGINT) IS NULL AND e.RESUME_VERIFIED_STATUS IS NOT NULL;

    UPDATE e SET e.PAYSLIP_VERIFIED_STATUS = CAST(s.ID AS NVARCHAR(50))
    FROM HR_EMPLOYEE e INNER JOIN AD_STATUS_MASTER s
        ON UPPER(TRIM(s.NAME)) = UPPER(TRIM(e.PAYSLIP_VERIFIED_STATUS))
    WHERE TRY_CAST(e.PAYSLIP_VERIFIED_STATUS AS BIGINT) IS NULL AND e.PAYSLIP_VERIFIED_STATUS IS NOT NULL;

    UPDATE e SET e.AADHAR_VERIFIED_STATUS = CAST(s.ID AS NVARCHAR(50))
    FROM HR_EMPLOYEE e INNER JOIN AD_STATUS_MASTER s
        ON UPPER(TRIM(s.NAME)) = UPPER(TRIM(e.AADHAR_VERIFIED_STATUS))
    WHERE TRY_CAST(e.AADHAR_VERIFIED_STATUS AS BIGINT) IS NULL AND e.AADHAR_VERIFIED_STATUS IS NOT NULL;

    PRINT 'Verified status text values fixed';
END TRY BEGIN CATCH PRINT 'Warning fixing verified status text: ' + ERROR_MESSAGE(); END CATCH;
GO

BEGIN TRY
    IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_PHOTO_VERIFIED_STATUS')
        ALTER TABLE HR_EMPLOYEE DROP CONSTRAINT FK_HR_EMPLOYEE_PHOTO_VERIFIED_STATUS;
    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE' AND COLUMN_NAME='PHOTO_VERIFIED_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
        ALTER TABLE HR_EMPLOYEE ALTER COLUMN PHOTO_VERIFIED_STATUS BIGINT NULL;
    PRINT 'PHOTO_VERIFIED_STATUS -> BIGINT';
END TRY BEGIN CATCH PRINT 'Warning PHOTO: ' + ERROR_MESSAGE(); END CATCH;
GO

BEGIN TRY
    IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_RESUME_VERIFIED_STATUS')
        ALTER TABLE HR_EMPLOYEE DROP CONSTRAINT FK_HR_EMPLOYEE_RESUME_VERIFIED_STATUS;
    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE' AND COLUMN_NAME='RESUME_VERIFIED_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
        ALTER TABLE HR_EMPLOYEE ALTER COLUMN RESUME_VERIFIED_STATUS BIGINT NULL;
    PRINT 'RESUME_VERIFIED_STATUS -> BIGINT';
END TRY BEGIN CATCH PRINT 'Warning RESUME: ' + ERROR_MESSAGE(); END CATCH;
GO

BEGIN TRY
    IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_PAYSLIP_VERIFIED_STATUS')
        ALTER TABLE HR_EMPLOYEE DROP CONSTRAINT FK_HR_EMPLOYEE_PAYSLIP_VERIFIED_STATUS;
    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE' AND COLUMN_NAME='PAYSLIP_VERIFIED_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
        ALTER TABLE HR_EMPLOYEE ALTER COLUMN PAYSLIP_VERIFIED_STATUS BIGINT NULL;
    PRINT 'PAYSLIP_VERIFIED_STATUS -> BIGINT';
END TRY BEGIN CATCH PRINT 'Warning PAYSLIP: ' + ERROR_MESSAGE(); END CATCH;
GO

BEGIN TRY
    IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_AADHAR_VERIFIED_STATUS')
        ALTER TABLE HR_EMPLOYEE DROP CONSTRAINT FK_HR_EMPLOYEE_AADHAR_VERIFIED_STATUS;
    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE' AND COLUMN_NAME='AADHAR_VERIFIED_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
        ALTER TABLE HR_EMPLOYEE ALTER COLUMN AADHAR_VERIFIED_STATUS BIGINT NULL;
    PRINT 'AADHAR_VERIFIED_STATUS -> BIGINT';
END TRY BEGIN CATCH PRINT 'Warning AADHAR: ' + ERROR_MESSAGE(); END CATCH;
GO

-- Step 5: Add FK constraints on BIGINT columns
BEGIN TRY
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_PHOTO_VERIFIED_STATUS')
        ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_PHOTO_VERIFIED_STATUS FOREIGN KEY (PHOTO_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_RESUME_VERIFIED_STATUS')
        ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_RESUME_VERIFIED_STATUS FOREIGN KEY (RESUME_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_PAYSLIP_VERIFIED_STATUS')
        ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_PAYSLIP_VERIFIED_STATUS FOREIGN KEY (PAYSLIP_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_AADHAR_VERIFIED_STATUS')
        ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_AADHAR_VERIFIED_STATUS FOREIGN KEY (AADHAR_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
    PRINT 'FK constraints added';
END TRY BEGIN CATCH PRINT 'Warning FK: ' + ERROR_MESSAGE(); END CATCH;
GO

-- Step 6: Fix HR_EMPLOYEE_SELF_ASSESSMENT.SELF_ASSESSMENT_STATUS (NVARCHAR -> BIGINT)
-- This column had 'SUBMITTED' text values which caused NumberFormatException.
-- Map: SUBMITTED -> TO BE VERIFY, DRAFT/68 -> Pending

BEGIN TRY
    -- Remap text 'SUBMITTED' -> TO BE VERIFY ID
    UPDATE HR_EMPLOYEE_SELF_ASSESSMENT 
    SET SELF_ASSESSMENT_STATUS = CAST((SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME = 'TO BE VERIFY') AS NVARCHAR(50))
    WHERE UPPER(TRIM(ISNULL(SELF_ASSESSMENT_STATUS,''))) = 'SUBMITTED';
    PRINT 'SELF_ASSESSMENT: SUBMITTED remapped: ' + CAST(@@ROWCOUNT AS VARCHAR);

    -- Remap other invalid text values
    UPDATE HR_EMPLOYEE_SELF_ASSESSMENT 
    SET SELF_ASSESSMENT_STATUS = CAST((SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE NAME = 'Pending') AS NVARCHAR(50))
    WHERE UPPER(TRIM(ISNULL(SELF_ASSESSMENT_STATUS,''))) IN ('DRAFT','IN_PROGRESS')
       OR (TRY_CAST(SELF_ASSESSMENT_STATUS AS BIGINT) = (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(NAME)='DRAFT'));
    PRINT 'SELF_ASSESSMENT: DRAFT remapped: ' + CAST(@@ROWCOUNT AS VARCHAR);

    -- Drop default constraint if exists
    DECLARE @saConstraint NVARCHAR(200);
    SELECT @saConstraint = d.name 
    FROM sys.default_constraints d
    JOIN sys.columns c ON d.parent_object_id = c.object_id AND d.parent_column_id = c.column_id
    WHERE c.object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND c.name = 'SELF_ASSESSMENT_STATUS';
    IF @saConstraint IS NOT NULL
        EXEC('ALTER TABLE HR_EMPLOYEE_SELF_ASSESSMENT DROP CONSTRAINT ' + @saConstraint);

    -- Drop FK if exists
    IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMP_SELF_ASSESS_STATUS')
        ALTER TABLE HR_EMPLOYEE_SELF_ASSESSMENT DROP CONSTRAINT FK_HR_EMP_SELF_ASSESS_STATUS;

    -- Alter NVARCHAR -> BIGINT
    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_SELF_ASSESSMENT' AND COLUMN_NAME='SELF_ASSESSMENT_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
        ALTER TABLE HR_EMPLOYEE_SELF_ASSESSMENT ALTER COLUMN SELF_ASSESSMENT_STATUS BIGINT NULL;
    PRINT 'SELF_ASSESSMENT_STATUS altered to BIGINT';

    -- Add FK
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMP_SELF_ASSESS_STATUS')
        ALTER TABLE HR_EMPLOYEE_SELF_ASSESSMENT ADD CONSTRAINT FK_HR_EMP_SELF_ASSESS_STATUS 
        FOREIGN KEY (SELF_ASSESSMENT_STATUS) REFERENCES AD_STATUS_MASTER(ID);
    PRINT 'SELF_ASSESSMENT_STATUS FK added';
END TRY BEGIN CATCH PRINT 'Warning SELF_ASSESSMENT_STATUS: ' + ERROR_MESSAGE(); END CATCH;
GO

PRINT 'V1205.0 - HR_EMPLOYEE ATS status normalization complete (flow-aware mapping).';
