-- Migration V390.0: Add WEEK_DAYS to QMS_SCHEDULE_MEETING_CONFIG table
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_SCHEDULE_MEETING_CONFIG') AND name = 'WEEK_DAYS')
BEGIN
    ALTER TABLE QMS_SCHEDULE_MEETING_CONFIG ADD WEEK_DAYS NVARCHAR(100) NULL;
END
GO
