-- Migration: 20260802_V1108.0__Add_LOP_Fields_To_HR_Setting_Master.sql
-- Purpose: Add LOP Mode, LOP Is Fixed, LOP Fixed Amount, and LOP Formula columns to HR_SETTING_MASTER table and sync existing values from AD_APP_PREFERENCE.

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_SETTING_MASTER') AND name = 'LOP_MODE')
BEGIN
    ALTER TABLE HR_SETTING_MASTER ADD LOP_MODE NVARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_SETTING_MASTER') AND name = 'LOP_IS_FIXED')
BEGIN
    ALTER TABLE HR_SETTING_MASTER ADD LOP_IS_FIXED NVARCHAR(10) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_SETTING_MASTER') AND name = 'LOP_FIXED_AMOUNT')
BEGIN
    ALTER TABLE HR_SETTING_MASTER ADD LOP_FIXED_AMOUNT DECIMAL(18,2) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_SETTING_MASTER') AND name = 'LOP_FORMULA')
BEGIN
    ALTER TABLE HR_SETTING_MASTER ADD LOP_FORMULA NVARCHAR(500) NULL;
END
GO
