-- Create SM_INVOICE_HEADER table
IF OBJECT_ID('SM_INVOICE_HEADER', 'U') IS NULL
BEGIN
    CREATE TABLE SM_INVOICE_HEADER (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        INVOICE_NO NVARCHAR(50) NOT NULL UNIQUE,
        INVOICE_DATE DATETIME NOT NULL,
        CUSTOMER_ID BIGINT NULL,
        BILLING_ADDRESS_ID BIGINT NULL,
        SHIPPING_ADDRESS_ID BIGINT NULL,
        PAYMENT_TERMS NVARCHAR(50) NULL,
        DELIVERY_TERMS NVARCHAR(50) NULL,
        CURRENCY_CODE NVARCHAR(15) NULL,
        EXCHANGE_RATE NUMERIC(12, 4) NULL,
        CUSTOMER_PO NVARCHAR(50) NULL,
        REMARKS NVARCHAR(500) NULL,
        SUB_TOTAL NUMERIC(12, 2) NULL,
        DISCOUNT_AMOUNT NUMERIC(12, 2) NULL,
        TAXABLE_AMOUNT NUMERIC(12, 2) NULL,
        CGST_AMOUNT NUMERIC(12, 2) NULL,
        SGST_AMOUNT NUMERIC(12, 2) NULL,
        IGST_AMOUNT NUMERIC(12, 2) NULL,
        GRAND_TOTAL NUMERIC(12, 2) NULL,
        CREATED_BY NVARCHAR(50) NULL,
        CREATED_DATE DATETIME NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_SM_INVOICE_HDR_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SM_INVOICE_HDR_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END

-- Create SM_INVOICE_DETAIL table
IF OBJECT_ID('SM_INVOICE_DETAIL', 'U') IS NULL
BEGIN
    CREATE TABLE SM_INVOICE_DETAIL (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        INVOICE_REF_ID BIGINT NOT NULL,
        SALES_ORDER_ID BIGINT NOT NULL,
        SALES_ORDER_NO NVARCHAR(50) NULL,
        SALES_ORDER_LINE_ID BIGINT NOT NULL,
        PART_ID BIGINT NULL,
        PART_NO NVARCHAR(50) NULL,
        PART_NAME NVARCHAR(500) NULL,
        UOM NVARCHAR(20) NULL,
        QTY INT NULL,
        PRICE NUMERIC(12, 2) NULL,
        DISCOUNT_PER NUMERIC(12, 2) NULL,
        CGST_PER NUMERIC(12, 2) NULL,
        SGST_PER NUMERIC(12, 2) NULL,
        IGST_PER NUMERIC(12, 2) NULL,
        CGST_AMOUNT NUMERIC(12, 2) NULL,
        SGST_AMOUNT NUMERIC(12, 2) NULL,
        IGST_AMOUNT NUMERIC(12, 2) NULL,
        TAX_AMOUNT NUMERIC(12, 2) NULL,
        NET_AMOUNT NUMERIC(12, 2) NULL,
        CREATED_BY NVARCHAR(50) NULL,
        CREATED_DATE DATETIME NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_SM_INVOICE_DETAIL_HEADER FOREIGN KEY (INVOICE_REF_ID) REFERENCES SM_INVOICE_HEADER(ID) ON DELETE CASCADE,
        CONSTRAINT FK_SM_INVOICE_DTL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SM_INVOICE_DTL_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
