-- Create EXCHANGE_RATE table
IF OBJECT_ID('EXCHANGE_RATE', 'U') IS NULL
BEGIN
    CREATE TABLE EXCHANGE_RATE (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        FROM_CURRENCY NVARCHAR(15) NOT NULL,
        TO_CURRENCY NVARCHAR(15) NOT NULL,
        RATE NUMERIC(18, 6) NOT NULL,
        RATE_DATE DATE NOT NULL,
        SOURCE NVARCHAR(100) NULL,
        CONSTRAINT UC_EXCHANGE_RATE UNIQUE (FROM_CURRENCY, TO_CURRENCY, RATE_DATE)
    );
END
GO

-- Add rate freeze columns to SM_INVOICE_HEADER table
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SM_INVOICE_HEADER') AND name = 'BASE_CURRENCY')
BEGIN
    ALTER TABLE SM_INVOICE_HEADER ADD BASE_CURRENCY NVARCHAR(15) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SM_INVOICE_HEADER') AND name = 'RATE_DATE')
BEGIN
    ALTER TABLE SM_INVOICE_HEADER ADD RATE_DATE DATE NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SM_INVOICE_HEADER') AND name = 'EXCHANGE_RATE_SOURCE')
BEGIN
    ALTER TABLE SM_INVOICE_HEADER ADD EXCHANGE_RATE_SOURCE NVARCHAR(100) NULL;
END
GO
