-- Migration: V370.0 Standardize Description/SOP Columns to NVARCHAR(MAX)
-- Date: 2026-06-26
-- Author: Antigravity

-- 1. AD_DIVISION
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('AD_DIVISION') AND name = 'DESCRIPTION')
BEGIN
    ALTER TABLE AD_DIVISION ALTER COLUMN DESCRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered AD_DIVISION.DESCRIPTION to NVARCHAR(MAX)';
END

-- 2. MST_HSN_MASTER (DECRIPTION)
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('MST_HSN_MASTER') AND name = 'DECRIPTION')
BEGIN
    ALTER TABLE MST_HSN_MASTER ALTER COLUMN DECRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered MST_HSN_MASTER.DECRIPTION to NVARCHAR(MAX)';
END

-- 3. HR_PAYROLL_STRUCTURE
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_PAYROLL_STRUCTURE') AND name = 'DESCRIPTION')
BEGIN
    ALTER TABLE HR_PAYROLL_STRUCTURE ALTER COLUMN DESCRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered HR_PAYROLL_STRUCTURE.DESCRIPTION to NVARCHAR(MAX)';
END

-- 4. COMPANY_HOLIDAYS
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('COMPANY_HOLIDAYS') AND name = 'DESCRIPTION')
BEGIN
    ALTER TABLE COMPANY_HOLIDAYS ALTER COLUMN DESCRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered COMPANY_HOLIDAYS.DESCRIPTION to NVARCHAR(MAX)';
END

-- 5. HR_INDUCTION_ROUND
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_INDUCTION_ROUND') AND name = 'DESCRIPTION')
BEGIN
    ALTER TABLE HR_INDUCTION_ROUND ALTER COLUMN DESCRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered HR_INDUCTION_ROUND.DESCRIPTION to NVARCHAR(MAX)';
END

-- 6. SM_TYPE_OF_SERVICE
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SM_TYPE_OF_SERVICE') AND name = 'DESCRIPTION')
BEGIN
    ALTER TABLE SM_TYPE_OF_SERVICE ALTER COLUMN DESCRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered SM_TYPE_OF_SERVICE.DESCRIPTION to NVARCHAR(MAX)';
END

-- 7. NPD_INVENTORY_TYPE
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('NPD_INVENTORY_TYPE') AND name = 'DESCRIPTION')
BEGIN
    ALTER TABLE NPD_INVENTORY_TYPE ALTER COLUMN DESCRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered NPD_INVENTORY_TYPE.DESCRIPTION to NVARCHAR(MAX)';
END

-- 8. NPD_MATERIAL_GRADE (DECRIPTION)
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('NPD_MATERIAL_GRADE') AND name = 'DECRIPTION')
BEGIN
    ALTER TABLE NPD_MATERIAL_GRADE ALTER COLUMN DECRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered NPD_MATERIAL_GRADE.DECRIPTION to NVARCHAR(MAX)';
END

-- 9. NPD_MATERIAL_TYPE (DECRIPTION)
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('NPD_MATERIAL_TYPE') AND name = 'DECRIPTION')
BEGIN
    ALTER TABLE NPD_MATERIAL_TYPE ALTER COLUMN DECRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered NPD_MATERIAL_TYPE.DECRIPTION to NVARCHAR(MAX)';
END

-- 10. NPD_SHAPE_MASTER (DECRIPTION)
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('NPD_SHAPE_MASTER') AND name = 'DECRIPTION')
BEGIN
    ALTER TABLE NPD_SHAPE_MASTER ALTER COLUMN DECRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered NPD_SHAPE_MASTER.DECRIPTION to NVARCHAR(MAX)';
END

-- 11. NPD_MATERIAL_CONDITIONS
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('NPD_MATERIAL_CONDITIONS') AND name = 'DESCRIPTION')
BEGIN
    ALTER TABLE NPD_MATERIAL_CONDITIONS ALTER COLUMN DESCRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered NPD_MATERIAL_CONDITIONS.DESCRIPTION to NVARCHAR(MAX)';
END

-- 12. NPD_FEASIBILITY_CATEGORY (description - lowercase in table definition)
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('NPD_FEASIBILITY_CATEGORY') AND name = 'description')
BEGIN
    ALTER TABLE NPD_FEASIBILITY_CATEGORY ALTER COLUMN description NVARCHAR(MAX) NULL;
    PRINT 'Altered NPD_FEASIBILITY_CATEGORY.description to NVARCHAR(MAX)';
END

-- 13. NPD_PROCESS
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('NPD_PROCESS') AND name = 'DESCRIPTION')
BEGIN
    ALTER TABLE NPD_PROCESS ALTER COLUMN DESCRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered NPD_PROCESS.DESCRIPTION to NVARCHAR(MAX)';
END

-- 14. QMS_MODEL_NAME
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MODEL_NAME') AND name = 'DESCRIPTION')
BEGIN
    ALTER TABLE QMS_MODEL_NAME ALTER COLUMN DESCRIPTION NVARCHAR(MAX) NULL;
    PRINT 'Altered QMS_MODEL_NAME.DESCRIPTION to NVARCHAR(MAX)';
END
