-- Update directory_path for company 1 from D:\NUTECH_DOCUMENTS to BOS_DOCUMENTS to support Docker volume persistence
IF EXISTS (SELECT 1 FROM AD_COMPANY_CREDENTIAL WHERE ID = 1)
BEGIN
    UPDATE AD_COMPANY_CREDENTIAL
    SET DIRECTORY_PATH = 'BOS_DOCUMENTS'
    WHERE ID = 1 AND (DIRECTORY_PATH = 'D:\NUTECH_DOCUMENTS' OR DIRECTORY_PATH IS NULL OR DIRECTORY_PATH = '');
END
