-- Seed 'AMENDED' status in AD_STATUS_MASTER if it does not already exist
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'AMENDED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('AMENDED');
