-- SQL Migration: Drop ENABLED_MODULES column from CLI_CLIENT_MASTER if present
-- Created: 2026-07-24

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[CLI_CLIENT_MASTER]') AND name = 'ENABLED_MODULES')
BEGIN
    ALTER TABLE CLI_CLIENT_MASTER DROP COLUMN ENABLED_MODULES;
END;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_LICENSE]') AND name = 'ENABLED_MODULES')
BEGIN
    ALTER TABLE CM_CLIENT_LICENSE DROP COLUMN ENABLED_MODULES;
END;
