-- Purpose: Add performance indexes on QMS_CLOSE_MOM_AND_VERIFY and QMS_MOM_DETAILS for fast lookup in Close MOM and MOM Approval
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_CLOSE_MOM_VERIFY_ACTION_ITEM' AND object_id = OBJECT_ID('QMS_CLOSE_MOM_AND_VERIFY'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CLOSE_MOM_VERIFY_ACTION_ITEM 
    ON [dbo].[QMS_CLOSE_MOM_AND_VERIFY] ([ACTION_ITEM_ID], [ID] DESC)
    INCLUDE ([NEW_STATUS], [ASSIGNED_TO_ID], [ASSIGNED_BY_ID], [ACTION_TAKEN], [ACTION_OBSERVATION], [REJECTION_REMARKS], [ATTACHMENT_INFO]);
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_MOM_DETAILS_ACTIVE_ASSIGNED_TO' AND object_id = OBJECT_ID('QMS_MOM_DETAILS'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MOM_DETAILS_ACTIVE_ASSIGNED_TO
    ON [dbo].[QMS_MOM_DETAILS] ([IS_ACTIVE], [ASSIGNED_TO_ID], [MOM_ID]);
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_MOM_DETAILS_ACTIVE_ASSIGNED_BY' AND object_id = OBJECT_ID('QMS_MOM_DETAILS'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MOM_DETAILS_ACTIVE_ASSIGNED_BY
    ON [dbo].[QMS_MOM_DETAILS] ([IS_ACTIVE], [ASSIGNED_BY_ID], [MOM_ID]);
END
