-- =======================================================================================
-- MIGRATION SCRIPT: Drop Remaining Incoming Inspection Tables and References
-- DB TYPE: Microsoft SQL Server
-- VERSION: 1140.1
-- =======================================================================================

-- 1. Drop Foreign Key on PP_PURCHASE_RETURN_HEAD
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_PP_PURCHASE_RETURN_INSP' AND TABLE_NAME = 'PP_PURCHASE_RETURN_HEAD')
BEGIN
    ALTER TABLE PP_PURCHASE_RETURN_HEAD DROP CONSTRAINT FK_PP_PURCHASE_RETURN_INSP;
END
GO

-- 2. Drop Column INSPECTION_HEAD_ID from PP_PURCHASE_RETURN_HEAD
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PP_PURCHASE_RETURN_HEAD' AND COLUMN_NAME = 'INSPECTION_HEAD_ID')
BEGIN
    ALTER TABLE PP_PURCHASE_RETURN_HEAD DROP COLUMN INSPECTION_HEAD_ID;
END
GO

-- 3. Drop Foreign Key on PP_PURCHASE_RETURN_TRANS
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_PP_PURCHASE_RETURN_TRANS_INSP' AND TABLE_NAME = 'PP_PURCHASE_RETURN_TRANS')
BEGIN
    ALTER TABLE PP_PURCHASE_RETURN_TRANS DROP CONSTRAINT FK_PP_PURCHASE_RETURN_TRANS_INSP;
END
GO

-- 4. Drop Column INSPECTION_TRANS_ID from PP_PURCHASE_RETURN_TRANS
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PP_PURCHASE_RETURN_TRANS' AND COLUMN_NAME = 'INSPECTION_TRANS_ID')
BEGIN
    ALTER TABLE PP_PURCHASE_RETURN_TRANS DROP COLUMN INSPECTION_TRANS_ID;
END
GO

-- 5. Drop tables in reverse order of creation (re-attempting drops that failed due to FKs)
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_RESULT')
    DROP TABLE PP_INCOMING_INSPECTION_RESULT;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_TRANS')
    DROP TABLE PP_INCOMING_INSPECTION_TRANS;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_SOURCE')
    DROP TABLE PP_INCOMING_INSPECTION_SOURCE;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_HEAD')
    DROP TABLE PP_INCOMING_INSPECTION_HEAD;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INSPECTION_TEMPLATE_DETAIL')
    DROP TABLE PP_INSPECTION_TEMPLATE_DETAIL;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INSPECTION_TEMPLATE')
    DROP TABLE PP_INSPECTION_TEMPLATE;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INSPECTION_POLICY')
    DROP TABLE PP_INSPECTION_POLICY;
GO
