-- Check and Drop QUOTATION_NO from Customer Order Header
IF EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'SM_CUSTOMER_ORDER_HEADER' 
      AND COLUMN_NAME = 'QUOTATION_NO'
)
BEGIN
    ALTER TABLE SM_CUSTOMER_ORDER_HEADER DROP COLUMN QUOTATION_NO;
END;
GO

-- Check and Drop QUOTATION_DATE from Customer Order Header
IF EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'SM_CUSTOMER_ORDER_HEADER' 
      AND COLUMN_NAME = 'QUOTATION_DATE'
)
BEGIN
    ALTER TABLE SM_CUSTOMER_ORDER_HEADER DROP COLUMN QUOTATION_DATE;
END;
GO
