-- Create HR_ATS_REJECTED_DOCUMENT table for tracking document rejections and their history
IF OBJECT_ID('dbo.HR_ATS_REJECTED_DOCUMENT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.HR_ATS_REJECTED_DOCUMENT (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        EMPLOYEE_ID BIGINT NOT NULL,
        STAGE VARCHAR(50) NOT NULL,
        DOCUMENT_NAME VARCHAR(255) NOT NULL,
        REJECT_REASON NVARCHAR(MAX) NOT NULL,
        ACTIVE_STATUS VARCHAR(50) NOT NULL,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_HR_ATS_REJECTED_DOCUMENT_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES dbo.HR_EMPLOYEE(ID),
        CONSTRAINT FK_HR_ATS_REJECTED_DOCUMENT_CREATED FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_HR_ATS_REJECTED_DOCUMENT_UPDATED FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_HR_ATS_REJECTED_DOCUMENT_EMP ON dbo.HR_ATS_REJECTED_DOCUMENT(EMPLOYEE_ID, STAGE);
END
GO
