-- 20260623_V325.0__Standardize_Permissions_Schema_SOP__TIS.sql
-- Purpose: Restructure HR_PERMISSION_ENTRY and SC_PERMISSION_REQUEST to ensure 100% compliance with SOP:
--          1. Group standard audit columns contiguously at the very end of the table structure.
--          2. Establish clean, standard foreign key names.
--          3. Map approved_by, rejected_by, and verified_by to AD_USER_CREDENTIAL(USER_ID).

-- USE [AUTONOMA];
-- GO

-- =========================================================================
-- 1. DROP ALL EXISTING FOREIGN KEY CONSTRAINTS DYNAMICALLY
-- =========================================================================

DECLARE @SqlDropFks NVARCHAR(MAX) = N'';
SELECT @SqlDropFks += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + 
               ' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13) + CHAR(10)
FROM sys.foreign_keys
WHERE parent_object_id IN (
    OBJECT_ID('dbo.HR_PERMISSION_ENTRY'), 
    OBJECT_ID('dbo.SC_PERMISSION_REQUEST'),
    OBJECT_ID('dbo.HR_PERMISSION_ENTRY_OLD'),
    OBJECT_ID('dbo.SC_PERMISSION_REQUEST_OLD')
)
   OR referenced_object_id IN (
    OBJECT_ID('dbo.HR_PERMISSION_ENTRY'), 
    OBJECT_ID('dbo.SC_PERMISSION_REQUEST'),
    OBJECT_ID('dbo.HR_PERMISSION_ENTRY_OLD'),
    OBJECT_ID('dbo.SC_PERMISSION_REQUEST_OLD')
);

IF @SqlDropFks <> N''
BEGIN
    EXEC sp_executesql @SqlDropFks;
    PRINT 'Dropped all foreign key constraints for target tables';
END
GO

-- =========================================================================
-- 2. DROP ALL DEFAULT CONSTRAINTS DYNAMICALLY TO AVOID GLOBAL CONFLICTS
-- =========================================================================

DECLARE @SqlDropDefaults NVARCHAR(MAX) = N'';
SELECT @SqlDropDefaults += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + 
               ' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13) + CHAR(10)
FROM sys.default_constraints
WHERE parent_object_id IN (
    OBJECT_ID('dbo.HR_PERMISSION_ENTRY'), 
    OBJECT_ID('dbo.SC_PERMISSION_REQUEST'),
    OBJECT_ID('dbo.HR_PERMISSION_ENTRY_OLD'),
    OBJECT_ID('dbo.SC_PERMISSION_REQUEST_OLD')
);

IF @SqlDropDefaults <> N''
BEGIN
    EXEC sp_executesql @SqlDropDefaults;
    PRINT 'Dropped all default constraints for target tables';
END
GO

-- =========================================================================
-- 3. RENAME EXISTING TABLES TO OLD FOR DATA MIGRATION
-- =========================================================================

IF OBJECT_ID('dbo.HR_PERMISSION_ENTRY', 'U') IS NOT NULL AND OBJECT_ID('dbo.HR_PERMISSION_ENTRY_OLD', 'U') IS NULL
BEGIN
    EXEC sp_rename 'dbo.HR_PERMISSION_ENTRY', 'HR_PERMISSION_ENTRY_OLD';
    PRINT 'Renamed HR_PERMISSION_ENTRY to HR_PERMISSION_ENTRY_OLD';
END
GO

IF OBJECT_ID('dbo.SC_PERMISSION_REQUEST', 'U') IS NOT NULL AND OBJECT_ID('dbo.SC_PERMISSION_REQUEST_OLD', 'U') IS NULL
BEGIN
    EXEC sp_rename 'dbo.SC_PERMISSION_REQUEST', 'SC_PERMISSION_REQUEST_OLD';
    PRINT 'Renamed SC_PERMISSION_REQUEST to SC_PERMISSION_REQUEST_OLD';
END
GO

-- =========================================================================
-- 4. CREATE NEW STRUCTURE FOR HR_PERMISSION_ENTRY (AUDIT COLUMNS AT THE END)
-- =========================================================================

IF OBJECT_ID('dbo.HR_PERMISSION_ENTRY', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.HR_PERMISSION_ENTRY (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        EMPLOYEE_ID BIGINT NOT NULL,
        PERMISSION_DATE DATE NOT NULL,
        FROM_TIME NVARCHAR(50) NOT NULL,
        TO_TIME NVARCHAR(50) NOT NULL,
        ACTUAL_DURATION NVARCHAR(100) NOT NULL,
        CONSIDERED_DURATION DECIMAL(10,2) NOT NULL,
        REASON NVARCHAR(MAX) NULL,
        STATUS NVARCHAR(50) NULL CONSTRAINT DF_HR_PERMISSION_ENTRY_status DEFAULT 'Pending for Verify',
        MONTH NVARCHAR(50) NOT NULL,
        YEAR INT NOT NULL,
        REJECTION_REASON NVARCHAR(MAX) NULL,
        REQUEST_TYPE NVARCHAR(50) NULL,
        EMPLOYEE_CODE NVARCHAR(50) NULL,
        APPROVED_BY NVARCHAR(50) NULL,
        APPROVED_DATE DATETIME NULL,
        REJECTED_BY NVARCHAR(50) NULL,
        REJECTED_DATE DATETIME NULL,
        REJECTION_COMMENT NVARCHAR(MAX) NULL,
        VERIFIED_BY NVARCHAR(50) NULL,
        VERIFIED_DATE DATETIME NULL,
        IS_ACTIVE BIT NOT NULL CONSTRAINT DF_HR_PERMISSION_ENTRY_is_active DEFAULT 1,
        
        -- SOP §3.1 Mandatory Audit Columns grouped contiguously at the very end
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL
    );
    PRINT 'Created new HR_PERMISSION_ENTRY table with SOP-compliant layout';
END
GO

-- =========================================================================
-- 5. CREATE NEW STRUCTURE FOR SC_PERMISSION_REQUEST (AUDIT COLUMNS AT THE END)
-- =========================================================================

IF OBJECT_ID('dbo.SC_PERMISSION_REQUEST', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_PERMISSION_REQUEST (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        PERMISSION_ENTRY_ID BIGINT NOT NULL,
        EMPLOYEE_ID BIGINT NOT NULL,
        PERMISSION_DATE DATE NOT NULL,
        FROM_TIME NVARCHAR(50) NOT NULL,
        TO_TIME NVARCHAR(50) NOT NULL,
        ACTUAL_DURATION NVARCHAR(100) NOT NULL,
        CONSIDERED_DURATION DECIMAL(10,2) NOT NULL,
        REASON NVARCHAR(MAX) NULL,
        STATUS NVARCHAR(50) NOT NULL CONSTRAINT DF_SC_PERMISSION_REQUEST_status DEFAULT 'Pending for Verify',
        REJECTION_REASON NVARCHAR(MAX) NULL,
        REQUEST_TYPE NVARCHAR(50) NULL,
        EMPLOYEE_CODE NVARCHAR(50) NULL,
        APPROVED_BY NVARCHAR(50) NULL,
        APPROVED_DATE DATETIME NULL,
        REJECTED_BY NVARCHAR(50) NULL,
        REJECTED_DATE DATETIME NULL,
        REJECTION_COMMENT NVARCHAR(MAX) NULL,
        VERIFIED_BY NVARCHAR(50) NULL,
        VERIFIED_DATE DATETIME NULL,
        IS_ACTIVE BIT NOT NULL CONSTRAINT DF_SC_PERMISSION_REQUEST_is_active DEFAULT 1,
        
        -- SOP §3.1 Mandatory Audit Columns grouped contiguously at the very end
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL
    );
    PRINT 'Created new SC_PERMISSION_REQUEST table with SOP-compliant layout';
END
GO

-- =========================================================================
-- 6. MIGRATE DATA FROM OLD TABLES TO NEW TABLES
-- =========================================================================

IF OBJECT_ID('dbo.HR_PERMISSION_ENTRY_OLD', 'U') IS NOT NULL
BEGIN
    SET IDENTITY_INSERT dbo.HR_PERMISSION_ENTRY ON;
    INSERT INTO dbo.HR_PERMISSION_ENTRY (
        ID, EMPLOYEE_ID, PERMISSION_DATE, FROM_TIME, TO_TIME, ACTUAL_DURATION, CONSIDERED_DURATION,
        REASON, STATUS, MONTH, YEAR, REJECTION_REASON, REQUEST_TYPE, EMPLOYEE_CODE,
        APPROVED_BY, APPROVED_DATE, REJECTED_BY, REJECTED_DATE, REJECTION_COMMENT,
        VERIFIED_BY, VERIFIED_DATE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE
    )
    SELECT 
        ID, EMPLOYEE_ID, PERMISSION_DATE, FROM_TIME, TO_TIME, ACTUAL_DURATION, CONSIDERED_DURATION,
        REASON, STATUS, MONTH, YEAR, REJECTION_REASON, REQUEST_TYPE, EMPLOYEE_CODE,
        APPROVED_BY, APPROVED_DATE, REJECTED_BY, REJECTED_DATE, REJECTION_COMMENT,
        VERIFIED_BY, VERIFIED_DATE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE
    FROM dbo.HR_PERMISSION_ENTRY_OLD;
    SET IDENTITY_INSERT dbo.HR_PERMISSION_ENTRY OFF;
    PRINT 'Migrated data to new HR_PERMISSION_ENTRY';
END
GO

IF OBJECT_ID('dbo.SC_PERMISSION_REQUEST_OLD', 'U') IS NOT NULL
BEGIN
    SET IDENTITY_INSERT dbo.SC_PERMISSION_REQUEST ON;
    INSERT INTO dbo.SC_PERMISSION_REQUEST (
        ID, PERMISSION_ENTRY_ID, EMPLOYEE_ID, PERMISSION_DATE, FROM_TIME, TO_TIME, ACTUAL_DURATION, CONSIDERED_DURATION,
        REASON, STATUS, REJECTION_REASON, REQUEST_TYPE, EMPLOYEE_CODE,
        APPROVED_BY, APPROVED_DATE, REJECTED_BY, REJECTED_DATE, REJECTION_COMMENT,
        VERIFIED_BY, VERIFIED_DATE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE
    )
    SELECT 
        ID, PERMISSION_ENTRY_ID, EMPLOYEE_ID, PERMISSION_DATE, FROM_TIME, TO_TIME, ACTUAL_DURATION, CONSIDERED_DURATION,
        REASON, STATUS, REJECTION_REASON, REQUEST_TYPE, EMPLOYEE_CODE,
        APPROVED_BY, APPROVED_DATE, REJECTED_BY, REJECTED_DATE, REJECTION_COMMENT,
        VERIFIED_BY, VERIFIED_DATE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE
    FROM dbo.SC_PERMISSION_REQUEST_OLD;
    SET IDENTITY_INSERT dbo.SC_PERMISSION_REQUEST OFF;
    PRINT 'Migrated data to new SC_PERMISSION_REQUEST';
END
GO

-- =========================================================================
-- 7. DROP OLD TABLES
-- =========================================================================

IF OBJECT_ID('dbo.HR_PERMISSION_ENTRY_OLD', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.HR_PERMISSION_ENTRY_OLD;
    PRINT 'Dropped HR_PERMISSION_ENTRY_OLD';
END
GO

IF OBJECT_ID('dbo.SC_PERMISSION_REQUEST_OLD', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.SC_PERMISSION_REQUEST_OLD;
    PRINT 'Dropped SC_PERMISSION_REQUEST_OLD';
END
GO

-- =========================================================================
-- 8. CLEAN UP ORPHANED AND INVALID FOREIGN KEY VALUES IN NEW TABLES
-- =========================================================================

-- Clean up invalid references to AD_USER_CREDENTIAL(USER_ID)
-- For CREATED_BY / UPDATED_BY: default to 'System' if not existing
UPDATE dbo.HR_PERMISSION_ENTRY SET CREATED_BY = 'System' WHERE CREATED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);
UPDATE dbo.HR_PERMISSION_ENTRY SET UPDATED_BY = 'System' WHERE UPDATED_BY IS NOT NULL AND UPDATED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);

UPDATE dbo.SC_PERMISSION_REQUEST SET CREATED_BY = 'System' WHERE CREATED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);
UPDATE dbo.SC_PERMISSION_REQUEST SET UPDATED_BY = 'System' WHERE UPDATED_BY IS NOT NULL AND UPDATED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);

-- For APPROVED_BY, REJECTED_BY, VERIFIED_BY: nullify if not existing (as they are optional null columns)
UPDATE dbo.HR_PERMISSION_ENTRY SET APPROVED_BY = NULL WHERE APPROVED_BY IS NOT NULL AND APPROVED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);
UPDATE dbo.HR_PERMISSION_ENTRY SET REJECTED_BY = NULL WHERE REJECTED_BY IS NOT NULL AND REJECTED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);
UPDATE dbo.HR_PERMISSION_ENTRY SET VERIFIED_BY = NULL WHERE VERIFIED_BY IS NOT NULL AND VERIFIED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);

UPDATE dbo.SC_PERMISSION_REQUEST SET APPROVED_BY = NULL WHERE APPROVED_BY IS NOT NULL AND APPROVED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);
UPDATE dbo.SC_PERMISSION_REQUEST SET REJECTED_BY = NULL WHERE REJECTED_BY IS NOT NULL AND REJECTED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);
UPDATE dbo.SC_PERMISSION_REQUEST SET VERIFIED_BY = NULL WHERE VERIFIED_BY IS NOT NULL AND VERIFIED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);

-- Clean up employee references
DELETE FROM dbo.HR_PERMISSION_ENTRY WHERE EMPLOYEE_ID NOT IN (SELECT ID FROM dbo.HR_EMPLOYEE);
DELETE FROM dbo.SC_PERMISSION_REQUEST WHERE EMPLOYEE_ID NOT IN (SELECT ID FROM dbo.HR_EMPLOYEE);
DELETE FROM dbo.SC_PERMISSION_REQUEST WHERE PERMISSION_ENTRY_ID NOT IN (SELECT ID FROM dbo.HR_PERMISSION_ENTRY);
GO

-- =========================================================================
-- 9. RECREATE INDEXES
-- =========================================================================

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HR_PERMISSION_ENTRY_EMPLOYEE' AND object_id = OBJECT_ID('dbo.HR_PERMISSION_ENTRY'))
    CREATE INDEX IX_HR_PERMISSION_ENTRY_EMPLOYEE ON dbo.HR_PERMISSION_ENTRY(EMPLOYEE_ID);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HR_PERMISSION_ENTRY_DATE' AND object_id = OBJECT_ID('dbo.HR_PERMISSION_ENTRY'))
    CREATE INDEX IX_HR_PERMISSION_ENTRY_DATE ON dbo.HR_PERMISSION_ENTRY(PERMISSION_DATE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SC_PERMISSION_REQUEST_PERMISSION_ENTRY' AND object_id = OBJECT_ID('dbo.SC_PERMISSION_REQUEST'))
    CREATE INDEX IX_SC_PERMISSION_REQUEST_PERMISSION_ENTRY ON dbo.SC_PERMISSION_REQUEST(PERMISSION_ENTRY_ID);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SC_PERMISSION_REQUEST_EMPLOYEE' AND object_id = OBJECT_ID('dbo.SC_PERMISSION_REQUEST'))
    CREATE INDEX IX_SC_PERMISSION_REQUEST_EMPLOYEE ON dbo.SC_PERMISSION_REQUEST(EMPLOYEE_ID);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SC_PERMISSION_REQUEST_DATE' AND object_id = OBJECT_ID('dbo.SC_PERMISSION_REQUEST'))
    CREATE INDEX IX_SC_PERMISSION_REQUEST_DATE ON dbo.SC_PERMISSION_REQUEST(PERMISSION_DATE);

PRINT 'Created indexes for new tables';
GO

-- =========================================================================
-- 10. CREATE CLEAN, SOP-COMPLIANT FOREIGN KEY CONSTRAINTS
-- =========================================================================

-- HR_PERMISSION_ENTRY
ALTER TABLE dbo.HR_PERMISSION_ENTRY ADD CONSTRAINT FK_HR_PERMISSION_ENTRY_EMPLOYEE
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES dbo.HR_EMPLOYEE(ID);

ALTER TABLE dbo.HR_PERMISSION_ENTRY ADD CONSTRAINT FK_HR_PERMISSION_ENTRY_CREATED_BY
    FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE dbo.HR_PERMISSION_ENTRY ADD CONSTRAINT FK_HR_PERMISSION_ENTRY_UPDATED_BY
    FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE dbo.HR_PERMISSION_ENTRY ADD CONSTRAINT FK_HR_PERMISSION_ENTRY_APPROVED_BY
    FOREIGN KEY (APPROVED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE dbo.HR_PERMISSION_ENTRY ADD CONSTRAINT FK_HR_PERMISSION_ENTRY_REJECTED_BY
    FOREIGN KEY (REJECTED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE dbo.HR_PERMISSION_ENTRY ADD CONSTRAINT FK_HR_PERMISSION_ENTRY_VERIFIED_BY
    FOREIGN KEY (VERIFIED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);

-- SC_PERMISSION_REQUEST
ALTER TABLE dbo.SC_PERMISSION_REQUEST ADD CONSTRAINT FK_SC_PERMISSION_REQUEST_PERMISSION_ENTRY
    FOREIGN KEY (PERMISSION_ENTRY_ID) REFERENCES dbo.HR_PERMISSION_ENTRY(ID);

ALTER TABLE dbo.SC_PERMISSION_REQUEST ADD CONSTRAINT FK_SC_PERMISSION_REQUEST_EMPLOYEE
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES dbo.HR_EMPLOYEE(ID);

ALTER TABLE dbo.SC_PERMISSION_REQUEST ADD CONSTRAINT FK_SC_PERMISSION_REQUEST_CREATED_BY
    FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE dbo.SC_PERMISSION_REQUEST ADD CONSTRAINT FK_SC_PERMISSION_REQUEST_UPDATED_BY
    FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE dbo.SC_PERMISSION_REQUEST ADD CONSTRAINT FK_SC_PERMISSION_REQUEST_APPROVED_BY
    FOREIGN KEY (APPROVED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE dbo.SC_PERMISSION_REQUEST ADD CONSTRAINT FK_SC_PERMISSION_REQUEST_REJECTED_BY
    FOREIGN KEY (REJECTED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE dbo.SC_PERMISSION_REQUEST ADD CONSTRAINT FK_SC_PERMISSION_REQUEST_VERIFIED_BY
    FOREIGN KEY (VERIFIED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);

PRINT 'Successfully created all SOP-compliant Foreign Key constraints!';
GO
