-- =========================================================================
-- Migration: Add Performance Indexes for Interview Criteria Master Tables
-- Date: 2026-07-27
-- Developer: Antigravity
-- =========================================================================

-- Create index on HR_INTERVIEW (INTERVIEW_ROUND, STATUS) if not exists
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_INTERVIEW_ROUND_STATUS' AND object_id = OBJECT_ID('HR_INTERVIEW'))
BEGIN
    CREATE INDEX IX_HR_INTERVIEW_ROUND_STATUS ON HR_INTERVIEW (INTERVIEW_ROUND, STATUS);
END;

-- Create index on HR_INTERVIEW_DEPARTMENT_MAPPING (INTERVIEW_ID, DEPARTMENT_ID) if not exists
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_INTERVIEW_DEPARTMENT_MAPPING_ID_DEPT' AND object_id = OBJECT_ID('HR_INTERVIEW_DEPARTMENT_MAPPING'))
BEGIN
    CREATE INDEX IX_HR_INTERVIEW_DEPARTMENT_MAPPING_ID_DEPT ON HR_INTERVIEW_DEPARTMENT_MAPPING (INTERVIEW_ID, DEPARTMENT_ID);
END;

-- Create index on HR_INTERVIEW_LEVEL_MAPPING (INTERVIEW_ID, LEVEL_ID) if not exists
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_INTERVIEW_LEVEL_MAPPING_ID_LEVEL' AND object_id = OBJECT_ID('HR_INTERVIEW_LEVEL_MAPPING'))
BEGIN
    CREATE INDEX IX_HR_INTERVIEW_LEVEL_MAPPING_ID_LEVEL ON HR_INTERVIEW_LEVEL_MAPPING (INTERVIEW_ID, LEVEL_ID);
END;
