-- V1032.0: Leave Module – Drop obsolete tables, rename WHERE_FROM → FROM_WHERE, change data type

-- Step 1: Drop HR_LEAVE_REQUEST table (if exists)
IF OBJECT_ID('HR_LEAVE_REQUEST', 'U') IS NOT NULL
BEGIN
    DROP TABLE HR_LEAVE_REQUEST;
    PRINT 'Dropped table: HR_LEAVE_REQUEST';
END

-- Step 2: Drop HR_LEAVE_TYPE table (if exists)
IF OBJECT_ID('HR_LEAVE_TYPE', 'U') IS NOT NULL
BEGIN
    DROP TABLE HR_LEAVE_TYPE;
    PRINT 'Dropped table: HR_LEAVE_TYPE';
END

-- Step 3: Rename WHERE_FROM → FROM_WHERE in HR_LEAVE_DETAILS (if WHERE_FROM still exists)
IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_LEAVE_DETAILS' AND COLUMN_NAME = 'WHERE_FROM'
)
AND NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_LEAVE_DETAILS' AND COLUMN_NAME = 'FROM_WHERE'
)
BEGIN
    EXEC sp_rename 'HR_LEAVE_DETAILS.WHERE_FROM', 'FROM_WHERE', 'COLUMN';
    PRINT 'Renamed WHERE_FROM to FROM_WHERE in HR_LEAVE_DETAILS';
END

-- Step 4: Change FROM_WHERE data type to NVARCHAR(25)
IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_LEAVE_DETAILS' AND COLUMN_NAME = 'FROM_WHERE'
)
BEGIN
    ALTER TABLE HR_LEAVE_DETAILS ALTER COLUMN FROM_WHERE NVARCHAR(25) NULL;
    PRINT 'Changed FROM_WHERE to NVARCHAR(25) in HR_LEAVE_DETAILS';
END
