-- Claimed V386.0: Add SELF_ASSESSMENT_STATUS, CURRENT_STEP, LAST_DRAFT_SAVED_DATE columns to HR_EMPLOYEE_ATS table
IF OBJECT_ID('[dbo].[HR_EMPLOYEE_ATS]', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[HR_EMPLOYEE_ATS]') AND name = 'SELF_ASSESSMENT_STATUS')
    BEGIN
        ALTER TABLE [dbo].[HR_EMPLOYEE_ATS] ADD [SELF_ASSESSMENT_STATUS] VARCHAR(20) NOT NULL DEFAULT 'DRAFT';
        PRINT 'Added column SELF_ASSESSMENT_STATUS to HR_EMPLOYEE_ATS';
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[HR_EMPLOYEE_ATS]') AND name = 'CURRENT_STEP')
    BEGIN
        ALTER TABLE [dbo].[HR_EMPLOYEE_ATS] ADD [CURRENT_STEP] INT NULL;
        PRINT 'Added column CURRENT_STEP to HR_EMPLOYEE_ATS';
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[HR_EMPLOYEE_ATS]') AND name = 'LAST_DRAFT_SAVED_DATE')
    BEGIN
        ALTER TABLE [dbo].[HR_EMPLOYEE_ATS] ADD [LAST_DRAFT_SAVED_DATE] DATETIME NULL;
        PRINT 'Added column LAST_DRAFT_SAVED_DATE to HR_EMPLOYEE_ATS';
    END
END
GO
