-- SQL Migration: Standardize CLI_CLIENT_MASTER for SQL Server / MSSQL (BOS SOP Compliant)
-- Created: 2026-07-24

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLI_CLIENT_MASTER]') AND type in (N'U'))
BEGIN
    CREATE TABLE CLI_CLIENT_MASTER (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_CODE NVARCHAR(10) NOT NULL UNIQUE,
        CLIENT_NAME NVARCHAR(150) NOT NULL,
        COMPANY_NAME NVARCHAR(150) NOT NULL,
        SHORT_NAME NVARCHAR(50),
        GST_NUMBER NVARCHAR(20),
        PAN_NUMBER NVARCHAR(15),
        CIN_NUMBER NVARCHAR(25),
        CONTACT_PERSON NVARCHAR(100),
        MOBILE_NUMBER NVARCHAR(20),
        EMAIL NVARCHAR(100) NOT NULL,
        WEBSITE NVARCHAR(150),
        ADDRESS NVARCHAR(MAX),
        COUNTRY NVARCHAR(50),
        STATE NVARCHAR(50),
        CITY NVARCHAR(50),
        PINCODE NVARCHAR(15),
        TIME_ZONE NVARCHAR(50) DEFAULT 'UTC',
        CURRENCY NVARCHAR(10) DEFAULT 'USD',
        COMPANY_LOGO NVARCHAR(255),
        STATUS NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    
        IS_DELETED BIT DEFAULT 0,
        CREATED_BY NVARCHAR(50),
        UPDATED_BY NVARCHAR(50),
        CREATED_AT DATETIME DEFAULT GETDATE(),
        UPDATED_AT DATETIME DEFAULT GETDATE()
    );

    CREATE UNIQUE INDEX IDX_CLI_CLIENT_CODE ON CLI_CLIENT_MASTER(CLIENT_CODE);
    CREATE INDEX IDX_CLI_CLIENT_STATUS ON CLI_CLIENT_MASTER(STATUS);
    CREATE INDEX IDX_CLI_LICENSE_EXPIRY ON CLI_CLIENT_MASTER(LICENSE_EXPIRY_DATE);
    CREATE INDEX IDX_CLI_EMAIL ON CLI_CLIENT_MASTER(EMAIL);
END;
