-- Normalize ability column values in HR_EMPLOYEE_ABILITY to standard '1' and '0'
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_EMPLOYEE_ABILITY' AND COLUMN_NAME = 'IS_INTERVIEWER')
BEGIN
    UPDATE HR_EMPLOYEE_ABILITY SET IS_INTERVIEWER = '1' WHERE UPPER(TRIM(IS_INTERVIEWER)) = 'YES' OR IS_INTERVIEWER = '1';
    UPDATE HR_EMPLOYEE_ABILITY SET IS_INTERVIEWER = '0' WHERE UPPER(TRIM(IS_INTERVIEWER)) = 'NO' OR IS_INTERVIEWER = '0' OR IS_INTERVIEWER IS NULL;
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_EMPLOYEE_ABILITY' AND COLUMN_NAME = 'IS_ENQUIRY_ASSIGNEE')
BEGIN
    UPDATE HR_EMPLOYEE_ABILITY SET IS_ENQUIRY_ASSIGNEE = '1' WHERE UPPER(TRIM(IS_ENQUIRY_ASSIGNEE)) = 'YES' OR IS_ENQUIRY_ASSIGNEE = '1';
    UPDATE HR_EMPLOYEE_ABILITY SET IS_ENQUIRY_ASSIGNEE = '0' WHERE UPPER(TRIM(IS_ENQUIRY_ASSIGNEE)) = 'NO' OR IS_ENQUIRY_ASSIGNEE = '0' OR IS_ENQUIRY_ASSIGNEE IS NULL;
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_EMPLOYEE_ABILITY' AND COLUMN_NAME = 'IS_PR_ASSIGNEE')
BEGIN
    UPDATE HR_EMPLOYEE_ABILITY SET IS_PR_ASSIGNEE = '1' WHERE UPPER(TRIM(IS_PR_ASSIGNEE)) = 'YES' OR IS_PR_ASSIGNEE = '1';
    UPDATE HR_EMPLOYEE_ABILITY SET IS_PR_ASSIGNEE = '0' WHERE UPPER(TRIM(IS_PR_ASSIGNEE)) = 'NO' OR IS_PR_ASSIGNEE = '0' OR IS_PR_ASSIGNEE IS NULL;
END
