-- Add DIVISION to QMC_INSPECTION_SPECIFICATION
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'DIVISION' AND Object_ID = Object_ID(N'dbo.QMC_INSPECTION_SPECIFICATION'))
BEGIN
    ALTER TABLE dbo.QMC_INSPECTION_SPECIFICATION ADD DIVISION BIGINT NULL;
END
GO

-- Add REFERENCE and VISUAL_NAME to QMC_INSPECTION_SPECIFICATION_DETAIL
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'REFERENCE' AND Object_ID = Object_ID(N'dbo.QMC_INSPECTION_SPECIFICATION_DETAIL'))
BEGIN
    ALTER TABLE dbo.QMC_INSPECTION_SPECIFICATION_DETAIL ADD REFERENCE NVARCHAR(500) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'VISUAL_NAME' AND Object_ID = Object_ID(N'dbo.QMC_INSPECTION_SPECIFICATION_DETAIL'))
BEGIN
    ALTER TABLE dbo.QMC_INSPECTION_SPECIFICATION_DETAIL ADD VISUAL_NAME NVARCHAR(500) NULL;
END
GO
