-- Drop Q41_MANAGER_1_EMAIL from HR_EMPLOYEE_SELF_ASSESSMENT if exists
IF EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') 
    AND name = 'Q41_MANAGER_1_EMAIL'
)
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] DROP COLUMN [Q41_MANAGER_1_EMAIL];
END
GO

-- Drop Q42_MANAGER_2_EMAIL from HR_EMPLOYEE_SELF_ASSESSMENT if exists
IF EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') 
    AND name = 'Q42_MANAGER_2_EMAIL'
)
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] DROP COLUMN [Q42_MANAGER_2_EMAIL];
END
GO
