-- V1107.0: Add missing verification, reject_reason, status_id, and from_where columns to HR_LEAVE_TRAVEL_DETAILS
-- Fully idempotent with IF NOT EXISTS validation guards

IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS') AND name = 'REJECT_REASON')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD REJECT_REASON NVARCHAR(500) NULL;
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS') AND name = 'VERIFIED_BY')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD VERIFIED_BY NVARCHAR(50) NULL;
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS') AND name = 'VERIFIED_DATE')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD VERIFIED_DATE DATETIME NULL;
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS') AND name = 'STATUS_ID')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD STATUS_ID INT NULL;
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS') AND name = 'NO_OF_BILLS')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD NO_OF_BILLS INT NULL DEFAULT 1;
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS') AND name = 'FROM_WHERE')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD FROM_WHERE NVARCHAR(25) NULL;
    END
END
GO
