-- Migration Script: Idempotent Drop of PK_VENDOR_SATISFACTION_RESPONSE primary key constraint
IF OBJECT_ID('PK_VENDOR_SATISFACTION_RESPONSE', 'PK') IS NOT NULL
BEGIN
    ALTER TABLE VENDOR_SATISFACTION_RESPONSE DROP CONSTRAINT PK_VENDOR_SATISFACTION_RESPONSE;
END
