IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PP_PURCHASE_ORDER_HEAD') AND name = 'GST_TYPE')
BEGIN
    ALTER TABLE PP_PURCHASE_ORDER_HEAD ADD GST_TYPE NVARCHAR(20) DEFAULT 'INTRA_STATE' NOT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PP_PURCHASE_ORDER_TRANS') AND name = 'CGST_PERCENT')
BEGIN
    ALTER TABLE PP_PURCHASE_ORDER_TRANS ADD CGST_PERCENT DECIMAL(5, 2) DEFAULT 0 NOT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PP_PURCHASE_ORDER_TRANS') AND name = 'SGST_PERCENT')
BEGIN
    ALTER TABLE PP_PURCHASE_ORDER_TRANS ADD SGST_PERCENT DECIMAL(5, 2) DEFAULT 0 NOT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PP_PURCHASE_ORDER_TRANS') AND name = 'IGST_PERCENT')
BEGIN
    ALTER TABLE PP_PURCHASE_ORDER_TRANS ADD IGST_PERCENT DECIMAL(5, 2) DEFAULT 0 NOT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PP_PURCHASE_ORDER_TRANS') AND name = 'CGST_AMOUNT')
BEGIN
    ALTER TABLE PP_PURCHASE_ORDER_TRANS ADD CGST_AMOUNT DECIMAL(18, 4) DEFAULT 0 NOT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PP_PURCHASE_ORDER_TRANS') AND name = 'SGST_AMOUNT')
BEGIN
    ALTER TABLE PP_PURCHASE_ORDER_TRANS ADD SGST_AMOUNT DECIMAL(18, 4) DEFAULT 0 NOT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PP_PURCHASE_ORDER_TRANS') AND name = 'IGST_AMOUNT')
BEGIN
    ALTER TABLE PP_PURCHASE_ORDER_TRANS ADD IGST_AMOUNT DECIMAL(18, 4) DEFAULT 0 NOT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PP_PURCHASE_ORDER_TRANS') AND name = 'TAX_AMOUNT')
BEGIN
    ALTER TABLE PP_PURCHASE_ORDER_TRANS ADD TAX_AMOUNT DECIMAL(18, 4) DEFAULT 0 NOT NULL;
END
GO
