IF NOT EXISTS (SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('PP_PURCHASE_ORDER_HEAD') AND name = 'TRANSPORT_SCOPE')
BEGIN
    ALTER TABLE PP_PURCHASE_ORDER_HEAD ADD TRANSPORT_SCOPE NVARCHAR(50) NULL;
END
GO
