-- Migration: Fix TRANS_NO (GRN No) and REFERENCE_NO (QI Inspection ID) and backfill CREATED_DATE in ITEM_TRANSACTION table
-- Idempotent check

IF OBJECT_ID('ITEM_TRANSACTION', 'U') IS NOT NULL
BEGIN
    UPDATE ITEM_TRANSACTION
    SET TRANS_NO = REFERENCE_NO,
        REFERENCE_NO = 'QI-' + CAST(ID as nvarchar(50))
    WHERE (REFERENCE_NO LIKE 'GRN%' OR REFERENCE_NO LIKE '%GRN%')
      AND (TRANS_NO NOT LIKE 'GRN%' AND TRANS_NO NOT LIKE '%GRN%');

    UPDATE ITEM_TRANSACTION
    SET CREATED_DATE = GETDATE()
    WHERE CREATED_DATE IS NULL;
END;

IF OBJECT_ID('ITEM_TRANSACTIONS', 'U') IS NOT NULL
BEGIN
    UPDATE ITEM_TRANSACTIONS
    SET TRANS_NO = REFERENCE_NO,
        REFERENCE_NO = 'QI-' + CAST(ID as nvarchar(50))
    WHERE (REFERENCE_NO LIKE 'GRN%' OR REFERENCE_NO LIKE '%GRN%')
      AND (TRANS_NO NOT LIKE 'GRN%' AND TRANS_NO NOT LIKE '%GRN%');

    UPDATE ITEM_TRANSACTIONS
    SET CREATED_DATE = GETDATE()
    WHERE CREATED_DATE IS NULL;
END;
