-- Migration: Expand LOGO_FILE_NAME and LOGIN_BG_FILE_NAME in AD_COMPANY_CREDENTIAL to NVARCHAR(500)

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'AD_COMPANY_CREDENTIAL' AND COLUMN_NAME = 'LOGO_FILE_NAME'
)
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL]
    ALTER COLUMN [LOGO_FILE_NAME] NVARCHAR(500) NULL;
END
GO

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'AD_COMPANY_CREDENTIAL' AND COLUMN_NAME = 'LOGIN_BG_FILE_NAME'
)
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL]
    ALTER COLUMN [LOGIN_BG_FILE_NAME] NVARCHAR(500) NULL;
END
GO
