DECLARE @AdminId NVARCHAR(50) = (SELECT TOP 1 USER_ID FROM AD_USER_CREDENTIAL);

IF NOT EXISTS (SELECT 1 FROM SM_ADDITIONAL_CHARGES WHERE CHARGES = 'Freight & Forwarding')
BEGIN
    INSERT INTO SM_ADDITIONAL_CHARGES (CHARGES, CALCULATION_TYPE, STATUS, CREATED_BY, CREATED_DATE)
    VALUES ('Freight & Forwarding', 'AMOUNT', 1, @AdminId, GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM SM_ADDITIONAL_CHARGES WHERE CHARGES = 'Packaging')
BEGIN
    INSERT INTO SM_ADDITIONAL_CHARGES (CHARGES, CALCULATION_TYPE, STATUS, CREATED_BY, CREATED_DATE)
    VALUES ('Packaging', 'AMOUNT', 1, @AdminId, GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM SM_ADDITIONAL_CHARGES WHERE CHARGES = 'Insurance')
BEGIN
    INSERT INTO SM_ADDITIONAL_CHARGES (CHARGES, CALCULATION_TYPE, STATUS, CREATED_BY, CREATED_DATE)
    VALUES ('Insurance', 'AMOUNT', 1, @AdminId, GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM SM_ADDITIONAL_CHARGES WHERE CHARGES = 'Documentation Charges')
BEGIN
    INSERT INTO SM_ADDITIONAL_CHARGES (CHARGES, CALCULATION_TYPE, STATUS, CREATED_BY, CREATED_DATE)
    VALUES ('Documentation Charges', 'AMOUNT', 1, @AdminId, GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM SM_ADDITIONAL_CHARGES WHERE CHARGES = 'Handling Charges')
BEGIN
    INSERT INTO SM_ADDITIONAL_CHARGES (CHARGES, CALCULATION_TYPE, STATUS, CREATED_BY, CREATED_DATE)
    VALUES ('Handling Charges', 'AMOUNT', 1, @AdminId, GETDATE());
END
GO