-- SQL Migration: Create CLI_CLIENT_LICENSE Table (BOS SOP Compliant)
-- Created: 2026-07-24

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLI_CLIENT_LICENSE]') AND type in (N'U'))
BEGIN
    CREATE TABLE CLI_CLIENT_LICENSE (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_ID BIGINT NOT NULL,
        CLIENT_CODE NVARCHAR(10) NOT NULL,
        LICENSE_KEY NVARCHAR(128) UNIQUE,
        IMPLEMENTED_DATE DATE NOT NULL,
        EXPIRY_DATE DATE NOT NULL,
        MAX_USERS INT NOT NULL DEFAULT 5,
        MAX_BRANCHES INT NOT NULL DEFAULT 1,
        MAX_COMPANIES INT NOT NULL DEFAULT 1,
        MAX_CONCURRENT_LOGIN INT NOT NULL DEFAULT 5,
        MAX_STORAGE_MB INT NOT NULL DEFAULT 1024,
        API_ACCESS BIT DEFAULT 0,
        MOBILE_APP_ACCESS BIT DEFAULT 0,
        BACKUP_ENABLED BIT DEFAULT 1,
        STATUS NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
        IS_DELETED BIT DEFAULT 0,
        CREATED_BY NVARCHAR(50),
        UPDATED_BY NVARCHAR(50),
        CREATED_AT DATETIME DEFAULT GETDATE(),
        UPDATED_AT DATETIME DEFAULT GETDATE(),
        CONSTRAINT FK_CLI_LICENSE_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLI_CLIENT_MASTER(ID)
    );

    CREATE UNIQUE INDEX IDX_CLI_LICENSE_CODE ON CLI_CLIENT_LICENSE(CLIENT_CODE);
    CREATE INDEX IDX_CLI_LICENSE_EXPIRY ON CLI_CLIENT_LICENSE(EXPIRY_DATE);
END;
