-- SQL Migration: Create Client Management Tables (CM_ Prefix)
-- Created: 2026-07-06

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_MASTER]') AND type in (N'U'))
BEGIN
    CREATE TABLE CM_CLIENT_MASTER (
        CLIENT_ID INT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_CODE NVARCHAR(50) NOT NULL UNIQUE,
        CLIENT_NAME NVARCHAR(150) NOT NULL,
        COMPANY_NAME NVARCHAR(150),
        CONTACT_PERSON NVARCHAR(100),
        EMAIL NVARCHAR(100),
        MOBILE NVARCHAR(20),
        ERP_VERSION NVARCHAR(50),
        AGENT_VERSION NVARCHAR(50),
        SERVER_NAME NVARCHAR(100),
        DATABASE_NAME NVARCHAR(100),
        DOMAIN_IP NVARCHAR(100),
        LICENSE_KEY NVARCHAR(100),
        LICENSE_TYPE NVARCHAR(50),
        INSTALLATION_DATE DATETIME,
        LAST_SYNC DATETIME,
        LAST_HEARTBEAT DATETIME,
        CURRENT_STATUS NVARCHAR(50), -- ONLINE, OFFLINE, WARNING
        IS_ACTIVE BIT DEFAULT 1,
        CREATED_BY NVARCHAR(50),
        CREATED_DATE DATETIME DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME
    );
END;

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_CONFIGURATION]') AND type in (N'U'))
BEGIN
    CREATE TABLE CM_CLIENT_CONFIGURATION (
        CONFIG_ID INT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_CODE NVARCHAR(50) NOT NULL,
        CONFIG_TYPE NVARCHAR(100) NOT NULL, -- DATABASE, MAIL, SMS, WHATSAPP, API_URLS, SCHEDULER, BACKUP, AUTHENTICATION, FILE_STORAGE, REPORTS
        CONFIG_KEY NVARCHAR(100) NOT NULL,
        CONFIG_VALUE NVARCHAR(MAX),
        SYNC_STATUS NVARCHAR(50) DEFAULT 'PENDING_SYNC', -- SYNCED, PENDING_SYNC, FAILED
        LAST_SYNC_TIME DATETIME,
        CREATED_BY NVARCHAR(50),
        CREATED_DATE DATETIME DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME,
        CONSTRAINT UQ_CM_CONFIG_CUST_KEY UNIQUE (CLIENT_CODE, CONFIG_KEY)
    );
END;

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_HEARTBEAT]') AND type in (N'U'))
BEGIN
    CREATE TABLE CM_CLIENT_HEARTBEAT (
        HEARTBEAT_ID INT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_CODE NVARCHAR(50) NOT NULL,
        ERP_VERSION NVARCHAR(50),
        DATABASE_STATUS NVARCHAR(50), -- ONLINE, OFFLINE
        APPLICATION_STATUS NVARCHAR(50), -- ONLINE, OFFLINE
        SCHEDULER_STATUS NVARCHAR(50), -- ONLINE, OFFLINE
        CPU_USAGE DECIMAL(5,2),
        RAM_USAGE DECIMAL(5,2),
        DISK_USAGE DECIMAL(5,2),
        BACKUP_STATUS NVARCHAR(50), -- SUCCESS, FAILED
        LAST_HEARTBEAT DATETIME DEFAULT GETDATE()
    );
END;

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_LICENSE]') AND type in (N'U'))
BEGIN
    CREATE TABLE CM_CLIENT_LICENSE (
        LICENSE_ID INT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_CODE NVARCHAR(50) NOT NULL,
        LICENSE_KEY NVARCHAR(100) NOT NULL UNIQUE,
        LICENSE_TYPE NVARCHAR(50), -- TRIAL, MONTHLY, YEARLY, LIFETIME
        ACTIVATION_DATE DATETIME,
        EXPIRY_DATE DATETIME,
        REMAINING_DAYS INT,
        STATUS NVARCHAR(50), -- ACTIVE, EXPIRED, REVOKED
        CREATED_BY NVARCHAR(50),
        CREATED_DATE DATETIME DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME
    );
END;

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_COMMAND]') AND type in (N'U'))
BEGIN
    CREATE TABLE CM_CLIENT_COMMAND (
        COMMAND_ID INT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_CODE NVARCHAR(50) NOT NULL,
        COMMAND_TYPE NVARCHAR(100) NOT NULL, -- RESTART_SCHEDULER, REFRESH_CONFIGURATION, RUN_SYNC, DOWNLOAD_LOGS, UPLOAD_LOGS, TAKE_BACKUP, REFRESH_LICENSE, RESTART_APPLICATION, CLEAR_CACHE
        COMMAND_PARAMS NVARCHAR(MAX),
        STATUS NVARCHAR(50) DEFAULT 'PENDING', -- PENDING, RUNNING, COMPLETED, FAILED
        CREATED_BY NVARCHAR(50),
        CREATED_DATE DATETIME DEFAULT GETDATE()
    );
END;

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_COMMAND_HISTORY]') AND type in (N'U'))
BEGIN
    CREATE TABLE CM_CLIENT_COMMAND_HISTORY (
        HISTORY_ID INT IDENTITY(1,1) PRIMARY KEY,
        COMMAND_ID INT NOT NULL,
        CLIENT_CODE NVARCHAR(50) NOT NULL,
        COMMAND_TYPE NVARCHAR(100) NOT NULL,
        COMMAND_PARAMS NVARCHAR(MAX),
        STATUS NVARCHAR(50),
        EXECUTION_RESULT NVARCHAR(MAX),
        EXECUTED_BY NVARCHAR(50),
        EXECUTED_TIME DATETIME DEFAULT GETDATE()
    );
END;

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_VERSION]') AND type in (N'U'))
BEGIN
    CREATE TABLE CM_CLIENT_VERSION (
        VERSION_ID INT IDENTITY(1,1) PRIMARY KEY,
        VERSION_CODE NVARCHAR(50) NOT NULL UNIQUE, -- e.g. v1.4.0
        BUILD_NUMBER NVARCHAR(50),
        RELEASE_DATE DATETIME,
        DOWNLOAD_URL NVARCHAR(250),
        IS_ACTIVE BIT DEFAULT 1,
        CREATED_BY NVARCHAR(50),
        CREATED_DATE DATETIME DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME
    );
END;

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_LOG]') AND type in (N'U'))
BEGIN
    CREATE TABLE CM_CLIENT_LOG (
        LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_CODE NVARCHAR(50) NOT NULL,
        LOG_TYPE NVARCHAR(50), -- APPLICATION, ERROR, SCHEDULER
        LOG_CONTENT NVARCHAR(MAX),
        LOG_TIME DATETIME,
        UPLOADED_TIME DATETIME DEFAULT GETDATE()
    );
END;

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_BACKUP_HISTORY]') AND type in (N'U'))
BEGIN
    CREATE TABLE CM_CLIENT_BACKUP_HISTORY (
        BACKUP_ID INT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_CODE NVARCHAR(50) NOT NULL,
        LAST_BACKUP DATETIME,
        BACKUP_STATUS NVARCHAR(50), -- SUCCESS, FAILED
        BACKUP_SIZE BIGINT,
        BACKUP_LOCATION NVARCHAR(250),
        FAILURE_REASON NVARCHAR(MAX)
    );
END;

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CM_CLIENT_NOTIFICATION]') AND type in (N'U'))
BEGIN
    CREATE TABLE CM_CLIENT_NOTIFICATION (
        NOTIFICATION_ID INT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_CODE NVARCHAR(50) NOT NULL,
        SEVERITY NVARCHAR(50), -- INFO, WARNING, CRITICAL
        MESSAGE NVARCHAR(MAX),
        IS_READ BIT DEFAULT 0,
        CREATED_DATE DATETIME DEFAULT GETDATE()
    );
END;

-- Seed Initial Clients and Details
IF NOT EXISTS (SELECT * FROM CM_CLIENT_MASTER WHERE CLIENT_CODE = 'CLI001')
BEGIN
    INSERT INTO CM_CLIENT_MASTER (CLIENT_CODE, CLIENT_NAME, COMPANY_NAME, CONTACT_PERSON, EMAIL, MOBILE, ERP_VERSION, AGENT_VERSION, SERVER_NAME, DATABASE_NAME, DOMAIN_IP, LICENSE_KEY, LICENSE_TYPE, INSTALLATION_DATE, LAST_SYNC, LAST_HEARTBEAT, CURRENT_STATUS, CREATED_BY)
    VALUES ('CLI001', 'ACME Corporation', 'ACME Industrial Ltd', 'John Doe', 'john@acme.com', '9876543210', 'v1.4.0', 'v1.0.0', 'ACME-SRV-01', 'ACME_ERP', 'acme-erp.com', 'LIC-ACME-999', 'YEARLY', DATEADD(day, -30, GETDATE()), GETDATE(), GETDATE(), 'ONLINE', 'System');
END;

IF NOT EXISTS (SELECT * FROM CM_CLIENT_MASTER WHERE CLIENT_CODE = 'CLI002')
BEGIN
    INSERT INTO CM_CLIENT_MASTER (CLIENT_CODE, CLIENT_NAME, COMPANY_NAME, CONTACT_PERSON, EMAIL, MOBILE, ERP_VERSION, AGENT_VERSION, SERVER_NAME, DATABASE_NAME, DOMAIN_IP, LICENSE_KEY, LICENSE_TYPE, INSTALLATION_DATE, LAST_SYNC, LAST_HEARTBEAT, CURRENT_STATUS, CREATED_BY)
    VALUES ('CLI002', 'Globex Corporation', 'Globex International', 'Hank Scorpio', 'hank@globex.com', '9876543211', 'v1.4.0', 'v1.0.0', 'GLOBEX-SRV-02', 'GLOBEX_ERP', 'globex-erp.com', 'LIC-GLOB-777', 'LIFETIME', DATEADD(day, -100, GETDATE()), GETDATE(), GETDATE(), 'ONLINE', 'System');
END;

IF NOT EXISTS (SELECT * FROM CM_CLIENT_MASTER WHERE CLIENT_CODE = 'CLI003')
BEGIN
    INSERT INTO CM_CLIENT_MASTER (CLIENT_CODE, CLIENT_NAME, COMPANY_NAME, CONTACT_PERSON, EMAIL, MOBILE, ERP_VERSION, AGENT_VERSION, SERVER_NAME, DATABASE_NAME, DOMAIN_IP, LICENSE_KEY, LICENSE_TYPE, INSTALLATION_DATE, LAST_SYNC, LAST_HEARTBEAT, CURRENT_STATUS, CREATED_BY)
    VALUES ('CLI003', 'Initech Corporation', 'Initech Software', 'Peter Gibbons', 'peter@initech.com', '9876543212', 'v1.3.5', 'v1.0.0', 'INIT-SRV-01', 'INIT_ERP', 'initech-erp.com', 'LIC-INIT-333', 'MONTHLY', DATEADD(day, -45, GETDATE()), GETDATE(), GETDATE(), 'WARNING', 'System');
END;

-- Seed Licenses
IF NOT EXISTS (SELECT * FROM CM_CLIENT_LICENSE WHERE LICENSE_KEY = 'LIC-ACME-999')
BEGIN
    INSERT INTO CM_CLIENT_LICENSE (CLIENT_CODE, LICENSE_KEY, LICENSE_TYPE, ACTIVATION_DATE, EXPIRY_DATE, REMAINING_DAYS, STATUS, CREATED_BY)
    VALUES ('CLI001', 'LIC-ACME-999', 'YEARLY', DATEADD(day, -30, GETDATE()), DATEADD(day, 120, GETDATE()), 120, 'ACTIVE', 'System');
END;

IF NOT EXISTS (SELECT * FROM CM_CLIENT_LICENSE WHERE LICENSE_KEY = 'LIC-GLOB-777')
BEGIN
    INSERT INTO CM_CLIENT_LICENSE (CLIENT_CODE, LICENSE_KEY, LICENSE_TYPE, ACTIVATION_DATE, EXPIRY_DATE, REMAINING_DAYS, STATUS, CREATED_BY)
    VALUES ('CLI002', 'LIC-GLOB-777', 'LIFETIME', DATEADD(day, -100, GETDATE()), DATEADD(year, 10, GETDATE()), 3650, 'ACTIVE', 'System');
END;

IF NOT EXISTS (SELECT * FROM CM_CLIENT_LICENSE WHERE LICENSE_KEY = 'LIC-INIT-333')
BEGIN
    INSERT INTO CM_CLIENT_LICENSE (CLIENT_CODE, LICENSE_KEY, LICENSE_TYPE, ACTIVATION_DATE, EXPIRY_DATE, REMAINING_DAYS, STATUS, CREATED_BY)
    VALUES ('CLI003', 'LIC-INIT-333', 'MONTHLY', DATEADD(day, -45, GETDATE()), DATEADD(day, -15, GETDATE()), 0, 'EXPIRED', 'System');
END;

-- Seed Configurations
IF NOT EXISTS (SELECT * FROM CM_CLIENT_CONFIGURATION WHERE CLIENT_CODE = 'CLI001' AND CONFIG_KEY = 'DB_URL')
BEGIN
    INSERT INTO CM_CLIENT_CONFIGURATION (CLIENT_CODE, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, SYNC_STATUS, LAST_SYNC_TIME, CREATED_BY)
    VALUES ('CLI001', 'DATABASE', 'DB_URL', 'jdbc:sqlserver://10.0.0.5:1433;databaseName=ACME_ERP', 'SYNCED', GETDATE(), 'System');
END;

IF NOT EXISTS (SELECT * FROM CM_CLIENT_CONFIGURATION WHERE CLIENT_CODE = 'CLI001' AND CONFIG_KEY = 'MAIL_HOST')
BEGIN
    INSERT INTO CM_CLIENT_CONFIGURATION (CLIENT_CODE, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, SYNC_STATUS, LAST_SYNC_TIME, CREATED_BY)
    VALUES ('CLI001', 'MAIL', 'MAIL_HOST', 'smtp.acme.com', 'SYNCED', GETDATE(), 'System');
END;

-- Seed Versions
IF NOT EXISTS (SELECT * FROM CM_CLIENT_VERSION WHERE VERSION_CODE = 'v1.4.0')
BEGIN
    INSERT INTO CM_CLIENT_VERSION (VERSION_CODE, BUILD_NUMBER, RELEASE_DATE, DOWNLOAD_URL, IS_ACTIVE, CREATED_BY)
    VALUES ('v1.4.0', '1040', DATEADD(day, -30, GETDATE()), 'https://updates.autonoma.com/downloads/v1.4.0.zip', 1, 'System');
END;

IF NOT EXISTS (SELECT * FROM CM_CLIENT_VERSION WHERE VERSION_CODE = 'v1.4.1')
BEGIN
    INSERT INTO CM_CLIENT_VERSION (VERSION_CODE, BUILD_NUMBER, RELEASE_DATE, DOWNLOAD_URL, IS_ACTIVE, CREATED_BY)
    VALUES ('v1.4.1', '1041', GETDATE(), 'https://updates.autonoma.com/downloads/v1.4.1.zip', 1, 'System');
END;

-- Seed Notifications
INSERT INTO CM_CLIENT_NOTIFICATION (CLIENT_CODE, SEVERITY, MESSAGE, IS_READ)
VALUES ('CLI003', 'WARNING', 'License key LIC-INIT-333 has expired!', 0);

INSERT INTO CM_CLIENT_NOTIFICATION (CLIENT_CODE, SEVERITY, MESSAGE, IS_READ)
VALUES ('CLI001', 'INFO', 'Heartbeat received successfully.', 1);
