-- ============================================================
-- V395.0 — BOS AI Platform: Skill Manifest Audit Log Columns
-- Adds PERMISSION_STATUS, ENTITY_RESOLVED, OPERATION_RESOLVED
-- to SYS_AI_AUDIT_LOG for full enterprise traceability.
-- ============================================================

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'SYS_AI_AUDIT_LOG'
      AND COLUMN_NAME = 'PERMISSION_STATUS'
)
BEGIN
    ALTER TABLE SYS_AI_AUDIT_LOG
    ADD PERMISSION_STATUS NVARCHAR(20) NULL;
    PRINT 'Added PERMISSION_STATUS column';
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'SYS_AI_AUDIT_LOG'
      AND COLUMN_NAME = 'ENTITY_RESOLVED'
)
BEGIN
    ALTER TABLE SYS_AI_AUDIT_LOG
    ADD ENTITY_RESOLVED NVARCHAR(50) NULL;
    PRINT 'Added ENTITY_RESOLVED column';
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'SYS_AI_AUDIT_LOG'
      AND COLUMN_NAME = 'OPERATION_RESOLVED'
)
BEGIN
    ALTER TABLE SYS_AI_AUDIT_LOG
    ADD OPERATION_RESOLVED NVARCHAR(50) NULL;
    PRINT 'Added OPERATION_RESOLVED column';
END

PRINT 'V395.0 complete — AI audit log extended with Skill Manifest traceability fields';
