-- Migration V1047.0: Add SECONDARY_HOST_ID and TERTIARY_HOST_ID to QMS_MEETING_SCHEDULE table

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') AND name = 'SECONDARY_HOST_ID')
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ADD SECONDARY_HOST_ID BIGINT NOT NULL DEFAULT 0;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') AND name = 'TERTIARY_HOST_ID')
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ADD TERTIARY_HOST_ID BIGINT NOT NULL DEFAULT 0;
END
GO
