-- ===============================================================================
-- DDL Script: Create Dynamic Schedule Rule Builder Tables for QMS Meeting Module
-- Target DB: Microsoft SQL Server (AUTONOMA / ERPDb_NUTECH)
-- ===============================================================================

-- 1. Create QMS_SCHEDULE_RULE Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QMS_SCHEDULE_RULE]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[QMS_SCHEDULE_RULE] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RULE_NAME] NVARCHAR(200) NOT NULL,
        [DESCRIPTION] NVARCHAR(500) NULL,
        [CONFIG_ID] BIGINT NULL,
        [MEETING_ID] BIGINT NULL,
        [BASE_DATE_GENERATOR] NVARCHAR(50) NOT NULL DEFAULT 'FREQUENCY_DATE',
        [BASE_DATE_PARAMS] NVARCHAR(MAX) NULL,
        [PRIORITY] INT NOT NULL DEFAULT 1,
        [STATUS] NVARCHAR(20) NULL DEFAULT 'ACTIVE',
        [IS_ACTIVE] BIT NULL DEFAULT 1,
        [CREATED_BY] NVARCHAR(50) NULL,
        [CREATED_DATE] DATETIME2 NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME2 NULL,
        CONSTRAINT [PK_QMS_SCHEDULE_RULE] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
    PRINT 'Created table QMS_SCHEDULE_RULE';
END;
GO

-- 2. Create QMS_SCHEDULE_RULE_GROUP Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QMS_SCHEDULE_RULE_GROUP]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[QMS_SCHEDULE_RULE_GROUP] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RULE_ID] BIGINT NULL,
        [PARENT_GROUP_ID] BIGINT NULL,
        [LOGICAL_OPERATOR] NVARCHAR(10) NOT NULL DEFAULT 'ALL',
        CONSTRAINT [PK_QMS_SCHEDULE_RULE_GROUP] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [FK_QMS_SCHEDULE_RULE_GROUP_RULE] FOREIGN KEY ([RULE_ID]) REFERENCES [dbo].[QMS_SCHEDULE_RULE] ([ID]) ON DELETE CASCADE,
        CONSTRAINT [FK_QMS_SCHEDULE_RULE_GROUP_PARENT] FOREIGN KEY ([PARENT_GROUP_ID]) REFERENCES [dbo].[QMS_SCHEDULE_RULE_GROUP] ([ID])
    );
    PRINT 'Created table QMS_SCHEDULE_RULE_GROUP';
END;
GO

-- 3. Create QMS_SCHEDULE_RULE_CONDITION Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QMS_SCHEDULE_RULE_CONDITION]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[QMS_SCHEDULE_RULE_CONDITION] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [GROUP_ID] BIGINT NULL,
        [FIELD_CODE] NVARCHAR(50) NOT NULL,
        [OPERATOR_CODE] NVARCHAR(50) NOT NULL,
        [CONDITION_VALUE] NVARCHAR(MAX) NULL,
        [DATA_TYPE] NVARCHAR(20) NOT NULL DEFAULT 'TEXT',
        [LOGICAL_OPERATOR] NVARCHAR(10) NULL DEFAULT 'AND',
        CONSTRAINT [PK_QMS_SCHEDULE_RULE_CONDITION] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [FK_QMS_SCHEDULE_RULE_CONDITION_GROUP] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[QMS_SCHEDULE_RULE_GROUP] ([ID]) ON DELETE CASCADE
    );
    PRINT 'Created table QMS_SCHEDULE_RULE_CONDITION';
END;
GO

-- 4. Create QMS_SCHEDULE_RULE_ACTION Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QMS_SCHEDULE_RULE_ACTION]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[QMS_SCHEDULE_RULE_ACTION] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RULE_ID] BIGINT NULL,
        [ACTION_TYPE] NVARCHAR(50) NOT NULL,
        [ACTION_PARAMS] NVARCHAR(MAX) NULL,
        CONSTRAINT [PK_QMS_SCHEDULE_RULE_ACTION] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [FK_QMS_SCHEDULE_RULE_ACTION_RULE] FOREIGN KEY ([RULE_ID]) REFERENCES [dbo].[QMS_SCHEDULE_RULE] ([ID]) ON DELETE CASCADE
    );
    PRINT 'Created table QMS_SCHEDULE_RULE_ACTION';
END;
GO

-- 5. Create QMS_SCHEDULE_RULE_FALLBACK Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QMS_SCHEDULE_RULE_FALLBACK]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[QMS_SCHEDULE_RULE_FALLBACK] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RULE_ID] BIGINT NULL,
        [FALLBACK_ACTION_TYPE] NVARCHAR(50) NOT NULL,
        [TARGET_RULE_ID] BIGINT NULL,
        [PRIORITY] INT NOT NULL DEFAULT 1,
        [ACTION_PARAMS] NVARCHAR(MAX) NULL,
        CONSTRAINT [PK_QMS_SCHEDULE_RULE_FALLBACK] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [FK_QMS_SCHEDULE_RULE_FALLBACK_RULE] FOREIGN KEY ([RULE_ID]) REFERENCES [dbo].[QMS_SCHEDULE_RULE] ([ID]) ON DELETE CASCADE
    );
    PRINT 'Created table QMS_SCHEDULE_RULE_FALLBACK';
END;
GO
