-- Migration: Uppercase PAYMENT_MODE and WAGES_TYPE in HR_EMPLOYEE_JOB_PROFILE, and migrate BANK_TRANSFER to BANK
UPDATE HR_EMPLOYEE_JOB_PROFILE
SET PAYMENT_MODE = UPPER(PAYMENT_MODE),
    WAGES_TYPE = UPPER(WAGES_TYPE);

UPDATE HR_EMPLOYEE_JOB_PROFILE
SET PAYMENT_MODE = 'BANK'
WHERE PAYMENT_MODE IN ('BANK_TRANSFER', 'BANK TRANSFER');
