-- Add STATUS column as BIGINT
IF COL_LENGTH('SM_CUSTOMER_ORDER_HEADER', 'STATUS') IS NULL
BEGIN
    ALTER TABLE SM_CUSTOMER_ORDER_HEADER ADD STATUS BIGINT;
END

-- Add Foreign Key constraint to AD_STATUS_MASTER
IF OBJECT_ID('FK_SM_CUSTOMER_ORDER_STATUS', 'F') IS NULL
BEGIN
    ALTER TABLE SM_CUSTOMER_ORDER_HEADER ADD CONSTRAINT FK_SM_CUSTOMER_ORDER_STATUS FOREIGN KEY (STATUS) REFERENCES AD_STATUS_MASTER(ID);
END
