-- =================================================================================
-- Migration Script: Rename WHERE_FROM to FROM_WHERE and alter to VARCHAR(25)
-- Date: 2026-07-22
-- Description: Standardize column name to FROM_WHERE VARCHAR(25) NULL across
--              HR_PERMISSION_DETAILS, HR_OD_DETAILS, and HR_LEAVE_DETAILS.
-- =================================================================================

-- 1. HR_PERMISSION_DETAILS
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'HR_PERMISSION_DETAILS')
BEGIN
    IF COL_LENGTH('dbo.HR_PERMISSION_DETAILS', 'WHERE_FROM') IS NOT NULL
       AND COL_LENGTH('dbo.HR_PERMISSION_DETAILS', 'FROM_WHERE') IS NULL
    BEGIN
        EXEC sp_rename 'dbo.HR_PERMISSION_DETAILS.WHERE_FROM', 'FROM_WHERE', 'COLUMN';
        PRINT 'Renamed WHERE_FROM to FROM_WHERE in HR_PERMISSION_DETAILS';
    END

    IF COL_LENGTH('dbo.HR_PERMISSION_DETAILS', 'FROM_WHERE') IS NOT NULL
    BEGIN
        ALTER TABLE dbo.HR_PERMISSION_DETAILS ALTER COLUMN FROM_WHERE VARCHAR(25) NULL;
        PRINT 'Altered FROM_WHERE to VARCHAR(25) in HR_PERMISSION_DETAILS';
    END
END
GO

-- 2. HR_OD_DETAILS
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'HR_OD_DETAILS')
BEGIN
    IF COL_LENGTH('dbo.HR_OD_DETAILS', 'WHERE_FROM') IS NOT NULL
       AND COL_LENGTH('dbo.HR_OD_DETAILS', 'FROM_WHERE') IS NULL
    BEGIN
        EXEC sp_rename 'dbo.HR_OD_DETAILS.WHERE_FROM', 'FROM_WHERE', 'COLUMN';
        PRINT 'Renamed WHERE_FROM to FROM_WHERE in HR_OD_DETAILS';
    END

    IF COL_LENGTH('dbo.HR_OD_DETAILS', 'FROM_WHERE') IS NOT NULL
    BEGIN
        ALTER TABLE dbo.HR_OD_DETAILS ALTER COLUMN FROM_WHERE VARCHAR(25) NULL;
        PRINT 'Altered FROM_WHERE to VARCHAR(25) in HR_OD_DETAILS';
    END
END
GO

-- 3. HR_LEAVE_DETAILS
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'HR_LEAVE_DETAILS')
BEGIN
    IF COL_LENGTH('dbo.HR_LEAVE_DETAILS', 'FROM_WHERE') IS NOT NULL
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_DETAILS ALTER COLUMN FROM_WHERE VARCHAR(25) NULL;
        PRINT 'Altered FROM_WHERE to VARCHAR(25) in HR_LEAVE_DETAILS';
    END
END
GO
