-- Drop Setup/Cycle from Main Process Table
ALTER TABLE [dbo].[NPD_BOM_PROCESS] DROP COLUMN [SETUP_TIME];
ALTER TABLE [dbo].[NPD_BOM_PROCESS] DROP COLUMN [CYCLE_TIME];

-- Add Auto GIR and Auto QC to Main Process Table
ALTER TABLE [dbo].[NPD_BOM_PROCESS] ADD [AUTO_GIR] BIT NULL DEFAULT 0;
ALTER TABLE [dbo].[NPD_BOM_PROCESS] ADD [AUTO_QC] BIT NULL DEFAULT 0;

-- Add Setup/Cycle to Machine Allocations Table
ALTER TABLE [dbo].[NPD_BOM_PROCESS_MACHINE] ADD [SETUP_TIME] DECIMAL(10,2) NULL DEFAULT 0;
ALTER TABLE [dbo].[NPD_BOM_PROCESS_MACHINE] ADD [CYCLE_TIME] DECIMAL(10,2) NULL DEFAULT 0;
