-- 1. Drop the old columns if they exist in QMS_AUDIT_ATTENDANCE
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QMS_AUDIT_ATTENDANCE' AND COLUMN_NAME = 'AUDIT_SCHEDULE_NO')
BEGIN
    ALTER TABLE QMS_AUDIT_ATTENDANCE DROP COLUMN AUDIT_SCHEDULE_NO;
END;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QMS_AUDIT_ATTENDANCE' AND COLUMN_NAME = 'AUDIT_SCHEDULE_ID')
BEGIN
    ALTER TABLE QMS_AUDIT_ATTENDANCE DROP COLUMN AUDIT_SCHEDULE_ID;
END;

-- 2. Add the new AUDIT_SCH_ID column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QMS_AUDIT_ATTENDANCE' AND COLUMN_NAME = 'AUDIT_SCH_ID')
BEGIN
    ALTER TABLE QMS_AUDIT_ATTENDANCE ADD AUDIT_SCH_ID BIGINT;
END;
