-- V329.0 Create missing Employee File Mapping Tables to fix Hibernate loading error
IF OBJECT_ID('HR_EMPLOYEE_AUDITOR_FILE_MAPPING', 'U') IS NOT NULL
    DROP TABLE HR_EMPLOYEE_AUDITOR_FILE_MAPPING;

IF OBJECT_ID('HR_EMPLOYEE_AUDITEE_FILE_MAPPING', 'U') IS NOT NULL
    DROP TABLE HR_EMPLOYEE_AUDITEE_FILE_MAPPING;

IF OBJECT_ID('HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING', 'U') IS NOT NULL
    DROP TABLE HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING;

CREATE TABLE HR_EMPLOYEE_AUDITOR_FILE_MAPPING (
    ID INT IDENTITY(1,1) NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    FILE_PATH NVARCHAR(500) NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'System',
    CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50) NOT NULL DEFAULT 'System',
    UPDATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_HR_EMPLOYEE_AUDITOR_FILE_MAPPING PRIMARY KEY (ID),
    CONSTRAINT FK_HR_EMPLOYEE_AUDITOR_FILE_MAPPING_HR_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(ID),
    CONSTRAINT FK_HR_EMPLOYEE_AUDITOR_FILE_MAPPING_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_HR_EMPLOYEE_AUDITOR_FILE_MAPPING_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);

CREATE TABLE HR_EMPLOYEE_AUDITEE_FILE_MAPPING (
    ID INT IDENTITY(1,1) NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    FILE_PATH NVARCHAR(500) NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'System',
    CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50) NOT NULL DEFAULT 'System',
    UPDATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_HR_EMPLOYEE_AUDITEE_FILE_MAPPING PRIMARY KEY (ID),
    CONSTRAINT FK_HR_EMPLOYEE_AUDITEE_FILE_MAPPING_HR_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(ID),
    CONSTRAINT FK_HR_EMPLOYEE_AUDITEE_FILE_MAPPING_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_HR_EMPLOYEE_AUDITEE_FILE_MAPPING_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);

CREATE TABLE HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING (
    ID INT IDENTITY(1,1) NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    FILE_PATH NVARCHAR(500) NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'System',
    CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50) NOT NULL DEFAULT 'System',
    UPDATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING PRIMARY KEY (ID),
    CONSTRAINT FK_HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING_HR_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(ID),
    CONSTRAINT FK_HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);
