-- Add ACTIVE_EMAIL_PROVIDER and PROVIDER_CONFIGS_JSON columns to AD_OCR_CONFIG table
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_OCR_CONFIG]') AND name = 'ACTIVE_EMAIL_PROVIDER')
BEGIN
    ALTER TABLE [dbo].[AD_OCR_CONFIG] ADD [ACTIVE_EMAIL_PROVIDER] NVARCHAR(50) NOT NULL DEFAULT 'OUTLOOK';
    PRINT 'Added column ACTIVE_EMAIL_PROVIDER to AD_OCR_CONFIG';
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_OCR_CONFIG]') AND name = 'PROVIDER_CONFIGS_JSON')
BEGIN
    ALTER TABLE [dbo].[AD_OCR_CONFIG] ADD [PROVIDER_CONFIGS_JSON] NVARCHAR(MAX) NULL;
    PRINT 'Added column PROVIDER_CONFIGS_JSON to AD_OCR_CONFIG';
END
GO
