IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE Name = N'REORDER_LEVEL'
    AND Object_ID = Object_ID(N'NPD_PRODUCT_MASTER')
)
BEGIN
    ALTER TABLE NPD_PRODUCT_MASTER ADD REORDER_LEVEL INT;
END;

IF EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE Name = N'LEAD_TIME_MIN'
    AND Object_ID = Object_ID(N'NPD_PRODUCT_MASTER')
)
BEGIN
    ALTER TABLE NPD_PRODUCT_MASTER ALTER COLUMN LEAD_TIME_MIN INT;
END;
