-- IDEMPOTENT DB MIGRATION: Checklist Scheduler Enterprise Compliance

-- 1. Add HOLIDAY_STRATEGY to SCHEDULE_CONFIGURATION
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SCHEDULE_CONFIGURATION') AND name = 'HOLIDAY_STRATEGY')
BEGIN
    ALTER TABLE SCHEDULE_CONFIGURATION ADD HOLIDAY_STRATEGY VARCHAR(20) DEFAULT 'NEXT';
END;

-- 2. Add ADDITIONAL_EMPLOYEE_IDS to QMS_CHECKLIST_MASTER
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_MASTER') AND name = 'ADDITIONAL_EMPLOYEE_IDS')
BEGIN
    ALTER TABLE QMS_CHECKLIST_MASTER ADD ADDITIONAL_EMPLOYEE_IDS VARCHAR(1000);
END;

-- 3. Add columns to QMS_CHECKLIST_ASSIGNMENT
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'EXECUTION_TYPE')
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD EXECUTION_TYPE VARCHAR(10) DEFAULT 'AUTO';
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'SCHEDULER_NAME')
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD SCHEDULER_NAME VARCHAR(100);
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'TRIGGER_ID')
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD TRIGGER_ID BIGINT;
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'DUE_DATE')
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD DUE_DATE DATE;
END;

-- 4. Add columns to QMS_CHECKLIST_CLOSED
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED') AND name = 'EXECUTION_TYPE')
BEGIN
    ALTER TABLE QMS_CHECKLIST_CLOSED ADD EXECUTION_TYPE VARCHAR(10) DEFAULT 'AUTO';
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED') AND name = 'SCHEDULER_NAME')
BEGIN
    ALTER TABLE QMS_CHECKLIST_CLOSED ADD SCHEDULER_NAME VARCHAR(100);
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED') AND name = 'TRIGGER_ID')
BEGIN
    ALTER TABLE QMS_CHECKLIST_CLOSED ADD TRIGGER_ID BIGINT;
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED') AND name = 'DUE_DATE')
BEGIN
    ALTER TABLE QMS_CHECKLIST_CLOSED ADD DUE_DATE DATE;
END;

-- 5. Create QMS_SCHEDULER_EXECUTION_LOG table
IF OBJECT_ID('QMS_SCHEDULER_EXECUTION_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE QMS_SCHEDULER_EXECUTION_LOG (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        SCHEDULER_NAME VARCHAR(100) NOT NULL,
        EXECUTION_TYPE VARCHAR(10) NOT NULL,
        TRIGGER_TIME DATETIME NOT NULL,
        START_TIME DATETIME NOT NULL,
        END_TIME DATETIME NOT NULL,
        DURATION_MS BIGINT,
        SUCCESS_COUNT INT DEFAULT 0,
        FAILED_COUNT INT DEFAULT 0,
        SKIPPED_COUNT INT DEFAULT 0,
        STATUS VARCHAR(20) NOT NULL,
        REASON VARCHAR(500),
        MACHINE_NAME VARCHAR(100),
        IP_ADDRESS VARCHAR(50),
        APP_VERSION VARCHAR(20)
    );
END;

-- 6. Backfill existing configurations
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SCHEDULE_CONFIGURATION') AND name = 'HOLIDAY_STRATEGY')
BEGIN
    EXEC('UPDATE SCHEDULE_CONFIGURATION SET HOLIDAY_STRATEGY = ''NEXT'' WHERE HOLIDAY_STRATEGY IS NULL');
END;
