-- Migration: V409.0 Optimize QMS Meeting Master Employee Mapping Schema
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_MASTER') AND name = 'EMPLOYEE_ID')
BEGIN
    IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_QMS_MEETING_EMPLOYEE')
    BEGIN
        ALTER TABLE [dbo].[QMS_MEETING_MASTER] DROP CONSTRAINT [FK_QMS_MEETING_EMPLOYEE];
    END
    ALTER TABLE [dbo].[QMS_MEETING_MASTER] DROP COLUMN [EMPLOYEE_ID];
END
GO

-- Alter EMPLOYEE_ID in QMS_MEETING_EMPLOYEE_MAPPING to BIGINT to match HR_EMPLOYEE(ID)
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_EMPLOYEE_MAPPING') AND name = 'EMPLOYEE_ID')
BEGIN
    ALTER TABLE [dbo].[QMS_MEETING_EMPLOYEE_MAPPING] ALTER COLUMN [EMPLOYEE_ID] BIGINT NULL;
END
GO

-- Add foreign key constraints to QMS_MEETING_EMPLOYEE_MAPPING if they do not exist
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_QMS_MEETING_EMP_MAP_MEETING')
BEGIN
    ALTER TABLE [dbo].[QMS_MEETING_EMPLOYEE_MAPPING] WITH CHECK ADD CONSTRAINT [FK_QMS_MEETING_EMP_MAP_MEETING]
        FOREIGN KEY ([MEETING_ID]) REFERENCES [dbo].[QMS_MEETING_MASTER] ([ID]) ON DELETE CASCADE;
    ALTER TABLE [dbo].[QMS_MEETING_EMPLOYEE_MAPPING] CHECK CONSTRAINT [FK_QMS_MEETING_EMP_MAP_MEETING];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_QMS_MEETING_EMP_MAP_EMP')
BEGIN
    ALTER TABLE [dbo].[QMS_MEETING_EMPLOYEE_MAPPING] WITH CHECK ADD CONSTRAINT [FK_QMS_MEETING_EMP_MAP_EMP]
        FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[HR_EMPLOYEE] ([ID]);
    ALTER TABLE [dbo].[QMS_MEETING_EMPLOYEE_MAPPING] CHECK CONSTRAINT [FK_QMS_MEETING_EMP_MAP_EMP];
END
GO
