-- Script: Add NEXT_RENEWAL_DATE column and auto-update missing REMINDER_DATE values
-- Module: Quality Management Systems (QMS) - Checklist Renewal

-- 1. Add NEXT_RENEWAL_DATE column to QMS_CHECKLIST_ASSIGNMENT table
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'QMS_CHECKLIST_ASSIGNMENT' AND COLUMN_NAME = 'NEXT_RENEWAL_DATE'
)
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD NEXT_RENEWAL_DATE DATE NULL;
END;
GO

-- 2. Add NEXT_RENEWAL_DATE column to QMS_CHECKLIST_CLOSED table
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'QMS_CHECKLIST_CLOSED' AND COLUMN_NAME = 'NEXT_RENEWAL_DATE'
)
BEGIN
    ALTER TABLE QMS_CHECKLIST_CLOSED ADD NEXT_RENEWAL_DATE DATE NULL;
END;
GO

-- 3. Auto-populate missing REMINDER_DATE in QMS_CHECKLIST_MASTER (EXPIRY_DATE - REMINDER_DAYS)
UPDATE QMS_CHECKLIST_MASTER
SET REMINDER_DATE = DATEADD(DAY, -ISNULL(REMINDER_DAYS, 0), EXPIRY_DATE)
WHERE CATEGORY = 'RENEWAL'
  AND EXPIRY_DATE IS NOT NULL
  AND REMINDER_DATE IS NULL;
GO
