-- DDL to add STREAM column to HR_EMPLOYEE_EDUCATION table
IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMPLOYEE_EDUCATION') 
      AND name = 'STREAM'
)
BEGIN
    ALTER TABLE HR_EMPLOYEE_EDUCATION ADD STREAM VARCHAR(150) NULL;
END
