IF OBJECT_ID('UQ_DD_PRODUCT_PROCESS_CODE', 'UQ') IS NOT NULL
    ALTER TABLE DD_PRODUCT_PROCESS DROP CONSTRAINT UQ_DD_PRODUCT_PROCESS_CODE;

IF OBJECT_ID('UQ_DD_PRODUCT_PROCESS_NAME', 'UQ') IS NOT NULL
    ALTER TABLE DD_PRODUCT_PROCESS DROP CONSTRAINT UQ_DD_PRODUCT_PROCESS_NAME;

-- Add composite unique constraints per Product
ALTER TABLE DD_PRODUCT_PROCESS ADD CONSTRAINT UQ_DD_PROD_PROC_CODE UNIQUE (PRODUCT_ID, PROCESS_CODE);
ALTER TABLE DD_PRODUCT_PROCESS ADD CONSTRAINT UQ_DD_PROD_PROC_NAME UNIQUE (PRODUCT_ID, PROCESS_NAME);
