-- Migration: Strip leading '@' character from DOMAIN_NAME columns to maintain clean corporate domains without '@'
-- Author: Autonoma ERP
-- Date: 2026-08-20

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FA_ACCOUNT_LEDGER' AND COLUMN_NAME = 'DOMAIN_NAME')
BEGIN
    UPDATE FA_ACCOUNT_LEDGER
    SET DOMAIN_NAME = LTRIM(RTRIM(SUBSTRING(DOMAIN_NAME, 2, LEN(DOMAIN_NAME))))
    WHERE DOMAIN_NAME LIKE '@%';
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMER_DOMAIN_MAPPING' AND COLUMN_NAME = 'DOMAIN_NAME')
BEGIN
    UPDATE CUSTOMER_DOMAIN_MAPPING
    SET DOMAIN_NAME = LTRIM(RTRIM(SUBSTRING(DOMAIN_NAME, 2, LEN(DOMAIN_NAME))))
    WHERE DOMAIN_NAME LIKE '@%';
END
GO
