-- Organization: Nutech Wind Parts Pvt Ltd
-- Owner: Nutech
-- Created At: 2026-09-01
-- Description: Add DIVISION, PRODUCT_ID, and DESCRIPTION columns to BOM tables for legacy data mapping

-- 1. NPD_BOM_MASTER: Add DIVISION
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NPD_BOM_MASTER')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'DIVISION' AND object_id = OBJECT_ID('NPD_BOM_MASTER'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_MASTER ADD DIVISION INT NULL;
        PRINT 'Added DIVISION column to NPD_BOM_MASTER.';
    END
END;
GO

-- 2. NPD_BOM_PROCESS: Add PRODUCT_ID, DIVISION, DESCRIPTION
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NPD_BOM_PROCESS')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'PRODUCT_ID' AND object_id = OBJECT_ID('NPD_BOM_PROCESS'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS ADD PRODUCT_ID BIGINT NULL;
        ALTER TABLE dbo.NPD_BOM_PROCESS ADD CONSTRAINT FK_NPD_BOM_PROC_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.NPD_PRODUCT_MASTER(ID);
        PRINT 'Added PRODUCT_ID column and FK to NPD_BOM_PROCESS.';
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'DIVISION' AND object_id = OBJECT_ID('NPD_BOM_PROCESS'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS ADD DIVISION INT NULL;
        PRINT 'Added DIVISION column to NPD_BOM_PROCESS.';
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'DESCRIPTION' AND object_id = OBJECT_ID('NPD_BOM_PROCESS'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS ADD DESCRIPTION NVARCHAR(500) NULL;
        PRINT 'Added DESCRIPTION column to NPD_BOM_PROCESS.';
    END
END;
GO

-- 3. NPD_BOM_PROCESS_MATERIAL: Add PRODUCT_ID, DIVISION
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NPD_BOM_PROCESS_MATERIAL')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'PRODUCT_ID' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_MATERIAL'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_MATERIAL ADD PRODUCT_ID BIGINT NULL;
        ALTER TABLE dbo.NPD_BOM_PROCESS_MATERIAL ADD CONSTRAINT FK_NPD_BOM_MAT_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.NPD_PRODUCT_MASTER(ID);
        PRINT 'Added PRODUCT_ID column and FK to NPD_BOM_PROCESS_MATERIAL.';
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'DIVISION' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_MATERIAL'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_MATERIAL ADD DIVISION INT NULL;
        PRINT 'Added DIVISION column to NPD_BOM_PROCESS_MATERIAL.';
    END
END;
GO

-- 4. NPD_BOM_PROCESS_MACHINE: Add PRODUCT_ID, DIVISION
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NPD_BOM_PROCESS_MACHINE')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'PRODUCT_ID' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_MACHINE'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_MACHINE ADD PRODUCT_ID BIGINT NULL;
        ALTER TABLE dbo.NPD_BOM_PROCESS_MACHINE ADD CONSTRAINT FK_NPD_BOM_MAC_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.NPD_PRODUCT_MASTER(ID);
        PRINT 'Added PRODUCT_ID column and FK to NPD_BOM_PROCESS_MACHINE.';
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'DIVISION' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_MACHINE'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_MACHINE ADD DIVISION INT NULL;
        PRINT 'Added DIVISION column to NPD_BOM_PROCESS_MACHINE.';
    END
END;
GO
