-- Migration: Add individual attempt and status master support to PP_RFQ_EMAIL_HISTORY
-- Database: NUTECH_LIVE

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PP_RFQ_EMAIL_HISTORY') AND name = 'SUPPLIER_ID')
BEGIN
    ALTER TABLE PP_RFQ_EMAIL_HISTORY ADD SUPPLIER_ID BIGINT NULL;
    ALTER TABLE PP_RFQ_EMAIL_HISTORY ADD CONSTRAINT FK_RFQ_EMAIL_HISTORY_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES FA_ACCOUNT_LEDGER(ID);
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PP_RFQ_EMAIL_HISTORY') AND name = 'RECIPIENT_EMAIL')
BEGIN
    ALTER TABLE PP_RFQ_EMAIL_HISTORY ADD RECIPIENT_EMAIL NVARCHAR(255) NULL;
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PP_RFQ_EMAIL_HISTORY') AND name = 'STATUS_ID')
BEGIN
    ALTER TABLE PP_RFQ_EMAIL_HISTORY ADD STATUS_ID BIGINT NULL;
    ALTER TABLE PP_RFQ_EMAIL_HISTORY ADD CONSTRAINT FK_RFQ_EMAIL_HISTORY_STATUS FOREIGN KEY (STATUS_ID) REFERENCES AD_STATUS_MASTER(ID);
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PP_RFQ_EMAIL_HISTORY') AND name = 'ATTEMPT')
BEGIN
    ALTER TABLE PP_RFQ_EMAIL_HISTORY ADD ATTEMPT INT DEFAULT 1;
END;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PP_RFQ_EMAIL_HISTORY') AND name = 'FAILURE_REASON')
BEGIN
    ALTER TABLE PP_RFQ_EMAIL_HISTORY ADD FAILURE_REASON NVARCHAR(MAX) NULL;
END;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('PP_RFQ_EMAIL_HISTORY') AND name = 'IX_PP_RFQ_EMAIL_HISTORY_RFQ_ID')
BEGIN
    CREATE INDEX IX_PP_RFQ_EMAIL_HISTORY_RFQ_ID ON PP_RFQ_EMAIL_HISTORY(RFQ_ID, SENT_DATE DESC);
END;
