SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

-- ============================================================
-- V1109.0 | Add SL, AL, PL columns to HRA_LEAVE_ENCASHMENT_VERIFIED
-- Module : HRA > Payroll > Leave Encashment Entry / Verified
-- Author : Antigravity
-- Date   : 2026-08-03
-- ============================================================

IF COL_LENGTH('dbo.HRA_LEAVE_ENCASHMENT_VERIFIED', 'SL') IS NULL
BEGIN
    ALTER TABLE dbo.HRA_LEAVE_ENCASHMENT_VERIFIED ADD SL DECIMAL(10,2) NOT NULL CONSTRAINT DF_LEVF_SL DEFAULT 0;
    PRINT 'Added SL column to HRA_LEAVE_ENCASHMENT_VERIFIED.';
END
GO

IF COL_LENGTH('dbo.HRA_LEAVE_ENCASHMENT_VERIFIED', 'AL') IS NULL
BEGIN
    ALTER TABLE dbo.HRA_LEAVE_ENCASHMENT_VERIFIED ADD AL DECIMAL(10,2) NOT NULL CONSTRAINT DF_LEVF_AL DEFAULT 0;
    PRINT 'Added AL column to HRA_LEAVE_ENCASHMENT_VERIFIED.';
END
GO

IF COL_LENGTH('dbo.HRA_LEAVE_ENCASHMENT_VERIFIED', 'PL') IS NULL
BEGIN
    ALTER TABLE dbo.HRA_LEAVE_ENCASHMENT_VERIFIED ADD PL DECIMAL(10,2) NOT NULL CONSTRAINT DF_LEVF_PL DEFAULT 0;
    PRINT 'Added PL column to HRA_LEAVE_ENCASHMENT_VERIFIED.';
END
GO
