-- Drop unused columns
ALTER TABLE FA_ACCOUNT_LEDGER DROP COLUMN IS_SUBCON;
ALTER TABLE FA_ACCOUNT_LEDGER DROP COLUMN DAILY_DISPATCH_MAIL;
ALTER TABLE FA_ACCOUNT_LEDGER DROP COLUMN CURRENCY_TYPE;
GO

-- Rename columns
EXEC sp_rename 'FA_ACCOUNT_LEDGER.REFERENCE_CODE', 'CODE', 'COLUMN';
EXEC sp_rename 'FA_ACCOUNT_LEDGER.TCS_ID', 'TCS_LEDGER_ID', 'COLUMN';
EXEC sp_rename 'FA_ACCOUNT_LEDGER.TDS_ID', 'TDS_LEDGER_ID', 'COLUMN';
GO

-- Modify existing columns lengths and types
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN CODE nvarchar(20);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN SHORT_NAME nvarchar(20);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN LOCATION nvarchar(100);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN LEDGER_TYPE nvarchar(25);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN GSTIN nvarchar(20);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN PAN_NO nvarchar(20);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN DOMAIN_NAME nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN REGISTER_NO nvarchar(20);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN CIN_NO nvarchar(20);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN ISO_NUMBER nvarchar(20);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN WEBSITE nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN CURRENCY_CODE nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN TAX_TYPE nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN TAX_PERCENTAGE numeric(10,2);
GO

-- Add new columns
ALTER TABLE FA_ACCOUNT_LEDGER ADD DESCRIPTION nvarchar(200);
ALTER TABLE FA_ACCOUNT_LEDGER ADD LATITUDE nvarchar(25);
ALTER TABLE FA_ACCOUNT_LEDGER ADD LONGITUDE nvarchar(25);
ALTER TABLE FA_ACCOUNT_LEDGER ADD MOBILE_NO nvarchar(15);
ALTER TABLE FA_ACCOUNT_LEDGER ADD MAIL_ID nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ADD MSME_REQ bit;
ALTER TABLE FA_ACCOUNT_LEDGER ADD MSME_NO nvarchar(20);
ALTER TABLE FA_ACCOUNT_LEDGER ADD INDUSTRY_TYPE nvarchar(20);
ALTER TABLE FA_ACCOUNT_LEDGER ADD VENDOR_CODE nvarchar(20);
ALTER TABLE FA_ACCOUNT_LEDGER ADD IS_FINANCE bit;
ALTER TABLE FA_ACCOUNT_LEDGER ADD LABOUR_SALES_ID bigint;
ALTER TABLE FA_ACCOUNT_LEDGER ADD BANK_AC_NO nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ADD BANK_AC_NAME nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ADD BANK_NAME nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ADD BRANCH_NAME nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ADD IFSC_CODE nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ADD OFFICE_NO nvarchar(50);
ALTER TABLE FA_ACCOUNT_LEDGER ADD FAX_NO nvarchar(50);
GO

-- Add UNIQUE constraint to CODE (ensure no duplicate or null values first if necessary, but usually CODE is required and unique)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('FA_ACCOUNT_LEDGER') AND name = 'UQ_FA_ACCOUNT_LEDGER_CODE')
BEGIN
    ALTER TABLE FA_ACCOUNT_LEDGER ADD CONSTRAINT UQ_FA_ACCOUNT_LEDGER_CODE UNIQUE (CODE);
END
GO
