-- Organization: Nutech Wind Parts Pvt Ltd
-- Owner: Nutech
-- Created At: 2026-08-31
-- Description: Alter BOM process and process materials tables for machine group mapping and alternate materials with priorities

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_NPD_BOM_PROCESS_MACHINE' AND parent_object_id = OBJECT_ID('dbo.NPD_BOM_PROCESS'))
BEGIN
    ALTER TABLE dbo.NPD_BOM_PROCESS DROP CONSTRAINT FK_NPD_BOM_PROCESS_MACHINE;
END

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.NPD_BOM_PROCESS') AND name = 'PRIMARY_MACHINE_ID')
BEGIN
    ALTER TABLE dbo.NPD_BOM_PROCESS DROP COLUMN PRIMARY_MACHINE_ID;
END

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.NPD_BOM_PROCESS') AND name = 'LOCATION')
BEGIN
    ALTER TABLE dbo.NPD_BOM_PROCESS DROP COLUMN LOCATION;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.NPD_BOM_PROCESS') AND name = 'MACHINE_GROUP_ID')
BEGIN
    ALTER TABLE dbo.NPD_BOM_PROCESS ADD MACHINE_GROUP_ID BIGINT NULL;
    
    ALTER TABLE dbo.NPD_BOM_PROCESS 
    ADD CONSTRAINT FK_NPD_BOM_PROCESS_MACHINE_GROUP 
    FOREIGN KEY (MACHINE_GROUP_ID) REFERENCES dbo.ASSET_GROUP(ID);
END

-- Alter NPD_BOM_PROCESS_MATERIAL for Alternates & Priorities
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.NPD_BOM_PROCESS_MATERIAL') AND name = 'IS_ALTERNATE')
BEGIN
    ALTER TABLE dbo.NPD_BOM_PROCESS_MATERIAL ADD IS_ALTERNATE BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.NPD_BOM_PROCESS_MATERIAL') AND name = 'PRIMARY_ITEM_NO')
BEGIN
    ALTER TABLE dbo.NPD_BOM_PROCESS_MATERIAL ADD PRIMARY_ITEM_NO NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.NPD_BOM_PROCESS_MATERIAL') AND name = 'ALT_PRIORITY')
BEGIN
    ALTER TABLE dbo.NPD_BOM_PROCESS_MATERIAL ADD ALT_PRIORITY INT NULL;
END
