-- =============================================================================
-- V388.0: Create QMS_SCHEDULE_MEETING_CONFIG Table
-- =============================================================================

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QMS_SCHEDULE_MEETING_CONFIG]') AND type in (N'U'))
BEGIN
    CREATE TABLE QMS_SCHEDULE_MEETING_CONFIG (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        MEETING_ID BIGINT NOT NULL,
        MEETING_TYPE_ID BIGINT NOT NULL,
        MEETING_START_DATE DATETIME NOT NULL,
        START_TIME DATETIME NOT NULL,
        END_TIME DATETIME NOT NULL,
        INTERVAL_TIME DATETIME NOT NULL,
        FREQUECY NVARCHAR(50) NOT NULL,
        STATUS BIT NULL DEFAULT 0,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME,

        CONSTRAINT PK_QMS_SCHEDULE_MEETING_CONFIG PRIMARY KEY (ID),
        CONSTRAINT FK_QMS_SCHEDULE_MEETING_CONFIG_CB FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_QMS_SCHEDULE_MEETING_CONFIG_UB FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
GO
