-- Insert Checklist Dynamic trigger configuration if it does not exist
-- Created: 2026-08-07

IF NOT EXISTS (SELECT 1 FROM [dbo].[SCHEDULE_CONFIGURATION] WHERE [SCHEDULAR_NAME] = 'CHECKLIST_DYNAMIC')
BEGIN
    INSERT INTO [dbo].[SCHEDULE_CONFIGURATION] ([SCHEDULAR_NAME], [SCHEDULAR_TIME], [STATUS], [CREATED_BY], [CREATED_DATE], [ACTIVE_STATUS])
    VALUES ('CHECKLIST_DYNAMIC', '2024-01-01 04:00:00', 1, 'SYSTEM', GETDATE(), 'Active');
END
GO
