-- Idempotent DDL script to add health insurance columns to HR_EMPLOYEE_SELF_ASSESSMENT
IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') 
    AND name = 'Q47_HAS_INSURANCE'
)
BEGIN
    ALTER TABLE HR_EMPLOYEE_SELF_ASSESSMENT ADD Q47_HAS_INSURANCE NVARCHAR(10) NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') 
    AND name = 'Q48_INSURANCE_NUMBER'
)
BEGIN
    ALTER TABLE HR_EMPLOYEE_SELF_ASSESSMENT ADD Q48_INSURANCE_NUMBER NVARCHAR(100) NULL;
END;
