-- Create HR_APPLICANT_PORTAL_TOKEN table for database-backed portal link lifecycle management
IF OBJECT_ID('dbo.HR_APPLICANT_PORTAL_TOKEN', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.HR_APPLICANT_PORTAL_TOKEN (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        EMPLOYEE_ID BIGINT NOT NULL,
        PORTAL_TYPE VARCHAR(50) NOT NULL,
        TOKEN VARCHAR(1000) NOT NULL,
        EXPIRY_DATE DATETIME NOT NULL,
        IS_ACTIVE BIT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_HR_APPLICANT_PORTAL_TOKEN_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES dbo.HR_EMPLOYEE(ID),
        CONSTRAINT FK_HR_APPLICANT_PORTAL_TOKEN_CREATED FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_HR_APPLICANT_PORTAL_TOKEN_UPDATED FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_HR_APPLICANT_PORTAL_TOKEN_TOKEN ON dbo.HR_APPLICANT_PORTAL_TOKEN(TOKEN);
    CREATE INDEX IX_HR_APPLICANT_PORTAL_TOKEN_EMP ON dbo.HR_APPLICANT_PORTAL_TOKEN(EMPLOYEE_ID, PORTAL_TYPE);
END
