-- Create HR_EMPLOYEE_BIRTHDAY_LOG table if it does not exist
IF OBJECT_ID('dbo.HR_EMPLOYEE_BIRTHDAY_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.HR_EMPLOYEE_BIRTHDAY_LOG (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        EMPLOYEE_ID BIGINT NOT NULL,
        BIRTHDAY_YEAR INT NOT NULL,
        POPUP_SHOWN BIT NOT NULL DEFAULT 1,
        SHOWN_DATE DATETIME NOT NULL DEFAULT GETDATE(),
        LOGIN_SESSION VARCHAR(100) NULL,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_BIRTHDAY_LOG_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES dbo.HR_EMPLOYEE(ID),
        CONSTRAINT FK_BIRTHDAY_LOG_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_BIRTHDAY_LOG_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    PRINT 'Created HR_EMPLOYEE_BIRTHDAY_LOG table successfully.';
END
ELSE
BEGIN
    PRINT 'HR_EMPLOYEE_BIRTHDAY_LOG table already exists.';
END
