-- Migration Script to add CGST, SGST, IGST columns to Quotation Details and remove old TAX_PERCENT column

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'CGST_PERCENT' AND Object_ID = Object_ID(N'PP_QUOTATION_DETAIL'))
BEGIN
    ALTER TABLE PP_QUOTATION_DETAIL
    ADD 
        CGST_PERCENT DECIMAL(5,2) DEFAULT 0 NOT NULL,
        SGST_PERCENT DECIMAL(5,2) DEFAULT 0 NOT NULL,
        IGST_PERCENT DECIMAL(5,2) DEFAULT 0 NOT NULL,
        CGST_AMOUNT DECIMAL(12,4) DEFAULT 0 NOT NULL,
        SGST_AMOUNT DECIMAL(12,4) DEFAULT 0 NOT NULL,
        IGST_AMOUNT DECIMAL(12,4) DEFAULT 0 NOT NULL;
END
GO

-- We can drop TAX_PERCENT as per the new rule
IF EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'TAX_PERCENT' AND Object_ID = Object_ID(N'PP_QUOTATION_DETAIL'))
BEGIN
    ALTER TABLE PP_QUOTATION_DETAIL
    DROP CONSTRAINT IF EXISTS DF_PP_QUOTATION_DETAIL_TAX_PERCENT;
    ALTER TABLE PP_QUOTATION_DETAIL
    DROP COLUMN TAX_PERCENT;
END
GO
