-- ============================================================
-- Migration: 20260720_V1024.0__Seed_Checklist_Status_Values.sql
-- Purpose  : Seed all checklist-specific status values into
--            AD_STATUS_MASTER so they exist from first boot
--            and are never created on-demand during transactions.
-- Idempotent: YES — uses IF NOT EXISTS guard on each insert.
-- ============================================================

-- Core record statuses
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'ACTIVE')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('ACTIVE');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'INACTIVE')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('INACTIVE');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PENDING')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('PENDING');

-- Verification statuses
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'TO BE VERIFIED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('TO BE VERIFIED');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'VERIFIED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('VERIFIED');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'REJECTED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('REJECTED');

-- Assignment statuses
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'UN ASSIGNED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('UN ASSIGNED');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'ASSIGNED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('ASSIGNED');

-- Checklist execution statuses (CHECK LIST category)
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'COMPLETED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('COMPLETED');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'NOT COMPLETED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('NOT COMPLETED');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'UNRESOLVED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('UNRESOLVED');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'MISSED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('MISSED');

-- Checklist execution progress statuses (RENEWAL category)
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'STARTED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('STARTED');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = '25%')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('25%');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = '50%')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('50%');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = '75%')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('75%');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'ATTENDED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('ATTENDED');

-- Verification pipeline statuses
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PENDING FOR VERIFY')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('PENDING FOR VERIFY');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PENDING FOR ACCEPTED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('PENDING FOR ACCEPTED');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'ACCEPTED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('ACCEPTED');

-- Renewal lifecycle statuses
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'RENEWAL PENDING')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('RENEWAL PENDING');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'RENEWAL VERIFIED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('RENEWAL VERIFIED');

-- Terminal / closed status (distinct from INACTIVE)
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'CLOSED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('CLOSED');

-- Misc
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'N/A')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('N/A');
