CREATE TABLE PP_PURCHASE_ORDER_ADD_CHARGES (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    PO_ID BIGINT NOT NULL,
    CHARGE_ID BIGINT NOT NULL,
    AMOUNT DECIMAL(18,4) NOT NULL DEFAULT 0,
    TAX_APPLICABLE BIT NOT NULL DEFAULT 0,
    CGST_PER DECIMAL(18,2) DEFAULT 0,
    CGST_VALUE DECIMAL(18,2) DEFAULT 0,
    SGST_PER DECIMAL(18,2) DEFAULT 0,
    SGST_VALUE DECIMAL(18,2) DEFAULT 0,
    IGST_PER DECIMAL(18,2) DEFAULT 0,
    IGST_VALUE DECIMAL(18,2) DEFAULT 0,
    TOTAL_VALUE DECIMAL(18,4) NOT NULL DEFAULT 0,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    ACTIVE_STATUS INT DEFAULT 1,
    CONSTRAINT FK_PP_PO_CHARGE_PO FOREIGN KEY (PO_ID) REFERENCES PP_PURCHASE_ORDER_HEAD(ID),
    CONSTRAINT FK_PP_PO_CHARGE_MASTER FOREIGN KEY (CHARGE_ID) REFERENCES SM_ADDITIONAL_CHARGES(ID)
);

CREATE INDEX IX_PP_PO_CHARGE_PO_ID ON PP_PURCHASE_ORDER_ADD_CHARGES(PO_ID);
