-- Database Migration: V1075.0__Alter_Verification_Criteria_Description_Length.sql
-- Alter description column in HR_VERIFICATION_CRITERIA to NVARCHAR(MAX) to remove 2000 character limit.

SET NOCOUNT ON;

IF EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'HR_VERIFICATION_CRITERIA' 
      AND COLUMN_NAME = 'DESCRIPTION' 
      AND (CHARACTER_MAXIMUM_LENGTH < -1 OR CHARACTER_MAXIMUM_LENGTH != -1)
)
BEGIN
    ALTER TABLE [dbo].[HR_VERIFICATION_CRITERIA] ALTER COLUMN [DESCRIPTION] NVARCHAR(MAX) NOT NULL;
END
GO