-- Rename Q41_REP_MGR_NAME to Q41_HR_MGR_NAME if Q41_REP_MGR_NAME exists and Q41_HR_MGR_NAME does not
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q41_REP_MGR_NAME')
   AND NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q41_HR_MGR_NAME')
BEGIN
    EXEC sp_rename 'HR_EMPLOYEE_SELF_ASSESSMENT.Q41_REP_MGR_NAME', 'Q41_HR_MGR_NAME', 'COLUMN';
END
GO

-- Rename Q42_REP_MGR_EMAIL to Q42_HR_MGR_EMAIL if Q42_REP_MGR_EMAIL exists and Q42_HR_MGR_EMAIL does not
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q42_REP_MGR_EMAIL')
   AND NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q42_HR_MGR_EMAIL')
BEGIN
    EXEC sp_rename 'HR_EMPLOYEE_SELF_ASSESSMENT.Q42_REP_MGR_EMAIL', 'Q42_HR_MGR_EMAIL', 'COLUMN';
END
GO

-- Rename Q43_REP_MGR_PHONE to Q43_HR_MGR_PHONE if Q43_REP_MGR_PHONE exists and Q43_HR_MGR_PHONE does not
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q43_REP_MGR_PHONE')
   AND NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q43_HR_MGR_PHONE')
BEGIN
    EXEC sp_rename 'HR_EMPLOYEE_SELF_ASSESSMENT.Q43_REP_MGR_PHONE', 'Q43_HR_MGR_PHONE', 'COLUMN';
END
GO

-- Add them as new columns if they still do not exist after rename attempts
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q41_HR_MGR_NAME')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q41_HR_MGR_NAME] NVARCHAR(255) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q42_HR_MGR_EMAIL')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q42_HR_MGR_EMAIL] NVARCHAR(255) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q43_HR_MGR_PHONE')
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_SELF_ASSESSMENT] ADD [Q43_HR_MGR_PHONE] NVARCHAR(50) NULL;
END
GO
