-- ============================================================================
-- DB Script: 20260905_V1228.0__Remove_Client_Code_And_Link_FK_Company_Credential.sql
-- Module: Platform / Identity / Client Management
-- Description: 
--   1. Drops CLIENT_CODE from CLI_CLIENT_SERVER_CONFIG, CLI_CLIENT_DATABASE_CONFIG,
--      CLI_CLIENT_LICENSE, and CLI_CLIENT_HEALTH_LOG.
--   2. Links CLIENT_ID as Foreign Key referencing AD_COMPANY_CREDENTIAL(id).
--   3. Updates indexes accordingly.
-- ============================================================================

-- 1. CLI_CLIENT_SERVER_CONFIG
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'CLI_CLIENT_SERVER_CONFIG')
BEGIN
    -- Drop old index on CLIENT_CODE if exists
    IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_CLI_SERVER_CLIENT_CODE' AND object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG'))
    BEGIN
        DROP INDEX IDX_CLI_SERVER_CLIENT_CODE ON CLI_CLIENT_SERVER_CONFIG;
    END

    -- Drop old foreign key constraint referencing CLI_CLIENT_MASTER if exists
    IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_CLI_SERVER_CLIENT_ID' AND parent_object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG'))
    BEGIN
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG DROP CONSTRAINT FK_CLI_SERVER_CLIENT_ID;
    END

    -- Add new foreign key referencing AD_COMPANY_CREDENTIAL(id)
    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_CLI_SERVER_COMPANY' AND parent_object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG'))
    BEGIN
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG 
        ADD CONSTRAINT FK_CLI_SERVER_COMPANY FOREIGN KEY (CLIENT_ID) REFERENCES AD_COMPANY_CREDENTIAL(id);
    END

    -- Drop CLIENT_CODE column if exists
    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'CLIENT_CODE')
    BEGIN
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG DROP COLUMN CLIENT_CODE;
    END
END
GO

-- 2. CLI_CLIENT_DATABASE_CONFIG
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'CLI_CLIENT_DATABASE_CONFIG')
BEGIN
    -- Drop old index on CLIENT_CODE if exists
    IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_CLI_DB_CLIENT_CODE' AND object_id = OBJECT_ID('CLI_CLIENT_DATABASE_CONFIG'))
    BEGIN
        DROP INDEX IDX_CLI_DB_CLIENT_CODE ON CLI_CLIENT_DATABASE_CONFIG;
    END

    -- Drop old foreign key constraint referencing CLI_CLIENT_MASTER if exists
    IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_CLI_DB_CLIENT_ID' AND parent_object_id = OBJECT_ID('CLI_CLIENT_DATABASE_CONFIG'))
    BEGIN
        ALTER TABLE CLI_CLIENT_DATABASE_CONFIG DROP CONSTRAINT FK_CLI_DB_CLIENT_ID;
    END

    -- Add new foreign key referencing AD_COMPANY_CREDENTIAL(id)
    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_CLI_DB_COMPANY' AND parent_object_id = OBJECT_ID('CLI_CLIENT_DATABASE_CONFIG'))
    BEGIN
        ALTER TABLE CLI_CLIENT_DATABASE_CONFIG 
        ADD CONSTRAINT FK_CLI_DB_COMPANY FOREIGN KEY (CLIENT_ID) REFERENCES AD_COMPANY_CREDENTIAL(id);
    END

    -- Drop CLIENT_CODE column if exists
    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_DATABASE_CONFIG') AND name = 'CLIENT_CODE')
    BEGIN
        ALTER TABLE CLI_CLIENT_DATABASE_CONFIG DROP COLUMN CLIENT_CODE;
    END
END
GO

-- 3. CLI_CLIENT_LICENSE
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'CLI_CLIENT_LICENSE')
BEGIN
    -- Drop old index on CLIENT_CODE if exists
    IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_CLI_LICENSE_CODE' AND object_id = OBJECT_ID('CLI_CLIENT_LICENSE'))
    BEGIN
        DROP INDEX IDX_CLI_LICENSE_CODE ON CLI_CLIENT_LICENSE;
    END

    -- Drop old foreign key constraint referencing CLI_CLIENT_MASTER if exists
    IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_CLI_LICENSE_CLIENT' AND parent_object_id = OBJECT_ID('CLI_CLIENT_LICENSE'))
    BEGIN
        ALTER TABLE CLI_CLIENT_LICENSE DROP CONSTRAINT FK_CLI_LICENSE_CLIENT;
    END

    IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_CLI_LICENSE_CLIENT_ID' AND parent_object_id = OBJECT_ID('CLI_CLIENT_LICENSE'))
    BEGIN
        ALTER TABLE CLI_CLIENT_LICENSE DROP CONSTRAINT FK_CLI_LICENSE_CLIENT_ID;
    END

    -- Add new foreign key referencing AD_COMPANY_CREDENTIAL(id)
    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_CLI_LICENSE_COMPANY' AND parent_object_id = OBJECT_ID('CLI_CLIENT_LICENSE'))
    BEGIN
        ALTER TABLE CLI_CLIENT_LICENSE 
        ADD CONSTRAINT FK_CLI_LICENSE_COMPANY FOREIGN KEY (CLIENT_ID) REFERENCES AD_COMPANY_CREDENTIAL(id);
    END

    -- Drop CLIENT_CODE column if exists
    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_LICENSE') AND name = 'CLIENT_CODE')
    BEGIN
        ALTER TABLE CLI_CLIENT_LICENSE DROP COLUMN CLIENT_CODE;
    END
END
GO

-- 4. CLI_CLIENT_HEALTH_LOG
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'CLI_CLIENT_HEALTH_LOG')
BEGIN
    -- Drop old index on CLIENT_CODE if exists
    IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_CLI_HEALTH_CLIENT_CODE' AND object_id = OBJECT_ID('CLI_CLIENT_HEALTH_LOG'))
    BEGIN
        DROP INDEX IDX_CLI_HEALTH_CLIENT_CODE ON CLI_CLIENT_HEALTH_LOG;
    END

    -- Add CLIENT_ID column if it does not exist
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_HEALTH_LOG') AND name = 'CLIENT_ID')
    BEGIN
        ALTER TABLE CLI_CLIENT_HEALTH_LOG ADD CLIENT_ID BIGINT NULL;
        
        -- Populate CLIENT_ID with default company ID from AD_COMPANY_CREDENTIAL
        UPDATE CLI_CLIENT_HEALTH_LOG 
        SET CLIENT_ID = ISNULL((SELECT TOP 1 id FROM AD_COMPANY_CREDENTIAL ORDER BY id ASC), 1)
        WHERE CLIENT_ID IS NULL;

        ALTER TABLE CLI_CLIENT_HEALTH_LOG ALTER COLUMN CLIENT_ID BIGINT NOT NULL;
    END

    -- Add index on CLIENT_ID if not exists
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_CLI_HEALTH_CLIENT_ID' AND object_id = OBJECT_ID('CLI_CLIENT_HEALTH_LOG'))
    BEGIN
        CREATE INDEX IDX_CLI_HEALTH_CLIENT_ID ON CLI_CLIENT_HEALTH_LOG(CLIENT_ID);
    END

    -- Add foreign key referencing AD_COMPANY_CREDENTIAL(id)
    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_CLI_HEALTH_COMPANY' AND parent_object_id = OBJECT_ID('CLI_CLIENT_HEALTH_LOG'))
    BEGIN
        ALTER TABLE CLI_CLIENT_HEALTH_LOG 
        ADD CONSTRAINT FK_CLI_HEALTH_COMPANY FOREIGN KEY (CLIENT_ID) REFERENCES AD_COMPANY_CREDENTIAL(id);
    END

    -- Drop CLIENT_CODE column if exists
    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_HEALTH_LOG') AND name = 'CLIENT_CODE')
    BEGIN
        ALTER TABLE CLI_CLIENT_HEALTH_LOG DROP COLUMN CLIENT_CODE;
    END
END
GO
