-- Organization: Nutech Wind Parts Pvt Ltd
-- Owner: Nutech
-- Created At: 2026-09-01
-- Description: Align BOM Process, Machine, and Tool tables structure with complete column schema

-- 1. NPD_BOM_PROCESS: Ensure SETUP_TIME and CYCLE_TIME exist
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NPD_BOM_PROCESS')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'SETUP_TIME' AND object_id = OBJECT_ID('NPD_BOM_PROCESS'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS ADD SETUP_TIME DECIMAL(10,2) DEFAULT 0.00 NOT NULL;
        PRINT 'Added SETUP_TIME column to NPD_BOM_PROCESS.';
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'CYCLE_TIME' AND object_id = OBJECT_ID('NPD_BOM_PROCESS'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS ADD CYCLE_TIME DECIMAL(10,2) DEFAULT 0.00 NOT NULL;
        PRINT 'Added CYCLE_TIME column to NPD_BOM_PROCESS.';
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'NORMS_PER_HRS' AND object_id = OBJECT_ID('NPD_BOM_PROCESS'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS ADD NORMS_PER_HRS DECIMAL(15,4) NULL;
        PRINT 'Added NORMS_PER_HRS column to NPD_BOM_PROCESS.';
    END
END;
GO

-- 2. NPD_BOM_PROCESS_MACHINE: Ensure SEQ_NO exists
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NPD_BOM_PROCESS_MACHINE')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'SEQ_NO' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_MACHINE'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_MACHINE ADD SEQ_NO INT NULL;
        PRINT 'Added SEQ_NO column to NPD_BOM_PROCESS_MACHINE.';
    END
END;
GO

-- 3. NPD_BOM_PROCESS_TOOL: Ensure PRODUCT_ID, DIVISION, USAGE_LIMIT exist
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NPD_BOM_PROCESS_TOOL')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'PRODUCT_ID' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_TOOL'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_TOOL ADD PRODUCT_ID BIGINT NULL;
        ALTER TABLE dbo.NPD_BOM_PROCESS_TOOL ADD CONSTRAINT FK_NPD_BOM_TOOL_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.NPD_PRODUCT_MASTER(ID);
        PRINT 'Added PRODUCT_ID column and FK to NPD_BOM_PROCESS_TOOL.';
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'DIVISION' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_TOOL'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_TOOL ADD DIVISION INT NULL;
        PRINT 'Added DIVISION column to NPD_BOM_PROCESS_TOOL.';
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE name = 'USAGE_LIMIT' AND object_id = OBJECT_ID('NPD_BOM_PROCESS_TOOL'))
    BEGIN
        ALTER TABLE dbo.NPD_BOM_PROCESS_TOOL ADD USAGE_LIMIT INT NULL;
        PRINT 'Added USAGE_LIMIT column to NPD_BOM_PROCESS_TOOL.';
    END
END;
GO
