-- Organization: Autonoma ERP
-- Created At: 2026-08-29
-- Description: Add High-Performance Covering Indexes for QMS Audit Schedule vs Actual Reports

IF OBJECT_ID('dbo.QMS_AUDIT_SCHEDULE', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_AUDIT_SCHEDULE') AND name = 'IX_QMS_AUDIT_SCHED_STATUS_DATE_PERF')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_AUDIT_SCHED_STATUS_DATE_PERF
    ON [dbo].[QMS_AUDIT_SCHEDULE] ([IS_ACTIVE], [STATUS], [AUDIT_DATE])
    INCLUDE ([SCHEDULE_NO], [AUDIT_TYPE_ID], [DEPARTMENT_ID], [AUDITOR_ID], [AUDITEE_ID]);
    PRINT 'Created IX_QMS_AUDIT_SCHED_STATUS_DATE_PERF index on QMS_AUDIT_SCHEDULE';
END;

IF OBJECT_ID('dbo.QMS_AUDIT_OBSERVATION', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_AUDIT_OBSERVATION') AND name = 'IX_QMS_AUDIT_OBS_SCHED_NO_PERF')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_AUDIT_OBS_SCHED_NO_PERF
    ON [dbo].[QMS_AUDIT_OBSERVATION] ([AUDIT_SCHEDULE_NO])
    INCLUDE ([OBSERVATION_NO], [OBSERVATION_DATE], [AUDIT_SCORE], [COMPLIANCE_COUNT], [NCR_COUNT], [OFI_COUNT], [STATUS]);
    PRINT 'Created IX_QMS_AUDIT_OBS_SCHED_NO_PERF index on QMS_AUDIT_OBSERVATION';
END;
