-- Idempotent Migration: Alter QMS_CHECKLIST_MASTER status columns to BIGINT to match AD_STATUS_MASTER(ID)

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_QMS_CHECKLIST_MASTER_STATUS_VERIFY')
BEGIN
    DROP INDEX IX_QMS_CHECKLIST_MASTER_STATUS_VERIFY ON QMS_CHECKLIST_MASTER;
END
GO

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_QMS_CHECKLIST_MASTER_VERIFY_STATUS')
BEGIN
    DROP INDEX IX_QMS_CHECKLIST_MASTER_VERIFY_STATUS ON QMS_CHECKLIST_MASTER;
END
GO

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'QMS_CHECKLIST_MASTER' 
      AND COLUMN_NAME = 'STATUS' 
      AND DATA_TYPE = 'int'
)
BEGIN
    ALTER TABLE QMS_CHECKLIST_MASTER ALTER COLUMN STATUS BIGINT NULL;
END
GO

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'QMS_CHECKLIST_MASTER' 
      AND COLUMN_NAME = 'TASK_STATUS' 
      AND DATA_TYPE = 'int'
)
BEGIN
    ALTER TABLE QMS_CHECKLIST_MASTER ALTER COLUMN TASK_STATUS BIGINT NULL;
END
GO

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'QMS_CHECKLIST_MASTER' 
      AND COLUMN_NAME = 'VERIFY_STATUS' 
      AND DATA_TYPE = 'int'
)
BEGIN
    ALTER TABLE QMS_CHECKLIST_MASTER ALTER COLUMN VERIFY_STATUS BIGINT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_QMS_CHECKLIST_MASTER_STATUS_VERIFY')
BEGIN
    CREATE INDEX IX_QMS_CHECKLIST_MASTER_STATUS_VERIFY ON QMS_CHECKLIST_MASTER (STATUS, VERIFY_STATUS);
END
GO
