-- V1034.0: Recreate legacy tables as views for compatibility and query safety

-- 1. Create HR_LEAVE_REQUEST view mapping to HR_LEAVE_DETAILS
IF OBJECT_ID('HR_LEAVE_REQUEST', 'V') IS NOT NULL
    DROP VIEW HR_LEAVE_REQUEST;
GO
CREATE VIEW HR_LEAVE_REQUEST AS
SELECT 
    ID AS LEAVE_REQUEST_ID,
    CAST('LR/' + CAST(ID AS VARCHAR(20)) AS NVARCHAR(50)) AS REQUEST_NO,
    EMPLOYEE_ID AS EMP_ID,
    (SELECT TOP 1 EMP_CODE FROM HR_EMPLOYEE WHERE ID = EMPLOYEE_ID) AS EMP_CODE,
    (SELECT TOP 1 EMPLOYEE_NAME FROM HR_EMPLOYEE WHERE ID = EMPLOYEE_ID) AS EMP_NAME,
    CAST(NULL AS BIGINT) AS DEPARTMENT_ID,
    CAST(1 AS BIGINT) AS LEAVE_TYPE_ID,
    LEAVE_TYPE AS LEAVE_TYPE_NAME,
    CAST(NULL AS BIGINT) AS HOLIDAY_ID,
    FROM_DATE AS START_DATE,
    TO_DATE AS END_DATE,
    CAST(NO_OF_DAYS AS FLOAT) AS NUMBER_OF_DAYS,
    REASON AS REASON,
    CASE 
        WHEN STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Rejected') THEN 'REJECTED'
        WHEN STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Verified') THEN 'APPROVED'
        ELSE 'PENDING'
    END AS STATUS,
    CREATED_DATE AS REQUEST_DATE,
    CREATED_DATE AS SUBMITTED_DATE,
    CAST(NULL AS BIGINT) AS MANAGER_ID,
    CAST(NULL AS NVARCHAR(200)) AS MANAGER_NAME,
    CAST(NULL AS NVARCHAR(MAX)) AS MANAGER_REMARKS,
    CAST(NULL AS DATETIME) AS MANAGER_ACTION_DATE,
    CAST(NULL AS BIGINT) AS HR_ID,
    CAST(NULL AS NVARCHAR(200)) AS HR_NAME,
    CAST(NULL AS NVARCHAR(MAX)) AS HR_REMARKS,
    CAST(NULL AS DATETIME) AS HR_ACTION_DATE,
    REJECT_REASON AS REJECTION_REASON,
    VERIFIED_BY AS APPROVED_BY,
    VERIFIED_DATE AS APPROVED_DATE,
    VERIFIED_BY AS REJECTED_BY,
    VERIFIED_DATE AS REJECTED_DATE,
    CAST(NULL AS NVARCHAR(MAX)) AS APPROVAL_REMARKS,
    CAST(0 AS BIT) AS ATTENDANCE_MARKED,
    CREATED_BY AS CREATED_BY,
    CREATED_DATE AS CREATED_DATE,
    CAST(NULL AS NVARCHAR(50)) AS UPDATED_BY,
    CAST(NULL AS DATETIME) AS UPDATED_DATE
FROM HR_LEAVE_DETAILS;
GO

-- 2. Create HR_LEAVE_TYPE view
IF OBJECT_ID('HR_LEAVE_TYPE', 'V') IS NOT NULL
    DROP VIEW HR_LEAVE_TYPE;
GO
CREATE VIEW HR_LEAVE_TYPE AS
SELECT 1 AS LEAVE_TYPE_ID, 'EL' AS LEAVE_CODE, 'Earned Leave' AS LEAVE_NAME, 'Earned Leave' AS DESCRIPTION, CAST(1 AS BIT) AS IS_ACTIVE, 'SYSTEM' AS CREATED_BY, GETDATE() AS CREATED_DATE, NULL AS UPDATED_BY, NULL AS UPDATED_DATE
UNION ALL
SELECT 2 AS LEAVE_TYPE_ID, 'CL' AS LEAVE_CODE, 'Casual Leave' AS LEAVE_NAME, 'Casual Leave' AS DESCRIPTION, CAST(1 AS BIT) AS IS_ACTIVE, 'SYSTEM' AS CREATED_BY, GETDATE() AS CREATED_DATE, NULL AS UPDATED_BY, NULL AS UPDATED_DATE
UNION ALL
SELECT 3 AS LEAVE_TYPE_ID, 'SL' AS LEAVE_CODE, 'Sick Leave' AS LEAVE_NAME, 'Sick Leave' AS DESCRIPTION, CAST(1 AS BIT) AS IS_ACTIVE, 'SYSTEM' AS CREATED_BY, GETDATE() AS CREATED_DATE, NULL AS UPDATED_BY, NULL AS UPDATED_DATE
UNION ALL
SELECT 4 AS LEAVE_TYPE_ID, 'AL' AS LEAVE_CODE, 'Alternative Leave' AS LEAVE_NAME, 'Alternative Leave' AS DESCRIPTION, CAST(1 AS BIT) AS IS_ACTIVE, 'SYSTEM' AS CREATED_BY, GETDATE() AS CREATED_DATE, NULL AS UPDATED_BY, NULL AS UPDATED_DATE
UNION ALL
SELECT 5 AS LEAVE_TYPE_ID, 'PL' AS LEAVE_CODE, 'Privilege Leave' AS LEAVE_NAME, 'Privilege Leave' AS DESCRIPTION, CAST(1 AS BIT) AS IS_ACTIVE, 'SYSTEM' AS CREATED_BY, GETDATE() AS CREATED_DATE, NULL AS UPDATED_BY, NULL AS UPDATED_DATE
UNION ALL
SELECT 6 AS LEAVE_TYPE_ID, 'LOP' AS LEAVE_CODE, 'Loss of Pay' AS LEAVE_NAME, 'Loss of Pay' AS DESCRIPTION, CAST(1 AS BIT) AS IS_ACTIVE, 'SYSTEM' AS CREATED_BY, GETDATE() AS CREATED_DATE, NULL AS UPDATED_BY, NULL AS UPDATED_DATE
UNION ALL
SELECT 7 AS LEAVE_TYPE_ID, 'WFH' AS LEAVE_CODE, 'Work From Home' AS LEAVE_NAME, 'Work From Home' AS DESCRIPTION, CAST(1 AS BIT) AS IS_ACTIVE, 'SYSTEM' AS CREATED_BY, GETDATE() AS CREATED_DATE, NULL AS UPDATED_BY, NULL AS UPDATED_DATE;
GO
