-- =============================================================================
-- Fix: Migrate HR_APPLICANT_INTERVIEW INTERVIEW_STATUS and INTERVIEW_RESULT
-- from NVARCHAR to BIGINT FK referencing AD_STATUS_MASTER
-- Values: PENDING, REJECTED, SELECTED, PASS, FAIL
-- =============================================================================
SET NOCOUNT ON;

-- Ensure all required statuses exist
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME))='PASS') INSERT INTO AD_STATUS_MASTER(NAME) VALUES('PASS');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME))='FAIL') INSERT INTO AD_STATUS_MASTER(NAME) VALUES('FAIL');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME))='PENDING') INSERT INTO AD_STATUS_MASTER(NAME) VALUES('PENDING');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME))='SELECTED') INSERT INTO AD_STATUS_MASTER(NAME) VALUES('SELECTED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME))='REJECTED') INSERT INTO AD_STATUS_MASTER(NAME) VALUES('REJECTED');
GO

-- ---- INTERVIEW_STATUS ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_APPLICANT_INTERVIEW' AND COLUMN_NAME='INTERVIEW_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_APPLICANT_INTERVIEW' AND COLUMN_NAME='INTERVIEW_STATUS_ID')
        EXEC('ALTER TABLE HR_APPLICANT_INTERVIEW ADD INTERVIEW_STATUS_ID BIGINT NULL');
    EXEC('UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(INTERVIEW_STATUS))) WHERE INTERVIEW_STATUS IS NOT NULL');
    DECLARE @sql NVARCHAR(512); DECLARE @nm NVARCHAR(256);
    DECLARE ix CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_APPLICANT_INTERVIEW') AND c.name='INTERVIEW_STATUS' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix; FETCH NEXT FROM ix INTO @nm; WHILE @@FETCH_STATUS=0 BEGIN SET @sql='DROP INDEX '+QUOTENAME(@nm)+' ON HR_APPLICANT_INTERVIEW'; EXEC(@sql); FETCH NEXT FROM ix INTO @nm; END CLOSE ix; DEALLOCATE ix;
    DECLARE dc CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_APPLICANT_INTERVIEW') AND c.name='INTERVIEW_STATUS';
    OPEN dc; FETCH NEXT FROM dc INTO @nm; WHILE @@FETCH_STATUS=0 BEGIN SET @sql='ALTER TABLE HR_APPLICANT_INTERVIEW DROP CONSTRAINT '+QUOTENAME(@nm); EXEC(@sql); FETCH NEXT FROM dc INTO @nm; END CLOSE dc; DEALLOCATE dc;
    EXEC('ALTER TABLE HR_APPLICANT_INTERVIEW DROP COLUMN INTERVIEW_STATUS');
    EXEC('EXEC sp_rename ''HR_APPLICANT_INTERVIEW.INTERVIEW_STATUS_ID'', ''INTERVIEW_STATUS'', ''COLUMN''');
    PRINT 'Migrated HR_APPLICANT_INTERVIEW.INTERVIEW_STATUS';
END

GO

-- ---- INTERVIEW_RESULT ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_APPLICANT_INTERVIEW' AND COLUMN_NAME='INTERVIEW_RESULT' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_APPLICANT_INTERVIEW' AND COLUMN_NAME='INTERVIEW_RESULT_ID')
        EXEC('ALTER TABLE HR_APPLICANT_INTERVIEW ADD INTERVIEW_RESULT_ID BIGINT NULL');
    EXEC('UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_RESULT_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(INTERVIEW_RESULT))) WHERE INTERVIEW_RESULT IS NOT NULL');
    DECLARE @sql2 NVARCHAR(512); DECLARE @nm2 NVARCHAR(256);
    DECLARE ix2 CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_APPLICANT_INTERVIEW') AND c.name='INTERVIEW_RESULT' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix2; FETCH NEXT FROM ix2 INTO @nm2; WHILE @@FETCH_STATUS=0 BEGIN SET @sql2='DROP INDEX '+QUOTENAME(@nm2)+' ON HR_APPLICANT_INTERVIEW'; EXEC(@sql2); FETCH NEXT FROM ix2 INTO @nm2; END CLOSE ix2; DEALLOCATE ix2;
    DECLARE dc2 CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_APPLICANT_INTERVIEW') AND c.name='INTERVIEW_RESULT';
    OPEN dc2; FETCH NEXT FROM dc2 INTO @nm2; WHILE @@FETCH_STATUS=0 BEGIN SET @sql2='ALTER TABLE HR_APPLICANT_INTERVIEW DROP CONSTRAINT '+QUOTENAME(@nm2); EXEC(@sql2); FETCH NEXT FROM dc2 INTO @nm2; END CLOSE dc2; DEALLOCATE dc2;
    EXEC('ALTER TABLE HR_APPLICANT_INTERVIEW DROP COLUMN INTERVIEW_RESULT');
    EXEC('EXEC sp_rename ''HR_APPLICANT_INTERVIEW.INTERVIEW_RESULT_ID'', ''INTERVIEW_RESULT'', ''COLUMN''');
    PRINT 'Migrated HR_APPLICANT_INTERVIEW.INTERVIEW_RESULT';
END

GO
PRINT 'HR_APPLICANT_INTERVIEW migration complete.';
GO
