-- Add OAuth token columns directly to AD_OCR_CONFIG table
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AD_OCR_OAUTH_CREDENTIAL]') AND type in (N'U'))
BEGIN
    DROP TABLE [dbo].[AD_OCR_OAUTH_CREDENTIAL];
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_OCR_CONFIG]') AND name = N'ACCESS_TOKEN')
BEGIN
    ALTER TABLE [dbo].[AD_OCR_CONFIG] ADD [ACCESS_TOKEN] NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_OCR_CONFIG]') AND name = N'REFRESH_TOKEN')
BEGIN
    ALTER TABLE [dbo].[AD_OCR_CONFIG] ADD [REFRESH_TOKEN] NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_OCR_CONFIG]') AND name = N'EXPIRES_AT')
BEGIN
    ALTER TABLE [dbo].[AD_OCR_CONFIG] ADD [EXPIRES_AT] DATETIME NULL;
END
