ALTER TABLE QMS_AUDIT_SCHEDULE DROP COLUMN AUDITEE_TYPE;
ALTER TABLE QMS_AUDIT_SCHEDULE DROP COLUMN AUDITOR_TYPE;
ALTER TABLE QMS_AUDIT_SCHEDULE DROP COLUMN NCR_APPROVED_BY_TYPE;
ALTER TABLE QMS_AUDIT_SCHEDULE DROP COLUMN AUDIT_MONTH;
ALTER TABLE QMS_AUDIT_SCHEDULE DROP COLUMN IS_DELETED;
