IF OBJECT_ID('SM_CUST_ADD_CHARGES', 'U') IS NULL
BEGIN
    CREATE TABLE SM_CUST_ADD_CHARGES (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        ORDER_ID BIGINT NULL,
        CHARGES_ID BIGINT NULL,
        AMOUNT NUMERIC(12,2) NULL,
        TAX_APPLICABLE BIT NULL DEFAULT 0,
        CGST_PER NUMERIC(12,2) NULL,
        CGST_VALUE NUMERIC(12,2) NULL,
        SGST_PER NUMERIC(12,2) NULL,
        SGST_VALUE NUMERIC(12,2) NULL,
        IGST_PER NUMERIC(12,2) NULL,
        IGST_VALUE NUMERIC(12,2) NULL,
        TOTAL_VALUE NUMERIC(12,2) NULL,
        STATUS BIT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_SM_CUST_ADD_CHARGES_ORDER FOREIGN KEY (ORDER_ID) REFERENCES SM_CUSTOMER_ORDER_HEADER(ID),
        CONSTRAINT FK_SM_CUST_ADD_CHARGES_MASTER FOREIGN KEY (CHARGES_ID) REFERENCES SM_ADDITIONAL_CHARGES(ID),
        CONSTRAINT FK_SM_CUST_ADD_CHARGES_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SM_CUST_ADD_CHARGES_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
GO
