-- SQL Migration: Add recruitment columns and filtered unique indexes to HR_EMPLOYEE
-- Stage A: Drop unique constraint / index on EMP_CODE first so it can be made nullable
IF OBJECT_ID('dbo.HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    -- Dynamically find and drop any foreign key constraint referencing UQ_HR_EMPLOYEE_EMP_CODE
    DECLARE @FKName NVARCHAR(255);
    DECLARE @FKParentTable NVARCHAR(255);
    DECLARE FKCursor CURSOR FOR
    SELECT fk.name, OBJECT_NAME(fk.parent_object_id)
    FROM sys.foreign_keys fk
    JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
    JOIN sys.columns c ON fkc.referenced_object_id = c.object_id AND fkc.referenced_column_id = c.column_id
    WHERE fk.referenced_object_id = OBJECT_ID('dbo.HR_EMPLOYEE')
      AND c.name = 'EMP_CODE';

    OPEN FKCursor;
    FETCH NEXT FROM FKCursor INTO @FKName, @FKParentTable;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        DECLARE @DropFK NVARCHAR(MAX) = 'ALTER TABLE dbo.' + @FKParentTable + ' DROP CONSTRAINT ' + @FKName;
        EXEC sp_executesql @DropFK;
        FETCH NEXT FROM FKCursor INTO @FKName, @FKParentTable;
    END;
    CLOSE FKCursor;
    DEALLOCATE FKCursor;

    -- Drop unique constraint UQ_HR_EMPLOYEE_EMP_CODE if exists
    IF EXISTS (SELECT * FROM sys.objects WHERE name = 'UQ_HR_EMPLOYEE_EMP_CODE' AND type = 'UQ')
    BEGIN
        ALTER TABLE dbo.HR_EMPLOYEE DROP CONSTRAINT UQ_HR_EMPLOYEE_EMP_CODE;
    END

    -- Also drop unique index UQ_HR_EMPLOYEE_EMP_CODE if exists
    IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'UQ_HR_EMPLOYEE_EMP_CODE' AND object_id = OBJECT_ID('dbo.HR_EMPLOYEE'))
    BEGIN
        DROP INDEX UQ_HR_EMPLOYEE_EMP_CODE ON dbo.HR_EMPLOYEE;
    END

    -- Also check for standard Hibernate unique keys UK_... on EMP_CODE and drop them dynamically!
    DECLARE @ConstraintName NVARCHAR(255);
    SELECT @ConstraintName = dc.name
    FROM sys.key_constraints dc
    WHERE dc.parent_object_id = OBJECT_ID('dbo.HR_EMPLOYEE')
      AND dc.type = 'UQ'
      AND EXISTS (
          SELECT 1 FROM sys.index_columns ic
          JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
          WHERE ic.object_id = dc.parent_object_id AND ic.index_id = dc.unique_index_id
            AND c.name = 'EMP_CODE'
      );

    IF @ConstraintName IS NOT NULL
    BEGIN
        DECLARE @sql NVARCHAR(MAX) = 'ALTER TABLE dbo.HR_EMPLOYEE DROP CONSTRAINT ' + @ConstraintName;
        EXEC sp_executesql @sql;
    END

    -- Also check if there's any other unique index on EMP_CODE and drop it
    DECLARE @IndexName NVARCHAR(255);
    SELECT @IndexName = i.name
    FROM sys.indexes i
    JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE i.object_id = OBJECT_ID('dbo.HR_EMPLOYEE')
      AND c.name = 'EMP_CODE'
      AND i.is_unique = 1
      AND i.is_primary_key = 0;

    IF @IndexName IS NOT NULL
    BEGIN
        DECLARE @sqlIndex NVARCHAR(MAX) = 'DROP INDEX ' + @IndexName + ' ON dbo.HR_EMPLOYEE';
        EXEC sp_executesql @sqlIndex;
    END
END
GO

-- Stage B: Alter column nullability and add recruitment columns
IF OBJECT_ID('dbo.HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    -- 0. Make EMP_CODE nullable
    ALTER TABLE dbo.HR_EMPLOYEE ALTER COLUMN EMP_CODE NVARCHAR(50) NULL;

    -- 1. FROMWHERE origin tracker
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'FROMWHERE')
        ALTER TABLE dbo.HR_EMPLOYEE ADD FROMWHERE NVARCHAR(50) NULL;

    -- 2. APPLICANT_CODE candidate unique code
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'APPLICANT_CODE')
        ALTER TABLE dbo.HR_EMPLOYEE ADD APPLICANT_CODE NVARCHAR(50) NULL;

    -- 3. POSITION_LOOK_FOR
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'POSITION_LOOK_FOR')
        ALTER TABLE dbo.HR_EMPLOYEE ADD POSITION_LOOK_FOR NVARCHAR(100) NULL;

    -- 4. APPLICANT_DATE
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'APPLICANT_DATE')
        ALTER TABLE dbo.HR_EMPLOYEE ADD APPLICANT_DATE DATE NULL;

    -- 5. CALL_LETTER_DATE
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'CALL_LETTER_DATE')
        ALTER TABLE dbo.HR_EMPLOYEE ADD CALL_LETTER_DATE NVARCHAR(50) NULL;

    -- 6. CALL_LETTER_TIME
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'CALL_LETTER_TIME')
        ALTER TABLE dbo.HR_EMPLOYEE ADD CALL_LETTER_TIME NVARCHAR(50) NULL;

    -- 7. PAYSLIP_PATH
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'PAYSLIP_PATH')
        ALTER TABLE dbo.HR_EMPLOYEE ADD PAYSLIP_PATH NVARCHAR(1000) NULL;

    -- 8. IS_REHIRED
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'IS_REHIRED')
        ALTER TABLE dbo.HR_EMPLOYEE ADD IS_REHIRED NVARCHAR(10) NULL DEFAULT 'NO';

    -- 9. PREVIOUS_EMP_CODE
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'PREVIOUS_EMP_CODE')
        ALTER TABLE dbo.HR_EMPLOYEE ADD PREVIOUS_EMP_CODE NVARCHAR(50) NULL;

    -- 10. ARCHIVED_DATE
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'ARCHIVED_DATE')
        ALTER TABLE dbo.HR_EMPLOYEE ADD ARCHIVED_DATE DATETIME NULL;

    -- 11. Call status ID
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'CALL_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD CALL_STATUS BIGINT NULL;

    -- 12. Interview status ID
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'INTERVIEW_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD INTERVIEW_STATUS BIGINT NULL;

    -- 13. Offer status ID
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'OFFER_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD OFFER_STATUS BIGINT NULL;

    -- 14. Verification status ID
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'VERIFICATION_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD VERIFICATION_STATUS BIGINT NULL;

    -- 15. Background verification status ID
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'BACKGROUND_VERIFICATION_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD BACKGROUND_VERIFICATION_STATUS BIGINT NULL;

    -- 16. ATS overall status ID
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') AND name = 'ATS_OVERALL_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD ATS_OVERALL_STATUS BIGINT NULL;
END
GO

-- Add constraints if not exists
IF OBJECT_ID('dbo.HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_CALL_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_CALL_STATUS FOREIGN KEY (CALL_STATUS) REFERENCES dbo.AD_STATUS_MASTER(ID);

    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_INT_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_INT_STATUS FOREIGN KEY (INTERVIEW_STATUS) REFERENCES dbo.AD_STATUS_MASTER(ID);

    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_OFFER_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_OFFER_STATUS FOREIGN KEY (OFFER_STATUS) REFERENCES dbo.AD_STATUS_MASTER(ID);

    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_VER_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_VER_STATUS FOREIGN KEY (VERIFICATION_STATUS) REFERENCES dbo.AD_STATUS_MASTER(ID);

    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_BG_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_BG_STATUS FOREIGN KEY (BACKGROUND_VERIFICATION_STATUS) REFERENCES dbo.AD_STATUS_MASTER(ID);

    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_ATS_OVERALL_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_OVERALL_STATUS FOREIGN KEY (ATS_OVERALL_STATUS) REFERENCES dbo.AD_STATUS_MASTER(ID);
END
GO

-- Create unique filtered index on EMP_CODE and APPLICANT_CODE
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UQ_HR_EMPLOYEE_EMP_CODE_NONNULL' AND object_id = OBJECT_ID('dbo.HR_EMPLOYEE'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UQ_HR_EMPLOYEE_EMP_CODE_NONNULL
    ON dbo.HR_EMPLOYEE(EMP_CODE)
    WHERE EMP_CODE IS NOT NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UQ_HR_EMPLOYEE_APPLICANT_CODE_NONNULL' AND object_id = OBJECT_ID('dbo.HR_EMPLOYEE'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UQ_HR_EMPLOYEE_APPLICANT_CODE_NONNULL
    ON dbo.HR_EMPLOYEE(APPLICANT_CODE)
    WHERE APPLICANT_CODE IS NOT NULL;
END
GO

-- Stage C: Schema alterations for child tables
-- 1. AGE column in HR_EMPLOYEE_PERSONAL
IF OBJECT_ID('dbo.HR_EMPLOYEE_PERSONAL', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE_PERSONAL') AND name = 'AGE')
        ALTER TABLE dbo.HR_EMPLOYEE_PERSONAL ADD AGE INT NULL;
END
GO

-- 2. Self-assessment columns in HR_EMPLOYEE_SELF_ASSESSMENT
IF OBJECT_ID('dbo.HR_EMPLOYEE_SELF_ASSESSMENT', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'SELF_ASSESSMENT_STATUS')
        ALTER TABLE dbo.HR_EMPLOYEE_SELF_ASSESSMENT ADD SELF_ASSESSMENT_STATUS NVARCHAR(20) NULL DEFAULT 'DRAFT';

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'CURRENT_STEP')
        ALTER TABLE dbo.HR_EMPLOYEE_SELF_ASSESSMENT ADD CURRENT_STEP INT NULL;

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'LAST_DRAFT_SAVED_DATE')
        ALTER TABLE dbo.HR_EMPLOYEE_SELF_ASSESSMENT ADD LAST_DRAFT_SAVED_DATE DATETIME NULL;
END
GO

-- Stage D: FK-safe cleanup of existing ATS test candidate records
-- Purges only non-onrolled candidate records from the tables to prevent orphan rows/violations
IF OBJECT_ID('dbo.HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    -- 1. Portal tokens
    DELETE FROM dbo.HR_APPLICANT_PORTAL_TOKEN WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');

    -- 2. Interview schedules
    DELETE FROM dbo.HR_APPLICANT_INTERVIEW WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');

    -- 3. Verification submissions and responses
    DELETE FROM dbo.APPLICANT_VERIFICATION_RESPONSE WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');
    DELETE FROM dbo.APPLICANT_VERIFICATION_SUBMISSION WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');

    -- 4. Document audits
    DELETE FROM dbo.ATS_REJECTED_DOCUMENT WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');

    -- 5. Child detail tables
    DELETE FROM dbo.HR_EMPLOYEE_PERSONAL WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');
    DELETE FROM dbo.HR_EMPLOYEE_CONTACT WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');
    DELETE FROM dbo.HR_EMPLOYEE_JOB_PROFILE WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');
    DELETE FROM dbo.HR_EMPLOYEE_SELF_ASSESSMENT WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');
    DELETE FROM dbo.HR_EMPLOYEE_ORGANIZATION WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');
    DELETE FROM dbo.HR_EMPLOYEE_SCHEDULING WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');
    DELETE FROM dbo.HR_EMPLOYEE_INDUCTION WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');
    DELETE FROM dbo.HR_EMPLOYEE_OPERATIONS WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');
    DELETE FROM dbo.HR_EMPLOYEE_REFERENCE WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');

    -- 6. ATS Extension table
    DELETE FROM dbo.HR_EMPLOYEE_ATS WHERE EMPLOYEE_ID IN (SELECT ID FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%');

    -- 7. Master employee candidate records
    DELETE FROM dbo.HR_EMPLOYEE WHERE EMP_CODE LIKE 'ATS-%';
END
GO
