-- Migration: Add Dynamic Checklist columns to QMS_CHECKLIST_MASTER
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_MASTER') AND name = 'DYNAMIC_RULE_JSON')
BEGIN
    ALTER TABLE QMS_CHECKLIST_MASTER ADD DYNAMIC_RULE_JSON NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_MASTER') AND name = 'PAGE_ID')
BEGIN
    ALTER TABLE QMS_CHECKLIST_MASTER ADD PAGE_ID INT NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_MASTER') AND name = 'EVENT_TRIGGER')
BEGIN
    ALTER TABLE QMS_CHECKLIST_MASTER ADD EVENT_TRIGGER NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_MASTER') AND name = 'OFFSET_DAYS')
BEGIN
    ALTER TABLE QMS_CHECKLIST_MASTER ADD OFFSET_DAYS INT NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_MASTER') AND name = 'OFFSET_TYPE')
BEGIN
    ALTER TABLE QMS_CHECKLIST_MASTER ADD OFFSET_TYPE NVARCHAR(50) NULL;
END
