-- Migration Script V1163.0: Add Performance Indexes To QMT_ASSET_MASTER
-- Description: Creates optimized indexes on search, foreign key, and status columns for fast listing and filtering.

IF OBJECT_ID('QMT_ASSET_MASTER', 'U') IS NOT NULL
BEGIN
    -- Index on ASSET_ID
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_QMT_ASSET_MASTER_ASSET_ID' AND object_id = OBJECT_ID('QMT_ASSET_MASTER'))
    BEGIN
        CREATE NONCLUSTERED INDEX IX_QMT_ASSET_MASTER_ASSET_ID ON QMT_ASSET_MASTER(ASSET_ID);
        PRINT 'Created index IX_QMT_ASSET_MASTER_ASSET_ID';
    END

    -- Index on ASSET_NAME
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_QMT_ASSET_MASTER_ASSET_NAME' AND object_id = OBJECT_ID('QMT_ASSET_MASTER'))
    BEGIN
        CREATE NONCLUSTERED INDEX IX_QMT_ASSET_MASTER_ASSET_NAME ON QMT_ASSET_MASTER(ASSET_NAME);
        PRINT 'Created index IX_QMT_ASSET_MASTER_ASSET_NAME';
    END

    -- Index on STATUS
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_QMT_ASSET_MASTER_STATUS' AND object_id = OBJECT_ID('QMT_ASSET_MASTER'))
    BEGIN
        CREATE NONCLUSTERED INDEX IX_QMT_ASSET_MASTER_STATUS ON QMT_ASSET_MASTER(STATUS);
        PRINT 'Created index IX_QMT_ASSET_MASTER_STATUS';
    END

    -- Index on ASSET_GROUP_ID
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_QMT_ASSET_MASTER_GROUP_ID' AND object_id = OBJECT_ID('QMT_ASSET_MASTER'))
    BEGIN
        CREATE NONCLUSTERED INDEX IX_QMT_ASSET_MASTER_GROUP_ID ON QMT_ASSET_MASTER(ASSET_GROUP_ID);
        PRINT 'Created index IX_QMT_ASSET_MASTER_GROUP_ID';
    END

    -- Index on ASSET_TYPE_ID
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_QMT_ASSET_MASTER_TYPE_ID' AND object_id = OBJECT_ID('QMT_ASSET_MASTER'))
    BEGIN
        CREATE NONCLUSTERED INDEX IX_QMT_ASSET_MASTER_TYPE_ID ON QMT_ASSET_MASTER(ASSET_TYPE_ID);
        PRINT 'Created index IX_QMT_ASSET_MASTER_TYPE_ID';
    END

    -- Index on CREATED_DATE
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_QMT_ASSET_MASTER_CREATED_DATE' AND object_id = OBJECT_ID('QMT_ASSET_MASTER'))
    BEGIN
        CREATE NONCLUSTERED INDEX IX_QMT_ASSET_MASTER_CREATED_DATE ON QMT_ASSET_MASTER(CREATED_DATE DESC);
        PRINT 'Created index IX_QMT_ASSET_MASTER_CREATED_DATE';
    END
END
GO
