-- Organization: Autonoma ERP
-- Created At: 2026-08-29
-- Description: Add High-Performance Indexes for QMS Audit Observation Score Reports and Filtering

IF OBJECT_ID('dbo.QMS_AUDIT_OBSERVATION', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_AUDIT_OBSERVATION') AND name = 'IX_QMS_AUDIT_OBS_MAIN_PERF')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_AUDIT_OBS_MAIN_PERF
    ON [dbo].[QMS_AUDIT_OBSERVATION] ([AUDITOR_ID], [OBSERVATION_DATE])
    INCLUDE ([OBSERVATION_NO], [AUDIT_SCHEDULE_NO], [DEPARTMENT_ID], [AUDIT_TYPE_ID], [AUDITEE_ID], [AUDIT_SCORE], [COMPLIANCE_COUNT], [NCR_COUNT], [OFI_COUNT], [STATUS], [CREATED_DATE]);
    PRINT 'Created IX_QMS_AUDIT_OBS_MAIN_PERF index on QMS_AUDIT_OBSERVATION';
END;

IF OBJECT_ID('dbo.QMS_AUDIT_OBSERVATION_DETAIL', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_AUDIT_OBSERVATION_DETAIL') AND name = 'IX_QMS_AUDIT_OBS_DETAIL_STATUS_PERF')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_AUDIT_OBS_DETAIL_STATUS_PERF
    ON [dbo].[QMS_AUDIT_OBSERVATION_DETAIL] ([OBSERVATION_ID], [OBSERVATION_STATUS])
    INCLUDE ([NCR_NO], [SEQ_NO], [CLAUSE], [APPROVAL_STATUS], [NCR_STATUS], [TARGET_DATE], [CLOSED_DATE]);
    PRINT 'Created IX_QMS_AUDIT_OBS_DETAIL_STATUS_PERF index on QMS_AUDIT_OBSERVATION_DETAIL';
END;
