-- Adding missing foreign key indexes to QMS_MOM_DETAILS and QMS_MOM_MASTER to prevent full table scans and improve join performance
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_MOM_DETAILS_MOM_ID' AND object_id = OBJECT_ID('QMS_MOM_DETAILS'))
BEGIN
    CREATE INDEX [IX_QMS_MOM_DETAILS_MOM_ID] ON [dbo].[QMS_MOM_DETAILS] ([MOM_ID]);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_MOM_DETAILS_ASSIGNED_TO' AND object_id = OBJECT_ID('QMS_MOM_DETAILS'))
BEGIN
    CREATE INDEX [IX_QMS_MOM_DETAILS_ASSIGNED_TO] ON [dbo].[QMS_MOM_DETAILS] ([ASSIGNED_TO_ID]);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_MOM_DETAILS_ASSIGNED_BY' AND object_id = OBJECT_ID('QMS_MOM_DETAILS'))
BEGIN
    CREATE INDEX [IX_QMS_MOM_DETAILS_ASSIGNED_BY] ON [dbo].[QMS_MOM_DETAILS] ([ASSIGNED_BY_ID]);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_MOM_MASTER_SCHEDULE_ID' AND object_id = OBJECT_ID('QMS_MOM_MASTER'))
BEGIN
    CREATE INDEX [IX_QMS_MOM_MASTER_SCHEDULE_ID] ON [dbo].[QMS_MOM_MASTER] ([SCHEDULE_ID]);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_MOM_MASTER_CHAIRED_BY' AND object_id = OBJECT_ID('QMS_MOM_MASTER'))
BEGIN
    CREATE INDEX [IX_QMS_MOM_MASTER_CHAIRED_BY] ON [dbo].[QMS_MOM_MASTER] ([CHAIRED_BY_ID]);
END
GO
