-- Migration: 20260830_V1212.0__Add_DC_To_Invoice_Tracking_Columns.sql
-- Description: Add REF_INVOICE_NO, REF_INVOICE_DATE, REF_DC_NOS, and DC_STATUS to SM_INVOICE_HEADER for DC-to-Invoice linking

IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'SM_INVOICE_HEADER') 
    AND name = 'REF_INVOICE_NO'
)
BEGIN
    ALTER TABLE SM_INVOICE_HEADER ADD REF_INVOICE_NO NVARCHAR(100) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'SM_INVOICE_HEADER') 
    AND name = 'REF_INVOICE_DATE'
)
BEGIN
    ALTER TABLE SM_INVOICE_HEADER ADD REF_INVOICE_DATE DATETIME NULL;
END;

IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'SM_INVOICE_HEADER') 
    AND name = 'REF_DC_NOS'
)
BEGIN
    ALTER TABLE SM_INVOICE_HEADER ADD REF_DC_NOS NVARCHAR(500) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'SM_INVOICE_HEADER') 
    AND name = 'DC_STATUS'
)
BEGIN
    ALTER TABLE SM_INVOICE_HEADER ADD DC_STATUS NVARCHAR(50) DEFAULT 'PENDING';
END;
