IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('AD_PREFIX_CREDENTIALS') AND name = 'ENQUIRY_PREFIX')
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD ENQUIRY_PREFIX NVARCHAR(20);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('AD_PREFIX_CREDENTIALS') AND name = 'ENQUIRY_SUFFIX')
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD ENQUIRY_SUFFIX NVARCHAR(20);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('AD_PREFIX_CREDENTIALS') AND name = 'ENQUIRY_DIGIT')
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD ENQUIRY_DIGIT INT;
END
GO


drop table ACCOUNT_LEDGER