-- Migration: Add missing eSSL configuration columns to AD_COMPANY_CREDENTIAL
-- Version: V427.0
-- Date: 2026-07-14
-- Author: TIS

IF OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_CONFIG_NAME')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_CONFIG_NAME] NVARCHAR(100) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_ATTENDANCE_SOURCE')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_ATTENDANCE_SOURCE] NVARCHAR(50) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_CONNECTION_TYPE')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_CONNECTION_TYPE] NVARCHAR(50) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_DATABASE_TYPE')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_DATABASE_TYPE] NVARCHAR(50) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_SERVER_IP')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_SERVER_IP] NVARCHAR(100) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_PORT')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_PORT] INT NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_DB_NAME')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_DB_NAME] NVARCHAR(100) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_USERNAME')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_USERNAME] NVARCHAR(100) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_PASSWORD')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_PASSWORD] NVARCHAR(255) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_STATUS')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_STATUS] NVARCHAR(50) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_API_BASE_URL')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_API_BASE_URL] NVARCHAR(500) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_API_KEY')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_API_KEY] NVARCHAR(255) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_SECRET_KEY')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_SECRET_KEY] NVARCHAR(255) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_CLIENT_ID')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_CLIENT_ID] NVARCHAR(100) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_CLIENT_SECRET')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_CLIENT_SECRET] NVARCHAR(255) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_ACCESS_TOKEN')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_ACCESS_TOKEN] NVARCHAR(MAX) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ESSL_REFRESH_TOKEN')
        ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ESSL_REFRESH_TOKEN] NVARCHAR(MAX) NULL;

    PRINT 'eSSL configuration columns added/verified on AD_COMPANY_CREDENTIAL!';
END
