-- SQL Migration Script: Add Index to QMS_CHECKLIST_MASTER for Verify Status performance optimization
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_CHECKLIST_MASTER_VERIFY_STATUS' AND object_id = OBJECT_ID('QMS_CHECKLIST_MASTER'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CHECKLIST_MASTER_VERIFY_STATUS ON QMS_CHECKLIST_MASTER(VERIFY_STATUS);
END
GO
