-- Organization: Nutech
-- Owner: Nutech
-- Created At: 2026-09-03
-- Description: Add SINGLE_ACTIVE_SESSION to AD_COMPANY_CREDENTIAL, session fields & indexes to AD_USER_SESSION_AUDIT

-- 1. Add SINGLE_ACTIVE_SESSION column to AD_COMPANY_CREDENTIAL
IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') 
      AND name = N'SINGLE_ACTIVE_SESSION'
)
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL]
    ADD [SINGLE_ACTIVE_SESSION] BIT NOT NULL CONSTRAINT DF_AD_COMPANY_CREDENTIAL_SINGLE_ACTIVE_SESSION DEFAULT 0;
    PRINT 'Added SINGLE_ACTIVE_SESSION column to AD_COMPANY_CREDENTIAL.';
END;

-- 2. Extend AD_USER_SESSION_AUDIT with session tracking columns if missing
IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_AUDIT]') AND name = N'SESSION_ID'
)
BEGIN
    ALTER TABLE [dbo].[AD_USER_SESSION_AUDIT]
    ADD [SESSION_ID] NVARCHAR(100) NULL;
    PRINT 'Added SESSION_ID to AD_USER_SESSION_AUDIT.';
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_AUDIT]') AND name = N'DEVICE_ID'
)
BEGIN
    ALTER TABLE [dbo].[AD_USER_SESSION_AUDIT]
    ADD [DEVICE_ID] NVARCHAR(100) NULL;
    PRINT 'Added DEVICE_ID to AD_USER_SESSION_AUDIT.';
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_AUDIT]') AND name = N'DEVICE_NAME'
)
BEGIN
    ALTER TABLE [dbo].[AD_USER_SESSION_AUDIT]
    ADD [DEVICE_NAME] NVARCHAR(100) NULL;
    PRINT 'Added DEVICE_NAME to AD_USER_SESSION_AUDIT.';
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_AUDIT]') AND name = N'LAST_ACTIVITY'
)
BEGIN
    ALTER TABLE [dbo].[AD_USER_SESSION_AUDIT]
    ADD [LAST_ACTIVITY] DATETIME NULL;
    PRINT 'Added LAST_ACTIVITY to AD_USER_SESSION_AUDIT.';
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_AUDIT]') AND name = N'LOGOUT_REASON'
)
BEGIN
    ALTER TABLE [dbo].[AD_USER_SESSION_AUDIT]
    ADD [LOGOUT_REASON] NVARCHAR(50) NULL;
    PRINT 'Added LOGOUT_REASON to AD_USER_SESSION_AUDIT.';
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_AUDIT]') AND name = N'FORCED_BY_USER_ID'
)
BEGIN
    ALTER TABLE [dbo].[AD_USER_SESSION_AUDIT]
    ADD [FORCED_BY_USER_ID] NVARCHAR(50) NULL;
    PRINT 'Added FORCED_BY_USER_ID to AD_USER_SESSION_AUDIT.';
END;

-- 3. Create Performance Indexes on AD_USER_SESSION_AUDIT
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes 
    WHERE name = N'IX_AD_USER_SESSION_USER_STATUS' 
      AND object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_AUDIT]')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_AD_USER_SESSION_USER_STATUS]
    ON [dbo].[AD_USER_SESSION_AUDIT] ([USER_ID], [SESSION_STATUS])
    INCLUDE ([SESSION_ID], [LOGIN_TIME], [LAST_ACTIVITY], [DEVICE_NAME], [IP_ADDRESS]);
    PRINT 'Created index IX_AD_USER_SESSION_USER_STATUS.';
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes 
    WHERE name = N'IX_AD_USER_SESSION_SESSION_ID' 
      AND object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_AUDIT]')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_AD_USER_SESSION_SESSION_ID]
    ON [dbo].[AD_USER_SESSION_AUDIT] ([SESSION_ID]);
    PRINT 'Created index IX_AD_USER_SESSION_SESSION_ID.';
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes 
    WHERE name = N'IX_AD_USER_SESSION_LAST_ACT' 
      AND object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_AUDIT]')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_AD_USER_SESSION_LAST_ACT]
    ON [dbo].[AD_USER_SESSION_AUDIT] ([LAST_ACTIVITY]);
    PRINT 'Created index IX_AD_USER_SESSION_LAST_ACT.';
END;
