-- Migration V381.0: Add AUTO_SCHEDULE and PARENT_SCHEDULE_ID to QMS_MEETING_SCHEDULE table
-- Created: 2026-07-01

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') AND name = 'AUTO_SCHEDULE')
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ADD AUTO_SCHEDULE BIT NOT NULL DEFAULT 1;
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') AND name = 'PARENT_SCHEDULE_ID')
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ADD PARENT_SCHEDULE_ID BIGINT NULL;
    
    -- Create foreign key constraint
    ALTER TABLE QMS_MEETING_SCHEDULE WITH CHECK ADD CONSTRAINT FK_QMS_MEETING_SCHEDULE_PARENT
        FOREIGN KEY (PARENT_SCHEDULE_ID) REFERENCES QMS_MEETING_SCHEDULE (ID);
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') AND name = 'MEETING_STATUS')
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ADD MEETING_STATUS NVARCHAR(50) NULL DEFAULT 'Scheduled';
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') AND name = 'ATTENDANCE_STATUS')
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ADD ATTENDANCE_STATUS NVARCHAR(50) NULL DEFAULT 'Pending';
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') AND name = 'MOM_STATUS')
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ADD MOM_STATUS NVARCHAR(50) NULL DEFAULT 'Not Started';
END
