ALTER TABLE [dbo].[NPD_PRODUCT_MASTER]
ADD 
    [DRAWING_NO] NVARCHAR(100) NULL,
    [SAC_CODE] NVARCHAR(50) NULL,
    [MAKE_NAME] NVARCHAR(100) NULL;
GO

EXEC sp_rename 'NPD_PRODUCT_MASTER.PART_NO', 'ITEM_NO', 'COLUMN';
GO

ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [ITEM_CODE] NVARCHAR(100) NULL;
GO

ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [PART_NO_OLD] NVARCHAR(255) NULL;
GO

ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [PRINT_NAME] NVARCHAR(500) NULL;
ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [ITEM_NAME] NVARCHAR(500) NOT NULL;
ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [DRAWING_NO] NVARCHAR(255) NULL;
ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [MODEL_NO] NVARCHAR(255) NULL;
ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [GRADE] NVARCHAR(255) NULL;
ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [UOM] NVARCHAR(255) NULL;
ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [ITEM_GROUP] NVARCHAR(255) NULL;
ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [ITEM_CATEGORY] NVARCHAR(255) NULL;
ALTER TABLE [dbo].[NPD_PRODUCT_MASTER] ALTER COLUMN [MAKE_NAME] NVARCHAR(255) NULL;
GO

ALTER TABLE [dbo].[MST_HSN_MASTER]
ADD [CODE_TYPE] VARCHAR(20) DEFAULT 'HSN';
GO