-- ===================================================================================
-- Migration: 20260801_V1097.0__Seed_Leave_OD_Permission_HR_App_Preferences.sql
-- Module: HR / Attendance, Leave, OD, Permission Policy Configuration
-- Purpose: Idempotently seed default HR App Preferences in AD_APP_PREFERENCE
-- ===================================================================================

-- 1. Leave Apply Preferences
IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'LEAVE_ALLOW_BACKDATED')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LEAVE_ALLOW_BACKDATED', 'Yes', 'Allow backdated leave applications (Yes/No)', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'LEAVE_MAX_BACKDATED_DAYS')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LEAVE_MAX_BACKDATED_DAYS', '3', 'Maximum backdated days allowed for leave application', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'LEAVE_ADVANCE_NOTICE_DAYS')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LEAVE_ADVANCE_NOTICE_DAYS', '1', 'Minimum advance notice required in days for leave application', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'LEAVE_ALLOW_NEGATIVE_BALANCE_GLOBAL')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LEAVE_ALLOW_NEGATIVE_BALANCE_GLOBAL', 'No', 'Global master toggle to allow negative leave balances', 'HRA', 'SYSTEM', GETDATE());
END

-- 2. OD Apply Preferences
IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OD_ALLOW_PAST_DATES')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('OD_ALLOW_PAST_DATES', 'No', 'Allow backdated OD applications (Yes/No)', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OD_MAX_BACKDATED_DAYS')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('OD_MAX_BACKDATED_DAYS', '2', 'Maximum backdated days allowed for OD application', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OD_MAX_REQUESTS_MONTH')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('OD_MAX_REQUESTS_MONTH', '5', 'Maximum OD applications allowed per employee per month', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OD_MAX_DAYS_PER_REQUEST')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('OD_MAX_DAYS_PER_REQUEST', '7', 'Maximum continuous days allowed per OD application', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OD_DOCUMENT_REQUIRED_THRESHOLD')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('OD_DOCUMENT_REQUIRED_THRESHOLD', '3', 'Threshold days requiring mandatory supporting document for OD', 'HRA', 'SYSTEM', GETDATE());
END

-- 3. Permission Apply Preferences
IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'PERMISSION_ALLOW_PAST_DATES')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('PERMISSION_ALLOW_PAST_DATES', 'No', 'Allow backdated permission applications (Yes/No)', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'PERMISSION_MAX_BACKDATED_DAYS')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('PERMISSION_MAX_BACKDATED_DAYS', '1', 'Maximum backdated days allowed for permission application', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'PERMISSION_ALLOW_SAME_DAY')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('PERMISSION_ALLOW_SAME_DAY', 'Yes', 'Allow same-day permission applications (Yes/No)', 'HRA', 'SYSTEM', GETDATE());
END
GO
