-- Migration to reassign Leave Verification (PAGE_CODE = 'HA1392') PAGE_ID from out-of-sequence 45004 to sequential 164

IF EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_ID = 45004)
BEGIN
    UPDATE BOS_USER_PAGE_AUTH SET PAGE_ID = 164 WHERE PAGE_ID = 45004;
    DELETE FROM BOS_PAGES WHERE PAGE_ID = 45004;
END

IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_ID = 164 OR PAGE_CODE = 'HA1392')
BEGIN
    SET IDENTITY_INSERT BOS_PAGES ON;
    INSERT INTO BOS_PAGES (PAGE_ID, MOD_ID, SUB_MOD_ID, PAGE_CODE, PAGE_NAME, ENABLED, PAGE_URL, ICON)
    VALUES (164, 2, 203, 'HA1392', 'Leave Verification', 1, '/hra/attendance/leave-verification', 'IconChecklist');
    SET IDENTITY_INSERT BOS_PAGES OFF;
END
