-- Migration Script: Add REASSIGN_COMMENTS and REASSIGN_HISTORY columns to QMS_MOM_DETAILS table
-- Date: 2026-08-24

IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE object_id = OBJECT_ID('QMS_MOM_DETAILS') 
      AND name = 'REASSIGN_COMMENTS'
)
BEGIN
    ALTER TABLE QMS_MOM_DETAILS ADD REASSIGN_COMMENTS NVARCHAR(MAX) NULL;
END
GO

IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE object_id = OBJECT_ID('QMS_MOM_DETAILS') 
      AND name = 'REASSIGN_HISTORY'
)
BEGIN
    ALTER TABLE QMS_MOM_DETAILS ADD REASSIGN_HISTORY NVARCHAR(MAX) NULL;
END
GO
