UPDATE QMS_MEETING_SCHEDULE 
SET SECONDARY_HOST_ID = NULL 
WHERE SECONDARY_HOST_ID IS NOT NULL AND SECONDARY_HOST_ID NOT IN (SELECT ID FROM HR_EMPLOYEE);

UPDATE QMS_MEETING_SCHEDULE 
SET TERTIARY_HOST_ID = NULL 
WHERE TERTIARY_HOST_ID IS NOT NULL AND TERTIARY_HOST_ID NOT IN (SELECT ID FROM HR_EMPLOYEE);
GO



IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
    WHERE TABLE_NAME = 'NPD_OEM' 
    AND CONSTRAINT_TYPE = 'PRIMARY KEY'
)
BEGIN
    ALTER TABLE [dbo].[NPD_OEM] 
    ADD CONSTRAINT PK_NPD_OEM PRIMARY KEY ([OEM_SHORT_NAME]);
END
GO