-- Organization: Nutechwindparts
-- Owner: Nutech
-- Created At: 2026-09-05
-- Description: Alter REV_NO column in NPD_PRODUCT_MASTER to NVARCHAR(50)

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NPD_PRODUCT_MASTER')
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_NAME = 'NPD_PRODUCT_MASTER' 
          AND COLUMN_NAME = 'REV_NO' 
          AND (CHARACTER_MAXIMUM_LENGTH IS NULL OR CHARACTER_MAXIMUM_LENGTH < 50)
    )
    BEGIN
        ALTER TABLE NPD_PRODUCT_MASTER
        ALTER COLUMN REV_NO NVARCHAR(50) NULL;
    END
END
GO
