-- Create AD_OCR_CONFIG table to maintain separate OCR configuration
IF OBJECT_ID('[dbo].[AD_OCR_CONFIG]', 'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AD_OCR_CONFIG] (
        [id] BIGINT IDENTITY(1,1) NOT NULL,
        [COMPANY_CREDENTIAL_ID] BIGINT NOT NULL,
        [OCR_TENANT_ID] NVARCHAR(100) NULL,
        [OCR_CLIENT_ID] NVARCHAR(100) NULL,
        [OCR_CLIENT_SECRET] NVARCHAR(255) NULL,
        [OCR_SHARED_MAILBOX] NVARCHAR(100) NULL,
        [OCR_PROCESSED_FOLDER] NVARCHAR(100) NULL,
        CONSTRAINT [PK_AD_OCR_CONFIG] PRIMARY KEY CLUSTERED ([id]),
        CONSTRAINT [FK_AD_OCR_CONFIG_COMPANY] FOREIGN KEY ([COMPANY_CREDENTIAL_ID]) REFERENCES [dbo].[AD_COMPANY_CREDENTIAL] ([id]) ON DELETE CASCADE,
        CONSTRAINT [UQ_AD_OCR_CONFIG_COMPANY] UNIQUE ([COMPANY_CREDENTIAL_ID])
    );
    PRINT 'Created table AD_OCR_CONFIG';
END
GO

-- Migrate existing OCR configuration from AD_COMPANY_CREDENTIAL to AD_OCR_CONFIG
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'OCR_TENANT_ID')
BEGIN
    INSERT INTO [dbo].[AD_OCR_CONFIG] (COMPANY_CREDENTIAL_ID, OCR_TENANT_ID, OCR_CLIENT_ID, OCR_CLIENT_SECRET, OCR_SHARED_MAILBOX, OCR_PROCESSED_FOLDER)
    SELECT id, OCR_TENANT_ID, OCR_CLIENT_ID, OCR_CLIENT_SECRET, OCR_SHARED_MAILBOX, OCR_PROCESSED_FOLDER
    FROM [dbo].[AD_COMPANY_CREDENTIAL];
    PRINT 'Migrated OCR configurations to AD_OCR_CONFIG';

    -- Drop old OCR configuration columns from AD_COMPANY_CREDENTIAL
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] DROP COLUMN OCR_TENANT_ID;
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] DROP COLUMN OCR_CLIENT_ID;
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] DROP COLUMN OCR_CLIENT_SECRET;
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] DROP COLUMN OCR_SHARED_MAILBOX;
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] DROP COLUMN OCR_PROCESSED_FOLDER;
    PRINT 'Dropped OCR columns from AD_COMPANY_CREDENTIAL';
END
GO
