IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('PP_QUOTATION_HEAD') AND name = 'TRANSPORT_SCOPE'
)
BEGIN
    ALTER TABLE PP_QUOTATION_HEAD ADD TRANSPORT_SCOPE NVARCHAR(50) DEFAULT 'BUYER';
END
GO
