-- 20260622_V316.0__Seed_Satisfaction_Mappings_For_All.sql
-- Seed Customer, Vendor, and Internal Customer satisfaction mappings for June 2026

-- 1. Seed SLS_CUSTOMER if not exists
IF NOT EXISTS (SELECT 1 FROM [dbo].[SLS_CUSTOMER] WHERE [CUSTOMER_CODE] = 'CUST-001')
BEGIN
    INSERT INTO [dbo].[SLS_CUSTOMER] (
        [CUSTOMER_CODE], [CUSTOMER_NAME], [STATUS], [IS_ACTIVE], [CREATED_BY], [CREATED_DATE]
    ) VALUES (
        'CUST-001', 'Acme Corporation', 'Active', 1, 'SYSTEM', GETDATE()
    );
    PRINT 'Seeded customer CUST-001';
END
GO

-- 2. Seed VND_VENDOR if not exists
IF NOT EXISTS (SELECT 1 FROM [dbo].[VND_VENDOR] WHERE [SUPPLIER_CODE] = 'VEND-001')
BEGIN
    INSERT INTO [dbo].[VND_VENDOR] (
        [SUPPLIER_CODE], [SUPPLIER_NAME], [STATUS], [IS_ACTIVE], [CREATED_BY], [CREATED_DATE]
    ) VALUES (
        'VEND-001', 'Apex Industries', 'Active', 1, 'SYSTEM', GETDATE()
    );
    PRINT 'Seeded vendor VEND-001';
END
GO

-- 3. Seed CUSTOMER_SATISFACTION_MAPPING
IF NOT EXISTS (
    SELECT 1 FROM [dbo].[CUSTOMER_SATISFACTION_MAPPING] c
    JOIN [dbo].[SLS_CUSTOMER] s ON c.[CUSTOMER_ID] = s.[ID]
    WHERE s.[CUSTOMER_CODE] = 'CUST-001' AND c.[FEEDBACK_CYCLE] = 'June 2026'
)
BEGIN
    INSERT INTO [dbo].[CUSTOMER_SATISFACTION_MAPPING] (
        [CUSTOMER_ID], [FEEDBACK_CYCLE], [ELIGIBILITY_DATE], [FEEDBACK_START_DATE], [FEEDBACK_END_DATE], [IS_CLOSED], [STATUS], [REMINDER_COUNT], [DISMISSED_COUNT], [CREATED_BY], [CREATED_DATE]
    ) VALUES (
        (SELECT [ID] FROM [dbo].[SLS_CUSTOMER] WHERE [CUSTOMER_CODE] = 'CUST-001'), 
        'June 2026', CAST(GETDATE() AS DATE), CAST(GETDATE() AS DATE), CAST(DATEADD(day, 14, GETDATE()) AS DATE), 'N', 'Pending', 0, 0, 'SYSTEM', GETDATE()
    );
    PRINT 'Seeded customer satisfaction mapping for June 2026';
END
GO

-- 4. Seed VENDOR_SATISFACTION_MAPPING
IF NOT EXISTS (
    SELECT 1 FROM [dbo].[VENDOR_SATISFACTION_MAPPING] v
    JOIN [dbo].[VND_VENDOR] s ON v.[VENDOR_ID] = s.[ID]
    WHERE s.[SUPPLIER_CODE] = 'VEND-001' AND v.[FEEDBACK_CYCLE] = 'June 2026'
)
BEGIN
    INSERT INTO [dbo].[VENDOR_SATISFACTION_MAPPING] (
        [VENDOR_ID], [FEEDBACK_CYCLE], [ELIGIBILITY_DATE], [FEEDBACK_START_DATE], [FEEDBACK_END_DATE], [IS_CLOSED], [STATUS], [REMINDER_COUNT], [CREATED_BY], [CREATED_DATE]
    ) VALUES (
        (SELECT [ID] FROM [dbo].[VND_VENDOR] WHERE [SUPPLIER_CODE] = 'VEND-001'), 
        'June 2026', CAST(GETDATE() AS DATE), CAST(GETDATE() AS DATE), CAST(DATEADD(day, 14, GETDATE()) AS DATE), 'N', 'Pending', 0, 'SYSTEM', GETDATE()
    );
    PRINT 'Seeded vendor satisfaction mapping for June 2026';
END
GO

-- 5. Seed INTERNAL_CUSTOMER_SATISFACTION_MAPPING
IF NOT EXISTS (
    SELECT 1 FROM [dbo].[INTERNAL_CUSTOMER_SATISFACTION_MAPPING] i
    JOIN [dbo].[HR_EMPLOYEE] e ON i.[EMPLOYEE_ID] = e.[ID]
    WHERE e.[EMP_CODE] = 'ADMIN_EMP' AND i.[FEEDBACK_CYCLE] = 'June 2026'
)
BEGIN
    INSERT INTO [dbo].[INTERNAL_CUSTOMER_SATISFACTION_MAPPING] (
        [EMPLOYEE_ID], [FEEDBACK_CYCLE], [ELIGIBILITY_DATE], [FEEDBACK_START_DATE], [FEEDBACK_END_DATE], [IS_CLOSED], [STATUS], [REMINDER_COUNT], [CREATED_BY], [CREATED_DATE]
    ) VALUES (
        (SELECT TOP 1 [ID] FROM [dbo].[HR_EMPLOYEE] WHERE [EMP_CODE] = 'ADMIN_EMP'), 
        'June 2026', CAST(GETDATE() AS DATE), CAST(GETDATE() AS DATE), CAST(DATEADD(day, 14, GETDATE()) AS DATE), 'N', 'Pending', 0, 'SYSTEM', GETDATE()
    );
    PRINT 'Seeded internal customer satisfaction mapping for June 2026';
END
GO
