-- Fix existing candidates who were rejected at the interview phase but still show 'Pending' for subsequent columns (Offer, Verification).
UPDATE HR_EMPLOYEE_ATS
SET OFFER_STATUS = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'REJECTED'),
    VERIFICATION_STATUS = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'REJECTED')
WHERE INTERVIEW_STATUS = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'REJECTED')
  AND (OFFER_STATUS = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PENDING') 
       OR VERIFICATION_STATUS = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PENDING'));
