-- V1031.0: Leave Apply – Status Master integration
-- 1. Seed required Status Master entries
-- 2. Add STATUS_ID (INT) column to HR_LEAVE_DETAILS
-- 3. Migrate existing rows to STATUS_ID
-- 4. Rename STATUS (BIT active flag) → IS_ACTIVE

-- Step 1: Seed Status Master entries
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Pending to Verify')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Pending to Verify');
    PRINT 'Inserted status: Pending to Verify';
END

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Verified')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Verified');
    PRINT 'Inserted status: Verified';
END

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Rejected')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Rejected');
    PRINT 'Inserted status: Rejected';
END

-- Step 2: Add STATUS_ID column
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_LEAVE_DETAILS' AND COLUMN_NAME = 'STATUS_ID'
)
BEGIN
    ALTER TABLE HR_LEAVE_DETAILS ADD STATUS_ID INT NULL;
    PRINT 'Added STATUS_ID column to HR_LEAVE_DETAILS';
END
GO

-- Step 3: Migrate existing data into STATUS_ID
-- Rows with REJECT_REASON → Rejected
UPDATE HR_LEAVE_DETAILS
SET STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Rejected')
WHERE REJECT_REASON IS NOT NULL AND LEN(REJECT_REASON) > 0 AND STATUS_ID IS NULL;

-- Rows with VERIFIED_BY (no reject reason) → Verified
UPDATE HR_LEAVE_DETAILS
SET STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Verified')
WHERE VERIFIED_BY IS NOT NULL AND LEN(VERIFIED_BY) > 0
  AND (REJECT_REASON IS NULL OR LEN(REJECT_REASON) = 0) AND STATUS_ID IS NULL;

-- Remaining rows → Pending to Verify
UPDATE HR_LEAVE_DETAILS
SET STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Pending to Verify')
WHERE VERIFIED_BY IS NULL AND STATUS_ID IS NULL;

PRINT 'STATUS_ID data migrated';

-- Step 4: Rename STATUS (BIT active flag) to IS_ACTIVE
IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_LEAVE_DETAILS' AND COLUMN_NAME = 'STATUS'
)
AND NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_LEAVE_DETAILS' AND COLUMN_NAME = 'IS_ACTIVE'
)
BEGIN
    EXEC sp_rename 'HR_LEAVE_DETAILS.STATUS', 'IS_ACTIVE', 'COLUMN';
    PRINT 'Renamed STATUS (BIT) to IS_ACTIVE in HR_LEAVE_DETAILS';
END
