-- 20260624_V343.0__Fix_Npd_Product_Master_Pk_And_Bom_Tables__TIS.sql

-- 1. Ensure NPD_PRODUCT_MASTER has Primary Key PK_NPD_PRODUCT_MASTER on ID column
IF NOT EXISTS (
    SELECT 1 FROM sys.key_constraints 
    WHERE type = 'PK' AND parent_object_id = OBJECT_ID('NPD_PRODUCT_MASTER')
)
BEGIN
    -- Ensure ID column is not nullable
    ALTER TABLE NPD_PRODUCT_MASTER ALTER COLUMN ID BIGINT NOT NULL;
    
    -- Add the primary key constraint
    ALTER TABLE NPD_PRODUCT_MASTER ADD CONSTRAINT PK_NPD_PRODUCT_MASTER PRIMARY KEY (ID);
END
GO

-- 2. Check and create NPD_BOM_MASTER
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('NPD_BOM_MASTER') AND type = 'U')
BEGIN
    CREATE TABLE NPD_BOM_MASTER (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        PRODUCT_ID BIGINT NOT NULL,
        BOM_NO NVARCHAR(100),
        REV_NO NVARCHAR(50),
        REV_DATE DATETIME2,
        IS_ACTIVE BIT DEFAULT 1,
        CREATED_BY NVARCHAR(50),
        CREATED_DATE DATETIME2 DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME2,
        BASE_QUANTITY DECIMAL(18, 4) DEFAULT 1.0,
        BOM_USAGE NVARCHAR(50) DEFAULT 'Production',
        VALID_FROM DATETIME2,
        VALID_TO DATETIME2,
        CONSTRAINT FK_BOM_MASTER_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES NPD_PRODUCT_MASTER(ID),
        CONSTRAINT FK_BOM_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_BOM_MASTER_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
ELSE
BEGIN
    -- Ensure columns exist
    IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'BASE_QUANTITY' AND Object_ID = Object_ID(N'NPD_BOM_MASTER'))
        ALTER TABLE NPD_BOM_MASTER ADD BASE_QUANTITY DECIMAL(18, 4) DEFAULT 1.0;
    IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'BOM_USAGE' AND Object_ID = Object_ID(N'NPD_BOM_MASTER'))
        ALTER TABLE NPD_BOM_MASTER ADD BOM_USAGE NVARCHAR(50) DEFAULT 'Production';
    IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'VALID_FROM' AND Object_ID = Object_ID(N'NPD_BOM_MASTER'))
        ALTER TABLE NPD_BOM_MASTER ADD VALID_FROM DATETIME2;
    IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'VALID_TO' AND Object_ID = Object_ID(N'NPD_BOM_MASTER'))
        ALTER TABLE NPD_BOM_MASTER ADD VALID_TO DATETIME2;
    
    -- Handle renaming CREATED_AT/UPDATED_AT to CREATED_DATE/UPDATED_DATE if they exist
    IF EXISTS(SELECT * FROM sys.columns WHERE Name = N'CREATED_AT' AND Object_ID = Object_ID(N'NPD_BOM_MASTER'))
        EXEC sp_rename 'NPD_BOM_MASTER.CREATED_AT', 'CREATED_DATE', 'COLUMN';
    IF EXISTS(SELECT * FROM sys.columns WHERE Name = N'UPDATED_AT' AND Object_ID = Object_ID(N'NPD_BOM_MASTER'))
        EXEC sp_rename 'NPD_BOM_MASTER.UPDATED_AT', 'UPDATED_DATE', 'COLUMN';
END
GO

-- 3. Check and create NPD_BOM_DETAILS
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('NPD_BOM_DETAILS') AND type = 'U')
BEGIN
    CREATE TABLE NPD_BOM_DETAILS (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        BOM_ID BIGINT NOT NULL,
        INPUT_PRODUCT_ID BIGINT NOT NULL,
        QUANTITY DECIMAL(18, 4),
        UOM NVARCHAR(50),
        IS_ALTERNATE BIT DEFAULT 0,
        PRIMARY_MATERIAL_ID BIGINT NULL,
        REMARKS NVARCHAR(255),
        CREATED_BY NVARCHAR(50),
        CREATED_DATE DATETIME2 DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME2,
        ITEM_NO INT,
        SCRAP_PERCENTAGE DECIMAL(5, 2) DEFAULT 0,
        PRIMARY_ITEM_NO INT,
        ALT_PRIORITY INT DEFAULT 1,
        CONSTRAINT FK_BOM_DETAILS_MASTER FOREIGN KEY (BOM_ID) REFERENCES NPD_BOM_MASTER(ID),
        CONSTRAINT FK_BOM_DETAILS_PRODUCT FOREIGN KEY (INPUT_PRODUCT_ID) REFERENCES NPD_PRODUCT_MASTER(ID),
        CONSTRAINT FK_BOM_DETAILS_PRIMARY FOREIGN KEY (PRIMARY_MATERIAL_ID) REFERENCES NPD_BOM_DETAILS(ID),
        CONSTRAINT FK_BOM_DETAILS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_BOM_DETAILS_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
ELSE
BEGIN
    -- Ensure columns exist
    IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'ITEM_NO' AND Object_ID = Object_ID(N'NPD_BOM_DETAILS'))
        ALTER TABLE NPD_BOM_DETAILS ADD ITEM_NO INT;
    IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'SCRAP_PERCENTAGE' AND Object_ID = Object_ID(N'NPD_BOM_DETAILS'))
        ALTER TABLE NPD_BOM_DETAILS ADD SCRAP_PERCENTAGE DECIMAL(5, 2) DEFAULT 0;
    IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'PRIMARY_ITEM_NO' AND Object_ID = Object_ID(N'NPD_BOM_DETAILS'))
        ALTER TABLE NPD_BOM_DETAILS ADD PRIMARY_ITEM_NO INT;
    IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'ALT_PRIORITY' AND Object_ID = Object_ID(N'NPD_BOM_DETAILS'))
        ALTER TABLE NPD_BOM_DETAILS ADD ALT_PRIORITY INT DEFAULT 1;

    -- Handle renaming CREATED_AT/UPDATED_AT to CREATED_DATE/UPDATED_DATE if they exist
    IF EXISTS(SELECT * FROM sys.columns WHERE Name = N'CREATED_AT' AND Object_ID = Object_ID(N'NPD_BOM_DETAILS'))
        EXEC sp_rename 'NPD_BOM_DETAILS.CREATED_AT', 'CREATED_DATE', 'COLUMN';
    IF EXISTS(SELECT * FROM sys.columns WHERE Name = N'UPDATED_AT' AND Object_ID = Object_ID(N'NPD_BOM_DETAILS'))
        EXEC sp_rename 'NPD_BOM_DETAILS.UPDATED_AT', 'UPDATED_DATE', 'COLUMN';
END
GO
