-- DB Script: 20260725_V1059.0__Consolidated_Client_Management_And_Status_Id.sql
-- Module: Platform / Identity / Client Management
-- Description: Consolidated migration script for Client Master, Server Config, and STATUS_ID schema updates.

-- 1. Ensure AD_STATUS_MASTER has ACTIVE & INACTIVE statuses
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'ACTIVE')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('ACTIVE');
END;

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'INACTIVE')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('INACTIVE');
END;

-- 2. Ensure CLI_CLIENT_SERVER_CONFIG table has all health monitoring columns
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'CLI_CLIENT_SERVER_CONFIG')
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'SERVER_NAME')
    BEGIN
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG ADD SERVER_NAME VARCHAR(150) NULL;
    END;

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'SERVER_IP')
    BEGIN
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG ADD SERVER_IP VARCHAR(50) NULL;
    END;

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'WINDOWS_USERNAME')
    BEGIN
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG ADD WINDOWS_USERNAME VARCHAR(100) NULL;
    END;

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'WINDOWS_PASSWORD')
    BEGIN
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG ADD WINDOWS_PASSWORD VARCHAR(500) NULL;
    END;

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'HEALTH_MONITORING_ENABLED')
    BEGIN
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG ADD HEALTH_MONITORING_ENABLED BIT DEFAULT 0;
    END;
END;

-- 3. Add STATUS_ID column to CLI_CLIENT_MASTER
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'CLI_CLIENT_MASTER')
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_MASTER') AND name = 'STATUS_ID')
    BEGIN
        ALTER TABLE CLI_CLIENT_MASTER ADD STATUS_ID BIGINT NULL;
    END;
END;
GO

-- 4. Add STATUS_ID column to CLI_CLIENT_LICENSE
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'CLI_CLIENT_LICENSE')
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_LICENSE') AND name = 'STATUS_ID')
    BEGIN
        ALTER TABLE CLI_CLIENT_LICENSE ADD STATUS_ID BIGINT NULL;
    END;
END;
GO

-- 5. Ensure AD_COMPANY_CREDENTIAL has CLIENT_CODE column
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'AD_COMPANY_CREDENTIAL') AND name = N'CLIENT_CODE')
BEGIN
    ALTER TABLE AD_COMPANY_CREDENTIAL ADD CLIENT_CODE NVARCHAR(50) NULL;
END;
GO

-- 6. Populate default seed Client Master record ('123456' / Autonoma) if absent
IF NOT EXISTS (SELECT 1 FROM CLI_CLIENT_MASTER WHERE CLIENT_CODE = '123456')
BEGIN
    INSERT INTO CLI_CLIENT_MASTER (
        CLIENT_CODE,
        CLIENT_NAME,
        COMPANY_NAME,
        SHORT_NAME,
        EMAIL,
        MOBILE_NUMBER,
        CONTACT_PERSON,
        STATUS_ID,
        IS_DELETED,
        CREATED_BY,
        CREATED_AT,
        UPDATED_AT
    ) VALUES (
        '123456',
        'Autonoma',
        'Autonoma',
        'AUTONOMA',
        'admin@autonoma.com',
        '9876543210',
        'System Admin',
        (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'ACTIVE'),
        0,
        'SYSTEM',
        GETDATE(),
        GETDATE()
    );
END;

-- 7. Sync AD_COMPANY_CREDENTIAL client codes to default '123456'
UPDATE AD_COMPANY_CREDENTIAL 
SET CLIENT_CODE = '123456'
WHERE CLIENT_CODE IS NULL OR CLIENT_CODE <> '123456';

-- 8. Dynamic status migration & fallback to ACTIVE status ID
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_MASTER') AND name = 'STATUS')
BEGIN
    EXEC sp_executesql N'
    UPDATE CM
    SET CM.STATUS_ID = S.ID
    FROM CLI_CLIENT_MASTER CM
    JOIN AD_STATUS_MASTER S ON UPPER(TRIM(CM.STATUS)) = UPPER(TRIM(S.NAME))
    WHERE CM.STATUS_ID IS NULL;
    ';
END;

UPDATE CLI_CLIENT_MASTER
SET STATUS_ID = (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'ACTIVE')
WHERE STATUS_ID IS NULL;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_LICENSE') AND name = 'STATUS')
BEGIN
    EXEC sp_executesql N'
    UPDATE CL
    SET CL.STATUS_ID = S.ID
    FROM CLI_CLIENT_LICENSE CL
    JOIN AD_STATUS_MASTER S ON UPPER(TRIM(CL.STATUS)) = UPPER(TRIM(S.NAME))
    WHERE CL.STATUS_ID IS NULL;
    ';
END;

UPDATE CLI_CLIENT_LICENSE
SET STATUS_ID = (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'ACTIVE')
WHERE STATUS_ID IS NULL;

GO
