-- 1. Add PR_TRANS_ID to PP_RFQ_DETAIL
IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[PP_RFQ_DETAIL]') 
    AND name = 'PR_TRANS_ID'
)
BEGIN
    ALTER TABLE [dbo].[PP_RFQ_DETAIL] ADD [PR_TRANS_ID] BIGINT NULL;
    ALTER TABLE [dbo].[PP_RFQ_DETAIL] ADD CONSTRAINT [FK_PP_RFQ_DETAIL_PR_TRANS] FOREIGN KEY ([PR_TRANS_ID]) REFERENCES [dbo].[PP_PURCHASE_REQUEST_TRANS]([ID]);
END
GO

-- 2. Add THREAD_MESSAGE_ID to PP_RFQ_SUPPLIER
IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[PP_RFQ_SUPPLIER]') 
    AND name = 'THREAD_MESSAGE_ID'
)
BEGIN
    ALTER TABLE [dbo].[PP_RFQ_SUPPLIER] ADD [THREAD_MESSAGE_ID] NVARCHAR(250) NULL;
END
GO

-- 3. Add MESSAGE_ID and IN_REPLY_TO to PP_RFQ_EMAIL_LOG
IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[PP_RFQ_EMAIL_LOG]') 
    AND name = 'MESSAGE_ID'
)
BEGIN
    ALTER TABLE [dbo].[PP_RFQ_EMAIL_LOG] ADD [MESSAGE_ID] NVARCHAR(250) NULL;
    ALTER TABLE [dbo].[PP_RFQ_EMAIL_LOG] ADD [IN_REPLY_TO] NVARCHAR(250) NULL;
END
GO
