CREATE TABLE QMS_AUDIT_SCHEDULER_LOG (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONFIG_ID BIGINT NOT NULL,
    TRIGGER_TIME DATETIME,
    STATUS NVARCHAR(50),
    SUCCESS_COUNT INT,
    FAILURE_COUNT INT,
    DURATION_MS BIGINT,
    ERROR_DETAILS NVARCHAR(MAX),
    CREATED_BY NVARCHAR(50),
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    CONSTRAINT FK_QMS_AUDIT_SCHEDULER_LOG_CONFIG FOREIGN KEY (CONFIG_ID) REFERENCES QMS_AUDIT_SCHEDULER_CONFIG(ID) ON DELETE CASCADE,
    CONSTRAINT FK_QMS_AUDIT_SCHEDULER_LOG_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_QMS_AUDIT_SCHEDULER_LOG_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);
