-- Organization: Nutech Wind Parts Pvt Ltd
-- Owner: Nutech
-- Created At: 2026-08-31
-- Description: Create Product BOM and Process Routing Tables, Constraints, and Page Registration

-- 1. Create NPD_BOM_MASTER
IF OBJECT_ID('dbo.NPD_BOM_MASTER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NPD_BOM_MASTER (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        PRODUCT_ID BIGINT NOT NULL,
        BOM_NO NVARCHAR(100) NULL,
        REV_NO NVARCHAR(50) NULL,
        REV_DATE DATETIME2 NULL,
        IS_ACTIVE BIT DEFAULT 1 NOT NULL,
        BASE_QUANTITY DECIMAL(18, 4) DEFAULT 1.0 NOT NULL,
        BOM_USAGE NVARCHAR(50) DEFAULT 'Production' NOT NULL,
        VALID_FROM DATETIME2 NULL,
        VALID_TO DATETIME2 NULL,
        REMARKS NVARCHAR(500) NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME2 DEFAULT GETDATE() NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME2 NULL,
        
        CONSTRAINT PK_NPD_BOM_MASTER PRIMARY KEY (ID),
        CONSTRAINT FK_NPD_BOM_MASTER_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.NPD_PRODUCT_MASTER(ID),
        CONSTRAINT FK_NPD_BOM_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_NPD_BOM_MASTER_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
END;
GO

-- 2. Create NPD_BOM_PROCESS
IF OBJECT_ID('dbo.NPD_BOM_PROCESS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NPD_BOM_PROCESS (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        BOM_ID BIGINT NOT NULL,
        SEQ_NO INT NOT NULL,
        PROCESS_ID BIGINT NOT NULL,
        WORK_CENTER NVARCHAR(150) NULL,
        LOCATION NVARCHAR(150) NULL,
        PRIMARY_MACHINE_ID BIGINT NULL,
        SETUP_TIME DECIMAL(10,2) DEFAULT 0.00 NOT NULL,
        CYCLE_TIME DECIMAL(10,2) DEFAULT 0.00 NOT NULL,
        IS_ACTIVE BIT DEFAULT 1 NOT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME2 DEFAULT GETDATE() NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME2 NULL,
        
        CONSTRAINT PK_NPD_BOM_PROCESS PRIMARY KEY (ID),
        CONSTRAINT FK_NPD_BOM_PROCESS_BOM FOREIGN KEY (BOM_ID) REFERENCES dbo.NPD_BOM_MASTER(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_BOM_PROCESS_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES dbo.NPD_PROCESS(ID),
        CONSTRAINT FK_NPD_BOM_PROCESS_MACHINE FOREIGN KEY (PRIMARY_MACHINE_ID) REFERENCES dbo.QMT_ASSET_MASTER(ID),
        CONSTRAINT FK_NPD_BOM_PROCESS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_NPD_BOM_PROCESS_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_NPD_BOM_PROCESS_BOM ON dbo.NPD_BOM_PROCESS(BOM_ID);
END;
GO

-- 3. Create NPD_BOM_PROCESS_MATERIAL
IF OBJECT_ID('dbo.NPD_BOM_PROCESS_MATERIAL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NPD_BOM_PROCESS_MATERIAL (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        BOM_PROCESS_ID BIGINT NOT NULL,
        SEQ_NO INT NOT NULL,
        INPUT_PRODUCT_ID BIGINT NOT NULL,
        QUANTITY DECIMAL(18, 4) NOT NULL,
        CONSUMPTION_QTY DECIMAL(18, 4) NULL,
        FINISH_QTY DECIMAL(18, 4) NOT NULL,
        UOM NVARCHAR(50) NOT NULL,
        SCRAP_PERCENTAGE DECIMAL(5, 2) DEFAULT 0 NULL,
        BACKFLUSH BIT DEFAULT 1 NOT NULL,
        REMARKS NVARCHAR(255) NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME2 DEFAULT GETDATE() NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME2 NULL,
        
        CONSTRAINT PK_NPD_BOM_PROCESS_MATERIAL PRIMARY KEY (ID),
        CONSTRAINT FK_NPD_BOM_PROC_MAT_PROCESS FOREIGN KEY (BOM_PROCESS_ID) REFERENCES dbo.NPD_BOM_PROCESS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_BOM_PROC_MAT_PRODUCT FOREIGN KEY (INPUT_PRODUCT_ID) REFERENCES dbo.NPD_PRODUCT_MASTER(ID),
        CONSTRAINT FK_NPD_BOM_PROC_MAT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_NPD_BOM_PROC_MAT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_NPD_BOM_PROCESS_MATERIAL_PROCESS ON dbo.NPD_BOM_PROCESS_MATERIAL(BOM_PROCESS_ID);
END;
GO

-- 4. Create NPD_BOM_PROCESS_MACHINE
IF OBJECT_ID('dbo.NPD_BOM_PROCESS_MACHINE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NPD_BOM_PROCESS_MACHINE (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        BOM_PROCESS_ID BIGINT NOT NULL,
        MACHINE_ID BIGINT NOT NULL,
        CAPACITY NVARCHAR(100) NULL,
        EFFICIENCY DECIMAL(5,2) NULL,
        IS_PRIMARY BIT DEFAULT 0 NOT NULL,
        STATUS BIT DEFAULT 1 NOT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME2 DEFAULT GETDATE() NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME2 NULL,
        
        CONSTRAINT PK_NPD_BOM_PROCESS_MACHINE PRIMARY KEY (ID),
        CONSTRAINT FK_NPD_BOM_PROC_MAC_PROCESS FOREIGN KEY (BOM_PROCESS_ID) REFERENCES dbo.NPD_BOM_PROCESS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_BOM_PROC_MAC_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES dbo.QMT_ASSET_MASTER(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_BOM_PROC_MAC_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_NPD_BOM_PROC_MAC_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_NPD_BOM_PROCESS_MACHINE_PROCESS ON dbo.NPD_BOM_PROCESS_MACHINE(BOM_PROCESS_ID);
END;
GO

-- 5. Create NPD_BOM_PROCESS_TOOL
IF OBJECT_ID('dbo.NPD_BOM_PROCESS_TOOL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NPD_BOM_PROCESS_TOOL (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        BOM_PROCESS_ID BIGINT NOT NULL,
        SEQ_NO INT NOT NULL,
        TOOL_NAME NVARCHAR(200) NOT NULL,
        TOOL_CODE NVARCHAR(50) NULL,
        TOOL_TYPE NVARCHAR(100) NULL,
        QUANTITY DECIMAL(12,4) NULL,
        TOOL_LIFE INT NULL,
        USAGE_LIMIT INT NULL,
        UOM NVARCHAR(50) NULL,
        MANDATORY BIT DEFAULT 0 NOT NULL,
        REMARKS NVARCHAR(255) NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME2 DEFAULT GETDATE() NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME2 NULL,
        
        CONSTRAINT PK_NPD_BOM_PROCESS_TOOL PRIMARY KEY (ID),
        CONSTRAINT FK_NPD_BOM_PROC_TOOL_PROCESS FOREIGN KEY (BOM_PROCESS_ID) REFERENCES dbo.NPD_BOM_PROCESS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_BOM_PROC_TOOL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_NPD_BOM_PROC_TOOL_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_NPD_BOM_PROCESS_TOOL_PROCESS ON dbo.NPD_BOM_PROCESS_TOOL(BOM_PROCESS_ID);
END;
GO

-- 6. Create NPD_BOM_PROCESS_NORM
IF OBJECT_ID('dbo.NPD_BOM_PROCESS_NORM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NPD_BOM_PROCESS_NORM (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        BOM_PROCESS_ID BIGINT NOT NULL,
        PARAMETER_NAME NVARCHAR(100) NOT NULL,
        STANDARD_VALUE NVARCHAR(100) NULL,
        MIN_VALUE NVARCHAR(100) NULL,
        MAX_VALUE NVARCHAR(100) NULL,
        UOM NVARCHAR(50) NULL,
        MACHINE_ID BIGINT NULL,
        MANDATORY BIT DEFAULT 0 NOT NULL,
        REMARKS NVARCHAR(255) NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME2 DEFAULT GETDATE() NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME2 NULL,
        
        CONSTRAINT PK_NPD_BOM_PROCESS_NORM PRIMARY KEY (ID),
        CONSTRAINT FK_NPD_BOM_PROC_NORM_PROCESS FOREIGN KEY (BOM_PROCESS_ID) REFERENCES dbo.NPD_BOM_PROCESS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_BOM_PROC_NORM_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES dbo.QMT_ASSET_MASTER(ID),
        CONSTRAINT FK_NPD_BOM_PROC_NORM_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_NPD_BOM_PROC_NORM_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_NPD_BOM_PROCESS_NORM_PROCESS ON dbo.NPD_BOM_PROCESS_NORM(BOM_PROCESS_ID);
END;
GO

-- 7. Create NPD_BOM_PROCESS_QUALITY
IF OBJECT_ID('dbo.NPD_BOM_PROCESS_QUALITY', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NPD_BOM_PROCESS_QUALITY (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        BOM_PROCESS_ID BIGINT NOT NULL,
        INSPECTION_PARAMETER NVARCHAR(150) NOT NULL,
        SPECIFICATION NVARCHAR(255) NULL,
        TARGET_VALUE NVARCHAR(100) NULL,
        MIN_VALUE NVARCHAR(100) NULL,
        MAX_VALUE NVARCHAR(100) NULL,
        UOM NVARCHAR(50) NULL,
        INSPECTION_FREQUENCY NVARCHAR(100) NULL,
        MANDATORY BIT DEFAULT 0 NOT NULL,
        REACTION_PLAN NVARCHAR(500) NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME2 DEFAULT GETDATE() NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME2 NULL,
        
        CONSTRAINT PK_NPD_BOM_PROCESS_QUALITY PRIMARY KEY (ID),
        CONSTRAINT FK_NPD_BOM_PROC_QLY_PROCESS FOREIGN KEY (BOM_PROCESS_ID) REFERENCES dbo.NPD_BOM_PROCESS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_BOM_PROC_QLY_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_NPD_BOM_PROC_QLY_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_NPD_BOM_PROCESS_QUALITY_PROCESS ON dbo.NPD_BOM_PROCESS_QUALITY(BOM_PROCESS_ID);
END;
GO

-- 8. Register Page in BOS_PAGES
DECLARE @modId INT, @subModId INT;
SELECT TOP 1 @modId = MOD_ID, @subModId = SUB_MOD_ID FROM dbo.BOS_PAGES WHERE PAGE_CODE IN ('DD1112', 'DD1113');
IF @modId IS NULL OR @subModId IS NULL
BEGIN
    SELECT TOP 1 @modId = MOD_ID, @subModId = SUB_MOD_ID FROM dbo.BOS_PAGES WHERE PAGE_CODE LIKE 'DD%';
END;
IF @modId IS NULL OR @subModId IS NULL
BEGIN
    SET @modId = 1;
    SET @subModId = 1;
END;

IF NOT EXISTS (SELECT 1 FROM dbo.BOS_PAGES WHERE PAGE_CODE = 'DD1110')
BEGIN
    INSERT INTO dbo.BOS_PAGES (MOD_ID, SUB_MOD_ID, PAGE_CODE, PAGE_NAME, ENABLED, PAGE_URL, ICON)
    VALUES (@modId, @subModId, 'DD1110', 'Product BOM & Routing', 1, '/dd/product-bom', 'IconPackage');
    PRINT 'Page DD1110 (Product BOM & Routing) registered in BOS_PAGES.';
END;
ELSE
BEGIN
    UPDATE dbo.BOS_PAGES
    SET PAGE_NAME = 'Product BOM & Routing', ENABLED = 1, PAGE_URL = '/dd/product-bom', ICON = 'IconPackage'
    WHERE PAGE_CODE = 'DD1110';
    PRINT 'Page DD1110 updated in BOS_PAGES.';
END;
GO

-- 9. Seed default permissions based on Admin and existing DD pages
DECLARE @newPageId INT;
SELECT @newPageId = PAGE_ID FROM dbo.BOS_PAGES WHERE PAGE_CODE = 'DD1110';

IF @newPageId IS NOT NULL
BEGIN
    -- Grant to Admin user
    IF NOT EXISTS (SELECT 1 FROM dbo.BOS_USER_PAGE_AUTH WHERE PAGE_ID = @newPageId AND USER_ID = 'Admin')
    BEGIN
        INSERT INTO dbo.BOS_USER_PAGE_AUTH
            (USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, READ_ACS, WRITE, DELETE_ACS,
             EXPORT, APPROVAL, MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, CREATED_BY, CREATED_DATE)
        SELECT DISTINCT
            'Admin', @newPageId, SUB_MOD_ID, MOD_ID,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'SYSTEM', SYSDATETIME()
        FROM dbo.BOS_PAGES
        WHERE PAGE_ID = @newPageId;
    END;

    -- Grant to users who have access to other DD pages
    INSERT INTO dbo.BOS_USER_PAGE_AUTH
        (USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, READ_ACS, WRITE, DELETE_ACS,
         EXPORT, APPROVAL, MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, CREATED_BY, CREATED_DATE)
    SELECT DISTINCT
        auth.USER_ID, @newPageId, p.SUB_MOD_ID, p.MOD_ID,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'SYSTEM', SYSDATETIME()
    FROM dbo.BOS_USER_PAGE_AUTH auth
    INNER JOIN dbo.BOS_PAGES p ON p.PAGE_ID = @newPageId
    WHERE auth.PAGE_ID IN (SELECT PAGE_ID FROM dbo.BOS_PAGES WHERE PAGE_CODE IN ('DD1112', 'DD1113'))
      AND auth.USER_ID NOT IN (
          SELECT USER_ID FROM dbo.BOS_USER_PAGE_AUTH WHERE PAGE_ID = @newPageId
      );
    PRINT 'Access grants for DD1110 seeded.';
END;
GO
