-- Migration Script: Add FROM_WHERE column to HR_LEAVE_TRAVEL_DETAILS
-- Date: 2026-07-26

IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS') AND name = 'FROM_WHERE')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD FROM_WHERE VARCHAR(25) NULL;
        PRINT 'Added FROM_WHERE column to HR_LEAVE_TRAVEL_DETAILS successfully.';
    END
END
