-- SQL Migration script V1157.0: Create QMT_MACHINE_INTEGRATION_LOG Table

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QMT_MACHINE_INTEGRATION_LOG]') AND type in (N'U'))
BEGIN
    CREATE TABLE QMT_MACHINE_INTEGRATION_LOG (
        ID              BIGINT IDENTITY(1,1)    NOT NULL,
        MACHINE_ID_REF  BIGINT                  NOT NULL,
        OP_TYPE         NVARCHAR(10)            NOT NULL, -- 'READ' or 'SEND'
        RECORD_HASH     NVARCHAR(64)            NOT NULL,
        CREATED_DATE    DATETIME                NOT NULL DEFAULT GETDATE(),
        PRIMARY KEY (ID),
        CONSTRAINT FK_QMT_MACH_INT_LOG_MACH FOREIGN KEY (MACHINE_ID_REF) REFERENCES QMT_MACHINE(ID)
    );

    CREATE UNIQUE INDEX UQ_QMT_MACH_INT_LOG ON QMT_MACHINE_INTEGRATION_LOG(MACHINE_ID_REF, OP_TYPE, RECORD_HASH);
END
GO
