-- 20260623_V326.0__Delete_SC_Permission_Request_Table__TIS.sql
-- Purpose: Delete/Drop the redundant SC_PERMISSION_REQUEST table as requested.

-- USE [AUTONOMA];
-- GO

-- Drop foreign keys if they exist
IF OBJECT_ID('dbo.FK_SC_PERMISSION_REQUEST_PERMISSION_ENTRY', 'F') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST DROP CONSTRAINT FK_SC_PERMISSION_REQUEST_PERMISSION_ENTRY;

IF OBJECT_ID('dbo.FK_SC_PERMISSION_REQUEST_EMPLOYEE', 'F') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST DROP CONSTRAINT FK_SC_PERMISSION_REQUEST_EMPLOYEE;

IF OBJECT_ID('dbo.FK_SC_PERMISSION_REQUEST_CREATED_BY', 'F') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST DROP CONSTRAINT FK_SC_PERMISSION_REQUEST_CREATED_BY;

IF OBJECT_ID('dbo.FK_SC_PERMISSION_REQUEST_UPDATED_BY', 'F') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST DROP CONSTRAINT FK_SC_PERMISSION_REQUEST_UPDATED_BY;

IF OBJECT_ID('dbo.FK_SC_PERMISSION_REQUEST_APPROVED_BY', 'F') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST DROP CONSTRAINT FK_SC_PERMISSION_REQUEST_APPROVED_BY;

IF OBJECT_ID('dbo.FK_SC_PERMISSION_REQUEST_REJECTED_BY', 'F') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST DROP CONSTRAINT FK_SC_PERMISSION_REQUEST_REJECTED_BY;

IF OBJECT_ID('dbo.FK_SC_PERMISSION_REQUEST_VERIFIED_BY', 'F') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST DROP CONSTRAINT FK_SC_PERMISSION_REQUEST_VERIFIED_BY;
GO

-- Drop Table
IF OBJECT_ID('dbo.SC_PERMISSION_REQUEST', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.SC_PERMISSION_REQUEST;
    PRINT 'Dropped SC_PERMISSION_REQUEST table successfully.';
END
GO
