
-- 1. Create PP_PROCUREMENT_SCORE_CATEGORY table
CREATE TABLE PP_PROCUREMENT_SCORE_CATEGORY (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    DIVISION BIGINT NOT NULL,
    CODE NVARCHAR(50) NOT NULL,
    NAME NVARCHAR(100) NOT NULL,
    SEQUENCE INT DEFAULT 0,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    ACTIVE_STATUS INT DEFAULT 1,
    CONSTRAINT FK_PP_SCORE_CAT_DIVISION FOREIGN KEY (DIVISION) REFERENCES AD_DIVISION(ID),
    CONSTRAINT UQ_PP_SCORE_CAT_CODE UNIQUE (DIVISION, CODE)
);

-- 2. Create PP_PROCUREMENT_SCORING_RULES table
CREATE TABLE PP_PROCUREMENT_SCORING_RULES (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CATEGORY_ID BIGINT NOT NULL,
    RULE_CODE NVARCHAR(50) NOT NULL,
    DISPLAY_NAME NVARCHAR(100) NOT NULL,
    FORMULA_TYPE NVARCHAR(50) NOT NULL, -- LOWEST_IS_BEST, HIGHEST_IS_BEST, EXPRESSION
    FORMULA_EXPRESSION NVARCHAR(255),
    WEIGHT NUMERIC(5,2) NOT NULL DEFAULT 0,
    SEQUENCE INT DEFAULT 0,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    ACTIVE_STATUS INT DEFAULT 1,
    CONSTRAINT FK_PP_SCORE_RULE_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES PP_PROCUREMENT_SCORE_CATEGORY(ID),
    CONSTRAINT UQ_PP_SCORE_RULE_CODE UNIQUE (CATEGORY_ID, RULE_CODE)
);

-- 3. Create PP_QUOTE_COMPARISON_HEAD table
CREATE TABLE PP_QUOTE_COMPARISON_HEAD (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    COMPARISON_NO NVARCHAR(50) NOT NULL,
    VERSION INT NOT NULL DEFAULT 1,
    COMPARISON_DATE DATE NOT NULL,
    RFQ_ID BIGINT NOT NULL,
    STATUS_ID BIGINT NOT NULL,
    SNAPSHOT_DATE DATETIME,
    SNAPSHOT_BY BIGINT,
    SOURCE_RFQ_VERSION INT,
    SOURCE_NEGOTIATION_VERSION INT,
    SELECTION_TYPE NVARCHAR(50), -- ENTIRE_RFQ, ITEM_WISE
    OVERALL_RECOMMENDED_SUPPLIER_ID BIGINT,
    OVERALL_SELECTED_SUPPLIER_ID BIGINT,
    IS_MANUAL_OVERRIDE BIT DEFAULT 0,
    OVERRIDE_REASON NVARCHAR(1000),
    OVERRIDE_BY BIGINT,
    OVERRIDE_DATE DATETIME,
    APPROVAL_REMARKS NVARCHAR(1000),
    LOCKED_BY BIGINT,
    LOCKED_DATE DATETIME,
    APPROVAL_VERSION INT,
    APPROVAL_SEQUENCE INT,
    DIVISION BIGINT NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    ACTIVE_STATUS INT DEFAULT 1,
    CONSTRAINT FK_PP_COMP_HEAD_RFQ FOREIGN KEY (RFQ_ID) REFERENCES PP_RFQ_HEAD(ID),
    CONSTRAINT FK_PP_COMP_HEAD_STATUS FOREIGN KEY (STATUS_ID) REFERENCES AD_STATUS_MASTER(ID),
    CONSTRAINT FK_PP_COMP_HEAD_REC_SUP FOREIGN KEY (OVERALL_RECOMMENDED_SUPPLIER_ID) REFERENCES FA_ACCOUNT_LEDGER(ID),
    CONSTRAINT FK_PP_COMP_HEAD_SEL_SUP FOREIGN KEY (OVERALL_SELECTED_SUPPLIER_ID) REFERENCES FA_ACCOUNT_LEDGER(ID),
    CONSTRAINT FK_PP_COMP_HEAD_DIV FOREIGN KEY (DIVISION) REFERENCES AD_DIVISION(ID),
    CONSTRAINT UQ_PP_COMP_HEAD_NO_VER UNIQUE (COMPARISON_NO, VERSION)
);

-- 4. Create PP_QUOTE_COMPARISON_TRANS table
CREATE TABLE PP_QUOTE_COMPARISON_TRANS (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    COMPARISON_HEAD_ID BIGINT NOT NULL,
    RFQ_ITEM_ID BIGINT NOT NULL,
    SELECTED_SUPPLIER_ID BIGINT,
    SELECTED_QUOTATION_ID BIGINT,
    SELECTED_NEGOTIATION_ID BIGINT,
    AWARDED_PRICE NUMERIC(18,2),
    AWARDED_QTY NUMERIC(18,2),
    REMARKS NVARCHAR(1000),
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    ACTIVE_STATUS INT DEFAULT 1,
    CONSTRAINT FK_PP_COMP_TRANS_HEAD FOREIGN KEY (COMPARISON_HEAD_ID) REFERENCES PP_QUOTE_COMPARISON_HEAD(ID) ON DELETE CASCADE,
    CONSTRAINT FK_PP_COMP_TRANS_RFQ_ITEM FOREIGN KEY (RFQ_ITEM_ID) REFERENCES PP_PURCHASE_RFQ_TRANS(ID),
    CONSTRAINT FK_PP_COMP_TRANS_SEL_SUP FOREIGN KEY (SELECTED_SUPPLIER_ID) REFERENCES FA_ACCOUNT_LEDGER(ID),
    CONSTRAINT FK_PP_COMP_TRANS_SEL_QUO FOREIGN KEY (SELECTED_QUOTATION_ID) REFERENCES PP_QUOTATION_HEAD(ID),
    CONSTRAINT FK_PP_COMP_TRANS_SEL_NEG FOREIGN KEY (SELECTED_NEGOTIATION_ID) REFERENCES PP_QUOTATION_NEGOTIATION_HEAD(ID)
);

-- 5. Create PP_QUOTE_COMPARISON_MATRIX table
CREATE TABLE PP_QUOTE_COMPARISON_MATRIX (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    COMPARISON_HEAD_ID BIGINT NOT NULL,
    RFQ_ITEM_ID BIGINT NOT NULL,
    SUPPLIER_ID BIGINT NOT NULL,
    QUOTATION_ID BIGINT,
    NEGOTIATION_ID BIGINT,
    ORIGINAL_PRICE NUMERIC(18,2),
    NEGOTIATED_PRICE NUMERIC(18,2),
    DISCOUNT NUMERIC(18,2),
    TAX NUMERIC(18,2),
    FREIGHT NUMERIC(18,2),
    PACKING NUMERIC(18,2),
    DELIVERY_DAYS INT,
    WARRANTY NVARCHAR(100),
    PAYMENT_TERMS NVARCHAR(200),
    BRAND NVARCHAR(100),
    ORIGIN NVARCHAR(100),
    CURRENCY NVARCHAR(10),
    EXCHANGE_RATE NUMERIC(18,4),
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    ACTIVE_STATUS INT DEFAULT 1,
    CONSTRAINT FK_PP_COMP_MAT_HEAD FOREIGN KEY (COMPARISON_HEAD_ID) REFERENCES PP_QUOTE_COMPARISON_HEAD(ID) ON DELETE CASCADE,
    CONSTRAINT FK_PP_COMP_MAT_RFQ_ITEM FOREIGN KEY (RFQ_ITEM_ID) REFERENCES PP_PURCHASE_RFQ_TRANS(ID),
    CONSTRAINT FK_PP_COMP_MAT_SUP FOREIGN KEY (SUPPLIER_ID) REFERENCES FA_ACCOUNT_LEDGER(ID)
);

-- 6. Create PP_QUOTE_COMPARISON_SCORE table
CREATE TABLE PP_QUOTE_COMPARISON_SCORE (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    COMPARISON_HEAD_ID BIGINT NOT NULL,
    COMPARISON_MATRIX_ID BIGINT, -- Nullable because some scores might be overall per supplier
    SUPPLIER_ID BIGINT NOT NULL,
    SCORE_TYPE NVARCHAR(50) NOT NULL, -- RULE_SCORE, AGGREGATE
    RULE_CODE NVARCHAR(50),
    VALUE_NUMERIC NUMERIC(18,4),
    VALUE_TEXT NVARCHAR(500),
    VALUE_DATE DATETIME,
    VALUE_BOOLEAN BIT,
    APPLIED_WEIGHT NUMERIC(18,2),
    CALCULATED_SCORE NUMERIC(18,4),
    IS_LOWEST_PRICE BIT,
    IS_RECOMMENDED BIT,
    OVERALL_RANK INT,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    ACTIVE_STATUS INT DEFAULT 1,
    CONSTRAINT FK_PP_COMP_SCORE_HEAD FOREIGN KEY (COMPARISON_HEAD_ID) REFERENCES PP_QUOTE_COMPARISON_HEAD(ID) ON DELETE CASCADE,
    CONSTRAINT FK_PP_COMP_SCORE_MAT FOREIGN KEY (COMPARISON_MATRIX_ID) REFERENCES PP_QUOTE_COMPARISON_MATRIX(ID),
    CONSTRAINT FK_PP_COMP_SCORE_SUP FOREIGN KEY (SUPPLIER_ID) REFERENCES FA_ACCOUNT_LEDGER(ID)
);

-- 7. Create PP_QUOTE_COMPARISON_LOG table
CREATE TABLE PP_QUOTE_COMPARISON_LOG (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    COMPARISON_HEAD_ID BIGINT NOT NULL,
    EVENT_TYPE NVARCHAR(50) NOT NULL,
    EVENT_DESCRIPTION NVARCHAR(MAX),
    OLD_VALUE NVARCHAR(MAX),
    NEW_VALUE NVARCHAR(MAX),
    USER_ID BIGINT,
    EVENT_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    IP_ADDRESS NVARCHAR(50),
    SESSION_ID NVARCHAR(100),
    MESSAGE NVARCHAR(1000),
    ACTIVE_STATUS INT DEFAULT 1,
    CONSTRAINT FK_PP_COMP_LOG_HEAD FOREIGN KEY (COMPARISON_HEAD_ID) REFERENCES PP_QUOTE_COMPARISON_HEAD(ID) ON DELETE CASCADE
);

-- 8. Add Statuses
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'COMPARED')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME)
    VALUES ('COMPARED');
END

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'LOCKED')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME)
    VALUES ('LOCKED');
END


IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(NAME) = 'OPEN')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('OPEN');
END
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(NAME) = 'IN DISCUSSION')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('IN DISCUSSION');
END
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(NAME) = 'AGREED')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('AGREED');
END
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(NAME) = 'REJECTED')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('REJECTED');
END
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(NAME) = 'CLOSED')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('CLOSED');
END
