IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Pending for Verified')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Pending for Verified');
GO

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Accepted')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Accepted');
GO

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Rejected')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Rejected');
GO

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Created')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Created');
GO

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Unresolved')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Unresolved');
GO
