-- ============================================================
-- V379.0 : Seed HR_CATEGORY_MASTER with base employee categories
-- Required for Employee Master migration FK constraint
-- FK_HR_EMPLOYEE_ORGANIZATION_CATEGORY references HR_CATEGORY_MASTER
-- ============================================================

IF NOT EXISTS (SELECT 1 FROM HR_CATEGORY_MASTER WHERE ID = 1)
BEGIN
    SET IDENTITY_INSERT HR_CATEGORY_MASTER ON;
    INSERT INTO HR_CATEGORY_MASTER (ID, CATEGORY_NAME, CREATED_BY, CREATED_DATE)
    VALUES (1, 'Employee', 'SUPER BOSS', GETDATE());
    SET IDENTITY_INSERT HR_CATEGORY_MASTER OFF;
END

IF NOT EXISTS (SELECT 1 FROM HR_CATEGORY_MASTER WHERE ID = 2)
BEGIN
    SET IDENTITY_INSERT HR_CATEGORY_MASTER ON;
    INSERT INTO HR_CATEGORY_MASTER (ID, CATEGORY_NAME, CREATED_BY, CREATED_DATE)
    VALUES (2, 'Contractor', 'SUPER BOSS', GETDATE());
    SET IDENTITY_INSERT HR_CATEGORY_MASTER OFF;
END

IF NOT EXISTS (SELECT 1 FROM HR_CATEGORY_MASTER WHERE ID = 3)
BEGIN
    SET IDENTITY_INSERT HR_CATEGORY_MASTER ON;
    INSERT INTO HR_CATEGORY_MASTER (ID, CATEGORY_NAME, CREATED_BY, CREATED_DATE)
    VALUES (3, 'Consultant', 'SUPER BOSS', GETDATE());
    SET IDENTITY_INSERT HR_CATEGORY_MASTER OFF;
END

IF NOT EXISTS (SELECT 1 FROM HR_CATEGORY_MASTER WHERE UPPER(CATEGORY_NAME) = 'GENERAL')
BEGIN
    INSERT INTO HR_CATEGORY_MASTER (CATEGORY_NAME, CREATED_BY, CREATED_DATE)
    VALUES ('General', 'SUPER BOSS', GETDATE());
END
