-- Idempotent script to add SAME_AS_CURRENT_ADDRESS column to HR_EMPLOYEE_SELF_ASSESSMENT table

IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') 
    AND name = 'SAME_AS_CURRENT_ADDRESS'
)
BEGIN
    ALTER TABLE HR_EMPLOYEE_SELF_ASSESSMENT 
    ADD SAME_AS_CURRENT_ADDRESS VARCHAR(10) NULL;
END
GO
