-- Migration script to add CANCEL_REASON column to QMS_AUDIT_SCHEDULE table
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[QMS_AUDIT_SCHEDULE]') AND name = 'CANCEL_REASON')
BEGIN
    ALTER TABLE [dbo].[QMS_AUDIT_SCHEDULE] ADD CANCEL_REASON NVARCHAR(MAX) NULL;
END;
GO
