-- Migration: Add AQL_ID to NPD_ITEM_GROUP table
-- Date: 2026-08-24
IF COL_LENGTH('NPD_ITEM_GROUP', 'AQL_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[NPD_ITEM_GROUP] ADD [AQL_ID] [bigint] NULL;
END
GO

IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys 
    WHERE object_id = OBJECT_ID(N'[dbo].[FK_NPD_ITEM_GROUP_AQL]') 
    AND parent_object_id = OBJECT_ID(N'[dbo].[NPD_ITEM_GROUP]')
)
BEGIN
    ALTER TABLE [dbo].[NPD_ITEM_GROUP] WITH CHECK ADD CONSTRAINT [FK_NPD_ITEM_GROUP_AQL] FOREIGN KEY([AQL_ID])
    REFERENCES [dbo].[QMC_AQL_MASTER] ([ID]);
END
GO
