IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.AD_DIVISION') AND name = 'MAP_LINK')
BEGIN
    ALTER TABLE dbo.AD_DIVISION ADD MAP_LINK NVARCHAR(1000) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.AD_DIVISION') AND name = 'LATITUDE')
BEGIN
    ALTER TABLE dbo.AD_DIVISION ADD LATITUDE NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.AD_DIVISION') AND name = 'LONGITUDE')
BEGIN
    ALTER TABLE dbo.AD_DIVISION ADD LONGITUDE NVARCHAR(50) NULL;
END
