IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'OPEN')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('OPEN');
GO

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'CLOSED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('CLOSED');
GO

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'AUTO CLOSED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('AUTO CLOSED');
GO

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'CANCELLED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('CANCELLED');
GO

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'RESCHEDULE')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('RESCHEDULE');
GO

-- Fix existing meeting schedules that have NULL status
UPDATE QMS_MEETING_SCHEDULE 
SET STATUS = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'OPEN')
WHERE STATUS IS NULL;
GO
