IF OBJECT_ID('CLIENT_ESSL_CONFIG', 'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[CLIENT_ESSL_CONFIG] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [CLIENT_ID] NVARCHAR(50) NOT NULL,
        [CLIENT_NAME] NVARCHAR(200) NOT NULL,
        [JDBC_URL] NVARCHAR(500) NOT NULL,
        [USERNAME] NVARCHAR(100) NOT NULL,
        [PASSWORD] NVARCHAR(200) NOT NULL,
        [ESSL_TABLE_NAME] NVARCHAR(128) NOT NULL DEFAULT ('HRMS_BIOMETRIC_LOG'),
        [EMP_CD_COLUMN] NVARCHAR(64) NOT NULL DEFAULT ('EMP_CD'),
        [DATE_COLUMN] NVARCHAR(64) NOT NULL DEFAULT ('ATT_DATE'),
        [IN_TIME_COLUMN] NVARCHAR(64) NOT NULL DEFAULT ('IN_TIME'),
        [OUT_TIME_COLUMN] NVARCHAR(64) NOT NULL DEFAULT ('OUT_TIME'),
        [SYNC_MODE] NVARCHAR(20) NOT NULL DEFAULT ('MONTHLY'),
        [IS_ACTIVE] BIT NOT NULL DEFAULT ((1)),
        [CREATED_BY] NVARCHAR(50) NULL,
        [CREATED_DATE] DATETIME2 NULL DEFAULT (getdate()),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME2 NULL,
        CONSTRAINT [PK_CLIENT_ESSL_CONFIG] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [UQ_CLIENT_ESSL_CONFIG_CLIENT_ID] UNIQUE ([CLIENT_ID])
    );
END
GO
