-- 20260814_V1141.0__Add_Document_Details_To_Goods_Receipt.sql
-- Add Supplier Invoice / Delivery Challan Document Details

ALTER TABLE PP_GOODS_RECEIPT_HEAD
ADD DOCUMENT_TYPE NVARCHAR(50),
    DOCUMENT_NO NVARCHAR(100),
    DOCUMENT_DATE DATE,
    BILL_NO NVARCHAR(100),
    BILL_DATE DATE;

-- Create GRN Attachment Table
CREATE TABLE PP_GOODS_RECEIPT_ATTACHMENT (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    GOODS_RECEIPT_HEAD_ID BIGINT NOT NULL,
    FILE_NAME NVARCHAR(255) NOT NULL,
    FILE_PATH NVARCHAR(1000) NOT NULL,
    FILE_SIZE BIGINT,
    MIME_TYPE NVARCHAR(100),
    ATTACHMENT_TYPE NVARCHAR(50),
    ACTIVE_STATUS INT NOT NULL DEFAULT 1,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    FOREIGN KEY (GOODS_RECEIPT_HEAD_ID) REFERENCES PP_GOODS_RECEIPT_HEAD(ID)
);
