-- V1029.0: Remove UPDATED_BY and UPDATED_DATE columns from HR_LEAVE_APPLICATION

-- 1. Drop foreign key constraint if it exists
IF EXISTS (
    SELECT 1 FROM sys.foreign_keys 
    WHERE name = 'FK_HR_LEAVE_ENTRY_EMPLOYEE_ID' AND parent_object_id = OBJECT_ID('HR_LEAVE_APPLICATION')
)
BEGIN
    ALTER TABLE HR_LEAVE_APPLICATION DROP CONSTRAINT [FK_HR_LEAVE_ENTRY_EMPLOYEE_ID];
    PRINT 'Dropped foreign key constraint FK_HR_LEAVE_ENTRY_EMPLOYEE_ID';
END

-- 2. Drop columns
IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_LEAVE_APPLICATION' AND COLUMN_NAME = 'UPDATED_BY'
)
BEGIN
    ALTER TABLE HR_LEAVE_APPLICATION DROP COLUMN [UPDATED_BY];
    PRINT 'Dropped UPDATED_BY column';
END

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_LEAVE_APPLICATION' AND COLUMN_NAME = 'UPDATED_DATE'
)
BEGIN
    ALTER TABLE HR_LEAVE_APPLICATION DROP COLUMN [UPDATED_DATE];
    PRINT 'Dropped UPDATED_DATE column';
END
