-- Add missing Primary Keys to NPD tables

IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
    WHERE TABLE_NAME = 'NPD_ITEM_GROUP' 
    AND CONSTRAINT_TYPE = 'PRIMARY KEY'
)
BEGIN
    ALTER TABLE [dbo].[NPD_ITEM_GROUP] 
    ADD CONSTRAINT PK_NPD_ITEM_GROUP PRIMARY KEY ([GROUP_NAME]);
END
GO

IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
    WHERE TABLE_NAME = 'NPD_ITEM_SUBTYPE' 
    AND CONSTRAINT_TYPE = 'PRIMARY KEY'
)
BEGIN
    ALTER TABLE [dbo].[NPD_ITEM_SUBTYPE] 
    ADD CONSTRAINT PK_NPD_ITEM_SUBTYPE PRIMARY KEY ([SUB_TYPE]);
END
GO

IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
    WHERE TABLE_NAME = 'NPD_ITEM_TYPE' 
    AND CONSTRAINT_TYPE = 'PRIMARY KEY'
)
BEGIN
    ALTER TABLE [dbo].[NPD_ITEM_TYPE] 
    ADD CONSTRAINT PK_NPD_ITEM_TYPE PRIMARY KEY ([ITEM_TYPE]);
END
GO

IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
    WHERE TABLE_NAME = 'NPD_MATERIAL_CONDITIONS' 
    AND CONSTRAINT_TYPE = 'PRIMARY KEY'
)
BEGIN
    ALTER TABLE [dbo].[NPD_MATERIAL_CONDITIONS] 
    ADD CONSTRAINT PK_NPD_MATERIAL_CONDITIONS PRIMARY KEY ([CODE]);
END
GO

IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
    WHERE TABLE_NAME = 'NPD_MATERIAL_TYPE' 
    AND CONSTRAINT_TYPE = 'PRIMARY KEY'
)
BEGIN
    ALTER TABLE [dbo].[NPD_MATERIAL_TYPE] 
    ADD CONSTRAINT PK_NPD_MATERIAL_TYPE PRIMARY KEY ([CODE]);
END
GO
