-- Migration: Create HR_BANK_MASTER table for Payroll Bank Master
-- Date: 2026-08-12

IF OBJECT_ID('dbo.HR_BANK_MASTER', 'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[HR_BANK_MASTER] (
        [ROW_ID]               BIGINT IDENTITY(1,1) NOT NULL,
        [BANK_CODE]            NVARCHAR(20) NOT NULL,
        [BANK_NAME]            NVARCHAR(150) NOT NULL,
        [ACCOUNT_NO]           NVARCHAR(50) NOT NULL,
        [ACCOUNT_HOLDER_NAME]  NVARCHAR(150) NOT NULL,
        [IFSC_CODE]            NVARCHAR(20) NOT NULL,
        [BRANCH_NAME]          NVARCHAR(100) NULL,
        [BRANCH_LOCATION]      NVARCHAR(150) NULL,
        [ACCOUNT_TYPE]         NVARCHAR(50) NULL,
        [SWIFT_CODE]           NVARCHAR(30) NULL,
        [MICR_CODE]            NVARCHAR(30) NULL,
        [REMARKS]              NVARCHAR(500) NULL,
        [IS_ACTIVE]            BIT NOT NULL CONSTRAINT [DF_HR_BANK_MASTER_IS_ACTIVE] DEFAULT (1),
        [CREATED_BY]           NVARCHAR(50) NOT NULL,
        [CREATED_DATE]         DATETIME NOT NULL CONSTRAINT [DF_HR_BANK_MASTER_CREATED_DATE] DEFAULT (GETDATE()),
        [UPDATED_BY]           NVARCHAR(50) NULL,
        [UPDATED_DATE]         DATETIME NULL,
        CONSTRAINT [PK_HR_BANK_MASTER] PRIMARY KEY CLUSTERED ([ROW_ID] ASC),
        CONSTRAINT [UQ_HR_BANK_MASTER_BANK_CODE] UNIQUE ([BANK_CODE]),
        CONSTRAINT [UQ_HR_BANK_MASTER_ACCOUNT_NO] UNIQUE ([ACCOUNT_NO])
    );

    IF EXISTS (SELECT * FROM sys.tables WHERE name = 'AD_USER_CREDENTIAL')
    BEGIN
        IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_BANK_MASTER_CREATED_BY')
        BEGIN
            ALTER TABLE [dbo].[HR_BANK_MASTER] WITH CHECK ADD CONSTRAINT [FK_HR_BANK_MASTER_CREATED_BY]
            FOREIGN KEY ([CREATED_BY]) REFERENCES [dbo].[AD_USER_CREDENTIAL] ([USER_ID]);
        END

        IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_BANK_MASTER_UPDATED_BY')
        BEGIN
            ALTER TABLE [dbo].[HR_BANK_MASTER] WITH CHECK ADD CONSTRAINT [FK_HR_BANK_MASTER_UPDATED_BY]
            FOREIGN KEY ([UPDATED_BY]) REFERENCES [dbo].[AD_USER_CREDENTIAL] ([USER_ID]);
        END
    END
END;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_BANK_MASTER_SEARCH' AND object_id = OBJECT_ID('dbo.HR_BANK_MASTER'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_HR_BANK_MASTER_SEARCH]
    ON [dbo].[HR_BANK_MASTER] ([BANK_NAME], [ACCOUNT_NO], [IFSC_CODE], [IS_ACTIVE]);
END;
