-- SQL Migration to add COMPANY_ID and DIVISION_ID columns to AD_OCR_PROCESSING_REQUEST
IF OBJECT_ID('dbo.AD_OCR_PROCESSING_REQUEST', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.AD_OCR_PROCESSING_REQUEST') AND name = 'COMPANY_ID')
    BEGIN
        ALTER TABLE dbo.AD_OCR_PROCESSING_REQUEST ADD COMPANY_ID BIGINT;
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.AD_OCR_PROCESSING_REQUEST') AND name = 'DIVISION_ID')
    BEGIN
        ALTER TABLE dbo.AD_OCR_PROCESSING_REQUEST ADD DIVISION_ID BIGINT;
    END
END
GO
