-- =======================================================================================
-- MIGRATION SCRIPT: Create Enterprise Procurement Workflow and IQC Module
-- DB TYPE: Microsoft SQL Server
-- VERSION: 1094.0
-- =======================================================================================

-- 1. AD_STATUS_MASTER Updates
-- We need to ensure we have statuses like 'QUARANTINE', 'HOLD', 'REWORK', etc.
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'QUARANTINE')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('QUARANTINE');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'HOLD')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('HOLD');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'REWORK')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('REWORK');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'INSPECTION PENDING')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('INSPECTION PENDING');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'DEVIATION')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('DEVIATION');
GO

-- 2. PP_PROCUREMENT_WORKFLOW
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_PROCUREMENT_WORKFLOW')
BEGIN
    CREATE TABLE PP_PROCUREMENT_WORKFLOW (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        DIVISION_ID             BIGINT          NOT NULL,
        STEP_CODE               NVARCHAR(50)    NOT NULL,
        STEP_NAME               NVARCHAR(100)   NOT NULL,
        MODULE_NAME             NVARCHAR(100)   NOT NULL,
        SEQUENCE                INT             NOT NULL,
        MANDATORY               INT             NOT NULL DEFAULT 1,
        ENABLED                 INT             NOT NULL DEFAULT 1,
        SKIP_ALLOWED            INT             NOT NULL DEFAULT 0,
        NEXT_STEP               NVARCHAR(50)    NULL,
        ON_SUCCESS              NVARCHAR(50)    NULL,
        ON_FAILURE              NVARCHAR(50)    NULL,
        CONDITION_EXPRESSION    NVARCHAR(MAX)   NULL,
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_WF_DIV FOREIGN KEY (DIVISION_ID) REFERENCES AD_DIVISION(ID)
    );
END
GO

-- 3. PP_INSPECTION_POLICY
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INSPECTION_POLICY')
BEGIN
    CREATE TABLE PP_INSPECTION_POLICY (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        DIVISION_ID             BIGINT          NOT NULL,
        CODE                    NVARCHAR(50)    NOT NULL,
        NAME                    NVARCHAR(100)   NOT NULL,
        DESCRIPTION             NVARCHAR(500)   NULL,
        QC_REQUIRED             INT             NOT NULL DEFAULT 1,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_INSP_POL_DIV FOREIGN KEY (DIVISION_ID) REFERENCES AD_DIVISION(ID)
    );
END
GO

-- 4. ALTER NPD_PRODUCT_MASTER to link Inspection Policy
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NPD_PRODUCT_MASTER' AND COLUMN_NAME = 'INSPECTION_POLICY_ID')
BEGIN
    ALTER TABLE NPD_PRODUCT_MASTER ADD INSPECTION_POLICY_ID BIGINT NULL;
    ALTER TABLE NPD_PRODUCT_MASTER ADD CONSTRAINT FK_NPD_PROD_INSP_POL FOREIGN KEY (INSPECTION_POLICY_ID) REFERENCES PP_INSPECTION_POLICY(ID);
END
GO

-- 5. PP_INSPECTION_TEMPLATE
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INSPECTION_TEMPLATE')
BEGIN
    CREATE TABLE PP_INSPECTION_TEMPLATE (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        DIVISION_ID             BIGINT          NOT NULL,
        CODE                    NVARCHAR(50)    NOT NULL,
        NAME                    NVARCHAR(100)   NOT NULL,
        VERSION                 NVARCHAR(20)    NOT NULL DEFAULT '1.0',
        EFFECTIVE_FROM          DATE            NOT NULL,
        EFFECTIVE_TO            DATE            NULL,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_INSP_TMPL_DIV FOREIGN KEY (DIVISION_ID) REFERENCES AD_DIVISION(ID)
    );
END
GO

-- 6. PP_INSPECTION_TEMPLATE_DETAIL
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INSPECTION_TEMPLATE_DETAIL')
BEGIN
    CREATE TABLE PP_INSPECTION_TEMPLATE_DETAIL (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        TEMPLATE_ID             BIGINT          NOT NULL,
        PARAMETER_NAME          NVARCHAR(200)   NOT NULL,
        INSPECTION_TYPE         NVARCHAR(50)    NOT NULL, -- VISUAL, DIMENSIONAL, CHEMICAL
        EXPECTED_VALUE          NVARCHAR(500)   NULL,
        UOM_ID                  BIGINT          NULL,
        MIN_TOLERANCE           DECIMAL(18,4)   NULL,
        MAX_TOLERANCE           DECIMAL(18,4)   NULL,
        IS_MANDATORY            INT             NOT NULL DEFAULT 1,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_INSP_TMPLDTL_TMPL FOREIGN KEY (TEMPLATE_ID) REFERENCES PP_INSPECTION_TEMPLATE(ID) ON DELETE CASCADE
    );
END
GO

-- 7. PP_INCOMING_INSPECTION_HEAD
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_HEAD')
BEGIN
    CREATE TABLE PP_INCOMING_INSPECTION_HEAD (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        DIVISION_ID             BIGINT          NOT NULL,
        
        INSPECTION_NO           NVARCHAR(50)    NOT NULL,
        INSPECTION_DATE         DATE            NOT NULL,
        
        SUPPLIER_ID             BIGINT          NULL,
        DEPARTMENT_ID           BIGINT          NULL,
        INSPECTOR_ID            NVARCHAR(50)    NULL,
        
        STATUS_ID               BIGINT          NOT NULL,
        APPROVAL_VERSION        INT             NOT NULL DEFAULT 1,
        APPROVAL_SEQUENCE       INT             NOT NULL DEFAULT 0,
        
        REMARKS                 NVARCHAR(MAX)   NULL,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_IQC_HEAD_DIV   FOREIGN KEY (DIVISION_ID)   REFERENCES AD_DIVISION(ID),
        CONSTRAINT FK_PP_IQC_HEAD_SUPP  FOREIGN KEY (SUPPLIER_ID)   REFERENCES FA_ACCOUNT_LEDGER(ID),
        CONSTRAINT FK_PP_IQC_HEAD_DEPT  FOREIGN KEY (DEPARTMENT_ID) REFERENCES HR_DEPARTMENT(ID),
        CONSTRAINT FK_PP_IQC_HEAD_INSP  FOREIGN KEY (INSPECTOR_ID)  REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_PP_IQC_HEAD_STAT  FOREIGN KEY (STATUS_ID)     REFERENCES AD_STATUS_MASTER(ID)
    );
END
GO

-- 8. PP_INCOMING_INSPECTION_SOURCE
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_SOURCE')
BEGIN
    CREATE TABLE PP_INCOMING_INSPECTION_SOURCE (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        INSPECTION_HEAD_ID      BIGINT          NOT NULL,
        
        SOURCE_TYPE             NVARCHAR(50)    NOT NULL, -- PO, GATE_ENTRY, DIRECT_INWARD
        SOURCE_HEAD_ID          BIGINT          NOT NULL,
        SOURCE_DOCUMENT_NO      NVARCHAR(100)   NOT NULL,
        SOURCE_DOCUMENT_DATE    DATE            NULL,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_IQC_SRC_HEAD FOREIGN KEY (INSPECTION_HEAD_ID) REFERENCES PP_INCOMING_INSPECTION_HEAD(ID) ON DELETE CASCADE
    );
END
GO

-- 9. PP_INCOMING_INSPECTION_TRANS
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_TRANS')
BEGIN
    CREATE TABLE PP_INCOMING_INSPECTION_TRANS (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        INSPECTION_HEAD_ID      BIGINT          NOT NULL,
        
        SOURCE_ID               BIGINT          NULL,
        SOURCE_LINE_ID          BIGINT          NULL,
        
        ITEM_ID                 BIGINT          NOT NULL,
          UOM                     NVARCHAR(50)    NOT NULL,
        
        ORDER_QTY               DECIMAL(18,4)   NOT NULL DEFAULT 0,
        RECEIVED_QTY            DECIMAL(18,4)   NOT NULL DEFAULT 0,
        INSPECTED_QTY           DECIMAL(18,4)   NOT NULL DEFAULT 0,
        
        INSPECTION_POLICY_ID    BIGINT          NULL,
        INSPECTION_TEMPLATE_ID  BIGINT          NULL,
        
        REMARKS                 NVARCHAR(1000)  NULL,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_IQC_TRANS_HEAD FOREIGN KEY (INSPECTION_HEAD_ID) REFERENCES PP_INCOMING_INSPECTION_HEAD(ID) ON DELETE CASCADE,
        CONSTRAINT FK_PP_IQC_TRANS_SRC  FOREIGN KEY (SOURCE_ID)          REFERENCES PP_INCOMING_INSPECTION_SOURCE(ID),
        CONSTRAINT FK_PP_IQC_TRANS_ITEM FOREIGN KEY (ITEM_ID)            REFERENCES NPD_PRODUCT_MASTER(ID),
        CONSTRAINT FK_PP_IQC_TRANS_POL  FOREIGN KEY (INSPECTION_POLICY_ID) REFERENCES PP_INSPECTION_POLICY(ID),
        CONSTRAINT FK_PP_IQC_TRANS_TMPL FOREIGN KEY (INSPECTION_TEMPLATE_ID) REFERENCES PP_INSPECTION_TEMPLATE(ID)
    );
END
GO

-- 10. PP_INCOMING_INSPECTION_CHECKLIST
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_CHECKLIST')
BEGIN
    CREATE TABLE PP_INCOMING_INSPECTION_CHECKLIST (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        INSPECTION_TRANS_ID     BIGINT          NOT NULL,
        
        PARAMETER_NAME          NVARCHAR(200)   NOT NULL,
        INSPECTION_TYPE         NVARCHAR(50)    NOT NULL,
        EXPECTED_VALUE          NVARCHAR(500)   NULL,
        UOM_ID                  BIGINT          NULL,
        MIN_TOLERANCE           DECIMAL(18,4)   NULL,
        MAX_TOLERANCE           DECIMAL(18,4)   NULL,
        
        OBSERVED_VALUE          NVARCHAR(500)   NULL,
        IS_PASSED               INT             NOT NULL DEFAULT 0,
        
        REMARKS                 NVARCHAR(1000)  NULL,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_IQC_CHK_TRANS FOREIGN KEY (INSPECTION_TRANS_ID) REFERENCES PP_INCOMING_INSPECTION_TRANS(ID) ON DELETE CASCADE
    );
END
GO

-- 11. PP_INCOMING_INSPECTION_RESULT
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_RESULT')
BEGIN
    CREATE TABLE PP_INCOMING_INSPECTION_RESULT (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        INSPECTION_TRANS_ID     BIGINT          NOT NULL,
        
        ACCEPTED_QTY            DECIMAL(18,4)   NOT NULL DEFAULT 0,
        REJECTED_QTY            DECIMAL(18,4)   NOT NULL DEFAULT 0,
        HOLD_QTY                DECIMAL(18,4)   NOT NULL DEFAULT 0,
        QUARANTINE_QTY          DECIMAL(18,4)   NOT NULL DEFAULT 0,
        REWORK_QTY              DECIMAL(18,4)   NOT NULL DEFAULT 0,
        DEVIATION_QTY           DECIMAL(18,4)   NOT NULL DEFAULT 0,
        
        INSPECTION_DATE         DATETIME        NOT NULL,
        INSPECTOR_ID            NVARCHAR(50)    NULL,
        STATUS_ID               BIGINT          NOT NULL,
        
        REMARKS                 NVARCHAR(MAX)   NULL,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_IQC_RES_TRANS FOREIGN KEY (INSPECTION_TRANS_ID) REFERENCES PP_INCOMING_INSPECTION_TRANS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_PP_IQC_RES_STAT  FOREIGN KEY (STATUS_ID) REFERENCES AD_STATUS_MASTER(ID),
        CONSTRAINT FK_PP_IQC_RES_INSP  FOREIGN KEY (INSPECTOR_ID) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
GO

-- 12. PP_INCOMING_INSPECTION_LOG
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_LOG')
BEGIN
    CREATE TABLE PP_INCOMING_INSPECTION_LOG (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        INSPECTION_HEAD_ID      BIGINT          NOT NULL,
        
        ACTION_TYPE             NVARCHAR(50)    NOT NULL,
        REMARKS                 NVARCHAR(MAX)   NULL,
        IP_ADDRESS              NVARCHAR(50)    NULL,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_IQC_LOG_HEAD FOREIGN KEY (INSPECTION_HEAD_ID) REFERENCES PP_INCOMING_INSPECTION_HEAD(ID) ON DELETE CASCADE
    );
END
GO

-- 13. PP_INCOMING_INSPECTION_ATTACHMENT
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_ATTACHMENT')
BEGIN
    CREATE TABLE PP_INCOMING_INSPECTION_ATTACHMENT (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        INSPECTION_HEAD_ID      BIGINT          NOT NULL,
        
        FILE_NAME               NVARCHAR(200)   NOT NULL,
        FILE_PATH               NVARCHAR(500)   NOT NULL,
        FILE_TYPE               NVARCHAR(50)    NULL,
        DOCUMENT_TYPE           NVARCHAR(50)    NOT NULL,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_IQC_ATT_HEAD FOREIGN KEY (INSPECTION_HEAD_ID) REFERENCES PP_INCOMING_INSPECTION_HEAD(ID) ON DELETE CASCADE
    );
END
GO
