-- Claimed Version: V379.0
-- Description: Refactor Employee Ability file mappings to use HR_ATTACHMENT_PATH and drop legacy tables

-- 1. Migrate Auditor File Mapping
IF OBJECT_ID('HR_EMPLOYEE_AUDITOR_FILE_MAPPING', 'U') IS NOT NULL AND OBJECT_ID('HR_ATTACHMENT_PATH', 'U') IS NOT NULL
BEGIN
    INSERT INTO HR_ATTACHMENT_PATH (PAGE_CODE, REF_ID, DOC_TYPE, PATH, FILE_NAME, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, UPDATED_USER)
    SELECT
        'M2110' AS PAGE_CODE,
        EMPLOYEE_ID AS REF_ID,
        'AUDITOR' AS DOC_TYPE,
        FILE_PATH AS PATH,
        CASE 
            WHEN CHARINDEX('/', FILE_PATH) > 0 
            THEN SUBSTRING(FILE_PATH, LEN(FILE_PATH) - CHARINDEX('/', REVERSE(FILE_PATH)) + 2, LEN(FILE_PATH))
            ELSE FILE_PATH 
        END AS FILE_NAME,
        ISNULL(CREATED_BY, 'System') AS CREATED_BY,
        ISNULL(CREATED_DATE, GETDATE()) AS CREATED_DATE,
        UPDATED_BY,
        UPDATED_DATE,
        UPDATED_BY AS UPDATED_USER
    FROM HR_EMPLOYEE_AUDITOR_FILE_MAPPING m
    WHERE NOT EXISTS (
        SELECT 1 FROM HR_ATTACHMENT_PATH a
        WHERE a.PAGE_CODE = 'M2110' 
          AND a.REF_ID = m.EMPLOYEE_ID 
          AND a.DOC_TYPE = 'AUDITOR'
          AND a.PATH = m.FILE_PATH
    );
    PRINT 'Migrated auditor file mappings to HR_ATTACHMENT_PATH.';
END
GO

-- 2. Migrate Auditee File Mapping
IF OBJECT_ID('HR_EMPLOYEE_AUDITEE_FILE_MAPPING', 'U') IS NOT NULL AND OBJECT_ID('HR_ATTACHMENT_PATH', 'U') IS NOT NULL
BEGIN
    INSERT INTO HR_ATTACHMENT_PATH (PAGE_CODE, REF_ID, DOC_TYPE, PATH, FILE_NAME, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, UPDATED_USER)
    SELECT
        'M2110' AS PAGE_CODE,
        EMPLOYEE_ID AS REF_ID,
        'AUDITEE' AS DOC_TYPE,
        FILE_PATH AS PATH,
        CASE 
            WHEN CHARINDEX('/', FILE_PATH) > 0 
            THEN SUBSTRING(FILE_PATH, LEN(FILE_PATH) - CHARINDEX('/', REVERSE(FILE_PATH)) + 2, LEN(FILE_PATH))
            ELSE FILE_PATH 
        END AS FILE_NAME,
        ISNULL(CREATED_BY, 'System') AS CREATED_BY,
        ISNULL(CREATED_DATE, GETDATE()) AS CREATED_DATE,
        UPDATED_BY,
        UPDATED_DATE,
        UPDATED_BY AS UPDATED_USER
    FROM HR_EMPLOYEE_AUDITEE_FILE_MAPPING m
    WHERE NOT EXISTS (
        SELECT 1 FROM HR_ATTACHMENT_PATH a
        WHERE a.PAGE_CODE = 'M2110' 
          AND a.REF_ID = m.EMPLOYEE_ID 
          AND a.DOC_TYPE = 'AUDITEE'
          AND a.PATH = m.FILE_PATH
    );
    PRINT 'Migrated auditee file mappings to HR_ATTACHMENT_PATH.';
END
GO

-- 3. Migrate NCR Approver File Mapping
IF OBJECT_ID('HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING', 'U') IS NOT NULL AND OBJECT_ID('HR_ATTACHMENT_PATH', 'U') IS NOT NULL
BEGIN
    INSERT INTO HR_ATTACHMENT_PATH (PAGE_CODE, REF_ID, DOC_TYPE, PATH, FILE_NAME, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, UPDATED_USER)
    SELECT
        'M2110' AS PAGE_CODE,
        EMPLOYEE_ID AS REF_ID,
        'NCR_APPROVER' AS DOC_TYPE,
        FILE_PATH AS PATH,
        CASE 
            WHEN CHARINDEX('/', FILE_PATH) > 0 
            THEN SUBSTRING(FILE_PATH, LEN(FILE_PATH) - CHARINDEX('/', REVERSE(FILE_PATH)) + 2, LEN(FILE_PATH))
            ELSE FILE_PATH 
        END AS FILE_NAME,
        ISNULL(CREATED_BY, 'System') AS CREATED_BY,
        ISNULL(CREATED_DATE, GETDATE()) AS CREATED_DATE,
        UPDATED_BY,
        UPDATED_DATE,
        UPDATED_BY AS UPDATED_USER
    FROM HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING m
    WHERE NOT EXISTS (
        SELECT 1 FROM HR_ATTACHMENT_PATH a
        WHERE a.PAGE_CODE = 'M2110' 
          AND a.REF_ID = m.EMPLOYEE_ID 
          AND a.DOC_TYPE = 'NCR_APPROVER'
          AND a.PATH = m.FILE_PATH
    );
    PRINT 'Migrated ncr_approver file mappings to HR_ATTACHMENT_PATH.';
END
GO

-- 4. Migrate Task Verifier File Mapping
IF OBJECT_ID('HR_EMPLOYEE_TASK_VERIFIER_FILE_MAPPING', 'U') IS NOT NULL AND OBJECT_ID('HR_ATTACHMENT_PATH', 'U') IS NOT NULL
BEGIN
    INSERT INTO HR_ATTACHMENT_PATH (PAGE_CODE, REF_ID, DOC_TYPE, PATH, FILE_NAME, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, UPDATED_USER)
    SELECT
        'M2110' AS PAGE_CODE,
        EMPLOYEE_ID AS REF_ID,
        'TASK_VERIFIER' AS DOC_TYPE,
        FILE_PATH AS PATH,
        CASE 
            WHEN CHARINDEX('/', FILE_PATH) > 0 
            THEN SUBSTRING(FILE_PATH, LEN(FILE_PATH) - CHARINDEX('/', REVERSE(FILE_PATH)) + 2, LEN(FILE_PATH))
            ELSE FILE_PATH 
        END AS FILE_NAME,
        ISNULL(CREATED_BY, 'System') AS CREATED_BY,
        ISNULL(CREATED_DATE, GETDATE()) AS CREATED_DATE,
        UPDATED_BY,
        UPDATED_DATE,
        UPDATED_BY AS UPDATED_USER
    FROM HR_EMPLOYEE_TASK_VERIFIER_FILE_MAPPING m
    WHERE NOT EXISTS (
        SELECT 1 FROM HR_ATTACHMENT_PATH a
        WHERE a.PAGE_CODE = 'M2110' 
          AND a.REF_ID = m.EMPLOYEE_ID 
          AND a.DOC_TYPE = 'TASK_VERIFIER'
          AND a.PATH = m.FILE_PATH
    );
    PRINT 'Migrated task_verifier file mappings to HR_ATTACHMENT_PATH.';
END
GO

-- 5. Migrate Task Tester File Mapping
IF OBJECT_ID('HR_EMPLOYEE_TASK_TESTER_FILE_MAPPING', 'U') IS NOT NULL AND OBJECT_ID('HR_ATTACHMENT_PATH', 'U') IS NOT NULL
BEGIN
    INSERT INTO HR_ATTACHMENT_PATH (PAGE_CODE, REF_ID, DOC_TYPE, PATH, FILE_NAME, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, UPDATED_USER)
    SELECT
        'M2110' AS PAGE_CODE,
        EMPLOYEE_ID AS REF_ID,
        'TASK_TESTER' AS DOC_TYPE,
        FILE_PATH AS PATH,
        CASE 
            WHEN CHARINDEX('/', FILE_PATH) > 0 
            THEN SUBSTRING(FILE_PATH, LEN(FILE_PATH) - CHARINDEX('/', REVERSE(FILE_PATH)) + 2, LEN(FILE_PATH))
            ELSE FILE_PATH 
        END AS FILE_NAME,
        ISNULL(CREATED_BY, 'System') AS CREATED_BY,
        ISNULL(CREATED_DATE, GETDATE()) AS CREATED_DATE,
        UPDATED_BY,
        UPDATED_DATE,
        UPDATED_BY AS UPDATED_USER
    FROM HR_EMPLOYEE_TASK_TESTER_FILE_MAPPING m
    WHERE NOT EXISTS (
        SELECT 1 FROM HR_ATTACHMENT_PATH a
        WHERE a.PAGE_CODE = 'M2110' 
          AND a.REF_ID = m.EMPLOYEE_ID 
          AND a.DOC_TYPE = 'TASK_TESTER'
          AND a.PATH = m.FILE_PATH
    );
    PRINT 'Migrated task_tester file mappings to HR_ATTACHMENT_PATH.';
END
GO

-- 6. Migrate Chaired File Mapping
IF OBJECT_ID('HR_EMPLOYEE_CHAIRED_FILE_MAPPING', 'U') IS NOT NULL AND OBJECT_ID('HR_ATTACHMENT_PATH', 'U') IS NOT NULL
BEGIN
    INSERT INTO HR_ATTACHMENT_PATH (PAGE_CODE, REF_ID, DOC_TYPE, PATH, FILE_NAME, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, UPDATED_USER)
    SELECT
        'M2110' AS PAGE_CODE,
        EMPLOYEE_ID AS REF_ID,
        'CHAIRED' AS DOC_TYPE,
        FILE_PATH AS PATH,
        CASE 
            WHEN CHARINDEX('/', FILE_PATH) > 0 
            THEN SUBSTRING(FILE_PATH, LEN(FILE_PATH) - CHARINDEX('/', REVERSE(FILE_PATH)) + 2, LEN(FILE_PATH))
            ELSE FILE_PATH 
        END AS FILE_NAME,
        ISNULL(CREATED_BY, 'System') AS CREATED_BY,
        ISNULL(CREATED_DATE, GETDATE()) AS CREATED_DATE,
        UPDATED_BY,
        UPDATED_DATE,
        UPDATED_BY AS UPDATED_USER
    FROM HR_EMPLOYEE_CHAIRED_FILE_MAPPING m
    WHERE NOT EXISTS (
        SELECT 1 FROM HR_ATTACHMENT_PATH a
        WHERE a.PAGE_CODE = 'M2110' 
          AND a.REF_ID = m.EMPLOYEE_ID 
          AND a.DOC_TYPE = 'CHAIRED'
          AND a.PATH = m.FILE_PATH
    );
    PRINT 'Migrated chaired file mappings to HR_ATTACHMENT_PATH.';
END
GO

-- 7. Migrate Host File Mapping
IF OBJECT_ID('HR_EMPLOYEE_HOST_FILE_MAPPING', 'U') IS NOT NULL AND OBJECT_ID('HR_ATTACHMENT_PATH', 'U') IS NOT NULL
BEGIN
    INSERT INTO HR_ATTACHMENT_PATH (PAGE_CODE, REF_ID, DOC_TYPE, PATH, FILE_NAME, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, UPDATED_USER)
    SELECT
        'M2110' AS PAGE_CODE,
        EMPLOYEE_ID AS REF_ID,
        'HOST' AS DOC_TYPE,
        FILE_PATH AS PATH,
        CASE 
            WHEN CHARINDEX('/', FILE_PATH) > 0 
            THEN SUBSTRING(FILE_PATH, LEN(FILE_PATH) - CHARINDEX('/', REVERSE(FILE_PATH)) + 2, LEN(FILE_PATH))
            ELSE FILE_PATH 
        END AS FILE_NAME,
        ISNULL(CREATED_BY, 'System') AS CREATED_BY,
        ISNULL(CREATED_DATE, GETDATE()) AS CREATED_DATE,
        UPDATED_BY,
        UPDATED_DATE,
        UPDATED_BY AS UPDATED_USER
    FROM HR_EMPLOYEE_HOST_FILE_MAPPING m
    WHERE NOT EXISTS (
        SELECT 1 FROM HR_ATTACHMENT_PATH a
        WHERE a.PAGE_CODE = 'M2110' 
          AND a.REF_ID = m.EMPLOYEE_ID 
          AND a.DOC_TYPE = 'HOST'
          AND a.PATH = m.FILE_PATH
    );
    PRINT 'Migrated host file mappings to HR_ATTACHMENT_PATH.';
END
GO

-- 8. Migrate Participants File Mapping
IF OBJECT_ID('HR_EMPLOYEE_PARTICIPANTS_FILE_MAPPING', 'U') IS NOT NULL AND OBJECT_ID('HR_ATTACHMENT_PATH', 'U') IS NOT NULL
BEGIN
    INSERT INTO HR_ATTACHMENT_PATH (PAGE_CODE, REF_ID, DOC_TYPE, PATH, FILE_NAME, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, UPDATED_USER)
    SELECT
        'M2110' AS PAGE_CODE,
        EMPLOYEE_ID AS REF_ID,
        'PARTICIPANTS' AS DOC_TYPE,
        FILE_PATH AS PATH,
        CASE 
            WHEN CHARINDEX('/', FILE_PATH) > 0 
            THEN SUBSTRING(FILE_PATH, LEN(FILE_PATH) - CHARINDEX('/', REVERSE(FILE_PATH)) + 2, LEN(FILE_PATH))
            ELSE FILE_PATH 
        END AS FILE_NAME,
        ISNULL(CREATED_BY, 'System') AS CREATED_BY,
        ISNULL(CREATED_DATE, GETDATE()) AS CREATED_DATE,
        UPDATED_BY,
        UPDATED_DATE,
        UPDATED_BY AS UPDATED_USER
    FROM HR_EMPLOYEE_PARTICIPANTS_FILE_MAPPING m
    WHERE NOT EXISTS (
        SELECT 1 FROM HR_ATTACHMENT_PATH a
        WHERE a.PAGE_CODE = 'M2110' 
          AND a.REF_ID = m.EMPLOYEE_ID 
          AND a.DOC_TYPE = 'PARTICIPANTS'
          AND a.PATH = m.FILE_PATH
    );
    PRINT 'Migrated participants file mappings to HR_ATTACHMENT_PATH.';
END
GO

-- 9. Drop the redundant mapping tables
IF OBJECT_ID('HR_EMPLOYEE_AUDITOR_FILE_MAPPING', 'U') IS NOT NULL
BEGIN
    DROP TABLE HR_EMPLOYEE_AUDITOR_FILE_MAPPING;
    PRINT 'Dropped redundant HR_EMPLOYEE_AUDITOR_FILE_MAPPING table.';
END
GO

IF OBJECT_ID('HR_EMPLOYEE_AUDITEE_FILE_MAPPING', 'U') IS NOT NULL
BEGIN
    DROP TABLE HR_EMPLOYEE_AUDITEE_FILE_MAPPING;
    PRINT 'Dropped redundant HR_EMPLOYEE_AUDITEE_FILE_MAPPING table.';
END
GO

IF OBJECT_ID('HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING', 'U') IS NOT NULL
BEGIN
    DROP TABLE HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING;
    PRINT 'Dropped redundant HR_EMPLOYEE_NCR_APPROVER_FILE_MAPPING table.';
END
GO

IF OBJECT_ID('HR_EMPLOYEE_TASK_VERIFIER_FILE_MAPPING', 'U') IS NOT NULL
BEGIN
    DROP TABLE HR_EMPLOYEE_TASK_VERIFIER_FILE_MAPPING;
    PRINT 'Dropped redundant HR_EMPLOYEE_TASK_VERIFIER_FILE_MAPPING table.';
END
GO

IF OBJECT_ID('HR_EMPLOYEE_TASK_TESTER_FILE_MAPPING', 'U') IS NOT NULL
BEGIN
    DROP TABLE HR_EMPLOYEE_TASK_TESTER_FILE_MAPPING;
    PRINT 'Dropped redundant HR_EMPLOYEE_TASK_TESTER_FILE_MAPPING table.';
END
GO

IF OBJECT_ID('HR_EMPLOYEE_CHAIRED_FILE_MAPPING', 'U') IS NOT NULL
BEGIN
    DROP TABLE HR_EMPLOYEE_CHAIRED_FILE_MAPPING;
    PRINT 'Dropped redundant HR_EMPLOYEE_CHAIRED_FILE_MAPPING table.';
END
GO

IF OBJECT_ID('HR_EMPLOYEE_HOST_FILE_MAPPING', 'U') IS NOT NULL
BEGIN
    DROP TABLE HR_EMPLOYEE_HOST_FILE_MAPPING;
    PRINT 'Dropped redundant HR_EMPLOYEE_HOST_FILE_MAPPING table.';
END
GO

IF OBJECT_ID('HR_EMPLOYEE_PARTICIPANTS_FILE_MAPPING', 'U') IS NOT NULL
BEGIN
    DROP TABLE HR_EMPLOYEE_PARTICIPANTS_FILE_MAPPING;
    PRINT 'Dropped redundant HR_EMPLOYEE_PARTICIPANTS_FILE_MAPPING table.';
END
GO
