-- Create ITEM_TRANSACTION table
IF OBJECT_ID('dbo.ITEM_TRANSACTION', 'U') IS NOT NULL
    DROP TABLE dbo.ITEM_TRANSACTION;
GO

CREATE TABLE ITEM_TRANSACTION (
    ID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TRANS_CATEGORY nvarchar(10) NOT NULL, -- STOCK, REJECTION, SCRAP, REWORK
    INVENTORY_TYPE nvarchar(50) NOT NULL, -- FK to ITEM_TRANSACTION_TYPE.TYPE
    PRODUCT_ID bigint NOT NULL, -- FK to NPD_PRODUCT_MASTER
    TRANS_DATE date NOT NULL,
    TRANS_NO nvarchar(50) NOT NULL,
    TRANS_TYPE nvarchar(50) NOT NULL, -- FK to ITEM_TRANSACTION_TYPE
    REFERENCE_NO nvarchar(50), -- e.g. GRN-1001, SO-2001, MO-3001
    QTY_IN numeric(18,3) DEFAULT 0,
    QTY_OUT numeric(18,3) DEFAULT 0,
    PRICE numeric(18,2) DEFAULT 0,
    UOM nvarchar(10),
    BATCH_ID nvarchar(50),
    VENDOR_ID bigint,
    REMARKS nvarchar(200),
    DIVISION_ID bigint NOT NULL,
    CREATED_BY nvarchar(50),
    CREATED_DATE datetime,
    UPDATED_BY nvarchar(50),
    UPDATED_DATE datetime
);
GO

-- Add Foreign Key Constraints (Optional depending on if DB supports strict constraints here, but following standard relational design)
ALTER TABLE ITEM_TRANSACTION 
ADD CONSTRAINT FK_ITEM_TRANS_PRODUCT 
FOREIGN KEY (PRODUCT_ID) REFERENCES NPD_PRODUCT_MASTER(ID);
GO

-- INVENTORY_TYPE and TRANS_TYPE refer to ITEM_TRANSACTION_TYPE table's TYPE column, which is unique.
ALTER TABLE ITEM_TRANSACTION 
ADD CONSTRAINT FK_ITEM_TRANS_INV_TYPE 
FOREIGN KEY (INVENTORY_TYPE) REFERENCES ITEM_TRANSACTION_TYPE(TYPE);
GO

ALTER TABLE ITEM_TRANSACTION 
ADD CONSTRAINT FK_ITEM_TRANS_TRANS_TYPE 
FOREIGN KEY (TRANS_TYPE) REFERENCES ITEM_TRANSACTION_TYPE(TYPE);
GO

-- Indexes for Reports Performance
CREATE INDEX IX_ITEM_TRANSACTION_DIVISION_PRODUCT ON ITEM_TRANSACTION(DIVISION_ID, PRODUCT_ID);
CREATE INDEX IX_ITEM_TRANSACTION_CATEGORY ON ITEM_TRANSACTION(TRANS_CATEGORY);
CREATE INDEX IX_ITEM_TRANSACTION_DATE ON ITEM_TRANSACTION(TRANS_DATE);
GO
