-- ===================================================================================
-- Migration: 20260721_V1045.0__Enhance_Leave_Config_And_Leave_Master.sql
-- Module: HR / Attendance & Leave Management
-- Purpose: Enhance HR_LEAVE_CONFIG schema for enterprise leave policy parameters,
--          backfill REF_NO in HR_LEAVE_MASTER, and cap excessive Earned Leave (EL) balances.
-- ===================================================================================

-- 1. Enhance HR_LEAVE_CONFIG table schema idempotently
IF COL_LENGTH('HR_LEAVE_CONFIG', 'LEAVE_CODE') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD LEAVE_CODE VARCHAR(50) NULL;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'LEAVE_NAME') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD LEAVE_NAME VARCHAR(100) NULL;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'ANNUAL_QUOTA') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD ANNUAL_QUOTA DECIMAL(18,2) DEFAULT 0.00;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'MONTHLY_CREDIT_RATE') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD MONTHLY_CREDIT_RATE DECIMAL(18,2) DEFAULT 0.00;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'ACCRUAL_FREQUENCY') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD ACCRUAL_FREQUENCY VARCHAR(50) DEFAULT 'MONTHLY';

IF COL_LENGTH('HR_LEAVE_CONFIG', 'ALLOW_CARRY_FORWARD') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD ALLOW_CARRY_FORWARD BIT DEFAULT 0;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'MAX_CARRY_FORWARD_DAYS') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD MAX_CARRY_FORWARD_DAYS DECIMAL(18,2) DEFAULT 0.00;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'CARRY_FORWARD_EXPIRY_MONTHS') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD CARRY_FORWARD_EXPIRY_MONTHS INT DEFAULT 12;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'ALLOW_ENCASHMENT') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD ALLOW_ENCASHMENT BIT DEFAULT 0;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'MIN_BALANCE_TO_RETAIN') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD MIN_BALANCE_TO_RETAIN DECIMAL(18,2) DEFAULT 0.00;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'MAX_ENCASHABLE_DAYS') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD MAX_ENCASHABLE_DAYS DECIMAL(18,2) DEFAULT 0.00;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'GENDER_ELIGIBILITY') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD GENDER_ELIGIBILITY VARCHAR(20) DEFAULT 'ALL';

IF COL_LENGTH('HR_LEAVE_CONFIG', 'PROBATION_ALLOWED') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD PROBATION_ALLOWED BIT DEFAULT 1;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'MIN_SERVICE_MONTHS') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD MIN_SERVICE_MONTHS INT DEFAULT 0;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'SANDWICH_RULE_APPLIES') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD SANDWICH_RULE_APPLIES BIT DEFAULT 0;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'INCLUDE_WEEKENDS') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD INCLUDE_WEEKENDS BIT DEFAULT 0;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'INCLUDE_HOLIDAYS') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD INCLUDE_HOLIDAYS BIT DEFAULT 0;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'MAX_CONSECUTIVE_DAYS') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD MAX_CONSECUTIVE_DAYS INT DEFAULT 30;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'ALLOW_HALF_DAY') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD ALLOW_HALF_DAY BIT DEFAULT 1;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'ALLOW_HOURLY') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD ALLOW_HOURLY BIT DEFAULT 0;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'APPROVAL_LEVELS') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD APPROVAL_LEVELS INT DEFAULT 1;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'DOCUMENT_REQUIRED') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD DOCUMENT_REQUIRED BIT DEFAULT 0;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'DOCUMENT_THRESHOLD_DAYS') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD DOCUMENT_THRESHOLD_DAYS INT DEFAULT 3;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'AUTO_CREDIT_POLICY') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD AUTO_CREDIT_POLICY VARCHAR(50) DEFAULT 'WORKING_DAYS_20';

IF COL_LENGTH('HR_LEAVE_CONFIG', 'ALLOW_NEGATIVE_BALANCE') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD ALLOW_NEGATIVE_BALANCE BIT DEFAULT 0;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'EFFECTIVE_FROM_DATE') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD EFFECTIVE_FROM_DATE DATE NULL;

IF COL_LENGTH('HR_LEAVE_CONFIG', 'EFFECTIVE_TO_DATE') IS NULL
    ALTER TABLE HR_LEAVE_CONFIG ADD EFFECTIVE_TO_DATE DATE NULL;
GO

-- 2. Populate LEAVE_CODE and LEAVE_NAME for existing rows if null
IF COL_LENGTH('HR_LEAVE_CONFIG', 'LEAVE_CODE') IS NOT NULL
BEGIN
    EXEC('UPDATE HR_LEAVE_CONFIG SET LEAVE_CODE = LEAVE_TYPE, LEAVE_NAME = LEAVE_TYPE WHERE LEAVE_CODE IS NULL;');
END
GO

-- 3. Backfill REF_NO in HR_LEAVE_MASTER for all rows where REF_NO IS NULL or empty
IF COL_LENGTH('HR_LEAVE_MASTER', 'REF_NO') IS NOT NULL
BEGIN
    EXEC('UPDATE lm SET lm.REF_NO = ''LM/'' + ISNULL(emp.EMP_CODE, CAST(lm.EMPLOYEE_ID AS VARCHAR(50))) FROM HR_LEAVE_MASTER lm INNER JOIN HR_EMPLOYEE emp ON lm.EMPLOYEE_ID = emp.ID WHERE lm.REF_NO IS NULL OR TRIM(lm.REF_NO) = '''';');
END
GO

