-- DB Script for adding External Email and Mobile No to QMS_AUDIT_SCHEDULE

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = N'EXTERNAL_EMAIL_ID' AND Object_ID = Object_ID(N'dbo.QMS_AUDIT_SCHEDULE'))
BEGIN
    ALTER TABLE dbo.QMS_AUDIT_SCHEDULE ADD EXTERNAL_EMAIL_ID NVARCHAR(200);
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = N'EXTERNAL_MOBILE_NO' AND Object_ID = Object_ID(N'dbo.QMS_AUDIT_SCHEDULE'))
BEGIN
    ALTER TABLE dbo.QMS_AUDIT_SCHEDULE ADD EXTERNAL_MOBILE_NO NVARCHAR(50);
END
GO
