-- ============================================================================
-- V1130.0 -- Add Defensive Composite and Covering Performance Indexes Across All Dashboard Modules
-- Date: 2026-08-08
-- Purpose: Add non-clustered indexes for Audit, Checklist, ATS, HR, Sales,
--          OCR, and Permissions tables to optimize User Task Queue Dashboard
--          query execution without changing any application business logic.
-- ============================================================================

-- 1. AUDIT MODULE INDEXES
IF OBJECT_ID('dbo.QMS_AUDIT_SCHEDULE', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_AUDIT_SCHEDULE') AND name = 'IX_QMS_AUDIT_SCHEDULE_DATE_STATUS')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_AUDIT_SCHEDULE_DATE_STATUS
    ON [dbo].[QMS_AUDIT_SCHEDULE] ([SCHEDULE_DATE])
    INCLUDE ([AUDITEE_ID], [AUDITOR_ID], [NCR_APPROVED_BY_ID], [UPDATED_DATE]);
END
GO

IF OBJECT_ID('dbo.QMS_NCR_REWORK_LOG', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_NCR_REWORK_LOG') AND name = 'IX_QMS_NCR_REWORK_LOG_CREATED_DETAIL')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_NCR_REWORK_LOG_CREATED_DETAIL
    ON [dbo].[QMS_NCR_REWORK_LOG] ([CREATED_DATE])
    INCLUDE ([OBSERVATION_DETAIL_ID], [UPDATED_DATE]);
END
GO

IF OBJECT_ID('dbo.QMS_AUDIT_OBSERVATION_DETAIL', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_AUDIT_OBSERVATION_DETAIL') AND name = 'IX_QMS_AUDIT_OBSERVATION_DETAIL_STATUS_TARGET')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_AUDIT_OBSERVATION_DETAIL_STATUS_TARGET
    ON [dbo].[QMS_AUDIT_OBSERVATION_DETAIL] ([TARGET_DATE])
    INCLUDE ([OBSERVATION_ID], [NCR_STATUS]);
END
GO

IF OBJECT_ID('dbo.QMS_AUDIT_OBSERVATION', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_AUDIT_OBSERVATION') AND name = 'IX_QMS_AUDIT_OBSERVATION_SCHEDULE_NO')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_AUDIT_OBSERVATION_SCHEDULE_NO
    ON [dbo].[QMS_AUDIT_OBSERVATION] ([AUDIT_SCHEDULE_NO]);
END
GO

IF OBJECT_ID('dbo.QMS_NCR_OFI_MASTER', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_NCR_OFI_MASTER') AND name = 'IX_QMS_NCR_OFI_MASTER_APPROVAL_STATUS_DATE')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_NCR_OFI_MASTER_APPROVAL_STATUS_DATE
    ON [dbo].[QMS_NCR_OFI_MASTER] ([APPROVAL_STATUS])
    INCLUDE ([OBSERVATION_DETAIL_ID], [OBSERVATION_DATE]);
END
GO

-- 2. CHECKLIST MODULE INDEXES
IF OBJECT_ID('dbo.QMS_CHECKLIST_MASTER', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_CHECKLIST_MASTER') AND name = 'IX_QMS_CHECKLIST_MASTER_STATUS_VERIFY')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CHECKLIST_MASTER_STATUS_VERIFY
    ON [dbo].[QMS_CHECKLIST_MASTER] ([STATUS])
    INCLUDE ([VERIFY_STATUS], [PRIMARY_EMPLOYEE_ID], [SECONDARY_EMPLOYEE_ID], [TERTIARY_EMPLOYEE_ID]);
END
GO

IF OBJECT_ID('dbo.QMS_CHECKLIST_CLOSED', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED') AND name = 'IX_QMS_CHECKLIST_CLOSED_DATE_STATUS_ID')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CHECKLIST_CLOSED_DATE_STATUS_ID
    ON [dbo].[QMS_CHECKLIST_CLOSED] ([CHECKLIST_DATE])
    INCLUDE ([ASSIGNED_TO], [CHECKLIST_ID], [STATUS_ID], [UPDATED_DATE]);
END
GO

IF OBJECT_ID('dbo.QMS_CHECKLIST_ACKNOWLEDGEMENT', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ACKNOWLEDGEMENT') AND name = 'IX_QMS_CHECKLIST_ACK_STATUS_ASSIGNEES')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CHECKLIST_ACK_STATUS_ASSIGNEES
    ON [dbo].[QMS_CHECKLIST_ACKNOWLEDGEMENT] ([ACK_STATUS])
    INCLUDE ([NEW_ASSIGNEE_ID], [OLD_ASSIGNEE_ID], [REASSIGNED_BY], [CREATED_BY]);
END
GO

-- 3. HR & ATS MODULE INDEXES
IF OBJECT_ID('dbo.HR_LEAVE_DETAILS', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('HR_LEAVE_DETAILS') AND name = 'IX_HR_LEAVE_DETAILS_DATE_VERIFIED')
BEGIN
    CREATE NONCLUSTERED INDEX IX_HR_LEAVE_DETAILS_DATE_VERIFIED
    ON [dbo].[HR_LEAVE_DETAILS] ([FROM_DATE])
    INCLUDE ([VERIFIED_BY], [EMPLOYEE_ID], [REJECT_REASON]);
END
GO

IF OBJECT_ID('dbo.HR_LOAN_APPLICATION', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('HR_LOAN_APPLICATION') AND name = 'IX_HR_LOAN_APPLICATION_STATUS_EMP')
BEGIN
    CREATE NONCLUSTERED INDEX IX_HR_LOAN_APPLICATION_STATUS_EMP
    ON [dbo].[HR_LOAN_APPLICATION] ([EMP_CODE])
    INCLUDE ([STATUS]);
END
GO

IF OBJECT_ID('dbo.HR_PERMISSION_DETAILS', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('HR_PERMISSION_DETAILS') AND name = 'IX_HR_PERMISSION_DETAILS_DATE_STATUS')
BEGIN
    CREATE NONCLUSTERED INDEX IX_HR_PERMISSION_DETAILS_DATE_STATUS
    ON [dbo].[HR_PERMISSION_DETAILS] ([PERMISSION_DATE])
    INCLUDE ([EMPLOYEE_ID]);
END
GO

IF OBJECT_ID('dbo.HR_OD_DETAILS', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('HR_OD_DETAILS') AND name = 'IX_HR_OD_DETAILS_EMP_WHERE')
BEGIN
    CREATE NONCLUSTERED INDEX IX_HR_OD_DETAILS_EMP_WHERE
    ON [dbo].[HR_OD_DETAILS] ([EMPLOYEE_ID])
    INCLUDE ([FROM_WHERE]);
END
GO

IF OBJECT_ID('dbo.HR_APPLICANT_INTERVIEW', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('HR_APPLICANT_INTERVIEW') AND name = 'IX_HR_APPLICANT_INTERVIEW_DATE_STATUS')
BEGIN
    CREATE NONCLUSTERED INDEX IX_HR_APPLICANT_INTERVIEW_DATE_STATUS
    ON [dbo].[HR_APPLICANT_INTERVIEW] ([INTERVIEW_DATE])
    INCLUDE ([INTERVIEWER_ID]);
END
GO

-- 4. SALES, OCR & PERMISSION INDEXES
IF OBJECT_ID('dbo.SLS_QUOTATION_HEADER', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('SLS_QUOTATION_HEADER') AND name = 'IX_SLS_QUOTATION_HEADER_DATE_STATUS')
BEGIN
    CREATE NONCLUSTERED INDEX IX_SLS_QUOTATION_HEADER_DATE_STATUS
    ON [dbo].[SLS_QUOTATION_HEADER] ([QUOTATION_DATE])
    INCLUDE ([CREATED_BY]);
END
GO

IF OBJECT_ID('dbo.SLS_ENQUIRY', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'IX_SLS_ENQUIRY_DATE_CREATED')
BEGIN
    CREATE NONCLUSTERED INDEX IX_SLS_ENQUIRY_DATE_CREATED
    ON [dbo].[SLS_ENQUIRY] ([ENQUIRY_DATE], [CREATED_BY]);
END
GO

IF OBJECT_ID('dbo.AD_OCR_PROCESSING_REQUEST', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('AD_OCR_PROCESSING_REQUEST') AND name = 'IX_AD_OCR_PROCESSING_REQUEST_STATUS_CREATED')
BEGIN
    CREATE NONCLUSTERED INDEX IX_AD_OCR_PROCESSING_REQUEST_STATUS_CREATED
    ON [dbo].[AD_OCR_PROCESSING_REQUEST] ([STATUS], [CREATED_BY]);
END
GO

IF OBJECT_ID('dbo.BOS_USER_PAGE_AUTH', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('BOS_USER_PAGE_AUTH') AND name = 'IX_BOS_USER_PAGE_AUTH_USER_PAGE')
BEGIN
    CREATE NONCLUSTERED INDEX IX_BOS_USER_PAGE_AUTH_USER_PAGE
    ON [dbo].[BOS_USER_PAGE_AUTH] ([USER_ID], [PAGE_ID])
    INCLUDE ([ENABLE], [ADD_TASK_ENABLE], [READ_ACS]);
END
GO

IF OBJECT_ID('dbo.BOS_PAGES', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('BOS_PAGES') AND name = 'IX_BOS_PAGES_CODE_ENABLED')
BEGIN
    CREATE NONCLUSTERED INDEX IX_BOS_PAGES_CODE_ENABLED
    ON [dbo].[BOS_PAGES] ([PAGE_CODE])
    INCLUDE ([PAGE_ID], [ENABLED]);
END
GO
