-- Create QMS_AUDIT_SCHEDULE_LOG table for Audit Schedule Reschedule Audit Log
IF OBJECT_ID('[dbo].[QMS_AUDIT_SCHEDULE_LOG]', 'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[QMS_AUDIT_SCHEDULE_LOG] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [SCHEDULE_ID] BIGINT NOT NULL,
        [SCHEDULE_NO] NVARCHAR(255) NOT NULL,
        [PREV_AUDIT_DATE] DATE NULL,
        [NEW_AUDIT_DATE] DATE NULL,
        [PREV_START_TIME] NVARCHAR(50) NULL,
        [NEW_START_TIME] NVARCHAR(50) NULL,
        [PREV_END_TIME] NVARCHAR(50) NULL,
        [NEW_END_TIME] NVARCHAR(50) NULL,
        [PREV_AUDITOR] NVARCHAR(255) NULL,
        [NEW_AUDITOR] NVARCHAR(255) NULL,
        [PREV_AUDITEE] NVARCHAR(255) NULL,
        [NEW_AUDITEE] NVARCHAR(255) NULL,
        [MODIFIED_BY] NVARCHAR(255) NULL,
        [MODIFIED_DATE] DATETIME NULL,
        [ACTION] NVARCHAR(50) NULL,
        CONSTRAINT [PK_QMS_AUDIT_SCHEDULE_LOG] PRIMARY KEY CLUSTERED ([ID] DESC)
    );
    PRINT 'Created table QMS_AUDIT_SCHEDULE_LOG';
END;
