-- Rename Q37_PREV_REPORTING_TO to Q37_PREV_HR_MGR
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q37_PREV_REPORTING_TO')
BEGIN
    EXEC sp_rename 'HR_EMPLOYEE_SELF_ASSESSMENT.Q37_PREV_REPORTING_TO', 'Q37_PREV_HR_MGR', 'COLUMN';
END
GO

-- Rename Q41_REP_MGR_NAME to Q41_HR_MGR_NAME
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q41_REP_MGR_NAME')
BEGIN
    EXEC sp_rename 'HR_EMPLOYEE_SELF_ASSESSMENT.Q41_REP_MGR_NAME', 'Q41_HR_MGR_NAME', 'COLUMN';
END
GO

-- Rename Q42_REP_MGR_EMAIL to Q42_HR_MGR_EMAIL
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q42_REP_MGR_EMAIL')
BEGIN
    EXEC sp_rename 'HR_EMPLOYEE_SELF_ASSESSMENT.Q42_REP_MGR_EMAIL', 'Q42_HR_MGR_EMAIL', 'COLUMN';
END
GO

-- Rename Q43_REP_MGR_PHONE to Q43_HR_MGR_PHONE
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_EMPLOYEE_SELF_ASSESSMENT') AND name = 'Q43_REP_MGR_PHONE')
BEGIN
    EXEC sp_rename 'HR_EMPLOYEE_SELF_ASSESSMENT.Q43_REP_MGR_PHONE', 'Q43_HR_MGR_PHONE', 'COLUMN';
END
GO
