-- Seed QMS_PROCESS_TYPE_MASTER if empty
IF NOT EXISTS (SELECT 1 FROM QMS_PROCESS_TYPE_MASTER WHERE CODE = 'INFO')
BEGIN
    INSERT INTO QMS_PROCESS_TYPE_MASTER (CODE, NAME, IS_ACTIVE, CREATED_BY, CREATED_DATE)
    VALUES ('INFO', 'Information', 1, 'SYSTEM', GETDATE());
END;

IF NOT EXISTS (SELECT 1 FROM QMS_PROCESS_TYPE_MASTER WHERE CODE = 'ACTION')
BEGIN
    INSERT INTO QMS_PROCESS_TYPE_MASTER (CODE, NAME, IS_ACTIVE, CREATED_BY, CREATED_DATE)
    VALUES ('ACTION', 'Action', 1, 'SYSTEM', GETDATE());
END;

-- Seed QMS_POINT_TYPE_MASTER if empty
IF NOT EXISTS (SELECT 1 FROM QMS_POINT_TYPE_MASTER WHERE CODE = 'PROCESS')
BEGIN
    INSERT INTO QMS_POINT_TYPE_MASTER (CODE, NAME, IS_ACTIVE, CREATED_BY, CREATED_DATE)
    VALUES ('PROCESS', 'Process', 1, 'SYSTEM', GETDATE());
END;

IF NOT EXISTS (SELECT 1 FROM QMS_POINT_TYPE_MASTER WHERE CODE = 'MATERIAL')
BEGIN
    INSERT INTO QMS_POINT_TYPE_MASTER (CODE, NAME, IS_ACTIVE, CREATED_BY, CREATED_DATE)
    VALUES ('MATERIAL', 'Material', 1, 'SYSTEM', GETDATE());
END;

-- Update existing nvarchar values in QMS_MOM_DETAILS to point to the resolved numeric IDs
DECLARE @actionId BIGINT;
DECLARE @infoId BIGINT;
DECLARE @processId BIGINT;
DECLARE @materialId BIGINT;

SELECT @actionId = ID FROM QMS_PROCESS_TYPE_MASTER WHERE CODE = 'ACTION';
SELECT @infoId = ID FROM QMS_PROCESS_TYPE_MASTER WHERE CODE = 'INFO';
SELECT @processId = ID FROM QMS_POINT_TYPE_MASTER WHERE CODE = 'PROCESS';
SELECT @materialId = ID FROM QMS_POINT_TYPE_MASTER WHERE CODE = 'MATERIAL';

-- Perform the data type mapping updates
UPDATE QMS_MOM_DETAILS
SET PROCESS_TYPE_ID = CAST(@actionId AS NVARCHAR(50))
WHERE PROCESS_TYPE_ID = 'ACTION';

UPDATE QMS_MOM_DETAILS
SET PROCESS_TYPE_ID = CAST(@infoId AS NVARCHAR(50))
WHERE PROCESS_TYPE_ID = 'INFO';

UPDATE QMS_MOM_DETAILS
SET POINT_TYPE_ID = CAST(@processId AS NVARCHAR(50))
WHERE POINT_TYPE_ID = 'PROCESS';

UPDATE QMS_MOM_DETAILS
SET POINT_TYPE_ID = CAST(@materialId AS NVARCHAR(50))
WHERE POINT_TYPE_ID = 'MATERIAL';

-- Alter the column types to BIGINT to match Hibernate entity mapping and prevent type mismatches
ALTER TABLE QMS_MOM_DETAILS ALTER COLUMN PROCESS_TYPE_ID BIGINT;
ALTER TABLE QMS_MOM_DETAILS ALTER COLUMN POINT_TYPE_ID BIGINT;
