-- V328.0 Fix AD_USER_SESSION_AUDIT and AD_USER_SESSION_ACTIVITY Identity Properties
IF OBJECT_ID('dbo.FK_AD_USER_SESSION_AUDIT_CREATED_BY', 'F') IS NOT NULL
    ALTER TABLE [dbo].[AD_USER_SESSION_AUDIT] DROP CONSTRAINT [FK_AD_USER_SESSION_AUDIT_CREATED_BY];
IF OBJECT_ID('dbo.FK_AD_USER_SESSION_AUDIT_UPDATED_BY', 'F') IS NOT NULL
    ALTER TABLE [dbo].[AD_USER_SESSION_AUDIT] DROP CONSTRAINT [FK_AD_USER_SESSION_AUDIT_UPDATED_BY];

IF OBJECT_ID('dbo.FK_AD_USER_SESSION_ACTIVITY_CREATED_BY', 'F') IS NOT NULL
    ALTER TABLE [dbo].[AD_USER_SESSION_ACTIVITY] DROP CONSTRAINT [FK_AD_USER_SESSION_ACTIVITY_CREATED_BY];
IF OBJECT_ID('dbo.FK_AD_USER_SESSION_ACTIVITY_UPDATED_BY', 'F') IS NOT NULL
    ALTER TABLE [dbo].[AD_USER_SESSION_ACTIVITY] DROP CONSTRAINT [FK_AD_USER_SESSION_ACTIVITY_UPDATED_BY];

IF OBJECT_ID('dbo.AD_USER_SESSION_AUDIT', 'U') IS NOT NULL
    DROP TABLE [dbo].[AD_USER_SESSION_AUDIT];

IF OBJECT_ID('dbo.AD_USER_SESSION_ACTIVITY', 'U') IS NOT NULL
    DROP TABLE [dbo].[AD_USER_SESSION_ACTIVITY];

CREATE TABLE [dbo].[AD_USER_SESSION_AUDIT] (
    [ID] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [USER_ID] NVARCHAR(50) NULL,
    [IP_ADDRESS] NVARCHAR(50) NULL,
    [LOGIN_TIME] DATETIME NULL,
    [LOGOUT_TIME] DATETIME NULL,
    [USER_AGENT] NVARCHAR(255) NULL,
    [SESSION_STATUS] NVARCHAR(20) NULL,
    [CREATED_BY] NVARCHAR(50) NULL,
    [CREATED_DATE] DATETIME NULL,
    [UPDATED_BY] NVARCHAR(50) NULL,
    [UPDATED_DATE] DATETIME NULL
);

CREATE TABLE [dbo].[AD_USER_SESSION_ACTIVITY] (
    [ID] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [USER_ID] NVARCHAR(50) NULL,
    [PAGE_NAME] NVARCHAR(100) NULL,
    [PAGE_URL] NVARCHAR(255) NULL,
    [ENTRY_TIME] DATETIME NULL,
    [EXIT_TIME] DATETIME NULL,
    [DURATION_MS] BIGINT NULL,
    [IS_IDLE] BIT NULL DEFAULT 0,
    [IDLE_TIME_MS] BIGINT NULL DEFAULT 0,
    [CREATED_BY] NVARCHAR(50) NULL,
    [CREATED_DATE] DATETIME NULL,
    [UPDATED_BY] NVARCHAR(50) NULL,
    [UPDATED_DATE] DATETIME NULL
);

ALTER TABLE [dbo].[AD_USER_SESSION_AUDIT] ADD CONSTRAINT [FK_AD_USER_SESSION_AUDIT_CREATED_BY] 
    FOREIGN KEY ([CREATED_BY]) REFERENCES [dbo].[AD_USER_CREDENTIAL]([USER_ID]);

ALTER TABLE [dbo].[AD_USER_SESSION_AUDIT] ADD CONSTRAINT [FK_AD_USER_SESSION_AUDIT_UPDATED_BY] 
    FOREIGN KEY ([UPDATED_BY]) REFERENCES [dbo].[AD_USER_CREDENTIAL]([USER_ID]);

ALTER TABLE [dbo].[AD_USER_SESSION_ACTIVITY] ADD CONSTRAINT [FK_AD_USER_SESSION_ACTIVITY_CREATED_BY] 
    FOREIGN KEY ([CREATED_BY]) REFERENCES [dbo].[AD_USER_CREDENTIAL]([USER_ID]);

ALTER TABLE [dbo].[AD_USER_SESSION_ACTIVITY] ADD CONSTRAINT [FK_AD_USER_SESSION_ACTIVITY_UPDATED_BY] 
    FOREIGN KEY ([UPDATED_BY]) REFERENCES [dbo].[AD_USER_CREDENTIAL]([USER_ID]);
