-- Migration Script: Add NO_OF_BILLS column to HR_LEAVE_TRAVEL_DETAILS
IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS') AND name = 'NO_OF_BILLS'
)
BEGIN
    ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD NO_OF_BILLS INT NULL DEFAULT 1;
    PRINT 'Added NO_OF_BILLS column to HR_LEAVE_TRAVEL_DETAILS successfully.';
END
