-- Create Procurement Modules Tables (RFQ, Quotation, Comparison)

-- 1. Procurement Settings
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_PROCUREMENT_SETTINGS]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_PROCUREMENT_SETTINGS] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [DIVISION] BIGINT NOT NULL,
        [WEIGHT_PRICE] NUMERIC(5,2) NOT NULL DEFAULT 40.00,
        [WEIGHT_DELIVERY] NUMERIC(5,2) NOT NULL DEFAULT 20.00,
        [WEIGHT_RATING] NUMERIC(5,2) NOT NULL DEFAULT 15.00,
        [WEIGHT_WARRANTY] NUMERIC(5,2) NOT NULL DEFAULT 10.00,
        [WEIGHT_PAYMENT] NUMERIC(5,2) NOT NULL DEFAULT 15.00,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_PP_PROCUREMENT_SETTINGS] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_PROC_SETTING_DIV] FOREIGN KEY ([DIVISION]) REFERENCES [dbo].[AD_DIVISION]([ID])
    );
END
GO

-- 2. RFQ Head
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_RFQ_HEAD]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_RFQ_HEAD] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RFQ_NO] NVARCHAR(50) NOT NULL,
        [RFQ_DATE] DATE NOT NULL,
        [PR_REF_ID] BIGINT NULL,
        [DEPARTMENT_ID] BIGINT NOT NULL,
        [BUYER_ID] BIGINT NOT NULL,
        [CLOSING_DATE] DATE NOT NULL,
        [COMMERCIAL_TERMS] NVARCHAR(MAX) NULL,
        [INTERNAL_NOTES] NVARCHAR(500) NULL,
        [STATUS_ID] BIGINT NOT NULL,
        [DIVISION] BIGINT NOT NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_PP_RFQ_HEAD] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_RFQ_HEAD_PR] FOREIGN KEY ([PR_REF_ID]) REFERENCES [dbo].[PP_PURCHASE_REQUEST_HEAD]([ID]),
        CONSTRAINT [FK_PP_RFQ_HEAD_DEPT] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[HR_DEPARTMENT]([ID]),
        CONSTRAINT [FK_PP_RFQ_HEAD_BUYER] FOREIGN KEY ([BUYER_ID]) REFERENCES [dbo].[HR_EMPLOYEE]([ID]),
        CONSTRAINT [FK_PP_RFQ_HEAD_STATUS] FOREIGN KEY ([STATUS_ID]) REFERENCES [dbo].[AD_STATUS_MASTER]([ID]),
        CONSTRAINT [FK_PP_RFQ_HEAD_DIV] FOREIGN KEY ([DIVISION]) REFERENCES [dbo].[AD_DIVISION]([ID])
    );
    CREATE NONCLUSTERED INDEX [IX_PP_RFQ_HEAD_RFQ_NO] ON [dbo].[PP_RFQ_HEAD]([RFQ_NO]);
END
GO

-- 3. RFQ Detail
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_RFQ_DETAIL]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_RFQ_DETAIL] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RFQ_REF_ID] BIGINT NOT NULL,
        [ITEM_ID] BIGINT NOT NULL,
        [UOM] NVARCHAR(20) NOT NULL,
        [REQ_QTY] NUMERIC(12,4) NOT NULL DEFAULT 0,
        [EXPECTED_DELIVERY_DATE] DATE NULL,
        [REMARKS] NVARCHAR(250) NULL,
        [DIVISION] BIGINT NOT NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_PP_RFQ_DETAIL] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_RFQ_DETAIL_HEAD] FOREIGN KEY ([RFQ_REF_ID]) REFERENCES [dbo].[PP_RFQ_HEAD]([ID]) ON DELETE CASCADE,
        CONSTRAINT [FK_PP_RFQ_DETAIL_ITEM] FOREIGN KEY ([ITEM_ID]) REFERENCES [dbo].[NPD_PRODUCT_MASTER]([ID]),
        CONSTRAINT [FK_PP_RFQ_DETAIL_DIV] FOREIGN KEY ([DIVISION]) REFERENCES [dbo].[AD_DIVISION]([ID])
    );
END
GO

-- 4. RFQ Supplier
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_RFQ_SUPPLIER]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_RFQ_SUPPLIER] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RFQ_REF_ID] BIGINT NOT NULL,
        [SUPPLIER_ID] BIGINT NOT NULL,
        [SUPPLIER_STATUS_ID] BIGINT NULL,
        [EMAIL_SENT] BIT NOT NULL DEFAULT 0,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_PP_RFQ_SUPPLIER] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_RFQ_SUPPLIER_HEAD] FOREIGN KEY ([RFQ_REF_ID]) REFERENCES [dbo].[PP_RFQ_HEAD]([ID]) ON DELETE CASCADE,
        CONSTRAINT [FK_PP_RFQ_SUPPLIER_VND] FOREIGN KEY ([SUPPLIER_ID]) REFERENCES [dbo].[VND_VENDOR]([ID])
    );
END
GO

-- 5. RFQ Attachment
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_RFQ_ATTACHMENT]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_RFQ_ATTACHMENT] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RFQ_REF_ID] BIGINT NOT NULL,
        [FILE_NAME] NVARCHAR(250) NOT NULL,
        [FILE_PATH] NVARCHAR(500) NOT NULL,
        [FILE_TYPE] NVARCHAR(50) NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_PP_RFQ_ATTACHMENT] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_RFQ_ATT_HEAD] FOREIGN KEY ([RFQ_REF_ID]) REFERENCES [dbo].[PP_RFQ_HEAD]([ID]) ON DELETE CASCADE
    );
END
GO

-- 6. RFQ Activity
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_RFQ_ACTIVITY]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_RFQ_ACTIVITY] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RFQ_REF_ID] BIGINT NOT NULL,
        [ACTIVITY_TYPE] NVARCHAR(100) NOT NULL,
        [DESCRIPTION] NVARCHAR(500) NOT NULL,
        [ACTOR_ID] NVARCHAR(50) NOT NULL,
        [ACTIVITY_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        CONSTRAINT [PK_PP_RFQ_ACTIVITY] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_RFQ_ACT_HEAD] FOREIGN KEY ([RFQ_REF_ID]) REFERENCES [dbo].[PP_RFQ_HEAD]([ID]) ON DELETE CASCADE
    );
END
GO

-- 7. RFQ Workflow
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_RFQ_WORKFLOW]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_RFQ_WORKFLOW] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RFQ_REF_ID] BIGINT NOT NULL,
        [FROM_STATUS_ID] BIGINT NULL,
        [TO_STATUS_ID] BIGINT NOT NULL,
        [REMARKS] NVARCHAR(500) NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        CONSTRAINT [PK_PP_RFQ_WORKFLOW] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_RFQ_WF_HEAD] FOREIGN KEY ([RFQ_REF_ID]) REFERENCES [dbo].[PP_RFQ_HEAD]([ID]) ON DELETE CASCADE
    );
END
GO

-- 8. RFQ Email Log
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_RFQ_EMAIL_LOG]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_RFQ_EMAIL_LOG] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RFQ_REF_ID] BIGINT NOT NULL,
        [SUPPLIER_ID] BIGINT NOT NULL,
        [EMAIL_TO] NVARCHAR(250) NOT NULL,
        [SUBJECT] NVARCHAR(250) NOT NULL,
        [SENT_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [STATUS] NVARCHAR(50) NOT NULL,
        [ERROR_MESSAGE] NVARCHAR(MAX) NULL,
        CONSTRAINT [PK_PP_RFQ_EMAIL_LOG] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_RFQ_EMAIL_HEAD] FOREIGN KEY ([RFQ_REF_ID]) REFERENCES [dbo].[PP_RFQ_HEAD]([ID]) ON DELETE CASCADE
    );
END
GO

-- 9. Quotation Head
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_QUOTATION_HEAD]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_QUOTATION_HEAD] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [QUOTATION_NO] NVARCHAR(50) NOT NULL,
        [RFQ_REF_ID] BIGINT NOT NULL,
        [SUPPLIER_ID] BIGINT NOT NULL,
        [QUOTATION_DATE] DATE NOT NULL,
        [VALIDITY_DATE] DATE NOT NULL,
        [CURRENCY] NVARCHAR(20) NOT NULL DEFAULT 'INR',
        [LEAD_TIME_DAYS] INT NULL,
        [WARRANTY_TERMS] NVARCHAR(250) NULL,
        [PAYMENT_TERMS] NVARCHAR(250) NULL,
        [REMARKS] NVARCHAR(500) NULL,
        [TECHNICAL_STATUS_ID] BIGINT NULL,
        [STATUS_ID] BIGINT NOT NULL,
        [DIVISION] BIGINT NOT NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_PP_QUOTATION_HEAD] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_QUOT_HEAD_RFQ] FOREIGN KEY ([RFQ_REF_ID]) REFERENCES [dbo].[PP_RFQ_HEAD]([ID]),
        CONSTRAINT [FK_PP_QUOT_HEAD_VND] FOREIGN KEY ([SUPPLIER_ID]) REFERENCES [dbo].[VND_VENDOR]([ID]),
        CONSTRAINT [FK_PP_QUOT_HEAD_TECH_STAT] FOREIGN KEY ([TECHNICAL_STATUS_ID]) REFERENCES [dbo].[AD_STATUS_MASTER]([ID]),
        CONSTRAINT [FK_PP_QUOT_HEAD_STAT] FOREIGN KEY ([STATUS_ID]) REFERENCES [dbo].[AD_STATUS_MASTER]([ID]),
        CONSTRAINT [FK_PP_QUOT_HEAD_DIV] FOREIGN KEY ([DIVISION]) REFERENCES [dbo].[AD_DIVISION]([ID])
    );
END
GO

-- 10. Quotation Detail
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_QUOTATION_DETAIL]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_QUOTATION_DETAIL] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [QUOTATION_REF_ID] BIGINT NOT NULL,
        [RFQ_DETAIL_ID] BIGINT NOT NULL,
        [ITEM_ID] BIGINT NOT NULL,
        [UOM] NVARCHAR(20) NOT NULL,
        [QTY] NUMERIC(12,4) NOT NULL DEFAULT 0,
        [UNIT_PRICE] NUMERIC(12,4) NOT NULL DEFAULT 0,
        [DISCOUNT_PERCENT] NUMERIC(5,2) NOT NULL DEFAULT 0,
        [TAX_PERCENT] NUMERIC(5,2) NOT NULL DEFAULT 0,
        [FREIGHT_AMOUNT] NUMERIC(12,4) NOT NULL DEFAULT 0,
        [TOTAL_AMOUNT] NUMERIC(12,4) NOT NULL DEFAULT 0,
        [REMARKS] NVARCHAR(250) NULL,
        [DIVISION] BIGINT NOT NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_PP_QUOTATION_DETAIL] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_QUOT_DET_HEAD] FOREIGN KEY ([QUOTATION_REF_ID]) REFERENCES [dbo].[PP_QUOTATION_HEAD]([ID]) ON DELETE CASCADE,
        CONSTRAINT [FK_PP_QUOT_DET_RFQ] FOREIGN KEY ([RFQ_DETAIL_ID]) REFERENCES [dbo].[PP_RFQ_DETAIL]([ID]),
        CONSTRAINT [FK_PP_QUOT_DET_ITEM] FOREIGN KEY ([ITEM_ID]) REFERENCES [dbo].[NPD_PRODUCT_MASTER]([ID]),
        CONSTRAINT [FK_PP_QUOT_DET_DIV] FOREIGN KEY ([DIVISION]) REFERENCES [dbo].[AD_DIVISION]([ID])
    );
END
GO

-- 11. Quotation Attachment
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_QUOTATION_ATTACHMENT]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_QUOTATION_ATTACHMENT] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [QUOTATION_REF_ID] BIGINT NOT NULL,
        [FILE_NAME] NVARCHAR(250) NOT NULL,
        [FILE_PATH] NVARCHAR(500) NOT NULL,
        [FILE_TYPE] NVARCHAR(50) NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_PP_QUOTATION_ATTACHMENT] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_QUOT_ATT_HEAD] FOREIGN KEY ([QUOTATION_REF_ID]) REFERENCES [dbo].[PP_QUOTATION_HEAD]([ID]) ON DELETE CASCADE
    );
END
GO

-- 12. Comparison Decision
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_COMPARISON_DECISION]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_COMPARISON_DECISION] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [RFQ_REF_ID] BIGINT NOT NULL,
        [RECOMMENDED_SUPPLIER_ID] BIGINT NULL,
        [RECOMMENDED_REASON] NVARCHAR(MAX) NULL,
        [SELECTED_SUPPLIER_ID] BIGINT NOT NULL,
        [OVERRIDE_REMARKS] NVARCHAR(MAX) NULL,
        [DECISION_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [STATUS_ID] BIGINT NOT NULL,
        [DIVISION] BIGINT NOT NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_PP_COMPARISON_DECISION] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_COMP_DEC_RFQ] FOREIGN KEY ([RFQ_REF_ID]) REFERENCES [dbo].[PP_RFQ_HEAD]([ID]),
        CONSTRAINT [FK_PP_COMP_DEC_REC_VND] FOREIGN KEY ([RECOMMENDED_SUPPLIER_ID]) REFERENCES [dbo].[VND_VENDOR]([ID]),
        CONSTRAINT [FK_PP_COMP_DEC_SEL_VND] FOREIGN KEY ([SELECTED_SUPPLIER_ID]) REFERENCES [dbo].[VND_VENDOR]([ID]),
        CONSTRAINT [FK_PP_COMP_DEC_STAT] FOREIGN KEY ([STATUS_ID]) REFERENCES [dbo].[AD_STATUS_MASTER]([ID]),
        CONSTRAINT [FK_PP_COMP_DEC_DIV] FOREIGN KEY ([DIVISION]) REFERENCES [dbo].[AD_DIVISION]([ID])
    );
END
GO

-- 13. Supplier Performance
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_SUPPLIER_PERFORMANCE]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_SUPPLIER_PERFORMANCE] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [SUPPLIER_ID] BIGINT NOT NULL,
        [RATING_SCORE] NUMERIC(5,2) NOT NULL DEFAULT 0,
        [DELIVERY_PERFORMANCE] NUMERIC(5,2) NOT NULL DEFAULT 0,
        [QUALITY_PERFORMANCE] NUMERIC(5,2) NOT NULL DEFAULT 0,
        [LAST_EVALUATED] DATETIME NULL,
        [DIVISION] BIGINT NOT NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_PP_SUPPLIER_PERFORMANCE] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_SUP_PERF_VND] FOREIGN KEY ([SUPPLIER_ID]) REFERENCES [dbo].[VND_VENDOR]([ID]),
        CONSTRAINT [FK_PP_SUP_PERF_DIV] FOREIGN KEY ([DIVISION]) REFERENCES [dbo].[AD_DIVISION]([ID])
    );
END
GO
