-- Migration Script: Rename HR_LEAVE_TRAVEL_APPLICATION to HR_LEAVE_TRAVEL_DETAILS
-- Date: 2026-07-26

IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_APPLICATION', 'U') IS NOT NULL AND OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NULL
BEGIN
    EXEC sp_rename 'dbo.HR_LEAVE_TRAVEL_APPLICATION', 'HR_LEAVE_TRAVEL_DETAILS';
    PRINT 'Renamed table HR_LEAVE_TRAVEL_APPLICATION to HR_LEAVE_TRAVEL_DETAILS successfully.';
END
ELSE IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NOT NULL
BEGIN
    PRINT 'Table HR_LEAVE_TRAVEL_DETAILS already exists.';
END;

-- Backward compatibility view for legacy queries if needed
IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_APPLICATION', 'U') IS NULL AND OBJECT_ID('dbo.HR_LEAVE_TRAVEL_APPLICATION', 'V') IS NULL AND OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NOT NULL
BEGIN
    EXEC('CREATE VIEW dbo.HR_LEAVE_TRAVEL_APPLICATION AS SELECT * FROM dbo.HR_LEAVE_TRAVEL_DETAILS');
    PRINT 'Created backward compatibility view HR_LEAVE_TRAVEL_APPLICATION.';
END;
