

-- =======================================================================================
-- MIGRATION SCRIPT: Create Gate Entry Module Tables
-- DB TYPE: Microsoft SQL Server
-- VERSION: 1093.0
-- =======================================================================================

-- 1. PP_GATE_ENTRY_HEAD
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_GATE_ENTRY_HEAD')
BEGIN
    CREATE TABLE PP_GATE_ENTRY_HEAD (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        DIVISION                BIGINT          NOT NULL,
        
        -- Header Information
        GATE_ENTRY_NO           NVARCHAR(50)    NOT NULL,
        GATE_ENTRY_DATE         DATE            NOT NULL,
        GATE_PASS_TYPE          NVARCHAR(50)    NOT NULL DEFAULT 'MATERIAL_RECEIPT', -- MATERIAL_RECEIPT, ASSET_RECEIPT, etc.
        ENTRY_TYPE              NVARCHAR(20)    NOT NULL DEFAULT 'INWARD', -- INWARD / OUTWARD
        
        -- Entities
        SUPPLIER_ID             BIGINT          NULL,
        TRANSPORTER_ID          BIGINT          NULL,
        TRANSPORT_MODE          NVARCHAR(50)    NULL,
        VEHICLE_NO              NVARCHAR(50)    NULL,
        LR_NO                   NVARCHAR(50)    NULL,
        LR_DATE                 DATE            NULL,
        
        -- Time Tracking KPIs
        EXPECTED_ARRIVAL_TIME   DATETIME        NULL,
        ARRIVAL_TIME            DATETIME        NULL,
        SECURITY_CHECK_START    DATETIME        NULL,
        SECURITY_CHECK_END      DATETIME        NULL,
        STORES_INSPECTION_START DATETIME        NULL,
        STORES_INSPECTION_END   DATETIME        NULL,
        GRN_CREATED_TIME        DATETIME        NULL,
        EXIT_TIME               DATETIME        NULL,
        
        -- Internal Tracking
        GATE_NO                 NVARCHAR(50)    NULL,
        SECURITY_OFFICER_ID     NVARCHAR(50)    NULL,
        DEPARTMENT_ID           BIGINT          NULL,
        REMARKS                 NVARCHAR(MAX)   NULL,
        
        -- Approval & Status
        STATUS_ID               BIGINT          NOT NULL,
        APPROVAL_VERSION        INT             NOT NULL DEFAULT 1,
        APPROVAL_SEQUENCE       INT             NOT NULL DEFAULT 0,
        
        -- Audit Fields
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_GATE_HEAD_DIV     FOREIGN KEY (DIVISION)            REFERENCES AD_DIVISION(ID),
        CONSTRAINT FK_PP_GATE_HEAD_SUPP    FOREIGN KEY (SUPPLIER_ID)         REFERENCES FA_ACCOUNT_LEDGER(ID),
        CONSTRAINT FK_PP_GATE_HEAD_TRANS   FOREIGN KEY (TRANSPORTER_ID)      REFERENCES FA_ACCOUNT_LEDGER(ID),
        CONSTRAINT FK_PP_GATE_HEAD_SEC     FOREIGN KEY (SECURITY_OFFICER_ID) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_PP_GATE_HEAD_DEPT    FOREIGN KEY (DEPARTMENT_ID)       REFERENCES HR_DEPARTMENT(ID),
        CONSTRAINT FK_PP_GATE_HEAD_STAT    FOREIGN KEY (STATUS_ID)           REFERENCES AD_STATUS_MASTER(ID)
    );
    PRINT 'PP_GATE_ENTRY_HEAD created.';
END
ELSE
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PP_GATE_ENTRY_HEAD' AND COLUMN_NAME = 'VEHICLE_NO')
        ALTER TABLE PP_GATE_ENTRY_HEAD ADD VEHICLE_NO NVARCHAR(50) NULL;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PP_GATE_ENTRY_HEAD' AND COLUMN_NAME = 'LR_NO')
        ALTER TABLE PP_GATE_ENTRY_HEAD ADD LR_NO NVARCHAR(50) NULL;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PP_GATE_ENTRY_HEAD' AND COLUMN_NAME = 'LR_DATE')
        ALTER TABLE PP_GATE_ENTRY_HEAD ADD LR_DATE DATE NULL;
END
GO

-- 2. PP_GATE_ENTRY_SOURCE (Maps multiple documents like PO, Invoice, Challan, LR)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_GATE_ENTRY_SOURCE')
BEGIN
    CREATE TABLE PP_GATE_ENTRY_SOURCE (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        GATE_ENTRY_HEAD_ID      BIGINT          NOT NULL,
        
        SOURCE_TYPE             NVARCHAR(50)    NOT NULL, -- PO, INVOICE, CHALLAN, LR, EWAY_BILL
        SOURCE_HEAD_ID          BIGINT          NULL,     -- FK to PP_PURCHASE_ORDER_HEAD if type=PO
        SOURCE_DOCUMENT_NO      NVARCHAR(100)   NULL,
        SOURCE_DOCUMENT_DATE    DATE            NULL,
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_GATE_SRC_HEAD FOREIGN KEY (GATE_ENTRY_HEAD_ID) REFERENCES PP_GATE_ENTRY_HEAD(ID) ON DELETE CASCADE
    );
    PRINT 'PP_GATE_ENTRY_SOURCE created.';
END
GO

-- 3. PP_GATE_ENTRY_TRANS (Line Items)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_GATE_ENTRY_TRANS')
BEGIN
    CREATE TABLE PP_GATE_ENTRY_TRANS (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        GATE_ENTRY_HEAD_ID      BIGINT          NOT NULL,
        SOURCE_ID               BIGINT          NOT NULL,     -- FK to PP_GATE_ENTRY_SOURCE
        SOURCE_LINE_ID          BIGINT          NULL,         -- Line ID of source if applicable
        PO_TRANS_ID             BIGINT          NULL,         -- Link to ordered item
        ITEM_ID                 BIGINT          NOT NULL,     -- PP_PRODUCT_MASTER
        
        -- Quantities
        DELIVERED_QTY           NUMERIC(18,4)   NOT NULL DEFAULT 0,
        ACCEPTED_QTY            NUMERIC(18,4)   NOT NULL DEFAULT 0,
        REJECTED_QTY            NUMERIC(18,4)   NOT NULL DEFAULT 0,
        DAMAGED_QTY             NUMERIC(18,4)   NOT NULL DEFAULT 0,
        SHORT_QTY               NUMERIC(18,4)   NOT NULL DEFAULT 0,
        
        -- Package details
        PACKAGE_COUNT           INT             NULL,
        BATCH_NO                NVARCHAR(100)   NULL,
        SERIAL_NO               NVARCHAR(100)   NULL,
        REMARKS                 NVARCHAR(MAX)   NULL,
        
        -- Audit Fields
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_GATE_TRANS_HEAD   FOREIGN KEY (GATE_ENTRY_HEAD_ID) REFERENCES PP_GATE_ENTRY_HEAD(ID) ON DELETE CASCADE,
        CONSTRAINT FK_PP_GATE_TRANS_PO     FOREIGN KEY (PO_TRANS_ID)        REFERENCES PP_PURCHASE_ORDER_TRANS(ID),
        CONSTRAINT FK_PP_GATE_TRANS_ITEM FOREIGN KEY (ITEM_ID) REFERENCES NPD_PRODUCT_MASTER(ID),
        CONSTRAINT FK_PP_GATE_TRANS_SRC FOREIGN KEY (SOURCE_ID) REFERENCES PP_GATE_ENTRY_SOURCE(ID)
    );
    PRINT 'PP_GATE_ENTRY_TRANS created.';
END
ELSE
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PP_GATE_ENTRY_TRANS' AND COLUMN_NAME = 'SOURCE_ID')
    BEGIN
        ALTER TABLE PP_GATE_ENTRY_TRANS ADD SOURCE_ID BIGINT NULL;
        ALTER TABLE PP_GATE_ENTRY_TRANS ADD CONSTRAINT FK_PP_GATE_TRANS_SRC FOREIGN KEY (SOURCE_ID) REFERENCES PP_GATE_ENTRY_SOURCE(ID);
    END
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PP_GATE_ENTRY_TRANS' AND COLUMN_NAME = 'SOURCE_LINE_ID')
    BEGIN
        ALTER TABLE PP_GATE_ENTRY_TRANS ADD SOURCE_LINE_ID BIGINT NULL;
    END
END
GO

-- 4. PP_GATE_ENTRY_VISITOR (Vehicle & Driver & Weighbridge Info)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_GATE_ENTRY_VISITOR')
BEGIN
    CREATE TABLE PP_GATE_ENTRY_VISITOR (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        GATE_ENTRY_HEAD_ID      BIGINT          NOT NULL,
        
        -- Vehicle Info
        VEHICLE_NO              NVARCHAR(50)    NOT NULL,
        VEHICLE_TYPE            NVARCHAR(50)    NULL,
        TRUCK_SIZE              NVARCHAR(50)    NULL,
        TRAILER_NO              NVARCHAR(50)    NULL,
        CONTAINER_NO            NVARCHAR(100)   NULL,
        SEAL_NO                 NVARCHAR(100)   NULL,
        SEAL_CONDITION          NVARCHAR(50)    NULL,
        PARKING_LOCATION        NVARCHAR(100)   NULL,
        
        -- Weighbridge Info
        GROSS_WEIGHT            NUMERIC(18,4)   NULL,
        TARE_WEIGHT             NUMERIC(18,4)   NULL,
        NET_WEIGHT              NUMERIC(18,4)   NULL,
        WEIGHBRIDGE_SLIP_NO     NVARCHAR(100)   NULL,
        
        -- Driver Info
        DRIVER_NAME             NVARCHAR(100)   NOT NULL,
        DRIVER_MOBILE           NVARCHAR(20)    NOT NULL,
        DRIVER_LICENSE_NO       NVARCHAR(50)    NULL,
        LICENSE_EXPIRY          DATE            NULL,
        HELPER_NAME             NVARCHAR(100)   NULL,
        TRANSPORT_COMPANY       NVARCHAR(100)   NULL,
        EMERGENCY_CONTACT       NVARCHAR(20)    NULL,
        
        -- Audit Fields
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_GATE_VISITOR_HEAD FOREIGN KEY (GATE_ENTRY_HEAD_ID) REFERENCES PP_GATE_ENTRY_HEAD(ID) ON DELETE CASCADE
    );
    PRINT 'PP_GATE_ENTRY_VISITOR created.';
END
GO

-- 5. PP_GATE_ENTRY_ATTACHMENT
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_GATE_ENTRY_ATTACHMENT')
BEGIN
    CREATE TABLE PP_GATE_ENTRY_ATTACHMENT (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        GATE_ENTRY_HEAD_ID      BIGINT          NOT NULL,
        FILE_NAME               NVARCHAR(255)   NOT NULL,
        FILE_PATH               NVARCHAR(1000)  NOT NULL,
        FILE_SIZE               BIGINT          NULL,
        MIME_TYPE               NVARCHAR(100)   NULL,
        ATTACHMENT_TYPE         NVARCHAR(50)    NULL, -- RC, LICENSE, PHOTO
        
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_GATE_ATT_HEAD FOREIGN KEY (GATE_ENTRY_HEAD_ID) REFERENCES PP_GATE_ENTRY_HEAD(ID) ON DELETE CASCADE
    );
    PRINT 'PP_GATE_ENTRY_ATTACHMENT created.';
END
GO

-- 6. PP_GATE_ENTRY_LOG (Immutable audit event log)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_GATE_ENTRY_LOG')
BEGIN
    CREATE TABLE PP_GATE_ENTRY_LOG (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        GATE_ENTRY_HEAD_ID      BIGINT          NOT NULL,
        EVENT_TYPE              NVARCHAR(50)    NOT NULL,
        EVENT_DESCRIPTION       NVARCHAR(MAX)   NULL,
        
        -- Audit Fields
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_GATE_LOG_HEAD FOREIGN KEY (GATE_ENTRY_HEAD_ID) REFERENCES PP_GATE_ENTRY_HEAD(ID) ON DELETE CASCADE
    );
    PRINT 'PP_GATE_ENTRY_LOG created.';
END
GO

-- 7. PP_PROCUREMENT_SETTINGS Updates
-- Add Gate Entry Configurable toggles
IF COL_LENGTH('PP_PROCUREMENT_SETTINGS', 'ENABLE_GATE_ENTRY') IS NULL
BEGIN
    ALTER TABLE PP_PROCUREMENT_SETTINGS ADD ENABLE_GATE_ENTRY INT NOT NULL DEFAULT 0;
    ALTER TABLE PP_PROCUREMENT_SETTINGS ADD REQUIRE_SECURITY_APPROVAL INT NOT NULL DEFAULT 0;
    ALTER TABLE PP_PROCUREMENT_SETTINGS ADD REQUIRE_STORES_VERIFICATION INT NOT NULL DEFAULT 0;
    ALTER TABLE PP_PROCUREMENT_SETTINGS ADD REQUIRE_VEHICLE_PHOTOS INT NOT NULL DEFAULT 0;
    ALTER TABLE PP_PROCUREMENT_SETTINGS ADD REQUIRE_DRIVER_LICENSE INT NOT NULL DEFAULT 0;
    ALTER TABLE PP_PROCUREMENT_SETTINGS ADD REQUIRE_SEAL_VERIFICATION INT NOT NULL DEFAULT 0;
    ALTER TABLE PP_PROCUREMENT_SETTINGS ADD REQUIRE_WEIGHBRIDGE INT NOT NULL DEFAULT 0;
    
    PRINT 'PP_PROCUREMENT_SETTINGS Gate Entry columns added.';
END
GO

-- 8. Indexes
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PP_GATE_HEAD_NO' AND object_id = OBJECT_ID('PP_GATE_ENTRY_HEAD'))
    CREATE UNIQUE INDEX IX_PP_GATE_HEAD_NO ON PP_GATE_ENTRY_HEAD (GATE_ENTRY_NO, DIVISION);
    
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PP_GATE_HEAD_STATUS' AND object_id = OBJECT_ID('PP_GATE_ENTRY_HEAD'))
    CREATE INDEX IX_PP_GATE_HEAD_STATUS ON PP_GATE_ENTRY_HEAD (STATUS_ID);
    
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PP_GATE_TRANS_HEAD' AND object_id = OBJECT_ID('PP_GATE_ENTRY_TRANS'))
    CREATE INDEX IX_PP_GATE_TRANS_HEAD ON PP_GATE_ENTRY_TRANS (GATE_ENTRY_HEAD_ID, ACTIVE_STATUS);

-- 9. Seed Gate Entry Statuses
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'VEHICLE EXPECTED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('VEHICLE EXPECTED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'VEHICLE ARRIVED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('VEHICLE ARRIVED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'WAITING FOR SECURITY')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('WAITING FOR SECURITY');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'SECURITY CHECKED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('SECURITY CHECKED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'WAITING FOR STORES')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('WAITING FOR STORES');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'STORES VERIFIED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('STORES VERIFIED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'READY FOR GRN')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('READY FOR GRN');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'GRN CREATED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('GRN CREATED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'VEHICLE EXIT')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('VEHICLE EXIT');

-- 10. Seed BOS Page Permissions


IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'PP0102')
BEGIN
    DECLARE @ModuleId BIGINT;
    SELECT TOP 1 @ModuleId = MOD_ID FROM BOS_PAGES WHERE PAGE_CODE LIKE 'PP%' ORDER BY PAGE_ID;
    IF @ModuleId IS NOT NULL
    BEGIN
        INSERT INTO BOS_PAGES (MOD_ID, PAGE_CODE, PAGE_NAME, PAGE_URL, ICON, ENABLED)
        VALUES (@ModuleId, 'PP0102', 'Gate Entry Register', '/GateEntry/GateEntry', 'IconShoppingCart', 1);
        PRINT 'PP0102 - Gate Entry Register.';
    END
END

IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'PP0103')
BEGIN
    DECLARE @ModuleId2 BIGINT;
    SELECT TOP 1 @ModuleId2 = MOD_ID FROM BOS_PAGES WHERE PAGE_CODE LIKE 'PP%' ORDER BY PAGE_ID;
    IF @ModuleId2 IS NOT NULL
    BEGIN
        INSERT INTO BOS_PAGES (MOD_ID, PAGE_CODE, PAGE_NAME, PAGE_URL, ICON, ENABLED)
        VALUES (@ModuleId2, 'PP0103', 'Gate Entry', '/GateEntry/GateEntry/entry', 'IconShoppingCart',  1);
        PRINT 'PP0103 - Gate Entry page registered.';
    END
END

 