IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PP_QUOT_HEAD_VND]') AND parent_object_id = OBJECT_ID(N'[dbo].[PP_QUOTATION_HEAD]'))
BEGIN
    ALTER TABLE [dbo].[PP_QUOTATION_HEAD] DROP CONSTRAINT [FK_PP_QUOT_HEAD_VND];
END
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PP_QUOT_HEAD_ACCOUNT_LEDGER]') AND parent_object_id = OBJECT_ID(N'[dbo].[PP_QUOTATION_HEAD]'))
BEGIN
    ALTER TABLE [dbo].[PP_QUOTATION_HEAD]  WITH CHECK ADD  CONSTRAINT [FK_PP_QUOT_HEAD_ACCOUNT_LEDGER] FOREIGN KEY([SUPPLIER_ID])
    REFERENCES [dbo].[FA_ACCOUNT_LEDGER] ([ID]);
    ALTER TABLE [dbo].[PP_QUOTATION_HEAD] CHECK CONSTRAINT [FK_PP_QUOT_HEAD_ACCOUNT_LEDGER];
END
GO
