-- Migration script to update FA_ACCOUNT_LEDGER based on new schema
-- 1. Alter SHORT_NAME to be NOT NULL
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN SHORT_NAME nvarchar(25) NOT NULL;

-- 2. Add UNIQUE constraint to SHORT_NAME
ALTER TABLE FA_ACCOUNT_LEDGER ADD CONSTRAINT UQ_FA_ACCOUNT_LEDGER_SHORT_NAME UNIQUE (SHORT_NAME);

-- 3. Alter LEDGER_NAME to be NOT NULL
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN LEDGER_NAME nvarchar(100) NOT NULL;

-- 4. Add LEDGER_TYPE
ALTER TABLE FA_ACCOUNT_LEDGER ADD LEDGER_TYPE nvarchar(20);

-- 5. Drop IS_OTHERS if exists
IF COL_LENGTH('FA_ACCOUNT_LEDGER', 'IS_OTHERS') IS NOT NULL
BEGIN
    ALTER TABLE FA_ACCOUNT_LEDGER DROP COLUMN IS_OTHERS;
END

-- 6. Drop TDS_APPLICABLE if exists
IF COL_LENGTH('FA_ACCOUNT_LEDGER', 'TDS_APPLICABLE') IS NOT NULL
BEGIN
    ALTER TABLE FA_ACCOUNT_LEDGER DROP COLUMN TDS_APPLICABLE;
END

-- 7. Rename FRIEGHT_APPLICABLE to FRIEIGHT_APPLICABLE
IF COL_LENGTH('FA_ACCOUNT_LEDGER', 'FRIEGHT_APPLICABLE') IS NOT NULL
BEGIN
    EXEC sp_rename 'FA_ACCOUNT_LEDGER.FRIEGHT_APPLICABLE', 'FRIEIGHT_APPLICABLE', 'COLUMN';
END
