-- =====================================================================================
-- Migration Script: V1223.0 - Optimize HRA_OFFER_LETTERS Schema, Typed Snapshots,
--                             STATUS_ID FK, Concurrency Locking and Data Backfill
-- Target Database   : Application-configured primary database
-- Module            : HRA -> Onboarding -> Offer Letter (HA1360)
-- Description       : Adds typed snapshot columns for candidate, job, salary totals,
--                     company legal identity, template binding, and STATUS_ID referencing
--                     AD_STATUS_MASTER. Adds LOCK_VERSION for optimistic locking.
--                     Backfills existing records idempotently from FORM_DATA JSON.
-- =====================================================================================

SET NOCOUNT ON;

-- 1. ADD TYPED RELATIONAL & SNAPSHOT COLUMNS TO HRA_OFFER_LETTERS (IDEMPOTENT)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'APPLICANT_ID')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [APPLICANT_ID] BIGINT NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'EMAIL')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [EMAIL] NVARCHAR(150) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'PHONE')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [PHONE] NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'DEPARTMENT_ID')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [DEPARTMENT_ID] BIGINT NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'DESIGNATION_ID')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [DESIGNATION_ID] BIGINT NULL;
END

-- REPORTING_MANAGER_ID / REPORTING_MANAGER are intentionally NOT added: the entity,
-- DTOs and UI never persist them, and they stay available in FORM_DATA.

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'EMPLOYMENT_TYPE')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [EMPLOYMENT_TYPE] NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'WORK_LOCATION')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [WORK_LOCATION] NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'GRADE')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [GRADE] NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'JOINING_DATE')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [JOINING_DATE] DATE NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'PROBATION_PERIOD_MONTHS')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [PROBATION_PERIOD_MONTHS] INT NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'GROSS_SALARY')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [GROSS_SALARY] DECIMAL(18,2) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'ANNUAL_CTC')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [ANNUAL_CTC] DECIMAL(18,2) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'NET_SALARY')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [NET_SALARY] DECIMAL(18,2) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'MONTHLY_CTC')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [MONTHLY_CTC] DECIMAL(18,2) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'COMPANY_NAME')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [COMPANY_NAME] NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'COMPANY_ADDRESS')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [COMPANY_ADDRESS] NVARCHAR(500) NULL;
END

-- COMPANY_GSTIN is intentionally NOT added: GSTIN belongs to the company profile
-- master, and the offer letter reads it from there rather than snapshotting it.

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'SIGNATORY_NAME')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [SIGNATORY_NAME] NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'SIGNATORY_DESIGNATION')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [SIGNATORY_DESIGNATION] NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'TEMPLATE_ID')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [TEMPLATE_ID] BIGINT NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'STATUS_ID')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [STATUS_ID] BIGINT NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HRA_OFFER_LETTERS' AND COLUMN_NAME = 'LOCK_VERSION')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS] ADD [LOCK_VERSION] BIGINT NOT NULL CONSTRAINT [DF_HRA_OFFER_LETTERS_LOCK_VERSION] DEFAULT (0);
END
GO

-- 2. SEED CORE STATUSES IN AD_STATUS_MASTER IF MISSING
IF NOT EXISTS (SELECT 1 FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) = 'DRAFT')
BEGIN
    INSERT INTO [dbo].[AD_STATUS_MASTER] ([NAME]) VALUES ('Draft');
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) = 'APPROVED')
BEGIN
    INSERT INTO [dbo].[AD_STATUS_MASTER] ([NAME]) VALUES ('Approved');
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) = 'SENT')
BEGIN
    INSERT INTO [dbo].[AD_STATUS_MASTER] ([NAME]) VALUES ('Sent');
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) = 'ACCEPTED')
BEGIN
    INSERT INTO [dbo].[AD_STATUS_MASTER] ([NAME]) VALUES ('Accepted');
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) = 'REJECTED')
BEGIN
    INSERT INTO [dbo].[AD_STATUS_MASTER] ([NAME]) VALUES ('Rejected');
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) = 'PENDING')
BEGIN
    INSERT INTO [dbo].[AD_STATUS_MASTER] ([NAME]) VALUES ('Pending');
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) = 'CANCELLED')
BEGIN
    INSERT INTO [dbo].[AD_STATUS_MASTER] ([NAME]) VALUES ('Cancelled');
END
GO

-- 3. IDEMPOTENT DML BACKFILL FROM FORM_DATA JSON
-- Backfill Financials
UPDATE [dbo].[HRA_OFFER_LETTERS]
SET
    [GROSS_SALARY] = TRY_CAST(JSON_VALUE([FORM_DATA], '$.compensation.grossSalary') AS DECIMAL(18,2)),
    [ANNUAL_CTC]   = COALESCE(
                        TRY_CAST(JSON_VALUE([FORM_DATA], '$.compensation.annualCTC') AS DECIMAL(18,2)),
                        TRY_CAST(JSON_VALUE([FORM_DATA], '$.compensation.totalCTC') AS DECIMAL(18,2)) * 12,
                        TRY_CAST(JSON_VALUE([FORM_DATA], '$.totalCTC') AS DECIMAL(18,2))
                     ),
    [NET_SALARY]   = TRY_CAST(JSON_VALUE([FORM_DATA], '$.compensation.netSalary') AS DECIMAL(18,2)),
    [MONTHLY_CTC]  = COALESCE(
                        TRY_CAST(JSON_VALUE([FORM_DATA], '$.compensation.totalCTC') AS DECIMAL(18,2)),
                        TRY_CAST(JSON_VALUE([FORM_DATA], '$.compensation.annualCTC') AS DECIMAL(18,2)) / 12
                     )
WHERE [GROSS_SALARY] IS NULL AND [FORM_DATA] IS NOT NULL;

-- Backfill Job & Timeline
UPDATE [dbo].[HRA_OFFER_LETTERS]
SET
    [EMAIL]                   = COALESCE([EMAIL], JSON_VALUE([FORM_DATA], '$.email')),
    [PHONE]                   = COALESCE([PHONE], JSON_VALUE([FORM_DATA], '$.phone')),
    [EMPLOYMENT_TYPE]         = COALESCE([EMPLOYMENT_TYPE], JSON_VALUE([FORM_DATA], '$.employmentType')),
    [WORK_LOCATION]           = COALESCE([WORK_LOCATION], JSON_VALUE([FORM_DATA], '$.workLocation')),
    [GRADE]                   = COALESCE([GRADE], JSON_VALUE([FORM_DATA], '$.grade')),
    [JOINING_DATE]            = COALESCE([JOINING_DATE], TRY_CAST(JSON_VALUE([FORM_DATA], '$.joiningDate') AS DATE)),
    [PROBATION_PERIOD_MONTHS] = COALESCE([PROBATION_PERIOD_MONTHS], TRY_CAST(JSON_VALUE([FORM_DATA], '$.probationPeriod') AS INT))
WHERE [FORM_DATA] IS NOT NULL;

-- Backfill Company Snapshot
UPDATE [dbo].[HRA_OFFER_LETTERS]
SET
    [COMPANY_NAME]          = COALESCE([COMPANY_NAME], JSON_VALUE([FORM_DATA], '$.companyInfo.companyName')),
    [COMPANY_ADDRESS]       = COALESCE([COMPANY_ADDRESS], JSON_VALUE([FORM_DATA], '$.companyInfo.companyAddress')),
    [SIGNATORY_NAME]        = COALESCE([SIGNATORY_NAME], JSON_VALUE([FORM_DATA], '$.companyInfo.hrName'), JSON_VALUE([FORM_DATA], '$.signatory.hrName')),
    [SIGNATORY_DESIGNATION] = COALESCE([SIGNATORY_DESIGNATION], JSON_VALUE([FORM_DATA], '$.companyInfo.hrDesignation'), JSON_VALUE([FORM_DATA], '$.signatory.hrDesignation'))
WHERE [FORM_DATA] IS NOT NULL;

-- Backfill APPLICANT_ID by matching Candidate Code or Employee Code
UPDATE hol
SET hol.[APPLICANT_ID] = emp.[ID]
FROM [dbo].[HRA_OFFER_LETTERS] AS hol
INNER JOIN [dbo].[HR_EMPLOYEE] AS emp
    ON (hol.[EMPLOYEE_CODE] IS NOT NULL AND (emp.[APPLICANT_CODE] = hol.[EMPLOYEE_CODE] OR emp.[EMP_CODE] = hol.[EMPLOYEE_CODE]))
    OR (JSON_VALUE(hol.[FORM_DATA], '$.candidateCode') IS NOT NULL AND (emp.[APPLICANT_CODE] = JSON_VALUE(hol.[FORM_DATA], '$.candidateCode') OR emp.[EMP_CODE] = JSON_VALUE(hol.[FORM_DATA], '$.candidateCode')))
WHERE hol.[APPLICANT_ID] IS NULL;

-- Backfill DEPARTMENT_ID
UPDATE hol
SET hol.[DEPARTMENT_ID] = d.[ID]
FROM [dbo].[HRA_OFFER_LETTERS] AS hol
INNER JOIN [dbo].[HR_DEPARTMENT] AS d
    ON (hol.[DEPARTMENT] IS NOT NULL AND UPPER(d.[DEPARTMENT_NAME]) = UPPER(hol.[DEPARTMENT]))
    OR (JSON_VALUE(hol.[FORM_DATA], '$.department') IS NOT NULL AND UPPER(d.[DEPARTMENT_NAME]) = UPPER(JSON_VALUE(hol.[FORM_DATA], '$.department')))
WHERE hol.[DEPARTMENT_ID] IS NULL;

-- Backfill DESIGNATION_ID
UPDATE hol
SET hol.[DESIGNATION_ID] = des.[ID]
FROM [dbo].[HRA_OFFER_LETTERS] AS hol
INNER JOIN [dbo].[HR_DESIGNATION] AS des
    ON (hol.[DESIGNATION] IS NOT NULL AND UPPER(des.[DESIGNATION_NAME]) = UPPER(hol.[DESIGNATION]))
    OR (JSON_VALUE(hol.[FORM_DATA], '$.designation') IS NOT NULL AND UPPER(des.[DESIGNATION_NAME]) = UPPER(JSON_VALUE(hol.[FORM_DATA], '$.designation')))
WHERE hol.[DESIGNATION_ID] IS NULL;

-- Backfill STATUS_ID from AD_STATUS_MASTER
UPDATE hol
SET hol.[STATUS_ID] = sm.[ID]
FROM [dbo].[HRA_OFFER_LETTERS] AS hol
INNER JOIN [dbo].[AD_STATUS_MASTER] AS sm
    ON UPPER(sm.[NAME]) = UPPER(COALESCE(hol.[STATUS], JSON_VALUE(hol.[FORM_DATA], '$.status'), 'Draft'))
WHERE hol.[STATUS_ID] IS NULL;

-- If status name aliases exist, map them to AD_STATUS_MASTER
UPDATE [dbo].[HRA_OFFER_LETTERS]
SET [STATUS_ID] = (SELECT TOP 1 [ID] FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) IN ('DRAFT', 'PENDING') ORDER BY [ID] ASC)
WHERE [STATUS_ID] IS NULL AND UPPER(COALESCE([STATUS], JSON_VALUE([FORM_DATA], '$.status'), '')) IN ('DRAFT', 'PENDING', 'OPEN');

UPDATE [dbo].[HRA_OFFER_LETTERS]
SET [STATUS_ID] = (SELECT TOP 1 [ID] FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) IN ('APPROVED', 'VERIFIED') ORDER BY [ID] ASC)
WHERE [STATUS_ID] IS NULL AND UPPER(COALESCE([STATUS], JSON_VALUE([FORM_DATA], '$.status'), '')) IN ('APPROVED', 'VERIFIED', 'CONFIRM');

UPDATE [dbo].[HRA_OFFER_LETTERS]
SET [STATUS_ID] = (SELECT TOP 1 [ID] FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) IN ('SENT', 'EMAIL SENT') ORDER BY [ID] ASC)
WHERE [STATUS_ID] IS NULL AND UPPER(COALESCE([STATUS], JSON_VALUE([FORM_DATA], '$.status'), '')) IN ('SENT', 'EMAIL SENT');

UPDATE [dbo].[HRA_OFFER_LETTERS]
SET [STATUS_ID] = (SELECT TOP 1 [ID] FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) IN ('ACCEPTED', 'CANDIDATE ACCEPTED') ORDER BY [ID] ASC)
WHERE [STATUS_ID] IS NULL AND UPPER(COALESCE([STATUS], JSON_VALUE([FORM_DATA], '$.status'), '')) IN ('ACCEPTED', 'CANDIDATE ACCEPTED');

UPDATE [dbo].[HRA_OFFER_LETTERS]
SET [STATUS_ID] = (SELECT TOP 1 [ID] FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) IN ('REJECTED') ORDER BY [ID] ASC)
WHERE [STATUS_ID] IS NULL AND UPPER(COALESCE([STATUS], JSON_VALUE([FORM_DATA], '$.status'), '')) IN ('REJECTED');

-- Fallback any remaining NULL STATUS_ID to Draft
UPDATE [dbo].[HRA_OFFER_LETTERS]
SET [STATUS_ID] = (SELECT TOP 1 [ID] FROM [dbo].[AD_STATUS_MASTER] WHERE UPPER([NAME]) IN ('DRAFT', 'PENDING') ORDER BY [ID] ASC)
WHERE [STATUS_ID] IS NULL;
GO

-- 4. ESTABLISH FOREIGN KEY CONSTRAINTS (IDEMPOTENT)
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HRA_OFFER_LETTERS_APPLICANT_ID')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS]
    ADD CONSTRAINT [FK_HRA_OFFER_LETTERS_APPLICANT_ID]
    FOREIGN KEY ([APPLICANT_ID]) REFERENCES [dbo].[HR_EMPLOYEE] ([ID])
    ON DELETE NO ACTION;
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HRA_OFFER_LETTERS_DEPT_ID')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS]
    ADD CONSTRAINT [FK_HRA_OFFER_LETTERS_DEPT_ID]
    FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[HR_DEPARTMENT] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HRA_OFFER_LETTERS_DESIG_ID')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS]
    ADD CONSTRAINT [FK_HRA_OFFER_LETTERS_DESIG_ID]
    FOREIGN KEY ([DESIGNATION_ID]) REFERENCES [dbo].[HR_DESIGNATION] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HRA_OFFER_LETTERS_STATUS_ID')
BEGIN
    ALTER TABLE [dbo].[HRA_OFFER_LETTERS]
    ADD CONSTRAINT [FK_HRA_OFFER_LETTERS_STATUS_ID]
    FOREIGN KEY ([STATUS_ID]) REFERENCES [dbo].[AD_STATUS_MASTER] ([ID]);
END
GO

-- 5. OPTIMIZE INDEXES
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HRA_OFFER_LETTERS_APPLICANT_STATUS' AND object_id = OBJECT_ID('[dbo].[HRA_OFFER_LETTERS]'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_HRA_OFFER_LETTERS_APPLICANT_STATUS]
    ON [dbo].[HRA_OFFER_LETTERS] ([APPLICANT_ID] ASC, [STATUS_ID] ASC)
    INCLUDE ([REF_NO], [LETTER_DATE], [JOINING_DATE], [ANNUAL_CTC], [GROSS_SALARY]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_HRA_OFFER_LETTERS_REF_NO' AND object_id = OBJECT_ID('[dbo].[HRA_OFFER_LETTERS]'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UQ_HRA_OFFER_LETTERS_REF_NO]
    ON [dbo].[HRA_OFFER_LETTERS] ([REF_NO])
    WHERE [LETTER_TYPE] = 'OFFER_LETTER';
END
GO
