IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLI_CLIENT_SERVER_CONFIG]') AND type in (N'U'))
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[CLI_CLIENT_SERVER_CONFIG]') AND name = 'SERVER_PORT')
    BEGIN
        ALTER TABLE [dbo].[CLI_CLIENT_SERVER_CONFIG] ADD [SERVER_PORT] INT NULL;
    END
END
GO
