IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'NC_REMARKS' AND Object_ID = Object_ID(N'QMC_QUALITY_INSPECTION'))
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION ADD NC_REMARKS NVARCHAR(250) NULL;
END
