-- Migration Script: Add Q20_WILLING_ROTATIONAL_SHIFTS to HR_EMPLOYEE_SELF_ASSESSMENT table
-- Standard: Fully idempotent guard check

IF NOT EXISTS (
    SELECT * 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'HR_EMPLOYEE_SELF_ASSESSMENT' 
      AND COLUMN_NAME = 'Q20_WILLING_ROTATIONAL_SHIFTS'
)
BEGIN
    ALTER TABLE HR_EMPLOYEE_SELF_ASSESSMENT
    ADD Q20_WILLING_ROTATIONAL_SHIFTS NVARCHAR(20) NULL;
END;
GO

