-- =============================================================================
-- Migration: V1159.0 - Alter Parameter Columns Length in QMC_INSPECTION_SPECIFICATION_DETAIL
-- Date: 20260821
-- Description: Alters PARAMETER_ALIAS and PARAMETER_NAME columns to NVARCHAR(1000)
--              to prevent truncation errors.
-- =============================================================================

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QMC_INSPECTION_SPECIFICATION_DETAIL')
BEGIN
    -- 1. Alter PARAMETER_ALIAS
    IF EXISTS (
        SELECT 1 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_NAME = 'QMC_INSPECTION_SPECIFICATION_DETAIL' 
          AND COLUMN_NAME = 'PARAMETER_ALIAS' 
          AND (CHARACTER_MAXIMUM_LENGTH IS NULL OR CHARACTER_MAXIMUM_LENGTH < 1000)
    )
    BEGIN
        ALTER TABLE QMC_INSPECTION_SPECIFICATION_DETAIL
        ALTER COLUMN PARAMETER_ALIAS NVARCHAR(1000) NULL;
    END

    -- 2. Alter PARAMETER_NAME
    IF EXISTS (
        SELECT 1 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_NAME = 'QMC_INSPECTION_SPECIFICATION_DETAIL' 
          AND COLUMN_NAME = 'PARAMETER_NAME' 
          AND (CHARACTER_MAXIMUM_LENGTH IS NULL OR CHARACTER_MAXIMUM_LENGTH < 1000)
    )
    BEGIN
        ALTER TABLE QMC_INSPECTION_SPECIFICATION_DETAIL
        ALTER COLUMN PARAMETER_NAME NVARCHAR(1000) NOT NULL;
    END
END
GO
