-- V1026.0: Add verification columns and reject reason to HR_LEAVE_APPLICATION table

IF OBJECT_ID('dbo.HR_LEAVE_APPLICATION', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'HR_LEAVE_APPLICATION' AND COLUMN_NAME = 'VERIFIED_BY'
    )
    BEGIN
        EXEC('ALTER TABLE HR_LEAVE_APPLICATION ADD VERIFIED_BY NVARCHAR(50) NULL;');
        PRINT 'Added VERIFIED_BY column';
    END

    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'HR_LEAVE_APPLICATION' AND COLUMN_NAME = 'VERIFIED_DATE'
    )
    BEGIN
        EXEC('ALTER TABLE HR_LEAVE_APPLICATION ADD VERIFIED_DATE DATETIME NULL;');
        PRINT 'Added VERIFIED_DATE column';
    END

    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'HR_LEAVE_APPLICATION' AND COLUMN_NAME = 'REJECT_REASON'
    )
    BEGIN
        EXEC('ALTER TABLE HR_LEAVE_APPLICATION ADD REJECT_REASON NVARCHAR(500) NULL;');
        PRINT 'Added REJECT_REASON column';
    END
END
