-- Migration: Add ENQ_ENTRY_NO and linking columns to AD_OCR_PROCESSING_REQUEST and SALES_ENQUIRY tables
-- Database: AT_NUTECH

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('AD_OCR_PROCESSING_REQUEST') AND name = 'ENQ_ENTRY_NO')
BEGIN
    ALTER TABLE AD_OCR_PROCESSING_REQUEST ADD ENQ_ENTRY_NO NVARCHAR(50) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('AD_OCR_PROCESSING_REQUEST') AND name = 'SM_ENQUIRY_ID')
BEGIN
    ALTER TABLE AD_OCR_PROCESSING_REQUEST ADD SM_ENQUIRY_ID BIGINT NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('AD_OCR_PROCESSING_REQUEST') AND name = 'QUOTE_ENTRY_NO')
BEGIN
    ALTER TABLE AD_OCR_PROCESSING_REQUEST ADD QUOTE_ENTRY_NO NVARCHAR(50) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('AD_OCR_PROCESSING_REQUEST') AND name = 'SALE_ORDER_ENTRY_NO')
BEGIN
    ALTER TABLE AD_OCR_PROCESSING_REQUEST ADD SALE_ORDER_ENTRY_NO NVARCHAR(50) NULL;
END;

-- Link columns on SALES_ENQUIRY_HEADER
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SALES_ENQUIRY_HEADER') AND name = 'OCR_REQUEST_ID')
BEGIN
    ALTER TABLE SALES_ENQUIRY_HEADER ADD OCR_REQUEST_ID BIGINT NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SALES_ENQUIRY_HEADER') AND name = 'EMAIL_MESSAGE_ID')
BEGIN
    ALTER TABLE SALES_ENQUIRY_HEADER ADD EMAIL_MESSAGE_ID NVARCHAR(500) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SALES_ENQUIRY_HEADER') AND name = 'CONVERSATION_THREAD_ID')
BEGIN
    ALTER TABLE SALES_ENQUIRY_HEADER ADD CONVERSATION_THREAD_ID NVARCHAR(500) NULL;
END;

-- Extracted part columns on SALES_ENQUIRY_DETAIL
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SALES_ENQUIRY_DETAIL') AND name = 'PART_NO')
BEGIN
    ALTER TABLE SALES_ENQUIRY_DETAIL ADD PART_NO NVARCHAR(255) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SALES_ENQUIRY_DETAIL') AND name = 'PART_NAME')
BEGIN
    ALTER TABLE SALES_ENQUIRY_DETAIL ADD PART_NAME NVARCHAR(500) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SALES_ENQUIRY_DETAIL') AND name = 'OEM_PART_NO')
BEGIN
    ALTER TABLE SALES_ENQUIRY_DETAIL ADD OEM_PART_NO NVARCHAR(255) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SALES_ENQUIRY_DETAIL') AND name = 'IPP_PART_NO')
BEGIN
    ALTER TABLE SALES_ENQUIRY_DETAIL ADD IPP_PART_NO NVARCHAR(255) NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SALES_ENQUIRY_DETAIL') AND name = 'REMARKS')
BEGIN
    ALTER TABLE SALES_ENQUIRY_DETAIL ADD REMARKS NVARCHAR(MAX) NULL;
END;
