-- Migration: Add AQL_ID to QMC_INSPECTION_SPECIFICATION table
-- Date: 2026-08-24
IF COL_LENGTH('QMC_INSPECTION_SPECIFICATION', 'AQL_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[QMC_INSPECTION_SPECIFICATION] ADD [AQL_ID] [bigint] NULL;
END
GO

IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys 
    WHERE object_id = OBJECT_ID(N'[dbo].[FK_QMC_INSP_SPEC_AQL]') 
    AND parent_object_id = OBJECT_ID(N'[dbo].[QMC_INSPECTION_SPECIFICATION]')
)
BEGIN
    ALTER TABLE [dbo].[QMC_INSPECTION_SPECIFICATION] WITH CHECK ADD CONSTRAINT [FK_QMC_INSP_SPEC_AQL] FOREIGN KEY([AQL_ID])
    REFERENCES [dbo].[QMC_AQL_MASTER] ([ID]);
END
GO
