INSERT INTO MST_COUNTRY
(
    COUNTRY_NAME,
    STATUS,
    CREATED_BY,
    CREATED_DATE,
    IS_ACTIVE,
    COUNTRY_CODE,
    PHONE_MIN_LENGTH,
    PHONE_MAX_LENGTH,
    COUNTRY_ISO,
    ISD
)
SELECT
    V.COUNTRY_NAME,
    V.STATUS,
    'SYSTEM',
    GETDATE(),
    1,
    V.COUNTRY_CODE,
    7,
    15,
    V.COUNTRY_ISO,
    V.ISD
FROM
(
    VALUES
    ('AFGHANISTAN', 'ACTIVE', 'AFG', 'AF', '+93'),
    ('ALBANIA', 'ACTIVE', 'ALB', 'AL', '+355'),
    ('ALGERIA', 'ACTIVE', 'DZA', 'DZ', '+213'),
    ('ANDORRA', 'ACTIVE', 'AND', 'AD', '+376'),
    ('ANGOLA', 'ACTIVE', 'AGO', 'AO', '+244'),
    ('ANTIGUA AND BARBUDA', 'ACTIVE', 'ATG', 'AG', '+1-268'),
    ('ARGENTINA', 'ACTIVE', 'ARG', 'AR', '+54'),
    ('ARMENIA', 'ACTIVE', 'ARM', 'AM', '+374'),
    ('AUSTRALIA', 'ACTIVE', 'AUS', 'AU', '+61'),
    ('AUSTRIA', 'ACTIVE', 'AUT', 'AT', '+43'),
    ('AZERBAIJAN', 'ACTIVE', 'AZE', 'AZ', '+994'),
    ('BAHAMAS', 'ACTIVE', 'BHS', 'BS', '+1-242'),
    ('BAHRAIN', 'ACTIVE', 'BHR', 'BH', '+973'),
    ('BANGLADESH', 'ACTIVE', 'BGD', 'BD', '+880'),
    ('BARBADOS', 'ACTIVE', 'BRB', 'BB', '+1-246'),
    ('BELARUS', 'ACTIVE', 'BLR', 'BY', '+375'),
    ('BELGIUM', 'ACTIVE', 'BEL', 'BE', '+32'),
    ('BELIZE', 'ACTIVE', 'BLZ', 'BZ', '+501'),
    ('BENIN', 'ACTIVE', 'BEN', 'BJ', '+229'),
    ('BHUTAN', 'ACTIVE', 'BTN', 'BT', '+975'),
    ('BOLIVIA', 'ACTIVE', 'BOL', 'BO', '+591'),
    ('BOSNIA AND HERZEGOVINA', 'ACTIVE', 'BIH', 'BA', '+387'),
    ('BOTSWANA', 'ACTIVE', 'BWA', 'BW', '+267'),
    ('BRAZIL', 'ACTIVE', 'BRA', 'BR', '+55'),
    ('BRUNEI', 'ACTIVE', 'BRN', 'BN', '+673'),
    ('BULGARIA', 'ACTIVE', 'BGR', 'BG', '+359'),
    ('BURKINA FASO', 'ACTIVE', 'BFA', 'BF', '+226'),
    ('BURUNDI', 'ACTIVE', 'BDI', 'BI', '+257'),
    ('CAMBODIA', 'ACTIVE', 'KHM', 'KH', '+855'),
    ('CAMEROON', 'ACTIVE', 'CMR', 'CM', '+237'),
    ('CANADA', 'ACTIVE', 'CAN', 'CA', '+1'),
    ('CHILE', 'ACTIVE', 'CHL', 'CL', '+56'),
    ('CHINA', 'ACTIVE', 'CHN', 'CN', '+86'),
    ('COLOMBIA', 'ACTIVE', 'COL', 'CO', '+57'),
    ('COSTA RICA', 'ACTIVE', 'CRI', 'CR', '+506'),
    ('CROATIA', 'ACTIVE', 'HRV', 'HR', '+385'),
    ('CUBA', 'ACTIVE', 'CUB', 'CU', '+53'),
    ('CYPRUS', 'ACTIVE', 'CYP', 'CY', '+357'),
    ('CZECH REPUBLIC', 'ACTIVE', 'CZE', 'CZ', '+420'),
    ('DENMARK', 'ACTIVE', 'DNK', 'DK', '+45'),
    ('DOMINICA', 'ACTIVE', 'DMA', 'DM', '+1-767'),
    ('DOMINICAN REPUBLIC', 'ACTIVE', 'DOM', 'DO', '+1-809'),
    ('ECUADOR', 'ACTIVE', 'ECU', 'EC', '+593'),
    ('EGYPT', 'ACTIVE', 'EGY', 'EG', '+20'),
    ('ESTONIA', 'ACTIVE', 'EST', 'EE', '+372'),
    ('ETHIOPIA', 'ACTIVE', 'ETH', 'ET', '+251'),
    ('FIJI', 'ACTIVE', 'FJI', 'FJ', '+679'),
    ('FINLAND', 'ACTIVE', 'FIN', 'FI', '+358'),
    ('FRANCE', 'ACTIVE', 'FRA', 'FR', '+33'),
    ('GEORGIA', 'ACTIVE', 'GEO', 'GE', '+995'),
    ('GERMANY', 'ACTIVE', 'DEU', 'DE', '+49'),
    ('GHANA', 'ACTIVE', 'GHA', 'GH', '+233'),
    ('GREECE', 'ACTIVE', 'GRC', 'GR', '+30'),
    ('GUATEMALA', 'ACTIVE', 'GTM', 'GT', '+502'),
    ('HAITI', 'ACTIVE', 'HTI', 'HT', '+509'),
    ('HONDURAS', 'ACTIVE', 'HND', 'HN', '+504'),
    ('HUNGARY', 'ACTIVE', 'HUN', 'HU', '+36'),
    ('ICELAND', 'ACTIVE', 'ISL', 'IS', '+354'),
    ('INDIA', 'ACTIVE', 'IND', 'IN', '+91'),
    ('INDONESIA', 'ACTIVE', 'IDN', 'ID', '+62'),
    ('IRAN', 'ACTIVE', 'IRN', 'IR', '+98'),
    ('IRAQ', 'ACTIVE', 'IRQ', 'IQ', '+964'),
    ('IRELAND', 'ACTIVE', 'IRL', 'IE', '+353'),
    ('ISRAEL', 'ACTIVE', 'ISR', 'IL', '+972'),
    ('ITALY', 'ACTIVE', 'ITA', 'IT', '+39'),
    ('JAMAICA', 'ACTIVE', 'JAM', 'JM', '+1-876'),
    ('JAPAN', 'ACTIVE', 'JPN', 'JP', '+81'),
    ('JORDAN', 'ACTIVE', 'JOR', 'JO', '+962'),
    ('KAZAKHSTAN', 'ACTIVE', 'KAZ', 'KZ', '+7'),
    ('KENYA', 'ACTIVE', 'KEN', 'KE', '+254'),
    ('KUWAIT', 'ACTIVE', 'KWT', 'KW', '+965'),
    ('KYRGYZSTAN', 'ACTIVE', 'KGZ', 'KG', '+996'),
    ('LAOS', 'ACTIVE', 'LAO', 'LA', '+856'),
    ('LATVIA', 'ACTIVE', 'LVA', 'LV', '+371'),
    ('LEBANON', 'ACTIVE', 'LBN', 'LB', '+961'),
    ('LIBYA', 'ACTIVE', 'LBY', 'LY', '+218'),
    ('LITHUANIA', 'ACTIVE', 'LTU', 'LT', '+370'),
    ('LUXEMBOURG', 'ACTIVE', 'LUX', 'LU', '+352'),
    ('MADAGASCAR', 'ACTIVE', 'MDG', 'MG', '+261'),
    ('MALAWI', 'ACTIVE', 'MWI', 'MW', '+265'),
    ('MALAYSIA', 'ACTIVE', 'MYS', 'MY', '+60'),
    ('MALDIVES', 'ACTIVE', 'MDV', 'MV', '+960'),
    ('MALI', 'ACTIVE', 'MLI', 'ML', '+223'),
    ('MALTA', 'ACTIVE', 'MLT', 'MT', '+356'),
    ('MAURITIUS', 'ACTIVE', 'MUS', 'MU', '+230'),
    ('MEXICO', 'ACTIVE', 'MEX', 'MX', '+52'),
    ('MOLDOVA', 'ACTIVE', 'MDA', 'MD', '+373'),
    ('MONACO', 'ACTIVE', 'MCO', 'MC', '+377'),
    ('MONGOLIA', 'ACTIVE', 'MNG', 'MN', '+976'),
    ('MONTENEGRO', 'ACTIVE', 'MNE', 'ME', '+382'),
    ('MOROCCO', 'ACTIVE', 'MAR', 'MA', '+212'),
    ('MOZAMBIQUE', 'ACTIVE', 'MOZ', 'MZ', '+258'),
    ('MYANMAR', 'ACTIVE', 'MMR', 'MM', '+95'),
    ('NAMIBIA', 'ACTIVE', 'NAM', 'NA', '+264'),
    ('NEPAL', 'ACTIVE', 'NPL', 'NP', '+977'),
    ('NETHERLANDS', 'ACTIVE', 'NLD', 'NL', '+31'),
    ('NEW ZEALAND', 'ACTIVE', 'NZL', 'NZ', '+64'),
    ('NICARAGUA', 'ACTIVE', 'NIC', 'NI', '+505'),
    ('NIGER', 'ACTIVE', 'NER', 'NE', '+227'),
    ('NIGERIA', 'ACTIVE', 'NGA', 'NG', '+234'),
    ('NORWAY', 'ACTIVE', 'NOR', 'NO', '+47'),
    ('OMAN', 'ACTIVE', 'OMN', 'OM', '+968'),
    ('PAKISTAN', 'ACTIVE', 'PAK', 'PK', '+92'),
    ('PANAMA', 'ACTIVE', 'PAN', 'PA', '+507'),
    ('PARAGUAY', 'ACTIVE', 'PRY', 'PY', '+595'),
    ('PERU', 'ACTIVE', 'PER', 'PE', '+51'),
    ('PHILIPPINES', 'ACTIVE', 'PHL', 'PH', '+63'),
    ('POLAND', 'ACTIVE', 'POL', 'PL', '+48'),
    ('PORTUGAL', 'ACTIVE', 'PRT', 'PT', '+351'),
    ('QATAR', 'ACTIVE', 'QAT', 'QA', '+974'),
    ('ROMANIA', 'ACTIVE', 'ROU', 'RO', '+40'),
    ('RUSSIA', 'ACTIVE', 'RUS', 'RU', '+7'),
    ('RWANDA', 'ACTIVE', 'RWA', 'RW', '+250'),
    ('SAUDI ARABIA', 'ACTIVE', 'SAU', 'SA', '+966'),
    ('SENEGAL', 'ACTIVE', 'SEN', 'SN', '+221'),
    ('SERBIA', 'ACTIVE', 'SRB', 'RS', '+381'),
    ('SINGAPORE', 'ACTIVE', 'SGP', 'SG', '+65'),
    ('SLOVAKIA', 'ACTIVE', 'SVK', 'SK', '+421'),
    ('SLOVENIA', 'ACTIVE', 'SVN', 'SI', '+386'),
    ('SOMALIA', 'ACTIVE', 'SOM', 'SO', '+252'),
    ('SOUTH AFRICA', 'ACTIVE', 'ZAF', 'ZA', '+27'),
    ('SOUTH KOREA', 'ACTIVE', 'KOR', 'KR', '+82'),
    ('SPAIN', 'ACTIVE', 'ESP', 'ES', '+34'),
    ('SRI LANKA', 'ACTIVE', 'LKA', 'LK', '+94'),
    ('SUDAN', 'ACTIVE', 'SDN', 'SD', '+249'),
    ('SWEDEN', 'ACTIVE', 'SWE', 'SE', '+46'),
    ('SWITZERLAND', 'ACTIVE', 'CHE', 'CH', '+41'),
    ('TAIWAN', 'ACTIVE', 'TWN', 'TW', '+886'),
    ('TAJIKISTAN', 'ACTIVE', 'TJK', 'TJ', '+992'),
    ('TANZANIA', 'ACTIVE', 'TZA', 'TZ', '+255'),
    ('THAILAND', 'ACTIVE', 'THA', 'TH', '+66'),
    ('TUNISIA', 'ACTIVE', 'TUN', 'TN', '+216'),
    ('TURKEY', 'ACTIVE', 'TUR', 'TR', '+90'),
    ('TURKMENISTAN', 'ACTIVE', 'TKM', 'TM', '+993'),
    ('UGANDA', 'ACTIVE', 'UGA', 'UG', '+256'),
    ('UKRAINE', 'ACTIVE', 'UKR', 'UA', '+380'),
    ('UNITED ARAB EMIRATES', 'ACTIVE', 'ARE', 'AE', '+971'),
    ('UNITED KINGDOM', 'ACTIVE', 'GBR', 'GB', '+44'),
    ('UNITED STATES', 'ACTIVE', 'USA', 'US', '+1'),
    ('URUGUAY', 'ACTIVE', 'URY', 'UY', '+598'),
    ('UZBEKISTAN', 'ACTIVE', 'UZB', 'UZ', '+998'),
    ('VENEZUELA', 'ACTIVE', 'VEN', 'VE', '+58'),
    ('VIETNAM', 'ACTIVE', 'VNM', 'VN', '+84'),
    ('YEMEN', 'ACTIVE', 'YEM', 'YE', '+967'),
    ('ZAMBIA', 'ACTIVE', 'ZMB', 'ZM', '+260'),
    ('ZIMBABWE', 'ACTIVE', 'ZWE', 'ZW', '+263')
) V
(
    COUNTRY_NAME,
    STATUS,
    COUNTRY_CODE,
    COUNTRY_ISO,
    ISD
)
WHERE NOT EXISTS
(
    SELECT 1
    FROM MST_COUNTRY C
    WHERE UPPER(C.COUNTRY_ISO) = V.COUNTRY_ISO
);

---- STATE
INSERT INTO MST_STATE
(
    COUNTRY_NAME,
    STATE_NAME,
    STATE_CODE,
    STATUS,
    CREATED_BY,
    CREATED_DATE,
    IS_ACTIVE
)
SELECT
    'INDIA',
    V.STATE_NAME,
    V.STATE_CODE,
    'ACTIVE',
    'SYSTEM',
    GETDATE(),
    1
FROM
(
    VALUES
    ('JAMMU AND KASHMIR', '01'),
    ('HIMACHAL PRADESH', '02'),
    ('PUNJAB', '03'),
    ('CHANDIGARH', '04'),
    ('UTTARAKHAND', '05'),
    ('HARYANA', '06'),
    ('DELHI', '07'),
    ('RAJASTHAN', '08'),
    ('UTTAR PRADESH', '09'),
    ('BIHAR', '10'),
    ('SIKKIM', '11'),
    ('ARUNACHAL PRADESH', '12'),
    ('NAGALAND', '13'),
    ('MANIPUR', '14'),
    ('MIZORAM', '15'),
    ('TRIPURA', '16'),
    ('MEGHALAYA', '17'),
    ('ASSAM', '18'),
    ('WEST BENGAL', '19'),
    ('JHARKHAND', '20'),
    ('ODISHA', '21'),
    ('CHHATTISGARH', '22'),
    ('MADHYA PRADESH', '23'),
    ('GUJARAT', '24'),
    ('DAMAN AND DIU', '25'),
    ('DADRA AND NAGAR HAVELI', '26'),
    ('MAHARASHTRA', '27'),
    ('ANDHRA PRADESH', '28'),
    ('KARNATAKA', '29'),
    ('GOA', '30'),
    ('LAKSHADWEEP', '31'),
    ('KERALA', '32'),
    ('TAMIL NADU', '33'),
    ('PUDUCHERRY', '34'),
    ('ANDAMAN AND NICOBAR ISLANDS', '35'),
    ('TELANGANA', '36'),
    ('ANDHRA PRADESH', '37'),
    ('LADAKH', '38')
) V
(
    STATE_NAME,
    STATE_CODE
)
WHERE NOT EXISTS
(
    SELECT 1
    FROM MST_STATE S
    WHERE UPPER(S.COUNTRY_NAME) = 'INDIA'
      AND UPPER(S.STATE_CODE) = V.STATE_CODE
);

---CITY
INSERT INTO MST_CITY_MASTER
(
    CODE,
    CITY_NAME,
    STATE_NAME,
    STATUS,
    CREATED_BY,
    CREATED_DATE
)
SELECT
    V.CODE,
    V.CITY_NAME,
    V.STATE_NAME,
    '0',
    'SYSTEM',
    GETDATE()
FROM
(
    VALUES

    -- ANDHRA PRADESH
    ('APVJA1','VIJAYAWADA','ANDHRA PRADESH'),
    ('APVSKH1','VISAKHAPATNAM','ANDHRA PRADESH'),
    ('APGNT01','GUNTUR','ANDHRA PRADESH'),
    ('APTPTY1','TIRUPATI','ANDHRA PRADESH'),
    ('APKAKN1','KAKINADA','ANDHRA PRADESH'),
    ('APNEL01','NELLORE','ANDHRA PRADESH'),
    ('APKUR01','KURNOOL','ANDHRA PRADESH'),
    ('APRAJ01','RAJAHMUNDRY','ANDHRA PRADESH'),
    ('APANA01','ANANTAPUR','ANDHRA PRADESH'),
    ('APONG01','ONGOLE','ANDHRA PRADESH'),

    -- ARUNACHAL PRADESH
    ('APITN01','ITANAGAR','ARUNACHAL PRADESH'),
    ('APNHL01','NAHARLAGUN','ARUNACHAL PRADESH'),
    ('APTPR01','TAWANG','ARUNACHAL PRADESH'),

    -- ASSAM
    ('ASGWH01','GUWAHATI','ASSAM'),
    ('ASDIB01','DIBRUGARH','ASSAM'),
    ('ASJRH01','JORHAT','ASSAM'),
    ('ASSLB01','SILCHAR','ASSAM'),
    ('ASTZP01','TEZPUR','ASSAM'),

    -- BIHAR
    ('BHPAT01','PATNA','BIHAR'),
    ('BHGYA01','GAYA','BIHAR'),
    ('BHBGP01','BHAGALPUR','BIHAR'),
    ('BHMZP01','MUZAFFARPUR','BIHAR'),
    ('BHDPR01','DARBHANGA','BIHAR'),
    ('BHARA01','ARRAH','BIHAR'),
    ('BHBEG01','BEGUSARAI','BIHAR'),

    -- CHHATTISGARH
    ('CGRAI01','RAIPUR','CHHATTISGARH'),
    ('CGBSP01','BILASPUR','CHHATTISGARH'),
    ('CGDUR01','DURG','CHHATTISGARH'),
    ('CGBHL01','BHILAI','CHHATTISGARH'),
    ('CGKOR01','KORBA','CHHATTISGARH'),
    ('CGJGP01','JAGDALPUR','CHHATTISGARH'),

    -- GOA
    ('GAPNJ01','PANAJI','GOA'),
    ('GAMRG01','MARGAO','GOA'),
    ('GAVSG01','VASCO DA GAMA','GOA'),

    -- GUJARAT
    ('GJAMD01','AHMEDABAD','GUJARAT'),
    ('GJSRT01','SURAT','GUJARAT'),
    ('GJVD01','VADODARA','GUJARAT'),
    ('GJRJK01','RAJKOT','GUJARAT'),
    ('GJBNG01','BHAVNAGAR','GUJARAT'),
    ('GJJMN01','JAMNAGAR','GUJARAT'),
    ('GJGAN01','GANDHINAGAR','GUJARAT'),
    ('GJANN01','ANAND','GUJARAT'),
    ('GJBRD01','BHARUCH','GUJARAT'),
    ('GJMSN01','MEHSANA','GUJARAT'),

    -- HARYANA
    ('HRGUR01','GURUGRAM','HARYANA'),
    ('HRFBD01','FARIDABAD','HARYANA'),
    ('HRPCK01','PANCHKULA','HARYANA'),
    ('HRPNP01','PANIPAT','HARYANA'),
    ('HRAMB01','AMBALA','HARYANA'),
    ('HRKRL01','KARNAL','HARYANA'),
    ('HRHTR01','HISAR','HARYANA'),
    ('HRRHT01','ROHTAK','HARYANA'),

    -- HIMACHAL PRADESH
    ('HPSML01','SHIMLA','HIMACHAL PRADESH'),
    ('HPML01','MANALI','HIMACHAL PRADESH'),
    ('HPDHM01','DHARAMSHALA','HIMACHAL PRADESH'),
    ('HPSLN01','SOLAN','HIMACHAL PRADESH'),

    -- JHARKHAND
    ('JHRNC01','RANCHI','JHARKHAND'),
    ('JHAMS01','JAMSHEDPUR','JHARKHAND'),
    ('JHDBD01','DHANBAD','JHARKHAND'),
    ('JHBKR01','BOKARO','JHARKHAND'),
    ('JHDGR01','DEOGHAR','JHARKHAND'),

    -- KARNATAKA
    ('KABLR01','BENGALURU','KARNATAKA'),
    ('KAMYS01','MYSURU','KARNATAKA'),
    ('KAMNG01','MANGALURU','KARNATAKA'),
    ('KAHBL01','HUBBALLI','KARNATAKA'),
    ('KABJP01','BELAGAVI','KARNATAKA'),
    ('KATMP01','TUMAKURU','KARNATAKA'),
    ('KASHV01','SHIVAMOGGA','KARNATAKA'),
    ('KADWD01','DAVANAGERE','KARNATAKA'),
    ('KABDR01','BALLARI','KARNATAKA'),
    ('KAKLR01','KALABURAGI','KARNATAKA'),

    -- KERALA
    ('KLTVM01','THIRUVANANTHAPURAM','KERALA'),
    ('KLCOK01','KOCHI','KERALA'),
    ('KLKZH01','KOZHIKODE','KERALA'),
    ('KLTSR01','THRISSUR','KERALA'),
    ('KLKLM01','KOLLAM','KERALA'),
    ('KLALP01','ALAPPUZHA','KERALA'),
    ('KLKNR01','KANNUR','KERALA'),
    ('KLPKD01','PALAKKAD','KERALA'),
    ('KLCNG01','KOTTAYAM','KERALA'),

    -- MADHYA PRADESH
    ('MPBPL01','BHOPAL','MADHYA PRADESH'),
    ('MPIDR01','INDORE','MADHYA PRADESH'),
    ('MPJBL01','JABALPUR','MADHYA PRADESH'),
    ('MPGWL01','GWALIOR','MADHYA PRADESH'),
    ('MPUJN01','UJJAIN','MADHYA PRADESH'),
    ('MPSGR01','SAGAR','MADHYA PRADESH'),
    ('MPRWA01','REWA','MADHYA PRADESH'),

    -- MAHARASHTRA
    ('MUMBAI1','MUMBAI','MAHARASHTRA'),
    ('MHPN01','PUNE','MAHARASHTRA'),
    ('MHNGP01','NAGPUR','MAHARASHTRA'),
    ('MHNSK01','NASHIK','MAHARASHTRA'),
    ('MHVSH01','VASAI-VIRAR','MAHARASHTRA'),
    ('MHACB01','AURANGABAD','MAHARASHTRA'),
    ('MHKLP01','KOLHAPUR','MAHARASHTRA'),
    ('MHNDP01','NANDED','MAHARASHTRA'),
    ('MHSLP01','SOLAPUR','MAHARASHTRA'),
    ('MHAMR01','AMRAVATI','MAHARASHTRA'),

    -- ODISHA
    ('ODBBS01','BHUBANESWAR','ODISHA'),
    ('ODCTK01','CUTTACK','ODISHA'),
    ('ODRKL01','ROURKELA','ODISHA'),
    ('ODBHR01','BERHAMPUR','ODISHA'),
    ('ODBLS01','BALASORE','ODISHA'),
    ('ODSPD01','SAMBALPUR','ODISHA'),

    -- PUNJAB
    ('PBCHD01','CHANDIGARH','PUNJAB'),
    ('PBLDH01','LUDHIANA','PUNJAB'),
    ('PBAMR01','AMRITSAR','PUNJAB'),
    ('PBJAL01','JALANDHAR','PUNJAB'),
    ('PBPAT01','PATIALA','PUNJAB'),
    ('PBBTN01','BATHINDA','PUNJAB'),

    -- RAJASTHAN
    ('RJJP01','JAIPUR','RAJASTHAN'),
    ('RJJDH01','JODHPUR','RAJASTHAN'),
    ('RJUDR01','UDAIPUR','RAJASTHAN'),
    ('RJKOT01','KOTA','RAJASTHAN'),
    ('RBAJK01','AJMER','RAJASTHAN'),
    ('RBBKN01','BIKANER','RAJASTHAN'),
    ('RJALW01','ALWAR','RAJASTHAN'),
    ('RJBSW01','BHARATPUR','RAJASTHAN'),

    -- TAMIL NADU
    ('TNCHN01','CHENNAI','TAMIL NADU'),
    ('TNMDU01','MADURAI','TAMIL NADU'),
    ('TNCOI01','COIMBATORE','TAMIL NADU'),
    ('TNTCY01','TIRUCHIRAPPALLI','TAMIL NADU'),
    ('TNSLM01','SALEM','TAMIL NADU'),
    ('TNTNV01','TIRUNELVELI','TAMIL NADU'),
    ('TNTNJ01','THANJAVUR','TAMIL NADU'),
    ('TNVEL01','VELLORE','TAMIL NADU'),
    ('TNEDE01','ERODE','TAMIL NADU'),
    ('TNTUT01','THOOTHUKUDI','TAMIL NADU'),
    ('TNDIN01','DINDIGUL','TAMIL NADU'),
    ('TNKRM01','KARUR','TAMIL NADU'),
    ('TNKNY01','KANYAKUMARI','TAMIL NADU'),
    ('TNNMK01','NAMAKKAL','TAMIL NADU'),
    ('TNVPM01','VILLUPURAM','TAMIL NADU'),
    ('TNCUD01','CUDDALORE','TAMIL NADU'),
    ('TNRNP01','RANIPET','TAMIL NADU'),
    ('TNSVP01','SIVAKASI','TAMIL NADU'),
    ('TNHOS01','HOSUR','TAMIL NADU'),
    ('TNODC01','OOTY','TAMIL NADU'),

    -- TELANGANA
    ('TGHYD01','HYDERABAD','TELANGANA'),
    ('TGWRG01','WARANGAL','TELANGANA'),
    ('TGKRM01','KARIMNAGAR','TELANGANA'),
    ('TGNGD01','NIZAMABAD','TELANGANA'),
    ('TGKHM01','KHAMMAM','TELANGANA'),
    ('TGRMG01','RAMAGUNDAM','TELANGANA'),

    -- UTTAR PRADESH
    ('UPLKO01','LUCKNOW','UTTAR PRADESH'),
    ('UPKNP01','KANPUR','UTTAR PRADESH'),
    ('UPGZB01','GHAZIABAD','UTTAR PRADESH'),
    ('UPAGR01','AGRA','UTTAR PRADESH'),
    ('UPVNS01','VARANASI','UTTAR PRADESH'),
    ('UPPRY01','PRAYAGRAJ','UTTAR PRADESH'),
    ('UPMRT01','MEERUT','UTTAR PRADESH'),
    ('UPBRL01','BAREILLY','UTTAR PRADESH'),
    ('UPALD01','ALIGARH','UTTAR PRADESH'),
    ('UPMRA01','MORADABAD','UTTAR PRADESH'),
    ('UPNOD01','NOIDA','UTTAR PRADESH'),
    ('UPGKP01','GORAKHPUR','UTTAR PRADESH'),

    -- UTTARAKHAND
    ('UKDDN01','DEHRADUN','UTTARAKHAND'),
    ('UKHWR01','HARIDWAR','UTTARAKHAND'),
    ('UKHLD01','HALDWANI','UTTARAKHAND'),
    ('UKRSH01','RISHIKESH','UTTARAKHAND'),

    -- WEST BENGAL
    ('WBKOL01','KOLKATA','WEST BENGAL'),
    ('WBSLG01','SILIGURI','WEST BENGAL'),
    ('WBDGP01','DURGAPUR','WEST BENGAL'),
    ('WBASN01','ASANSOL','WEST BENGAL'),
    ('WBDHJ01','DARJEELING','WEST BENGAL'),
    ('WBHWH01','HOWRAH','WEST BENGAL'),

    -- DELHI
    ('DLNDL01','NEW DELHI','DELHI'),

    -- JAMMU AND KASHMIR
    ('JKJMU01','JAMMU','JAMMU AND KASHMIR'),
    ('JKSRI01','SRINAGAR','JAMMU AND KASHMIR'),
    ('JKAN01','ANANTNAG','JAMMU AND KASHMIR'),

    -- LADAKH
    ('LKLEH01','LEH','LADAKH'),
    ('LKARG01','KARGIL','LADAKH'),

    -- CHANDIGARH
    ('CHCHD01','CHANDIGARH','CHANDIGARH'),

    -- PUDUCHERRY
    ('PYPDY01','PUDUCHERRY','PUDUCHERRY'),
    ('PYKAR01','KARAIKAL','PUDUCHERRY'),

    -- ANDAMAN AND NICOBAR
    ('ANPBL01','PORT BLAIR','ANDAMAN AND NICOBAR ISLANDS'),

    -- SIKKIM
    ('SKGNG01','GANGTOK','SIKKIM'),

    -- MEGHALAYA
    ('MLSHL01','SHILLONG','MEGHALAYA'),

    -- TRIPURA
    ('TRAGT01','AGARTALA','TRIPURA'),

    -- MANIPUR
    ('MNIMP01','IMPHAL','MANIPUR'),

    -- MIZORAM
    ('MZAIZ01','AIZAWL','MIZORAM'),

    -- NAGALAND
    ('NKOHM01','KOHIMA','NAGALAND'),
    ('NKDMP01','DIMAPUR','NAGALAND'),

    -- ARUNACHAL PRADESH
    ('APITN02','ITANAGAR','ARUNACHAL PRADESH'),

    -- JHARKHAND
    ('JHGRD01','GIRIDIH','JHARKHAND'),

    -- CHHATTISGARH
    ('CGKAW01','KAWARDHA','CHHATTISGARH'),

    -- TELANGANA
    ('TGNLG01','NALGONDA','TELANGANA'),

    -- BIHAR
    ('BHPUR01','PURNIA','BIHAR'),

    -- HARYANA
    ('HRSON01','SONIPAT','HARYANA'),

    -- HIMACHAL PRADESH
    ('HPMND01','MANDI','HIMACHAL PRADESH'),

    -- PUNJAB
    ('PBMOH01','MOHALI','PUNJAB'),

    -- RAJASTHAN
    ('RJBSM01','BHILWARA','RAJASTHAN'),

    -- MAHARASHTRA
    ('MHNAG01','NAVI MUMBAI','MAHARASHTRA'),

    -- GUJARAT
    ('GJSRG01','GANDHIDHAM','GUJARAT')

) V
(
    CODE,
    CITY_NAME,
    STATE_NAME
)
WHERE NOT EXISTS
(
    SELECT 1
    FROM MST_CITY_MASTER C
    WHERE UPPER(LTRIM(RTRIM(C.CITY_NAME))) =
          UPPER(LTRIM(RTRIM(V.CITY_NAME)))
      AND UPPER(LTRIM(RTRIM(C.STATE_NAME))) =
          UPPER(LTRIM(RTRIM(V.STATE_NAME)))
);
