-- ====================================================================================
-- Migration: 20260821_V1160.0__Add_FromWhere_To_Shared_Attachment_Tables.sql
-- Description: Adds FROMWHERE (NVARCHAR(20)) column to shared attachment tables 
--              (HR_EMPLOYEE_EDUCATION, HR_EMPLOYEE_EXPERIENCE, HR_EMPLOYEE_KYC_DOCUMENT, 
--              HR_EMPLOYEE_ACTIVITY, HR_ATTACHMENT_PATH) and populates historical records.
-- Target DB: AT_NUTECH
-- ====================================================================================

-- 1. HR_EMPLOYEE_EDUCATION
IF COL_LENGTH('dbo.HR_EMPLOYEE_EDUCATION', 'FROMWHERE') IS NULL
BEGIN
    ALTER TABLE dbo.HR_EMPLOYEE_EDUCATION
    ADD FROMWHERE NVARCHAR(20) NULL;
END
GO

-- 2. HR_EMPLOYEE_EXPERIENCE
IF COL_LENGTH('dbo.HR_EMPLOYEE_EXPERIENCE', 'FROMWHERE') IS NULL
BEGIN
    ALTER TABLE dbo.HR_EMPLOYEE_EXPERIENCE
    ADD FROMWHERE NVARCHAR(20) NULL;
END
GO

-- 3. HR_EMPLOYEE_KYC_DOCUMENT
IF COL_LENGTH('dbo.HR_EMPLOYEE_KYC_DOCUMENT', 'FROMWHERE') IS NULL
BEGIN
    ALTER TABLE dbo.HR_EMPLOYEE_KYC_DOCUMENT
    ADD FROMWHERE NVARCHAR(20) NULL;
END
GO

-- 4. HR_EMPLOYEE_ACTIVITY
IF COL_LENGTH('dbo.HR_EMPLOYEE_ACTIVITY', 'FROMWHERE') IS NULL
BEGIN
    ALTER TABLE dbo.HR_EMPLOYEE_ACTIVITY
    ADD FROMWHERE NVARCHAR(20) NULL;
END
GO

-- 5. HR_ATTACHMENT_PATH
IF COL_LENGTH('dbo.HR_ATTACHMENT_PATH', 'FROMWHERE') IS NULL
BEGIN
    ALTER TABLE dbo.HR_ATTACHMENT_PATH
    ADD FROMWHERE NVARCHAR(20) NULL;
END
GO

-- ====================================================================================
-- HISTORICAL DATA MIGRATION
-- ====================================================================================

-- Populate HR_EMPLOYEE_EDUCATION.FROMWHERE from HR_EMPLOYEE.FROMWHERE
UPDATE E
SET E.FROMWHERE = ISNULL(NULLIF(LTRIM(RTRIM(H.FROMWHERE)), ''), 'EMPLOYEE')
FROM dbo.HR_EMPLOYEE_EDUCATION E
INNER JOIN dbo.HR_EMPLOYEE H ON H.ID = E.EMPLOYEE_ID
WHERE E.FROMWHERE IS NULL;
GO

-- Populate HR_EMPLOYEE_EXPERIENCE.FROMWHERE from HR_EMPLOYEE.FROMWHERE
UPDATE E
SET E.FROMWHERE = ISNULL(NULLIF(LTRIM(RTRIM(H.FROMWHERE)), ''), 'EMPLOYEE')
FROM dbo.HR_EMPLOYEE_EXPERIENCE E
INNER JOIN dbo.HR_EMPLOYEE H ON H.ID = E.EMPLOYEE_ID
WHERE E.FROMWHERE IS NULL;
GO

-- Populate HR_EMPLOYEE_KYC_DOCUMENT.FROMWHERE from HR_EMPLOYEE.FROMWHERE
UPDATE E
SET E.FROMWHERE = ISNULL(NULLIF(LTRIM(RTRIM(H.FROMWHERE)), ''), 'EMPLOYEE')
FROM dbo.HR_EMPLOYEE_KYC_DOCUMENT E
INNER JOIN dbo.HR_EMPLOYEE H ON H.ID = E.EMPLOYEE_ID
WHERE E.FROMWHERE IS NULL;
GO

-- Populate HR_EMPLOYEE_ACTIVITY.FROMWHERE from HR_EMPLOYEE.FROMWHERE
UPDATE E
SET E.FROMWHERE = ISNULL(NULLIF(LTRIM(RTRIM(H.FROMWHERE)), ''), 'EMPLOYEE')
FROM dbo.HR_EMPLOYEE_ACTIVITY E
INNER JOIN dbo.HR_EMPLOYEE H ON H.ID = E.EMPLOYEE_ID
WHERE E.FROMWHERE IS NULL;
GO

-- Populate HR_ATTACHMENT_PATH.FROMWHERE based on PAGE_CODE semantic domain
UPDATE A
SET A.FROMWHERE = CASE 
    WHEN UPPER(LTRIM(RTRIM(A.PAGE_CODE))) IN ('HA1110', 'HA1120') THEN 'ATS'
    WHEN UPPER(LTRIM(RTRIM(A.PAGE_CODE))) IN ('M2110', 'M2140') THEN 'EMPLOYEE'
    ELSE 'EMPLOYEE'
END
FROM dbo.HR_ATTACHMENT_PATH A
WHERE A.FROMWHERE IS NULL;
GO
