-- ============================================================================
-- DB Script: 20260727_V1071.0__Create_CLI_CLIENT_DATABASE_CONFIG_Table.sql
-- Module: Platform / Identity / Client Management
-- Description: Creates CLI_CLIENT_DATABASE_CONFIG table for storing client database
--              connection configuration (Microsoft SQL Server).
-- ============================================================================

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CLI_CLIENT_DATABASE_CONFIG')
BEGIN
    CREATE TABLE CLI_CLIENT_DATABASE_CONFIG (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_ID BIGINT NOT NULL,
        CLIENT_CODE NVARCHAR(10) NOT NULL,
        DB_TYPE NVARCHAR(50) DEFAULT 'Microsoft SQL Server',
        DB_HOST NVARCHAR(150) NULL,
        DB_PORT INT DEFAULT 1433,
        DB_NAME NVARCHAR(150) NULL,
        DB_USERNAME NVARCHAR(100) NULL,
        DB_PASSWORD NVARCHAR(500) NULL,
        CREATED_BY NVARCHAR(50) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        CREATED_AT DATETIME2 DEFAULT GETDATE(),
        UPDATED_AT DATETIME2 DEFAULT GETDATE(),
        CONSTRAINT FK_CLI_DB_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLI_CLIENT_MASTER(ID) ON DELETE CASCADE
    );

    CREATE INDEX IDX_CLI_DB_CLIENT_ID ON CLI_CLIENT_DATABASE_CONFIG(CLIENT_ID);
    CREATE INDEX IDX_CLI_DB_CLIENT_CODE ON CLI_CLIENT_DATABASE_CONFIG(CLIENT_CODE);
END;
ELSE
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_DATABASE_CONFIG') AND name = 'DB_TYPE')
        ALTER TABLE CLI_CLIENT_DATABASE_CONFIG ADD DB_TYPE NVARCHAR(50) DEFAULT 'Microsoft SQL Server';
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_DATABASE_CONFIG') AND name = 'DB_HOST')
        ALTER TABLE CLI_CLIENT_DATABASE_CONFIG ADD DB_HOST NVARCHAR(150) NULL;
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_DATABASE_CONFIG') AND name = 'DB_PORT')
        ALTER TABLE CLI_CLIENT_DATABASE_CONFIG ADD DB_PORT INT DEFAULT 1433;
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_DATABASE_CONFIG') AND name = 'DB_NAME')
        ALTER TABLE CLI_CLIENT_DATABASE_CONFIG ADD DB_NAME NVARCHAR(150) NULL;
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_DATABASE_CONFIG') AND name = 'DB_USERNAME')
        ALTER TABLE CLI_CLIENT_DATABASE_CONFIG ADD DB_USERNAME NVARCHAR(100) NULL;
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_DATABASE_CONFIG') AND name = 'DB_PASSWORD')
        ALTER TABLE CLI_CLIENT_DATABASE_CONFIG ADD DB_PASSWORD NVARCHAR(500) NULL;
END;
GO
