-- 1. Add INTERVIEWER_ID Column
IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[HR_APPLICANT_INTERVIEW]') 
      AND name = N'INTERVIEWER_ID'
)
BEGIN
    ALTER TABLE [dbo].[HR_APPLICANT_INTERVIEW] ADD [INTERVIEWER_ID] BIGINT NULL;
END
GO

-- 2. Add Foreign Key Constraint
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys 
    WHERE object_id = OBJECT_ID(N'[dbo].[FK_HR_APPLICANT_INTERVIEW_INTERVIEWER]') 
      AND parent_object_id = OBJECT_ID(N'[dbo].[HR_APPLICANT_INTERVIEW]')
)
BEGIN
    ALTER TABLE [dbo].[HR_APPLICANT_INTERVIEW] 
    ADD CONSTRAINT [FK_HR_APPLICANT_INTERVIEW_INTERVIEWER] 
    FOREIGN KEY ([INTERVIEWER_ID]) REFERENCES [dbo].[HR_EMPLOYEE] ([ID]);
END
GO

-- 3. Duplicate-Safe DML Backfill
-- Only backfill the ID if there is exactly one active employee with the given name matching INTERVIEW_PERSON
UPDATE i
SET i.INTERVIEWER_ID = e.ID
FROM [dbo].[HR_APPLICANT_INTERVIEW] i
JOIN [dbo].[HR_EMPLOYEE] e ON LOWER(TRIM(e.EMPLOYEE_NAME)) = LOWER(TRIM(i.INTERVIEW_PERSON))
WHERE i.INTERVIEWER_ID IS NULL 
  AND i.INTERVIEW_PERSON IS NOT NULL
  AND e.IS_ACTIVE = 1
  AND (
      SELECT COUNT(*) 
      FROM [dbo].[HR_EMPLOYEE] emp 
      WHERE LOWER(TRIM(emp.EMPLOYEE_NAME)) = LOWER(TRIM(i.INTERVIEW_PERSON))
        AND emp.IS_ACTIVE = 1
  ) = 1;
GO
