-- Fix search_text column contents for QMS_AUDIT_SCHEDULE using the correct column mappings and joins
UPDATE a
SET a.SEARCH_TEXT = LOWER(
    COALESCE(a.SCHEDULE_NO, '') + ' ' +
    COALESCE(t.AUDIT_TYPE, '') + ' ' +
    COALESCE(ar.DESCRIPTION, '') + ' ' +
    COALESCE(d.DEPARTMENT_NAME, '') + ' ' +
    COALESCE(e1.EMPLOYEE_NAME, COALESCE(e1.FIRST_NAME + ' ' + e1.LAST_NAME, '')) + ' ' +
    COALESCE(e2.EMPLOYEE_NAME, COALESCE(e2.FIRST_NAME + ' ' + e2.LAST_NAME, ''))
)
FROM QMS_AUDIT_SCHEDULE a
LEFT JOIN QMS_AUDIT_TYPE t ON a.AUDIT_TYPE_ID = t.id
LEFT JOIN QMS_AUDIT_AREA ar ON a.AUDIT_AREA_ID = ar.id
LEFT JOIN HR_DEPARTMENT d ON a.DEPARTMENT_ID = d.id
LEFT JOIN HR_EMPLOYEE e1 ON a.AUDITOR_ID = e1.id
LEFT JOIN HR_EMPLOYEE e2 ON a.AUDITEE_ID = e2.id OPTION (MAXDOP 1);
GO
