-- V1063.0: Align HR_LEAVE_TRAVEL_DETAILS schema with HR_LEAVE_DETAILS
-- 1. Seed Status Master entries
-- 2. Add STATUS_ID (INT) column and migrate status values
-- 3. Add VERIFIED_BY, VERIFIED_DATE, REJECT_REASON columns
-- 4. Drop legacy STATUS (VARCHAR) column
-- 5. Drop IS_ACTIVE, UPDATED_BY, UPDATED_DATE columns

-- Step 1: Seed Status Master entries if missing
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Pending to Verify')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Pending to Verify');
END;

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Verified')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Verified');
END;

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Rejected')
BEGIN
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Rejected');
END;

-- Step 2: Add STATUS_ID, VERIFIED_BY, VERIFIED_DATE, REJECT_REASON columns to HR_LEAVE_TRAVEL_DETAILS
IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_LEAVE_TRAVEL_DETAILS' AND COLUMN_NAME = 'STATUS_ID')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD STATUS_ID INT NULL;
        PRINT 'Added STATUS_ID column to HR_LEAVE_TRAVEL_DETAILS';
    END;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_LEAVE_TRAVEL_DETAILS' AND COLUMN_NAME = 'VERIFIED_BY')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD VERIFIED_BY VARCHAR(50) NULL;
        PRINT 'Added VERIFIED_BY column to HR_LEAVE_TRAVEL_DETAILS';
    END;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_LEAVE_TRAVEL_DETAILS' AND COLUMN_NAME = 'VERIFIED_DATE')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD VERIFIED_DATE DATETIME NULL;
        PRINT 'Added VERIFIED_DATE column to HR_LEAVE_TRAVEL_DETAILS';
    END;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_LEAVE_TRAVEL_DETAILS' AND COLUMN_NAME = 'REJECT_REASON')
    BEGIN
        ALTER TABLE dbo.HR_LEAVE_TRAVEL_DETAILS ADD REJECT_REASON VARCHAR(500) NULL;
        PRINT 'Added REJECT_REASON column to HR_LEAVE_TRAVEL_DETAILS';
    END;
END;

-- Step 3: Migrate string STATUS data to STATUS_ID
IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NOT NULL AND EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_LEAVE_TRAVEL_DETAILS' AND COLUMN_NAME = 'STATUS')
BEGIN
    UPDATE HR_LEAVE_TRAVEL_DETAILS
    SET STATUS_ID = (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'REJECTED')
    WHERE UPPER(TRIM(STATUS)) = 'REJECTED' AND STATUS_ID IS NULL;

    UPDATE HR_LEAVE_TRAVEL_DETAILS
    SET STATUS_ID = (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'VERIFIED')
    WHERE UPPER(TRIM(STATUS)) = 'VERIFIED' AND STATUS_ID IS NULL;

    UPDATE HR_LEAVE_TRAVEL_DETAILS
    SET STATUS_ID = (SELECT TOP 1 ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PENDING TO VERIFY')
    WHERE STATUS_ID IS NULL;

    -- Drop legacy STATUS column
    DECLARE @StatusConstraint NVARCHAR(256);
    SELECT @StatusConstraint = OBJECT_NAME(default_object_id)
    FROM sys.columns
    WHERE object_id = OBJECT_ID('HR_LEAVE_TRAVEL_DETAILS') AND name = 'STATUS';

    IF @StatusConstraint IS NOT NULL
    BEGIN
        EXEC('ALTER TABLE HR_LEAVE_TRAVEL_DETAILS DROP CONSTRAINT ' + @StatusConstraint);
    END;

    ALTER TABLE HR_LEAVE_TRAVEL_DETAILS DROP COLUMN STATUS;
    PRINT 'Migrated STATUS data to STATUS_ID and dropped legacy STATUS column.';
END;

-- Step 4: Drop IS_ACTIVE column
IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NOT NULL AND EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_LEAVE_TRAVEL_DETAILS' AND COLUMN_NAME = 'IS_ACTIVE')
BEGIN
    DECLARE @IsActiveConstraint NVARCHAR(256);
    SELECT @IsActiveConstraint = OBJECT_NAME(default_object_id)
    FROM sys.columns
    WHERE object_id = OBJECT_ID('HR_LEAVE_TRAVEL_DETAILS') AND name = 'IS_ACTIVE';

    IF @IsActiveConstraint IS NOT NULL
    BEGIN
        EXEC('ALTER TABLE HR_LEAVE_TRAVEL_DETAILS DROP CONSTRAINT ' + @IsActiveConstraint);
    END;

    ALTER TABLE HR_LEAVE_TRAVEL_DETAILS DROP COLUMN IS_ACTIVE;
    PRINT 'Dropped IS_ACTIVE column from HR_LEAVE_TRAVEL_DETAILS.';
END;

-- Step 5: Drop UPDATED_BY and UPDATED_DATE columns
IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NOT NULL AND EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_LEAVE_TRAVEL_DETAILS' AND COLUMN_NAME = 'UPDATED_BY')
BEGIN
    DECLARE @UpdatedByConstraint NVARCHAR(256);
    SELECT @UpdatedByConstraint = OBJECT_NAME(default_object_id)
    FROM sys.columns
    WHERE object_id = OBJECT_ID('HR_LEAVE_TRAVEL_DETAILS') AND name = 'UPDATED_BY';

    IF @UpdatedByConstraint IS NOT NULL
    BEGIN
        EXEC('ALTER TABLE HR_LEAVE_TRAVEL_DETAILS DROP CONSTRAINT ' + @UpdatedByConstraint);
    END;

    ALTER TABLE HR_LEAVE_TRAVEL_DETAILS DROP COLUMN UPDATED_BY;
    PRINT 'Dropped UPDATED_BY column from HR_LEAVE_TRAVEL_DETAILS.';
END;

IF OBJECT_ID('dbo.HR_LEAVE_TRAVEL_DETAILS', 'U') IS NOT NULL AND EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_LEAVE_TRAVEL_DETAILS' AND COLUMN_NAME = 'UPDATED_DATE')
BEGIN
    DECLARE @UpdatedDateConstraint NVARCHAR(256);
    SELECT @UpdatedDateConstraint = OBJECT_NAME(default_object_id)
    FROM sys.columns
    WHERE object_id = OBJECT_ID('HR_LEAVE_TRAVEL_DETAILS') AND name = 'UPDATED_DATE';

    IF @UpdatedDateConstraint IS NOT NULL
    BEGIN
        EXEC('ALTER TABLE HR_LEAVE_TRAVEL_DETAILS DROP CONSTRAINT ' + @UpdatedDateConstraint);
    END;

    ALTER TABLE HR_LEAVE_TRAVEL_DETAILS DROP COLUMN UPDATED_DATE;
    PRINT 'Dropped UPDATED_DATE column from HR_LEAVE_TRAVEL_DETAILS.';
END;
