-- ============================================================================
-- DB Script: 20260724_V1055.0__Create_CLI_CLIENT_SERVER_CONFIG_And_Health_Tables.sql
-- Module: Platform / Identity / Client Health Monitoring
-- Description: Creates CLI_CLIENT_SERVER_CONFIG table for storing client server 
--              monitoring credentials and CLI_CLIENT_HEALTH_LOG for historical health tracking.
--              Registers page AD1140 (Health Dashboard).
-- ============================================================================

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CLI_CLIENT_SERVER_CONFIG')
BEGIN
    CREATE TABLE CLI_CLIENT_SERVER_CONFIG (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_ID BIGINT NOT NULL,
        CLIENT_CODE VARCHAR(10) NOT NULL,
        HEALTH_MONITORING_ENABLED BIT DEFAULT 0,
        SERVER_NAME VARCHAR(150) NULL,
        SERVER_IP VARCHAR(50) NULL,
        WINDOWS_USERNAME VARCHAR(100) NULL,
        WINDOWS_PASSWORD VARCHAR(500) NULL,
        CREATED_BY VARCHAR(50) NULL,
        UPDATED_BY VARCHAR(50) NULL,
        CREATED_AT DATETIME2 DEFAULT GETDATE(),
        UPDATED_AT DATETIME2 DEFAULT GETDATE(),
        CONSTRAINT FK_CLI_SERVER_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLI_CLIENT_MASTER(ID) ON DELETE CASCADE
    );

    CREATE INDEX IDX_CLI_SERVER_CLIENT_ID ON CLI_CLIENT_SERVER_CONFIG(CLIENT_ID);
    CREATE INDEX IDX_CLI_SERVER_CLIENT_CODE ON CLI_CLIENT_SERVER_CONFIG(CLIENT_CODE);
END;
ELSE
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'SERVER_NAME')
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG ADD SERVER_NAME VARCHAR(150) NULL;
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'SERVER_IP')
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG ADD SERVER_IP VARCHAR(50) NULL;
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'WINDOWS_USERNAME')
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG ADD WINDOWS_USERNAME VARCHAR(100) NULL;
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'WINDOWS_PASSWORD')
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG ADD WINDOWS_PASSWORD VARCHAR(500) NULL;
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CLI_CLIENT_SERVER_CONFIG') AND name = 'HEALTH_MONITORING_ENABLED')
        ALTER TABLE CLI_CLIENT_SERVER_CONFIG ADD HEALTH_MONITORING_ENABLED BIT DEFAULT 0;
END;
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CLI_CLIENT_HEALTH_LOG')
BEGIN
    CREATE TABLE CLI_CLIENT_HEALTH_LOG (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        CLIENT_CODE VARCHAR(10) NOT NULL,
        SERVER_NAME VARCHAR(150) NULL,
        SERVER_IP VARCHAR(50) NULL,
        CPU_USAGE_PCT FLOAT NULL,
        MEMORY_USAGE_PCT FLOAT NULL,
        DISK_USAGE_PCT FLOAT NULL,
        SQL_SERVER_STATUS VARCHAR(20) DEFAULT 'ONLINE',
        APPLICATION_STATUS VARCHAR(20) DEFAULT 'ONLINE',
        NETWORK_STATUS VARCHAR(20) DEFAULT 'ONLINE',
        NETWORK_LATENCY_MS BIGINT NULL,
        SERVER_UPTIME_SECONDS BIGINT NULL,
        OVERALL_STATUS VARCHAR(20) DEFAULT 'HEALTHY',
        LOGGED_AT DATETIME2 DEFAULT GETDATE()
    );

    CREATE INDEX IDX_CLI_HEALTH_CLIENT_CODE ON CLI_CLIENT_HEALTH_LOG(CLIENT_CODE);
    CREATE INDEX IDX_CLI_HEALTH_LOGGED_AT ON CLI_CLIENT_HEALTH_LOG(LOGGED_AT);
END;
GO


