-- Add REJECTED_COUNT column to QMS_MOM_DETAILS table
IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID('QMS_MOM_DETAILS') AND name = 'REJECTED_COUNT'
)
BEGIN
    ALTER TABLE QMS_MOM_DETAILS ADD REJECTED_COUNT INT DEFAULT 0;
END
GO

-- Update existing records to have 0 if null
UPDATE QMS_MOM_DETAILS SET REJECTED_COUNT = 0 WHERE REJECTED_COUNT IS NULL;
GO
