-- Add new columns for header commercial terms negotiation
IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'ORIGINAL_DELIVERY_TERMS' AND Object_ID = Object_ID(N'PP_QUOTATION_NEGOTIATION_HEAD'))
BEGIN
    ALTER TABLE PP_QUOTATION_NEGOTIATION_HEAD
    ADD ORIGINAL_DELIVERY_TERMS NVARCHAR(500),
        NEGOTIATED_DELIVERY_TERMS NVARCHAR(500),
        ORIGINAL_PAYMENT_TERMS NVARCHAR(500),
        NEGOTIATED_PAYMENT_TERMS NVARCHAR(500),
        ORIGINAL_TRANSPORT_MODE NVARCHAR(200),
        NEGOTIATED_TRANSPORT_MODE NVARCHAR(200);
END



IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PP_QUOTATION_HEAD') AND name = 'DELIVERY_TERMS')
BEGIN
    ALTER TABLE PP_QUOTATION_HEAD ADD DELIVERY_TERMS NVARCHAR(500);
END
GO


IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE Name = N'WARRANTY_TERMS' 
    AND Object_ID = Object_ID(N'dbo.PP_QUOTATION_DETAIL')
)
BEGIN
    ALTER TABLE dbo.PP_QUOTATION_DETAIL ADD WARRANTY_TERMS NVARCHAR(250);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE Name = N'WARRANTY_TERMS' 
    AND Object_ID = Object_ID(N'dbo.PP_PURCHASE_ORDER_TRANS')
)
BEGIN
    ALTER TABLE dbo.PP_PURCHASE_ORDER_TRANS ADD WARRANTY_TERMS NVARCHAR(250);
END
GO
