-- Migration to add ONBOARDING_STARTED column to HR_EMPLOYEE table
IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMPLOYEE') 
      AND name = 'ONBOARDING_STARTED'
)
BEGIN
    ALTER TABLE HR_EMPLOYEE ADD ONBOARDING_STARTED BIT NOT NULL DEFAULT 0;
END
