-- Organization: Nutech
-- Owner: Nutech
-- Created At: 2026-09-02
-- Description: Create DOC_SEARCH_DOCUMENT metadata table and register Document Search page AD1180

IF OBJECT_ID('dbo.DOC_SEARCH_DOCUMENT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_SEARCH_DOCUMENT (
        ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        MODULE_CODE NVARCHAR(50) NOT NULL,
        PAGE_CODE NVARCHAR(50) NULL,
        SOURCE_TABLE NVARCHAR(100) NOT NULL,
        SOURCE_PK_VALUE NVARCHAR(100) NOT NULL,
        REF_ID NVARCHAR(100) NULL,
        FILE_NAME NVARCHAR(255) NOT NULL,
        FILE_TYPE NVARCHAR(50) NOT NULL,
        STORAGE_PATH NVARCHAR(1000) NOT NULL,
        FILE_HASH NVARCHAR(64) NOT NULL,
        FILE_SIZE BIGINT NULL,
        TOTAL_PAGES INT DEFAULT 1,
        INDEX_STATUS NVARCHAR(50) NOT NULL DEFAULT 'PENDING',
        INDEX_ATTEMPTS INT DEFAULT 0,
        LAST_ATTEMPT_DATE DATETIME2 NULL,
        INDEX_ERROR NVARCHAR(MAX) NULL,
        CREATED_DATE DATETIME2 DEFAULT GETDATE(),
        CREATED_BY NVARCHAR(50) DEFAULT 'SYSTEM',
        MODIFIED_DATE DATETIME2 DEFAULT GETDATE(),
        MODIFIED_BY NVARCHAR(50) NULL
    );

    CREATE INDEX IX_DOC_SEARCH_DOC_STATUS ON dbo.DOC_SEARCH_DOCUMENT(INDEX_STATUS, LAST_ATTEMPT_DATE);
    CREATE INDEX IX_DOC_SEARCH_DOC_HASH ON dbo.DOC_SEARCH_DOCUMENT(FILE_HASH);
    CREATE INDEX IX_DOC_SEARCH_DOC_SOURCE ON dbo.DOC_SEARCH_DOCUMENT(SOURCE_TABLE, SOURCE_PK_VALUE);
    CREATE INDEX IX_DOC_SEARCH_DOC_MODULE ON dbo.DOC_SEARCH_DOCUMENT(MODULE_CODE, PAGE_CODE);
    PRINT 'Created table DOC_SEARCH_DOCUMENT and indexes.';
END;

-- Register BOS Page for Document Search (DM1010)
IF NOT EXISTS (SELECT 1 FROM dbo.BOS_PAGES WHERE page_code = 'DM1010')
BEGIN
    INSERT INTO dbo.BOS_PAGES (mod_id, sub_mod_id, page_code, page_name, enabled)
    VALUES (14, 141, 'DM1010', 'Document Search', 1);
    PRINT 'Registered page DM1010 (Document Search).';
END;

-- Grant permissions to Admin users in BOS_USER_PAGE_AUTH
DECLARE @PageId INT;
SELECT @PageId = page_id FROM dbo.BOS_PAGES WHERE page_code = 'DM1010';

IF @PageId IS NOT NULL
BEGIN
    INSERT INTO dbo.BOS_USER_PAGE_AUTH (
        USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, 
        READ_ACS, WRITE, DELETE_ACS, EXPORT, APPROVAL, 
        MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, 
        CREATED_BY, CREATED_DATE
    )
    SELECT DISTINCT 
        u.USER_ID, @PageId, 141, 14, 1, 
        1, 1, 1, 1, 1, 
        1, 0, 0, 0, 
        'SYSTEM', GETDATE()
    FROM dbo.AD_USER_CREDENTIAL u
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.BOS_USER_PAGE_AUTH a WHERE a.USER_ID = u.USER_ID AND a.PAGE_ID = @PageId
    );
    PRINT 'Granted DM1010 permissions to users.';
END;
