-- Database Migration: V1051.0__Normalize_Ats_Statuses.sql
-- Normalize ATS status values in the database, changing VARCHAR/NVARCHAR status strings to BIGINT Status Master IDs.

-- ==========================================
-- PHASE 1: Populate Master Status Table
-- ==========================================
SET NOCOUNT ON;

-- Ensure missing statuses exist in AD_STATUS_MASTER
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'IN PROGRESS')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('In Progress');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'WAITING FOR PROGRESS')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Waiting For Progress');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'SELECTED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Selected');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'HOLD')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Hold');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'SENT')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Sent');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'RESENT')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Resent');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'CONFIRM')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Confirm');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PARTIALLY VERIFIED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Partially Verified');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'APPLIED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Applied');

-- Standardize ID 17 from 'TO BE VERIFIED' to 'To Be Verified'
UPDATE AD_STATUS_MASTER SET NAME = 'To Be Verified' WHERE ID = 17;


-- ==========================================
-- PHASE 2: Create temporary columns
-- ==========================================

-- HR_EMPLOYEE_ATS columns
IF COL_LENGTH('HR_EMPLOYEE_ATS', 'CALL_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE_ATS ADD CALL_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE_ATS', 'INTERVIEW_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE_ATS ADD INTERVIEW_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE_ATS', 'OFFER_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE_ATS ADD OFFER_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE_ATS', 'VERIFICATION_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE_ATS ADD VERIFICATION_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE_ATS', 'BACKGROUND_VERIFICATION_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE_ATS ADD BACKGROUND_VERIFICATION_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE_ATS', 'PHOTO_VERIFIED_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE_ATS ADD PHOTO_VERIFIED_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE_ATS', 'RESUME_VERIFIED_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE_ATS ADD RESUME_VERIFIED_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE_ATS', 'PAYSLIP_VERIFIED_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE_ATS ADD PAYSLIP_VERIFIED_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE_ATS', 'AADHAR_VERIFIED_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE_ATS ADD AADHAR_VERIFIED_STATUS_ID BIGINT NULL;


-- HR_APPLICANT_INTERVIEW columns
IF COL_LENGTH('HR_APPLICANT_INTERVIEW', 'INTERVIEW_STATUS_ID') IS NULL
    ALTER TABLE HR_APPLICANT_INTERVIEW ADD INTERVIEW_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_APPLICANT_INTERVIEW', 'INTERVIEW_RESULT_ID') IS NULL
    ALTER TABLE HR_APPLICANT_INTERVIEW ADD INTERVIEW_RESULT_ID BIGINT NULL;


-- HR_EMPLOYEE columns
IF COL_LENGTH('HR_EMPLOYEE', 'STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE ADD STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE', 'PHOTO_VERIFIED_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE ADD PHOTO_VERIFIED_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE', 'RESUME_VERIFIED_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE ADD RESUME_VERIFIED_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE', 'PAYSLIP_VERIFIED_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE ADD PAYSLIP_VERIFIED_STATUS_ID BIGINT NULL;

IF COL_LENGTH('HR_EMPLOYEE', 'AADHAR_VERIFIED_STATUS_ID') IS NULL
    ALTER TABLE HR_EMPLOYEE ADD AADHAR_VERIFIED_STATUS_ID BIGINT NULL;


-- ==========================================
-- PHASE 3: Map and populate temporary columns
-- ==========================================

-- Dynamically resolve status IDs to prevent environment hardcoding issues
DECLARE @PendingId BIGINT = 13;
DECLARE @CancelledId BIGINT = 5;
DECLARE @VerifiedId BIGINT = 15;
DECLARE @RejectedId BIGINT = 9;
DECLARE @ApprovedId BIGINT = 36;
DECLARE @CompletedId BIGINT = 20;
DECLARE @ToBeVerifiedId BIGINT = 17;
DECLARE @NaId BIGINT = 32;

DECLARE @InProgressId BIGINT;
SELECT @InProgressId = ID FROM AD_STATUS_MASTER WHERE NAME = 'In Progress';

DECLARE @WaitingForProgressId BIGINT;
SELECT @WaitingForProgressId = ID FROM AD_STATUS_MASTER WHERE NAME = 'Waiting For Progress';

DECLARE @SelectedId BIGINT;
SELECT @SelectedId = ID FROM AD_STATUS_MASTER WHERE NAME = 'Selected';

DECLARE @HoldId BIGINT;
SELECT @HoldId = ID FROM AD_STATUS_MASTER WHERE NAME = 'Hold';

DECLARE @SentId BIGINT;
SELECT @SentId = ID FROM AD_STATUS_MASTER WHERE NAME = 'Sent';

DECLARE @ResentId BIGINT;
SELECT @ResentId = ID FROM AD_STATUS_MASTER WHERE NAME = 'Resent';

DECLARE @ConfirmId BIGINT;
SELECT @ConfirmId = ID FROM AD_STATUS_MASTER WHERE NAME = 'Confirm';

DECLARE @PartiallyVerifiedId BIGINT;
SELECT @PartiallyVerifiedId = ID FROM AD_STATUS_MASTER WHERE NAME = 'Partially Verified';

DECLARE @AppliedId BIGINT;
SELECT @AppliedId = ID FROM AD_STATUS_MASTER WHERE NAME = 'Applied';

DECLARE @ActiveId BIGINT = 16;


-- 1. HR_EMPLOYEE_ATS CALL_STATUS
UPDATE HR_EMPLOYEE_ATS SET CALL_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(CALL_STATUS AS VARCHAR(100)))) = 'PENDING' OR CALL_STATUS IS NULL;
UPDATE HR_EMPLOYEE_ATS SET CALL_STATUS_ID = @SentId WHERE UPPER(TRIM(CAST(CALL_STATUS AS VARCHAR(100)))) = 'SENT';
UPDATE HR_EMPLOYEE_ATS SET CALL_STATUS_ID = @ResentId WHERE UPPER(TRIM(CAST(CALL_STATUS AS VARCHAR(100)))) = 'RESENT';
UPDATE HR_EMPLOYEE_ATS SET CALL_STATUS_ID = @ConfirmId WHERE UPPER(TRIM(CAST(CALL_STATUS AS VARCHAR(100)))) = 'CONFIRM';
UPDATE HR_EMPLOYEE_ATS SET CALL_STATUS_ID = @ToBeVerifiedId WHERE UPPER(TRIM(CAST(CALL_STATUS AS VARCHAR(100)))) IN ('TO BE VERIFY', 'TO BE VERIFIED');
UPDATE HR_EMPLOYEE_ATS SET CALL_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(CALL_STATUS AS VARCHAR(100)))) = 'CANCELLED';

-- 2. HR_EMPLOYEE_ATS INTERVIEW_STATUS
UPDATE HR_EMPLOYEE_ATS SET INTERVIEW_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(INTERVIEW_STATUS AS VARCHAR(100)))) = 'PENDING' OR INTERVIEW_STATUS IS NULL;
UPDATE HR_EMPLOYEE_ATS SET INTERVIEW_STATUS_ID = @InProgressId WHERE UPPER(TRIM(CAST(INTERVIEW_STATUS AS VARCHAR(100)))) IN ('IN PROGRESS', 'ON PROGRESS');
UPDATE HR_EMPLOYEE_ATS SET INTERVIEW_STATUS_ID = @CompletedId WHERE UPPER(TRIM(CAST(INTERVIEW_STATUS AS VARCHAR(100)))) = 'COMPLETED';
UPDATE HR_EMPLOYEE_ATS SET INTERVIEW_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(INTERVIEW_STATUS AS VARCHAR(100)))) = 'CANCELLED';

-- 3. HR_EMPLOYEE_ATS OFFER_STATUS
UPDATE HR_EMPLOYEE_ATS SET OFFER_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(OFFER_STATUS AS VARCHAR(100)))) = 'PENDING' OR OFFER_STATUS IS NULL;
UPDATE HR_EMPLOYEE_ATS SET OFFER_STATUS_ID = @SentId WHERE UPPER(TRIM(CAST(OFFER_STATUS AS VARCHAR(100)))) = 'SENT';
UPDATE HR_EMPLOYEE_ATS SET OFFER_STATUS_ID = @ResentId WHERE UPPER(TRIM(CAST(OFFER_STATUS AS VARCHAR(100)))) = 'RESENT';
UPDATE HR_EMPLOYEE_ATS SET OFFER_STATUS_ID = @ConfirmId WHERE UPPER(TRIM(CAST(OFFER_STATUS AS VARCHAR(100)))) = 'CONFIRM';
UPDATE HR_EMPLOYEE_ATS SET OFFER_STATUS_ID = @ToBeVerifiedId WHERE UPPER(TRIM(CAST(OFFER_STATUS AS VARCHAR(100)))) IN ('TO BE VERIFY', 'TO BE VERIFIED');
UPDATE HR_EMPLOYEE_ATS SET OFFER_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(OFFER_STATUS AS VARCHAR(100)))) = 'CANCELLED';

-- 4. HR_EMPLOYEE_ATS VERIFICATION_STATUS
UPDATE HR_EMPLOYEE_ATS SET VERIFICATION_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(VERIFICATION_STATUS AS VARCHAR(100)))) = 'PENDING' OR VERIFICATION_STATUS IS NULL;
UPDATE HR_EMPLOYEE_ATS SET VERIFICATION_STATUS_ID = @InProgressId WHERE UPPER(TRIM(CAST(VERIFICATION_STATUS AS VARCHAR(100)))) IN ('IN PROGRESS', 'ON PROGRESS');
UPDATE HR_EMPLOYEE_ATS SET VERIFICATION_STATUS_ID = @VerifiedId WHERE UPPER(TRIM(CAST(VERIFICATION_STATUS AS VARCHAR(100)))) = 'VERIFIED';
UPDATE HR_EMPLOYEE_ATS SET VERIFICATION_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(VERIFICATION_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE_ATS SET VERIFICATION_STATUS_ID = @NaId WHERE UPPER(TRIM(CAST(VERIFICATION_STATUS AS VARCHAR(100)))) = 'N/A';
UPDATE HR_EMPLOYEE_ATS SET VERIFICATION_STATUS_ID = @PartiallyVerifiedId WHERE UPPER(TRIM(CAST(VERIFICATION_STATUS AS VARCHAR(100)))) = 'PARTIALLY_VERIFIED';
UPDATE HR_EMPLOYEE_ATS SET VERIFICATION_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(VERIFICATION_STATUS AS VARCHAR(100)))) = 'CANCELLED';

-- 5. HR_EMPLOYEE_ATS BACKGROUND_VERIFICATION_STATUS
UPDATE HR_EMPLOYEE_ATS SET BACKGROUND_VERIFICATION_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(BACKGROUND_VERIFICATION_STATUS AS VARCHAR(100)))) = 'PENDING' OR BACKGROUND_VERIFICATION_STATUS IS NULL;
UPDATE HR_EMPLOYEE_ATS SET BACKGROUND_VERIFICATION_STATUS_ID = @InProgressId WHERE UPPER(TRIM(CAST(BACKGROUND_VERIFICATION_STATUS AS VARCHAR(100)))) IN ('IN PROGRESS', 'ON PROGRESS');
UPDATE HR_EMPLOYEE_ATS SET BACKGROUND_VERIFICATION_STATUS_ID = @VerifiedId WHERE UPPER(TRIM(CAST(BACKGROUND_VERIFICATION_STATUS AS VARCHAR(100)))) = 'VERIFIED';
UPDATE HR_EMPLOYEE_ATS SET BACKGROUND_VERIFICATION_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(BACKGROUND_VERIFICATION_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE_ATS SET BACKGROUND_VERIFICATION_STATUS_ID = @NaId WHERE UPPER(TRIM(CAST(BACKGROUND_VERIFICATION_STATUS AS VARCHAR(100)))) = 'N/A';
UPDATE HR_EMPLOYEE_ATS SET BACKGROUND_VERIFICATION_STATUS_ID = @PartiallyVerifiedId WHERE UPPER(TRIM(CAST(BACKGROUND_VERIFICATION_STATUS AS VARCHAR(100)))) = 'PARTIALLY_VERIFIED';
UPDATE HR_EMPLOYEE_ATS SET BACKGROUND_VERIFICATION_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(BACKGROUND_VERIFICATION_STATUS AS VARCHAR(100)))) = 'CANCELLED';

-- 6. Document Approvals (HR_EMPLOYEE_ATS)
UPDATE HR_EMPLOYEE_ATS SET PHOTO_VERIFIED_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(PHOTO_VERIFIED_STATUS AS VARCHAR(100)))) = 'PENDING' OR PHOTO_VERIFIED_STATUS IS NULL;
UPDATE HR_EMPLOYEE_ATS SET PHOTO_VERIFIED_STATUS_ID = @ApprovedId WHERE UPPER(TRIM(CAST(PHOTO_VERIFIED_STATUS AS VARCHAR(100)))) = 'APPROVED';
UPDATE HR_EMPLOYEE_ATS SET PHOTO_VERIFIED_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(PHOTO_VERIFIED_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE_ATS SET PHOTO_VERIFIED_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(PHOTO_VERIFIED_STATUS AS VARCHAR(100)))) = 'CANCELLED';

UPDATE HR_EMPLOYEE_ATS SET RESUME_VERIFIED_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(RESUME_VERIFIED_STATUS AS VARCHAR(100)))) = 'PENDING' OR RESUME_VERIFIED_STATUS IS NULL;
UPDATE HR_EMPLOYEE_ATS SET RESUME_VERIFIED_STATUS_ID = @ApprovedId WHERE UPPER(TRIM(CAST(RESUME_VERIFIED_STATUS AS VARCHAR(100)))) = 'APPROVED';
UPDATE HR_EMPLOYEE_ATS SET RESUME_VERIFIED_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(RESUME_VERIFIED_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE_ATS SET RESUME_VERIFIED_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(RESUME_VERIFIED_STATUS AS VARCHAR(100)))) = 'CANCELLED';

UPDATE HR_EMPLOYEE_ATS SET PAYSLIP_VERIFIED_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(PAYSLIP_VERIFIED_STATUS AS VARCHAR(100)))) = 'PENDING' OR PAYSLIP_VERIFIED_STATUS IS NULL;
UPDATE HR_EMPLOYEE_ATS SET PAYSLIP_VERIFIED_STATUS_ID = @ApprovedId WHERE UPPER(TRIM(CAST(PAYSLIP_VERIFIED_STATUS AS VARCHAR(100)))) = 'APPROVED';
UPDATE HR_EMPLOYEE_ATS SET PAYSLIP_VERIFIED_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(PAYSLIP_VERIFIED_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE_ATS SET PAYSLIP_VERIFIED_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(PAYSLIP_VERIFIED_STATUS AS VARCHAR(100)))) = 'CANCELLED';

UPDATE HR_EMPLOYEE_ATS SET AADHAR_VERIFIED_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(AADHAR_VERIFIED_STATUS AS VARCHAR(100)))) = 'PENDING' OR AADHAR_VERIFIED_STATUS IS NULL;
UPDATE HR_EMPLOYEE_ATS SET AADHAR_VERIFIED_STATUS_ID = @ApprovedId WHERE UPPER(TRIM(CAST(AADHAR_VERIFIED_STATUS AS VARCHAR(100)))) = 'APPROVED';
UPDATE HR_EMPLOYEE_ATS SET AADHAR_VERIFIED_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(AADHAR_VERIFIED_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE_ATS SET AADHAR_VERIFIED_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(AADHAR_VERIFIED_STATUS AS VARCHAR(100)))) = 'CANCELLED';


-- 7. HR_APPLICANT_INTERVIEW INTERVIEW_STATUS / INTERVIEW_RESULT
UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(INTERVIEW_STATUS AS VARCHAR(100)))) = 'PENDING' OR INTERVIEW_STATUS IS NULL;
UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_STATUS_ID = @WaitingForProgressId WHERE UPPER(TRIM(CAST(INTERVIEW_STATUS AS VARCHAR(100)))) IN ('WAITING FOR PROGRESS', 'WAITING FOR PROCESS');
UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_STATUS_ID = @SelectedId WHERE UPPER(TRIM(CAST(INTERVIEW_STATUS AS VARCHAR(100)))) = 'SELECTED';
UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(INTERVIEW_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_STATUS_ID = @HoldId WHERE UPPER(TRIM(CAST(INTERVIEW_STATUS AS VARCHAR(100)))) = 'HOLD';
UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(INTERVIEW_STATUS AS VARCHAR(100)))) = 'CANCELLED';

UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_RESULT_ID = @PendingId WHERE UPPER(TRIM(CAST(INTERVIEW_RESULT AS VARCHAR(100)))) = 'PENDING' OR INTERVIEW_RESULT IS NULL;
UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_RESULT_ID = @SelectedId WHERE UPPER(TRIM(CAST(INTERVIEW_RESULT AS VARCHAR(100)))) = 'SELECTED';
UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_RESULT_ID = @RejectedId WHERE UPPER(TRIM(CAST(INTERVIEW_RESULT AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_RESULT_ID = @HoldId WHERE UPPER(TRIM(CAST(INTERVIEW_RESULT AS VARCHAR(100)))) = 'HOLD';
UPDATE HR_APPLICANT_INTERVIEW SET INTERVIEW_RESULT_ID = @CancelledId WHERE UPPER(TRIM(CAST(INTERVIEW_RESULT AS VARCHAR(100)))) = 'CANCELLED';


-- 8. HR_EMPLOYEE STATUS
UPDATE HR_EMPLOYEE SET STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(STATUS AS VARCHAR(100)))) IN ('PENDING', 'APPLIED', 'Applied') OR STATUS IS NULL;
UPDATE HR_EMPLOYEE SET STATUS_ID = @ActiveId WHERE UPPER(TRIM(CAST(STATUS AS VARCHAR(100)))) = 'ACTIVE';
UPDATE HR_EMPLOYEE SET STATUS_ID = @SelectedId WHERE UPPER(TRIM(CAST(STATUS AS VARCHAR(100)))) = 'SELECTED';
UPDATE HR_EMPLOYEE SET STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE SET STATUS_ID = @HoldId WHERE UPPER(TRIM(CAST(STATUS AS VARCHAR(100)))) IN ('HOLD', 'ON HOLD', 'ONHOLD');
UPDATE HR_EMPLOYEE SET STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(STATUS AS VARCHAR(100)))) = 'CANCELLED';

-- Document Approvals (HR_EMPLOYEE)
UPDATE HR_EMPLOYEE SET PHOTO_VERIFIED_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(PHOTO_VERIFIED_STATUS AS VARCHAR(100)))) = 'PENDING' OR PHOTO_VERIFIED_STATUS IS NULL;
UPDATE HR_EMPLOYEE SET PHOTO_VERIFIED_STATUS_ID = @ApprovedId WHERE UPPER(TRIM(CAST(PHOTO_VERIFIED_STATUS AS VARCHAR(100)))) = 'APPROVED';
UPDATE HR_EMPLOYEE SET PHOTO_VERIFIED_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(PHOTO_VERIFIED_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE SET PHOTO_VERIFIED_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(PHOTO_VERIFIED_STATUS AS VARCHAR(100)))) = 'CANCELLED';

UPDATE HR_EMPLOYEE SET RESUME_VERIFIED_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(RESUME_VERIFIED_STATUS AS VARCHAR(100)))) = 'PENDING' OR RESUME_VERIFIED_STATUS IS NULL;
UPDATE HR_EMPLOYEE SET RESUME_VERIFIED_STATUS_ID = @ApprovedId WHERE UPPER(TRIM(CAST(RESUME_VERIFIED_STATUS AS VARCHAR(100)))) = 'APPROVED';
UPDATE HR_EMPLOYEE SET RESUME_VERIFIED_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(RESUME_VERIFIED_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE SET RESUME_VERIFIED_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(RESUME_VERIFIED_STATUS AS VARCHAR(100)))) = 'CANCELLED';

UPDATE HR_EMPLOYEE SET PAYSLIP_VERIFIED_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(PAYSLIP_VERIFIED_STATUS AS VARCHAR(100)))) = 'PENDING' OR PAYSLIP_VERIFIED_STATUS IS NULL;
UPDATE HR_EMPLOYEE SET PAYSLIP_VERIFIED_STATUS_ID = @ApprovedId WHERE UPPER(TRIM(CAST(PAYSLIP_VERIFIED_STATUS AS VARCHAR(100)))) = 'APPROVED';
UPDATE HR_EMPLOYEE SET PAYSLIP_VERIFIED_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(PAYSLIP_VERIFIED_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE SET PAYSLIP_VERIFIED_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(PAYSLIP_VERIFIED_STATUS AS VARCHAR(100)))) = 'CANCELLED';

UPDATE HR_EMPLOYEE SET AADHAR_VERIFIED_STATUS_ID = @PendingId WHERE UPPER(TRIM(CAST(AADHAR_VERIFIED_STATUS AS VARCHAR(100)))) = 'PENDING' OR AADHAR_VERIFIED_STATUS IS NULL;
UPDATE HR_EMPLOYEE SET AADHAR_VERIFIED_STATUS_ID = @ApprovedId WHERE UPPER(TRIM(CAST(AADHAR_VERIFIED_STATUS AS VARCHAR(100)))) = 'APPROVED';
UPDATE HR_EMPLOYEE SET AADHAR_VERIFIED_STATUS_ID = @RejectedId WHERE UPPER(TRIM(CAST(AADHAR_VERIFIED_STATUS AS VARCHAR(100)))) = 'REJECTED';
UPDATE HR_EMPLOYEE SET AADHAR_VERIFIED_STATUS_ID = @CancelledId WHERE UPPER(TRIM(CAST(AADHAR_VERIFIED_STATUS AS VARCHAR(100)))) = 'CANCELLED';


-- ==========================================
-- PHASE 4: Data integrity validation checks
-- ==========================================

IF EXISTS (SELECT 1 FROM HR_EMPLOYEE_ATS WHERE CALL_STATUS_ID IS NULL AND CALL_STATUS IS NOT NULL)
    THROW 50000, 'Migration aborted: Unmapped value found in HR_EMPLOYEE_ATS.CALL_STATUS', 1;

IF EXISTS (SELECT 1 FROM HR_EMPLOYEE_ATS WHERE INTERVIEW_STATUS_ID IS NULL AND INTERVIEW_STATUS IS NOT NULL)
    THROW 50000, 'Migration aborted: Unmapped value found in HR_EMPLOYEE_ATS.INTERVIEW_STATUS', 1;

IF EXISTS (SELECT 1 FROM HR_EMPLOYEE_ATS WHERE OFFER_STATUS_ID IS NULL AND OFFER_STATUS IS NOT NULL)
    THROW 50000, 'Migration aborted: Unmapped value found in HR_EMPLOYEE_ATS.OFFER_STATUS', 1;

IF EXISTS (SELECT 1 FROM HR_EMPLOYEE_ATS WHERE VERIFICATION_STATUS_ID IS NULL AND VERIFICATION_STATUS IS NOT NULL)
    THROW 50000, 'Migration aborted: Unmapped value found in HR_EMPLOYEE_ATS.VERIFICATION_STATUS', 1;

IF EXISTS (SELECT 1 FROM HR_APPLICANT_INTERVIEW WHERE INTERVIEW_STATUS_ID IS NULL AND INTERVIEW_STATUS IS NOT NULL)
    THROW 50000, 'Migration aborted: Unmapped value found in HR_APPLICANT_INTERVIEW.INTERVIEW_STATUS', 1;

IF EXISTS (SELECT 1 FROM HR_EMPLOYEE WHERE STATUS_ID IS NULL AND STATUS IS NOT NULL)
    THROW 50000, 'Migration aborted: Unmapped value found in HR_EMPLOYEE.STATUS', 1;


-- ==========================================
-- PHASE 5: Swapping and Renaming Columns
-- ==========================================

-- 1. HR_EMPLOYEE_ATS
ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN CALL_STATUS;
EXEC sp_rename 'HR_EMPLOYEE_ATS.CALL_STATUS_ID', 'CALL_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN INTERVIEW_STATUS;
EXEC sp_rename 'HR_EMPLOYEE_ATS.INTERVIEW_STATUS_ID', 'INTERVIEW_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN OFFER_STATUS;
EXEC sp_rename 'HR_EMPLOYEE_ATS.OFFER_STATUS_ID', 'OFFER_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN VERIFICATION_STATUS;
EXEC sp_rename 'HR_EMPLOYEE_ATS.VERIFICATION_STATUS_ID', 'VERIFICATION_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN BACKGROUND_VERIFICATION_STATUS;
EXEC sp_rename 'HR_EMPLOYEE_ATS.BACKGROUND_VERIFICATION_STATUS_ID', 'BACKGROUND_VERIFICATION_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN PHOTO_VERIFIED_STATUS;
EXEC sp_rename 'HR_EMPLOYEE_ATS.PHOTO_VERIFIED_STATUS_ID', 'PHOTO_VERIFIED_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN RESUME_VERIFIED_STATUS;
EXEC sp_rename 'HR_EMPLOYEE_ATS.RESUME_VERIFIED_STATUS_ID', 'RESUME_VERIFIED_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN PAYSLIP_VERIFIED_STATUS;
EXEC sp_rename 'HR_EMPLOYEE_ATS.PAYSLIP_VERIFIED_STATUS_ID', 'PAYSLIP_VERIFIED_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN AADHAR_VERIFIED_STATUS;
EXEC sp_rename 'HR_EMPLOYEE_ATS.AADHAR_VERIFIED_STATUS_ID', 'AADHAR_VERIFIED_STATUS', 'COLUMN';


-- 2. HR_APPLICANT_INTERVIEW
ALTER TABLE HR_APPLICANT_INTERVIEW DROP COLUMN INTERVIEW_STATUS;
EXEC sp_rename 'HR_APPLICANT_INTERVIEW.INTERVIEW_STATUS_ID', 'INTERVIEW_STATUS', 'COLUMN';

ALTER TABLE HR_APPLICANT_INTERVIEW DROP COLUMN INTERVIEW_RESULT;
EXEC sp_rename 'HR_APPLICANT_INTERVIEW.INTERVIEW_RESULT_ID', 'INTERVIEW_RESULT', 'COLUMN';


-- 3. HR_EMPLOYEE
ALTER TABLE HR_EMPLOYEE DROP COLUMN STATUS;
EXEC sp_rename 'HR_EMPLOYEE.STATUS_ID', 'STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE DROP COLUMN PHOTO_VERIFIED_STATUS;
EXEC sp_rename 'HR_EMPLOYEE.PHOTO_VERIFIED_STATUS_ID', 'PHOTO_VERIFIED_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE DROP COLUMN RESUME_VERIFIED_STATUS;
EXEC sp_rename 'HR_EMPLOYEE.RESUME_VERIFIED_STATUS_ID', 'RESUME_VERIFIED_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE DROP COLUMN PAYSLIP_VERIFIED_STATUS;
EXEC sp_rename 'HR_EMPLOYEE.PAYSLIP_VERIFIED_STATUS_ID', 'PAYSLIP_VERIFIED_STATUS', 'COLUMN';

ALTER TABLE HR_EMPLOYEE DROP COLUMN AADHAR_VERIFIED_STATUS;
EXEC sp_rename 'HR_EMPLOYEE.AADHAR_VERIFIED_STATUS_ID', 'AADHAR_VERIFIED_STATUS', 'COLUMN';


-- ==========================================
-- PHASE 6: Foreign Key Bindings
-- ==========================================

ALTER TABLE HR_EMPLOYEE_ATS ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_CALL_STATUS FOREIGN KEY (CALL_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE_ATS ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_INT_STATUS FOREIGN KEY (INTERVIEW_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE_ATS ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_OFFER_STATUS FOREIGN KEY (OFFER_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE_ATS ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_VER_STATUS FOREIGN KEY (VERIFICATION_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE_ATS ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_BG_STATUS FOREIGN KEY (BACKGROUND_VERIFICATION_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE_ATS ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_PHOTO_STATUS FOREIGN KEY (PHOTO_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE_ATS ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_RESUME_STATUS FOREIGN KEY (RESUME_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE_ATS ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_PAYSLIP_STATUS FOREIGN KEY (PAYSLIP_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE_ATS ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_AADHAR_STATUS FOREIGN KEY (AADHAR_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);

ALTER TABLE HR_APPLICANT_INTERVIEW ADD CONSTRAINT FK_HR_APPLICANT_INTERVIEW_STATUS FOREIGN KEY (INTERVIEW_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_APPLICANT_INTERVIEW ADD CONSTRAINT FK_HR_APPLICANT_INTERVIEW_RESULT FOREIGN KEY (INTERVIEW_RESULT) REFERENCES AD_STATUS_MASTER(ID);

ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_STATUS FOREIGN KEY (STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_PHOTO_STATUS FOREIGN KEY (PHOTO_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_RESUME_STATUS FOREIGN KEY (RESUME_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_PAYSLIP_STATUS FOREIGN KEY (PAYSLIP_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_AADHAR_STATUS FOREIGN KEY (AADHAR_VERIFIED_STATUS) REFERENCES AD_STATUS_MASTER(ID);
