-- ---------------------------------------------------------
-- Description: Add Extra Fields to AD_DIVISION
-- Author: Antigravity
-- Date: 2026-08-19
-- ---------------------------------------------------------

IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[AD_DIVISION]') 
    AND name = 'MOBILE_NO'
)
BEGIN
    ALTER TABLE [dbo].[AD_DIVISION] ADD [MOBILE_NO] NVARCHAR(20) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [PAN_NO] NVARCHAR(50) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [PF_NO] NVARCHAR(50) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [ESI_NO] NVARCHAR(50) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [IE_CODE] NVARCHAR(50) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [CIN_NO] NVARCHAR(50) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [EMAIL_ID] NVARCHAR(100) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [WEBSITE] NVARCHAR(100) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [EWAYBILL_USER_NAME] NVARCHAR(100) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [EWAYBILL_PASSWORD] NVARCHAR(100) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [GST_USER_NAME] NVARCHAR(100) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [EINVOICE_USER_NAME] NVARCHAR(100) NULL;
    ALTER TABLE [dbo].[AD_DIVISION] ADD [EINVOICE_PASSWORD] NVARCHAR(100) NULL;
END
GO
