-- ==============================================================================
-- Migration Script: V388.0 Create BOS Notebook System
-- Description: Creates professional database schema for the BOS Notebook Assistant
--              and AI Workflow Automation engine with strict foreign key relations
--              linking to core HR, QMS, Sales, and Asset masters.
-- Audit Convention: CREATED_BY / UPDATED_BY store NVARCHAR(50) user IDs matching
--                   the AD_USER_CREDENTIAL.USER_ID pattern used by all other tables.
-- ==============================================================================

-- 1. Create SYS_NOTEBOOK
IF OBJECT_ID('dbo.SYS_NOTEBOOK', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SYS_NOTEBOOK (
        ID              BIGINT IDENTITY(1,1)    NOT NULL,
        TITLE           NVARCHAR(255)           NOT NULL,
        DESCRIPTION     NVARCHAR(500)           NULL,
        OWNER_ID        BIGINT                  NOT NULL, -- FK -> HR_EMPLOYEE.ID
        COMPANY_ID      BIGINT                  NOT NULL,
        DIVISION_ID     BIGINT                  NOT NULL,
        SOURCE_COUNT    INT                     NOT NULL DEFAULT 0,
        CREATED_BY      NVARCHAR(50)            NOT NULL,
        CREATED_DATE    DATETIME                NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      NVARCHAR(50)            NULL,
        UPDATED_DATE    DATETIME                NULL,
        ACTIVE_STATUS   CHAR(1)                 NOT NULL DEFAULT 'Y',
        CONSTRAINT PK_SYS_NOTEBOOK PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT FK_SYS_NOTEBOOK_OWNER FOREIGN KEY (OWNER_ID) REFERENCES dbo.HR_EMPLOYEE(ID),
        CONSTRAINT FK_SYS_NOTEBOOK_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SYS_NOTEBOOK_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE NONCLUSTERED INDEX IX_SYS_NOTEBOOK_OWNER ON dbo.SYS_NOTEBOOK(OWNER_ID);
    CREATE NONCLUSTERED INDEX IX_SYS_NOTEBOOK_COMPANY_DIV ON dbo.SYS_NOTEBOOK(COMPANY_ID, DIVISION_ID);
    CREATE NONCLUSTERED INDEX IX_SYS_NOTEBOOK_ACTIVE ON dbo.SYS_NOTEBOOK(ACTIVE_STATUS);
    PRINT 'Created SYS_NOTEBOOK table';
END;

-- 2. Create SYS_NOTEBOOK_SOURCE
IF OBJECT_ID('dbo.SYS_NOTEBOOK_SOURCE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SYS_NOTEBOOK_SOURCE (
        ID                  BIGINT IDENTITY(1,1)    NOT NULL,
        NOTEBOOK_ID         BIGINT                  NOT NULL,
        SOURCE_TYPE         NVARCHAR(50)            NOT NULL, -- 'FILE','CHECKLIST','EMPLOYEE','MACHINE','CUSTOMER','TICKET'
        SOURCE_NAME         NVARCHAR(255)           NOT NULL,
        FILE_PATH           NVARCHAR(500)           NULL,
        LINKED_EMPLOYEE_ID  BIGINT                  NULL,     -- FK -> HR_EMPLOYEE.ID
        LINKED_MACHINE_ID   BIGINT                  NULL,     -- FK -> QMT_MACHINE.ID
        LINKED_CUSTOMER_ID  BIGINT                  NULL,     -- FK -> SLS_CUSTOMER.ID
        LINKED_TICKET_ID    INT                     NULL,     -- FK -> TICKET_TRACEABILITY_CENTER.ROW_ID
        CREATED_BY          NVARCHAR(50)            NOT NULL,
        CREATED_DATE        DATETIME                NOT NULL DEFAULT GETDATE(),
        UPDATED_BY          NVARCHAR(50)            NULL,
        UPDATED_DATE        DATETIME                NULL,
        ACTIVE_STATUS       CHAR(1)                 NOT NULL DEFAULT 'Y',
        CONSTRAINT PK_SYS_NOTEBOOK_SOURCE PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT FK_SYS_NB_SOURCE_NOTEBOOK FOREIGN KEY (NOTEBOOK_ID) REFERENCES dbo.SYS_NOTEBOOK(ID) ON DELETE CASCADE,
        CONSTRAINT FK_SYS_NB_SOURCE_EMPLOYEE FOREIGN KEY (LINKED_EMPLOYEE_ID) REFERENCES dbo.HR_EMPLOYEE(ID),
        CONSTRAINT FK_SYS_NB_SOURCE_MACHINE FOREIGN KEY (LINKED_MACHINE_ID) REFERENCES dbo.QMT_MACHINE(ID),
        CONSTRAINT FK_SYS_NB_SOURCE_CUSTOMER FOREIGN KEY (LINKED_CUSTOMER_ID) REFERENCES dbo.SLS_CUSTOMER(ID),
        CONSTRAINT FK_SYS_NB_SOURCE_TICKET FOREIGN KEY (LINKED_TICKET_ID) REFERENCES dbo.TICKET_TRACEABILITY_CENTER(ROW_ID),
        CONSTRAINT FK_SYS_NB_SOURCE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SYS_NB_SOURCE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE NONCLUSTERED INDEX IX_SYS_NB_SOURCE_NOTEBOOK ON dbo.SYS_NOTEBOOK_SOURCE(NOTEBOOK_ID);
    CREATE NONCLUSTERED INDEX IX_SYS_NB_SOURCE_TYPE ON dbo.SYS_NOTEBOOK_SOURCE(SOURCE_TYPE);
    CREATE NONCLUSTERED INDEX IX_SYS_NB_SOURCE_ACTIVE ON dbo.SYS_NOTEBOOK_SOURCE(ACTIVE_STATUS);
    PRINT 'Created SYS_NOTEBOOK_SOURCE table';
END;

-- 3. Create SYS_NOTEBOOK_NOTE
IF OBJECT_ID('dbo.SYS_NOTEBOOK_NOTE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SYS_NOTEBOOK_NOTE (
        ID              BIGINT IDENTITY(1,1)    NOT NULL,
        NOTEBOOK_ID     BIGINT                  NOT NULL,
        TITLE           NVARCHAR(255)           NOT NULL,
        CONTENT         NVARCHAR(MAX)           NOT NULL,
        CREATED_BY      NVARCHAR(50)            NOT NULL,
        CREATED_DATE    DATETIME                NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      NVARCHAR(50)            NULL,
        UPDATED_DATE    DATETIME                NULL,
        ACTIVE_STATUS   CHAR(1)                 NOT NULL DEFAULT 'Y',
        CONSTRAINT PK_SYS_NOTEBOOK_NOTE PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT FK_SYS_NB_NOTE_NOTEBOOK FOREIGN KEY (NOTEBOOK_ID) REFERENCES dbo.SYS_NOTEBOOK(ID) ON DELETE CASCADE,
        CONSTRAINT FK_SYS_NB_NOTE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SYS_NB_NOTE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE NONCLUSTERED INDEX IX_SYS_NB_NOTE_NOTEBOOK ON dbo.SYS_NOTEBOOK_NOTE(NOTEBOOK_ID);
    PRINT 'Created SYS_NOTEBOOK_NOTE table';
END;

-- 4. Create SYS_AI_WORKFLOW_RULE
IF OBJECT_ID('dbo.SYS_AI_WORKFLOW_RULE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SYS_AI_WORKFLOW_RULE (
        ID                  BIGINT IDENTITY(1,1)    NOT NULL,
        NOTEBOOK_ID         BIGINT                  NOT NULL,
        RULE_NAME           NVARCHAR(255)           NOT NULL,
        TRIGGER_TYPE        NVARCHAR(100)           NOT NULL, -- 'MACHINE_FAILURE','TICKET_CREATION','QMS_DEVIATION'
        TRIGGER_CONDITION   NVARCHAR(MAX)           NOT NULL, -- JSON formatted trigger logic
        ACTION_TYPE         NVARCHAR(100)           NOT NULL, -- 'CREATE_CAPA','NOTIFY_QA','SEND_EMAIL','CREATE_TICKET'
        ACTION_PAYLOAD      NVARCHAR(MAX)           NOT NULL, -- JSON payload details
        PRIORITY            INT                     NOT NULL DEFAULT 0,
        EXECUTION_COUNT     INT                     NOT NULL DEFAULT 0,
        LAST_EXECUTED_DATE  DATETIME                NULL,
        CREATED_BY          NVARCHAR(50)            NOT NULL,
        CREATED_DATE        DATETIME                NOT NULL DEFAULT GETDATE(),
        UPDATED_BY          NVARCHAR(50)            NULL,
        UPDATED_DATE        DATETIME                NULL,
        ACTIVE_STATUS       CHAR(1)                 NOT NULL DEFAULT 'Y',
        CONSTRAINT PK_SYS_AI_WORKFLOW_RULE PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT FK_SYS_AI_WF_RULE_NOTEBOOK FOREIGN KEY (NOTEBOOK_ID) REFERENCES dbo.SYS_NOTEBOOK(ID) ON DELETE CASCADE,
        CONSTRAINT FK_SYS_AI_WF_RULE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_SYS_AI_WF_RULE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE NONCLUSTERED INDEX IX_SYS_AI_WF_RULE_NOTEBOOK ON dbo.SYS_AI_WORKFLOW_RULE(NOTEBOOK_ID);
    CREATE NONCLUSTERED INDEX IX_SYS_AI_WF_RULE_TRIGGER ON dbo.SYS_AI_WORKFLOW_RULE(TRIGGER_TYPE);
    CREATE NONCLUSTERED INDEX IX_SYS_AI_WF_RULE_ACTIVE ON dbo.SYS_AI_WORKFLOW_RULE(ACTIVE_STATUS);
    PRINT 'Created SYS_AI_WORKFLOW_RULE table';
END;
