IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SCHEDULE_CONFIGURATION]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[SCHEDULE_CONFIGURATION] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [SCHEDULAR_NAME] NVARCHAR(50) NULL,
        [SCHEDULAR_TIME] DATETIME NULL,
        [FREQUENCY] NVARCHAR(50) NULL,
        [STATUS] BIT NULL DEFAULT 1,
        CONSTRAINT [PK_SCHEDULE_CONFIGURATION] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
GO

-- Insert default rows if they do not exist
IF NOT EXISTS (SELECT 1 FROM [dbo].[SCHEDULE_CONFIGURATION] WHERE [SCHEDULAR_NAME] = 'CHECKLIST')
BEGIN
    INSERT INTO [dbo].[SCHEDULE_CONFIGURATION] ([SCHEDULAR_NAME], [STATUS]) VALUES ('CHECKLIST', 1);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SCHEDULE_CONFIGURATION] WHERE [SCHEDULAR_NAME] = 'AUDIT')
BEGIN
    INSERT INTO [dbo].[SCHEDULE_CONFIGURATION] ([SCHEDULAR_NAME], [STATUS]) VALUES ('AUDIT', 1);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SCHEDULE_CONFIGURATION] WHERE [SCHEDULAR_NAME] = 'MEETING')
BEGIN
    INSERT INTO [dbo].[SCHEDULE_CONFIGURATION] ([SCHEDULAR_NAME], [STATUS]) VALUES ('MEETING', 1);
END
GO
