-- SQL Migration Script: Add Index to QMS_CHECKLIST_CLOSED for Created Date and Checklist Date Performance Optimization
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_CHECKLIST_CLOSED_CREATED_DATE' AND object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CHECKLIST_CLOSED_CREATED_DATE ON QMS_CHECKLIST_CLOSED(CREATED_DATE);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_CHECKLIST_CLOSED_CHECKLIST_DATE' AND object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CHECKLIST_CLOSED_CHECKLIST_DATE ON QMS_CHECKLIST_CLOSED(CHECKLIST_DATE);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_CHECKLIST_CLOSED_ASSIGNED_DATE' AND object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CHECKLIST_CLOSED_ASSIGNED_DATE ON QMS_CHECKLIST_CLOSED(ASSIGNED_DATE);
END
GO
