-- ============================================================================
-- V376.0  Register Inventory Reports Pages and grant access
-- ============================================================================

-- 1. Register INV_TRANSACTION_TYPE
IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'AD1190')
BEGIN
    INSERT INTO BOS_PAGES (MOD_ID, SUB_MOD_ID, PAGE_CODE, PAGE_NAME, ENABLED, PAGE_URL, ICON)
    VALUES (1, 31, 'AD1190', 'Item Transaction Type Master', 1, '/inventory/transaction-type', 'IconSettings');
    PRINT 'Page AD1190 registered in BOS_PAGES.';
END
ELSE
BEGIN
    PRINT 'Page AD1190 already exists in BOS_PAGES — skipped.';
END
GO

-- 2. Register INV1001 (Current Stock)
IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'INV1001')
BEGIN
    INSERT INTO BOS_PAGES (MOD_ID, SUB_MOD_ID, PAGE_CODE, PAGE_NAME, ENABLED, PAGE_URL, ICON)
    VALUES (1, 31, 'INV1001', 'Current Stock Report', 1, '/reports/inventory/current-stock', 'IconCategory');
    PRINT 'Page INV1001 registered in BOS_PAGES.';
END
ELSE
BEGIN
    PRINT 'Page INV1001 already exists in BOS_PAGES — skipped.';
END
GO

-- 3. Register INV1002 (Stock Ledger)
IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'INV1002')
BEGIN
    INSERT INTO BOS_PAGES (MOD_ID, SUB_MOD_ID, PAGE_CODE, PAGE_NAME, ENABLED, PAGE_URL, ICON)
    VALUES (1, 31, 'INV1002', 'Stock Ledger Report', 1, '/reports/inventory/stock-ledger', 'IconFileText');
    PRINT 'Page INV1002 registered in BOS_PAGES.';
END
ELSE
BEGIN
    PRINT 'Page INV1002 already exists in BOS_PAGES — skipped.';
END
GO

-- 4. Register INV1003 (Rejection Stock)
IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'INV1003')
BEGIN
    INSERT INTO BOS_PAGES (MOD_ID, SUB_MOD_ID, PAGE_CODE, PAGE_NAME, ENABLED, PAGE_URL, ICON)
    VALUES (1, 31, 'INV1003', 'Rejection Stock Report', 1, '/reports/inventory/rejection-stock', 'IconCircleX');
    PRINT 'Page INV1003 registered in BOS_PAGES.';
END
ELSE
BEGIN
    PRINT 'Page INV1003 already exists in BOS_PAGES — skipped.';
END
GO

-- 5. Register INV1004 (Stock Movement)
IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'INV1004')
BEGIN
    INSERT INTO BOS_PAGES (MOD_ID, SUB_MOD_ID, PAGE_CODE, PAGE_NAME, ENABLED, PAGE_URL, ICON)
    VALUES (1, 31, 'INV1004', 'Stock Movement Report', 1, '/reports/inventory/stock-movement', 'IconTimeline');
    PRINT 'Page INV1004 registered in BOS_PAGES.';
END
ELSE
BEGIN
    PRINT 'Page INV1004 already exists in BOS_PAGES — skipped.';
END
GO

-- 6. Grant access to all Admin users (or all users for now so it works without being blocked)
-- For simplicity, giving access to the user who created it or USER_ID=1 (Super Admin).
-- Using a generic grant to any user who has access to M3230 to ensure it gets seeded.
DECLARE @inv1001PageId INT, @inv1002PageId INT, @inv1003PageId INT, @inv1004PageId INT, @invTransTypePageId INT;

SELECT @inv1001PageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'INV1001';
SELECT @inv1002PageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'INV1002';
SELECT @inv1003PageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'INV1003';
SELECT @inv1004PageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'INV1004';
SELECT @invTransTypePageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'INV_TRANSACTION_TYPE';

-- Grant access for INV1001
IF @inv1001PageId IS NOT NULL
BEGIN
    INSERT INTO BOS_USER_PAGE_AUTH (USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, READ_ACS, WRITE, DELETE_ACS, EXPORT, APPROVAL, MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, CREATED_BY, CREATED_DATE)
    SELECT USER_ID, @inv1001PageId, 31, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'SYSTEM', SYSDATETIME()
    FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = (SELECT PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'M3230')
    AND USER_ID NOT IN (SELECT USER_ID FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = @inv1001PageId);
END

-- Grant access for INV1002
IF @inv1002PageId IS NOT NULL
BEGIN
    INSERT INTO BOS_USER_PAGE_AUTH (USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, READ_ACS, WRITE, DELETE_ACS, EXPORT, APPROVAL, MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, CREATED_BY, CREATED_DATE)
    SELECT USER_ID, @inv1002PageId, 31, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'SYSTEM', SYSDATETIME()
    FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = (SELECT PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'M3230')
    AND USER_ID NOT IN (SELECT USER_ID FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = @inv1002PageId);
END

-- Grant access for INV1003
IF @inv1003PageId IS NOT NULL
BEGIN
    INSERT INTO BOS_USER_PAGE_AUTH (USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, READ_ACS, WRITE, DELETE_ACS, EXPORT, APPROVAL, MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, CREATED_BY, CREATED_DATE)
    SELECT USER_ID, @inv1003PageId, 31, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'SYSTEM', SYSDATETIME()
    FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = (SELECT PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'M3230')
    AND USER_ID NOT IN (SELECT USER_ID FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = @inv1003PageId);
END

-- Grant access for INV1004
IF @inv1004PageId IS NOT NULL
BEGIN
    INSERT INTO BOS_USER_PAGE_AUTH (USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, READ_ACS, WRITE, DELETE_ACS, EXPORT, APPROVAL, MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, CREATED_BY, CREATED_DATE)
    SELECT USER_ID, @inv1004PageId, 31, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'SYSTEM', SYSDATETIME()
    FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = (SELECT PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'M3230')
    AND USER_ID NOT IN (SELECT USER_ID FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = @inv1004PageId);
END

-- Grant access for INV_TRANSACTION_TYPE
IF @invTransTypePageId IS NOT NULL
BEGIN
    INSERT INTO BOS_USER_PAGE_AUTH (USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, READ_ACS, WRITE, DELETE_ACS, EXPORT, APPROVAL, MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, CREATED_BY, CREATED_DATE)
    SELECT USER_ID, @invTransTypePageId, 31, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'SYSTEM', SYSDATETIME()
    FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = (SELECT PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'M3230')
    AND USER_ID NOT IN (SELECT USER_ID FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = @invTransTypePageId);
END
GO
