-- Organization: Autonoma ERP
-- Description: Create Production Plan Head & Trans tables, indexes, constraints, and BOS Page registration for PP1010
-- Created At: 2026-09-05

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PP_PRODUCTION_PLAN_HEAD')
BEGIN
    CREATE TABLE PP_PRODUCTION_PLAN_HEAD (
        PLAN_NO BIGINT IDENTITY(100001,1) PRIMARY KEY,
        PLAN_DATE DATETIME NOT NULL DEFAULT GETDATE(),
        PRODUCT_ID BIGINT NULL,
        SOURCE_TYPE VARCHAR(50) NOT NULL,
        SOURCE_ID BIGINT NULL,
        SOURCE_NO VARCHAR(50) NULL,
        DIVISION_ID BIGINT NULL,
        PRIORITY VARCHAR(20) NULL DEFAULT 'MEDIUM',
        STATUS VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
        REMARKS NVARCHAR(MAX) NULL,
        CREATED_BY BIGINT NULL,
        CREATED_DATE DATETIME NULL DEFAULT GETDATE(),
        UPDATED_BY BIGINT NULL,
        UPDATED_DATE DATETIME NULL
    );
END
GO

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'PP_PRODUCTION_PLAN_HEAD')
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PP_PRODUCTION_PLAN_HEAD') AND name = 'PRODUCT_ID')
    BEGIN
        ALTER TABLE PP_PRODUCTION_PLAN_HEAD ADD PRODUCT_ID BIGINT NULL;
    END
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PP_PRODUCTION_PLAN_TRANS')
BEGIN
    CREATE TABLE PP_PRODUCTION_PLAN_TRANS (
        PLAN_TRANS_NO BIGINT IDENTITY(200001,1) PRIMARY KEY,
        PLAN_NO BIGINT NOT NULL,
        PARENT_TRANS_NO BIGINT NULL,
        SOURCE_LINE_ID BIGINT NULL,
        PRODUCT_ID BIGINT NOT NULL,
        ITEM_TYPE VARCHAR(50) NULL,
        REQUIREMENT_TYPE VARCHAR(30) NOT NULL,
        BOM_ID BIGINT NULL,
        BOM_VERSION_ID BIGINT NULL,
        BOM_LEVEL INT NOT NULL DEFAULT 0,
        GROSS_QTY DECIMAL(18, 4) NOT NULL DEFAULT 0,
        STOCK_QTY DECIMAL(18, 4) NOT NULL DEFAULT 0,
        WIP_QTY DECIMAL(18, 4) NOT NULL DEFAULT 0,
        OPEN_PRODUCTION_QTY DECIMAL(18, 4) NOT NULL DEFAULT 0,
        NET_QTY DECIMAL(18, 4) NOT NULL DEFAULT 0,
        UOM VARCHAR(20) NULL,
        REQUIRED_DATE DATETIME NULL,
        STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
        CREATED_BY BIGINT NULL,
        CREATED_DATE DATETIME NULL DEFAULT GETDATE(),
        UPDATED_BY BIGINT NULL,
        UPDATED_DATE DATETIME NULL,
        CONSTRAINT FK_PP_TRANS_PLAN_NO FOREIGN KEY (PLAN_NO) REFERENCES PP_PRODUCTION_PLAN_HEAD(PLAN_NO) ON DELETE CASCADE,
        CONSTRAINT FK_PP_TRANS_PARENT FOREIGN KEY (PARENT_TRANS_NO) REFERENCES PP_PRODUCTION_PLAN_TRANS(PLAN_TRANS_NO)
    );
END
GO

-- Filtered Unique Index for 1 Active Source Plan Rule
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_PP_HEAD_SOURCE' AND object_id = OBJECT_ID('PP_PRODUCTION_PLAN_HEAD'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_PP_HEAD_SOURCE
    ON PP_PRODUCTION_PLAN_HEAD (SOURCE_TYPE, SOURCE_ID)
    WHERE SOURCE_ID IS NOT NULL AND STATUS <> 'CANCELLED';
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PP_HEAD_PRODUCT' AND object_id = OBJECT_ID('PP_PRODUCTION_PLAN_HEAD'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_PP_HEAD_PRODUCT ON PP_PRODUCTION_PLAN_HEAD(PRODUCT_ID);
END
GO

-- Performance Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PP_TRANS_PLAN_NO' AND object_id = OBJECT_ID('PP_PRODUCTION_PLAN_TRANS'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_PP_TRANS_PLAN_NO ON PP_PRODUCTION_PLAN_TRANS(PLAN_NO);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PP_TRANS_PARENT' AND object_id = OBJECT_ID('PP_PRODUCTION_PLAN_TRANS'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_PP_TRANS_PARENT ON PP_PRODUCTION_PLAN_TRANS(PARENT_TRANS_NO);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PP_TRANS_PRODUCT' AND object_id = OBJECT_ID('PP_PRODUCTION_PLAN_TRANS'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_PP_TRANS_PRODUCT ON PP_PRODUCTION_PLAN_TRANS(PRODUCT_ID);
END
GO

-- Register Page Code PP1010 in BOS_PAGES
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'BOS_PAGES')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'PP1010')
    BEGIN
        INSERT INTO BOS_PAGES (
            PAGE_CODE, PAGE_NAME, PAGE_URL, MODULE_ID, SUBMODULE_ID,
            DISPLAY_ORDER, IS_ACTIVE, CREATED_BY, CREATED_DATE
        )
        VALUES (
            'PP1010', 'Production Planning & BOM Explosion', '/production/production-plan',
            (SELECT TOP 1 ID FROM BOS_MODULES WHERE MODULE_CODE = 'PROD' OR MODULE_NAME LIKE '%Production%'),
            (SELECT TOP 1 ID FROM BOS_SUBMODULES WHERE SUBMODULE_NAME LIKE '%Plan%' OR MODULE_ID = (SELECT TOP 1 ID FROM BOS_MODULES WHERE MODULE_CODE = 'PROD')),
            1, 1, 1, GETDATE()
        );
    END
END
GO
