IF EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('HRA_LEAVE_ENCASHMENT_VERIFIED') 
    AND name = 'REF_NO'
)
BEGIN
    ALTER TABLE HRA_LEAVE_ENCASHMENT_VERIFIED
    DROP COLUMN REF_NO;
END
GO
