-- Fix column name in FA_ACCOUNT_LEDGER if it was not renamed or is missing
IF COL_LENGTH('FA_ACCOUNT_LEDGER', 'FRIEIGHT_APPLICABLE') IS NULL
BEGIN
    IF COL_LENGTH('FA_ACCOUNT_LEDGER', 'FRIEGHT_APPLICABLE') IS NOT NULL
    BEGIN
        EXEC sp_rename 'FA_ACCOUNT_LEDGER.FRIEGHT_APPLICABLE', 'FRIEIGHT_APPLICABLE', 'COLUMN';
    END
    ELSE
    BEGIN
        ALTER TABLE FA_ACCOUNT_LEDGER ADD FRIEIGHT_APPLICABLE bit;
    END
END

-- Fix LEDGER_TYPE column if missing
IF COL_LENGTH('FA_ACCOUNT_LEDGER', 'LEDGER_TYPE') IS NULL
BEGIN
    ALTER TABLE FA_ACCOUNT_LEDGER ADD LEDGER_TYPE nvarchar(20);
END

-- Safely make SHORT_NAME NOT NULL by first backfilling NULLs
UPDATE FA_ACCOUNT_LEDGER SET SHORT_NAME = REFERENCE_CODE WHERE SHORT_NAME IS NULL OR TRIM(SHORT_NAME) = '';
UPDATE FA_ACCOUNT_LEDGER SET SHORT_NAME = 'L-' + CAST(ID as nvarchar(10)) WHERE SHORT_NAME IS NULL OR TRIM(SHORT_NAME) = '';
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN SHORT_NAME nvarchar(25) NOT NULL;

-- Safely add UQ constraint on SHORT_NAME after de-duplicating any existing records
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = 'UQ_FA_ACCOUNT_LEDGER_SHORT_NAME')
BEGIN
    -- De-duplicate if any duplicates exist
    ;WITH CTE AS (
        SELECT ID, SHORT_NAME, ROW_NUMBER() OVER (PARTITION BY SHORT_NAME ORDER BY ID) as rn
        FROM FA_ACCOUNT_LEDGER
    )
    UPDATE FA_ACCOUNT_LEDGER 
    SET SHORT_NAME = FA_ACCOUNT_LEDGER.SHORT_NAME + '-' + CAST(FA_ACCOUNT_LEDGER.ID as nvarchar(10))
    FROM FA_ACCOUNT_LEDGER
    INNER JOIN CTE ON FA_ACCOUNT_LEDGER.ID = CTE.ID
    WHERE CTE.rn > 1;

    ALTER TABLE FA_ACCOUNT_LEDGER ADD CONSTRAINT UQ_FA_ACCOUNT_LEDGER_SHORT_NAME UNIQUE (SHORT_NAME);
END

-- Safely make LEDGER_NAME NOT NULL by first backfilling NULLs
UPDATE FA_ACCOUNT_LEDGER SET LEDGER_NAME = 'Ledger-' + CAST(ID as nvarchar(10)) WHERE LEDGER_NAME IS NULL OR TRIM(LEDGER_NAME) = '';
ALTER TABLE FA_ACCOUNT_LEDGER ALTER COLUMN LEDGER_NAME nvarchar(100) NOT NULL;

-- Drop legacy columns if present
IF COL_LENGTH('FA_ACCOUNT_LEDGER', 'IS_OTHERS') IS NOT NULL
BEGIN
    ALTER TABLE FA_ACCOUNT_LEDGER DROP COLUMN IS_OTHERS;
END

IF COL_LENGTH('FA_ACCOUNT_LEDGER', 'TDS_APPLICABLE') IS NOT NULL
BEGIN
    ALTER TABLE FA_ACCOUNT_LEDGER DROP COLUMN TDS_APPLICABLE;
END
