-- Migration script to add ENQUIRY_PREFIX, ENQUIRY_SUFFIX and ENQUIRY_DIGIT to AD_PREFIX_CREDENTIALS table.
-- Last updated: August 10, 2026

IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'AD_PREFIX_CREDENTIALS' AND COLUMN_NAME = 'ENQUIRY_PREFIX'
)
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD ENQUIRY_PREFIX NVARCHAR(20) NULL;
END;

IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'AD_PREFIX_CREDENTIALS' AND COLUMN_NAME = 'ENQUIRY_SUFFIX'
)
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD ENQUIRY_SUFFIX NVARCHAR(20) NULL;
END;

IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'AD_PREFIX_CREDENTIALS' AND COLUMN_NAME = 'ENQUIRY_DIGIT'
)
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD ENQUIRY_DIGIT INT NULL;
END;
