-- Migration V389.0: Add CONFIG_ID to QMS_MEETING_SCHEDULE table
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') AND name = 'CONFIG_ID')
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ADD CONFIG_ID BIGINT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_QMS_MEETING_SCHEDULE_CONFIG' AND parent_object_id = OBJECT_ID('QMS_MEETING_SCHEDULE'))
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ADD CONSTRAINT FK_QMS_MEETING_SCHEDULE_CONFIG FOREIGN KEY (CONFIG_ID) REFERENCES QMS_SCHEDULE_MEETING_CONFIG(ID);
END
GO
