-- Adding missing foreign key indexes to QMS_MEETING_PARTICIPANT_MAPPING to prevent full table scans and improve join performance
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_MEETING_PART_MAP_SCHED' AND object_id = OBJECT_ID('QMS_MEETING_PARTICIPANT_MAPPING'))
BEGIN
    CREATE INDEX [IX_QMS_MEETING_PART_MAP_SCHED] ON [dbo].[QMS_MEETING_PARTICIPANT_MAPPING] ([SCHEDULE_ID]);
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_QMS_MEETING_PART_MAP_EMP' AND object_id = OBJECT_ID('QMS_MEETING_PARTICIPANT_MAPPING'))
BEGIN
    CREATE INDEX [IX_QMS_MEETING_PART_MAP_EMP] ON [dbo].[QMS_MEETING_PARTICIPANT_MAPPING] ([EMPLOYEE_ID]);
END
GO
