-- Idempotent script to bridge ITEM_TRANSACTION and ITEM_TRANSACTIONS table names in AT_NUTECH database
IF OBJECT_ID('dbo.ITEM_TRANSACTION', 'U') IS NULL AND OBJECT_ID('dbo.ITEM_TRANSACTION', 'V') IS NULL AND OBJECT_ID('dbo.ITEM_TRANSACTION', 'SN') IS NULL
BEGIN
    IF OBJECT_ID('dbo.ITEM_TRANSACTIONS', 'U') IS NOT NULL
    BEGIN
        CREATE SYNONYM dbo.ITEM_TRANSACTION FOR dbo.ITEM_TRANSACTIONS;
    END
END;

IF OBJECT_ID('dbo.ITEM_TRANSACTIONS', 'U') IS NULL AND OBJECT_ID('dbo.ITEM_TRANSACTIONS', 'V') IS NULL AND OBJECT_ID('dbo.ITEM_TRANSACTIONS', 'SN') IS NULL
BEGIN
    IF OBJECT_ID('dbo.ITEM_TRANSACTION', 'U') IS NOT NULL
    BEGIN
        CREATE SYNONYM dbo.ITEM_TRANSACTIONS FOR dbo.ITEM_TRANSACTION;
    END
END;
