CREATE TABLE SM_ADDITIONAL_CHARGES (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CHARGES NVARCHAR(300) NULL,
    CALCULATION_TYPE NVARCHAR(20) NULL,
    STATUS BIT DEFAULT 1,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    CONSTRAINT FK_SM_ADD_CHARGES_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_SM_ADD_CHARGES_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);
