-- ===================================================================================
-- Migration: 20260801_V1099.0__Create_HR_Setting_Master_Table.sql
-- Module: HR / Policy & Settings Configuration
-- Purpose: Dedicated HR_SETTING_MASTER table for all 6 HR policy categories
-- ===================================================================================

IF OBJECT_ID('HR_SETTING_MASTER', 'U') IS NULL
BEGIN
    CREATE TABLE HR_SETTING_MASTER (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        
        -- Category 1: Leave Apply Policy
        LEAVE_ALLOW_BACKDATED NVARCHAR(10) DEFAULT 'YES',
        LEAVE_MAX_BACKDATED_DAYS INT DEFAULT 3,
        LEAVE_ADVANCE_NOTICE_DAYS INT DEFAULT 1,
        SANDWICH_LEAVE_ENABLED NVARCHAR(10) DEFAULT 'YES',
        LEAVE_ALLOW_NEGATIVE_BALANCE_GLOBAL NVARCHAR(10) DEFAULT 'NO',

        -- Category 2: OD Apply Policy
        OD_ALLOW_PAST_DATES NVARCHAR(10) DEFAULT 'NO',
        OD_MAX_BACKDATED_DAYS INT DEFAULT 2,
        OD_MAX_REQUESTS_PER_MONTH INT DEFAULT 5,
        OD_MAX_DAYS_PER_REQUEST INT DEFAULT 7,
        OD_DOC_REQUIRED_THRESHOLD_DAYS INT DEFAULT 3,

        -- Category 3: Permission Apply Policy
        PERMISSION_ALLOW_PAST_DATES NVARCHAR(10) DEFAULT 'NO',
        PERMISSION_MAX_BACKDATED_DAYS INT DEFAULT 1,
        PERMISSION_ALLOW_SAME_DAY NVARCHAR(10) DEFAULT 'YES',
        PERMISSION_MAX_REQUESTS_PER_MONTH INT DEFAULT 2,
        PERMISSION_MAX_MINUTES_PER_REQUEST INT DEFAULT 60,
        PERMISSION_MAX_TOTAL_MINUTES_PER_MONTH INT DEFAULT 120,

        -- Category 4: Attendance & Loss of Minutes (LOM) Policy
        LOM_GRACE_MINUTES INT DEFAULT 15,
        LOM_PERMISSION_WAIVE_ENABLED NVARCHAR(10) DEFAULT 'YES',
        LOM_DEDUCTION_FACTOR DECIMAL(5,2) DEFAULT 1.00,
        LATE_ARRIVAL_THRESHOLD_MINUTES INT DEFAULT 30,

        -- Category 5: Overtime & Biometric eSSL Policy
        OT_CALCULATION_INTERVAL_MINUTES INT DEFAULT 30,
        OT_MIN_MINUTES_REQUIRED INT DEFAULT 60,
        OT_FACTORIAL DECIMAL(5,2) DEFAULT 1.50,
        ESSL_SYNC_INTERVAL_MINUTES INT DEFAULT 15,
        ESSL_AUTO_MIGRATION_ACTIVE NVARCHAR(10) DEFAULT 'YES',

        -- Category 6: Payroll & Salary Components Policy
        DEFAULT_PF_ENABLED NVARCHAR(10) DEFAULT 'YES',
        DEFAULT_ESI_ENABLED NVARCHAR(10) DEFAULT 'YES',
        DEFAULT_PROFESSIONAL_TAX_ENABLED NVARCHAR(10) DEFAULT 'YES',
        DEFAULT_LTA_ELIGIBLE NVARCHAR(10) DEFAULT 'NO',
        PAYSLIP_AUTO_GENERATE_DAY INT DEFAULT 1,
        SALARY_CALCULATION_BASE_DAYS INT DEFAULT 30,

        -- Mandatory Audit & Multi-company Columns
        COMPANY_ID BIGINT,
        DIVISION_ID BIGINT,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME
    );
END
GO

-- Seed default initial setting record if table is empty
IF NOT EXISTS (SELECT 1 FROM HR_SETTING_MASTER)
BEGIN
    INSERT INTO HR_SETTING_MASTER (
        LEAVE_ALLOW_BACKDATED, LEAVE_MAX_BACKDATED_DAYS, LEAVE_ADVANCE_NOTICE_DAYS, SANDWICH_LEAVE_ENABLED, LEAVE_ALLOW_NEGATIVE_BALANCE_GLOBAL,
        OD_ALLOW_PAST_DATES, OD_MAX_BACKDATED_DAYS, OD_MAX_REQUESTS_PER_MONTH, OD_MAX_DAYS_PER_REQUEST, OD_DOC_REQUIRED_THRESHOLD_DAYS,
        PERMISSION_ALLOW_PAST_DATES, PERMISSION_MAX_BACKDATED_DAYS, PERMISSION_ALLOW_SAME_DAY, PERMISSION_MAX_REQUESTS_PER_MONTH, PERMISSION_MAX_MINUTES_PER_REQUEST, PERMISSION_MAX_TOTAL_MINUTES_PER_MONTH,
        LOM_GRACE_MINUTES, LOM_PERMISSION_WAIVE_ENABLED, LOM_DEDUCTION_FACTOR, LATE_ARRIVAL_THRESHOLD_MINUTES,
        OT_CALCULATION_INTERVAL_MINUTES, OT_MIN_MINUTES_REQUIRED, OT_FACTORIAL, ESSL_SYNC_INTERVAL_MINUTES, ESSL_AUTO_MIGRATION_ACTIVE,
        DEFAULT_PF_ENABLED, DEFAULT_ESI_ENABLED, DEFAULT_PROFESSIONAL_TAX_ENABLED, DEFAULT_LTA_ELIGIBLE, PAYSLIP_AUTO_GENERATE_DAY, SALARY_CALCULATION_BASE_DAYS,
        CREATED_BY, CREATED_DATE
    ) VALUES (
        'YES', 3, 1, 'YES', 'NO',
        'NO', 2, 5, 7, 3,
        'NO', 1, 'YES', 2, 60, 120,
        15, 'YES', 1.00, 30,
        30, 60, 1.50, 15, 'YES',
        'YES', 'YES', 'YES', 'NO', 1, 30,
        'SYSTEM', GETDATE()
    );
END
GO
