-- =============================================================================
-- Fix: Migrate HR_EMPLOYEE_ATS status columns from VARCHAR to BIGINT FK
-- Tables: HR_EMPLOYEE_ATS
-- Columns: CALL_STATUS, INTERVIEW_STATUS, OFFER_STATUS, VERIFICATION_STATUS,
--          BACKGROUND_VERIFICATION_STATUS, PHOTO_VERIFIED_STATUS,
--          RESUME_VERIFIED_STATUS, PAYSLIP_VERIFIED_STATUS, AADHAR_VERIFIED_STATUS
-- =============================================================================
SET NOCOUNT ON;

-- Step 1: Ensure all required statuses exist in AD_STATUS_MASTER
DECLARE @statuses TABLE (nm NVARCHAR(100));
INSERT INTO @statuses VALUES
    ('PENDING'), ('APPROVED'), ('REJECTED'), ('VERIFIED'),
    ('CONFIRM'), ('SENT'), ('RESENT'), ('COMPLETED'), ('SELECTED'),
    ('SUBMITTED'), ('TO BE VERIFY'), ('N/A');

INSERT INTO AD_STATUS_MASTER (NAME)
SELECT nm FROM @statuses s
WHERE NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(s.nm)));

GO

-- =========================================================
-- Helper: migrate a single VARCHAR column to BIGINT FK
-- Pattern: add NEW_COL, map values, drop old, rename new
-- =========================================================

-- ---- CALL_STATUS ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='CALL_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='CALL_STATUS_ID')
        EXEC('ALTER TABLE HR_EMPLOYEE_ATS ADD CALL_STATUS_ID BIGINT NULL');
    EXEC('UPDATE HR_EMPLOYEE_ATS SET CALL_STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(CALL_STATUS))) WHERE CALL_STATUS IS NOT NULL');
    -- Drop indexes on CALL_STATUS
    DECLARE @sql NVARCHAR(512);
    DECLARE @nm NVARCHAR(256);
    DECLARE ix CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='CALL_STATUS' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix; FETCH NEXT FROM ix INTO @nm;
    WHILE @@FETCH_STATUS=0 BEGIN SET @sql='DROP INDEX '+QUOTENAME(@nm)+' ON HR_EMPLOYEE_ATS'; EXEC(@sql); FETCH NEXT FROM ix INTO @nm; END
    CLOSE ix; DEALLOCATE ix;
    -- Drop defaults
    DECLARE dc CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='CALL_STATUS';
    OPEN dc; FETCH NEXT FROM dc INTO @nm;
    WHILE @@FETCH_STATUS=0 BEGIN SET @sql='ALTER TABLE HR_EMPLOYEE_ATS DROP CONSTRAINT '+QUOTENAME(@nm); EXEC(@sql); FETCH NEXT FROM dc INTO @nm; END
    CLOSE dc; DEALLOCATE dc;
    EXEC('ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN CALL_STATUS');
    EXEC('EXEC sp_rename ''HR_EMPLOYEE_ATS.CALL_STATUS_ID'', ''CALL_STATUS'', ''COLUMN''');
    PRINT 'Migrated CALL_STATUS';
END

GO

-- ---- INTERVIEW_STATUS ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='INTERVIEW_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='INTERVIEW_STATUS_ID')
        EXEC('ALTER TABLE HR_EMPLOYEE_ATS ADD INTERVIEW_STATUS_ID BIGINT NULL');
    EXEC('UPDATE HR_EMPLOYEE_ATS SET INTERVIEW_STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(INTERVIEW_STATUS))) WHERE INTERVIEW_STATUS IS NOT NULL');
    DECLARE @sql2 NVARCHAR(512); DECLARE @nm2 NVARCHAR(256);
    DECLARE ix2 CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='INTERVIEW_STATUS' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix2; FETCH NEXT FROM ix2 INTO @nm2; WHILE @@FETCH_STATUS=0 BEGIN SET @sql2='DROP INDEX '+QUOTENAME(@nm2)+' ON HR_EMPLOYEE_ATS'; EXEC(@sql2); FETCH NEXT FROM ix2 INTO @nm2; END CLOSE ix2; DEALLOCATE ix2;
    DECLARE dc2 CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='INTERVIEW_STATUS';
    OPEN dc2; FETCH NEXT FROM dc2 INTO @nm2; WHILE @@FETCH_STATUS=0 BEGIN SET @sql2='ALTER TABLE HR_EMPLOYEE_ATS DROP CONSTRAINT '+QUOTENAME(@nm2); EXEC(@sql2); FETCH NEXT FROM dc2 INTO @nm2; END CLOSE dc2; DEALLOCATE dc2;
    EXEC('ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN INTERVIEW_STATUS');
    EXEC('EXEC sp_rename ''HR_EMPLOYEE_ATS.INTERVIEW_STATUS_ID'', ''INTERVIEW_STATUS'', ''COLUMN''');
    PRINT 'Migrated INTERVIEW_STATUS';
END

GO

-- ---- OFFER_STATUS ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='OFFER_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='OFFER_STATUS_ID')
        EXEC('ALTER TABLE HR_EMPLOYEE_ATS ADD OFFER_STATUS_ID BIGINT NULL');
    EXEC('UPDATE HR_EMPLOYEE_ATS SET OFFER_STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(OFFER_STATUS))) WHERE OFFER_STATUS IS NOT NULL');
    DECLARE @sql3 NVARCHAR(512); DECLARE @nm3 NVARCHAR(256);
    DECLARE ix3 CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='OFFER_STATUS' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix3; FETCH NEXT FROM ix3 INTO @nm3; WHILE @@FETCH_STATUS=0 BEGIN SET @sql3='DROP INDEX '+QUOTENAME(@nm3)+' ON HR_EMPLOYEE_ATS'; EXEC(@sql3); FETCH NEXT FROM ix3 INTO @nm3; END CLOSE ix3; DEALLOCATE ix3;
    DECLARE dc3 CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='OFFER_STATUS';
    OPEN dc3; FETCH NEXT FROM dc3 INTO @nm3; WHILE @@FETCH_STATUS=0 BEGIN SET @sql3='ALTER TABLE HR_EMPLOYEE_ATS DROP CONSTRAINT '+QUOTENAME(@nm3); EXEC(@sql3); FETCH NEXT FROM dc3 INTO @nm3; END CLOSE dc3; DEALLOCATE dc3;
    EXEC('ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN OFFER_STATUS');
    EXEC('EXEC sp_rename ''HR_EMPLOYEE_ATS.OFFER_STATUS_ID'', ''OFFER_STATUS'', ''COLUMN''');
    PRINT 'Migrated OFFER_STATUS';
END

GO

-- ---- VERIFICATION_STATUS ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='VERIFICATION_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='VERIFICATION_STATUS_ID')
        EXEC('ALTER TABLE HR_EMPLOYEE_ATS ADD VERIFICATION_STATUS_ID BIGINT NULL');
    EXEC('UPDATE HR_EMPLOYEE_ATS SET VERIFICATION_STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(VERIFICATION_STATUS))) WHERE VERIFICATION_STATUS IS NOT NULL');
    DECLARE @sql4 NVARCHAR(512); DECLARE @nm4 NVARCHAR(256);
    DECLARE ix4 CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='VERIFICATION_STATUS' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix4; FETCH NEXT FROM ix4 INTO @nm4; WHILE @@FETCH_STATUS=0 BEGIN SET @sql4='DROP INDEX '+QUOTENAME(@nm4)+' ON HR_EMPLOYEE_ATS'; EXEC(@sql4); FETCH NEXT FROM ix4 INTO @nm4; END CLOSE ix4; DEALLOCATE ix4;
    DECLARE dc4 CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='VERIFICATION_STATUS';
    OPEN dc4; FETCH NEXT FROM dc4 INTO @nm4; WHILE @@FETCH_STATUS=0 BEGIN SET @sql4='ALTER TABLE HR_EMPLOYEE_ATS DROP CONSTRAINT '+QUOTENAME(@nm4); EXEC(@sql4); FETCH NEXT FROM dc4 INTO @nm4; END CLOSE dc4; DEALLOCATE dc4;
    EXEC('ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN VERIFICATION_STATUS');
    EXEC('EXEC sp_rename ''HR_EMPLOYEE_ATS.VERIFICATION_STATUS_ID'', ''VERIFICATION_STATUS'', ''COLUMN''');
    PRINT 'Migrated VERIFICATION_STATUS';
END

GO

-- ---- BACKGROUND_VERIFICATION_STATUS ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='BACKGROUND_VERIFICATION_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='BGV_STATUS_ID')
        EXEC('ALTER TABLE HR_EMPLOYEE_ATS ADD BGV_STATUS_ID BIGINT NULL');
    EXEC('UPDATE HR_EMPLOYEE_ATS SET BGV_STATUS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(BACKGROUND_VERIFICATION_STATUS))) WHERE BACKGROUND_VERIFICATION_STATUS IS NOT NULL');
    DECLARE @sql5 NVARCHAR(512); DECLARE @nm5 NVARCHAR(256);
    DECLARE ix5 CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='BACKGROUND_VERIFICATION_STATUS' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix5; FETCH NEXT FROM ix5 INTO @nm5; WHILE @@FETCH_STATUS=0 BEGIN SET @sql5='DROP INDEX '+QUOTENAME(@nm5)+' ON HR_EMPLOYEE_ATS'; EXEC(@sql5); FETCH NEXT FROM ix5 INTO @nm5; END CLOSE ix5; DEALLOCATE ix5;
    DECLARE dc5 CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='BACKGROUND_VERIFICATION_STATUS';
    OPEN dc5; FETCH NEXT FROM dc5 INTO @nm5; WHILE @@FETCH_STATUS=0 BEGIN SET @sql5='ALTER TABLE HR_EMPLOYEE_ATS DROP CONSTRAINT '+QUOTENAME(@nm5); EXEC(@sql5); FETCH NEXT FROM dc5 INTO @nm5; END CLOSE dc5; DEALLOCATE dc5;
    EXEC('ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN BACKGROUND_VERIFICATION_STATUS');
    EXEC('EXEC sp_rename ''HR_EMPLOYEE_ATS.BGV_STATUS_ID'', ''BACKGROUND_VERIFICATION_STATUS'', ''COLUMN''');
    PRINT 'Migrated BACKGROUND_VERIFICATION_STATUS';
END

GO

-- ---- PHOTO_VERIFIED_STATUS ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='PHOTO_VERIFIED_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='PHOTO_VS_ID')
        EXEC('ALTER TABLE HR_EMPLOYEE_ATS ADD PHOTO_VS_ID BIGINT NULL');
    EXEC('UPDATE HR_EMPLOYEE_ATS SET PHOTO_VS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(PHOTO_VERIFIED_STATUS))) WHERE PHOTO_VERIFIED_STATUS IS NOT NULL');
    DECLARE @sql6 NVARCHAR(512); DECLARE @nm6 NVARCHAR(256);
    DECLARE ix6 CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='PHOTO_VERIFIED_STATUS' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix6; FETCH NEXT FROM ix6 INTO @nm6; WHILE @@FETCH_STATUS=0 BEGIN SET @sql6='DROP INDEX '+QUOTENAME(@nm6)+' ON HR_EMPLOYEE_ATS'; EXEC(@sql6); FETCH NEXT FROM ix6 INTO @nm6; END CLOSE ix6; DEALLOCATE ix6;
    DECLARE dc6 CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='PHOTO_VERIFIED_STATUS';
    OPEN dc6; FETCH NEXT FROM dc6 INTO @nm6; WHILE @@FETCH_STATUS=0 BEGIN SET @sql6='ALTER TABLE HR_EMPLOYEE_ATS DROP CONSTRAINT '+QUOTENAME(@nm6); EXEC(@sql6); FETCH NEXT FROM dc6 INTO @nm6; END CLOSE dc6; DEALLOCATE dc6;
    EXEC('ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN PHOTO_VERIFIED_STATUS');
    EXEC('EXEC sp_rename ''HR_EMPLOYEE_ATS.PHOTO_VS_ID'', ''PHOTO_VERIFIED_STATUS'', ''COLUMN''');
    PRINT 'Migrated PHOTO_VERIFIED_STATUS';
END

GO

-- ---- RESUME_VERIFIED_STATUS ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='RESUME_VERIFIED_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='RESUME_VS_ID')
        EXEC('ALTER TABLE HR_EMPLOYEE_ATS ADD RESUME_VS_ID BIGINT NULL');
    EXEC('UPDATE HR_EMPLOYEE_ATS SET RESUME_VS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(RESUME_VERIFIED_STATUS))) WHERE RESUME_VERIFIED_STATUS IS NOT NULL');
    DECLARE @sql7 NVARCHAR(512); DECLARE @nm7 NVARCHAR(256);
    DECLARE ix7 CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='RESUME_VERIFIED_STATUS' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix7; FETCH NEXT FROM ix7 INTO @nm7; WHILE @@FETCH_STATUS=0 BEGIN SET @sql7='DROP INDEX '+QUOTENAME(@nm7)+' ON HR_EMPLOYEE_ATS'; EXEC(@sql7); FETCH NEXT FROM ix7 INTO @nm7; END CLOSE ix7; DEALLOCATE ix7;
    DECLARE dc7 CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='RESUME_VERIFIED_STATUS';
    OPEN dc7; FETCH NEXT FROM dc7 INTO @nm7; WHILE @@FETCH_STATUS=0 BEGIN SET @sql7='ALTER TABLE HR_EMPLOYEE_ATS DROP CONSTRAINT '+QUOTENAME(@nm7); EXEC(@sql7); FETCH NEXT FROM dc7 INTO @nm7; END CLOSE dc7; DEALLOCATE dc7;
    EXEC('ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN RESUME_VERIFIED_STATUS');
    EXEC('EXEC sp_rename ''HR_EMPLOYEE_ATS.RESUME_VS_ID'', ''RESUME_VERIFIED_STATUS'', ''COLUMN''');
    PRINT 'Migrated RESUME_VERIFIED_STATUS';
END

GO

-- ---- PAYSLIP_VERIFIED_STATUS ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='PAYSLIP_VERIFIED_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='PAYSLIP_VS_ID')
        EXEC('ALTER TABLE HR_EMPLOYEE_ATS ADD PAYSLIP_VS_ID BIGINT NULL');
    EXEC('UPDATE HR_EMPLOYEE_ATS SET PAYSLIP_VS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(PAYSLIP_VERIFIED_STATUS))) WHERE PAYSLIP_VERIFIED_STATUS IS NOT NULL');
    DECLARE @sql8 NVARCHAR(512); DECLARE @nm8 NVARCHAR(256);
    DECLARE ix8 CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='PAYSLIP_VERIFIED_STATUS' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix8; FETCH NEXT FROM ix8 INTO @nm8; WHILE @@FETCH_STATUS=0 BEGIN SET @sql8='DROP INDEX '+QUOTENAME(@nm8)+' ON HR_EMPLOYEE_ATS'; EXEC(@sql8); FETCH NEXT FROM ix8 INTO @nm8; END CLOSE ix8; DEALLOCATE ix8;
    DECLARE dc8 CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='PAYSLIP_VERIFIED_STATUS';
    OPEN dc8; FETCH NEXT FROM dc8 INTO @nm8; WHILE @@FETCH_STATUS=0 BEGIN SET @sql8='ALTER TABLE HR_EMPLOYEE_ATS DROP CONSTRAINT '+QUOTENAME(@nm8); EXEC(@sql8); FETCH NEXT FROM dc8 INTO @nm8; END CLOSE dc8; DEALLOCATE dc8;
    EXEC('ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN PAYSLIP_VERIFIED_STATUS');
    EXEC('EXEC sp_rename ''HR_EMPLOYEE_ATS.PAYSLIP_VS_ID'', ''PAYSLIP_VERIFIED_STATUS'', ''COLUMN''');
    PRINT 'Migrated PAYSLIP_VERIFIED_STATUS';
END

GO

-- ---- AADHAR_VERIFIED_STATUS ----
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='AADHAR_VERIFIED_STATUS' AND DATA_TYPE IN ('nvarchar','varchar'))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HR_EMPLOYEE_ATS' AND COLUMN_NAME='AADHAR_VS_ID')
        EXEC('ALTER TABLE HR_EMPLOYEE_ATS ADD AADHAR_VS_ID BIGINT NULL');
    EXEC('UPDATE HR_EMPLOYEE_ATS SET AADHAR_VS_ID = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = UPPER(TRIM(AADHAR_VERIFIED_STATUS))) WHERE AADHAR_VERIFIED_STATUS IS NOT NULL');
    DECLARE @sql9 NVARCHAR(512); DECLARE @nm9 NVARCHAR(256);
    DECLARE ix9 CURSOR FOR SELECT i.name FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id WHERE i.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='AADHAR_VERIFIED_STATUS' AND i.is_primary_key=0 AND i.is_unique_constraint=0;
    OPEN ix9; FETCH NEXT FROM ix9 INTO @nm9; WHILE @@FETCH_STATUS=0 BEGIN SET @sql9='DROP INDEX '+QUOTENAME(@nm9)+' ON HR_EMPLOYEE_ATS'; EXEC(@sql9); FETCH NEXT FROM ix9 INTO @nm9; END CLOSE ix9; DEALLOCATE ix9;
    DECLARE dc9 CURSOR FOR SELECT dc.name FROM sys.default_constraints dc JOIN sys.columns c ON dc.parent_column_id=c.column_id AND dc.parent_object_id=c.object_id WHERE c.object_id=OBJECT_ID('HR_EMPLOYEE_ATS') AND c.name='AADHAR_VERIFIED_STATUS';
    OPEN dc9; FETCH NEXT FROM dc9 INTO @nm9; WHILE @@FETCH_STATUS=0 BEGIN SET @sql9='ALTER TABLE HR_EMPLOYEE_ATS DROP CONSTRAINT '+QUOTENAME(@nm9); EXEC(@sql9); FETCH NEXT FROM dc9 INTO @nm9; END CLOSE dc9; DEALLOCATE dc9;
    EXEC('ALTER TABLE HR_EMPLOYEE_ATS DROP COLUMN AADHAR_VERIFIED_STATUS');
    EXEC('EXEC sp_rename ''HR_EMPLOYEE_ATS.AADHAR_VS_ID'', ''AADHAR_VERIFIED_STATUS'', ''COLUMN''');
    PRINT 'Migrated AADHAR_VERIFIED_STATUS';
END

GO

PRINT 'ALL HR_EMPLOYEE_ATS status columns migrated successfully.';
GO
