-- Organization: Autonoma ERP
-- Owner: Nutech
-- Created At: 2026-08-31
-- Description: Add performance indexes to optimize dashboard and unallocated resource queries

SET NOCOUNT ON;

-- 1. Index on QMS_MEETING_SCHEDULE for IS_ACTIVE and STATUS to optimize AllocatedMeetings subqueries
IF OBJECT_ID('dbo.QMS_MEETING_SCHEDULE', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') AND name = 'IX_QMS_MEETING_SCHEDULE_ACTIVE_STATUS')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MEETING_SCHEDULE_ACTIVE_STATUS
    ON [dbo].[QMS_MEETING_SCHEDULE] ([IS_ACTIVE], [STATUS])
    INCLUDE ([CHAIRED_BY_ID], [HOST_BY_ID], [SECONDARY_HOST_ID], [TERTIARY_HOST_ID]);
END
GO

-- 2. Index on QMS_MEETING_USER_ATTENDANCE for IS_ACTIVE and SCHEDULE_ID
IF OBJECT_ID('dbo.QMS_MEETING_USER_ATTENDANCE', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_MEETING_USER_ATTENDANCE') AND name = 'IX_QMS_MEETING_USER_ATTENDANCE_ACTIVE_SCHED')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MEETING_USER_ATTENDANCE_ACTIVE_SCHED
    ON [dbo].[QMS_MEETING_USER_ATTENDANCE] ([IS_ACTIVE], [SCHEDULE_ID])
    INCLUDE ([EMPLOYEE_ID]);
END
GO

-- 3. Index on QMS_AUDIT_SCHEDULE for IS_ACTIVE to optimize AllocatedAudits subqueries
IF OBJECT_ID('dbo.QMS_AUDIT_SCHEDULE', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_AUDIT_SCHEDULE') AND name = 'IX_QMS_AUDIT_SCHEDULE_ACTIVE')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_AUDIT_SCHEDULE_ACTIVE
    ON [dbo].[QMS_AUDIT_SCHEDULE] ([IS_ACTIVE])
    INCLUDE ([AUDITOR_ID], [AUDITEE_ID], [NCR_APPROVED_BY_ID]);
END
GO

-- 4. Index on QMS_CHECKLIST_ASSIGNMENT for ASSIGNED_TO to optimize AllocatedChecklists subqueries
IF OBJECT_ID('dbo.QMS_CHECKLIST_ASSIGNMENT', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'IX_QMS_CHECKLIST_ASSIGNMENT_ASSIGNED_TO')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CHECKLIST_ASSIGNMENT_ASSIGNED_TO
    ON [dbo].[QMS_CHECKLIST_ASSIGNMENT] ([ASSIGNED_TO])
    INCLUDE ([CHECKLIST_ID]);
END
GO

-- 5. Index on QMS_CHECKLIST_MASTER for ASSIGN_TO to optimize checklist master queries
IF OBJECT_ID('dbo.QMS_CHECKLIST_MASTER', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_CHECKLIST_MASTER') AND name = 'IX_QMS_CHECKLIST_MASTER_ASSIGN_TO')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CHECKLIST_MASTER_ASSIGN_TO
    ON [dbo].[QMS_CHECKLIST_MASTER] ([ASSIGN_TO])
    INCLUDE ([STATUS]);
END
GO

-- 6. Index on QMS_CHECKLIST_CLOSED for ASSIGNED_TO to optimize checklist closed status/date filtering
IF OBJECT_ID('dbo.QMS_CHECKLIST_CLOSED', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED') AND name = 'IX_QMS_CHECKLIST_CLOSED_ASSIGNED_TO')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CHECKLIST_CLOSED_ASSIGNED_TO
    ON [dbo].[QMS_CHECKLIST_CLOSED] ([ASSIGNED_TO])
    INCLUDE ([CHECKLIST_ID], [STATUS_ID], [CHECKLIST_DATE]);
END
GO

-- 7. Index on AD_USER_CREDENTIAL for EMP_ID to optimize user-employee joins
IF OBJECT_ID('dbo.AD_USER_CREDENTIAL', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('AD_USER_CREDENTIAL') AND name = 'IX_AD_USER_CREDENTIAL_EMP_ID')
BEGIN
    CREATE NONCLUSTERED INDEX IX_AD_USER_CREDENTIAL_EMP_ID
    ON [dbo].[AD_USER_CREDENTIAL] ([EMP_ID])
    INCLUDE ([USER_ID]);
END
GO

-- 8. Index on QMS_NCR_REWORK_LOG for OBSERVATION_DETAIL_ID and REWORK_NO to optimize MAX(REWORK_NO) subqueries in Audit NCR queries
IF OBJECT_ID('dbo.QMS_NCR_REWORK_LOG', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('QMS_NCR_REWORK_LOG') AND name = 'IX_QMS_NCR_REWORK_LOG_DETAIL_REWORK')
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_NCR_REWORK_LOG_DETAIL_REWORK
    ON [dbo].[QMS_NCR_REWORK_LOG] ([OBSERVATION_DETAIL_ID], [REWORK_NO] DESC)
    INCLUDE ([CREATED_DATE], [UPDATED_DATE], [NCR_STATUS], [VERIFY_STATUS]);
END
GO
