-- Migration: Add Footer Configuration Columns to HR_EMAIL_CONTENT table
-- Date: 2026-07-29

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMAIL_CONTENT') 
    AND name = 'FOOTER_HEADER'
)
BEGIN
    ALTER TABLE HR_EMAIL_CONTENT ADD FOOTER_HEADER NVARCHAR(200) NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMAIL_CONTENT') 
    AND name = 'FOOTER_CONTENT'
)
BEGIN
    ALTER TABLE HR_EMAIL_CONTENT ADD FOOTER_CONTENT NVARCHAR(MAX) NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('HR_EMAIL_CONTENT') 
    AND name = 'USE_CURRENT_USER_CREDENTIALS'
)
BEGIN
    ALTER TABLE HR_EMAIL_CONTENT ADD USE_CURRENT_USER_CREDENTIALS BIT NULL DEFAULT 0;
END;
GO

-- Ensure defaults for existing rows
UPDATE HR_EMAIL_CONTENT
SET FOOTER_HEADER = 'Thanks & Regards'
WHERE FOOTER_HEADER IS NULL;

UPDATE HR_EMAIL_CONTENT
SET FOOTER_CONTENT = YOURS_WINDFULLY
WHERE FOOTER_CONTENT IS NULL;

UPDATE HR_EMAIL_CONTENT
SET USE_CURRENT_USER_CREDENTIALS = 0
WHERE USE_CURRENT_USER_CREDENTIALS IS NULL;
