-- SQL Migration: V1115.4__Unified_ATS_Consolidation_Final.sql
BEGIN TRANSACTION;
BEGIN TRY

    -- 1. Create a safety backup table before making any changes
    IF OBJECT_ID('dbo.HR_EMPLOYEE_ATS_BACKUP', 'U') IS NOT NULL
    BEGIN
        DROP TABLE dbo.HR_EMPLOYEE_ATS_BACKUP;
    END
    SELECT * INTO dbo.HR_EMPLOYEE_ATS_BACKUP FROM dbo.HR_EMPLOYEE_ATS;

    -- 2. Align Designation: Map ATS POSITION_LOOK_FOR text values to HR_EMPLOYEE_ORGANIZATION.DESIGNATION_ID
    -- Ensure every employee in HR_EMPLOYEE_ATS has an organization record
    INSERT INTO dbo.HR_EMPLOYEE_ORGANIZATION (EMPLOYEE_ID, CREATED_BY, CREATED_DATE)
    SELECT a.EMPLOYEE_ID, a.CREATED_BY, a.CREATED_DATE
    FROM dbo.HR_EMPLOYEE_ATS a
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ORGANIZATION o WHERE o.EMPLOYEE_ID = a.EMPLOYEE_ID
    ) AND EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE e WHERE e.ID = a.EMPLOYEE_ID
    );

    -- Map text designations dynamically to Designation Master
    UPDATE o
    SET o.DESIGNATION_ID = COALESCE(o.DESIGNATION_ID, d.ID)
    FROM dbo.HR_EMPLOYEE_ORGANIZATION o
    INNER JOIN dbo.HR_EMPLOYEE_ATS a ON o.EMPLOYEE_ID = a.EMPLOYEE_ID
    INNER JOIN dbo.HR_DESIGNATION d ON UPPER(TRIM(a.POSITION_LOOK_FOR)) = UPPER(TRIM(d.DESIGNATION_NAME))
    WHERE a.POSITION_LOOK_FOR IS NOT NULL;

    -- 3. Transition the 11 candidate records with EMP_CODE LIKE 'ATS-%' to the unified schema
    UPDATE dbo.HR_EMPLOYEE
    SET APPLICANT_CODE = EMP_CODE,
        FROMWHERE = 'ATS',
        EMP_CODE = NULL
    WHERE EMP_CODE LIKE 'ATS-%';

    -- 4. Recover known ATS Applicant Codes for active employees
    UPDATE dbo.HR_EMPLOYEE
    SET FROMWHERE = 'ATS',
        APPLICANT_CODE = 'ATS-2026-001'
    WHERE ID = 218 AND APPLICANT_CODE IS NULL;

    UPDATE dbo.HR_EMPLOYEE
    SET FROMWHERE = 'ATS',
        APPLICANT_CODE = 'ATS-2026-003'
    WHERE ID = 220 AND APPLICANT_CODE IS NULL;

    -- 5. Merge core applicant and status data (COALESCE to prevent overwriting newer parent data)
    UPDATE e
    SET e.APPLICANT_DATE = COALESCE(e.APPLICANT_DATE, a.APPLICANT_DATE),
        e.CALL_LETTER_DATE = COALESCE(e.CALL_LETTER_DATE, a.CALL_LETTER_DATE),
        e.CALL_LETTER_TIME = COALESCE(e.CALL_LETTER_TIME, a.CALL_LETTER_TIME),
        e.RESUME_PATH = COALESCE(e.RESUME_PATH, a.RESUME_PATH),
        e.AADHAR_PATH = COALESCE(e.AADHAR_PATH, a.AADHAR_PATH),
        e.PAYSLIP_PATH = COALESCE(e.PAYSLIP_PATH, a.PAYSLIP_PATH),
        e.PHOTO_REJECT_REASON = COALESCE(e.PHOTO_REJECT_REASON, a.PHOTO_REJECT_REASON),
        e.RESUME_REJECT_REASON = COALESCE(e.RESUME_REJECT_REASON, a.RESUME_REJECT_REASON),
        e.PAYSLIP_REJECT_REASON = COALESCE(e.PAYSLIP_REJECT_REASON, a.PAYSLIP_REJECT_REASON),
        e.AADHAR_REJECT_REASON = COALESCE(e.AADHAR_REJECT_REASON, a.AADHAR_REJECT_REASON),
        e.NEXT_SALARY_HIKE_MONTH = COALESCE(e.NEXT_SALARY_HIKE_MONTH, a.NEXT_SALARY_HIKE_MONTH),
        e.MINIMUM_AMOUNT = COALESCE(e.MINIMUM_AMOUNT, a.MINIMUM_AMOUNT),
        e.MAXIMUM_AMOUNT = COALESCE(e.MAXIMUM_AMOUNT, a.MAXIMUM_AMOUNT),
        e.IS_REHIRED = COALESCE(e.IS_REHIRED, a.IS_REHIRED),
        e.PREVIOUS_EMP_CODE = COALESCE(e.PREVIOUS_EMP_CODE, a.PREVIOUS_EMP_CODE),
        e.ARCHIVED_DATE = COALESCE(e.ARCHIVED_DATE, a.ARCHIVED_DATE),
        e.CALL_STATUS = COALESCE(e.CALL_STATUS, a.CALL_STATUS),
        e.INTERVIEW_STATUS = COALESCE(e.INTERVIEW_STATUS, a.INTERVIEW_STATUS),
        e.OFFER_STATUS = COALESCE(e.OFFER_STATUS, a.OFFER_STATUS),
        e.VERIFICATION_STATUS = COALESCE(e.VERIFICATION_STATUS, a.VERIFICATION_STATUS),
        e.BACKGROUND_VERIFICATION_STATUS = COALESCE(e.BACKGROUND_VERIFICATION_STATUS, a.BACKGROUND_VERIFICATION_STATUS),
        e.PHOTO_VERIFIED_STATUS = COALESCE(e.PHOTO_VERIFIED_STATUS, a.PHOTO_VERIFIED_STATUS),
        e.RESUME_VERIFIED_STATUS = COALESCE(e.RESUME_VERIFIED_STATUS, a.RESUME_VERIFIED_STATUS),
        e.PAYSLIP_VERIFIED_STATUS = COALESCE(e.PAYSLIP_VERIFIED_STATUS, a.PAYSLIP_VERIFIED_STATUS),
        e.AADHAR_VERIFIED_STATUS = COALESCE(e.AADHAR_VERIFIED_STATUS, a.AADHAR_VERIFIED_STATUS),
        e.ATS_OVERALL_STATUS = COALESCE(e.ATS_OVERALL_STATUS, a.ATS_OVERALL_STATUS)
    FROM dbo.HR_EMPLOYEE e
    INNER JOIN dbo.HR_EMPLOYEE_ATS a ON e.ID = a.EMPLOYEE_ID;

    -- 6. Merge AGE to HR_EMPLOYEE_PERSONAL
    INSERT INTO dbo.HR_EMPLOYEE_PERSONAL (EMPLOYEE_ID, CREATED_BY, CREATED_DATE)
    SELECT a.EMPLOYEE_ID, a.CREATED_BY, a.CREATED_DATE
    FROM dbo.HR_EMPLOYEE_ATS a
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_PERSONAL p WHERE p.EMPLOYEE_ID = a.EMPLOYEE_ID
    ) AND EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE e WHERE e.ID = a.EMPLOYEE_ID
    ) AND a.AGE IS NOT NULL;

    UPDATE p
    SET p.AGE = COALESCE(p.AGE, a.AGE)
    FROM dbo.HR_EMPLOYEE_PERSONAL p
    INNER JOIN dbo.HR_EMPLOYEE_ATS a ON p.EMPLOYEE_ID = a.EMPLOYEE_ID
    WHERE a.AGE IS NOT NULL;

    -- 7. Merge Self-Assessment status to HR_EMPLOYEE_SELF_ASSESSMENT
    UPDATE s
    SET s.SELF_ASSESSMENT_STATUS = COALESCE(
            CASE WHEN s.SELF_ASSESSMENT_STATUS = 'DRAFT' THEN a.SELF_ASSESSMENT_STATUS ELSE s.SELF_ASSESSMENT_STATUS END,
            s.SELF_ASSESSMENT_STATUS,
            'DRAFT'
        ),
        s.CURRENT_STEP = COALESCE(s.CURRENT_STEP, a.CURRENT_STEP),
        s.LAST_DRAFT_SAVED_DATE = COALESCE(s.LAST_DRAFT_SAVED_DATE, a.LAST_DRAFT_SAVED_DATE)
    FROM dbo.HR_EMPLOYEE_SELF_ASSESSMENT s
    INNER JOIN dbo.HR_EMPLOYEE_ATS a ON s.EMPLOYEE_ID = a.EMPLOYEE_ID;

    -- Insert missing self-assessment records ONLY when active assessment data exists
    INSERT INTO dbo.HR_EMPLOYEE_SELF_ASSESSMENT (EMPLOYEE_ID, SELF_ASSESSMENT_STATUS, CURRENT_STEP, LAST_DRAFT_SAVED_DATE, CREATED_BY, CREATED_DATE)
    SELECT a.EMPLOYEE_ID, COALESCE(a.SELF_ASSESSMENT_STATUS, 'DRAFT'), a.CURRENT_STEP, a.LAST_DRAFT_SAVED_DATE, a.CREATED_BY, a.CREATED_DATE
    FROM dbo.HR_EMPLOYEE_ATS a
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_SELF_ASSESSMENT s WHERE s.EMPLOYEE_ID = a.EMPLOYEE_ID
    ) AND EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE e WHERE e.ID = a.EMPLOYEE_ID
    ) AND (
        a.SELF_ASSESSMENT_STATUS <> 'DRAFT'
        OR a.CURRENT_STEP IS NOT NULL
        OR a.LAST_DRAFT_SAVED_DATE IS NOT NULL
    );

    -- 8. COMPLETE MIGRATION VALIDATIONS
    -- Validate: POSITION_LOOK_FOR -> DESIGNATION_ID mapping
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE_ORGANIZATION o ON o.EMPLOYEE_ID = a.EMPLOYEE_ID 
        WHERE a.POSITION_LOOK_FOR IS NOT NULL 
          AND o.DESIGNATION_ID IS NULL
    )
    BEGIN
        THROW 50001, 'Validation Failed: POSITION_LOOK_FOR was not successfully mapped to DESIGNATION_ID in HR_EMPLOYEE_ORGANIZATION.', 1;
    END

    -- Validate: APPLICANT_DATE
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.APPLICANT_DATE IS NOT NULL AND e.APPLICANT_DATE IS NULL
    )
    BEGIN
        THROW 50002, 'Validation Failed: APPLICANT_DATE was not successfully migrated.', 1;
    END

    -- Validate: CALL_LETTER_DATE
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.CALL_LETTER_DATE IS NOT NULL AND e.CALL_LETTER_DATE IS NULL
    )
    BEGIN
        THROW 50003, 'Validation Failed: CALL_LETTER_DATE was not successfully migrated.', 1;
    END

    -- Validate: CALL_LETTER_TIME
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.CALL_LETTER_TIME IS NOT NULL AND e.CALL_LETTER_TIME IS NULL
    )
    BEGIN
        THROW 50004, 'Validation Failed: CALL_LETTER_TIME was not successfully migrated.', 1;
    END

    -- Validate: RESUME_PATH
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.RESUME_PATH IS NOT NULL AND e.RESUME_PATH IS NULL
    )
    BEGIN
        THROW 50005, 'Validation Failed: RESUME_PATH was not successfully migrated.', 1;
    END

    -- Validate: AADHAR_PATH
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.AADHAR_PATH IS NOT NULL AND e.AADHAR_PATH IS NULL
    )
    BEGIN
        THROW 50006, 'Validation Failed: AADHAR_PATH was not successfully migrated.', 1;
    END

    -- Validate: PAYSLIP_PATH
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.PAYSLIP_PATH IS NOT NULL AND e.PAYSLIP_PATH IS NULL
    )
    BEGIN
        THROW 50007, 'Validation Failed: PAYSLIP_PATH was not successfully migrated.', 1;
    END

    -- Validate: PHOTO_REJECT_REASON
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.PHOTO_REJECT_REASON IS NOT NULL AND e.PHOTO_REJECT_REASON IS NULL
    )
    BEGIN
        THROW 50008, 'Validation Failed: PHOTO_REJECT_REASON was not successfully migrated.', 1;
    END

    -- Validate: RESUME_REJECT_REASON
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.RESUME_REJECT_REASON IS NOT NULL AND e.RESUME_REJECT_REASON IS NULL
    )
    BEGIN
        THROW 50009, 'Validation Failed: RESUME_REJECT_REASON was not successfully migrated.', 1;
    END

    -- Validate: PAYSLIP_REJECT_REASON
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.PAYSLIP_REJECT_REASON IS NOT NULL AND e.PAYSLIP_REJECT_REASON IS NULL
    )
    BEGIN
        THROW 50010, 'Validation Failed: PAYSLIP_REJECT_REASON was not successfully migrated.', 1;
    END

    -- Validate: AADHAR_REJECT_REASON
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.AADHAR_REJECT_REASON IS NOT NULL AND e.AADHAR_REJECT_REASON IS NULL
    )
    BEGIN
        THROW 50011, 'Validation Failed: AADHAR_REJECT_REASON was not successfully migrated.', 1;
    END

    -- Validate: NEXT_SALARY_HIKE_MONTH
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.NEXT_SALARY_HIKE_MONTH IS NOT NULL AND e.NEXT_SALARY_HIKE_MONTH IS NULL
    )
    BEGIN
        THROW 50012, 'Validation Failed: NEXT_SALARY_HIKE_MONTH was not successfully migrated.', 1;
    END

    -- Validate: MINIMUM_AMOUNT
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.MINIMUM_AMOUNT IS NOT NULL AND e.MINIMUM_AMOUNT IS NULL
    )
    BEGIN
        THROW 50013, 'Validation Failed: MINIMUM_AMOUNT was not successfully migrated.', 1;
    END

    -- Validate: MAXIMUM_AMOUNT
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.MAXIMUM_AMOUNT IS NOT NULL AND e.MAXIMUM_AMOUNT IS NULL
    )
    BEGIN
        THROW 50014, 'Validation Failed: MAXIMUM_AMOUNT was not successfully migrated.', 1;
    END

    -- Validate: IS_REHIRED
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.IS_REHIRED IS NOT NULL AND e.IS_REHIRED IS NULL
    )
    BEGIN
        THROW 50015, 'Validation Failed: IS_REHIRED was not successfully migrated.', 1;
    END

    -- Validate: PREVIOUS_EMP_CODE
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.PREVIOUS_EMP_CODE IS NOT NULL AND e.PREVIOUS_EMP_CODE IS NULL
    )
    BEGIN
        THROW 50016, 'Validation Failed: PREVIOUS_EMP_CODE was not successfully migrated.', 1;
    END

    -- Validate: ARCHIVED_DATE
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.ARCHIVED_DATE IS NOT NULL AND e.ARCHIVED_DATE IS NULL
    )
    BEGIN
        THROW 50017, 'Validation Failed: ARCHIVED_DATE was not successfully migrated.', 1;
    END

    -- Validate: CALL_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.CALL_STATUS IS NOT NULL AND e.CALL_STATUS IS NULL
    )
    BEGIN
        THROW 50018, 'Validation Failed: CALL_STATUS was not successfully migrated.', 1;
    END

    -- Validate: INTERVIEW_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.INTERVIEW_STATUS IS NOT NULL AND e.INTERVIEW_STATUS IS NULL
    )
    BEGIN
        THROW 50019, 'Validation Failed: INTERVIEW_STATUS was not successfully migrated.', 1;
    END

    -- Validate: OFFER_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.OFFER_STATUS IS NOT NULL AND e.OFFER_STATUS IS NULL
    )
    BEGIN
        THROW 50020, 'Validation Failed: OFFER_STATUS was not successfully migrated.', 1;
    END

    -- Validate: VERIFICATION_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.VERIFICATION_STATUS IS NOT NULL AND e.VERIFICATION_STATUS IS NULL
    )
    BEGIN
        THROW 50021, 'Validation Failed: VERIFICATION_STATUS was not successfully migrated.', 1;
    END

    -- Validate: BACKGROUND_VERIFICATION_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.BACKGROUND_VERIFICATION_STATUS IS NOT NULL AND e.BACKGROUND_VERIFICATION_STATUS IS NULL
    )
    BEGIN
        THROW 50022, 'Validation Failed: BACKGROUND_VERIFICATION_STATUS was not successfully migrated.', 1;
    END

    -- Validate: PHOTO_VERIFIED_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.PHOTO_VERIFIED_STATUS IS NOT NULL AND e.PHOTO_VERIFIED_STATUS IS NULL
    )
    BEGIN
        THROW 50023, 'Validation Failed: PHOTO_VERIFIED_STATUS was not successfully migrated.', 1;
    END

    -- Validate: RESUME_VERIFIED_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.RESUME_VERIFIED_STATUS IS NOT NULL AND e.RESUME_VERIFIED_STATUS IS NULL
    )
    BEGIN
        THROW 50024, 'Validation Failed: RESUME_VERIFIED_STATUS was not successfully migrated.', 1;
    END

    -- Validate: PAYSLIP_VERIFIED_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.PAYSLIP_VERIFIED_STATUS IS NOT NULL AND e.PAYSLIP_VERIFIED_STATUS IS NULL
    )
    BEGIN
        THROW 50025, 'Validation Failed: PAYSLIP_VERIFIED_STATUS was not successfully migrated.', 1;
    END

    -- Validate: AADHAR_VERIFIED_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.AADHAR_VERIFIED_STATUS IS NOT NULL AND e.AADHAR_VERIFIED_STATUS IS NULL
    )
    BEGIN
        THROW 50026, 'Validation Failed: AADHAR_VERIFIED_STATUS was not successfully migrated.', 1;
    END

    -- Validate: ATS_OVERALL_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE e ON e.ID = a.EMPLOYEE_ID 
        WHERE a.ATS_OVERALL_STATUS IS NOT NULL AND e.ATS_OVERALL_STATUS IS NULL
    )
    BEGIN
        THROW 50027, 'Validation Failed: ATS_OVERALL_STATUS was not successfully migrated.', 1;
    END

    -- Validate: AGE
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE_PERSONAL p ON p.EMPLOYEE_ID = a.EMPLOYEE_ID 
        WHERE a.AGE IS NOT NULL AND p.AGE IS NULL
    )
    BEGIN
        THROW 50028, 'Validation Failed: AGE was not successfully migrated to HR_EMPLOYEE_PERSONAL.', 1;
    END

    -- Validate: SELF_ASSESSMENT_STATUS
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE_SELF_ASSESSMENT s ON s.EMPLOYEE_ID = a.EMPLOYEE_ID 
        WHERE a.SELF_ASSESSMENT_STATUS IS NOT NULL AND s.SELF_ASSESSMENT_STATUS IS NULL
    )
    BEGIN
        THROW 50029, 'Validation Failed: SELF_ASSESSMENT_STATUS was not successfully migrated to HR_EMPLOYEE_SELF_ASSESSMENT.', 1;
    END

    -- Validate: CURRENT_STEP
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE_SELF_ASSESSMENT s ON s.EMPLOYEE_ID = a.EMPLOYEE_ID 
        WHERE a.CURRENT_STEP IS NOT NULL AND s.CURRENT_STEP IS NULL
    )
    BEGIN
        THROW 50030, 'Validation Failed: CURRENT_STEP was not successfully migrated to HR_EMPLOYEE_SELF_ASSESSMENT.', 1;
    END

    -- Validate: LAST_DRAFT_SAVED_DATE
    IF EXISTS (
        SELECT 1 FROM dbo.HR_EMPLOYEE_ATS a 
        INNER JOIN dbo.HR_EMPLOYEE_SELF_ASSESSMENT s ON s.EMPLOYEE_ID = a.EMPLOYEE_ID 
        WHERE a.LAST_DRAFT_SAVED_DATE IS NOT NULL AND s.LAST_DRAFT_SAVED_DATE IS NULL
    )
    BEGIN
        THROW 50031, 'Validation Failed: LAST_DRAFT_SAVED_DATE was not successfully migrated to HR_EMPLOYEE_SELF_ASSESSMENT.', 1;
    END

    -- 9. Drop the obsolete table
    IF OBJECT_ID('dbo.HR_EMPLOYEE_ATS', 'U') IS NOT NULL
    BEGIN
        DROP TABLE dbo.HR_EMPLOYEE_ATS;
    END

    -- 10. Drop the redundant POSITION_LOOK_FOR column from HR_EMPLOYEE
    IF EXISTS (
        SELECT 1 FROM sys.columns 
        WHERE object_id = OBJECT_ID('dbo.HR_EMPLOYEE') 
          AND name = 'POSITION_LOOK_FOR'
    )
    BEGIN
        ALTER TABLE dbo.HR_EMPLOYEE DROP COLUMN POSITION_LOOK_FOR;
    END

    COMMIT TRANSACTION;
    PRINT 'Migration completed successfully, HR_EMPLOYEE_ATS and POSITION_LOOK_FOR dropped.';

END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
    BEGIN
        ROLLBACK TRANSACTION;
    END
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();
    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
END CATCH;
GO
