

-- =============================================
-- V1091.0 - Enterprise Purchase Order Module
-- Date: 2026-07-31
-- =============================================

-- 1. PP_PURCHASE_ORDER_HEAD
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_PURCHASE_ORDER_HEAD')
BEGIN
    CREATE TABLE PP_PURCHASE_ORDER_HEAD (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        PO_NO                   NVARCHAR(50)    NOT NULL,
        PO_DATE                 DATE            NOT NULL,
        REVISION_NO             INT             NOT NULL DEFAULT 0,
        ORIGINAL_PO_ID          BIGINT          NULL,         -- FK to self for revisions

        -- Supplier
        SUPPLIER_ID             BIGINT          NOT NULL,     -- FA_ACCOUNT_LEDGER

        -- Source
        SOURCE_TYPE             NVARCHAR(50)    NOT NULL,     -- DIRECT/PURCHASE_REQUEST/RFQ/SUPPLIER_QUOTATION/NEGOTIATION/QUOTATION_COMPARISON/RATE_CONTRACT

        -- People & Org
        BUYER_ID                BIGINT          NULL,         -- HR_EMPLOYEE_MASTER
        DEPARTMENT_ID           BIGINT          NULL,         -- HR_DEPARTMENT
        DIVISION                BIGINT          NOT NULL,

        -- Delivery
        BILLING_ADDRESS         NVARCHAR(500)   NULL,
        DELIVERY_ADDRESS        NVARCHAR(500)   NULL,

        -- Commercial Terms
        CURRENCY                NVARCHAR(10)    NOT NULL DEFAULT 'INR',
        EXCHANGE_RATE           NUMERIC(18,6)   NOT NULL DEFAULT 1.000000,
        PAYMENT_TERMS           NVARCHAR(500)   NULL,
        DELIVERY_TERMS          NVARCHAR(500)   NULL,
        SHIPPING_TERMS          NVARCHAR(200)   NULL,
        WARRANTY_TERMS          NVARCHAR(500)   NULL,

        -- Charges & Totals
        SUBTOTAL                NUMERIC(18,4)   NOT NULL DEFAULT 0,
        FREIGHT_AMOUNT          NUMERIC(18,4)   NOT NULL DEFAULT 0,
        PACKING_AMOUNT          NUMERIC(18,4)   NOT NULL DEFAULT 0,
        INSURANCE_AMOUNT        NUMERIC(18,4)   NOT NULL DEFAULT 0,
        OTHER_CHARGES           NUMERIC(18,4)   NOT NULL DEFAULT 0,
        DISCOUNT_AMOUNT         NUMERIC(18,4)   NOT NULL DEFAULT 0,
        TAX_AMOUNT              NUMERIC(18,4)   NOT NULL DEFAULT 0,
        ROUND_OFF               NUMERIC(18,4)   NOT NULL DEFAULT 0,
        GRAND_TOTAL             NUMERIC(18,4)   NOT NULL DEFAULT 0,

        -- Status
        STATUS_ID               BIGINT          NOT NULL,

        -- Remarks
        REMARKS                 NVARCHAR(1000)  NULL,
        INTERNAL_NOTES          NVARCHAR(1000)  NULL,
        SUPPLIER_REFERENCE_NO   NVARCHAR(100)   NULL,
        SUPPLIER_REFERENCE_DATE DATE            NULL,

        -- Approval
        APPROVAL_VERSION        INT             NULL,
        APPROVAL_SEQUENCE       INT             NULL,

        -- Audit
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_PO_HEAD_SUPPLIER   FOREIGN KEY (SUPPLIER_ID)   REFERENCES FA_ACCOUNT_LEDGER(ID),
        CONSTRAINT FK_PP_PO_HEAD_STATUS     FOREIGN KEY (STATUS_ID)     REFERENCES AD_STATUS_MASTER(ID),
        CONSTRAINT FK_PP_PO_HEAD_DIVISION   FOREIGN KEY (DIVISION)      REFERENCES AD_DIVISION(ID),
        CONSTRAINT FK_PP_PO_HEAD_ORIG       FOREIGN KEY (ORIGINAL_PO_ID)REFERENCES PP_PURCHASE_ORDER_HEAD(ID),
        CONSTRAINT UQ_PP_PO_HEAD_NO_REV     UNIQUE (PO_NO, REVISION_NO)
    );
    PRINT 'PP_PURCHASE_ORDER_HEAD created.';
END

-- 2. PP_PURCHASE_ORDER_TRANS (Line Items)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_PURCHASE_ORDER_TRANS')
BEGIN
    CREATE TABLE PP_PURCHASE_ORDER_TRANS (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        PO_HEAD_ID              BIGINT          NOT NULL,
        LINE_NO                 INT             NOT NULL DEFAULT 0,

        -- Item
        ITEM_ID                 BIGINT          NOT NULL,     -- PP_PRODUCT_MASTER
        DESCRIPTION             NVARCHAR(500)   NULL,
        HSN_CODE                NVARCHAR(20)    NULL,
        UOM                     NVARCHAR(20)    NOT NULL,
        BRAND                   NVARCHAR(100)   NULL,
        ORIGIN                  NVARCHAR(100)   NULL,

        -- Pricing
        QTY                     NUMERIC(18,4)   NOT NULL,
        UNIT_PRICE              NUMERIC(18,4)   NOT NULL,
        DISCOUNT_PERCENT        NUMERIC(5,2)    NOT NULL DEFAULT 0,
        TAX_PERCENT             NUMERIC(5,2)    NOT NULL DEFAULT 0,
        NET_AMOUNT              NUMERIC(18,4)   NOT NULL DEFAULT 0,

        -- Tracking Quantities (future-ready for GRN / Invoice)
        PENDING_QTY             NUMERIC(18,4)   NOT NULL DEFAULT 0,
        RECEIVED_QTY            NUMERIC(18,4)   NOT NULL DEFAULT 0,
        REJECTED_QTY            NUMERIC(18,4)   NOT NULL DEFAULT 0,
        RETURNED_QTY            NUMERIC(18,4)   NOT NULL DEFAULT 0,
        INVOICED_QTY            NUMERIC(18,4)   NOT NULL DEFAULT 0,

        -- Delivery
        EXPECTED_DELIVERY_DATE  DATE            NULL,
        WAREHOUSE               NVARCHAR(100)   NULL,
        PROJECT                 NVARCHAR(100)   NULL,
        COST_CENTER             NVARCHAR(100)   NULL,

        -- Remarks
        REMARKS                 NVARCHAR(500)   NULL,

        -- Audit
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_PO_TRANS_HEAD  FOREIGN KEY (PO_HEAD_ID) REFERENCES PP_PURCHASE_ORDER_HEAD(ID) ON DELETE CASCADE,
        CONSTRAINT FK_PP_PO_TRANS_ITEM  FOREIGN KEY (ITEM_ID)    REFERENCES NPD_PRODUCT_MASTER(ID)
    );
    PRINT 'PP_PURCHASE_ORDER_TRANS created.';
END

-- 3. PP_PURCHASE_ORDER_SOURCE (Multi-source traceability — replaces single SOURCE_DOC_ID)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_PURCHASE_ORDER_SOURCE')
BEGIN
    CREATE TABLE PP_PURCHASE_ORDER_SOURCE (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        PO_HEAD_ID              BIGINT          NOT NULL,
        PO_TRANS_ID             BIGINT          NULL,         -- NULL = header-level link, NOT NULL = line-level link

        -- Source Traceability
        SOURCE_TYPE             NVARCHAR(50)    NOT NULL,     -- matches PoSourceType enum
        SOURCE_HEAD_ID          BIGINT          NOT NULL,
        SOURCE_TRANS_ID         BIGINT          NULL,
        SOURCE_DOCUMENT_NO      NVARCHAR(100)   NULL,
        SOURCE_LINE_NO          INT             NULL,

        -- Conversion Tracking
        SOURCE_QTY              NUMERIC(18,4)   NULL,
        ORDERED_QTY             NUMERIC(18,4)   NULL,
        BALANCE_QTY             NUMERIC(18,4)   NULL,
        CONVERTED_QTY           NUMERIC(18,4)   NOT NULL DEFAULT 0,
        IS_FULLY_CONVERTED      BIT             NOT NULL DEFAULT 0,

        -- Audit
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,

        CONSTRAINT FK_PP_PO_SRC_HEAD    FOREIGN KEY (PO_HEAD_ID)  REFERENCES PP_PURCHASE_ORDER_HEAD(ID) ON DELETE CASCADE,
        CONSTRAINT FK_PP_PO_SRC_TRANS   FOREIGN KEY (PO_TRANS_ID) REFERENCES PP_PURCHASE_ORDER_TRANS(ID)
    );
    PRINT 'PP_PURCHASE_ORDER_SOURCE created.';
END

-- 4. PP_PURCHASE_ORDER_TERMS
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_PURCHASE_ORDER_TERMS')
BEGIN
    CREATE TABLE PP_PURCHASE_ORDER_TERMS (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        PO_HEAD_ID              BIGINT          NOT NULL,
        TERM_TYPE               NVARCHAR(50)    NOT NULL,     -- PAYMENT / DELIVERY / WARRANTY / SPECIAL
        TERM_CODE               NVARCHAR(50)    NULL,
        TERM_DESCRIPTION        NVARCHAR(MAX)   NULL,
        SEQUENCE                INT             NOT NULL DEFAULT 0,
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,
        CONSTRAINT FK_PP_PO_TERMS_HEAD  FOREIGN KEY (PO_HEAD_ID) REFERENCES PP_PURCHASE_ORDER_HEAD(ID) ON DELETE CASCADE
    );
    PRINT 'PP_PURCHASE_ORDER_TERMS created.';
END

-- 5. PP_PURCHASE_ORDER_ATTACHMENT
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_PURCHASE_ATTACHMENT')
BEGIN
    CREATE TABLE PP_PURCHASE_ATTACHMENT (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        PO_HEAD_ID              BIGINT          NOT NULL,
        FILE_NAME               NVARCHAR(255)   NOT NULL,
        FILE_PATH               NVARCHAR(1000)  NOT NULL,
        FILE_SIZE               BIGINT          NULL,
        MIME_TYPE               NVARCHAR(100)   NULL,
        ACTIVE_STATUS           INT             NOT NULL DEFAULT 1,
        CREATED_BY              NVARCHAR(50)    NOT NULL,
        CREATED_DATE            DATETIME        NULL,
        UPDATED_BY              NVARCHAR(50)    NULL,
        UPDATED_DATE            DATETIME        NULL,
        CONSTRAINT FK_PP_PO_ATTACH_HEAD FOREIGN KEY (PO_HEAD_ID) REFERENCES PP_PURCHASE_ORDER_HEAD(ID) ON DELETE CASCADE
    );
    PRINT 'PP_PURCHASE_ATTACHMENT created.';
END

-- 6. PP_PURCHASE_ORDER_LOG (Immutable audit event log)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_PURCHASE_ORDER_LOG')
BEGIN
    CREATE TABLE PP_PURCHASE_ORDER_LOG (
        ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
        PO_HEAD_ID              BIGINT          NOT NULL,
        EVENT_TYPE              NVARCHAR(50)    NOT NULL,     -- CREATED/SUBMITTED/APPROVED/REJECTED/RELEASED/CANCELLED/REVISED/PRICE_CHANGED/QTY_CHANGED/EMAILED/PRINTED
        EVENT_DESCRIPTION       NVARCHAR(MAX)   NULL,
        OLD_VALUE               NVARCHAR(MAX)   NULL,
        NEW_VALUE               NVARCHAR(MAX)   NULL,
        PERFORMED_BY            NVARCHAR(100)   NULL,
        EVENT_DATE              DATETIME        NOT NULL DEFAULT GETDATE(),
        IP_ADDRESS              NVARCHAR(50)    NULL,
        REMARKS                 NVARCHAR(500)   NULL,
        CONSTRAINT FK_PP_PO_LOG_HEAD    FOREIGN KEY (PO_HEAD_ID) REFERENCES PP_PURCHASE_ORDER_HEAD(ID)
    );
    PRINT 'PP_PURCHASE_ORDER_LOG created.';
END

-- 7. Indexes for Performance
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PP_PO_HEAD_DIVISION' AND object_id = OBJECT_ID('PP_PURCHASE_ORDER_HEAD'))
    CREATE INDEX IX_PP_PO_HEAD_DIVISION      ON PP_PURCHASE_ORDER_HEAD (DIVISION, ACTIVE_STATUS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PP_PO_HEAD_STATUS' AND object_id = OBJECT_ID('PP_PURCHASE_ORDER_HEAD'))
    CREATE INDEX IX_PP_PO_HEAD_STATUS        ON PP_PURCHASE_ORDER_HEAD (STATUS_ID);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PP_PO_HEAD_SUPPLIER' AND object_id = OBJECT_ID('PP_PURCHASE_ORDER_HEAD'))
    CREATE INDEX IX_PP_PO_HEAD_SUPPLIER      ON PP_PURCHASE_ORDER_HEAD (SUPPLIER_ID);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PP_PO_TRANS_HEAD' AND object_id = OBJECT_ID('PP_PURCHASE_ORDER_TRANS'))
    CREATE INDEX IX_PP_PO_TRANS_HEAD         ON PP_PURCHASE_ORDER_TRANS (PO_HEAD_ID, ACTIVE_STATUS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PP_PO_SRC_HEAD' AND object_id = OBJECT_ID('PP_PURCHASE_ORDER_SOURCE'))
    CREATE INDEX IX_PP_PO_SRC_HEAD           ON PP_PURCHASE_ORDER_SOURCE (PO_HEAD_ID);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PP_PO_SRC_TYPE' AND object_id = OBJECT_ID('PP_PURCHASE_ORDER_SOURCE'))
    CREATE INDEX IX_PP_PO_SRC_TYPE           ON PP_PURCHASE_ORDER_SOURCE (SOURCE_TYPE, SOURCE_HEAD_ID);

-- 8. Seed PO Statuses
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'SUBMITTED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('SUBMITTED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'APPROVED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('APPROVED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'RELEASED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('RELEASED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'SENT TO SUPPLIER')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('SENT TO SUPPLIER');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'SUPPLIER ACKNOWLEDGED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('SUPPLIER ACKNOWLEDGED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PARTIALLY RECEIVED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('PARTIALLY RECEIVED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'FULLY RECEIVED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('FULLY RECEIVED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'CANCELLED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('CANCELLED');

-- 9. Register Purchase Order Pages in BOS_PAGES
IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'PP0100')
BEGIN
    DECLARE @ModuleId BIGINT;
    SELECT TOP 1 @ModuleId = MOD_ID FROM BOS_PAGES WHERE PAGE_CODE LIKE 'PP%' ORDER BY PAGE_ID;
    IF @ModuleId IS NOT NULL
    BEGIN
        INSERT INTO BOS_PAGES (MOD_ID, PAGE_CODE, PAGE_NAME, PAGE_URL, ICON, ENABLED)
        VALUES (@ModuleId, 'PP0100', 'Purchase Order', '/purchase/po', 'IconShoppingCart', 1);
        PRINT 'PP0100 - Purchase Order page registered.';
    END
END

IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'PP0101')
BEGIN
    DECLARE @ModuleId2 BIGINT;
    SELECT TOP 1 @ModuleId2 = MOD_ID FROM BOS_PAGES WHERE PAGE_CODE LIKE 'PP%' ORDER BY PAGE_ID;
    IF @ModuleId2 IS NOT NULL
    BEGIN
        INSERT INTO BOS_PAGES (MOD_ID, PAGE_CODE, PAGE_NAME, PAGE_URL, ICON, ENABLED)
        VALUES (@ModuleId2, 'PP0101', 'Purchase Order Entry', '/purchase/po/entry', 'IconShoppingCart',  1);
        PRINT 'PP0101 - Purchase Order Entry page registered.';
    END
END
