-- Indexes for QMS_MOM_MASTER to improve query performance
CREATE INDEX IDX_QMS_MOM_MASTER_DATE ON QMS_MOM_MASTER(MOM_DATE);
CREATE INDEX IDX_QMS_MOM_MASTER_SCHEDULE ON QMS_MOM_MASTER(SCHEDULE_ID);
CREATE INDEX IDX_QMS_MOM_MASTER_CHAIRED ON QMS_MOM_MASTER(CHAIRED_BY_ID);
CREATE INDEX IDX_QMS_MOM_MASTER_STATUS ON QMS_MOM_MASTER(STATUS);
CREATE INDEX IDX_QMS_MOM_MASTER_CREATED_DATE ON QMS_MOM_MASTER(CREATED_DATE);
CREATE INDEX IDX_QMS_MOM_MASTER_IS_ACTIVE ON QMS_MOM_MASTER(IS_ACTIVE);

-- Indexes for QMS_MOM_DETAILS to improve filtering performance
CREATE INDEX IDX_QMS_MOM_DETAILS_MOM ON QMS_MOM_DETAILS(MOM_ID);
CREATE INDEX IDX_QMS_MOM_DETAILS_ASSIGNED_TO ON QMS_MOM_DETAILS(ASSIGNED_TO_ID);
CREATE INDEX IDX_QMS_MOM_DETAILS_ASSIGNED_BY ON QMS_MOM_DETAILS(ASSIGNED_BY_ID);
CREATE INDEX IDX_QMS_MOM_DETAILS_STATUS ON QMS_MOM_DETAILS(STATUS);
CREATE INDEX IDX_QMS_MOM_DETAILS_TARGET_DATE ON QMS_MOM_DETAILS(TARGET_DATE);
