IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('HRA_LEAVE_ENCASHMENT_VERIFIED') 
    AND name = 'REV_NO'
)
BEGIN
    ALTER TABLE HRA_LEAVE_ENCASHMENT_VERIFIED
    ADD REV_NO INT DEFAULT 0;
END
GO
