-- ============================================================
-- Alter table to drop INSTRUMENT_NAME and add INSTRUMENT_ID
-- ============================================================

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QMC_INSPECTION_SPECIFICATION_DETAIL' AND COLUMN_NAME = 'INSTRUMENT_NAME')
BEGIN
    ALTER TABLE QMC_INSPECTION_SPECIFICATION_DETAIL DROP COLUMN INSTRUMENT_NAME;
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QMC_INSPECTION_SPECIFICATION_DETAIL' AND COLUMN_NAME = 'INSTRUMENT_ID')
BEGIN
    ALTER TABLE QMC_INSPECTION_SPECIFICATION_DETAIL ADD INSTRUMENT_ID BIGINT NULL;
    
    ALTER TABLE QMC_INSPECTION_SPECIFICATION_DETAIL
        ADD CONSTRAINT FK_QMC_INSP_SPEC_DTL_INSTRUMENT FOREIGN KEY (INSTRUMENT_ID)
        REFERENCES NPD_PRODUCT_MASTER(ID);
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QMC_INSPECTION_SPECIFICATION_DETAIL' AND COLUMN_NAME = 'REFERENCE_IMAGE')
BEGIN
    ALTER TABLE QMC_INSPECTION_SPECIFICATION_DETAIL ADD REFERENCE_IMAGE NVARCHAR(500) NULL;
END
GO
