-- Migration script to add EXTERNAL_LINK_SENT column to QMS_AUDIT_SCHEDULE table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QMS_AUDIT_SCHEDULE' AND COLUMN_NAME = 'EXTERNAL_LINK_SENT')
BEGIN
    ALTER TABLE QMS_AUDIT_SCHEDULE ADD EXTERNAL_LINK_SENT BIT NULL DEFAULT 0;
END
GO
