-- 20260622_V319.0__Standardize_Permission_Tables_SOP__TIS.sql
-- Purpose: Standardize HR_PERMISSION_ENTRY and SC_PERMISSION_REQUEST tables per Database Table Structure Standard SOP.

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

-- =========================================================================
-- 1. DROP REDUNDANT REFERENCE COLUMN (SOP §6.1)
-- =========================================================================

-- Drop EMPLOYEE_NAME from HR_PERMISSION_ENTRY
IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'EMPLOYEE_NAME') IS NOT NULL
BEGIN
    ALTER TABLE dbo.HR_PERMISSION_ENTRY DROP COLUMN EMPLOYEE_NAME;
    PRINT 'Dropped redundant column EMPLOYEE_NAME from HR_PERMISSION_ENTRY';
END
GO

-- Drop EMPLOYEE_NAME from SC_PERMISSION_REQUEST
IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'EMPLOYEE_NAME') IS NOT NULL
BEGIN
    ALTER TABLE dbo.SC_PERMISSION_REQUEST DROP COLUMN EMPLOYEE_NAME;
    PRINT 'Dropped redundant column EMPLOYEE_NAME from SC_PERMISSION_REQUEST';
END
GO


-- =========================================================================
-- 2. DROP DEPENDENT DEFAULT CONSTRAINTS
-- =========================================================================

-- Drop default constraint on HR_PERMISSION_ENTRY.STATUS if it exists
DECLARE @ConstraintName NVARCHAR(256);
SELECT @ConstraintName = d.name 
FROM sys.default_constraints d 
JOIN sys.columns c ON d.parent_column_id = c.column_id AND d.parent_object_id = c.object_id
WHERE c.object_id = OBJECT_ID('dbo.HR_PERMISSION_ENTRY') AND c.name = 'STATUS';

IF @ConstraintName IS NOT NULL
BEGIN
    DECLARE @DropSql NVARCHAR(MAX) = 'ALTER TABLE dbo.HR_PERMISSION_ENTRY DROP CONSTRAINT [' + @ConstraintName + ']';
    EXEC sp_executesql @DropSql;
    PRINT 'Dropped default constraint ' + @ConstraintName + ' on HR_PERMISSION_ENTRY(STATUS)';
END
GO

-- Drop default constraint on SC_PERMISSION_REQUEST.STATUS if it exists
DECLARE @ConstraintName NVARCHAR(256);
SELECT @ConstraintName = d.name 
FROM sys.default_constraints d 
JOIN sys.columns c ON d.parent_column_id = c.column_id AND d.parent_object_id = c.object_id
WHERE c.object_id = OBJECT_ID('dbo.SC_PERMISSION_REQUEST') AND c.name = 'STATUS';

IF @ConstraintName IS NOT NULL
BEGIN
    DECLARE @DropSql NVARCHAR(MAX) = 'ALTER TABLE dbo.SC_PERMISSION_REQUEST DROP CONSTRAINT [' + @ConstraintName + ']';
    EXEC sp_executesql @DropSql;
    PRINT 'Dropped default constraint ' + @ConstraintName + ' on SC_PERMISSION_REQUEST(STATUS)';
END
GO


-- =========================================================================
-- 3. STANDARDIZE CHARACTER COLUMNS TO NVARCHAR (SOP §5.2)
-- =========================================================================

-- HR_PERMISSION_ENTRY column standardizations
IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'ACTUAL_DURATION') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN ACTUAL_DURATION NVARCHAR(100) NOT NULL;

IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'FROM_TIME') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN FROM_TIME NVARCHAR(50) NOT NULL;

IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'TO_TIME') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN TO_TIME NVARCHAR(50) NOT NULL;

IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'MONTH') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN MONTH NVARCHAR(50) NOT NULL;

IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'STATUS') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN STATUS NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'REQUEST_TYPE') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN REQUEST_TYPE NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'EMPLOYEE_CODE') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN EMPLOYEE_CODE NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'APPROVED_BY') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN APPROVED_BY NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'REJECTED_BY') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN REJECTED_BY NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'VERIFIED_BY') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN VERIFIED_BY NVARCHAR(50) NULL;
GO

-- SC_PERMISSION_REQUEST column standardizations
IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'ACTUAL_DURATION') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN ACTUAL_DURATION NVARCHAR(100) NOT NULL;

IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'FROM_TIME') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN FROM_TIME NVARCHAR(50) NOT NULL;

IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'TO_TIME') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN TO_TIME NVARCHAR(50) NOT NULL;

IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'REQUEST_TYPE') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN REQUEST_TYPE NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'STATUS') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN STATUS NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'EMPLOYEE_CODE') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN EMPLOYEE_CODE NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'APPROVED_BY') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN APPROVED_BY NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'REJECTED_BY') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN REJECTED_BY NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'VERIFIED_BY') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN VERIFIED_BY NVARCHAR(50) NULL;
GO


-- =========================================================================
-- 4. RECREATE DEFAULT CONSTRAINTS
-- =========================================================================

-- Recreate default constraint on HR_PERMISSION_ENTRY.STATUS
IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE name = 'DF_HR_PERMISSION_ENTRY_status' AND parent_object_id = OBJECT_ID('dbo.HR_PERMISSION_ENTRY'))
BEGIN
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ADD CONSTRAINT DF_HR_PERMISSION_ENTRY_status DEFAULT 'Verified' FOR STATUS;
    PRINT 'Recreated default constraint DF_HR_PERMISSION_ENTRY_status';
END
GO


-- =========================================================================
-- 5. STANDARDIZE AUDIT DATE COLUMNS TO DATETIME (SOP §3.2)
-- =========================================================================

-- HR_PERMISSION_ENTRY audit dates
IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'CREATED_DATE') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN CREATED_DATE DATETIME NOT NULL;

IF COL_LENGTH('dbo.HR_PERMISSION_ENTRY', 'UPDATED_DATE') IS NOT NULL
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ALTER COLUMN UPDATED_DATE DATETIME NULL;
GO

-- SC_PERMISSION_REQUEST audit dates
IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'CREATED_DATE') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN CREATED_DATE DATETIME NOT NULL;

IF COL_LENGTH('dbo.SC_PERMISSION_REQUEST', 'UPDATED_DATE') IS NOT NULL
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ALTER COLUMN UPDATED_DATE DATETIME NULL;
GO


-- =========================================================================
-- 6. CLEAN DATA AND CREATE FOREIGN KEY CONSTRAINTS FOR AUDIT COLUMNS (SOP §4.2)
-- =========================================================================

-- Clean up invalid references in HR_PERMISSION_ENTRY.CREATED_BY
UPDATE dbo.HR_PERMISSION_ENTRY
SET CREATED_BY = 'System'
WHERE CREATED_BY IS NOT NULL
  AND CREATED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);
GO

-- Clean up invalid references in HR_PERMISSION_ENTRY.UPDATED_BY
UPDATE dbo.HR_PERMISSION_ENTRY
SET UPDATED_BY = 'System'
WHERE UPDATED_BY IS NOT NULL
  AND UPDATED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);
GO

-- Add Foreign Key Constraints to HR_PERMISSION_ENTRY
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_PERMISSION_ENTRY_CREATED_BY' AND parent_object_id = OBJECT_ID('dbo.HR_PERMISSION_ENTRY'))
BEGIN
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ADD CONSTRAINT FK_HR_PERMISSION_ENTRY_CREATED_BY
    FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);
    PRINT 'Added FK_HR_PERMISSION_ENTRY_CREATED_BY constraint';
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_PERMISSION_ENTRY_UPDATED_BY' AND parent_object_id = OBJECT_ID('dbo.HR_PERMISSION_ENTRY'))
BEGIN
    ALTER TABLE dbo.HR_PERMISSION_ENTRY ADD CONSTRAINT FK_HR_PERMISSION_ENTRY_UPDATED_BY
    FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);
    PRINT 'Added FK_HR_PERMISSION_ENTRY_UPDATED_BY constraint';
END
GO

-- Clean up invalid references in SC_PERMISSION_REQUEST.CREATED_BY
UPDATE dbo.SC_PERMISSION_REQUEST
SET CREATED_BY = 'System'
WHERE CREATED_BY IS NOT NULL
  AND CREATED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);
GO

-- Clean up invalid references in SC_PERMISSION_REQUEST.UPDATED_BY
UPDATE dbo.SC_PERMISSION_REQUEST
SET UPDATED_BY = 'System'
WHERE UPDATED_BY IS NOT NULL
  AND UPDATED_BY NOT IN (SELECT USER_ID FROM dbo.AD_USER_CREDENTIAL);
GO

-- Add Foreign Key Constraints to SC_PERMISSION_REQUEST
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SC_PERMISSION_REQUEST_CREATED_BY' AND parent_object_id = OBJECT_ID('dbo.SC_PERMISSION_REQUEST'))
BEGIN
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ADD CONSTRAINT FK_SC_PERMISSION_REQUEST_CREATED_BY
    FOREIGN KEY (CREATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);
    PRINT 'Added FK_SC_PERMISSION_REQUEST_CREATED_BY constraint';
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SC_PERMISSION_REQUEST_UPDATED_BY' AND parent_object_id = OBJECT_ID('dbo.SC_PERMISSION_REQUEST'))
BEGIN
    ALTER TABLE dbo.SC_PERMISSION_REQUEST ADD CONSTRAINT FK_SC_PERMISSION_REQUEST_UPDATED_BY
    FOREIGN KEY (UPDATED_BY) REFERENCES dbo.AD_USER_CREDENTIAL(USER_ID);
    PRINT 'Added FK_SC_PERMISSION_REQUEST_UPDATED_BY constraint';
END
GO
