-- Migration: Create HR_PAYROLL_PROCESS_MASTER and HR_PAYROLL_PROCESS_TRANS tables
-- Description: Creates payroll process master and detail tables for payroll execution & tracking

IF OBJECT_ID(N'dbo.HR_PAYROLL_PROCESS_MASTER', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HR_PAYROLL_PROCESS_MASTER (
        ROW_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        PAYROLL_YEAR INT NOT NULL,
        PAYROLL_MONTH NVARCHAR(20) NOT NULL,
        COMPANY_ID BIGINT NULL,
        EMPLOYEE_CATEGORY_ID BIGINT NULL,
        EMPLOYEE_ID BIGINT NOT NULL,
        EMPLOYEE_CODE NVARCHAR(50) NOT NULL,
        EMPLOYEE_NAME NVARCHAR(200) NOT NULL,
        PAYMENT_MODE NVARCHAR(20) NOT NULL,
        BANK_NAME NVARCHAR(100) NULL,
        BRANCH_NAME NVARCHAR(100) NULL,
        IFSC_CODE NVARCHAR(20) NULL,
        SALARY_ACCOUNT_NUMBER NVARCHAR(50) NULL,
        ACCOUNT_NAME NVARCHAR(100) NULL,
        BANK_ACCOUNT_TYPE NVARCHAR(20) NULL,
        GROSS_SALARY DECIMAL(18,2) NOT NULL,
        TOTAL_DEDUCTIONS DECIMAL(18,2) NOT NULL,
        NET_SALARY DECIMAL(18,2) NOT NULL,
        PRESENT_DAYS DECIMAL(5,2) NOT NULL,
        LOP_DAYS DECIMAL(5,2) NOT NULL,
        PAID_DAYS DECIMAL(5,2) NOT NULL,
        OT_HOURS DECIMAL(5,2) NULL,
        WAGE_TYPE NVARCHAR(50) NULL,
        DEPARTMENT_ID BIGINT NULL,
        DESIGNATION_ID BIGINT NULL,
        ESI_NO NVARCHAR(100) NULL,
        PF_NO NVARCHAR(100) NULL,
        OLD_EMPLOYEE_CODE NVARCHAR(100) NULL,
        STATUS_ID BIGINT NOT NULL,
        APPROVED_BY NVARCHAR(50) NULL,
        APPROVED_DATE DATETIME NULL,
        CREATED_BY NVARCHAR(50) NOT NULL CONSTRAINT DF_HPPM_CB DEFAULT 'SUPER BOSS',
        CREATED_DATE DATETIME NOT NULL CONSTRAINT DF_HPPM_CD DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL
    );

    CREATE INDEX IX_HR_PAYROLL_PROCESS_MASTER_YEAR_MONTH ON dbo.HR_PAYROLL_PROCESS_MASTER (PAYROLL_YEAR, PAYROLL_MONTH);
    CREATE INDEX IX_HR_PAYROLL_PROCESS_MASTER_EMP ON dbo.HR_PAYROLL_PROCESS_MASTER (EMPLOYEE_ID);
END;
GO

IF OBJECT_ID(N'dbo.HR_PAYROLL_PROCESS_TRANS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HR_PAYROLL_PROCESS_TRANS (
        ROW_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        MASTER_ID BIGINT NOT NULL,
        COMPONENT_ID BIGINT NULL,
        COMPONENT_CODE NVARCHAR(50) NOT NULL,
        COMPONENT_NAME NVARCHAR(150) NOT NULL,
        COMPONENT_TYPE NVARCHAR(20) NOT NULL,
        ACTUAL_AMOUNT DECIMAL(18,2) NOT NULL,
        PROCESS_AMOUNT DECIMAL(18,2) NOT NULL,
        FORMULA NVARCHAR(1000) NULL,
        CALC_TYPE NVARCHAR(50) NULL,
        CALCULATION_BASIS NVARCHAR(100) NULL,
        CALCULATION_SEQUENCE INT NULL,
        PERCENTAGE DECIMAL(5,2) NULL,
        RATE DECIMAL(18,2) NULL,
        MANUAL_OVERRIDE BIT NOT NULL DEFAULT 0,
        CALCULATION_LOG NVARCHAR(MAX) NULL,
        FORMULA_VERSION NVARCHAR(20) NULL,
        CALCULATION_TIMESTAMP DATETIME NOT NULL CONSTRAINT DF_HPPT_CT DEFAULT GETDATE(),
        CONSTRAINT FK_HPPT_HPPM FOREIGN KEY (MASTER_ID) REFERENCES dbo.HR_PAYROLL_PROCESS_MASTER(ROW_ID) ON DELETE CASCADE
    );

    CREATE INDEX IX_HR_PAYROLL_PROCESS_TRANS_MASTER ON dbo.HR_PAYROLL_PROCESS_TRANS (MASTER_ID);
END;
GO
