-- DDL Migration for AD_OCR_ATTACHMENTS_PATH

IF OBJECT_ID('dbo.AD_OCR_ATTACHMENTS_PATH', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AD_OCR_ATTACHMENTS_PATH (
        ID bigint IDENTITY(1,1) PRIMARY KEY NOT NULL,
        PROCESSING_REQUEST_ID bigint NOT NULL,
        FILE_NAME nvarchar(255) NOT NULL,
        PATH nvarchar(500) NOT NULL,
        DOC_TYPE nvarchar(50) NOT NULL,
        CONTENT_TYPE nvarchar(150),
        FILE_SIZE bigint NOT NULL,
        IS_INLINE bit NOT NULL DEFAULT 0,
        ORIGINAL_ATTACHMENT_ID nvarchar(500) NOT NULL,
        ATTACHMENT_TYPE nvarchar(50) NOT NULL, -- 'EMAIL', 'DOCUMENT', 'IMAGE'
        CREATED_BY nvarchar(50) NOT NULL,
        CREATED_DATE datetime NOT NULL,
        UPDATED_BY nvarchar(50),
        UPDATED_DATE datetime,
        CONSTRAINT FK_AD_OCR_ATTACHMENTS_REQ FOREIGN KEY (PROCESSING_REQUEST_ID) REFERENCES AD_OCR_PROCESSING_REQUEST(ID) ON DELETE CASCADE,
        CONSTRAINT FK_AD_OCR_ATTACHMENTS_USER_CREATED FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_AD_OCR_ATTACHMENTS_USER_UPDATED FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT UC_AD_OCR_ATTACHMENTS_UNIQUE UNIQUE (PROCESSING_REQUEST_ID, ORIGINAL_ATTACHMENT_ID)
    );
    PRINT 'Created AD_OCR_ATTACHMENTS_PATH table';
END
GO
