-- Migration Script to create FILE_ATTACHMENT_METADATA table

IF OBJECT_ID('dbo.FILE_ATTACHMENT_METADATA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.FILE_ATTACHMENT_METADATA (
        ID bigint IDENTITY(1,1) PRIMARY KEY NOT NULL,
        STORAGE_PATH nvarchar(1000) NOT NULL UNIQUE,
        ORIGINAL_FILE_NAME nvarchar(255) NOT NULL,
        ACTIVE_STATUS bit NOT NULL DEFAULT 1,
        CREATED_BY nvarchar(50) NOT NULL,
        CREATED_DATE datetime NOT NULL,
        UPDATED_BY nvarchar(50),
        UPDATED_DATE datetime,
        CONSTRAINT FK_FILE_ATTACHMENT_METADATA_USER_CREATED FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_FILE_ATTACHMENT_METADATA_USER_UPDATED FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
    PRINT 'Created table FILE_ATTACHMENT_METADATA';
END
GO
