-- Seed 12 Regular months and 12 HR dual-month spans into HR_MONTH_MASTER

-- REGULAR MONTHS
IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'JANUARY')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'JANUARY', 1, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'FEBRUARY')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'FEBRUARY', 2, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'MARCH')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'MARCH', 3, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'APRIL')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'APRIL', 4, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'MAY')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'MAY', 5, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'JUNE')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'JUNE', 6, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'JULY')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'JULY', 7, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'AUGUST')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'AUGUST', 8, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'SEPTEMBER')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'SEPTEMBER', 9, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'OCTOBER')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'OCTOBER', 10, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'NOVEMBER')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'NOVEMBER', 11, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'REGULAR' AND MONTH_NAME = 'DECEMBER')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('REGULAR', 'DECEMBER', 12, 1, 'SYSTEM', GETDATE());


-- HR DUAL MONTHS
IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'JANUARY')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'JANUARY', 1, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'FEBRUARY')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'FEBRUARY', 2, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'MARCH')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'MARCH', 3, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'APRIL')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'APRIL', 4, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'MAY')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'MAY', 5, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'JUNE')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'JUNE', 6, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'JULY')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'JULY', 7, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'AUGUST')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'AUGUST', 8, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'SEPTEMBER')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'SEPTEMBER', 9, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'OCTOBER')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'OCTOBER', 10, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'NOVEMBER')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'NOVEMBER', 11, 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_MONTH_MASTER WHERE MONTH_TYPE = 'HR' AND MONTH_NAME = 'DECEMBER')
    INSERT INTO HR_MONTH_MASTER (MONTH_TYPE, MONTH_NAME, SEQ_NO, IS_ACTIVE, CREATED_BY, CREATED_DATE) VALUES ('HR', 'DECEMBER', 12, 1, 'SYSTEM', GETDATE());
