-- SQL Migration to add email_cc column to AD_OCR_PROCESSING_REQUEST
IF OBJECT_ID('AD_OCR_PROCESSING_REQUEST', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('AD_OCR_PROCESSING_REQUEST') AND name = 'email_cc')
    BEGIN
        ALTER TABLE AD_OCR_PROCESSING_REQUEST ADD email_cc NVARCHAR(MAX);
    END
END
GO
