IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'PURCHASE_SCHEDULE_ID' AND Object_ID = Object_ID(N'PP_GATE_ENTRY_TRANS'))
BEGIN
    ALTER TABLE PP_GATE_ENTRY_TRANS ADD PURCHASE_SCHEDULE_ID BIGINT NULL;
    ALTER TABLE PP_GATE_ENTRY_TRANS ADD CONSTRAINT FK_GET_SCHED FOREIGN KEY (PURCHASE_SCHEDULE_ID) REFERENCES PP_PURCHASE_SCHEDULE(ID);
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'PURCHASE_SCHEDULE_ID' AND Object_ID = Object_ID(N'PP_GOODS_RECEIPT_TRANS'))
BEGIN
    ALTER TABLE PP_GOODS_RECEIPT_TRANS ADD PURCHASE_SCHEDULE_ID BIGINT NULL;
    ALTER TABLE PP_GOODS_RECEIPT_TRANS ADD CONSTRAINT FK_GRT_SCHED FOREIGN KEY (PURCHASE_SCHEDULE_ID) REFERENCES PP_PURCHASE_SCHEDULE(ID);
END
