-- =======================================================================================
-- MIGRATION SCRIPT: Drop Incoming Inspection Tables
-- DB TYPE: Microsoft SQL Server
-- VERSION: 1140.0
-- =======================================================================================

-- 1. Drop Foreign Key on NPD_PRODUCT_MASTER
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_NPD_PROD_INSP_POL' AND TABLE_NAME = 'NPD_PRODUCT_MASTER')
BEGIN
    ALTER TABLE NPD_PRODUCT_MASTER DROP CONSTRAINT FK_NPD_PROD_INSP_POL;
END
GO

-- 2. Drop Column INSPECTION_POLICY_ID from NPD_PRODUCT_MASTER
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NPD_PRODUCT_MASTER' AND COLUMN_NAME = 'INSPECTION_POLICY_ID')
BEGIN
    ALTER TABLE NPD_PRODUCT_MASTER DROP COLUMN INSPECTION_POLICY_ID;
END
GO

-- 3. Drop tables in reverse order of creation
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_CHECKLIST')
    DROP TABLE PP_INCOMING_INSPECTION_CHECKLIST;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_ATTACHMENT')
    DROP TABLE PP_INCOMING_INSPECTION_ATTACHMENT;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_LOG')
    DROP TABLE PP_INCOMING_INSPECTION_LOG;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_RESULT')
    DROP TABLE PP_INCOMING_INSPECTION_RESULT;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_TRANS')
    DROP TABLE PP_INCOMING_INSPECTION_TRANS;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_SOURCE')
    DROP TABLE PP_INCOMING_INSPECTION_SOURCE;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INCOMING_INSPECTION_HEAD')
    DROP TABLE PP_INCOMING_INSPECTION_HEAD;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INSPECTION_TEMPLATE_DETAIL')
    DROP TABLE PP_INSPECTION_TEMPLATE_DETAIL;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INSPECTION_TEMPLATE')
    DROP TABLE PP_INSPECTION_TEMPLATE;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_INSPECTION_POLICY')
    DROP TABLE PP_INSPECTION_POLICY;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PP_PROCUREMENT_WORKFLOW')
    DROP TABLE PP_PROCUREMENT_WORKFLOW;
GO
