-- =============================================================================
-- Migration: V392.0 Add Sensitivity and Scope columns to SYS_ENTERPRISE_KNOWLEDGE
-- Purpose: Enables module-scoped, sensitivity-classified Enterprise Knowledge.
--          Items tagged SECRET never reach Gemini regardless of user permission.
-- =============================================================================

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_ENTERPRISE_KNOWLEDGE' AND COLUMN_NAME='MODULE_SCOPE')
BEGIN
    ALTER TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE ADD MODULE_SCOPE NVARCHAR(255) NULL;
    PRINT 'Added MODULE_SCOPE to SYS_ENTERPRISE_KNOWLEDGE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_ENTERPRISE_KNOWLEDGE' AND COLUMN_NAME='SENSITIVITY_LEVEL')
BEGIN
    ALTER TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE ADD SENSITIVITY_LEVEL VARCHAR(20) NULL DEFAULT 'INTERNAL';
    PRINT 'Added SENSITIVITY_LEVEL to SYS_ENTERPRISE_KNOWLEDGE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_ENTERPRISE_KNOWLEDGE' AND COLUMN_NAME='DIVISION_ID')
BEGIN
    ALTER TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE ADD DIVISION_ID BIGINT NULL;
    PRINT 'Added DIVISION_ID to SYS_ENTERPRISE_KNOWLEDGE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_ENTERPRISE_KNOWLEDGE' AND COLUMN_NAME='DEPARTMENT_CODE')
BEGIN
    ALTER TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE ADD DEPARTMENT_CODE NVARCHAR(50) NULL;
    PRINT 'Added DEPARTMENT_CODE to SYS_ENTERPRISE_KNOWLEDGE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_ENTERPRISE_KNOWLEDGE' AND COLUMN_NAME='TAGS')
BEGIN
    ALTER TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE ADD TAGS NVARCHAR(500) NULL;
    PRINT 'Added TAGS to SYS_ENTERPRISE_KNOWLEDGE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_ENTERPRISE_KNOWLEDGE' AND COLUMN_NAME='VERSION')
BEGIN
    ALTER TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE ADD VERSION NVARCHAR(20) NULL;
    PRINT 'Added VERSION to SYS_ENTERPRISE_KNOWLEDGE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_ENTERPRISE_KNOWLEDGE' AND COLUMN_NAME='EFFECTIVE_DATE')
BEGIN
    ALTER TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE ADD EFFECTIVE_DATE DATE NULL;
    PRINT 'Added EFFECTIVE_DATE to SYS_ENTERPRISE_KNOWLEDGE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_ENTERPRISE_KNOWLEDGE' AND COLUMN_NAME='EXPIRY_DATE')
BEGIN
    ALTER TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE ADD EXPIRY_DATE DATE NULL;
    PRINT 'Added EXPIRY_DATE to SYS_ENTERPRISE_KNOWLEDGE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_ENTERPRISE_KNOWLEDGE' AND COLUMN_NAME='OWNER_USER_ID')
BEGIN
    ALTER TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE ADD OWNER_USER_ID NVARCHAR(50) NULL;
    PRINT 'Added OWNER_USER_ID to SYS_ENTERPRISE_KNOWLEDGE';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_ENTERPRISE_KNOWLEDGE' AND COLUMN_NAME='APPROVAL_STATUS')
BEGIN
    ALTER TABLE dbo.SYS_ENTERPRISE_KNOWLEDGE ADD APPROVAL_STATUS VARCHAR(20) NULL DEFAULT 'APPROVED';
    PRINT 'Added APPROVAL_STATUS to SYS_ENTERPRISE_KNOWLEDGE';
END;

-- Set defaults on existing records
EXEC('
UPDATE dbo.SYS_ENTERPRISE_KNOWLEDGE
SET MODULE_SCOPE = ISNULL(NULLIF(CATEGORY,''''), ''GENERAL''),
    SENSITIVITY_LEVEL = ''INTERNAL'',
    APPROVAL_STATUS = ''APPROVED''
WHERE MODULE_SCOPE IS NULL OR SENSITIVITY_LEVEL IS NULL OR APPROVAL_STATUS IS NULL
');

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SYS_EK_MODULE_SCOPE' AND object_id=OBJECT_ID('SYS_ENTERPRISE_KNOWLEDGE'))
    CREATE NONCLUSTERED INDEX IX_SYS_EK_MODULE_SCOPE ON dbo.SYS_ENTERPRISE_KNOWLEDGE(MODULE_SCOPE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SYS_EK_SENSITIVITY' AND object_id=OBJECT_ID('SYS_ENTERPRISE_KNOWLEDGE'))
    CREATE NONCLUSTERED INDEX IX_SYS_EK_SENSITIVITY ON dbo.SYS_ENTERPRISE_KNOWLEDGE(SENSITIVITY_LEVEL);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SYS_EK_APPROVAL' AND object_id=OBJECT_ID('SYS_ENTERPRISE_KNOWLEDGE'))
    CREATE NONCLUSTERED INDEX IX_SYS_EK_APPROVAL ON dbo.SYS_ENTERPRISE_KNOWLEDGE(APPROVAL_STATUS);

PRINT 'V392.0 completed: Enterprise Knowledge scoping columns added.';
