-- ==============================================================================
-- Migration Script: V355.0 Update QMT Machine Columns
-- Description: Alters QMT_MACHINE table to match the new columns specification.
-- ==============================================================================

-- 1. Drop old columns if they exist
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'SPECIFICATIONS')
BEGIN
    ALTER TABLE QMT_MACHINE DROP COLUMN SPECIFICATIONS;
END
GO

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'SERIAL_NUMBER')
BEGIN
    ALTER TABLE QMT_MACHINE DROP COLUMN SERIAL_NUMBER;
END
GO

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'MAKE')
BEGIN
    ALTER TABLE QMT_MACHINE DROP COLUMN MAKE;
END
GO

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'YEAR_OF_MANUFACTURE')
BEGIN
    ALTER TABLE QMT_MACHINE DROP COLUMN YEAR_OF_MANUFACTURE;
END
GO

-- 2. Add new columns
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'DIVISION')
BEGIN
    ALTER TABLE QMT_MACHINE ADD DIVISION NVARCHAR(100) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'SEQ_NO')
BEGIN
    ALTER TABLE QMT_MACHINE ADD SEQ_NO INT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'OEE')
BEGIN
    ALTER TABLE QMT_MACHINE ADD OEE DECIMAL(5, 2) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'PRINT_NAME')
BEGIN
    ALTER TABLE QMT_MACHINE ADD PRINT_NAME NVARCHAR(100) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'LOCATION')
BEGIN
    ALTER TABLE QMT_MACHINE ADD LOCATION NVARCHAR(100) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'IP_ADDRESS')
BEGIN
    ALTER TABLE QMT_MACHINE ADD IP_ADDRESS NVARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'PORT_NO')
BEGIN
    ALTER TABLE QMT_MACHINE ADD PORT_NO INT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMT_MACHINE') AND name = 'MACHINE_IMAGE')
BEGIN
    ALTER TABLE QMT_MACHINE ADD MACHINE_IMAGE NVARCHAR(MAX) NULL;
END
GO
