-- ============================================================================
-- V1129.0 -- Add Non-Clustered Composite and Covering Indexes for MOM Performance
-- Date: 2026-08-08
-- Purpose: Optimize Minutes of Meeting (MOM) & Meeting Schedule queries on
--          User Task Queue Dashboard without altering business logic.
-- ============================================================================

-- 1. Index for QMS_MOM_MASTER (Filtering Active MOMs by Date & Chaired By)
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('QMS_MOM_MASTER') AND name = 'IX_QMS_MOM_MASTER_ACTIVE_DATE_CHAIRED'
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MOM_MASTER_ACTIVE_DATE_CHAIRED
    ON [dbo].[QMS_MOM_MASTER] ([IS_ACTIVE], [MOM_DATE], [CHAIRED_BY_ID])
    INCLUDE ([SCHEDULE_ID], [STATUS], [CREATED_BY]);
END
GO

-- 2. Index for QMS_MOM_DETAILS (Filtering Active Action Items by Assigned To)
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('QMS_MOM_DETAILS') AND name = 'IX_QMS_MOM_DETAILS_ACTIVE_ASSIGNED_STATUS'
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MOM_DETAILS_ACTIVE_ASSIGNED_STATUS
    ON [dbo].[QMS_MOM_DETAILS] ([IS_ACTIVE], [ASSIGNED_TO_ID], [PROCESS_TYPE_ID])
    INCLUDE ([MOM_ID], [STATUS], [TARGET_DATE], [VERIFIED_DATE]);
END
GO

-- 3. Index for QMS_MOM_DETAILS (Filtering Active Action Items by Assigned By)
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('QMS_MOM_DETAILS') AND name = 'IX_QMS_MOM_DETAILS_ACTIVE_ASSIGNED_BY_STATUS'
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MOM_DETAILS_ACTIVE_ASSIGNED_BY_STATUS
    ON [dbo].[QMS_MOM_DETAILS] ([IS_ACTIVE], [ASSIGNED_BY_ID], [PROCESS_TYPE_ID])
    INCLUDE ([MOM_ID], [STATUS], [TARGET_DATE]);
END
GO

-- 4. Index for QMS_CLOSE_MOM_AND_VERIFY (OUTER APPLY TOP 1 Log Lookup Optimization)
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('QMS_CLOSE_MOM_AND_VERIFY') AND name = 'IX_QMS_CLOSE_MOM_VERIFY_ACTION_ITEM_DESC'
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_CLOSE_MOM_VERIFY_ACTION_ITEM_DESC
    ON [dbo].[QMS_CLOSE_MOM_AND_VERIFY] ([ACTION_ITEM_ID], [ID] DESC)
    INCLUDE ([NEW_STATUS]);
END
GO

-- 5. Index for QMS_MEETING_SCHEDULE (Attendance & Schedule Lookups by Date, Host, Chaired)
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') AND name = 'IX_QMS_MEETING_SCHEDULE_DATE_HOST_CHAIRED'
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MEETING_SCHEDULE_DATE_HOST_CHAIRED
    ON [dbo].[QMS_MEETING_SCHEDULE] ([MEETING_DATE], [HOST_BY_ID], [CHAIRED_BY_ID])
    INCLUDE ([STATUS], [START_TIME]);
END
GO

-- 6. Index for QMS_MEETING_USER_ATTENDANCE (Schedule and Employee Lookup)
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('QMS_MEETING_USER_ATTENDANCE') AND name = 'IX_QMS_MEETING_USER_ATTENDANCE_SCHEDULE_EMP'
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MEETING_USER_ATTENDANCE_SCHEDULE_EMP
    ON [dbo].[QMS_MEETING_USER_ATTENDANCE] ([SCHEDULE_ID], [EMPLOYEE_ID])
    INCLUDE ([STATUS]);
END
GO

-- 7. Index for QMS_MEETING_SCHEDULE_PARTICIPANT (Schedule & Employee Join Optimization)
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE_PARTICIPANT') AND name = 'IX_QMS_MEETING_SCHEDULE_PARTICIPANT_SCHEDULE_EMP'
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_QMS_MEETING_SCHEDULE_PARTICIPANT_SCHEDULE_EMP
    ON [dbo].[QMS_MEETING_SCHEDULE_PARTICIPANT] ([SCHEDULE_ID], [EMPLOYEE_ID]);
END
GO
