-- Database Migration: 20260724_V1056.0__Normalize_Ats_Statuses_Part2.sql
-- Ensure all missing statuses exist, add overall status column, perform data migrations and cleanup.

SET NOCOUNT ON;

-- 1. Ensure missing statuses exist in AD_STATUS_MASTER
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'IN PROGRESS')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('In Progress');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'WAITING FOR PROGRESS')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Waiting For Progress');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'HOLD')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Hold');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PARTIALLY VERIFIED')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Partially Verified');

GO

-- 2. Add ATS_OVERALL_STATUS column to HR_EMPLOYEE_ATS if not exists
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'HR_EMPLOYEE_ATS' AND COLUMN_NAME = 'ATS_OVERALL_STATUS'
)
BEGIN
    ALTER TABLE HR_EMPLOYEE_ATS ADD ATS_OVERALL_STATUS BIGINT NULL;
    PRINT 'Added column ATS_OVERALL_STATUS to HR_EMPLOYEE_ATS';
END

GO

-- 3. Initialize ATS_OVERALL_STATUS for all records to Pending (13)
DECLARE @PendingId BIGINT = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'PENDING');
IF @PendingId IS NOT NULL
BEGIN
    EXEC('UPDATE HR_EMPLOYEE_ATS SET ATS_OVERALL_STATUS = ' + @PendingId + ' WHERE ATS_OVERALL_STATUS IS NULL');
    PRINT 'Initialized ATS_OVERALL_STATUS to Pending';
END

GO

-- 4. Add foreign key constraint for ATS_OVERALL_STATUS if not exists
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_ATS_OVERALL_STATUS')
BEGIN
    ALTER TABLE HR_EMPLOYEE_ATS ADD CONSTRAINT FK_HR_EMPLOYEE_ATS_OVERALL_STATUS 
    FOREIGN KEY (ATS_OVERALL_STATUS) REFERENCES AD_STATUS_MASTER(ID);
    PRINT 'Added FK constraint FK_HR_EMPLOYEE_ATS_OVERALL_STATUS';
END

GO

-- 5. Data Migration: CALL_STATUS Confirm (40) -> Verified (15)
DECLARE @VerifiedId BIGINT = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'VERIFIED');
IF @VerifiedId IS NOT NULL
BEGIN
    EXEC('UPDATE HR_EMPLOYEE_ATS SET CALL_STATUS = ' + @VerifiedId + ' WHERE CALL_STATUS = 40');
    PRINT 'Migrated CALL_STATUS 40 (Confirm) to Verified';
END

GO

-- 6. Data Migration: INTERVIEW_STATUS Completed (20) -> In Progress (new ID)
DECLARE @InProgressId BIGINT = (SELECT ID FROM AD_STATUS_MASTER WHERE UPPER(TRIM(NAME)) = 'IN PROGRESS');
IF @InProgressId IS NOT NULL
BEGIN
    EXEC('UPDATE HR_EMPLOYEE_ATS SET INTERVIEW_STATUS = ' + @InProgressId + ' WHERE INTERVIEW_STATUS = 20');
    PRINT 'Migrated INTERVIEW_STATUS 20 (Completed) to In Progress';
END

GO

-- 7. Clean up and delete legacy statuses
-- First check if any columns still reference CONFIRM (40) or TO BE VERIFY (44)
DECLARE @ConfirmRefs INT = 0;
SELECT @ConfirmRefs = COUNT(*) FROM HR_EMPLOYEE_ATS WHERE CALL_STATUS = 40 OR OFFER_STATUS = 40 OR VERIFICATION_STATUS = 40;

DECLARE @ToVerifyRefs INT = 0;
SELECT @ToVerifyRefs = COUNT(*) FROM HR_EMPLOYEE_ATS WHERE CALL_STATUS = 44 OR OFFER_STATUS = 44 OR VERIFICATION_STATUS = 44;

IF @ConfirmRefs = 0
BEGIN
    BEGIN TRY
        DELETE FROM AD_STATUS_MASTER WHERE ID = 40;
        PRINT 'Deleted legacy CONFIRM status (ID 40)';
    END TRY
    BEGIN CATCH
        PRINT 'WARNING: CONFIRM status (ID 40) is referenced by other tables/FKs. Cannot delete.';
    END CATCH
END
ELSE
BEGIN
    PRINT 'WARNING: CONFIRM status is still referenced in HR_EMPLOYEE_ATS. Cannot delete.';
END

IF @ToVerifyRefs = 0
BEGIN
    BEGIN TRY
        DELETE FROM AD_STATUS_MASTER WHERE ID = 44;
        PRINT 'Deleted legacy TO BE VERIFY status (ID 44)';
    END TRY
    BEGIN CATCH
        PRINT 'WARNING: TO BE VERIFY status (ID 44) is referenced by other tables/FKs. Cannot delete.';
    END CATCH
END
ELSE
BEGIN
    PRINT 'WARNING: TO BE VERIFY status is still referenced in HR_EMPLOYEE_ATS. Cannot delete.';
END

GO
