IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VENDOR_ATTACHMENT_PATH]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[VENDOR_ATTACHMENT_PATH](
		[ID] [bigint] IDENTITY(1,1) NOT NULL,
		[PAGE_CODE] [nvarchar](100) NOT NULL,
		[REF_ID] [bigint] NOT NULL,
		[DOC_TYPE] [nvarchar](100) NOT NULL,
		[PATH] [nvarchar](1000) NOT NULL,
		[FILE_NAME] [nvarchar](255) NOT NULL,
		[CREATED_BY] [nvarchar](50) NOT NULL,
		[CREATED_DATE] [datetime] NOT NULL,
		[UPDATED_BY] [nvarchar](50) NULL,
		[UPDATED_DATE] [datetime] NULL,
		[UPDATED_USER] [nvarchar](100) NULL,
	 CONSTRAINT [PK_VENDOR_ATTACHMENT_PATH] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY];

	ALTER TABLE [dbo].[VENDOR_ATTACHMENT_PATH] ADD  CONSTRAINT [DF_VENDOR_ATTACHMENT_PATH_CREATED_BY]  DEFAULT ('SUPER BOSS') FOR [CREATED_BY];

	ALTER TABLE [dbo].[VENDOR_ATTACHMENT_PATH] ADD  DEFAULT (getdate()) FOR [CREATED_DATE];

	ALTER TABLE [dbo].[VENDOR_ATTACHMENT_PATH]  WITH CHECK ADD  CONSTRAINT [FK_VENDOR_ATTACHMENT_PATH_CREATED_BY] FOREIGN KEY([CREATED_BY])
	REFERENCES [dbo].[AD_USER_CREDENTIAL] ([USER_ID]);

	ALTER TABLE [dbo].[VENDOR_ATTACHMENT_PATH] CHECK CONSTRAINT [FK_VENDOR_ATTACHMENT_PATH_CREATED_BY];

	ALTER TABLE [dbo].[VENDOR_ATTACHMENT_PATH]  WITH CHECK ADD  CONSTRAINT [FK_VENDOR_ATTACHMENT_PATH_UPDATED_BY] FOREIGN KEY([UPDATED_BY])
	REFERENCES [dbo].[AD_USER_CREDENTIAL] ([USER_ID]);

	ALTER TABLE [dbo].[VENDOR_ATTACHMENT_PATH] CHECK CONSTRAINT [FK_VENDOR_ATTACHMENT_PATH_UPDATED_BY];
END
GO
