-- Migration Script: Add CLIENT_CODE column to AD_COMPANY_CREDENTIAL table
IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'AD_COMPANY_CREDENTIAL') 
      AND name = N'CLIENT_CODE'
)
BEGIN
    ALTER TABLE AD_COMPANY_CREDENTIAL ADD CLIENT_CODE NVARCHAR(50) NULL;
END
GO
