-- Add BGV_REMARK column to HR_EMPLOYEE_REFERENCE for capturing HR notes
-- during manual background verification decisions.
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'HR_EMPLOYEE_REFERENCE' AND COLUMN_NAME = 'BGV_REMARK'
)
BEGIN
    ALTER TABLE HR_EMPLOYEE_REFERENCE ADD BGV_REMARK NVARCHAR(MAX) NULL;
    PRINT 'Added BGV_REMARK column to HR_EMPLOYEE_REFERENCE';
END
ELSE
BEGIN
    PRINT 'BGV_REMARK column already exists in HR_EMPLOYEE_REFERENCE -- skipped';
END
