-- Add missing columns to SLS_ENQUIRY
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'RFQ_MODE')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD RFQ_MODE NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'CUST_CODE')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD CUST_CODE NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'CONTACT_PERSON1')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD CONTACT_PERSON1 NVARCHAR(200) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'MOBILE1')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD MOBILE1 NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'EMAIL_ID1')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD EMAIL_ID1 NVARCHAR(200) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'ADDRESS')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD ADDRESS NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'CITY')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD CITY NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'STATE')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD STATE NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'COUNTRY')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD COUNTRY NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'PHONE1')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD PHONE1 NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'TARGET_DATE')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD TARGET_DATE DATE NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'FROM_WHERE')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD FROM_WHERE NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'DELETE_STATUS')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD DELETE_STATUS NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'DELETE_COMMENTS')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD DELETE_COMMENTS NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SLS_ENQUIRY') AND name = 'SAL_TYPE')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD SAL_TYPE NVARCHAR(100) NULL;
END

-- Create SLS_ENQUIRY_PART Table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SLS_ENQUIRY_PART')
BEGIN
    CREATE TABLE SLS_ENQUIRY_PART (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        ENQUIRY_ID BIGINT NOT NULL,
        PART_NO NVARCHAR(100) NULL,
        NAME NVARCHAR(200) NULL,
        OEM_PART_NO NVARCHAR(100) NULL,
        IPP_PART_NO NVARCHAR(100) NULL,
        DRAWING_NO NVARCHAR(100) NULL,
        DRAWING_REV_NO NVARCHAR(50) NULL,
        RM_TYPE NVARCHAR(100) NULL,
        ANNUAL_REQ_QTY DECIMAL(18, 3) NULL,
        COMMERCIALLY_FEASIBLE NVARCHAR(50) NULL,
        TECHNICALLY_FEASIBLE NVARCHAR(50) NULL,
        QUOTE_NO NVARCHAR(100) NULL,
        QUOTE_DATE DATE NULL,
        CURRENCY_CD NVARCHAR(20) NULL,
        RATE DECIMAL(18, 3) NULL,
        RATE_IN_INR DECIMAL(18, 3) NULL,
        ANNUAL_BIZ_POTENTIAL DECIMAL(18, 3) NULL,
        PO_NO NVARCHAR(100) NULL,
        PO_DATE DATE NULL,
        REMARKS NVARCHAR(MAX) NULL,
        DEPARTMENT NVARCHAR(100) NULL,
        ASSIGN_TO NVARCHAR(200) NULL,
        STATUS NVARCHAR(50) NULL,
        IS_ACTIVE BIT DEFAULT 1,
        CONSTRAINT FK_SLS_ENQUIRY_PART_ENQUIRY FOREIGN KEY (ENQUIRY_ID) REFERENCES SLS_ENQUIRY(ID) ON DELETE CASCADE
    );
END
GO
