-- Migration script to add EXTERNAL_NAME column to QMS_AUDIT_ATTENDANCE table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QMS_AUDIT_ATTENDANCE' AND COLUMN_NAME = 'EXTERNAL_NAME')
BEGIN
    ALTER TABLE QMS_AUDIT_ATTENDANCE ADD EXTERNAL_NAME NVARCHAR(200) NULL;
END
GO
