-- ============================================================
-- Migration: Revert OD Verify Table and Uppercase OD Entry Columns
-- Date: 2026-06-23
-- ============================================================

-- USE [AUTONOMA];
-- GO

-- 1. Drop HR_ATTENDANCE_OD_VERIFY table if it exists
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'HR_ATTENDANCE_OD_VERIFY')
BEGIN
    DROP TABLE HR_ATTENDANCE_OD_VERIFY;
    PRINT 'Dropped HR_ATTENDANCE_OD_VERIFY table';
END
GO

-- 2. Drop existing foreign keys on HR_ATTENDANCE_OD_ENTRY
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_ATTENDANCE_OD_ENTRY_EMPLOYEE' AND parent_object_id = OBJECT_ID('HR_ATTENDANCE_OD_ENTRY'))
BEGIN
    ALTER TABLE HR_ATTENDANCE_OD_ENTRY DROP CONSTRAINT FK_HR_ATTENDANCE_OD_ENTRY_EMPLOYEE;
    PRINT 'Dropped FK_HR_ATTENDANCE_OD_ENTRY_EMPLOYEE';
END

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_ATTENDANCE_OD_ENTRY_CREATED_BY' AND parent_object_id = OBJECT_ID('HR_ATTENDANCE_OD_ENTRY'))
BEGIN
    ALTER TABLE HR_ATTENDANCE_OD_ENTRY DROP CONSTRAINT FK_HR_ATTENDANCE_OD_ENTRY_CREATED_BY;
    PRINT 'Dropped FK_HR_ATTENDANCE_OD_ENTRY_CREATED_BY';
END

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_HR_ATTENDANCE_OD_ENTRY_UPDATED_BY' AND parent_object_id = OBJECT_ID('HR_ATTENDANCE_OD_ENTRY'))
BEGIN
    ALTER TABLE HR_ATTENDANCE_OD_ENTRY DROP CONSTRAINT FK_HR_ATTENDANCE_OD_ENTRY_UPDATED_BY;
    PRINT 'Dropped FK_HR_ATTENDANCE_OD_ENTRY_UPDATED_BY';
END
GO

-- 3. Drop existing primary key on HR_ATTENDANCE_OD_ENTRY
IF EXISTS (SELECT * FROM sys.key_constraints WHERE name = 'PK_HR_ATTENDANCE_OD_ENTRY' AND parent_object_id = OBJECT_ID('HR_ATTENDANCE_OD_ENTRY'))
BEGIN
    ALTER TABLE HR_ATTENDANCE_OD_ENTRY DROP CONSTRAINT PK_HR_ATTENDANCE_OD_ENTRY;
    PRINT 'Dropped PK_HR_ATTENDANCE_OD_ENTRY';
END
GO

-- 4. Drop unique constraint on od_number dynamically
DECLARE @UQName NVARCHAR(200);
SELECT @UQName = name 
FROM sys.key_constraints 
WHERE type = 'UQ' AND parent_object_id = OBJECT_ID('HR_ATTENDANCE_OD_ENTRY');

IF @UQName IS NOT NULL
BEGIN
    EXEC('ALTER TABLE HR_ATTENDANCE_OD_ENTRY DROP CONSTRAINT ' + @UQName);
    PRINT 'Dropped unique constraint ' + @UQName;
END
GO

-- 5. Drop all default constraints dynamically
DECLARE @DropDefaultSQL NVARCHAR(MAX) = '';
SELECT @DropDefaultSQL = @DropDefaultSQL + 'ALTER TABLE HR_ATTENDANCE_OD_ENTRY DROP CONSTRAINT ' + d.name + ';' + CHAR(13)
FROM sys.default_constraints d
WHERE d.parent_object_id = OBJECT_ID('HR_ATTENDANCE_OD_ENTRY');

IF LEN(@DropDefaultSQL) > 0
BEGIN
    EXEC sp_executesql @DropDefaultSQL;
    PRINT 'Dropped all default constraints';
END
GO

-- 6. Rename all lowercase columns to UPPERCASE
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.id', 'ID', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.od_number', 'OD_NUMBER', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.employee_id', 'EMPLOYEE_ID', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.od_from_date_time', 'OD_FROM_DATE_TIME', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.od_to_date_time', 'OD_TO_DATE_TIME', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.visit_type', 'VISIT_TYPE', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.vehicle_type', 'VEHICLE_TYPE', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.purpose_of_od', 'PURPOSE_OF_OD', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.from_location', 'FROM_LOCATION', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.to_location', 'TO_LOCATION', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.distance', 'DISTANCE', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.status', 'STATUS', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.created_by', 'CREATED_BY', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.created_date', 'CREATED_DATE', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.updated_by', 'UPDATED_BY', 'COLUMN';
EXEC sp_rename 'HR_ATTENDANCE_OD_ENTRY.updated_date', 'UPDATED_DATE', 'COLUMN';
PRINT 'Renamed all columns to UPPERCASE';
GO

-- 7. Add VERIFIED_BY, VERIFIED_DATE, and REJECTION_REASON columns
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_ATTENDANCE_OD_ENTRY') AND name = 'VERIFIED_BY')
BEGIN
    ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD VERIFIED_BY NVARCHAR(50) NULL;
    PRINT 'Added VERIFIED_BY column';
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_ATTENDANCE_OD_ENTRY') AND name = 'VERIFIED_DATE')
BEGIN
    ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD VERIFIED_DATE DATETIME2 NULL;
    PRINT 'Added VERIFIED_DATE column';
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_ATTENDANCE_OD_ENTRY') AND name = 'REJECTION_REASON')
BEGIN
    ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD REJECTION_REASON NVARCHAR(1000) NULL;
    PRINT 'Added REJECTION_REASON column';
END
GO

-- 8. Recreate Primary Key, Unique, Default, and Foreign Key constraints
ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD CONSTRAINT PK_HR_ATTENDANCE_OD_ENTRY PRIMARY KEY (ID);
ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD CONSTRAINT UQ_HR_ATTENDANCE_OD_ENTRY_OD_NUMBER UNIQUE (OD_NUMBER);
ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD CONSTRAINT DF_HR_ATTENDANCE_OD_ENTRY_STATUS DEFAULT 'Pending for Verify' FOR STATUS;
ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD CONSTRAINT DF_HR_ATTENDANCE_OD_ENTRY_CREATED_DATE DEFAULT GETDATE() FOR CREATED_DATE;

ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD CONSTRAINT FK_HR_ATTENDANCE_OD_ENTRY_EMPLOYEE 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(ID);

ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD CONSTRAINT FK_HR_ATTENDANCE_OD_ENTRY_CREATED_BY 
    FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD CONSTRAINT FK_HR_ATTENDANCE_OD_ENTRY_UPDATED_BY 
    FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE HR_ATTENDANCE_OD_ENTRY ADD CONSTRAINT FK_HR_ATTENDANCE_OD_ENTRY_VERIFIED_BY 
    FOREIGN KEY (VERIFIED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);

PRINT 'Recreated all constraints in UPPERCASE';
GO
