-- Fix PP_PURCHASE_ORDER_HEAD Schema
ALTER TABLE PP_PURCHASE_ORDER_HEAD ADD PO_TYPE NVARCHAR(50);
ALTER TABLE PP_PURCHASE_ORDER_HEAD ADD CGST_AMOUNT DECIMAL(18,4) DEFAULT 0.0000 NOT NULL;
ALTER TABLE PP_PURCHASE_ORDER_HEAD ADD SGST_AMOUNT DECIMAL(18,4) DEFAULT 0.0000 NOT NULL;
ALTER TABLE PP_PURCHASE_ORDER_HEAD ADD IGST_AMOUNT DECIMAL(18,4) DEFAULT 0.0000 NOT NULL;

-- Note: User specifically requested dropping these legacy columns as they are no longer required
ALTER TABLE PP_PURCHASE_ORDER_HEAD DROP COLUMN REVISION_NO;
ALTER TABLE PP_PURCHASE_ORDER_HEAD DROP COLUMN FREIGHT_AMOUNT;
ALTER TABLE PP_PURCHASE_ORDER_HEAD DROP COLUMN PACKING_AMOUNT;
ALTER TABLE PP_PURCHASE_ORDER_HEAD DROP COLUMN INSURANCE_AMOUNT;
ALTER TABLE PP_PURCHASE_ORDER_HEAD DROP COLUMN OTHER_CHARGES;

-- Fix PP_PURCHASE_ORDER_TRANS Schema
-- Note: User specifically requested dropping these transaction-based runtime quantities
ALTER TABLE PP_PURCHASE_ORDER_TRANS DROP COLUMN PENDING_QTY;
ALTER TABLE PP_PURCHASE_ORDER_TRANS DROP COLUMN RECEIVED_QTY;
ALTER TABLE PP_PURCHASE_ORDER_TRANS DROP COLUMN REJECTED_QTY;
ALTER TABLE PP_PURCHASE_ORDER_TRANS DROP COLUMN RETURNED_QTY;
ALTER TABLE PP_PURCHASE_ORDER_TRANS DROP COLUMN INVOICED_QTY;
