IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DB_SAVED_QUERY]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[DB_SAVED_QUERY] (
        [ID] INT IDENTITY(1,1) PRIMARY KEY,
        [QUERY_NAME] NVARCHAR(255) NOT NULL,
        [QUERY_TEXT] NVARCHAR(MAX) NOT NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        [IS_ACTIVE] BIT DEFAULT 1
    );

    ALTER TABLE [dbo].[DB_SAVED_QUERY]  WITH CHECK ADD  CONSTRAINT [FK_DB_SAVED_QUERY_CREATED_BY] FOREIGN KEY([CREATED_BY])
    REFERENCES [dbo].[AD_USER_CREDENTIAL] ([USER_ID]);

    ALTER TABLE [dbo].[DB_SAVED_QUERY] CHECK CONSTRAINT [FK_DB_SAVED_QUERY_CREATED_BY];

    ALTER TABLE [dbo].[DB_SAVED_QUERY]  WITH CHECK ADD  CONSTRAINT [FK_DB_SAVED_QUERY_UPDATED_BY] FOREIGN KEY([UPDATED_BY])
    REFERENCES [dbo].[AD_USER_CREDENTIAL] ([USER_ID]);

    ALTER TABLE [dbo].[DB_SAVED_QUERY] CHECK CONSTRAINT [FK_DB_SAVED_QUERY_UPDATED_BY];
END
GO
