IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QMS_MOM_ATTENDANCE' AND COLUMN_NAME = 'IS_ACTIVE')
BEGIN
    ALTER TABLE QMS_MOM_ATTENDANCE ADD IS_ACTIVE bit DEFAULT 1 WITH VALUES;
END
GO
