-- ============================================================================
-- V371.0 Create DD Product Process Module
-- Date: 2026-06-26
-- ============================================================================

-- 1. Create DD_PRODUCT_PROCESS table
IF OBJECT_ID('DD_PRODUCT_PROCESS', 'U') IS NULL
BEGIN
    CREATE TABLE DD_PRODUCT_PROCESS (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        PROCESS_CODE NVARCHAR(50) NOT NULL,
        PROCESS_NAME NVARCHAR(150) NOT NULL,
        FLOW_IMAGE NVARCHAR(500) NULL,
        STATUS BIT DEFAULT 1 NOT NULL,
        PROCESS_WHERE NVARCHAR(50) NULL, -- INTERNAL, EXTERNAL, BOTH
        OUTPUT_QTY NUMERIC(12,3) NULL,
        OUTPUT_UOM NVARCHAR(10) NULL,
        AUTO_GRN BIT DEFAULT 0 NOT NULL, -- Yes/No (1/0)
        AUTO_INSPECTION BIT DEFAULT 0 NOT NULL, -- Yes/No (1/0)
        PROCESS_OUTPUT_WEIGHT NUMERIC(12,3) NULL,
        DIVISION INT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT PK_DD_PRODUCT_PROCESS PRIMARY KEY (ID),
        CONSTRAINT UQ_DD_PRODUCT_PROCESS_CODE UNIQUE (PROCESS_CODE),
        CONSTRAINT UQ_DD_PRODUCT_PROCESS_NAME UNIQUE (PROCESS_NAME),
        CONSTRAINT FK_DD_PRODUCT_PROCESS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_DD_PRODUCT_PROCESS_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
END
GO

-- 2. Create DD_PRODUCT_PROCESS_MACHINE junction table
IF OBJECT_ID('DD_PRODUCT_PROCESS_MACHINE', 'U') IS NULL
BEGIN
    CREATE TABLE DD_PRODUCT_PROCESS_MACHINE (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        PROCESS_ID BIGINT NOT NULL,
        MACHINE_CATEGORY_ID BIGINT NOT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT PK_DD_PRODUCT_PROCESS_MACHINE PRIMARY KEY (ID),
        CONSTRAINT FK_DD_PP_MACHINE_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES DD_PRODUCT_PROCESS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_DD_PP_MACHINE_CATEGORY FOREIGN KEY (MACHINE_CATEGORY_ID) REFERENCES QMT_MACHINE_CATEGORY(ID) ON DELETE CASCADE,
        CONSTRAINT FK_DD_PP_MACHINE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_DD_PP_MACHINE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_DD_PRODUCT_PROCESS_MACHINE_PROCESS ON DD_PRODUCT_PROCESS_MACHINE(PROCESS_ID);
END
GO

-- 3. Create DD_PRODUCT_PROCESS_TOOL table
IF OBJECT_ID('DD_PRODUCT_PROCESS_TOOL', 'U') IS NULL
BEGIN
    CREATE TABLE DD_PRODUCT_PROCESS_TOOL (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        PROCESS_ID BIGINT NOT NULL,
        TOOL_NAME NVARCHAR(200) NOT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT PK_DD_PRODUCT_PROCESS_TOOL PRIMARY KEY (ID),
        CONSTRAINT FK_DD_PP_TOOL_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES DD_PRODUCT_PROCESS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_DD_PP_TOOL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_DD_PP_TOOL_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );
    CREATE INDEX IX_DD_PRODUCT_PROCESS_TOOL_PROCESS ON DD_PRODUCT_PROCESS_TOOL(PROCESS_ID);
END
GO

-- 4. Register Page in BOS_PAGES
DECLARE @modId INT, @subModId INT;
-- Find MOD_ID and SUB_MOD_ID using existing DD1110 (Product BOM)
SELECT @modId = MOD_ID, @subModId = SUB_MOD_ID FROM BOS_PAGES WHERE PAGE_CODE = 'DD1110';

-- Fallback if DD1110 doesn't exist
IF @modId IS NULL OR @subModId IS NULL
BEGIN
    SELECT TOP 1 @modId = MOD_ID, @subModId = SUB_MOD_ID FROM BOS_PAGES WHERE PAGE_CODE LIKE 'DD%';
END

IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'DD1111')
BEGIN
    INSERT INTO BOS_PAGES (MOD_ID, SUB_MOD_ID, PAGE_CODE, PAGE_NAME, ENABLED, PAGE_URL, ICON)
    VALUES (ISNULL(@modId, 0), ISNULL(@subModId, 0), 'DD1111', 'Product Process', 1, '/dd/product-process', 'IconSettings');
    PRINT 'Page DD1111 (Product Process) registered in BOS_PAGES.';
END
ELSE
BEGIN
    PRINT 'Page DD1111 already exists in BOS_PAGES — skipped.';
END
GO

-- 5. Grant Access permissions to the new page
DECLARE @newPageId INT;
SELECT @newPageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'DD1111';

IF @newPageId IS NOT NULL
BEGIN
    DECLARE @refPageId INT;
    SELECT @refPageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'DD1110';

    IF @refPageId IS NOT NULL
    BEGIN
        INSERT INTO BOS_USER_PAGE_AUTH
            (USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, READ_ACS, WRITE, DELETE_ACS,
             EXPORT, APPROVAL, MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, CREATED_BY, CREATED_DATE)
        SELECT
            USER_ID, @newPageId, SUB_MOD_ID, MOD_ID,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'SYSTEM', SYSDATETIME()
        FROM BOS_USER_PAGE_AUTH
        WHERE PAGE_ID = @refPageId
          AND USER_ID NOT IN (
              SELECT USER_ID FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = @newPageId
          );
        PRINT 'Access grants for DD1111 seeded based on DD1110 users.';
    END
END
GO
