-- =============================================================================
-- Migration: V393.0 Enhance SYS_AI_AUDIT_LOG with full explainability columns
-- Purpose: Supports AI Dashboard, security audit, and explainability.
-- =============================================================================

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='NOTEBOOK_ID')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD NOTEBOOK_ID BIGINT NULL; PRINT 'Added NOTEBOOK_ID'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='INTENT_CATEGORY')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD INTENT_CATEGORY NVARCHAR(50) NULL; PRINT 'Added INTENT_CATEGORY'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='DETECTED_MODULES')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD DETECTED_MODULES NVARCHAR(255) NULL; PRINT 'Added DETECTED_MODULES'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='TOOLS_INVOKED')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD TOOLS_INVOKED NVARCHAR(500) NULL; PRINT 'Added TOOLS_INVOKED'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='SQL_QUERIES_COUNT')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD SQL_QUERIES_COUNT INT NULL DEFAULT 0; PRINT 'Added SQL_QUERIES_COUNT'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='ROWS_RETURNED')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD ROWS_RETURNED INT NULL DEFAULT 0; PRINT 'Added ROWS_RETURNED'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='NOTEBOOK_SOURCES')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD NOTEBOOK_SOURCES INT NULL DEFAULT 0; PRINT 'Added NOTEBOOK_SOURCES'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='PERMISSION_CHECKS')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD PERMISSION_CHECKS NVARCHAR(MAX) NULL; PRINT 'Added PERMISSION_CHECKS'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='PERMISSION_DENIED')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD PERMISSION_DENIED BIT NULL DEFAULT 0; PRINT 'Added PERMISSION_DENIED'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='INJECTION_DETECTED')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD INJECTION_DETECTED BIT NULL DEFAULT 0; PRINT 'Added INJECTION_DETECTED'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='COMPANY_ID')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD COMPANY_ID BIGINT NULL; PRINT 'Added COMPANY_ID'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='DIVISION_ID')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD DIVISION_ID BIGINT NULL; PRINT 'Added DIVISION_ID'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='DATA_SCOPE')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD DATA_SCOPE NVARCHAR(20) NULL; PRINT 'Added DATA_SCOPE'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='SENSITIVITY_MAX')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD SENSITIVITY_MAX NVARCHAR(20) NULL; PRINT 'Added SENSITIVITY_MAX'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='LLM_MODEL')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD LLM_MODEL NVARCHAR(50) NULL; PRINT 'Added LLM_MODEL'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='PROMPT_TOKENS')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD PROMPT_TOKENS INT NULL; PRINT 'Added PROMPT_TOKENS'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='TOTAL_LATENCY_MS')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD TOTAL_LATENCY_MS INT NULL; PRINT 'Added TOTAL_LATENCY_MS'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='LLM_LATENCY_MS')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD LLM_LATENCY_MS INT NULL; PRINT 'Added LLM_LATENCY_MS'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='DB_LATENCY_MS')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD DB_LATENCY_MS INT NULL; PRINT 'Added DB_LATENCY_MS'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='TRUST_SCORE')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD TRUST_SCORE DECIMAL(5,2) NULL; PRINT 'Added TRUST_SCORE'; END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SYS_AI_AUDIT_LOG' AND COLUMN_NAME='EXPLAINABILITY_JSON')
BEGIN ALTER TABLE dbo.SYS_AI_AUDIT_LOG ADD EXPLAINABILITY_JSON NVARCHAR(MAX) NULL; PRINT 'Added EXPLAINABILITY_JSON'; END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SYS_AI_AUDIT_NOTEBOOK' AND object_id=OBJECT_ID('SYS_AI_AUDIT_LOG'))
    CREATE NONCLUSTERED INDEX IX_SYS_AI_AUDIT_NOTEBOOK ON dbo.SYS_AI_AUDIT_LOG(NOTEBOOK_ID);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SYS_AI_AUDIT_INJECTION' AND object_id=OBJECT_ID('SYS_AI_AUDIT_LOG'))
    CREATE NONCLUSTERED INDEX IX_SYS_AI_AUDIT_INJECTION ON dbo.SYS_AI_AUDIT_LOG(INJECTION_DETECTED);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SYS_AI_AUDIT_COMPANY' AND object_id=OBJECT_ID('SYS_AI_AUDIT_LOG'))
    CREATE NONCLUSTERED INDEX IX_SYS_AI_AUDIT_COMPANY ON dbo.SYS_AI_AUDIT_LOG(COMPANY_ID);

PRINT 'V393.0 completed: AI Audit Log enhanced.';
