-- ============================================================================
-- V372.0 Create Packing Procedure Creation Tables and Register Page
-- Date: 2026-06-27
-- ============================================================================

-- 1. Add PROCESS_PROCEDURE_REQUIRED column to NPD_PROCESS if not exists
IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('NPD_PROCESS') 
      AND name = 'PROCESS_PROCEDURE_REQUIRED'
)
BEGIN
    ALTER TABLE NPD_PROCESS ADD PROCESS_PROCEDURE_REQUIRED BIT DEFAULT 0 NOT NULL;
    PRINT 'Added column PROCESS_PROCEDURE_REQUIRED to NPD_PROCESS';
END
GO

-- 2. Create NPD_PROCESS_PRODUCT_MAPPING table
IF OBJECT_ID('NPD_PROCESS_PRODUCT_MAPPING', 'U') IS NULL
BEGIN
    CREATE TABLE NPD_PROCESS_PRODUCT_MAPPING (
        ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PROCESS_ID BIGINT NOT NULL,
        PRODUCT_ID BIGINT NOT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        
        CONSTRAINT FK_NPD_PPM_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES NPD_PROCESS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_PPM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES NPD_PRODUCT_MASTER(ID) ON DELETE CASCADE,
        CONSTRAINT UQ_NPD_PPM_PROCESS_PRODUCT UNIQUE (PROCESS_ID, PRODUCT_ID)
    );
    CREATE INDEX IX_NPD_PPM_PROCESS ON NPD_PROCESS_PRODUCT_MAPPING(PROCESS_ID);
    CREATE INDEX IX_NPD_PPM_PRODUCT ON NPD_PROCESS_PRODUCT_MAPPING(PRODUCT_ID);
    PRINT 'Created table NPD_PROCESS_PRODUCT_MAPPING';
END
GO

-- 3. Create NPD_PACKING_PROCEDURE_HEADER table (Parent Table)
IF OBJECT_ID('NPD_PACKING_PROCEDURE_HEADER', 'U') IS NULL
BEGIN
    CREATE TABLE NPD_PACKING_PROCEDURE_HEADER (
        ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PROCESS_ID BIGINT NOT NULL,
        PRODUCT_ID BIGINT NOT NULL,
        DOC_NO NVARCHAR(100) NOT NULL,
        REV_NO INT DEFAULT 0 NOT NULL,
        REV_DATE DATETIME NOT NULL,
        APPROVAL_STATUS NVARCHAR(50) DEFAULT 'CREATED' NOT NULL,
        IS_ACTIVE BIT DEFAULT 1 NOT NULL,
        DIVISION_ID INT NULL,
        COMPANY_ID INT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT FK_NPD_PPH_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES NPD_PROCESS(ID),
        CONSTRAINT FK_NPD_PPH_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES NPD_PRODUCT_MASTER(ID),
        CONSTRAINT UQ_NPD_PPH_DOC_REV UNIQUE (DOC_NO, REV_NO)
    );
    CREATE INDEX IX_NPD_PPH_PROCESS ON NPD_PACKING_PROCEDURE_HEADER(PROCESS_ID);
    CREATE INDEX IX_NPD_PPH_PRODUCT ON NPD_PACKING_PROCEDURE_HEADER(PRODUCT_ID);
    PRINT 'Created table NPD_PACKING_PROCEDURE_HEADER';
END
GO

-- 4. Create NPD_PROCEDURE_CONSUMABLES table (Child Table)
IF OBJECT_ID('NPD_PROCEDURE_CONSUMABLES', 'U') IS NULL
BEGIN
    CREATE TABLE NPD_PROCEDURE_CONSUMABLES (
        ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PROCEDURE_HEADER_ID BIGINT NOT NULL,
        PRODUCT_ID BIGINT NOT NULL, -- references NPD_PRODUCT_MASTER (for consumables)
        QTY NUMERIC(12,3) NOT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT FK_NPD_PC_HEADER FOREIGN KEY (PROCEDURE_HEADER_ID) REFERENCES NPD_PACKING_PROCEDURE_HEADER(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_PC_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES NPD_PRODUCT_MASTER(ID)
    );
    CREATE INDEX IX_NPD_PC_HEADER ON NPD_PROCEDURE_CONSUMABLES(PROCEDURE_HEADER_ID);
    PRINT 'Created table NPD_PROCEDURE_CONSUMABLES';
END
GO

-- 5. Create NPD_PROCEDURE_TOOLS table (Child Table)
IF OBJECT_ID('NPD_PROCEDURE_TOOLS', 'U') IS NULL
BEGIN
    CREATE TABLE NPD_PROCEDURE_TOOLS (
        ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PROCEDURE_HEADER_ID BIGINT NOT NULL,
        ASSET_ID BIGINT NOT NULL, -- references AST_MASTER
        QTY NUMERIC(12,3) NOT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT FK_NPD_PT_HEADER FOREIGN KEY (PROCEDURE_HEADER_ID) REFERENCES NPD_PACKING_PROCEDURE_HEADER(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_PT_ASSET FOREIGN KEY (ASSET_ID) REFERENCES AST_MASTER(ID)
    );
    CREATE INDEX IX_NPD_PT_HEADER ON NPD_PROCEDURE_TOOLS(PROCEDURE_HEADER_ID);
    PRINT 'Created table NPD_PROCEDURE_TOOLS';
END
GO

-- 6. Create NPD_PROCEDURE_SAFETY_EQUIP table (Child Table)
IF OBJECT_ID('NPD_PROCEDURE_SAFETY_EQUIP', 'U') IS NULL
BEGIN
    CREATE TABLE NPD_PROCEDURE_SAFETY_EQUIP (
        ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PROCEDURE_HEADER_ID BIGINT NOT NULL,
        ASSET_ID BIGINT NOT NULL, -- references AST_MASTER
        QTY NUMERIC(12,3) NOT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT FK_NPD_PSE_HEADER FOREIGN KEY (PROCEDURE_HEADER_ID) REFERENCES NPD_PACKING_PROCEDURE_HEADER(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_PSE_ASSET FOREIGN KEY (ASSET_ID) REFERENCES AST_MASTER(ID)
    );
    CREATE INDEX IX_NPD_PSE_HEADER ON NPD_PROCEDURE_SAFETY_EQUIP(PROCEDURE_HEADER_ID);
    PRINT 'Created table NPD_PROCEDURE_SAFETY_EQUIP';
END
GO

-- 7. Create NPD_PROCEDURE_MANPOWER table (Child Table)
IF OBJECT_ID('NPD_PROCEDURE_MANPOWER', 'U') IS NULL
BEGIN
    CREATE TABLE NPD_PROCEDURE_MANPOWER (
        ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PROCEDURE_HEADER_ID BIGINT NOT NULL,
        DEPARTMENT_ID BIGINT NOT NULL, -- references HR_DEPARTMENT
        DESIGNATION_ID BIGINT NOT NULL, -- references HR_DESIGNATION
        QTY INT NOT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT FK_NPD_PM_HEADER FOREIGN KEY (PROCEDURE_HEADER_ID) REFERENCES NPD_PACKING_PROCEDURE_HEADER(ID) ON DELETE CASCADE,
        CONSTRAINT FK_NPD_PM_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES HR_DEPARTMENT(ID),
        CONSTRAINT FK_NPD_PM_DESIG FOREIGN KEY (DESIGNATION_ID) REFERENCES HR_DESIGNATION(ID)
    );
    CREATE INDEX IX_NPD_PM_HEADER ON NPD_PROCEDURE_MANPOWER(PROCEDURE_HEADER_ID);
    PRINT 'Created table NPD_PROCEDURE_MANPOWER';
END
GO

-- 8. Create NPD_PROCEDURE_STEPS table (Child Table)
IF OBJECT_ID('NPD_PROCEDURE_STEPS', 'U') IS NULL
BEGIN
    CREATE TABLE NPD_PROCEDURE_STEPS (
        ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PROCEDURE_HEADER_ID BIGINT NOT NULL,
        STEP_NO INT NOT NULL,
        SPENDING_MINUTES INT NOT NULL,
        REQUIRED_ITEMS NVARCHAR(MAX) NULL, -- JSON list of linked items
        PROCEDURE_DESCRIPTION NVARCHAR(MAX) NOT NULL,
        
        -- Audit fields
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        
        CONSTRAINT FK_NPD_PS_HEADER FOREIGN KEY (PROCEDURE_HEADER_ID) REFERENCES NPD_PACKING_PROCEDURE_HEADER(ID) ON DELETE CASCADE
    );
    CREATE INDEX IX_NPD_PS_HEADER ON NPD_PROCEDURE_STEPS(PROCEDURE_HEADER_ID);
    PRINT 'Created table NPD_PROCEDURE_STEPS';
END
GO

-- 9. Register Page in BOS_PAGES
DECLARE @modId INT, @subModId INT;
-- Find MOD_ID and SUB_MOD_ID using existing DD1110 (Product BOM)
SELECT @modId = MOD_ID, @subModId = SUB_MOD_ID FROM BOS_PAGES WHERE PAGE_CODE = 'DD1110';

-- Fallback if DD1110 doesn't exist
IF @modId IS NULL OR @subModId IS NULL
BEGIN
    SELECT TOP 1 @modId = MOD_ID, @subModId = SUB_MOD_ID FROM BOS_PAGES WHERE PAGE_CODE LIKE 'DD%';
END

IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'DD1113')
BEGIN
    INSERT INTO BOS_PAGES (MOD_ID, SUB_MOD_ID, PAGE_CODE, PAGE_NAME, ENABLED, PAGE_URL, ICON)
    VALUES (ISNULL(@modId, 0), ISNULL(@subModId, 0), 'DD1113', 'Packing Procedure Creation', 1, '/dd/packing-procedure', 'IconPackage');
    PRINT 'Page DD1113 registered in BOS_PAGES.';
END
ELSE
BEGIN
    PRINT 'Page DD1113 already exists in BOS_PAGES — skipped.';
END
GO

-- 10. Seed default permissions based on DD1110
DECLARE @newPageId INT;
SELECT @newPageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'DD1113';

IF @newPageId IS NOT NULL
BEGIN
    DECLARE @refPageId INT;
    SELECT @refPageId = PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'DD1110';

    IF @refPageId IS NOT NULL
    BEGIN
        INSERT INTO BOS_USER_PAGE_AUTH
            (USER_ID, PAGE_ID, SUB_MOD_ID, MOD_ID, ENABLE, READ_ACS, WRITE, DELETE_ACS,
             EXPORT, APPROVAL, MANAGER, ADDITIONAL1, ADDITIONAL2, ADD_TASK_ENABLE, CREATED_BY, CREATED_DATE)
        SELECT
            USER_ID, @newPageId, SUB_MOD_ID, MOD_ID,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'SYSTEM', SYSDATETIME()
        FROM BOS_USER_PAGE_AUTH
        WHERE PAGE_ID = @refPageId
          AND USER_ID NOT IN (
              SELECT USER_ID FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID = @newPageId
          );
        PRINT 'Access grants seeded for DD1113.';
    END
END
GO
