-- Migration script to remove Permission Master page (M2360)
IF EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'M2360')
BEGIN
    UPDATE BOS_PAGES SET ENABLED = 0 WHERE PAGE_CODE = 'M2360';
    DELETE FROM BOS_USER_PAGE_AUTH WHERE PAGE_ID IN (SELECT PAGE_ID FROM BOS_PAGES WHERE PAGE_CODE = 'M2360');
    PRINT 'Permission Master (M2360) disabled in BOS_PAGES and purged from BOS_USER_PAGE_AUTH.';
END
GO
