-- CREATE BOS_AI_BUSINESS_GRAPH table
CREATE TABLE BOS_AI_BUSINESS_GRAPH (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    FROM_ENTITY VARCHAR(50) NOT NULL,
    TO_ENTITY VARCHAR(50) NOT NULL,
    RELATION_TYPE VARCHAR(50) NOT NULL,
    JOIN_CONDITION VARCHAR(500) NOT NULL,
    DESCRIPTION VARCHAR(500) NULL,
    ACTIVE_STATUS CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATED_BY VARCHAR(50) NULL,
    UPDATED_DATE DATETIME NULL
);

-- Seed semantic graph relationships
INSERT INTO BOS_AI_BUSINESS_GRAPH (FROM_ENTITY, TO_ENTITY, RELATION_TYPE, JOIN_CONDITION, DESCRIPTION, CREATED_BY)
VALUES 
('CUSTOMER', 'SALES_ORDER', 'DEPENDS_ON', 'FROM.CUSTOMER_ID = TO.CUSTOMER_ID', 'Customer sales orders dependency mapping', 'SYSTEM'),
('SALES_ORDER', 'PRODUCTION_ORDER', 'PRODUCES', 'FROM.ORDER_ID = TO.ORDER_ID', 'Sales order produces production orders mapping', 'SYSTEM'),
('PRODUCTION_ORDER', 'MACHINE', 'USES', 'FROM.MACHINE_ID = TO.MACHINE_ID', 'Production order runs on machine mapping', 'SYSTEM'),
('MACHINE', 'MAINTENANCE_LOG', 'DEPENDS_ON', 'FROM.MACHINE_ID = TO.MACHINE_ID', 'Machine maintenance logs relationship mapping', 'SYSTEM');
