-- Drop script for Client Module & Client Management deprecated/temporary tables

DROP TABLE IF EXISTS CLI_CLIENT_AUDIT_LOG;
DROP TABLE IF EXISTS CLI_CLIENT_CODE_SEQ;
DROP TABLE IF EXISTS cli_client_audit_log;
DROP TABLE IF EXISTS cli_client_code_seq;

-- System Client Legacy Tables (sys_client_)
DROP TABLE IF EXISTS sys_client_audit_log;
DROP TABLE IF EXISTS sys_client_code_seq;

-- Client Management Module Tables (CM_CLIENT_)
DROP TABLE IF EXISTS CM_CLIENT_NOTIFICATION;
DROP TABLE IF EXISTS CM_CLIENT_BACKUP_HISTORY;
DROP TABLE IF EXISTS CM_CLIENT_LOG;
DROP TABLE IF EXISTS CM_CLIENT_VERSION;
DROP TABLE IF EXISTS CM_CLIENT_COMMAND_HISTORY;
DROP TABLE IF EXISTS CM_CLIENT_COMMAND;
DROP TABLE IF EXISTS CM_CLIENT_LICENSE;
DROP TABLE IF EXISTS CM_CLIENT_HEARTBEAT;
DROP TABLE IF EXISTS CM_CLIENT_CONFIGURATION;
DROP TABLE IF EXISTS CM_CLIENT_MASTER;
DROP TABLE IF EXISTS cm_client_notification;
DROP TABLE IF EXISTS cm_client_backup_history;
DROP TABLE IF EXISTS cm_client_log;
DROP TABLE IF EXISTS cm_client_version;
DROP TABLE IF EXISTS cm_client_command_history;
DROP TABLE IF EXISTS cm_client_command;
DROP TABLE IF EXISTS cm_client_license;
DROP TABLE IF EXISTS cm_client_heartbeat;
DROP TABLE IF EXISTS cm_client_configuration;
DROP TABLE IF EXISTS cm_client_master;
