IF OBJECT_ID('QMT_MACHINE', 'U') IS NOT NULL AND OBJECT_ID('QMT_ASSET_MASTER', 'U') IS NULL
BEGIN
    EXEC sp_rename 'QMT_MACHINE', 'QMT_ASSET_MASTER';
    PRINT 'Renamed table QMT_MACHINE to QMT_ASSET_MASTER';
END
GO

IF OBJECT_ID('QMT_MACHINE', 'V') IS NOT NULL
BEGIN
    DROP VIEW QMT_MACHINE;
    PRINT 'Dropped view QMT_MACHINE';
END
GO