IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'SM_CUSTOMER_ORDER_HEADER' AND COLUMN_NAME = 'ORDER_TYPE'
)
BEGIN
    ALTER TABLE SM_CUSTOMER_ORDER_HEADER ADD ORDER_TYPE NVARCHAR(25) NULL;
END
GO

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'SM_CUSTOMER_ORDER_HEADER' AND COLUMN_NAME = 'ORDER_CATEGORY'
)
BEGIN
    ALTER TABLE SM_CUSTOMER_ORDER_HEADER ADD ORDER_CATEGORY NVARCHAR(100) NULL;
END
GO
