-- Add COHORT_GROUP column to HR_EMPLOYEE_SATISFACTION_MAPPING table if missing
IF OBJECT_ID('[dbo].[HR_EMPLOYEE_SATISFACTION_MAPPING]', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[dbo].[HR_EMPLOYEE_SATISFACTION_MAPPING]') AND name = 'COHORT_GROUP')
    BEGIN
        ALTER TABLE [dbo].[HR_EMPLOYEE_SATISFACTION_MAPPING] ADD [COHORT_GROUP] INT NULL;
        PRINT 'Added column COHORT_GROUP to HR_EMPLOYEE_SATISFACTION_MAPPING';
    END
END
GO
