-- Insert Checklist Reassign and End of Day trigger configurations if they do not exist
-- Created: 2026-07-09

IF NOT EXISTS (SELECT 1 FROM [dbo].[SCHEDULE_CONFIGURATION] WHERE [SCHEDULAR_NAME] = 'CHECKLIST_REASSIGN_1')
BEGIN
    INSERT INTO [dbo].[SCHEDULE_CONFIGURATION] ([SCHEDULAR_NAME], [SCHEDULAR_TIME], [STATUS], [CREATED_BY], [CREATED_DATE], [ACTIVE_STATUS])
    VALUES ('CHECKLIST_REASSIGN_1', '2024-01-01 10:00:00', 1, 'SYSTEM', GETDATE(), 'Active');
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SCHEDULE_CONFIGURATION] WHERE [SCHEDULAR_NAME] = 'CHECKLIST_REASSIGN_2')
BEGIN
    INSERT INTO [dbo].[SCHEDULE_CONFIGURATION] ([SCHEDULAR_NAME], [SCHEDULAR_TIME], [STATUS], [CREATED_BY], [CREATED_DATE], [ACTIVE_STATUS])
    VALUES ('CHECKLIST_REASSIGN_2', '2024-01-01 14:00:00', 1, 'SYSTEM', GETDATE(), 'Active');
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SCHEDULE_CONFIGURATION] WHERE [SCHEDULAR_NAME] = 'CHECKLIST_REASSIGN_3')
BEGIN
    INSERT INTO [dbo].[SCHEDULE_CONFIGURATION] ([SCHEDULAR_NAME], [SCHEDULAR_TIME], [STATUS], [CREATED_BY], [CREATED_DATE], [ACTIVE_STATUS])
    VALUES ('CHECKLIST_REASSIGN_3', '2024-01-01 16:00:00', 1, 'SYSTEM', GETDATE(), 'Active');
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[SCHEDULE_CONFIGURATION] WHERE [SCHEDULAR_NAME] = 'CHECKLIST_EOD')
BEGIN
    INSERT INTO [dbo].[SCHEDULE_CONFIGURATION] ([SCHEDULAR_NAME], [SCHEDULAR_TIME], [STATUS], [CREATED_BY], [CREATED_DATE], [ACTIVE_STATUS])
    VALUES ('CHECKLIST_EOD', '2024-01-01 23:59:00', 1, 'SYSTEM', GETDATE(), 'Active');
END
GO
