IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SLS_CUSTOMER_ADDR_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[dbo].[SLS_CUSTOMER_ADDRESS]'))
BEGIN
    ALTER TABLE [dbo].[SLS_CUSTOMER_ADDRESS] DROP CONSTRAINT [FK_SLS_CUSTOMER_ADDR_CUSTOMER];
END
