-- Drop Foreign Key constraint on PP_RFQ_SUPPLIER referencing VND_VENDOR
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PP_RFQ_SUPPLIER_VND]') AND parent_object_id = OBJECT_ID(N'[dbo].[PP_RFQ_SUPPLIER]'))
BEGIN
    ALTER TABLE [dbo].[PP_RFQ_SUPPLIER] DROP CONSTRAINT [FK_PP_RFQ_SUPPLIER_VND];
END
GO

-- Drop SM_VENDOR_MASTER table
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SM_VENDOR_MASTER]') AND type in (N'U'))
BEGIN
    DROP TABLE [dbo].[SM_VENDOR_MASTER];
END
GO

IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[AD_PREFIX_CREDENTIALS]') 
    AND name = 'RFQ_PREFIX'
)
BEGIN
    ALTER TABLE [dbo].[AD_PREFIX_CREDENTIALS] ADD 
        [RFQ_PREFIX] NVARCHAR(20) NULL,
        [RFQ_SUFFIX] NVARCHAR(20) NULL,
        [RFQ_DIGIT] INT NULL;
END
GO

ALTER TABLE HR_DEPARTMENT ADD PR_PREFIX VARCHAR(20);

EXEC('ALTER TABLE HR_DEPARTMEN' + 'T ADD PR_PREFIX VARCHAR(20)');