-- Idempotent seeding of HRA App Preferences
IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE UPPER(TRIM(PREF_NAME)) = 'SANDWICH_LEAVE')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('SANDWICH_LEAVE', 'No', 'Enable or disable Sandwich Leave rule (yes/no)', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE UPPER(TRIM(PREF_NAME)) = 'OT_MIN_MINUTES')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('OT_MIN_MINUTES', '30', 'Minimum overtime calculation interval in minutes', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE UPPER(TRIM(PREF_NAME)) = 'ESSL_SYNC_INTERVAL_MINUTES')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('ESSL_SYNC_INTERVAL_MINUTES', '15', 'Biometric eSSL auto-sync interval in minutes (default: 15)', 'HRA', 'SUPER BOSS', GETDATE());
END
