-- Idempotent script: Add ESSL_SYNC_INTERVAL_MINUTES to CLI_CLIENT_DATABASE_CONFIG and AD_COMPANY_CREDENTIAL
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'CLI_CLIENT_DATABASE_CONFIG' AND COLUMN_NAME = 'ESSL_SYNC_INTERVAL_MINUTES'
)
BEGIN
    ALTER TABLE CLI_CLIENT_DATABASE_CONFIG ADD ESSL_SYNC_INTERVAL_MINUTES INT NULL DEFAULT 15;
END;

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'AD_COMPANY_CREDENTIAL' AND COLUMN_NAME = 'ESSL_SYNC_INTERVAL_MINUTES'
)
BEGIN
    ALTER TABLE AD_COMPANY_CREDENTIAL ADD ESSL_SYNC_INTERVAL_MINUTES INT NULL DEFAULT 15;
END;
