-- Idempotent Migration: Add STATUS and FROM_EMAIL columns to EMPLOYEE_MEMO
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'EMPLOYEE_MEMO' AND COLUMN_NAME = 'STATUS'
)
BEGIN
    ALTER TABLE EMPLOYEE_MEMO ADD STATUS NVARCHAR(30) DEFAULT 'SENT';
END;

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'EMPLOYEE_MEMO' AND COLUMN_NAME = 'FROM_EMAIL'
)
BEGIN
    ALTER TABLE EMPLOYEE_MEMO ADD FROM_EMAIL NVARCHAR(255) NULL;
END;
