-- V1.1.2__seed_hra_extended_preferences.sql
-- Seed additional HRA configuration preferences for eSSL thresholds, leave limits, and shift defaults

-- Default shift parameters (used when no shift is assigned to employee)
IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'DEFAULT_SHIFT_START_TIME')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('DEFAULT_SHIFT_START_TIME', '09:00', 'Default shift start time used when no shift assigned to employee (HH:mm)', 'HRA', 1, GETDATE(), 1);
END;

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'DEFAULT_SHIFT_END_TIME')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('DEFAULT_SHIFT_END_TIME', '18:00', 'Default shift end time used when no shift assigned to employee (HH:mm)', 'HRA', 1, GETDATE(), 1);
END;

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'DEFAULT_SHIFT_HOURS')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('DEFAULT_SHIFT_HOURS', '8', 'Standard shift duration in hours used for PRESENT/HALF-DAY classification when shift not assigned (default: 8)', 'HRA', 1, GETDATE(), 1);
END;

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'DEFAULT_SHIFT_GRACE_MINUTES')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('DEFAULT_SHIFT_GRACE_MINUTES', '15', 'Default grace minutes for late arrival when no shift master record exists (default: 15m)', 'HRA', 1, GETDATE(), 1);
END;

-- Attendance classification thresholds
IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'PRESENT_THRESHOLD_MINUTES')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('PRESENT_THRESHOLD_MINUTES', '480', 'Minimum working minutes to mark employee as PRESENT (default: 480 = 8 hours)', 'HRA', 1, GETDATE(), 1);
END;

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'HALF_DAY_THRESHOLD_MINUTES')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('HALF_DAY_THRESHOLD_MINUTES', '240', 'Minimum working minutes to mark employee as HALF DAY instead of ABSENT (default: 240 = 4 hours)', 'HRA', 1, GETDATE(), 1);
END;

-- Leave policy limits
IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'LEAVE_PAST_DAYS_LIMIT')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('LEAVE_PAST_DAYS_LIMIT', '30', 'Maximum number of past days for which HR can apply a leave entry (default: 30 days)', 'HRA', 1, GETDATE(), 1);
END;

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'EL_DEFAULT_MONTHLY_ACCRUAL')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('EL_DEFAULT_MONTHLY_ACCRUAL', '1.0', 'Default monthly Earned Leave accrual rate (days/month) when no LeaveConfig found (default: 1.0)', 'HRA', 1, GETDATE(), 1);
END;
