-- V1.1.1__seed_permission_and_essl_preferences.sql
-- Seed default App Preference entries for Permission limits and Biometric eSSL integration

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'PERMISSION_MAX_REQUESTS_MONTH')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('PERMISSION_MAX_REQUESTS_MONTH', '2', 'Maximum permission requests allowed per employee per month (default: 2)', 'HRA', 1, GETDATE(), 1);
END;

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'PERMISSION_MAX_MINUTES_MONTH')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('PERMISSION_MAX_MINUTES_MONTH', '120', 'Maximum permission duration allowed per employee per month in minutes (default: 120m / 2h)', 'HRA', 1, GETDATE(), 1);
END;

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'ESSL_CONNECTION_TIMEOUT_SECONDS')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('ESSL_CONNECTION_TIMEOUT_SECONDS', '5', 'Biometric eSSL connection timeout in seconds (default: 5s)', 'HRA', 1, GETDATE(), 1);
END;

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'ESSL_AUTO_SYNC_ENABLED')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE, ACTIVE_STATUS)
    VALUES ('ESSL_AUTO_SYNC_ENABLED', 'Yes', 'Enable or disable automatic biometric eSSL device attendance synchronization (Yes/No)', 'HRA', 1, GETDATE(), 1);
END;
