-- Idempotent seeding of LOM and HR Module Preferences
IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE UPPER(TRIM(PREF_NAME)) = 'LOM_GRACE_MINUTES')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LOM_GRACE_MINUTES', '10', 'Grace time in minutes allowed before LOM is calculated', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE UPPER(TRIM(PREF_NAME)) = 'LOM_MAX_LATE_MONTH')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LOM_MAX_LATE_MONTH', '3', 'Maximum allowed late arrivals per month before penalty', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE UPPER(TRIM(PREF_NAME)) = 'LOM_PERMISSION_WAIVE')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LOM_PERMISSION_WAIVE', 'Yes', 'Whether approved permission waives LOM penalty (Yes/No)', 'HRA', 'SYSTEM', GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM AD_APP_PREFERENCE WHERE UPPER(TRIM(PREF_NAME)) = 'LOM_DEDUCTION_THRESHOLD')
BEGIN
    INSERT INTO AD_APP_PREFERENCE (PREF_NAME, PREF_VALUE, COMMENTS, PREF_TYPE, CREATED_BY, CREATED_DATE)
    VALUES ('LOM_DEDUCTION_THRESHOLD', '60', 'LOM duration in minutes that triggers automatic half-day or LOP deduction', 'HRA', 'SYSTEM', GETDATE());
END
