IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('AD_USER_THEME_SETTING') 
    AND name = 'RIBBON_LAYOUT'
)
BEGIN
    ALTER TABLE AD_USER_THEME_SETTING ADD RIBBON_LAYOUT NVARCHAR(30) NULL;
END
GO
