-- ==============================================================================
-- Migration: V1_112__Create_Quality_Inspection_Tables.sql
-- Description: Creates tables for Post-GRN Quality Inspection
-- ==============================================================================

-- 1. Quality Inspection Head Table
CREATE TABLE PP_QUALITY_INSPECTION_HEAD (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    DIVISION_ID BIGINT NOT NULL,
    QI_NO NVARCHAR(50) NOT NULL UNIQUE,
    QI_DATE DATE NOT NULL,
    GRN_HEAD_ID BIGINT NOT NULL,
    INSPECTOR_ID BIGINT,
    STATUS_ID BIGINT NOT NULL,
    REMARKS NVARCHAR(MAX),
    
    -- Audit fields
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME2 NOT NULL DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME2,
    ACTIVE_STATUS NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT FK_QI_HEAD_DIVISION FOREIGN KEY (DIVISION_ID) REFERENCES AD_DIVISION_MASTER(ID),
    CONSTRAINT FK_QI_HEAD_GRN FOREIGN KEY (GRN_HEAD_ID) REFERENCES PP_GOODS_RECEIPT_HEAD(ID),
    CONSTRAINT FK_QI_HEAD_INSPECTOR FOREIGN KEY (INSPECTOR_ID) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_QI_HEAD_STATUS FOREIGN KEY (STATUS_ID) REFERENCES AD_STATUS_MASTER(ID)
);

-- 2. Quality Inspection Transaction Table
CREATE TABLE PP_QUALITY_INSPECTION_TRANS (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    QI_HEAD_ID BIGINT NOT NULL,
    GRN_TRANS_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    BATCH_NO NVARCHAR(100),
    
    GRN_QTY DECIMAL(18, 4) NOT NULL DEFAULT 0,
    ACCEPTED_QTY DECIMAL(18, 4) NOT NULL DEFAULT 0,
    REJECTED_QTY DECIMAL(18, 4) NOT NULL DEFAULT 0,
    HOLD_QTY DECIMAL(18, 4) NOT NULL DEFAULT 0,
    
    REJECTION_REASON NVARCHAR(MAX),
    HOLD_REASON NVARCHAR(MAX),
    REMARKS NVARCHAR(MAX),
    
    -- Audit fields
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME2 NOT NULL DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME2,
    ACTIVE_STATUS NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT FK_QI_TRANS_HEAD FOREIGN KEY (QI_HEAD_ID) REFERENCES PP_QUALITY_INSPECTION_HEAD(ID),
    CONSTRAINT FK_QI_TRANS_GRN_TRANS FOREIGN KEY (GRN_TRANS_ID) REFERENCES PP_GOODS_RECEIPT_TRANS(ID),
    CONSTRAINT FK_QI_TRANS_ITEM FOREIGN KEY (ITEM_ID) REFERENCES NPD_PRODUCT_MASTER(PRODUCT_ID)
);

-- 3. Drop ACCEPTED_QTY and REJECTED_QTY from PP_GOODS_RECEIPT_TRANS
ALTER TABLE PP_GOODS_RECEIPT_TRANS DROP COLUMN ACCEPTED_QTY;
ALTER TABLE PP_GOODS_RECEIPT_TRANS DROP COLUMN REJECTED_QTY;

-- 4. Add Quality Inspection Reference to Supplier Return
ALTER TABLE PP_PURCHASE_RETURN_HEAD ADD QI_HEAD_ID BIGINT NULL;
ALTER TABLE PP_PURCHASE_RETURN_HEAD ADD CONSTRAINT FK_PP_PURCHASE_RETURN_QI FOREIGN KEY (QI_HEAD_ID) REFERENCES PP_QUALITY_INSPECTION_HEAD(ID);

ALTER TABLE PP_PURCHASE_RETURN_TRANS ADD QI_TRANS_ID BIGINT NULL;
ALTER TABLE PP_PURCHASE_RETURN_TRANS ADD CONSTRAINT FK_PP_PURCHASE_RETURN_TRANS_QI FOREIGN KEY (QI_TRANS_ID) REFERENCES PP_QUALITY_INSPECTION_TRANS(ID);
