-- SQL Migration to seed default GENERAL shift in HR_SHIFT_MASTER
USE [AT_NUTECH];
IF NOT EXISTS (SELECT 1 FROM HR_SHIFT_MASTER WHERE UPPER(TRIM(SHIFT_NAME)) = 'GENERAL' OR UPPER(TRIM(SHIFT_CODE)) = 'GEN')
BEGIN
    INSERT INTO HR_SHIFT_MASTER (
        SHIFT_NAME, SHIFT_CODE, START_TIME, END_TIME, STANDARD_HOURS, GRACE_MINUTES, IS_ACTIVE, CREATED_BY, CREATED_DATE
    ) VALUES (
        'GENERAL', 'GEN', '09:00', '18:00', 8.00, 15, 1, 'SYSTEM', GETDATE()
    );
END;
