-- SQL Migration to make SHIFT_ID nullable in HR_ATTENDANCE_DAILY_LOG table
USE [AT_NUTECH];

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_ATTENDANCE_DAILY_LOG' AND COLUMN_NAME = 'SHIFT_ID')
BEGIN
    ALTER TABLE HR_ATTENDANCE_DAILY_LOG ALTER COLUMN SHIFT_ID BIGINT NULL;
END;
