-- Update AD_APP_PREFERENCE module types (PREF_TYPE) to module names (HRA, AUDIT, MEETINGS, SCHEDULER, ADMIN)
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'AD_APP_PREFERENCE')
BEGIN
    UPDATE AD_APP_PREFERENCE SET PREF_TYPE = 'SCHEDULER' WHERE PREF_NAME LIKE '%CHECKLIST%';
    UPDATE AD_APP_PREFERENCE SET PREF_TYPE = 'AUDIT' WHERE PREF_NAME LIKE '%AUDIT%';
    UPDATE AD_APP_PREFERENCE SET PREF_TYPE = 'MEETINGS' WHERE PREF_NAME LIKE '%MEETING%';
    UPDATE AD_APP_PREFERENCE SET PREF_TYPE = 'HRA' WHERE PREF_NAME IN ('SANDWICH_LEAVE', 'OT_MIN_MINUTES') OR PREF_NAME LIKE '%LEAVE%' OR PREF_NAME LIKE '%ATTENDANCE%';
    UPDATE AD_APP_PREFERENCE SET PREF_TYPE = 'ADMIN' WHERE PREF_TYPE = 'SYSTEM_GENERATED' OR PREF_TYPE = 'NUMBER' OR PREF_TYPE IS NULL OR TRIM(PREF_TYPE) = '';
END
