IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'VISUAL_LIMIT' AND Object_ID = Object_ID(N'dbo.QMC_INSPECTION_SPECIFICATION_DETAIL'))
BEGIN
    ALTER TABLE dbo.QMC_INSPECTION_SPECIFICATION_DETAIL ADD VISUAL_LIMIT NVARCHAR(500) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'METHOD_NAME' AND Object_ID = Object_ID(N'dbo.QMC_INSPECTION_SPECIFICATION_DETAIL'))
BEGIN
    ALTER TABLE dbo.QMC_INSPECTION_SPECIFICATION_DETAIL ADD METHOD_NAME NVARCHAR(200) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'SAMPLING' AND Object_ID = Object_ID(N'dbo.QMC_INSPECTION_SPECIFICATION_DETAIL'))
BEGIN
    ALTER TABLE dbo.QMC_INSPECTION_SPECIFICATION_DETAIL ADD SAMPLING NVARCHAR(200) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'CONTROL' AND Object_ID = Object_ID(N'dbo.QMC_INSPECTION_SPECIFICATION_DETAIL'))
BEGIN
    ALTER TABLE dbo.QMC_INSPECTION_SPECIFICATION_DETAIL ADD CONTROL NVARCHAR(200) NULL;
END
GO
