IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_GOODS_RECEIPT_HEAD]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PP_GOODS_RECEIPT_HEAD](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [DIVISION_ID] [bigint] NOT NULL,
    [GRN_NO] [nvarchar](50) NOT NULL,
    [GRN_DATE] [date] NOT NULL,
    [PO_HEAD_ID] [bigint] NULL,
    [GATE_ENTRY_HEAD_ID] [bigint] NULL,
    [INSPECTION_HEAD_ID] [bigint] NULL,
    [SUPPLIER_ID] [bigint] NULL,
    [STATUS_ID] [bigint] NOT NULL,
    [APPROVAL_VERSION] [int] NOT NULL DEFAULT ((1)),
    [APPROVAL_SEQUENCE] [int] NOT NULL DEFAULT ((0)),
    [REMARKS] [nvarchar](max) NULL,
    [ACTIVE_STATUS] [nvarchar](20) NULL,
    [CREATED_BY] [nvarchar](50) NOT NULL,
    [CREATED_DATE] [datetime2](7) NULL,
    [UPDATED_BY] [nvarchar](50) NULL,
    [UPDATED_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK_PP_GOODS_RECEIPT_HEAD] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_GOODS_RECEIPT_TRANS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PP_GOODS_RECEIPT_TRANS](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [GRN_HEAD_ID] [bigint] NOT NULL,
    [PO_TRANS_ID] [bigint] NULL,
    [GATE_ENTRY_TRANS_ID] [bigint] NULL,
    [INSPECTION_TRANS_ID] [bigint] NULL,
    [ITEM_ID] [bigint] NOT NULL,
    [UOM] [nvarchar](50) NULL,
    [PO_QTY] [decimal](18, 4) NOT NULL DEFAULT ((0)),
    [PREVIOUS_RECEIVED_QTY] [decimal](18, 4) NOT NULL DEFAULT ((0)),
    [ACCEPTED_QTY] [decimal](18, 4) NOT NULL DEFAULT ((0)),
    [REJECTED_QTY] [decimal](18, 4) NOT NULL DEFAULT ((0)),
    [GRN_QTY] [decimal](18, 4) NOT NULL DEFAULT ((0)),
    [BATCH_NO] [nvarchar](50) NULL,
    [REMARKS] [nvarchar](1000) NULL,
    [ACTIVE_STATUS] [nvarchar](20) NULL,
    [CREATED_BY] [nvarchar](50) NOT NULL,
    [CREATED_DATE] [datetime2](7) NULL,
    [UPDATED_BY] [nvarchar](50) NULL,
    [UPDATED_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK_PP_GOODS_RECEIPT_TRANS] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

-- Indexes for PP_GOODS_RECEIPT_HEAD (supports search API and JOIN queries)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PP_GRN_HEAD_DIVISION_STATUS' AND object_id = OBJECT_ID('PP_GOODS_RECEIPT_HEAD'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_PP_GRN_HEAD_DIVISION_STATUS ON PP_GOODS_RECEIPT_HEAD (DIVISION_ID, STATUS_ID) INCLUDE (GRN_NO, GRN_DATE, SUPPLIER_ID)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PP_GRN_HEAD_PO_HEAD' AND object_id = OBJECT_ID('PP_GOODS_RECEIPT_HEAD'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_PP_GRN_HEAD_PO_HEAD ON PP_GOODS_RECEIPT_HEAD (PO_HEAD_ID)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PP_GRN_HEAD_INSPECTION' AND object_id = OBJECT_ID('PP_GOODS_RECEIPT_HEAD'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_PP_GRN_HEAD_INSPECTION ON PP_GOODS_RECEIPT_HEAD (INSPECTION_HEAD_ID)
END
GO

-- Indexes for PP_GOODS_RECEIPT_TRANS (supports JOIN FETCH and aggregate queries)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PP_GRN_TRANS_HEAD' AND object_id = OBJECT_ID('PP_GOODS_RECEIPT_TRANS'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_PP_GRN_TRANS_HEAD ON PP_GOODS_RECEIPT_TRANS (GRN_HEAD_ID) INCLUDE (ITEM_ID, GRN_QTY)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PP_GRN_TRANS_INSPECTION' AND object_id = OBJECT_ID('PP_GOODS_RECEIPT_TRANS'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_PP_GRN_TRANS_INSPECTION ON PP_GOODS_RECEIPT_TRANS (INSPECTION_TRANS_ID) INCLUDE (GRN_QTY)
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PP_GRN_TRANS_BATCH' AND object_id = OBJECT_ID('PP_GOODS_RECEIPT_TRANS'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_PP_GRN_TRANS_BATCH ON PP_GOODS_RECEIPT_TRANS (BATCH_NO)
END
GO
