-- 1. Master Table for Return Reasons
CREATE TABLE PP_PURCHASE_RETURN_REASON (
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [NAME] NVARCHAR(100) NOT NULL,
    [DESCRIPTION] NVARCHAR(500) NULL,
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_BY] NVARCHAR(50) NOT NULL,
    [CREATED_DATE] DATETIME DEFAULT GETDATE(),
    [UPDATED_BY] NVARCHAR(50),
    [UPDATED_DATE] DATETIME
);
GO

INSERT INTO PP_PURCHASE_RETURN_REASON ([NAME], [DESCRIPTION], [CREATED_BY], [CREATED_DATE]) VALUES 
('Damaged', 'Damaged in transit or handling', 'SYSTEM', GETDATE()),
('Wrong Item', 'Incorrect item supplied', 'SYSTEM', GETDATE()),
('Wrong Quantity', 'Quantity mismatch', 'SYSTEM', GETDATE()),
('Quality Issue', 'Failed quality checks after acceptance', 'SYSTEM', GETDATE()),
('IQC Rejected', 'Failed initial quality control', 'SYSTEM', GETDATE()),
('Specification Mismatch', 'Did not match PO specs', 'SYSTEM', GETDATE()),
('Supplier Recall', 'Recalled by supplier', 'SYSTEM', GETDATE()),
('Excess Supply', 'Over-supplied quantity', 'SYSTEM', GETDATE()),
('Other', 'Other reason', 'SYSTEM', GETDATE());
GO

-- 2. Header Table
CREATE TABLE PP_PURCHASE_RETURN_HEAD (
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [DIVISION_ID] BIGINT NOT NULL,
    [SUPPLIER_ID] BIGINT NOT NULL,
    [GRN_HEAD_ID] BIGINT NOT NULL,
    [PO_HEAD_ID] BIGINT NOT NULL,
    [INSPECTION_HEAD_ID] BIGINT NULL,
    [RETURN_NO] NVARCHAR(50) NOT NULL UNIQUE,
    [RETURN_DATE] DATETIME NOT NULL,
    [RETURN_TYPE] NVARCHAR(50) NOT NULL, -- 'ACCEPTED_STOCK' or 'REJECTED_STOCK'
    [STATUS_ID] BIGINT NOT NULL,
    [TOTAL_QTY] DECIMAL(18, 4) NOT NULL DEFAULT 0,
    [TOTAL_AMOUNT] DECIMAL(18, 4) NOT NULL DEFAULT 0,
    [REMARKS] NVARCHAR(1000) NULL,
    [CREATED_BY] NVARCHAR(50) NOT NULL,
    [CREATED_DATE] DATETIME DEFAULT GETDATE(),
    [UPDATED_BY] NVARCHAR(50),
    [UPDATED_DATE] DATETIME,
    
    CONSTRAINT [FK_PP_PURCHASE_RETURN_DIV] FOREIGN KEY ([DIVISION_ID]) REFERENCES [dbo].[AD_COMPANY_DIVISION]([ID]),
    CONSTRAINT [FK_PP_PURCHASE_RETURN_SUPP] FOREIGN KEY ([SUPPLIER_ID]) REFERENCES [dbo].[FA_ACCOUNT_LEDGER]([ID]),
    CONSTRAINT [FK_PP_PURCHASE_RETURN_GRN] FOREIGN KEY ([GRN_HEAD_ID]) REFERENCES [dbo].[PP_GOODS_RECEIPT_HEAD]([ID]),
    CONSTRAINT [FK_PP_PURCHASE_RETURN_PO] FOREIGN KEY ([PO_HEAD_ID]) REFERENCES [dbo].[PP_PURCHASE_ORDER_HEAD]([ID]),
    CONSTRAINT [FK_PP_PURCHASE_RETURN_INSP] FOREIGN KEY ([INSPECTION_HEAD_ID]) REFERENCES [dbo].[PP_INCOMING_INSPECTION_HEAD]([ID]),
    CONSTRAINT [FK_PP_PURCHASE_RETURN_STAT] FOREIGN KEY ([STATUS_ID]) REFERENCES [dbo].[AD_STATUS_MASTER]([ID])
);
GO

-- 3. Transaction Details Table
CREATE TABLE PP_PURCHASE_RETURN_TRANS (
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [RETURN_HEAD_ID] BIGINT NOT NULL,
    [GRN_TRANS_ID] BIGINT NOT NULL,
    [PO_TRANS_ID] BIGINT NOT NULL,
    [INSPECTION_TRANS_ID] BIGINT NULL,
    [ITEM_ID] BIGINT NOT NULL,
    [UOM] NVARCHAR(50) NULL,
    [BATCH_NO] NVARCHAR(50) NULL,
    [RETURN_REASON_ID] BIGINT NOT NULL,
    [SOURCE_QTY] DECIMAL(18, 4) NOT NULL DEFAULT 0, -- the actual accepted or rejected qty for reference
    [PREVIOUS_RETURNED_QTY] DECIMAL(18, 4) NOT NULL DEFAULT 0,
    [RETURN_QTY] DECIMAL(18, 4) NOT NULL DEFAULT 0,
    [UNIT_PRICE] DECIMAL(18, 4) NOT NULL DEFAULT 0,
    [AMOUNT] DECIMAL(18, 4) NOT NULL DEFAULT 0,
    [REMARKS] NVARCHAR(1000) NULL,
    [CREATED_BY] NVARCHAR(50) NOT NULL,
    [CREATED_DATE] DATETIME DEFAULT GETDATE(),
    [UPDATED_BY] NVARCHAR(50),
    [UPDATED_DATE] DATETIME,
    
    CONSTRAINT [FK_PP_PURCHASE_RETURN_TRANS_HEAD] FOREIGN KEY ([RETURN_HEAD_ID]) REFERENCES [dbo].[PP_PURCHASE_RETURN_HEAD]([ID]),
    CONSTRAINT [FK_PP_PURCHASE_RETURN_TRANS_GRN] FOREIGN KEY ([GRN_TRANS_ID]) REFERENCES [dbo].[PP_GOODS_RECEIPT_TRANS]([ID]),
    CONSTRAINT [FK_PP_PURCHASE_RETURN_TRANS_PO] FOREIGN KEY ([PO_TRANS_ID]) REFERENCES [dbo].[PP_PURCHASE_ORDER_TRANS]([ID]),
    CONSTRAINT [FK_PP_PURCHASE_RETURN_TRANS_INSP] FOREIGN KEY ([INSPECTION_TRANS_ID]) REFERENCES [dbo].[PP_INCOMING_INSPECTION_TRANS]([ID]),
    CONSTRAINT [FK_PP_PURCHASE_RETURN_TRANS_ITEM] FOREIGN KEY ([ITEM_ID]) REFERENCES [dbo].[NPD_PRODUCT_MASTER]([ID]),
    CONSTRAINT [FK_PP_PURCHASE_RETURN_TRANS_REASON] FOREIGN KEY ([RETURN_REASON_ID]) REFERENCES [dbo].[PP_PURCHASE_RETURN_REASON]([ID])
);
GO

-- Indexes for performance
CREATE INDEX IDX_PURCHASE_RETURN_DIV ON PP_PURCHASE_RETURN_HEAD([DIVISION_ID]);
CREATE INDEX IDX_PURCHASE_RETURN_NO ON PP_PURCHASE_RETURN_HEAD([RETURN_NO]);
CREATE INDEX IDX_PURCHASE_RETURN_SUPP ON PP_PURCHASE_RETURN_HEAD([SUPPLIER_ID]);
CREATE INDEX IDX_PURCHASE_RETURN_GRN ON PP_PURCHASE_RETURN_HEAD([GRN_HEAD_ID]);
CREATE INDEX IDX_PURCHASE_RETURN_STAT ON PP_PURCHASE_RETURN_HEAD([STATUS_ID]);

CREATE INDEX IDX_PURCHASE_RETURN_TRANS_HEAD ON PP_PURCHASE_RETURN_TRANS([RETURN_HEAD_ID]);
CREATE INDEX IDX_PURCHASE_RETURN_TRANS_GRN ON PP_PURCHASE_RETURN_TRANS([GRN_TRANS_ID]);
CREATE INDEX IDX_PURCHASE_RETURN_TRANS_PO ON PP_PURCHASE_RETURN_TRANS([PO_TRANS_ID]);
CREATE INDEX IDX_PURCHASE_RETURN_TRANS_ITEM ON PP_PURCHASE_RETURN_TRANS([ITEM_ID]);
CREATE INDEX IDX_PURCHASE_RETURN_TRANS_BATCH ON PP_PURCHASE_RETURN_TRANS([BATCH_NO]);
GO

-- Ensure REJECTION_RETURN exists in ITEM_TRANSACTION_TYPE
IF NOT EXISTS (SELECT 1 FROM ITEM_TRANSACTION_TYPE WHERE TYPE = 'REJECTION_RETURN')
    INSERT INTO ITEM_TRANSACTION_TYPE (TYPE, STOCK_EFFECT, DESCRIPTION, CREATED_BY, CREATED_DATE) VALUES 
    ('REJECTION_RETURN', 1, 'Return rejected material to vendor', 'SYSTEM', GETDATE());
GO
