IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PP_PURCHASE_ORDER_HEAD' AND COLUMN_NAME = 'EXPECTED_DELIVERY_DATE'
)
BEGIN
    ALTER TABLE PP_PURCHASE_ORDER_HEAD ADD EXPECTED_DELIVERY_DATE DATE;
END
GO
