-- SQL Migration to recreate HR_BIOMETRIC_ATTENDANCE table with matching column types
USE [AT_NUTECH];

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'HR_BIOMETRIC_ATTENDANCE')
BEGIN
    DROP TABLE HR_BIOMETRIC_ATTENDANCE;
END;

CREATE TABLE HR_BIOMETRIC_ATTENDANCE (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    EMP_ID BIGINT NOT NULL,
    ATTENDANCE_DATE DATE NOT NULL,
    PUNCH_IN VARCHAR(20) NULL,
    PUNCH_OUT VARCHAR(20) NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PRESENT',
    REMARKS NVARCHAR(MAX) NULL,
    SHIFT_ID BIGINT NULL,
    ESSL_IN_TIME DECIMAL(10,2) NULL,
    ESSL_OUT_TIME DECIMAL(10,2) NULL,
    TOTAL_HOURS_WORKED DECIMAL(10,2) NULL,
    OVERTIME_HOURS DECIMAL(5,2) NULL,
    IS_LATE INT NULL DEFAULT 0,
    IS_EARLY_EXIT INT NULL DEFAULT 0,
    LATITUDE_IN VARCHAR(50) NULL,
    LONGITUDE_IN VARCHAR(50) NULL,
    LATITUDE_OUT VARCHAR(50) NULL,
    LONGITUDE_OUT VARCHAR(50) NULL,
    LOCATION_IN NVARCHAR(500) NULL,
    LOCATION_OUT NVARCHAR(500) NULL,
    DEVICE_IMAGE VARBINARY(MAX) NULL,
    IS_ACTIVE BIT NULL DEFAULT 1,
    CREATED_BY VARCHAR(50) NULL,
    CREATED_DATE DATETIME NULL,
    UPDATED_BY VARCHAR(50) NULL,
    UPDATED_DATE DATETIME NULL,
    CONSTRAINT UQ_HR_BIOMETRIC_ATTENDANCE_EMP_DATE UNIQUE (EMP_ID, ATTENDANCE_DATE)
);
