package com.autonoma.erp.modules.hr.settings.entity;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "HR_SETTING_MASTER")
public class HrSettingMaster {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Category 1: Leave Apply Policy
    @Column(name = "SANDWICH_LEAVE_ENABLED", length = 10)
    private String sandwichLeaveEnabled = "YES";

    // Category 3: Permission Apply Policy
    @Column(name = "PERMISSION_MAX_REQUESTS_PER_MONTH")
    private Integer permissionMaxRequestsPerMonth = 2;

    @Column(name = "PERMISSION_MAX_MINUTES_PER_REQUEST")
    private Integer permissionMaxMinutesPerRequest = 60;

    @Column(name = "PERMISSION_MAX_TOTAL_MINUTES_PER_MONTH")
    private Integer permissionMaxTotalMinutesPerMonth = 120;

    // Category 4: Attendance & Loss of Minutes (LOM) Policy
    @Column(name = "LOM_GRACE_MINUTES")
    private Integer lomGraceMinutes = 15;

    @Column(name = "LOM_DEDUCTION_FACTOR", precision = 5, scale = 2)
    private BigDecimal lomDeductionFactor = new BigDecimal("1.00");

    @Column(name = "LOP_MODE", length = 50)
    private String lopMode = "FORMULA";

    @Column(name = "LOP_IS_FIXED", length = 10)
    private String lopIsFixed = "false";

    @Column(name = "LOP_FIXED_AMOUNT", precision = 18, scale = 2)
    private BigDecimal lopFixedAmount = new BigDecimal("500.00");

    @Column(name = "LOP_FORMULA", length = 500)
    private String lopFormula = "(GROSS / TOTAL_DAYS) * LOP_DAYS";

    // Category 5: Overtime & Biometric eSSL Policy
    @Column(name = "OT_CALCULATION_INTERVAL_MINUTES")
    private Integer otCalculationIntervalMinutes = 30;

    @Column(name = "OT_MIN_MINUTES_REQUIRED")
    private Integer otMinMinutesRequired = 60;

    @Column(name = "OT_FACTORIAL", precision = 5, scale = 2)
    private BigDecimal otFactorial = new BigDecimal("1.50");

    @Column(name = "OT_MODE", length = 50)
    private String otMode = "FORMULA";

    @Column(name = "OT_IS_FIXED", length = 10)
    private String otIsFixed = "false";

    @Column(name = "OT_FIXED_AMOUNT", precision = 18, scale = 2)
    private BigDecimal otFixedAmount = new BigDecimal("0");

    @Column(name = "OT_FORMULA", length = 500)
    private String otFormula = "((BASIC / 26) / 8)";

    @Column(name = "ESSL_SYNC_INTERVAL_MINUTES")
    private Integer esslSyncIntervalMinutes = 15;

    // Category 6: Payroll & Salary Components Policy
    @Column(name = "DEFAULT_PF_ENABLED", length = 10)
    private String defaultPfEnabled = "YES";

    @Column(name = "DEFAULT_ESI_ENABLED", length = 10)
    private String defaultEsiEnabled = "YES";

    @Column(name = "DEFAULT_PROFESSIONAL_TAX_ENABLED", length = 10)
    private String defaultProfessionalTaxEnabled = "YES";

    @Column(name = "DEFAULT_LTA_ELIGIBLE", length = 10)
    private String defaultLtaEligible = "NO";

    @Column(name = "PAYSLIP_AUTO_GENERATE_DAY")
    private Integer payslipAutoGenerateDay = 1;

    @Column(name = "SALARY_CALCULATION_BASE_DAYS")
    private Integer salaryCalculationBaseDays = 30;

    // Company & Division
    @Column(name = "COMPANY_ID")
    private Long companyId;

    @Column(name = "DIVISION_ID")
    private Long divisionId;

    // Mandatory Audit Columns
    @Column(name = "CREATED_BY", nullable = false, length = 50)
    private String createdBy = "SYSTEM";

    @Column(name = "CREATED_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdDate = new Date();

    @Column(name = "UPDATED_BY", length = 50)
    private String updatedBy;

    @Column(name = "UPDATED_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedDate;

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSandwichLeaveEnabled() {
        return sandwichLeaveEnabled;
    }

    public void setSandwichLeaveEnabled(String sandwichLeaveEnabled) {
        this.sandwichLeaveEnabled = sandwichLeaveEnabled;
    }

    public Integer getPermissionMaxRequestsPerMonth() {
        return permissionMaxRequestsPerMonth;
    }

    public void setPermissionMaxRequestsPerMonth(Integer permissionMaxRequestsPerMonth) {
        this.permissionMaxRequestsPerMonth = permissionMaxRequestsPerMonth;
    }

    public Integer getPermissionMaxMinutesPerRequest() {
        return permissionMaxMinutesPerRequest;
    }

    public void setPermissionMaxMinutesPerRequest(Integer permissionMaxMinutesPerRequest) {
        this.permissionMaxMinutesPerRequest = permissionMaxMinutesPerRequest;
    }

    public Integer getPermissionMaxTotalMinutesPerMonth() {
        return permissionMaxTotalMinutesPerMonth;
    }

    public void setPermissionMaxTotalMinutesPerMonth(Integer permissionMaxTotalMinutesPerMonth) {
        this.permissionMaxTotalMinutesPerMonth = permissionMaxTotalMinutesPerMonth;
    }

    public Integer getLomGraceMinutes() {
        return lomGraceMinutes;
    }

    public void setLomGraceMinutes(Integer lomGraceMinutes) {
        this.lomGraceMinutes = lomGraceMinutes;
    }

    public BigDecimal getLomDeductionFactor() {
        return lomDeductionFactor;
    }

    public void setLomDeductionFactor(BigDecimal lomDeductionFactor) {
        this.lomDeductionFactor = lomDeductionFactor;
    }

    public Integer getOtCalculationIntervalMinutes() {
        return otCalculationIntervalMinutes;
    }

    public void setOtCalculationIntervalMinutes(Integer otCalculationIntervalMinutes) {
        this.otCalculationIntervalMinutes = otCalculationIntervalMinutes;
    }

    public Integer getOtMinMinutesRequired() {
        return otMinMinutesRequired;
    }

    public void setOtMinMinutesRequired(Integer otMinMinutesRequired) {
        this.otMinMinutesRequired = otMinMinutesRequired;
    }

    public BigDecimal getOtFactorial() {
        return otFactorial;
    }

    public void setOtFactorial(BigDecimal otFactorial) {
        this.otFactorial = otFactorial;
    }

    public Integer getEsslSyncIntervalMinutes() {
        return esslSyncIntervalMinutes;
    }

    public void setEsslSyncIntervalMinutes(Integer esslSyncIntervalMinutes) {
        this.esslSyncIntervalMinutes = esslSyncIntervalMinutes;
    }

    public String getDefaultPfEnabled() {
        return defaultPfEnabled;
    }

    public void setDefaultPfEnabled(String defaultPfEnabled) {
        this.defaultPfEnabled = defaultPfEnabled;
    }

    public String getDefaultEsiEnabled() {
        return defaultEsiEnabled;
    }

    public void setDefaultEsiEnabled(String defaultEsiEnabled) {
        this.defaultEsiEnabled = defaultEsiEnabled;
    }

    public String getDefaultProfessionalTaxEnabled() {
        return defaultProfessionalTaxEnabled;
    }

    public void setDefaultProfessionalTaxEnabled(String defaultProfessionalTaxEnabled) {
        this.defaultProfessionalTaxEnabled = defaultProfessionalTaxEnabled;
    }

    public String getDefaultLtaEligible() {
        return defaultLtaEligible;
    }

    public void setDefaultLtaEligible(String defaultLtaEligible) {
        this.defaultLtaEligible = defaultLtaEligible;
    }

    public Integer getPayslipAutoGenerateDay() {
        return payslipAutoGenerateDay;
    }

    public void setPayslipAutoGenerateDay(Integer payslipAutoGenerateDay) {
        this.payslipAutoGenerateDay = payslipAutoGenerateDay;
    }

    public Integer getSalaryCalculationBaseDays() {
        return salaryCalculationBaseDays;
    }

    public void setSalaryCalculationBaseDays(Integer salaryCalculationBaseDays) {
        this.salaryCalculationBaseDays = salaryCalculationBaseDays;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getDivisionId() {
        return divisionId;
    }

    public void setDivisionId(Long divisionId) {
        this.divisionId = divisionId;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public String getOtMode() {
        return otMode;
    }

    public void setOtMode(String otMode) {
        this.otMode = otMode;
    }

    public String getOtIsFixed() {
        return otIsFixed;
    }

    public void setOtIsFixed(String otIsFixed) {
        this.otIsFixed = otIsFixed;
    }

    public BigDecimal getOtFixedAmount() {
        return otFixedAmount;
    }

    public void setOtFixedAmount(BigDecimal otFixedAmount) {
        this.otFixedAmount = otFixedAmount;
    }

    public String getOtFormula() {
        return otFormula;
    }

    public void setOtFormula(String otFormula) {
        this.otFormula = otFormula;
    }

    public String getLopMode() {
        return lopMode;
    }

    public void setLopMode(String lopMode) {
        this.lopMode = lopMode;
    }

    public String getLopIsFixed() {
        return lopIsFixed;
    }

    public void setLopIsFixed(String lopIsFixed) {
        this.lopIsFixed = lopIsFixed;
    }

    public BigDecimal getLopFixedAmount() {
        return lopFixedAmount;
    }

    public void setLopFixedAmount(BigDecimal lopFixedAmount) {
        this.lopFixedAmount = lopFixedAmount;
    }

    public String getLopFormula() {
        return lopFormula;
    }

    public void setLopFormula(String lopFormula) {
        this.lopFormula = lopFormula;
    }
}
