package com.autonoma.erp.service.ai;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * Generates Excel (.xlsx) reports from AI query results using Apache POI.
 */
@Service
public class ExcelReportService {

    /**
     * Generate Excel report from structured data.
     *
     * @param title   Report title displayed in cell A1
     * @param headers Column headers
     * @param rows    Data rows
     * @return byte[] – the .xlsx file content
     */
    public byte[] generateReport(String title, List<String> headers, List<List<Object>> rows)
            throws Exception {

        try (XSSFWorkbook workbook = new XSSFWorkbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            Sheet sheet = workbook.createSheet("Report");

            // ── Styles ──────────────────────────────────────────────────
            CellStyle titleStyle = createTitleStyle(workbook);
            CellStyle headerStyle = createHeaderStyle(workbook);
            CellStyle dataStyle = createDataStyle(workbook);
            CellStyle altDataStyle = createAltDataStyle(workbook);

            int rowNum = 0;

            // ── Title row ───────────────────────────────────────────────
            Row titleRow = sheet.createRow(rowNum++);
            Cell titleCell = titleRow.createCell(0);
            titleCell.setCellValue(title);
            titleCell.setCellStyle(titleStyle);
            titleRow.setHeightInPoints(30);

            // ── Subtitle row (generated at timestamp) ───────────────────
            Row subtitleRow = sheet.createRow(rowNum++);
            Cell subtitleCell = subtitleRow.createCell(0);
            subtitleCell.setCellValue("Generated by AURA  |  " +
                new SimpleDateFormat("dd-MMM-yyyy HH:mm").format(new Date()));
            CellStyle subtitleStyle = workbook.createCellStyle();
            Font subtitleFont = workbook.createFont();
            subtitleFont.setItalic(true);
            subtitleFont.setColor(IndexedColors.GREY_50_PERCENT.getIndex());
            subtitleStyle.setFont(subtitleFont);
            subtitleCell.setCellStyle(subtitleStyle);

            rowNum++; // blank row

            // ── Header row ───────────────────────────────────────────────
            Row headerRow = sheet.createRow(rowNum++);
            headerRow.setHeightInPoints(20);
            for (int i = 0; i < headers.size(); i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(headers.get(i));
                cell.setCellStyle(headerStyle);
            }

            // ── Data rows ────────────────────────────────────────────────
            for (int i = 0; i < rows.size(); i++) {
                Row dataRow = sheet.createRow(rowNum++);
                List<Object> row = rows.get(i);
                CellStyle style = (i % 2 == 0) ? dataStyle : altDataStyle;
                for (int j = 0; j < row.size(); j++) {
                    Cell cell = dataRow.createCell(j);
                    Object val = row.get(j);
                    if (val instanceof Number n) {
                        cell.setCellValue(n.doubleValue());
                    } else {
                        cell.setCellValue(val != null ? val.toString() : "");
                    }
                    cell.setCellStyle(style);
                }
            }

            // ── Auto-size columns ─────────────────────────────────────────
            for (int i = 0; i < headers.size(); i++) {
                sheet.autoSizeColumn(i);
                // Enforce minimum/maximum width
                int width = Math.max(sheet.getColumnWidth(i), 3000);
                sheet.setColumnWidth(i, Math.min(width, 15000));
            }

            // ── Footer row ───────────────────────────────────────────────
            Row footerRow = sheet.createRow(rowNum + 1);
            Cell footerCell = footerRow.createCell(0);
            footerCell.setCellValue("Total Records: " + rows.size());

            workbook.write(out);
            return out.toByteArray();
        }
    }

    // ── Style builders ───────────────────────────────────────────────────

    private CellStyle createTitleStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 16);
        font.setColor(IndexedColors.DARK_BLUE.getIndex());
        style.setFont(font);
        style.setAlignment(HorizontalAlignment.LEFT);
        style.setFillForegroundColor(IndexedColors.PALE_BLUE.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        return style;
    }

    private CellStyle createHeaderStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setBold(true);
        font.setColor(IndexedColors.WHITE.getIndex());
        font.setFontHeightInPoints((short) 11);
        style.setFont(font);
        style.setFillForegroundColor(IndexedColors.DARK_BLUE.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setAlignment(HorizontalAlignment.CENTER);
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBottomBorderColor(IndexedColors.WHITE.getIndex());
        return style;
    }

    private CellStyle createDataStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        style.setFillForegroundColor(IndexedColors.WHITE.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setBorderBottom(BorderStyle.HAIR);
        style.setBottomBorderColor(IndexedColors.GREY_25_PERCENT.getIndex());
        return style;
    }

    private CellStyle createAltDataStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        style.setFillForegroundColor(IndexedColors.LIGHT_TURQUOISE.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setBorderBottom(BorderStyle.HAIR);
        style.setBottomBorderColor(IndexedColors.GREY_25_PERCENT.getIndex());
        return style;
    }
}
