package com.autonoma.erp.service.ai;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 * Generates PDF reports from AI query results using iText.
 */
@Service
public class PdfReportService {

    private static final BaseColor HEADER_BG   = new BaseColor(13, 27, 62);   // Navy
    private static final BaseColor HEADER_FG   = BaseColor.WHITE;
    private static final BaseColor ALT_ROW_BG  = new BaseColor(235, 245, 255); // Light blue
    private static final BaseColor BORDER_COLOR = new BaseColor(200, 215, 230);

    /**
     * Generate a PDF report.
     *
     * @param title   Report title
     * @param headers Column headers
     * @param rows    Data rows
     * @return byte[] – the .pdf file content
     */
    public byte[] generateReport(String title, List<String> headers, List<List<Object>> rows)
            throws Exception {

        Document document = new Document(PageSize.A4.rotate(), 30, 30, 50, 30);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter writer = PdfWriter.getInstance(document, out);

        // Header/footer on each page
        writer.setPageEvent(new PageHeaderFooter(title));

        document.open();

        // ── Title ─────────────────────────────────────────────────────
        Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD, HEADER_BG);
        Paragraph titlePara = new Paragraph(title, titleFont);
        titlePara.setAlignment(Element.ALIGN_LEFT);
        titlePara.setSpacingAfter(4);
        document.add(titlePara);

        // ── Subtitle ──────────────────────────────────────────────────
        Font subtitleFont = new Font(Font.FontFamily.HELVETICA, 9, Font.ITALIC, BaseColor.GRAY);
        String dateStr = new SimpleDateFormat("dd-MMM-yyyy HH:mm").format(new Date());
        Paragraph subtitle = new Paragraph("Generated by AURA  |  " + dateStr, subtitleFont);
        subtitle.setSpacingAfter(16);
        document.add(subtitle);

        // ── Summary line ──────────────────────────────────────────────
        Font summaryFont = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, HEADER_BG);
        Paragraph summary = new Paragraph("Total records: " + rows.size(), summaryFont);
        summary.setSpacingAfter(10);
        document.add(summary);

        // ── Table ─────────────────────────────────────────────────────
        if (headers.isEmpty()) {
            document.add(new Paragraph("No data available.", subtitleFont));
        } else {
            PdfPTable table = new PdfPTable(headers.size());
            table.setWidthPercentage(100);

            // Header row
            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(header,
                    new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, HEADER_FG)));
                cell.setBackgroundColor(HEADER_BG);
                cell.setPadding(8);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell.setBorderColor(BORDER_COLOR);
                table.addCell(cell);
            }

            // Data rows
            Font dataFont = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.DARK_GRAY);
            for (int i = 0; i < rows.size(); i++) {
                List<Object> row = rows.get(i);
                BaseColor rowBg = (i % 2 == 0) ? BaseColor.WHITE : ALT_ROW_BG;
                for (Object val : row) {
                    PdfPCell cell = new PdfPCell(new Phrase(val != null ? val.toString() : "-", dataFont));
                    cell.setBackgroundColor(rowBg);
                    cell.setPadding(6);
                    cell.setBorderColor(BORDER_COLOR);
                    table.addCell(cell);
                }
            }

            document.add(table);
        }

        document.close();
        return out.toByteArray();
    }

    // ── Page header/footer event ──────────────────────────────────────────

    private static class PageHeaderFooter extends PdfPageEventHelper {
        private final String title;

        PageHeaderFooter(String title) {
            this.title = title;
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();
            // Footer
            Font footerFont = new Font(Font.FontFamily.HELVETICA, 8, Font.ITALIC, BaseColor.GRAY);
            Phrase footer = new Phrase(
                "BOSS · AURA Report · Page " + writer.getPageNumber(), footerFont);
            ColumnText.showTextAligned(cb, Element.ALIGN_CENTER, footer,
                (document.left() + document.right()) / 2, document.bottom() - 10, 0);
        }
    }
}
