package com.autonoma.erp.service.ai;

import org.apache.poi.xwpf.usermodel.*;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTTblPr;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTTblWidth;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.STTblWidth;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 * Generates Word (.docx) reports from AI query results using Apache POI XWPF.
 */
@Service
public class WordReportService {

    /**
     * Generate a Word report.
     *
     * @param title   Report title
     * @param headers Column headers
     * @param rows    Data rows
     * @return byte[] – the .docx file content
     */
    public byte[] generateReport(String title, List<String> headers, List<List<Object>> rows)
            throws Exception {

        try (XWPFDocument document = new XWPFDocument();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            // ── Document title ─────────────────────────────────────────
            XWPFParagraph titlePara = document.createParagraph();
            titlePara.setAlignment(ParagraphAlignment.LEFT);
            XWPFRun titleRun = titlePara.createRun();
            titleRun.setText(title);
            titleRun.setBold(true);
            titleRun.setFontSize(20);
            titleRun.setColor("0D1B3E");
            titleRun.setFontFamily("Calibri");

            // ── Subtitle ───────────────────────────────────────────────
            XWPFParagraph subtitlePara = document.createParagraph();
            XWPFRun subtitleRun = subtitlePara.createRun();
            subtitleRun.setText("Generated by AURA  |  " +
                new java.text.SimpleDateFormat("dd MMM yyyy, HH:mm").format(new java.util.Date()));
            subtitleRun.setItalic(true);
            subtitleRun.setFontSize(9);
            subtitleRun.setColor("888888");

            // ── Blank line ─────────────────────────────────────────────
            document.createParagraph();

            // ── Summary ────────────────────────────────────────────────
            XWPFParagraph summaryPara = document.createParagraph();
            XWPFRun summaryRun = summaryPara.createRun();
            summaryRun.setText("Total Records: " + rows.size());
            summaryRun.setFontSize(10);
            summaryRun.setColor("0D1B3E");

            document.createParagraph(); // blank line

            // ── Data table ────────────────────────────────────────────
            if (!headers.isEmpty()) {
                XWPFTable table = document.createTable(rows.size() + 1, headers.size());

                // Set table to full width
                CTTblPr tblPr = table.getCTTbl().getTblPr();
                CTTblWidth tblW = tblPr.addNewTblW();
                tblW.setType(STTblWidth.PCT);
                tblW.setW(BigInteger.valueOf(5000));

                // Header row
                XWPFTableRow headerRow = table.getRow(0);
                for (int i = 0; i < headers.size(); i++) {
                    XWPFTableCell cell = headerRow.getCell(i);
                    cell.setColor("0D1B3E");
                    XWPFParagraph p = cell.getParagraphs().get(0);
                    p.setAlignment(ParagraphAlignment.CENTER);
                    XWPFRun run = p.createRun();
                    run.setText(headers.get(i));
                    run.setBold(true);
                    run.setColor("FFFFFF");
                    run.setFontSize(10);
                    run.setFontFamily("Calibri");
                }

                // Data rows
                for (int i = 0; i < rows.size(); i++) {
                    XWPFTableRow dataRow = table.getRow(i + 1);
                    List<Object> row = rows.get(i);
                    String rowColor = (i % 2 == 0) ? "FFFFFF" : "EBF5FF";

                    for (int j = 0; j < Math.min(row.size(), headers.size()); j++) {
                        XWPFTableCell cell = dataRow.getCell(j);
                        cell.setColor(rowColor);
                        XWPFParagraph p = cell.getParagraphs().get(0);
                        XWPFRun run = p.createRun();
                        Object val = row.get(j);
                        run.setText(val != null ? val.toString() : "-");
                        run.setFontSize(9);
                        run.setFontFamily("Calibri");
                    }
                }
            }

            document.createParagraph(); // blank line

            // ── Footer note ───────────────────────────────────────────
            XWPFParagraph footerPara = document.createParagraph();
            XWPFRun footerRun = footerPara.createRun();
            footerRun.setText("BOSS · AURA · Confidential");
            footerRun.setItalic(true);
            footerRun.setFontSize(8);
            footerRun.setColor("AAAAAA");

            document.write(out);
            return out.toByteArray();
        }
    }
}
