import { useState, useEffect, useCallback } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Grid,
  Switch,
  FormControlLabel,
  TextField,
  Button,
  Tabs,
  Tab,
  Stack,
  Divider,
  Alert,
  Tooltip,
  IconButton,
  Chip,
  useTheme
} from '@mui/material';
import {
  IconSettings,
  IconCalendarEvent,
  IconBriefcase,
  IconClock,
  IconFingerprint,
  IconCurrencyRupee,
  IconDeviceFloppy,
  IconRefresh,
  IconRotate2,
  IconInfoCircle
} from '@tabler/icons-react';
import axios from 'utils/axios';
import { useDispatch } from 'react-redux';
import { openSnackbar } from 'store/slices/snackbar';
import MainCard from 'ui-component/cards/MainCard';
import usePagePermissions, { PAGE_CODES } from 'hooks/usePagePermissions';

const INITIAL_SETTINGS = {
  // Category 1: Leave Apply Policy
  sandwichLeaveEnabled: 'YES',



  // Category 3: Permission Apply Policy
  permissionMaxRequestsPerMonth: 2,
  permissionMaxMinutesPerRequest: 60,
  permissionMaxTotalMinutesPerMonth: 120,

  // Category 4: Attendance & LOM Policy
  lomGraceMinutes: 15,
  lomDeductionFactor: 1.00,

  // Category 5: Overtime & Biometric eSSL Policy
  otCalculationIntervalMinutes: 30,
  otMinMinutesRequired: 60,
  otFactorial: 1.50,
  esslSyncIntervalMinutes: 15,

  // Category 6: Payroll & Salary Components Policy
  defaultPfEnabled: 'YES',
  defaultEsiEnabled: 'YES',
  defaultProfessionalTaxEnabled: 'YES',
  defaultLtaEligible: 'NO',
  payslipAutoGenerateDay: 1,
  salaryCalculationBaseDays: 30
};

export default function HrSettings() {
  const dispatch = useDispatch();
  const theme = useTheme();
  const perms = usePagePermissions(PAGE_CODES.AD_PAYROLL_WORKSPACE || 'AD_HR_SETTINGS');

  const [currentTab, setCurrentTab] = useState(0);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [settings, setSettings] = useState(INITIAL_SETTINGS);

  const fetchSettings = useCallback(async () => {
    setLoading(true);
    try {
      const res = await axios.get('/api/hr/settings');
      if (res.data) {
        setSettings({
          ...INITIAL_SETTINGS,
          ...res.data
        });
      }
    } catch (err) {
      console.error('Error loading HR settings:', err);
      dispatch(
        openSnackbar({
          open: true,
          message: 'Failed to load HR settings. Using default policies.',
          variant: 'alert',
          severity: 'error'
        })
      );
    } finally {
      setLoading(false);
    }
  }, [dispatch]);

  useEffect(() => {
    fetchSettings();
  }, [fetchSettings]);

  const handleSwitchChange = (field) => (event) => {
    const checked = event.target.checked;
    setSettings((prev) => ({
      ...prev,
      [field]: checked ? 'YES' : 'NO'
    }));
  };

  const handleNumberChange = (field) => (event) => {
    const val = event.target.value;
    setSettings((prev) => ({
      ...prev,
      [field]: val === '' ? '' : Number(val)
    }));
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      const res = await axios.post('/api/hr/settings', settings);
      if (res.data) {
        setSettings(res.data);
        dispatch(
          openSnackbar({
            open: true,
            message: 'HR Settings & Policies saved successfully!',
            variant: 'alert',
            severity: 'success'
          })
        );
      }
    } catch (err) {
      console.error('Error saving HR settings:', err);
      dispatch(
        openSnackbar({
          open: true,
          message: err?.response?.data?.message || 'Failed to save HR Settings.',
          variant: 'alert',
          severity: 'error'
        })
      );
    } finally {
      setSaving(false);
    }
  };

  const handleResetDefaults = () => {
    setSettings(INITIAL_SETTINGS);
    dispatch(
      openSnackbar({
        open: true,
        message: 'Settings reset to standard policy defaults. Click Save to apply.',
        variant: 'alert',
        severity: 'info'
      })
    );
  };

  return (
    <MainCard
      pageCode="AD_HR_SETTINGS"
      title={
        <Stack direction="row" alignItems="center" spacing={1.5}>
          <IconSettings size={24} color={theme.palette.primary.main} />
          <Typography variant="h3">HR Policy & Master Configuration Settings</Typography>
        </Stack>
      }
      secondary={
        <Stack direction="row" spacing={1.5} alignItems="center">
          <Tooltip title="Reset to Policy Defaults">
            <Button
              variant="outlined"
              color="secondary"
              startIcon={<IconRotate2 size={18} />}
              onClick={handleResetDefaults}
              disabled={saving || loading}
            >
              Reset Defaults
            </Button>
          </Tooltip>
          <Tooltip title="Refresh Settings">
            <IconButton onClick={fetchSettings} disabled={loading} color="primary">
              <IconRefresh size={20} />
            </IconButton>
          </Tooltip>
          <Button
            variant="contained"
            color="primary"
            startIcon={<IconDeviceFloppy size={18} />}
            onClick={handleSave}
            disabled={saving || loading}
          >
            {saving ? 'Saving...' : 'Save'}
          </Button>
        </Stack>
      }
    >
      <Box sx={{ width: '100%' }}>
        {/* STICKY QUICK NAV BAR */}
        <Box sx={{ mb: 3, display: 'flex', gap: 1, flexWrap: 'wrap' }}>
          {[
            { id: 'hr-leave', label: '1. Leave Policy', icon: <IconCalendarEvent size={16} /> },
            { id: 'hr-permission', label: '2. Permission Policy', icon: <IconClock size={16} /> },
            { id: 'hr-lom', label: '3. Attendance & LOM', icon: <IconClock size={16} /> },
            { id: 'hr-ot', label: '4. Overtime Policy', icon: <IconFingerprint size={16} /> },
            { id: 'hr-payroll', label: '5. Payroll & Salary Defaults', icon: <IconCurrencyRupee size={16} /> }
          ].map((panel) => (
            <Chip
              key={panel.id}
              icon={panel.icon}
              label={panel.label}
              onClick={() => {
                const el = document.getElementById(panel.id);
                if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
              }}
              clickable
              color="primary"
              variant="outlined"
              sx={{ fontWeight: 700, fontSize: '0.825rem' }}
            />
          ))}
        </Box>

        <Stack spacing={4}>
          {/* PANEL 1: LEAVE POLICY */}
          <Box id="hr-leave">
            <Typography variant="h4" color="primary" sx={{ fontWeight: 800, mb: 1.5 }}>
              1. Leave Policy & Sandwich Rules
            </Typography>
            <Grid container spacing={3}>
              <Grid item xs={12}>
                <Alert severity="info" icon={<IconInfoCircle />}>
                  Configure rules for Leave Applications and Sandwich rules. (Backdated leave is standard 3 days for employees/managers; further past dates require ADD1 permission).
                </Alert>
              </Grid>
              <Grid item xs={12} md={6}>
                <Card variant="outlined" sx={{ p: 2, height: '100%' }}>
                  <Typography variant="h4" color="primary" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <IconCalendarEvent size={20} /> Sandwich & Weekend Rules
                  </Typography>
                  <Divider sx={{ my: 1.5 }} />
                  <Stack spacing={2.5}>
                    <FormControlLabel
                      control={
                        <Switch
                          checked={settings.sandwichLeaveEnabled === 'YES'}
                          onChange={handleSwitchChange('sandwichLeaveEnabled')}
                          color="primary"
                        />
                      }
                      label={
                        <Box>
                          <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>Sandwich Leave Rule</Typography>
                          <Typography variant="caption" color="text.secondary">If enabled, weekends and holidays falling between leave days are counted as leave days</Typography>
                        </Box>
                      }
                    />
                  </Stack>
                </Card>
              </Grid>
            </Grid>
          </Box>

          {/* PANEL 2: PERMISSION POLICY */}
          <Box id="hr-permission">
            <Typography variant="h4" color="primary" sx={{ fontWeight: 800, mb: 1.5 }}>
              2. Permission Policy & Duration Limits
            </Typography>
            <Grid container spacing={3}>
              <Grid item xs={12}>
                <Alert severity="info" icon={<IconInfoCircle />}>
                  Permission applications are allowed for present and future dates by default, and follow the standard 3-day backdated limit (further past dates require ADD1 permission).
                </Alert>
              </Grid>
              <Grid item xs={12} md={6}>
                <Card variant="outlined" sx={{ p: 2, height: '100%' }}>
                  <Typography variant="h4" color="primary" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <IconClock size={20} /> Duration & Monthly Limits
                  </Typography>
                  <Divider sx={{ my: 1.5 }} />
                  <Stack spacing={2.5}>
                    <TextField
                      label="Max Permission Requests Per Month"
                      type="number"
                      value={settings.permissionMaxRequestsPerMonth}
                      onChange={handleNumberChange('permissionMaxRequestsPerMonth')}
                      fullWidth
                      helperText="Maximum permission applications allowed per month (Default: 2)"
                    />

                    <TextField
                      label="Max Minutes Allowed Per Permission Request"
                      type="number"
                      value={settings.permissionMaxMinutesPerRequest}
                      onChange={handleNumberChange('permissionMaxMinutesPerRequest')}
                      fullWidth
                      helperText="Single request duration cap in minutes (Default: 60)"
                    />

                    <TextField
                      label="Max Total Permission Minutes Per Month"
                      type="number"
                      value={settings.permissionMaxTotalMinutesPerMonth}
                      onChange={handleNumberChange('permissionMaxTotalMinutesPerMonth')}
                      fullWidth
                      helperText="Cumulative monthly permission duration cap in minutes (Default: 120)"
                    />
                  </Stack>
                </Card>
              </Grid>
            </Grid>
          </Box>

          {/* PANEL 3: ATTENDANCE & LOM POLICY */}
          <Box id="hr-lom">
            <Typography variant="h4" color="primary" sx={{ fontWeight: 800, mb: 1.5 }}>
              3. Attendance & Loss of Minutes (LOM) Policy
            </Typography>
            <Grid container spacing={3}>
              <Grid item xs={12}>
                <Alert severity="info" icon={<IconInfoCircle />}>
                  Configure Loss of Minutes (LOM) grace period, late arrival thresholds, and permission waiving rules.
                </Alert>
              </Grid>
              <Grid item xs={12} md={6}>
                <Card variant="outlined" sx={{ p: 2, height: '100%' }}>
                  <Typography variant="h4" color="primary" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <IconClock size={20} /> LOM Grace & Waive Rules
                  </Typography>
                  <Divider sx={{ my: 1.5 }} />
                  <Stack spacing={2.5}>
                    <TextField
                      label="LOM Grace Period (Minutes)"
                      type="number"
                      value={settings.lomGraceMinutes}
                      onChange={handleNumberChange('lomGraceMinutes')}
                      fullWidth
                      helperText="Allowed arrival grace time in minutes before LOM calculation starts (Default: 15)"
                    />
                  </Stack>
                </Card>
              </Grid>

              <Grid item xs={12} md={6}>
                <Card variant="outlined" sx={{ p: 2, height: '100%' }}>
                  <Typography variant="h4" color="primary" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <IconClock size={20} /> Deduction Rates & Thresholds
                  </Typography>
                  <Divider sx={{ my: 1.5 }} />
                  <Stack spacing={2.5}>
                    <TextField
                      label="LOM Deduction Multiplier / Factor"
                      type="number"
                      inputProps={{ step: '0.1' }}
                      value={settings.lomDeductionFactor}
                      onChange={handleNumberChange('lomDeductionFactor')}
                      fullWidth
                      helperText="Factor applied to LOM minutes for salary deduction (Default: 1.00)"
                    />
                  </Stack>
                </Card>
              </Grid>
            </Grid>
          </Box>

          {/* PANEL 4: OVERTIME POLICY */}
          <Box id="hr-ot">
            <Typography variant="h4" color="primary" sx={{ fontWeight: 800, mb: 1.5 }}>
              4. Overtime (OT) Policy Rules
            </Typography>
            <Grid container spacing={3}>
              <Grid item xs={12}>
                <Alert severity="info" icon={<IconInfoCircle />}>
                  Configure Overtime (OT) rounding, minimum thresholds, and multiplier settings.
                </Alert>
              </Grid>
              <Grid item xs={12} md={6}>
                <Card variant="outlined" sx={{ p: 2, height: '100%' }}>
                  <Typography variant="h4" color="primary" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <IconFingerprint size={20} /> Overtime (OT) Rules
                  </Typography>
                  <Divider sx={{ my: 1.5 }} />
                  <Stack spacing={2.5}>
                    <TextField
                      label="OT Calculation Rounding Interval (Minutes)"
                      type="number"
                      value={settings.otCalculationIntervalMinutes}
                      onChange={handleNumberChange('otCalculationIntervalMinutes')}
                      fullWidth
                      helperText="Overtime duration rounding interval (Default: 30 minutes)"
                    />

                    <TextField
                      label="Minimum OT Minutes Required"
                      type="number"
                      value={settings.otMinMinutesRequired}
                      onChange={handleNumberChange('otMinMinutesRequired')}
                      fullWidth
                      helperText="Minimum OT minutes required before OT is credited (Default: 60 minutes)"
                    />

                    <TextField
                      label="Overtime Rate Factorial / Multiplier"
                      type="number"
                      inputProps={{ step: '0.1' }}
                      value={settings.otFactorial}
                      onChange={handleNumberChange('otFactorial')}
                      fullWidth
                      helperText="OT hourly rate multiplier (e.g. 1.50 for 1.5x pay)"
                    />
                  </Stack>
                </Card>
              </Grid>
            </Grid>
          </Box>

          {/* PANEL 5: PAYROLL & SALARY DEFAULTS */}
          <Box id="hr-payroll">
            <Typography variant="h4" color="primary" sx={{ fontWeight: 800, mb: 1.5 }}>
              5. Payroll & Salary Defaults
            </Typography>
            <Grid container spacing={3}>
              <Grid item xs={12}>
                <Alert severity="info" icon={<IconInfoCircle />}>
                  Configure default statutory component toggles, payslip generation dates, and salary calculation base days.
                </Alert>
              </Grid>
              <Grid item xs={12} md={6}>
                <Card variant="outlined" sx={{ p: 2, height: '100%' }}>
                  <Typography variant="h4" color="primary" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <IconCurrencyRupee size={20} /> Statutory Defaults
                  </Typography>
                  <Divider sx={{ my: 1.5 }} />
                  <Stack spacing={2}>
                    <FormControlLabel
                      control={
                        <Switch
                          checked={settings.defaultPfEnabled === 'YES'}
                          onChange={handleSwitchChange('defaultPfEnabled')}
                          color="primary"
                        />
                      }
                      label={
                        <Box>
                          <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>Provident Fund (PF) Default Enabled</Typography>
                          <Typography variant="caption" color="text.secondary">Default PF deduction setting for new employees</Typography>
                        </Box>
                      }
                    />

                    <FormControlLabel
                      control={
                        <Switch
                          checked={settings.defaultEsiEnabled === 'YES'}
                          onChange={handleSwitchChange('defaultEsiEnabled')}
                          color="primary"
                        />
                      }
                      label={
                        <Box>
                          <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>Employee State Insurance (ESI) Default Enabled</Typography>
                          <Typography variant="caption" color="text.secondary">Default ESI deduction setting for new employees</Typography>
                        </Box>
                      }
                    />

                    <FormControlLabel
                      control={
                        <Switch
                          checked={settings.defaultProfessionalTaxEnabled === 'YES'}
                          onChange={handleSwitchChange('defaultProfessionalTaxEnabled')}
                          color="primary"
                        />
                      }
                      label={
                        <Box>
                          <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>Professional Tax (PT) Default Enabled</Typography>
                          <Typography variant="caption" color="text.secondary">Default Professional Tax deduction setting</Typography>
                        </Box>
                      }
                    />

                    <FormControlLabel
                      control={
                        <Switch
                          checked={settings.defaultLtaEligible === 'YES'}
                          onChange={handleSwitchChange('defaultLtaEligible')}
                          color="primary"
                        />
                      }
                      label={
                        <Box>
                          <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>LTA Eligibility Default</Typography>
                          <Typography variant="caption" color="text.secondary">Default Leave Travel Allowance eligibility setting</Typography>
                        </Box>
                      }
                    />
                  </Stack>
                </Card>
              </Grid>

              <Grid item xs={12} md={6}>
                <Card variant="outlined" sx={{ p: 2, height: '100%' }}>
                  <Typography variant="h4" color="primary" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <IconCurrencyRupee size={20} /> Payroll Base & Cutoff
                  </Typography>
                  <Divider sx={{ my: 1.5 }} />
                  <Stack spacing={2.5}>
                    <TextField
                      label="Monthly Payslip Auto-Generation Cutoff Day"
                      type="number"
                      value={settings.payslipAutoGenerateDay}
                      onChange={handleNumberChange('payslipAutoGenerateDay')}
                      fullWidth
                      helperText="Day of the month for automated monthly payslip generation (Default: 1)"
                    />

                    <TextField
                      label="Monthly Salary Calculation Base Days"
                      type="number"
                      value={settings.salaryCalculationBaseDays}
                      onChange={handleNumberChange('salaryCalculationBaseDays')}
                      fullWidth
                      helperText="Standard base days used for daily wage calculations (Default: 30)"
                    />
                  </Stack>
                </Card>
              </Grid>
            </Grid>
          </Box>
        </Stack>
      </Box>
    </MainCard>
  );
}
