package com.autonoma.erp.model.admin;

import com.autonoma.erp.util.SecurityUtils;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

@Entity
@Table(name = "AD_USER_CREDENTIAL")
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class UserCredential {
    @Id
    @Column(name = "USER_ID", columnDefinition = "NVARCHAR(50)")
    private String userId;

    @Column(name = "EMP_ID")
    private Long empId;

    @Column(name = "PASSWORD", nullable = false, columnDefinition = "NVARCHAR(255)")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    @Column(name = "CREATED_BY", length = 50)
    private String createdBy;

    @Column(name = "CREATED_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdDate;

    @Column(name = "UPDATED_BY", length = 50)
    private String updatedBy;

    @Column(name = "UPDATED_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedDate;

    @Column(name = "STATUS")
    private Integer status;

    public Integer getIsActive() { return status; }
    public void setIsActive(boolean active) { this.status = active ? 1 : 0; }

    @Column(name = "TENANT_ID", length = 50)
    private String tenantId;

    public String getTenantId() { return tenantId; }
    public void setTenantId(String tenantId) { this.tenantId = tenantId; }

    @Column(name = "USER_LEVEL")
    private Integer userLevel = 0;

    @Column(name = "IMG_NAME", columnDefinition = "NVARCHAR(255)")
    private String imgName;


    @Column(name = "FACE_IMAGE", columnDefinition = "NVARCHAR(MAX)")
    private String faceImage;

    @Column(name = "AUTH_METHOD", columnDefinition = "NVARCHAR(50)")
    private String authMethod = "PASSWORD";

    @Column(name = "FACE_DESCRIPTOR", columnDefinition = "NVARCHAR(MAX)")
    private String faceDescriptor;

    @Column(name = "FACE_EMBEDDINGS", columnDefinition = "NVARCHAR(MAX)")
    private String faceEmbeddings;

    /**
     * Tracks the face-api.js model version used during enrollment.
     * Null or 'LEGACY' = enrolled before quality hardening (pre-V1209).
     * 'FACE_API_V1' = enrolled after security hardening.
     * This enables graceful re-enrollment prompts and prevents mixing
     * embeddings generated by different model versions.
     */
    @Column(name = "FACE_TEMPLATE_VERSION", columnDefinition = "NVARCHAR(20)")
    private String faceTemplateVersion;

    @Column(name = "AUTO_LOGOUT_ON_FACE_ABSENCE")
    private Integer autoLogoutOnFaceAbsence = 0;

    @Column(name = "IS_ACTIVE")
    private Boolean isActive = true;

    @PrePersist
    protected void onCreate() {
        String currentUserId = null;
        try { currentUserId = com.autonoma.erp.util.SecurityUtils.getCurrentUserId(); } catch (Exception e) {}
        if (org.springframework.web.context.request.RequestContextHolder.getRequestAttributes() != null) {
            if (currentUserId == null || currentUserId.trim().isEmpty()) {
                throw new RuntimeException("Session expired or user not logged in. Please relogin.");
            }
            this.createdBy = currentUserId;
        }
        this.updatedBy = null;

        createdDate = new Date();
        if (isActive == null) isActive = true;
    }

    @PreUpdate
    protected void onUpdate() {
        String currentUserId = null;
        try { currentUserId = com.autonoma.erp.util.SecurityUtils.getCurrentUserId(); } catch (Exception e) {}
        if (org.springframework.web.context.request.RequestContextHolder.getRequestAttributes() != null) {
            if (currentUserId == null || currentUserId.trim().isEmpty()) {
                throw new RuntimeException("Session expired or user not logged in. Please relogin.");
            }
            this.updatedBy = currentUserId;
        }
        updatedDate = new Date();
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Long getEmpId() {
        return empId;
    }

    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getImgName() {
        return imgName;
    }

    public void setImgName(String imgName) {
        this.imgName = imgName;
    }

    public Integer getUserLevel() {
        return userLevel;
    }

    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    public String getFaceImage() {
        return faceImage;
    }

    public void setFaceImage(String faceImage) {
        this.faceImage = faceImage;
    }

    public String getAuthMethod() {
        return authMethod;
    }

    public void setAuthMethod(String authMethod) {
        this.authMethod = authMethod;
    }

    public String getFaceDescriptor() {
        return faceDescriptor;
    }

    public void setFaceDescriptor(String faceDescriptor) {
        this.faceDescriptor = faceDescriptor;
    }

    public String getFaceEmbeddings() {
        return faceEmbeddings;
    }

    public void setFaceEmbeddings(String faceEmbeddings) {
        this.faceEmbeddings = faceEmbeddings;
    }

    public String getFaceTemplateVersion() {
        return faceTemplateVersion;
    }

    public void setFaceTemplateVersion(String faceTemplateVersion) {
        this.faceTemplateVersion = faceTemplateVersion;
    }

    public Integer getAutoLogoutOnFaceAbsence() {
        return autoLogoutOnFaceAbsence;
    }

    public void setAutoLogoutOnFaceAbsence(Integer autoLogoutOnFaceAbsence) {
        this.autoLogoutOnFaceAbsence = autoLogoutOnFaceAbsence;
    }
}
