package com.autonoma.erp.modules.hr.settings.service;

import com.autonoma.erp.modules.hr.settings.entity.HrSettingMaster;
import com.autonoma.erp.modules.hr.settings.repository.HrSettingMasterRepository;
import com.autonoma.erp.service.admin.AppPreferenceService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class HrSettingsServiceTest {

    @Mock
    private HrSettingMasterRepository repository;

    @Mock
    private AppPreferenceService appPreferenceService;

    @InjectMocks
    private HrSettingsService hrSettingsService;

    private HrSettingMaster defaultSetting;

    @BeforeEach
    void setUp() {
        defaultSetting = new HrSettingMaster();
        defaultSetting.setId(1L);
        defaultSetting.setSandwichLeaveEnabled("YES");



        defaultSetting.setPermissionMaxRequestsPerMonth(2);
        defaultSetting.setPermissionMaxMinutesPerRequest(60);
        defaultSetting.setPermissionMaxTotalMinutesPerMonth(120);

        defaultSetting.setLomGraceMinutes(15);
        defaultSetting.setLomDeductionFactor(new BigDecimal("1.00"));

        defaultSetting.setOtCalculationIntervalMinutes(30);
        defaultSetting.setOtMinMinutesRequired(60);
        defaultSetting.setOtFactorial(new BigDecimal("1.50"));
        defaultSetting.setEsslSyncIntervalMinutes(15);

        defaultSetting.setDefaultPfEnabled("YES");
        defaultSetting.setDefaultEsiEnabled("YES");
        defaultSetting.setDefaultProfessionalTaxEnabled("YES");
        defaultSetting.setDefaultLtaEligible("NO");
        defaultSetting.setPayslipAutoGenerateDay(1);
        defaultSetting.setSalaryCalculationBaseDays(30);
    }

    @Test
    @DisplayName("Should return existing HR Settings from repository when present")
    void testGetSettings_Existing() {
        when(repository.findFirstByOrderByIdAsc()).thenReturn(Optional.of(defaultSetting));

        HrSettingMaster result = hrSettingsService.getSettings();

        assertNotNull(result);
        assertEquals(1L, result.getId());
        assertEquals("YES", result.getSandwichLeaveEnabled());
        verify(repository, times(1)).findFirstByOrderByIdAsc();
    }

    @Test
    @DisplayName("Should create and return default HR Settings when repository is empty")
    void testGetSettings_CreateDefaultWhenEmpty() {
        when(repository.findFirstByOrderByIdAsc()).thenReturn(Optional.empty());
        when(repository.save(any(HrSettingMaster.class))).thenAnswer(invocation -> invocation.getArgument(0));

        HrSettingMaster result = hrSettingsService.getSettings();

        assertNotNull(result);
        assertEquals("YES", result.getSandwichLeaveEnabled());
        assertEquals("SYSTEM", result.getCreatedBy());
        verify(repository, times(1)).save(any(HrSettingMaster.class));
    }

    @Test
    @DisplayName("1. Category Test: Leave Apply Policy")
    void testLeaveApplyPolicyCategory() {
        when(repository.findFirstByOrderByIdAsc()).thenReturn(Optional.of(defaultSetting));
        when(repository.save(any(HrSettingMaster.class))).thenAnswer(i -> i.getArgument(0));

        defaultSetting.setSandwichLeaveEnabled("NO");

        HrSettingMaster saved = hrSettingsService.saveSettings(defaultSetting);

        assertEquals("NO", saved.getSandwichLeaveEnabled());
    }



    @Test
    @DisplayName("3. Category Test: Permission Apply Policy")
    void testPermissionApplyPolicyCategory() {
        when(repository.findFirstByOrderByIdAsc()).thenReturn(Optional.of(defaultSetting));
        when(repository.save(any(HrSettingMaster.class))).thenAnswer(i -> i.getArgument(0));

        defaultSetting.setPermissionMaxRequestsPerMonth(3);
        defaultSetting.setPermissionMaxMinutesPerRequest(90);
        defaultSetting.setPermissionMaxTotalMinutesPerMonth(180);

        HrSettingMaster saved = hrSettingsService.saveSettings(defaultSetting);

        assertEquals(3, saved.getPermissionMaxRequestsPerMonth());
        assertEquals(90, saved.getPermissionMaxMinutesPerRequest());
        assertEquals(180, saved.getPermissionMaxTotalMinutesPerMonth());
    }

    @Test
    @DisplayName("4. Category Test: Attendance & LOM Policy")
    void testAttendanceLomPolicyCategory() {
        when(repository.findFirstByOrderByIdAsc()).thenReturn(Optional.of(defaultSetting));
        when(repository.save(any(HrSettingMaster.class))).thenAnswer(i -> i.getArgument(0));

        defaultSetting.setLomGraceMinutes(20);
        defaultSetting.setLomDeductionFactor(new BigDecimal("1.25"));

        HrSettingMaster saved = hrSettingsService.saveSettings(defaultSetting);

        assertEquals(20, saved.getLomGraceMinutes());
        assertEquals(new BigDecimal("1.25"), saved.getLomDeductionFactor());
    }

    @Test
    @DisplayName("5. Category Test: Overtime & Biometric eSSL Policy")
    void testOvertimeEsslPolicyCategory() {
        when(repository.findFirstByOrderByIdAsc()).thenReturn(Optional.of(defaultSetting));
        when(repository.save(any(HrSettingMaster.class))).thenAnswer(i -> i.getArgument(0));

        defaultSetting.setOtCalculationIntervalMinutes(15);
        defaultSetting.setOtMinMinutesRequired(45);
        defaultSetting.setOtFactorial(new BigDecimal("2.00"));
        defaultSetting.setEsslSyncIntervalMinutes(10);

        HrSettingMaster saved = hrSettingsService.saveSettings(defaultSetting);

        assertEquals(15, saved.getOtCalculationIntervalMinutes());
        assertEquals(45, saved.getOtMinMinutesRequired());
        assertEquals(new BigDecimal("2.00"), saved.getOtFactorial());
        assertEquals(10, saved.getEsslSyncIntervalMinutes());
    }

    @Test
    @DisplayName("6. Category Test: Payroll & Salary Components Policy")
    void testPayrollSalaryPolicyCategory() {
        when(repository.findFirstByOrderByIdAsc()).thenReturn(Optional.of(defaultSetting));
        when(repository.save(any(HrSettingMaster.class))).thenAnswer(i -> i.getArgument(0));

        defaultSetting.setDefaultPfEnabled("NO");
        defaultSetting.setDefaultEsiEnabled("NO");
        defaultSetting.setDefaultProfessionalTaxEnabled("NO");
        defaultSetting.setDefaultLtaEligible("YES");
        defaultSetting.setPayslipAutoGenerateDay(5);
        defaultSetting.setSalaryCalculationBaseDays(26);

        HrSettingMaster saved = hrSettingsService.saveSettings(defaultSetting);

        assertEquals("NO", saved.getDefaultPfEnabled());
        assertEquals("NO", saved.getDefaultEsiEnabled());
        assertEquals("NO", saved.getDefaultProfessionalTaxEnabled());
        assertEquals("YES", saved.getDefaultLtaEligible());
        assertEquals(5, saved.getPayslipAutoGenerateDay());
        assertEquals(26, saved.getSalaryCalculationBaseDays());
    }
}
