package com.autonoma.erp.modules.hr.asset.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Entity
@Table(name = "ASSET_TYPE")
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class AssetType {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private Long id;

    @Column(name = "GROUP_ID", nullable = false)
    private Long groupId;

    @Column(name = "TYPE", nullable = false, length = 100, unique = true)
    private String type;

    @Column(name = "IS_AUTO_GENERATED_CODE")
    private Boolean isAutoGeneratedCode = false;

    @Column(name = "TYPE_PREFIX", length = 10)
    private String typePrefix;

    @Column(name = "STATUS")
    private Boolean status = true;

    @Column(name = "CREATED_BY", nullable = false, length = 50)
    private String createdBy;

    @Column(name = "CREATED_DATE", updatable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdDate;

    @Column(name = "UPDATED_BY", length = 50)
    private String updatedBy;

    @Column(name = "UPDATED_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedDate;

    // Optional mapping if you want to join explicitly
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GROUP_ID", referencedColumnName = "ID", insertable = false, updatable = false)
    private AssetGroup assetGroup;

    @PrePersist
    protected void onCreate() {
        if (Boolean.TRUE.equals(isAutoGeneratedCode) && (typePrefix == null || typePrefix.trim().isEmpty())) {
            throw new IllegalArgumentException("Type prefix is mandatory when auto-generated code is enabled");
        }
        String currentUserId = null;
        try {
            currentUserId = com.autonoma.erp.util.SecurityUtils.getCurrentUserId();
        } catch (Exception e) {}
        this.createdBy = (currentUserId != null) ? currentUserId : "System";
        this.createdDate = new Date();
    }

    @PreUpdate
    protected void onUpdate() {
        if (Boolean.TRUE.equals(isAutoGeneratedCode) && (typePrefix == null || typePrefix.trim().isEmpty())) {
            throw new IllegalArgumentException("Type prefix is mandatory when auto-generated code is enabled");
        }
        String currentUserId = null;
        try {
            currentUserId = com.autonoma.erp.util.SecurityUtils.getCurrentUserId();
        } catch (Exception e) {}
        this.updatedBy = currentUserId;
        this.updatedDate = new Date();
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public Long getGroupId() { return groupId; }
    public void setGroupId(Long groupId) { this.groupId = groupId; }
    public String getType() { return type; }
    public void setType(String type) { this.type = type; }
    public Boolean getIsAutoGeneratedCode() { return isAutoGeneratedCode; }
    public void setIsAutoGeneratedCode(Boolean isAutoGeneratedCode) { this.isAutoGeneratedCode = isAutoGeneratedCode; }
    public String getTypePrefix() { return typePrefix; }
    public void setTypePrefix(String typePrefix) { this.typePrefix = typePrefix; }
    public Boolean getStatus() { return status; }
    public void setStatus(Boolean status) { this.status = status; }
    public AssetGroup getAssetGroup() { return assetGroup; }
    public void setAssetGroup(AssetGroup assetGroup) { this.assetGroup = assetGroup; }
}
