package com.autonoma.erp.modules.hr.settings.service;

import com.autonoma.erp.modules.hr.settings.entity.HrSettingMaster;
import com.autonoma.erp.modules.hr.settings.repository.HrSettingMasterRepository;
import com.autonoma.erp.service.admin.AppPreferenceService;
import com.autonoma.erp.util.SecurityUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;

@Service
public class HrSettingsService {

    @Autowired
    private HrSettingMasterRepository repository;

    @Autowired(required = false)
    private AppPreferenceService appPreferenceService;

    public HrSettingMaster getSettings() {
        return repository.findFirstByOrderByIdAsc().orElseGet(this::createDefaultSettings);
    }

    private HrSettingMaster createDefaultSettings() {
        HrSettingMaster settings = new HrSettingMaster();
        settings.setCreatedBy("SYSTEM");
        settings.setCreatedDate(new Date());
        return repository.save(settings);
    }

    @Transactional
    public HrSettingMaster saveSettings(HrSettingMaster input) {
        HrSettingMaster existing = getSettings();

        // Category 1: Leave Apply Policy
        existing.setSandwichLeaveEnabled(input.getSandwichLeaveEnabled());



        // Category 3: Permission Apply Policy
        existing.setPermissionMaxRequestsPerMonth(input.getPermissionMaxRequestsPerMonth());
        existing.setPermissionMaxMinutesPerRequest(input.getPermissionMaxMinutesPerRequest());
        existing.setPermissionMaxTotalMinutesPerMonth(input.getPermissionMaxTotalMinutesPerMonth());

        // Category 4: Attendance & LOM Policy
        existing.setLomGraceMinutes(input.getLomGraceMinutes());
        existing.setLomDeductionFactor(input.getLomDeductionFactor());
        existing.setLopMode(input.getLopMode());
        existing.setLopIsFixed(input.getLopIsFixed());
        existing.setLopFixedAmount(input.getLopFixedAmount());
        existing.setLopFormula(input.getLopFormula());

        // Category 5: Overtime & Biometric eSSL Policy
        existing.setOtCalculationIntervalMinutes(input.getOtCalculationIntervalMinutes());
        existing.setOtMinMinutesRequired(input.getOtMinMinutesRequired());
        existing.setOtFactorial(input.getOtFactorial());
        existing.setOtMode(input.getOtMode());
        existing.setOtIsFixed(input.getOtIsFixed());
        existing.setOtFixedAmount(input.getOtFixedAmount());
        existing.setOtFormula(input.getOtFormula());
        existing.setEsslSyncIntervalMinutes(input.getEsslSyncIntervalMinutes());

        // Category 6: Payroll & Salary Components Policy
        existing.setDefaultPfEnabled(input.getDefaultPfEnabled());
        existing.setDefaultEsiEnabled(input.getDefaultEsiEnabled());
        existing.setDefaultProfessionalTaxEnabled(input.getDefaultProfessionalTaxEnabled());
        existing.setDefaultLtaEligible(input.getDefaultLtaEligible());
        existing.setPayslipAutoGenerateDay(input.getPayslipAutoGenerateDay());
        existing.setSalaryCalculationBaseDays(input.getSalaryCalculationBaseDays());

        existing.setUpdatedDate(new Date());
        try {
            existing.setUpdatedBy(SecurityUtils.getCurrentUserId());
        } catch (Exception e) {
            existing.setUpdatedBy("SYSTEM");
        }

        HrSettingMaster saved = repository.save(existing);

        // Sync legacy key-value pairs in AppPreference if bean present
        if (appPreferenceService != null) {
            try {
                appPreferenceService.upsertByName("SANDWICH_LEAVE", saved.getSandwichLeaveEnabled(), "Sandwich Leave Rule Enabled", "HRA");
                


                appPreferenceService.upsertByName("LOM_GRACE_MINUTES", String.valueOf(saved.getLomGraceMinutes()), "LOM Grace Minutes", "HRA");
                appPreferenceService.upsertByName("OT_CALCULATION_INTERVAL", String.valueOf(saved.getOtCalculationIntervalMinutes()), "OT Calculation Interval", "HRA");
                appPreferenceService.upsertByName("OT_MIN_MINUTES", String.valueOf(saved.getOtMinMinutesRequired()), "OT Min Minutes", "HRA");
                appPreferenceService.upsertByName("ESSL_SYNC_INTERVAL_MINUTES", String.valueOf(saved.getEsslSyncIntervalMinutes()), "ESSL Sync Interval Mins", "HRA");
            } catch (Exception e) {
                // Log and swallow preference sync errors so primary entity update succeeds
                org.slf4j.LoggerFactory.getLogger(HrSettingsService.class).warn("Failed to sync legacy AppPreference keys: {}", e.getMessage());
            }
        }

        return saved;
    }
}
