export const WORKFLOW_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  PENDING_APPROVAL: 'PENDING APPROVAL',
  VERIFIED: 'VERIFIED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

export const PENDING_WORKFLOW_STATUSES = [
  WORKFLOW_STATUS.PENDING,
  WORKFLOW_STATUS.PENDING_APPROVAL
];

export const VERIFIED_WORKFLOW_STATUSES = [
  WORKFLOW_STATUS.VERIFIED,
  WORKFLOW_STATUS.APPROVED
];

export const TERMINAL_WORKFLOW_STATUSES = [
  WORKFLOW_STATUS.VERIFIED,
  WORKFLOW_STATUS.APPROVED,
  WORKFLOW_STATUS.REJECTED
];
