import { format } from 'date-fns';
import { getCompanyImageUrl } from './upload-helper';

/**
 * Enterprise PDF Report Renderer
 * Converts a JSON template configuration into a printable HTML string.
 */

const defaultTemplate = {
  page: { size: 'A4', orientation: 'portrait', margin: 20 },
  blocks: [
    { type: 'companyHeader', visible: true },
    { type: 'documentTitle', visible: true },
    { type: 'documentDetails', visible: true },
    { type: 'table', visible: true },
    { type: 'summary', visible: true },
    { type: 'signature', visible: true },
    { type: 'footer', visible: true }
  ]
};

const applyStyle = (styleObj = {}) => {
  let css = '';
  if (styleObj.fontSize) css += `font-size: ${styleObj.fontSize}px;`;
  if (styleObj.fontWeight) css += `font-weight: ${styleObj.fontWeight};`;
  if (styleObj.fontFamily) css += `font-family: ${styleObj.fontFamily};`;
  if (styleObj.textColor) css += `color: ${styleObj.textColor};`;
  if (styleObj.background) css += `background-color: ${styleObj.background};`;
  if (styleObj.alignment) css += `text-align: ${styleObj.alignment};`;
  
  if (styleObj.padding) css += `padding: ${styleObj.padding};`;
  if (styleObj.margin) css += `margin: ${styleObj.margin};`;
  if (styleObj.border) css += `border: ${styleObj.border};`;
  if (styleObj.borderRadius) css += `border-radius: ${styleObj.borderRadius}px;`;
  return css;
};

export const renderTemplateToHtml = (config = defaultTemplate, data = [], companyProfile = {}, user = {}, metadata = {}) => {
  const { reportName, reportTitle, documentDetails, signatures, stampText, tableColumns } = metadata;
  
  let html = `<div style="font-family: ${config.page?.fontFamily || 'sans-serif'}; width: 100%; box-sizing: border-box; background-color: #fff; padding: ${config.page?.margin || 10}px;">`;
  
  // Watermark
  if (companyProfile.logoFileName && config.page?.watermark) {
    const logoUrl = getCompanyImageUrl(companyProfile.logoFileName);
    html += `<div style="position: fixed; top: 30%; left: 20%; right: 20%; bottom: 30%; background-image: url('${logoUrl}'); background-size: contain; background-repeat: no-repeat; background-position: center; opacity: 0.05; z-index: -1;"></div>`;
  }
  
  const blocks = config.blocks || [];
  
  blocks.filter(b => b.visible !== false).forEach(block => {
    const style = applyStyle(block.style);
    
    if (block.type === 'companyHeader') {
      const logoUrl = companyProfile.logoFileName ? getCompanyImageUrl(companyProfile.logoFileName) : '';
      const addressLine = [companyProfile.address, companyProfile.city, companyProfile.state, companyProfile.pincode].filter(Boolean).join(', ');
      
      const contactItems = [];
      if (companyProfile.mobileNo || companyProfile.phoneNo) contactItems.push(`Mob: ${companyProfile.mobileNo || companyProfile.phoneNo}`);
      if (companyProfile.emailId) contactItems.push(`Email: ${companyProfile.emailId}`);
      if (companyProfile.website) contactItems.push(`Web: ${companyProfile.website}`);
      const contactLine = contactItems.join(' | ');
      
      html += `
        <div style="display: flex; justify-content: space-between; margin-bottom: 5px; border-bottom: 3px solid ${block.style?.borderColor || '#2196f3'}; padding-bottom: 10px; width: 100%; box-sizing: border-box; ${style}">
          <div style="display: flex; align-items: center; gap: 15px;">
            ${logoUrl ? `<img src="${logoUrl}" style="max-height: 50px; max-width: 150px; object-fit: contain;" />` : ''}
            <div>
              <h1 style="color: ${block.style?.primaryColor || '#2196f3'}; margin: 0; font-size: 24px; font-weight: 900;">${companyProfile.companyName || 'Company'}</h1>
              <p style="margin: 2px 0 0 0; font-size: 10px; font-weight: 700; color: #666; text-transform: uppercase; letter-spacing: 1px;">${companyProfile.shortName || ''}</p>
              ${addressLine ? `<p style="margin: 4px 0 0 0; font-size: 9px; color: #555;">${addressLine}</p>` : ''}
              ${(companyProfile.gstIn || companyProfile.gstNo) ? `<p style="margin: 2px 0 0 0; font-size: 9px; color: #555;">GSTIN: ${companyProfile.gstIn || companyProfile.gstNo}</p>` : ''}
              ${contactLine ? `<p style="margin: 2px 0 0 0; font-size: 9px; color: #555;">${contactLine}</p>` : ''}
            </div>
          </div>
          <div style="text-align: right;">
            <p style="margin: 2px 0 0 0; font-size: 9px; color: #666;">Generated By: ${user?.name || 'System User'}</p>
            <p style="margin: 2px 0 0 0; font-size: 9px; color: #666;">Date: ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</p>
          </div>
        </div>
      `;
    }
    
    if (block.type === 'documentTitle') {
      html += `
        <div style="text-align: center; margin-top: 5px; margin-bottom: 15px; width: 100%; ${style}">
          <h2 style="margin: 0; font-size: ${block.style?.fontSize || 16}px; font-weight: 900; text-transform: uppercase; color: #333; letter-spacing: 1px;">
            <u>${reportName || 'Document'}</u>
          </h2>
        </div>
      `;
    }
    
    if (block.type === 'documentDetails') {
       const docDetailsHtml = documentDetails && documentDetails.length > 0 ? `
        <div style="display: flex; flex-wrap: wrap; gap: 10px; margin-top: 15px;">
          ${documentDetails.map(detail => `
            <div style="flex: ${detail.label.toLowerCase() === 'remarks' ? '1 1 100%' : '1'}; min-width: 150px; margin-bottom: 5px;">
              <p style="margin: 0; font-size: 8px; color: #666; font-weight: 700; text-transform: uppercase;">${detail.label}</p>
              <p style="margin: 2px 0 0 0; font-size: 10px; font-weight: 600; color: #111; word-wrap: break-word;">${detail.value || '-'}</p>
            </div>
          `).join('')}
        </div>
      ` : '';
      
      html += `
        <div style="margin-bottom: 15px; padding: 10px; background-color: #f8f9fa; border-radius: 4px; border-left: 4px solid ${block.style?.borderColor || '#2196f3'}; width: 100%; box-sizing: border-box; ${style}">
          <h4 style="margin: 0 0 ${documentDetails?.length ? '10px' : '0'} 0; font-size: 14px; font-weight: 800; color: ${block.style?.primaryColor || '#2196f3'};">${reportTitle || ''}</h4>
          ${docDetailsHtml}
        </div>
      `;
    }
    
    if (block.type === 'table') {
      const activeColumns = block.columns && block.columns.length > 0 
        ? block.columns.filter(c => c.visible !== false) 
        : tableColumns || [];
        
      const padding = activeColumns.length > 8 ? '4px 3px' : '6px 4px';
      const fontSizeHeader = activeColumns.length > 8 ? '8.5px' : '10px';
      const fontSizeCell = activeColumns.length > 8 ? '7.5px' : '9px';
      
      const tableHeaderHtml = activeColumns.map(col => `
        <th style="padding: ${padding}; text-align: ${col.alignment || 'left'}; font-size: ${fontSizeHeader}; font-weight: 700; background-color: ${block.style?.headerBackground || '#2196f3'}; color: ${block.style?.headerTextColor || 'white'}; border: 1px solid #ddd; text-transform: uppercase; word-break: break-word; white-space: normal;">
          ${col.label || col.id}
        </th>
      `).join('');

      const tableRowsHtml = data.map((row, idx) => `
        <tr style="background-color: ${idx % 2 === 0 ? 'transparent' : (block.style?.alternateRowColor || '#f9f9f9')};">
          ${activeColumns.map(col => `
            <td style="padding: ${padding}; font-size: ${fontSizeCell}; color: #333; border: 1px solid #ddd; word-break: break-word; white-space: normal; text-align: ${col.alignment || 'left'};">
              ${row[col.id] || '-'}
            </td>
          `).join('')}
        </tr>
      `).join('');

      html += `
        <div style="width: 100%; overflow: visible; box-sizing: border-box; ${style}">
          <table style="width: 100%; border-collapse: collapse; margin-bottom: 15px; table-layout: auto;">
            <thead>
              <tr>${tableHeaderHtml}</tr>
            </thead>
            <tbody>
              ${tableRowsHtml}
            </tbody>
          </table>
        </div>
      `;
    }
    
    if (block.type === 'signature') {
      const signaturesHtml = signatures && signatures.length > 0 ? `
        <div style="margin-top: auto; padding-top: 40px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-end; width: 100%; box-sizing: border-box; page-break-inside: avoid; position: relative;">
          ${signatures.map(sig => `
            <div style="text-align: center; width: 150px; position: relative; z-index: 2;">
               <p style="margin: 0; font-size: 10px; font-weight: bold; color: #333;">${sig.label}</p>
               <p style="margin: 40px 0 0 0; font-size: 10px; border-bottom: 1px solid #333; padding-bottom: 2px;">${sig.name || ''}</p>
            </div>
          `).join('')}
          ${stampText ? `
          <div style="position: absolute; left: 50%; bottom: 10px; transform: translateX(-50%) rotate(-15deg); text-align: center; opacity: 0.15; z-index: 1;">
              <p style="margin: 0; font-size: 42px; font-weight: 900; letter-spacing: 6px; color: ${stampText.toLowerCase() === 'approved' ? '#166534' : stampText.toLowerCase() === 'rejected' ? '#991b1b' : '#444'}; text-transform: uppercase; border: 4px solid; padding: 5px 15px; border-radius: 8px;">
                  ${stampText}
              </p>
          </div>
          ` : ''}
        </div>
      ` : '<div style="margin-top: auto;"></div>';
      
      html += `<div style="${style}">${signaturesHtml}</div>`;
    }
    
    if (block.type === 'footer') {
      html += `
        <div style="margin-top: 20px; padding-top: 10px; border-top: 1px solid #eee; text-align: left; font-size: 8px; color: #999; width: 100%; box-sizing: border-box; ${style}">
          Confidential Report | © ${new Date().getFullYear()} ${companyProfile.companyName || 'Company'}
        </div>
      `;
    }
    
    // Extensible for more blocks like Notes, Summary, etc.
  });
  
  html += `</div>`;
  return html;
};
