IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SALES_QUOTATION_FOLLOW_UP_LOG]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[SALES_QUOTATION_FOLLOW_UP_LOG] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [QUOTATION_ID] BIGINT NOT NULL,
        [CUSTOMER_ID] BIGINT NULL,
        [PART_ID] BIGINT NULL,
        [FOLLOW_MODE] NVARCHAR(50) NULL,
        [FOLLOW_TYPE] NVARCHAR(50) NULL,
        [COMMENTS] NVARCHAR(MAX) NULL,
        [FOLLOW_UP_DATE] DATETIME NULL,
        [ATTACHMENT_PATH] NVARCHAR(MAX) NULL,
        [STATUS] BIT CONSTRAINT [DF_SALES_QUOTATION_FOLLOW_UP_LOG_STATUS] DEFAULT ((1)) NULL,
        [CREATED_BY] NVARCHAR(50) NULL,
        [CREATED_DATE] DATETIME CONSTRAINT [DF_SALES_QUOTATION_FOLLOW_UP_LOG_CREATED_DATE] DEFAULT (GETDATE()) NULL,
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_SALES_QUOTATION_FOLLOW_UP_LOG] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [FK_SALES_QUOTATION_FOLLOW_UP_LOG_QUOTATION] FOREIGN KEY ([QUOTATION_ID]) REFERENCES [dbo].[SALES_QUOTATION_HEADER] ([ID])
    );
END
GO
