IF EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') 
    AND name = 'SECONDARY_HOST_ID'
)
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ALTER COLUMN SECONDARY_HOST_ID BIGINT NULL;
END
GO

IF EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE object_id = OBJECT_ID('QMS_MEETING_SCHEDULE') 
    AND name = 'TERTIARY_HOST_ID'
)
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE ALTER COLUMN TERTIARY_HOST_ID BIGINT NULL;
END
GO
