ALTER TABLE PP_QUALITY_INSPECTION_TRANS ADD TEST_CERTIFICATE VARCHAR(100);
ALTER TABLE PP_QUALITY_INSPECTION_TRANS ADD TC_SOURCE VARCHAR(100);
ALTER TABLE PP_QUALITY_INSPECTION_TRANS ADD HEAT_NO VARCHAR(100);
ALTER TABLE PP_QUALITY_INSPECTION_TRANS ADD INSPECTED_BY VARCHAR(100);
