-- Migration: V1160.0 - Drop Unique Constraints on QMC_INSPECTION_SPECIFICATION
-- Date: 20260822
-- Description: Drops the unique constraints on ITEM_ID and SPECIFICATION_NAME

DECLARE @ConstraintName NVARCHAR(200);

-- Drop UNIQUE constraint on ITEM_ID
SELECT @ConstraintName = tc.CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
WHERE tc.TABLE_NAME = 'QMC_INSPECTION_SPECIFICATION' 
  AND ccu.COLUMN_NAME = 'ITEM_ID' 
  AND tc.CONSTRAINT_TYPE = 'UNIQUE';

IF @ConstraintName IS NOT NULL
BEGIN
    EXEC('ALTER TABLE QMC_INSPECTION_SPECIFICATION DROP CONSTRAINT ' + @ConstraintName);
END

-- Drop UNIQUE constraint on SPECIFICATION_NAME
SELECT @ConstraintName = tc.CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
WHERE tc.TABLE_NAME = 'QMC_INSPECTION_SPECIFICATION' 
  AND ccu.COLUMN_NAME = 'SPECIFICATION_NAME' 
  AND tc.CONSTRAINT_TYPE = 'UNIQUE';

IF @ConstraintName IS NOT NULL
BEGIN
    EXEC('ALTER TABLE QMC_INSPECTION_SPECIFICATION DROP CONSTRAINT ' + @ConstraintName);
END
GO
