-- Drop existing tables if they exist to recreate strictly based on schema
IF OBJECT_ID('SALES_ENQUIRY_DETAIL', 'U') IS NOT NULL DROP TABLE SALES_ENQUIRY_DETAIL;
IF OBJECT_ID('SALES_ENQUIRY_HEADER', 'U') IS NOT NULL DROP TABLE SALES_ENQUIRY_HEADER;
IF OBJECT_ID('SALES_QUOTATION_DETAIL', 'U') IS NOT NULL DROP TABLE SALES_QUOTATION_DETAIL;
IF OBJECT_ID('SALES_QUOTATION_HEADER', 'U') IS NOT NULL DROP TABLE SALES_QUOTATION_HEADER;

-- Create SALES_ENQUIRY_HEADER
CREATE TABLE SALES_ENQUIRY_HEADER (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ENQUIRY_NO NVARCHAR(50),
    ENQUIRY_DATE DATETIME,
    RFQ_MODE NVARCHAR(50),
    CUSTOMER_ID BIGINT,
    TARGET_DATE DATETIME,
    SAL_TYPE NVARCHAR(100),
    SOURCE NVARCHAR(100),
    PRIORITY NVARCHAR(50),
    REMARKS NVARCHAR(MAX),
    ATTACHMENT_PATH NVARCHAR(MAX),
    STATUS BIT,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME
);

-- Create SALES_ENQUIRY_DETAIL
CREATE TABLE SALES_ENQUIRY_DETAIL (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ENQUIRY_ID BIGINT,
    PART_NO_ID BIGINT,
    REQ_QTY NUMERIC(12,2),
    COMMERCIALLY_FEASIBLE NVARCHAR(50),
    TECHNICALLY_FEASIBLE NVARCHAR(50),
    ASSIGN_TO NVARCHAR(200),
    STATUS BIT,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    CONSTRAINT FK_ENQUIRY_DETAIL_HEADER FOREIGN KEY (ENQUIRY_ID) REFERENCES SALES_ENQUIRY_HEADER(ID) ON DELETE CASCADE
);

-- Create SALES_QUOTATION_HEADER
CREATE TABLE SALES_QUOTATION_HEADER (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    QUOTATION_NO NVARCHAR(50),
    QUOTATION_DATE DATETIME,
    CUSTOMER_ID BIGINT,
    RFQ_MODE NVARCHAR(50),
    REQUEST_DATE DATETIME,
    REMARKS NVARCHAR(MAX),
    QUOTATION_STATUS NVARCHAR(50),
    ATTACHMENT_PATH NVARCHAR(MAX),
    STATUS BIT,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME
);

-- Create SALES_QUOTATION_DETAIL
CREATE TABLE SALES_QUOTATION_DETAIL (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    QUOTATION_ID BIGINT,
    PART_NO_ID BIGINT,
    QTY NUMERIC(12,2),
    AMOUNT NUMERIC(12,2),
    DIS_TYPE NVARCHAR(20),
    DISCOUNT NUMERIC(12,2),
    FRIGHT_AMOUNT NUMERIC(12,2),
    FRIGHT_PER NUMERIC(12,2),
    TOTAL_VALUE NUMERIC(12,2),
    CAPACITY NUMERIC(12,2),
    ADDITIONAL_COMMENTS NVARCHAR(MAX),
    WARRENTY NVARCHAR(50),
    LEAD_TIME_TYPE NVARCHAR(50),
    LEAD_TIME_DAYS BIGINT,
    REMARKS NVARCHAR(MAX),
    APPROVAL_STATUS BIT,
    STATUS BIT,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    CONSTRAINT FK_QUOTATION_DETAIL_HEADER FOREIGN KEY (QUOTATION_ID) REFERENCES SALES_QUOTATION_HEADER(ID) ON DELETE CASCADE
);
