-- Create SALES_ATTACHMENTS_PATH table matching QMS_ATTACHMENTS_PATH structure
CREATE TABLE SALES_ATTACHMENTS_PATH (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    PAGE_CODE NVARCHAR(100) NOT NULL,
    REF_ID BIGINT NOT NULL,
    DOC_TYPE NVARCHAR(50),
    PATH NVARCHAR(500) NOT NULL,
    FILE_NAME NVARCHAR(255) NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(50) NOT NULL,
    UPDATED_DATE DATETIME
);

-- Drop ATTACHMENT_PATH column from SALES_ENQUIRY_HEADER
ALTER TABLE SALES_ENQUIRY_HEADER DROP COLUMN ATTACHMENT_PATH;
