-- Rename VERIFY_REMARKS to VERIFY_REJ_COMMENTS in SALES_PRICE_LIST_MASTER

IF EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'VERIFY_REMARKS' AND Object_ID = Object_ID(N'SALES_PRICE_LIST_MASTER'))
BEGIN
    EXEC sp_rename 'SALES_PRICE_LIST_MASTER.VERIFY_REMARKS', 'VERIFY_REJ_COMMENTS', 'COLUMN';
END
GO
