-- Drop old tables
IF OBJECT_ID('[dbo].[PP_QUALITY_INSPECTION_TRANS]', 'U') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[PP_QUALITY_INSPECTION_TRANS] DROP CONSTRAINT IF EXISTS FK_QI_TRANS_HEAD;
    ALTER TABLE [dbo].[PP_QUALITY_INSPECTION_TRANS] DROP CONSTRAINT IF EXISTS FK_QI_TRANS_GRN;
    ALTER TABLE [dbo].[PP_QUALITY_INSPECTION_TRANS] DROP CONSTRAINT IF EXISTS FK_QI_TRANS_ITEM;
    DROP TABLE [dbo].[PP_QUALITY_INSPECTION_TRANS];
END

IF OBJECT_ID('[dbo].[PP_QUALITY_INSPECTION_HEAD]', 'U') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[PP_QUALITY_INSPECTION_HEAD] DROP CONSTRAINT IF EXISTS FK_QI_HEAD_DIV;
    ALTER TABLE [dbo].[PP_QUALITY_INSPECTION_HEAD] DROP CONSTRAINT IF EXISTS FK_QI_HEAD_GRN;
    ALTER TABLE [dbo].[PP_QUALITY_INSPECTION_HEAD] DROP CONSTRAINT IF EXISTS FK_QI_HEAD_STATUS;
    DROP TABLE [dbo].[PP_QUALITY_INSPECTION_HEAD];
END

-- Create new single table
CREATE TABLE [dbo].[PP_QUALITY_INSPECTION] (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    INSPECTION_NO NVARCHAR(50) NOT NULL,
    INSPECTION_DATE DATETIME2 NOT NULL,
    GRN_ID BIGINT NOT NULL,
    ITEM_CODE NVARCHAR(150),
    ITEM_NAME NVARCHAR(500),
    BATCH_NO NVARCHAR(200),
    GRN_QTY NUMERIC(12,2) DEFAULT 0,
    ACCEPTED_QTY NUMERIC(12,2) DEFAULT 0,
    REJECTED_QTY NUMERIC(12,2) DEFAULT 0,
    REJECTION_REASON NVARCHAR(500),
    INSPECTED_BY_ID BIGINT,
    REMARKS NVARCHAR(500),
    ATTACHMENT_PATH NVARCHAR(MAX),
    STATUS BIT DEFAULT 1,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME2 NOT NULL DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME2,

    CONSTRAINT FK_QI_GRN FOREIGN KEY (GRN_ID) REFERENCES PP_GOODS_RECEIPT_TRANS(ID),
    CONSTRAINT FK_QI_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_QI_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);
