-- Add Foreign Keys for CREATED_BY and UPDATED_BY to map to AD_USER_CREDENTIAL
ALTER TABLE SALES_ATTACHMENTS_PATH 
ADD CONSTRAINT FK_SALES_ATT_CREATED FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);

ALTER TABLE SALES_ATTACHMENTS_PATH 
ADD CONSTRAINT FK_SALES_ATT_UPDATED FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);
