-- Add ATTACHMENT_PATH to SLS_ENQUIRY
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SLS_ENQUIRY' AND COLUMN_NAME = 'ATTACHMENT_PATH')
BEGIN
    ALTER TABLE SLS_ENQUIRY ADD ATTACHMENT_PATH NVARCHAR(MAX) NULL;
END
GO
