IF OBJECT_ID('dbo.QMC_REJECTION_REASON', 'U') IS NULL
BEGIN
    CREATE TABLE QMC_REJECTION_REASON (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        REJECTION_REASON NVARCHAR(MAX) NOT NULL,
        STATUS BIT DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME
    );

    -- Foreign Keys
    ALTER TABLE QMC_REJECTION_REASON
    ADD CONSTRAINT FK_QMC_REJECTION_REASON_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);

    ALTER TABLE QMC_REJECTION_REASON
    ADD CONSTRAINT FK_QMC_REJECTION_REASON_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);
END
GO
