-- 1. Rename table to QMC_QUALITY_INSPECTION if old table exists
IF OBJECT_ID('[dbo].[PP_QUALITY_INSPECTION]', 'U') IS NOT NULL
BEGIN
    EXEC sp_rename 'PP_QUALITY_INSPECTION', 'QMC_QUALITY_INSPECTION';
END
GO

-- 2. Rename GRN_ID to GRN_TRANS_ID (since it points to the transaction)
IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'GRN_ID') IS NOT NULL AND COL_LENGTH('QMC_QUALITY_INSPECTION', 'GRN_TRANS_ID') IS NULL
BEGIN
    EXEC sp_rename 'QMC_QUALITY_INSPECTION.GRN_ID', 'GRN_TRANS_ID', 'COLUMN';
END
GO

-- 3. Add new columns
IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'GRN_ID') IS NULL
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION ADD GRN_ID BIGINT NOT NULL DEFAULT 0;
END

IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'ITEM_ID') IS NULL
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION ADD ITEM_ID BIGINT NOT NULL DEFAULT 0;
END

IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'REJECTION_REASON_ID') IS NULL
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION ADD REJECTION_REASON_ID BIGINT;
END

IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'NC_QTY') IS NULL
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION ADD NC_QTY NUMERIC(12,2) DEFAULT 0;
END
GO

-- 4. Drop old columns
IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'INSPECTION_NO') IS NOT NULL
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION DROP COLUMN INSPECTION_NO;
END

IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'ITEM_CODE') IS NOT NULL
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION DROP COLUMN ITEM_CODE;
END

IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'ITEM_NAME') IS NOT NULL
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION DROP COLUMN ITEM_NAME;
END

IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'BATCH_NO') IS NOT NULL
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION DROP COLUMN BATCH_NO;
END

IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'REJECTION_REASON') IS NOT NULL
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION DROP COLUMN REJECTION_REASON;
END

IF COL_LENGTH('QMC_QUALITY_INSPECTION', 'ATTACHMENT_PATH') IS NOT NULL
BEGIN
    ALTER TABLE QMC_QUALITY_INSPECTION DROP COLUMN ATTACHMENT_PATH;
END
GO

-- 5. Drop prefix configuration columns
IF COL_LENGTH('AD_PREFIX_CREDENTIALS', 'quality_inspection_prefix') IS NOT NULL
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS DROP COLUMN quality_inspection_prefix;
END

IF COL_LENGTH('AD_PREFIX_CREDENTIALS', 'quality_inspection_suffix') IS NOT NULL
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS DROP COLUMN quality_inspection_suffix;
END

IF COL_LENGTH('AD_PREFIX_CREDENTIALS', 'quality_inspection_digit') IS NOT NULL
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS DROP COLUMN quality_inspection_digit;
END
GO
