-- Robust clean up of seeded/mock customers and their references
DELETE FROM [dbo].[CUSTOMER_SATISFACTION_MAPPING]
WHERE [CUSTOMER_ID] IN (
    SELECT [ID] FROM [dbo].[SLS_CUSTOMER] 
    WHERE [CUSTOMER_CODE] IN ('CUST001', 'CUST002', 'CUST003', 'CUST-001')
);
GO

DELETE FROM [dbo].[SLS_CUSTOMER_ADDRESS]
WHERE [CUSTOMER_ID] IN (
    SELECT [ID] FROM [dbo].[SLS_CUSTOMER] 
    WHERE [CUSTOMER_CODE] IN ('CUST001', 'CUST002', 'CUST003', 'CUST-001')
);
GO

DELETE FROM [dbo].[SLS_ENQUIRY]
WHERE [CUSTOMER_ID] IN (
    SELECT [ID] FROM [dbo].[SLS_CUSTOMER] 
    WHERE [CUSTOMER_CODE] IN ('CUST001', 'CUST002', 'CUST003', 'CUST-001')
);
GO

DELETE FROM [dbo].[SLS_PRICE_MASTER]
WHERE [CUSTOMER_ID] IN (
    SELECT [ID] FROM [dbo].[SLS_CUSTOMER] 
    WHERE [CUSTOMER_CODE] IN ('CUST001', 'CUST002', 'CUST003', 'CUST-001')
);
GO

DELETE FROM [dbo].[SLS_QUOTATION]
WHERE [CUSTOMER_ID] IN (
    SELECT [ID] FROM [dbo].[SLS_CUSTOMER] 
    WHERE [CUSTOMER_CODE] IN ('CUST001', 'CUST002', 'CUST003', 'CUST-001')
);
GO

DELETE FROM [dbo].[SLS_CUSTOMER]
WHERE [CUSTOMER_CODE] IN ('CUST001', 'CUST002', 'CUST003', 'CUST-001');
GO
