IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PP_PO_ATTACH_HEAD')
BEGIN
    ALTER TABLE PP_PURCHASE_ATTACHMENT DROP CONSTRAINT FK_PP_PO_ATTACH_HEAD;
END
GO

ALTER TABLE PP_PURCHASE_ATTACHMENT ALTER COLUMN PO_HEAD_ID BIGINT NULL;
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PP_PURCHASE_ATTACHMENT]') AND name = 'REF_ID')
BEGIN
    ALTER TABLE PP_PURCHASE_ATTACHMENT ADD REF_ID NVARCHAR(100) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PP_PURCHASE_ATTACHMENT]') AND name = 'PAGE_CODE')
BEGIN
    ALTER TABLE PP_PURCHASE_ATTACHMENT ADD PAGE_CODE NVARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PP_PURCHASE_ATTACHMENT]') AND name = 'DOC_TYPE')
BEGIN
    ALTER TABLE PP_PURCHASE_ATTACHMENT ADD DOC_TYPE NVARCHAR(50) NULL;
END
GO
