-- Add new fields for Procurement Policy
IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE Name = N'PO_APPROVAL_THRESHOLD'
    AND Object_ID = Object_ID(N'PP_PROCUREMENT_SETTINGS')
)
BEGIN
    ALTER TABLE PP_PROCUREMENT_SETTINGS ADD PO_APPROVAL_THRESHOLD DECIMAL(18,2) DEFAULT 0;
END
GO

IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE Name = N'DEFAULT_CURRENCY_ID'
    AND Object_ID = Object_ID(N'PP_PROCUREMENT_SETTINGS')
)
BEGIN
    ALTER TABLE PP_PROCUREMENT_SETTINGS ADD DEFAULT_CURRENCY_ID BIGINT NULL;
END
GO
