-- Drop REFERENCE_DOCUMENT column from SALES_PRICE_LIST_MASTER table
IF EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'REFERENCE_DOCUMENT' AND Object_ID = Object_ID(N'SALES_PRICE_LIST_MASTER'))
BEGIN
    ALTER TABLE SALES_PRICE_LIST_MASTER DROP COLUMN REFERENCE_DOCUMENT;
END
