IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'SALES_QUOTATION_HEADER' AND COLUMN_NAME = 'CONTACT_ID'
)
BEGIN
    ALTER TABLE SALES_QUOTATION_HEADER ADD CONTACT_ID BIGINT;
END
