-- Migration: V1161.0 - Drop Item Transaction FKs
-- Date: 20260822
-- Description: Drops the foreign key constraints on INVENTORY_TYPE and TRANS_TYPE in ITEM_TRANSACTION since they are used dynamically.

IF OBJECT_ID('FK_ITEM_TRANS_INV_TYPE', 'F') IS NOT NULL
BEGIN
    ALTER TABLE ITEM_TRANSACTION DROP CONSTRAINT FK_ITEM_TRANS_INV_TYPE;
END
GO

IF OBJECT_ID('FK_ITEM_TRANS_TRANS_TYPE', 'F') IS NOT NULL
BEGIN
    ALTER TABLE ITEM_TRANSACTION DROP CONSTRAINT FK_ITEM_TRANS_TRANS_TYPE;
END
GO
