-- Add new fields for Negotiation Prefix Credentials
IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE Name = N'NEGOTIATION_PREFIX'
    AND Object_ID = Object_ID(N'AD_PREFIX_CREDENTIALS')
)
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD NEGOTIATION_PREFIX NVARCHAR(20);
END
GO

IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE Name = N'NEGOTIATION_SUFFIX'
    AND Object_ID = Object_ID(N'AD_PREFIX_CREDENTIALS')
)
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD NEGOTIATION_SUFFIX NVARCHAR(20);
END
GO

IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE Name = N'NEGOTIATION_DIGIT'
    AND Object_ID = Object_ID(N'AD_PREFIX_CREDENTIALS')
)
BEGIN
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD NEGOTIATION_DIGIT INT;
END
GO
