IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PP_GOODS_RECEIPT_TRANS]') AND name = 'TEST_CERTIFICATE')
BEGIN
    ALTER TABLE PP_GOODS_RECEIPT_TRANS ADD TEST_CERTIFICATE nvarchar(500);
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PP_GOODS_RECEIPT_TRANS]') AND name = 'TC_SOURCE')
BEGIN
    ALTER TABLE PP_GOODS_RECEIPT_TRANS ADD TC_SOURCE nvarchar(200);
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PP_GOODS_RECEIPT_TRANS]') AND name = 'HEAT_NO')
BEGIN
    ALTER TABLE PP_GOODS_RECEIPT_TRANS ADD HEAT_NO nvarchar(150);
END
GO
