-- Rename SLS_ENQUIRY to SALES_ENQUIRY_HEADER
IF OBJECT_ID('SLS_ENQUIRY', 'U') IS NOT NULL
BEGIN
    EXEC sp_rename 'SLS_ENQUIRY', 'SALES_ENQUIRY_HEADER';
END
GO

-- Rename SLS_ENQUIRY_PART to SALES_ENQUIRY_DETAIL
IF OBJECT_ID('SLS_ENQUIRY_PART', 'U') IS NOT NULL
BEGIN
    EXEC sp_rename 'SLS_ENQUIRY_PART', 'SALES_ENQUIRY_DETAIL';
END
GO

-- Rename SLS_QUOTATION to SALES_QUOTATION_HEADER
IF OBJECT_ID('SLS_QUOTATION', 'U') IS NOT NULL
BEGIN
    EXEC sp_rename 'SLS_QUOTATION', 'SALES_QUOTATION_HEADER';
END
GO
