-- Add REMARKS column to SALES_PRICE_LIST_MASTER table
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'REMARKS' AND Object_ID = Object_ID(N'SALES_PRICE_LIST_MASTER'))
BEGIN
    ALTER TABLE SALES_PRICE_LIST_MASTER ADD REMARKS NVARCHAR(MAX);
END
