-- Migrate VERIFY_STATUS from NVARCHAR to BIGINT in SALES_PRICE_LIST_MASTER

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'VERIFY_STATUS_ID' AND Object_ID = Object_ID(N'SALES_PRICE_LIST_MASTER'))
BEGIN
    ALTER TABLE SALES_PRICE_LIST_MASTER ADD VERIFY_STATUS_ID BIGINT;
END
GO

UPDATE P
SET P.VERIFY_STATUS_ID = S.ID
FROM SALES_PRICE_LIST_MASTER P
JOIN AD_STATUS_MASTER S ON P.VERIFY_STATUS = S.NAME;
GO

DECLARE @defaultConstraintName VARCHAR(MAX);
SELECT @defaultConstraintName = df.name
FROM sys.default_constraints df
INNER JOIN sys.tables t ON df.parent_object_id = t.object_id
INNER JOIN sys.columns c ON df.parent_object_id = c.object_id AND df.parent_column_id = c.column_id
WHERE t.name = 'SALES_PRICE_LIST_MASTER' AND c.name = 'VERIFY_STATUS';

IF @defaultConstraintName IS NOT NULL
BEGIN
    EXEC('ALTER TABLE SALES_PRICE_LIST_MASTER DROP CONSTRAINT ' + @defaultConstraintName);
END
GO

IF EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'VERIFY_STATUS' AND Object_ID = Object_ID(N'SALES_PRICE_LIST_MASTER') AND system_type_id = 231) -- 231 is NVARCHAR
BEGIN
    ALTER TABLE SALES_PRICE_LIST_MASTER DROP COLUMN VERIFY_STATUS;
    EXEC sp_rename 'SALES_PRICE_LIST_MASTER.VERIFY_STATUS_ID', 'VERIFY_STATUS', 'COLUMN';
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PRICE_MASTER_VERIFY_STATUS')
BEGIN
    ALTER TABLE SALES_PRICE_LIST_MASTER ADD CONSTRAINT FK_PRICE_MASTER_VERIFY_STATUS FOREIGN KEY (VERIFY_STATUS) REFERENCES AD_STATUS_MASTER(ID);
END
GO
