IF OBJECT_ID('dbo.QMC_MATERIAL_INSPECTION', 'U') IS NULL
BEGIN
    CREATE TABLE QMC_MATERIAL_INSPECTION (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        QUALITY_INSPECTION_ID BIGINT NOT NULL,
        SPEC_PARAMETER_ID BIGINT,
        AQL_ID BIGINT,
        MIN_VAL NUMERIC(12,2),
        MAX_VAL NUMERIC(12,2),
        RESULT NVARCHAR(MAX),
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        UPDATED_BY NVARCHAR(50),
        UPDATED_DATE DATETIME,
        
        CONSTRAINT FK_QMC_MAT_INSP_QI FOREIGN KEY (QUALITY_INSPECTION_ID) REFERENCES QMC_QUALITY_INSPECTION(ID),
        CONSTRAINT FK_QMC_MAT_INSP_SPEC_PARAM FOREIGN KEY (SPEC_PARAMETER_ID) REFERENCES QMC_INSPECTION_SPECIFICATION_DETAIL(ID),
        CONSTRAINT FK_QMC_MAT_INSP_AQL FOREIGN KEY (AQL_ID) REFERENCES QMC_AQL_MASTER(ID)
    );
END
GO
