-- Idempotent script to add FINAL_FEEDBACK column to HR_EMPLOYEE_REFERENCE table
IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('[dbo].[HR_EMPLOYEE_REFERENCE]') 
    AND name = 'FINAL_FEEDBACK'
)
BEGIN
    ALTER TABLE [dbo].[HR_EMPLOYEE_REFERENCE] ADD [FINAL_FEEDBACK] NVARCHAR(MAX) NULL;
END
GO
