IF EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'SALES_QUOTATION_HEADER' AND COLUMN_NAME = 'ATTACHMENT_PATH'
)
BEGIN
    ALTER TABLE SALES_QUOTATION_HEADER DROP COLUMN ATTACHMENT_PATH;
END
