-- Ensure all existing statuses in NCR_STATUS are in AD_STATUS_MASTER
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_AUDIT_OBSERVATION_DETAIL') AND name = 'NCR_STATUS')
BEGIN
    -- Seed missing statuses
    INSERT INTO AD_STATUS_MASTER (NAME)
    SELECT DISTINCT NCR_STATUS FROM QMS_AUDIT_OBSERVATION_DETAIL
    WHERE NCR_STATUS IS NOT NULL AND NCR_STATUS != '' AND NOT EXISTS (
        SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = QMS_AUDIT_OBSERVATION_DETAIL.NCR_STATUS
    );

    -- Update NCR_STATUS to store the ID from AD_STATUS_MASTER
    UPDATE d
    SET d.NCR_STATUS = CAST(s.ID AS NVARCHAR(50))
    FROM QMS_AUDIT_OBSERVATION_DETAIL d
    JOIN AD_STATUS_MASTER s ON d.NCR_STATUS = s.NAME
    WHERE d.NCR_STATUS IS NOT NULL AND d.NCR_STATUS != '' AND ISNUMERIC(d.NCR_STATUS) = 0;

    -- Alter column type to BIGINT
    ALTER TABLE QMS_AUDIT_OBSERVATION_DETAIL ALTER COLUMN NCR_STATUS BIGINT NULL;
END
GO
