IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_NCR_REWORK_LOG') AND name = 'NCR_STATUS')
BEGIN
    ALTER TABLE QMS_NCR_REWORK_LOG ADD NCR_STATUS NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_NCR_REWORK_LOG') AND name = 'VERIFY_STATUS')
BEGIN
    ALTER TABLE QMS_NCR_REWORK_LOG ADD VERIFY_STATUS NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_NCR_REWORK_LOG') AND name = 'VERIFIED_BY')
BEGIN
    ALTER TABLE QMS_NCR_REWORK_LOG ADD VERIFIED_BY NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_NCR_REWORK_LOG') AND name = 'VERIFY_DATE')
BEGIN
    ALTER TABLE QMS_NCR_REWORK_LOG ADD VERIFY_DATE DATETIME NULL;
END
GO
