IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'VERIFY_STATUS_ID')
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD VERIFY_STATUS_ID BIGINT NULL;
    
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT 
    ADD CONSTRAINT FK_QMS_CHECKLIST_ASSIGNMENT_VERIFY_STATUS 
    FOREIGN KEY (VERIFY_STATUS_ID) REFERENCES AD_STATUS_MASTER(ID);
END
GO
