-- DB Migration: V1006__Fix_Recruitment_ATS_Bugs.sql

-- 1. Fix STATUS column in HR_INTERVIEW
DECLARE @ConstraintName NVARCHAR(200)
SELECT @ConstraintName = Name 
FROM sys.default_constraints 
WHERE parent_object_id = OBJECT_ID('[dbo].[HR_INTERVIEW]') 
  AND col_name(parent_object_id, parent_column_id) = 'STATUS'

IF @ConstraintName IS NOT NULL
    EXEC('ALTER TABLE [dbo].[HR_INTERVIEW] DROP CONSTRAINT ' + @ConstraintName)
GO

UPDATE [dbo].[HR_INTERVIEW]
SET [STATUS] = CASE 
    WHEN [STATUS] = 'ACTIVE' OR [STATUS] = 'true' OR [STATUS] = '1' THEN '1'
    ELSE '0'
END;
GO

ALTER TABLE [dbo].[HR_INTERVIEW] ALTER COLUMN [STATUS] BIT NULL;
GO

ALTER TABLE [dbo].[HR_INTERVIEW] ADD CONSTRAINT [DF_HR_INTERVIEW_STATUS] DEFAULT ((1)) FOR [STATUS];
GO

-- 2. Fix missing IS_ACTIVE column in HR_EMAIL_CONTENT
IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE object_id = OBJECT_ID('[dbo].[HR_EMAIL_CONTENT]') 
      AND name = 'IS_ACTIVE'
)
BEGIN
    ALTER TABLE [dbo].[HR_EMAIL_CONTENT] ADD [IS_ACTIVE] BIT NULL DEFAULT ((1));
END
GO

UPDATE [dbo].[HR_EMAIL_CONTENT] SET [IS_ACTIVE] = 1 WHERE [IS_ACTIVE] IS NULL;
GO

-- 3. Add performance indexes
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HR_INT_DEPT_MAP_DEPT' AND object_id = OBJECT_ID('[dbo].[HR_INTERVIEW_DEPARTMENT_MAPPING]'))
    CREATE NONCLUSTERED INDEX [IX_HR_INT_DEPT_MAP_DEPT] ON [dbo].[HR_INTERVIEW_DEPARTMENT_MAPPING] ([DEPARTMENT_ID]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HR_INT_LVL_MAP_LVL' AND object_id = OBJECT_ID('[dbo].[HR_INTERVIEW_LEVEL_MAPPING]'))
    CREATE NONCLUSTERED INDEX [IX_HR_INT_LVL_MAP_LVL] ON [dbo].[HR_INTERVIEW_LEVEL_MAPPING] ([LEVEL_ID]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HR_INDUCTION_ROUND_ID' AND object_id = OBJECT_ID('[dbo].[HR_INDUCTION]'))
    CREATE NONCLUSTERED INDEX [IX_HR_INDUCTION_ROUND_ID] ON [dbo].[HR_INDUCTION] ([INDUCTION_ROUND_ID]);
GO
