-- Add REFERENCE_ID_STRING column to HR_ATTACHMENT_PATH
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'HR_ATTACHMENT_PATH' 
      AND COLUMN_NAME = 'REFERENCE_ID_STRING'
)
BEGIN
    ALTER TABLE HR_ATTACHMENT_PATH ADD REFERENCE_ID_STRING NVARCHAR(255) NULL;
END
GO

-- Migrate existing M2110 page (Employee Ability) attachments to the new docType format and populate REFERENCE_ID_STRING
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_ATTACHMENT_PATH' AND COLUMN_NAME = 'REFERENCE_ID_STRING')
BEGIN
    -- 1. Auditor
    UPDATE HR_ATTACHMENT_PATH
    SET REFERENCE_ID_STRING = SUBSTRING(DOC_TYPE, 9, LEN(DOC_TYPE)),
        DOC_TYPE = 'ABILITY_AUDITOR'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE LIKE 'AUDITOR_%';

    UPDATE HR_ATTACHMENT_PATH
    SET DOC_TYPE = 'ABILITY_AUDITOR'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE = 'AUDITOR';

    -- 2. Auditee
    UPDATE HR_ATTACHMENT_PATH
    SET REFERENCE_ID_STRING = SUBSTRING(DOC_TYPE, 9, LEN(DOC_TYPE)),
        DOC_TYPE = 'ABILITY_AUDITEE'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE LIKE 'AUDITEE_%';

    UPDATE HR_ATTACHMENT_PATH
    SET DOC_TYPE = 'ABILITY_AUDITEE'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE = 'AUDITEE';

    -- 3. NC Approver
    UPDATE HR_ATTACHMENT_PATH
    SET REFERENCE_ID_STRING = SUBSTRING(DOC_TYPE, 14, LEN(DOC_TYPE)),
        DOC_TYPE = 'ABILITY_NC_APPROVAL'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE LIKE 'NCR_APPROVER_%';

    UPDATE HR_ATTACHMENT_PATH
    SET DOC_TYPE = 'ABILITY_NC_APPROVAL'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE = 'NCR_APPROVER';

    -- 4. Task Verifier
    UPDATE HR_ATTACHMENT_PATH
    SET REFERENCE_ID_STRING = SUBSTRING(DOC_TYPE, 15, LEN(DOC_TYPE)),
        DOC_TYPE = 'ABILITY_TASK_VERIFY'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE LIKE 'TASK_VERIFIER_%';

    UPDATE HR_ATTACHMENT_PATH
    SET DOC_TYPE = 'ABILITY_TASK_VERIFY'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE = 'TASK_VERIFIER';

    -- 5. Task Tester
    UPDATE HR_ATTACHMENT_PATH
    SET REFERENCE_ID_STRING = SUBSTRING(DOC_TYPE, 13, LEN(DOC_TYPE)),
        DOC_TYPE = 'ABILITY_TASK_TESTER'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE LIKE 'TASK_TESTER_%';

    UPDATE HR_ATTACHMENT_PATH
    SET DOC_TYPE = 'ABILITY_TASK_TESTER'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE = 'TASK_TESTER';

    -- 6. Chaired
    UPDATE HR_ATTACHMENT_PATH
    SET REFERENCE_ID_STRING = SUBSTRING(DOC_TYPE, 9, LEN(DOC_TYPE)),
        DOC_TYPE = 'CHAIRED'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE LIKE 'CHAIRED_%';

    -- 7. Host
    UPDATE HR_ATTACHMENT_PATH
    SET REFERENCE_ID_STRING = SUBSTRING(DOC_TYPE, 6, LEN(DOC_TYPE)),
        DOC_TYPE = 'HOST'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE LIKE 'HOST_%';

    -- 8. Participants
    UPDATE HR_ATTACHMENT_PATH
    SET REFERENCE_ID_STRING = SUBSTRING(DOC_TYPE, 14, LEN(DOC_TYPE)),
        DOC_TYPE = 'PARTICIPANTS'
    WHERE PAGE_CODE = 'M2110' AND DOC_TYPE LIKE 'PARTICIPANTS_%';
END
GO
