-- 1. Drop foreign key constraint on MST_STATE if it exists
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MST_STATE_COUNTRY')
BEGIN
    ALTER TABLE [dbo].[MST_STATE] DROP CONSTRAINT [FK_MST_STATE_COUNTRY];
END
GO

-- 2. Rename ID to ROW_ID in MST_COUNTRY if ID exists
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('MST_COUNTRY') AND name = 'ID')
BEGIN
    EXEC sp_rename 'MST_COUNTRY.ID', 'ROW_ID', 'COLUMN';
END
GO

-- 3. Rename COUNTRY to COUNTRY_NAME in MST_COUNTRY if COUNTRY exists
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('MST_COUNTRY') AND name = 'COUNTRY')
BEGIN
    EXEC sp_rename 'MST_COUNTRY.COUNTRY', 'COUNTRY_NAME', 'COLUMN';
END
GO

-- 4. Add new columns to MST_COUNTRY
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('MST_COUNTRY') AND name = 'COUNTRY_CODE')
BEGIN
    ALTER TABLE [dbo].[MST_COUNTRY] ADD [COUNTRY_CODE] NVARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('MST_COUNTRY') AND name = 'PHONE_MIN_LENGTH')
BEGIN
    ALTER TABLE [dbo].[MST_COUNTRY] ADD [PHONE_MIN_LENGTH] INT NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('MST_COUNTRY') AND name = 'PHONE_MAX_LENGTH')
BEGIN
    ALTER TABLE [dbo].[MST_COUNTRY] ADD [PHONE_MAX_LENGTH] INT NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('MST_COUNTRY') AND name = 'COUNTRY_ISO')
BEGIN
    ALTER TABLE [dbo].[MST_COUNTRY] ADD [COUNTRY_ISO] NVARCHAR(50) NULL;
END
GO

-- 5. Re-add foreign key constraint on MST_STATE referencing COUNTRY_NAME
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MST_STATE_COUNTRY')
BEGIN
    ALTER TABLE [dbo].[MST_STATE] WITH CHECK ADD CONSTRAINT [FK_MST_STATE_COUNTRY] FOREIGN KEY([COUNTRY_NAME])
    REFERENCES [dbo].[MST_COUNTRY] ([COUNTRY_NAME]);
    ALTER TABLE [dbo].[MST_STATE] CHECK CONSTRAINT [FK_MST_STATE_COUNTRY];
END
GO
