-- Seed Product Master tables' UPDATED_BY and UPDATED_DATE columns
UPDATE NPD_ITEM_GROUP SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_ITEM_TYPE SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_ITEM_SUBTYPE SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_OEM SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_OEM_MAPPING SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_MODEL SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_CAPACITY SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_PRODUCT_MASTER SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_PRODUCT_IPP SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
