-- Seed FMEA Master tables' UPDATED_BY and UPDATED_DATE columns
UPDATE SEVERITY_FMEA SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE DETECTION_FMEA SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE OCCURANCE_FMEA SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
