-- Migration Script: V1012 Alter QMS Checklist Remarks Column Lengths
-- Increases REMARKS and VERIFIED_COMMENTS lengths to prevent string truncation issues

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'REMARKS')
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ALTER COLUMN REMARKS NVARCHAR(500) NULL;
END
GO

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED') AND name = 'REMARKS')
BEGIN
    ALTER TABLE QMS_CHECKLIST_CLOSED ALTER COLUMN REMARKS NVARCHAR(500) NULL;
END
GO

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED') AND name = 'VERIFIED_COMMENTS')
BEGIN
    ALTER TABLE QMS_CHECKLIST_CLOSED ALTER COLUMN VERIFIED_COMMENTS NVARCHAR(500) NULL;
END
GO
