-- Seed NPD Material and Process Master tables' UPDATED_BY and UPDATED_DATE columns
UPDATE NPD_MATERIAL_TYPE SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_MATERIAL_GRADE SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_SHAPE_MASTER SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_MATERIAL_CONDITIONS SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_CHARACTER_SPECIFICATION SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_SAMPLE_SIZE SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_SAMPLE_FREQUENCY SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_CONTROL_METHOD SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_FEASIBILITY_CATEGORY SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_CORRECTIVE_ACTION SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_REACTION_PLAN SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE NPD_PROCESS SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
UPDATE DD_PRODUCT_PROCESS SET UPDATED_BY = CREATED_BY, UPDATED_DATE = CREATED_DATE WHERE UPDATED_BY IS NULL;
