DECLARE @ident INT, @maxid INT;
SELECT @ident = CAST(IDENT_CURRENT('NPD_CONTROL_METHOD') AS INT);
SELECT @maxid = MAX(id) FROM NPD_CONTROL_METHOD;
PRINT 'NPD_CONTROL_METHOD current identity: ' + CAST(ISNULL(@ident, 0) AS VARCHAR(20)) + ', max ID: ' + CAST(ISNULL(@maxid, 0) AS VARCHAR(20));
GO
