-- Migration Script: V1022 Alter QMS Checklist Remarks Column Lengths to NVARCHAR(MAX)
-- Increases REMARKS to NVARCHAR(MAX) to prevent string truncation issues

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'REMARKS')
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ALTER COLUMN REMARKS NVARCHAR(MAX) NULL;
END
GO

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED') AND name = 'REMARKS')
BEGIN
    ALTER TABLE QMS_CHECKLIST_CLOSED ALTER COLUMN REMARKS NVARCHAR(MAX) NULL;
END
GO
