-- V1021__Create_Sales_Price_Master_Module.sql

CREATE TABLE SALES_PRICE_LIST_MASTER (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    PRICE_LIST_NO NVARCHAR(50) NOT NULL UNIQUE,
    PRICE_LIST_TYPE NVARCHAR(50) NOT NULL,
    CUSTOMER_ID BIGINT NULL,
    CUSTOMER_GROUP_ID BIGINT NULL,
    PAYMENT_TERM_ID BIGINT NULL,
    REFERENCE_NO NVARCHAR(100) NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE NOT NULL,
    EXCHANGE_RATE DECIMAL(18, 4) NULL DEFAULT 1.0,
    STATUS NVARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    VERIFY_STATUS NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    VERIFY_REMARKS NVARCHAR(MAX) NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50) NULL,
    UPDATED_DATE DATETIME NULL,
    VERIFIED_BY NVARCHAR(50) NULL,
    VERIFIED_DATE DATETIME NULL,
    CONSTRAINT FK_SALES_PRICE_LIST_MASTER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES FA_ACCOUNT_LEDGER(ID),
    CONSTRAINT FK_SALES_PRICE_LIST_MASTER_CUST_GROUP FOREIGN KEY (CUSTOMER_GROUP_ID) REFERENCES FA_LEDGER_GROUP(ID),
    CONSTRAINT FK_SALES_PRICE_LIST_MASTER_PAY_TERM FOREIGN KEY (PAYMENT_TERM_ID) REFERENCES SM_PAYMENT_TERMS(ID),
    CONSTRAINT FK_SALES_PRICE_LIST_MASTER_CREATED FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_SALES_PRICE_LIST_MASTER_UPDATED FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_SALES_PRICE_LIST_MASTER_VERIFIED FOREIGN KEY (VERIFIED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);

CREATE TABLE SALES_PRICE_LIST_TRANS (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    PRICE_MASTER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    BASE_PRICE DECIMAL(18, 4) NULL,
    MIN_PRICE DECIMAL(18, 4) NULL,
    MAX_PRICE DECIMAL(18, 4) NULL,
    CONTRACT_PRICE DECIMAL(18, 4) NULL,
    TARGET_QTY DECIMAL(18, 4) NULL,
    CURRENCY NVARCHAR(10) NULL DEFAULT 'INR',
    REMARKS NVARCHAR(MAX) NULL,
    STATUS NVARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50) NULL,
    UPDATED_DATE DATETIME NULL,
    CONSTRAINT FK_SALES_PRICE_LIST_TRANS_MASTER FOREIGN KEY (PRICE_MASTER_ID) REFERENCES SALES_PRICE_LIST_MASTER(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SALES_PRICE_LIST_TRANS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES NPD_PRODUCT_MASTER(ID),
    CONSTRAINT FK_SALES_PRICE_LIST_TRANS_CREATED FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
    CONSTRAINT FK_SALES_PRICE_LIST_TRANS_UPDATED FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
);

-- Prefix Configuration columns for Sales Price List
IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'GPL_PREFIX' AND Object_ID = Object_ID(N'AD_PREFIX_CREDENTIALS'))
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD GPL_PREFIX NVARCHAR(20) NULL;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'CPC_PREFIX' AND Object_ID = Object_ID(N'AD_PREFIX_CREDENTIALS'))
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD CPC_PREFIX NVARCHAR(20) NULL;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'PRICE_LIST_DIGIT' AND Object_ID = Object_ID(N'AD_PREFIX_CREDENTIALS'))
    ALTER TABLE AD_PREFIX_CREDENTIALS ADD PRICE_LIST_DIGIT INT NULL;

