-- Create Purchase Request (PR) Entry Module Tables

-- 1. Modify HR_DEPARTMENT to include PR_PREFIX
IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'PR_PREFIX' AND Object_ID = Object_ID(N'HR_DEPARTMENT'))
BEGIN
    ALTER TABLE [dbo].[HR_DEPARTMENT] ADD [PR_PREFIX] NVARCHAR(10);
END

-- 2. Modify AD_PREFIX_CREDENTIALS to include PR configuration
IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'PR_PREFIX' AND Object_ID = Object_ID(N'AD_PREFIX_CREDENTIALS'))
BEGIN
    ALTER TABLE [dbo].[AD_PREFIX_CREDENTIALS] ADD [PR_PREFIX] NVARCHAR(20);
    ALTER TABLE [dbo].[AD_PREFIX_CREDENTIALS] ADD [PR_SUFFIX] NVARCHAR(20);
    ALTER TABLE [dbo].[AD_PREFIX_CREDENTIALS] ADD [PR_DIGIT] INT;
END

-- 3. Seed Statuses into AD_STATUS_MASTER
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Draft')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Draft');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'WIP')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('WIP');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Pending Approval')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Pending Approval');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Approved')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Approved');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Rejected')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Rejected');

IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'Cancelled')
    INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('Cancelled');

-- 4. Create PP_PURCHASE_REQUEST_HEAD Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_PURCHASE_REQUEST_HEAD]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_PURCHASE_REQUEST_HEAD] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [PR_NO] NVARCHAR(50) NOT NULL,
        [PR_DATE] DATE NOT NULL,
        [DEPARTMENT_ID] BIGINT NOT NULL,
        [PLANNERR_ID] BIGINT NOT NULL,
        [PR_FROM] NVARCHAR(25) DEFAULT 'REGULAR',
        [REMARKS] NVARCHAR(250) NULL,
        [STATUS] BIT NOT NULL DEFAULT 1,
        [DIVISION] BIGINT NOT NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        
        CONSTRAINT [PK_PP_PURCHASE_REQUEST_HEAD] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_PR_HEAD_DEPT] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[HR_DEPARTMENT]([ID]),
        CONSTRAINT [FK_PP_PR_HEAD_PLANNER] FOREIGN KEY ([PLANNERR_ID]) REFERENCES [dbo].[HR_EMPLOYEE]([ID]),
        CONSTRAINT [FK_PP_PR_HEAD_DIV] FOREIGN KEY ([DIVISION]) REFERENCES [dbo].[AD_DIVISION]([ID])
    );

    CREATE NONCLUSTERED INDEX [IX_PP_PURCHASE_REQUEST_HEAD_PR_NO] ON [dbo].[PP_PURCHASE_REQUEST_HEAD]([PR_NO]);
END
GO

-- 5. Create PP_PURCHASE_REQUEST_TRANS Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PP_PURCHASE_REQUEST_TRANS]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PP_PURCHASE_REQUEST_TRANS] (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        [PR_REF_ID] BIGINT NOT NULL,
        [ITEM_ID] BIGINT NOT NULL,
        [UOM] NVARCHAR(20) NOT NULL,
        [PRICE] NUMERIC(12,4) NOT NULL DEFAULT 0,
        [REQ_QTY] NUMERIC(12,4) NOT NULL DEFAULT 0,
        [REQ_DATE] DATE NOT NULL,
        [AMOUNT] NUMERIC(12,4) NOT NULL DEFAULT 0,
        [REMARKS] NVARCHAR(250) NULL,
        [APPROVER_ID] BIGINT NULL,
        [STATUS_ID] BIGINT NOT NULL,
        [APPROVED_DATE] DATETIME NULL,
        [DIVISION] BIGINT NOT NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        
        CONSTRAINT [PK_PP_PURCHASE_REQUEST_TRANS] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_PP_PR_TRANS_HEAD] FOREIGN KEY ([PR_REF_ID]) REFERENCES [dbo].[PP_PURCHASE_REQUEST_HEAD]([ID]) ON DELETE CASCADE,
        CONSTRAINT [FK_PP_PR_TRANS_ITEM] FOREIGN KEY ([ITEM_ID]) REFERENCES [dbo].[NPD_PRODUCT_MASTER]([ID]),
        CONSTRAINT [FK_PP_PR_TRANS_APPROVER] FOREIGN KEY ([APPROVER_ID]) REFERENCES [dbo].[HR_EMPLOYEE]([ID]),
        CONSTRAINT [FK_PP_PR_TRANS_STATUS] FOREIGN KEY ([STATUS_ID]) REFERENCES [dbo].[AD_STATUS_MASTER]([ID]),
        CONSTRAINT [FK_PP_PR_TRANS_DIV] FOREIGN KEY ([DIVISION]) REFERENCES [dbo].[AD_DIVISION]([ID])
    );
    
    CREATE NONCLUSTERED INDEX [IX_PP_PURCHASE_REQUEST_TRANS_REF] ON [dbo].[PP_PURCHASE_REQUEST_TRANS]([PR_REF_ID]);
END
GO

-- 6. Register Purchase Request Pages in BOS_PAGES
IF NOT EXISTS (SELECT 1 FROM BOS_PAGES WHERE PAGE_CODE = 'PP0104')
BEGIN
    DECLARE @ModuleId_PR BIGINT;
    SELECT @ModuleId_PR = MODULE_ID FROM BOS_MODULES WHERE MOD_CODE = 'PP0000';
    IF @ModuleId_PR IS NOT NULL
    BEGIN
        INSERT INTO BOS_PAGES (MOD_ID, PAGE_CODE, PAGE_NAME, PAGE_URL, ICON, ENABLED)
        VALUES (@ModuleId_PR, 'PP0104', 'Purchase Request', '/purchase/pr/list', 'IconClipboardList', 1);
        PRINT 'PP0104 - Purchase Request page registered.';
    END
END
GO
