-- Fix IDENTITY on QMT_MACHINE_CATEGORY ID column

-- 1. Drop foreign keys referencing QMT_MACHINE_CATEGORY
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_QMT_MACHINE_CATEGORY_ID' AND parent_object_id = OBJECT_ID('QMT_MACHINE'))
    ALTER TABLE QMT_MACHINE DROP CONSTRAINT FK_QMT_MACHINE_CATEGORY_ID;

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_DD_PP_MACHINE_CATEGORY' AND parent_object_id = OBJECT_ID('DD_PRODUCT_PROCESS_MACHINE'))
    ALTER TABLE DD_PRODUCT_PROCESS_MACHINE DROP CONSTRAINT FK_DD_PP_MACHINE_CATEGORY;

-- 2. Drop and recreate QMT_MACHINE_CATEGORY without IDENTITY if it is currently an identity column
IF EXISTS (
    SELECT 1 
    FROM sys.identity_columns 
    WHERE object_id = OBJECT_ID('QMT_MACHINE_CATEGORY') 
      AND name = 'ID'
)
BEGIN
    PRINT 'Dropping IDENTITY constraint from QMT_MACHINE_CATEGORY ID by migrating data...';

    -- Create temp table
    CREATE TABLE QMT_MACHINE_CATEGORY_TEMP (
        ID              BIGINT                  NOT NULL,
        CATEGORY_NAME   NVARCHAR(100)           NOT NULL,
        OEE_REQUIRED    BIT                     NOT NULL DEFAULT 0,
        SEQ_NO          INT                     NOT NULL DEFAULT 0,
        CATEGORY_PREFIX NVARCHAR(50)            NOT NULL,
        STATUS          BIT                     NOT NULL DEFAULT 1,
        CREATED_BY      NVARCHAR(50)            NOT NULL,
        CREATED_DATE    DATETIME                NOT NULL,
        UPDATED_BY      NVARCHAR(50)            NULL,
        UPDATED_DATE    DATETIME                NULL
    );

    -- Copy data
    INSERT INTO QMT_MACHINE_CATEGORY_TEMP (ID, CATEGORY_NAME, OEE_REQUIRED, SEQ_NO, CATEGORY_PREFIX, STATUS, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
    SELECT ID, CATEGORY_NAME, OEE_REQUIRED, SEQ_NO, CATEGORY_PREFIX, STATUS, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE
    FROM QMT_MACHINE_CATEGORY;

    -- Drop original table
    DROP TABLE QMT_MACHINE_CATEGORY;

    -- Rename temp table
    EXEC sp_rename 'QMT_MACHINE_CATEGORY_TEMP', 'QMT_MACHINE_CATEGORY';

    -- Add primary key and unique constraints
    ALTER TABLE QMT_MACHINE_CATEGORY ADD CONSTRAINT PK_QMT_MACHINE_CATEGORY PRIMARY KEY (ID);
    ALTER TABLE QMT_MACHINE_CATEGORY ADD CONSTRAINT UQ_QMT_MACHINE_CATEGORY_NAME UNIQUE (CATEGORY_NAME);
    ALTER TABLE QMT_MACHINE_CATEGORY ADD CONSTRAINT UQ_QMT_MACHINE_CATEGORY_PREFIX UNIQUE (CATEGORY_PREFIX);

    -- Add created/updated user constraints
    ALTER TABLE QMT_MACHINE_CATEGORY ADD CONSTRAINT FK_QMT_MACHINE_CATEGORY_CREATED_BY 
        FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);
    ALTER TABLE QMT_MACHINE_CATEGORY ADD CONSTRAINT FK_QMT_MACHINE_CATEGORY_UPDATED_BY 
        FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID);

    PRINT 'IDENTITY constraint dropped successfully from QMT_MACHINE_CATEGORY.';
END
GO

-- 3. Restore foreign keys referencing QMT_MACHINE_CATEGORY
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_QMT_MACHINE_CATEGORY_ID' AND parent_object_id = OBJECT_ID('QMT_MACHINE'))
BEGIN
    ALTER TABLE QMT_MACHINE ADD CONSTRAINT FK_QMT_MACHINE_CATEGORY_ID 
        FOREIGN KEY (CATEGORY_ID) REFERENCES QMT_MACHINE_CATEGORY(ID);
END
GO

IF OBJECT_ID('DD_PRODUCT_PROCESS_MACHINE', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_DD_PP_MACHINE_CATEGORY' AND parent_object_id = OBJECT_ID('DD_PRODUCT_PROCESS_MACHINE'))
BEGIN
    ALTER TABLE DD_PRODUCT_PROCESS_MACHINE ADD CONSTRAINT FK_DD_PP_MACHINE_CATEGORY 
        FOREIGN KEY (MACHINE_CATEGORY_ID) REFERENCES QMT_MACHINE_CATEGORY(ID);
END
GO

-- 4. Create QMT_MACHINE_CRITERIAL_SPARES if missing
IF OBJECT_ID('QMT_MACHINE_CRITERIAL_SPARES', 'U') IS NULL
BEGIN
    CREATE TABLE QMT_MACHINE_CRITERIAL_SPARES (
        ID              BIGINT IDENTITY(1,1)    NOT NULL,
        MACHINE_ID      BIGINT                  NOT NULL,
        ITEM_CODE       NVARCHAR(50)            NOT NULL,
        ITEM_NAME       NVARCHAR(100)           NOT NULL,
        SUPPLIER        NVARCHAR(100)           NULL,
        RATE            DECIMAL(18,2)           NULL,
        QTY             INT                     NULL,
        UOM             NVARCHAR(30)            NULL,
        CREATED_BY      NVARCHAR(50)            NOT NULL,
        CREATED_DATE    DATETIME                NOT NULL,
        UPDATED_BY      NVARCHAR(50)            NULL,
        UPDATED_DATE    DATETIME                NULL,
        CONSTRAINT PK_QMT_MACHINE_CRITERIAL_SPARES PRIMARY KEY (ID),
        CONSTRAINT FK_QMT_MACHINE_CRITERIAL_SPARES_MACHINE_ID 
            FOREIGN KEY (MACHINE_ID) REFERENCES QMT_MACHINE(ID) ON DELETE CASCADE,
        CONSTRAINT FK_QMT_MACHINE_CRITERIAL_SPARES_CREATED_BY 
            FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID),
        CONSTRAINT FK_QMT_MACHINE_CRITERIAL_SPARES_UPDATED_BY 
            FOREIGN KEY (UPDATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID)
    );

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_QMT_MACHINE_CRITERIAL_SPARES_MACHINE_ID')
        CREATE INDEX IX_QMT_MACHINE_CRITERIAL_SPARES_MACHINE_ID ON QMT_MACHINE_CRITERIAL_SPARES(MACHINE_ID);
END
GO
