-- 1. Seed standard statuses into AD_STATUS_MASTER if they don't exist (using exact casing)
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'ACTIVE') INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('ACTIVE');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'INACTIVE') INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('INACTIVE');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'TO BE VERIFIED') INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('TO BE VERIFIED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'VERIFIED') INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('VERIFIED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'REJECTED') INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('REJECTED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'UN ASSIGNED') INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('UN ASSIGNED');
IF NOT EXISTS (SELECT 1 FROM AD_STATUS_MASTER WHERE NAME = 'ASSIGNED') INSERT INTO AD_STATUS_MASTER (NAME) VALUES ('ASSIGNED');
GO

-- 2. Resolve IDs of standard statuses
DECLARE @ActiveId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'ACTIVE');
DECLARE @InactiveId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'INACTIVE');
DECLARE @ToBeVerifiedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'TO BE VERIFIED');
DECLARE @VerifiedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'VERIFIED');
DECLARE @RejectedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'REJECTED');
DECLARE @UnassignedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'UN ASSIGNED');
DECLARE @AssignedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'ASSIGNED');

-- Convert transaction tables referencing any other statuses to the 7 common status IDs
-- We map by checking name matches first, then doing updates.
DECLARE @OldActiveId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Active');
DECLARE @OldInactiveId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Inactive');
DECLARE @OldInActiveSpacedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'In Active');
DECLARE @OldToBeVerifiedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'To Be Verified');
DECLARE @OldVerifiedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Verified');
DECLARE @OldRejectedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Rejected');
DECLARE @OldUnassignedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Unassigned');
DECLARE @OldUnassignedSpacedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'UN ASSIGNED');
DECLARE @OldAssignedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Assigned');
DECLARE @OldPendingId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Pending');
DECLARE @OldInProgressId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'In Progress');
DECLARE @OldCompletedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Completed');
DECLARE @OldOverdueId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Overdue');
DECLARE @OldCancelledId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Cancelled');
DECLARE @OldAutoClosedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Auto Closed');
DECLARE @OldExpiredId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Expired');
DECLARE @OldClosedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Closed');
DECLARE @OldHoldId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Hold');

DECLARE @RenPendingId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Renewal Pending');
DECLARE @RenVerifiedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Renewal Verified');
DECLARE @RenRejectedId INT = (SELECT ID FROM AD_STATUS_MASTER WHERE NAME = 'Renewal Rejected');

-- Update QMS_CHECKLIST_ASSIGNMENT
UPDATE QMS_CHECKLIST_ASSIGNMENT SET STATUS_ID = @ToBeVerifiedId WHERE STATUS_ID IN (@RenPendingId, @OldPendingId, @OldHoldId);
UPDATE QMS_CHECKLIST_ASSIGNMENT SET STATUS_ID = @VerifiedId WHERE STATUS_ID IN (@RenVerifiedId, @OldVerifiedId, @OldCompletedId);
UPDATE QMS_CHECKLIST_ASSIGNMENT SET STATUS_ID = @RejectedId WHERE STATUS_ID IN (@RenRejectedId, @OldRejectedId);
UPDATE QMS_CHECKLIST_ASSIGNMENT SET STATUS_ID = @ActiveId WHERE STATUS_ID IN (@OldActiveId, @OldInProgressId, @OldAssignedId);
UPDATE QMS_CHECKLIST_ASSIGNMENT SET STATUS_ID = @InactiveId WHERE STATUS_ID IN (@OldInactiveId, @OldInActiveSpacedId, @OldCancelledId, @OldAutoClosedId, @OldExpiredId, @OldClosedId);
UPDATE QMS_CHECKLIST_ASSIGNMENT SET STATUS_ID = @UnassignedId WHERE STATUS_ID IN (@OldUnassignedId, @OldUnassignedSpacedId);

UPDATE QMS_CHECKLIST_ASSIGNMENT SET VERIFY_STATUS_ID = @ToBeVerifiedId WHERE VERIFY_STATUS_ID IN (@RenPendingId, @OldPendingId, @OldHoldId, @OldToBeVerifiedId) OR VERIFY_STATUS_ID IS NULL;
UPDATE QMS_CHECKLIST_ASSIGNMENT SET VERIFY_STATUS_ID = @VerifiedId WHERE VERIFY_STATUS_ID IN (@RenVerifiedId, @OldVerifiedId, @OldCompletedId);
UPDATE QMS_CHECKLIST_ASSIGNMENT SET VERIFY_STATUS_ID = @RejectedId WHERE VERIFY_STATUS_ID IN (@RenRejectedId, @OldRejectedId);

-- Update QMS_CHECKLIST_CLOSED
UPDATE QMS_CHECKLIST_CLOSED SET STATUS_ID = @ToBeVerifiedId WHERE STATUS_ID IN (@RenPendingId, @OldPendingId, @OldHoldId);
UPDATE QMS_CHECKLIST_CLOSED SET STATUS_ID = @VerifiedId WHERE STATUS_ID IN (@RenVerifiedId, @OldVerifiedId, @OldCompletedId);
UPDATE QMS_CHECKLIST_CLOSED SET STATUS_ID = @RejectedId WHERE STATUS_ID IN (@RenRejectedId, @OldRejectedId);
UPDATE QMS_CHECKLIST_CLOSED SET STATUS_ID = @ActiveId WHERE STATUS_ID IN (@OldActiveId, @OldInProgressId, @OldAssignedId);
UPDATE QMS_CHECKLIST_CLOSED SET STATUS_ID = @InactiveId WHERE STATUS_ID IN (@OldInactiveId, @OldInActiveSpacedId, @OldCancelledId, @OldAutoClosedId, @OldExpiredId, @OldClosedId);
UPDATE QMS_CHECKLIST_CLOSED SET STATUS_ID = @UnassignedId WHERE STATUS_ID IN (@OldUnassignedId, @OldUnassignedSpacedId);

UPDATE QMS_CHECKLIST_CLOSED SET VERIFY_STATUS_ID = @ToBeVerifiedId WHERE VERIFY_STATUS_ID IN (@RenPendingId, @OldPendingId, @OldHoldId, @OldToBeVerifiedId) OR VERIFY_STATUS_ID IS NULL;
UPDATE QMS_CHECKLIST_CLOSED SET VERIFY_STATUS_ID = @VerifiedId WHERE VERIFY_STATUS_ID IN (@RenVerifiedId, @OldVerifiedId, @OldCompletedId);
UPDATE QMS_CHECKLIST_CLOSED SET VERIFY_STATUS_ID = @RejectedId WHERE VERIFY_STATUS_ID IN (@RenRejectedId, @OldRejectedId);

-- Migrate QMS_CHECKLIST_MASTER integer codes to the 7 centralized status IDs
-- STATUS Column mappings
UPDATE QMS_CHECKLIST_MASTER SET STATUS = @ActiveId WHERE STATUS IN (1); -- Active, Pending, Renewal Pending, Renewal Verified
UPDATE QMS_CHECKLIST_MASTER SET STATUS = @InactiveId WHERE STATUS IN (0) OR STATUS IS NULL; -- Inactive, Expired, Cancelled, Closed

-- TASK_STATUS Column mappings
UPDATE QMS_CHECKLIST_MASTER SET TASK_STATUS = @AssignedId WHERE TASK_STATUS IN (1, 3, 7); -- In Progress, Overdue, Assigned
UPDATE QMS_CHECKLIST_MASTER SET TASK_STATUS = @UnassignedId WHERE TASK_STATUS IN (0, 6) OR TASK_STATUS IS NULL; -- Unassigned, Pending
UPDATE QMS_CHECKLIST_MASTER SET TASK_STATUS = @VerifiedId WHERE TASK_STATUS = 2; -- Completed (Completed task status maps to VERIFIED)
UPDATE QMS_CHECKLIST_MASTER SET TASK_STATUS = @InactiveId WHERE TASK_STATUS IN (4, 5); -- Cancelled, Auto Closed

-- VERIFY_STATUS Column mappings
UPDATE QMS_CHECKLIST_MASTER SET VERIFY_STATUS = @VerifiedId WHERE VERIFY_STATUS IN (1, 5); -- Verified, Renewal Verified
UPDATE QMS_CHECKLIST_MASTER SET VERIFY_STATUS = @RejectedId WHERE VERIFY_STATUS = 2; -- Rejected
UPDATE QMS_CHECKLIST_MASTER SET VERIFY_STATUS = @ToBeVerifiedId WHERE VERIFY_STATUS IN (0, 3, 4) OR VERIFY_STATUS IS NULL; -- To Be Verified, Hold, Renewal Pending
