-- =========================================================================================
-- FLYWAY MIGRATION SCRIPT: Create HR_PAYROLL_PROCESS_MASTER and HR_PAYROLL_PROCESS_TRANS
-- =========================================================================================

-- 1. Create Master Table: HR_PAYROLL_PROCESS_MASTER
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HR_PAYROLL_PROCESS_MASTER]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[HR_PAYROLL_PROCESS_MASTER] (
        [ROW_ID] BIGINT IDENTITY(1,1) NOT NULL,
        [PAYROLL_YEAR] INT NOT NULL,
        [PAYROLL_MONTH] INT NOT NULL,
        [COMPANY_ID] BIGINT NULL,
        [EMPLOYEE_CATEGORY_ID] BIGINT NULL,
        [EMPLOYEE_ID] BIGINT NULL,
        [EMPLOYEE_CODE] NVARCHAR(50) NULL,
        [EMPLOYEE_NAME] NVARCHAR(255) NULL,
        [PAYMENT_MODE] NVARCHAR(50) NULL,
        [BANK_NAME] NVARCHAR(100) NULL,
        [BRANCH_NAME] NVARCHAR(100) NULL,
        [IFSC_CODE] NVARCHAR(20) NULL,
        [SALARY_ACCOUNT_NUMBER] NVARCHAR(50) NULL,
        [ACCOUNT_NAME] NVARCHAR(100) NULL,
        [BANK_ACCOUNT_TYPE] NVARCHAR(20) NULL,
        [GROSS_SALARY] DECIMAL(18, 2) NULL DEFAULT 0.00,
        [TOTAL_DEDUCTIONS] DECIMAL(18, 2) NULL DEFAULT 0.00,
        [NET_SALARY] DECIMAL(18, 2) NULL DEFAULT 0.00,
        [PRESENT_DAYS] DECIMAL(18, 2) NULL DEFAULT 0.00,
        [LOP_DAYS] DECIMAL(18, 2) NULL DEFAULT 0.00,
        [PAID_DAYS] DECIMAL(18, 2) NULL DEFAULT 0.00,
        [OT_HOURS] DECIMAL(18, 2) NULL DEFAULT 0.00,
        [WAGE_TYPE] NVARCHAR(50) NULL,
        [DEPARTMENT_ID] BIGINT NULL,
        [DESIGNATION_ID] BIGINT NULL,
        [ESI_NO] NVARCHAR(100) NULL,
        [PF_NO] NVARCHAR(100) NULL,
        [OLD_EMPLOYEE_CODE] NVARCHAR(100) NULL,
        [STATUS_ID] BIGINT NULL,
        [APPROVED_BY] NVARCHAR(50) NULL,
        [APPROVED_DATE] DATETIME NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        [CREATED_DATE] DATETIME NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_HR_PAYROLL_PROCESS_MASTER] PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
    );
END;

-- 2. Create Transaction/Detail Table: HR_PAYROLL_PROCESS_TRANS
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HR_PAYROLL_PROCESS_TRANS]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[HR_PAYROLL_PROCESS_TRANS] (
        [TRANS_ID] BIGINT IDENTITY(1,1) NOT NULL,
        [ROW_ID] BIGINT NOT NULL,
        [COMPONENT_ID] BIGINT NULL,
        [COMPONENT_CODE] NVARCHAR(50) NULL,
        [COMPONENT_NAME] NVARCHAR(100) NULL,
        [COMPONENT_TYPE] NVARCHAR(20) NULL,
        [CALCULATION_TYPE] NVARCHAR(20) NULL,
        [AMOUNT] DECIMAL(18, 2) NULL DEFAULT 0.00,
        [SEQUENCE_NO] INT NULL,
        [CREATED_BY] NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        [CREATED_DATE] DATETIME NULL DEFAULT GETDATE(),
        [UPDATED_BY] NVARCHAR(50) NULL,
        [UPDATED_DATE] DATETIME NULL,
        CONSTRAINT [PK_HR_PAYROLL_PROCESS_TRANS] PRIMARY KEY CLUSTERED ([TRANS_ID] ASC),
        CONSTRAINT [FK_HPPT_HPPM] FOREIGN KEY ([ROW_ID]) REFERENCES [dbo].[HR_PAYROLL_PROCESS_MASTER] ([ROW_ID]) ON DELETE CASCADE
    );
END;

-- 3. Create Indexes for High Performance Querying
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_PAYROLL_PROCESS_MASTER_YEAR_MONTH' AND object_id = OBJECT_ID('HR_PAYROLL_PROCESS_MASTER'))
BEGIN
    CREATE INDEX IX_HR_PAYROLL_PROCESS_MASTER_YEAR_MONTH ON HR_PAYROLL_PROCESS_MASTER(PAYROLL_YEAR, PAYROLL_MONTH);
END;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_PAYROLL_PROCESS_MASTER_EMP' AND object_id = OBJECT_ID('HR_PAYROLL_PROCESS_MASTER'))
BEGIN
    CREATE INDEX IX_HR_PAYROLL_PROCESS_MASTER_EMP ON HR_PAYROLL_PROCESS_MASTER(EMPLOYEE_ID, EMPLOYEE_CODE);
END;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HR_PAYROLL_PROCESS_TRANS_MASTER' AND object_id = OBJECT_ID('HR_PAYROLL_PROCESS_TRANS'))
BEGIN
    CREATE INDEX IX_HR_PAYROLL_PROCESS_TRANS_MASTER ON HR_PAYROLL_PROCESS_TRANS(ROW_ID, COMPONENT_CODE);
END;
