-- Migration: V1107__Add_OT_Fields_To_HR_Setting_Master.sql
-- Purpose: Add OT Mode, OT Is Fixed, OT Fixed Amount, and OT Formula columns to HR_SETTING_MASTER table and sync existing values from AD_APP_PREFERENCE.

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_SETTING_MASTER') AND name = 'OT_MODE')
BEGIN
    ALTER TABLE HR_SETTING_MASTER ADD OT_MODE NVARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_SETTING_MASTER') AND name = 'OT_IS_FIXED')
BEGIN
    ALTER TABLE HR_SETTING_MASTER ADD OT_IS_FIXED NVARCHAR(10) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_SETTING_MASTER') AND name = 'OT_FIXED_AMOUNT')
BEGIN
    ALTER TABLE HR_SETTING_MASTER ADD OT_FIXED_AMOUNT DECIMAL(18,2) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_SETTING_MASTER') AND name = 'OT_FORMULA')
BEGIN
    ALTER TABLE HR_SETTING_MASTER ADD OT_FORMULA NVARCHAR(500) NULL;
END
GO

-- Seed / Sync existing settings from AD_APP_PREFERENCE or use default fallback values
UPDATE H SET
    H.OT_MODE = COALESCE(
        (SELECT TOP 1 PREF_VALUE FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OT_MODE'), 
        'FORMULA'
    ),
    H.OT_IS_FIXED = COALESCE(
        (SELECT TOP 1 PREF_VALUE FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OT_IS_FIXED'), 
        'false'
    ),
    H.OT_FIXED_AMOUNT = COALESCE(
        TRY_CAST((SELECT TOP 1 PREF_VALUE FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OT_FIXED_AMOUNT') AS DECIMAL(18,2)), 
        0.00
    ),
    H.OT_FORMULA = COALESCE(
        (SELECT TOP 1 PREF_VALUE FROM AD_APP_PREFERENCE WHERE PREF_NAME = 'OT_FORMULA'), 
        '((BASIC / 26) / 8)'
    )
FROM HR_SETTING_MASTER H;
GO
