-- ==================================================================================
-- Migration: V1115 - Fix CHECKLIST_DATE column type in QMS_CHECKLIST_ASSIGNMENT
-- Problem:   Column is DATETIME but Hibernate maps it as DATE (@Temporal(TemporalType.DATE))
--            The index UIX_QMS_CHECKLIST_ASSIGNMENT_UNIQUE_ACTIVE_TEMPLATE and
--            IX_CHECKLIST_ASSIGNMENT_DATE are dependent on this column, so we must
--            drop them first, alter the column, then recreate them.
-- ==================================================================================

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

-- Step 1: Drop the dependent indexes if they exist
IF EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'UIX_QMS_CHECKLIST_ASSIGNMENT_UNIQUE_ACTIVE_TEMPLATE'
      AND object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT')
)
BEGIN
    DROP INDEX UIX_QMS_CHECKLIST_ASSIGNMENT_UNIQUE_ACTIVE_TEMPLATE
        ON QMS_CHECKLIST_ASSIGNMENT;
END
GO

IF EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'IX_CHECKLIST_ASSIGNMENT_DATE'
      AND object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT')
)
BEGIN
    DROP INDEX IX_CHECKLIST_ASSIGNMENT_DATE
        ON QMS_CHECKLIST_ASSIGNMENT;
END
GO

-- Step 2: Alter CHECKLIST_DATE column from DATETIME to DATE
IF EXISTS (
    SELECT * FROM sys.columns
    WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT')
      AND name = 'CHECKLIST_DATE'
      AND system_type_id = TYPE_ID('datetime')
)
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT
        ALTER COLUMN CHECKLIST_DATE DATE NULL;
END
GO

-- Step 3: Recreate the filtered unique index (same as V438)
IF NOT EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'UIX_QMS_CHECKLIST_ASSIGNMENT_UNIQUE_ACTIVE_TEMPLATE'
      AND object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT')
)
BEGIN
    CREATE UNIQUE INDEX UIX_QMS_CHECKLIST_ASSIGNMENT_UNIQUE_ACTIVE_TEMPLATE
        ON QMS_CHECKLIST_ASSIGNMENT (CHECKLIST_ID, ASSIGNED_TO, ASSIGN_TYPE)
        WHERE CHECKLIST_DATE IS NULL AND ACTIVE = 1;
END
GO

-- Step 4: Recreate the date-based index
IF NOT EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'IX_CHECKLIST_ASSIGNMENT_DATE'
      AND object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT')
)
BEGIN
    CREATE INDEX IX_CHECKLIST_ASSIGNMENT_DATE
        ON QMS_CHECKLIST_ASSIGNMENT (CHECKLIST_DATE, ASSIGN_TYPE);
END
GO

-- Step 5: Fix CHECKLIST_DATE column type in QMS_CHECKLIST_CLOSED to DATE
IF EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'IX_CHECKLIST_CLOSED_DATE'
      AND object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED')
)
BEGIN
    DROP INDEX IX_CHECKLIST_CLOSED_DATE
        ON QMS_CHECKLIST_CLOSED;
END
GO

IF EXISTS (
    SELECT * FROM sys.columns
    WHERE object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED')
      AND name = 'CHECKLIST_DATE'
      AND system_type_id = TYPE_ID('datetime')
)
BEGIN
    ALTER TABLE QMS_CHECKLIST_CLOSED
        ALTER COLUMN CHECKLIST_DATE DATE NULL;
END
GO

IF NOT EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'IX_CHECKLIST_CLOSED_DATE'
      AND object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED')
)
BEGIN
    CREATE INDEX IX_CHECKLIST_CLOSED_DATE
        ON QMS_CHECKLIST_CLOSED (CHECKLIST_DATE, CHECKLIST_ID);
END
GO

-- Step 6: Create index on QMS_CHECKLIST_CLOSED (ASSIGNED_DATE) for performance
IF NOT EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'IX_CHECKLIST_CLOSED_ASSIGNED_DATE'
      AND object_id = OBJECT_ID('QMS_CHECKLIST_CLOSED')
)
BEGIN
    CREATE INDEX IX_CHECKLIST_CLOSED_ASSIGNED_DATE
        ON QMS_CHECKLIST_CLOSED (ASSIGNED_DATE);
END
GO

-- Step 7: Create index on QMS_CHECKLIST_ASSIGNMENT (ASSIGNED_DATE) for performance
IF NOT EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'IX_CHECKLIST_ASSIGNMENT_ASSIGNED_DATE'
      AND object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT')
)
BEGIN
    CREATE INDEX IX_CHECKLIST_ASSIGNMENT_ASSIGNED_DATE
        ON QMS_CHECKLIST_ASSIGNMENT (ASSIGNED_DATE);
END
GO

-- Step 8: Create index on HR_EMPLOYEE_MANAGER_MAPPING (HOME_MANAGER_ID) for performance
IF NOT EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'IX_HR_EMPLOYEE_MANAGER_MAPPING_HOME_MANAGER'
      AND object_id = OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING')
)
BEGIN
    CREATE INDEX IX_HR_EMPLOYEE_MANAGER_MAPPING_HOME_MANAGER
        ON HR_EMPLOYEE_MANAGER_MAPPING (HOME_MANAGER_ID);
END
GO

-- Step 9: Create index on HR_EMPLOYEE_MANAGER_MAPPING (BUSINESS_MANAGER_ID) for performance
IF NOT EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'IX_HR_EMPLOYEE_MANAGER_MAPPING_BUSINESS_MANAGER'
      AND object_id = OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING')
)
BEGIN
    CREATE INDEX IX_HR_EMPLOYEE_MANAGER_MAPPING_BUSINESS_MANAGER
        ON HR_EMPLOYEE_MANAGER_MAPPING (BUSINESS_MANAGER_ID);
END
GO
