-- 1. Add Primary Key to NPD_OEM
IF NOT EXISTS (
    SELECT 1 
    FROM sys.key_constraints 
    WHERE parent_object_id = OBJECT_ID('dbo.NPD_OEM') 
      AND type = 'PK'
)
BEGIN
    ALTER TABLE [dbo].[NPD_OEM] ADD CONSTRAINT [PK_NPD_OEM] PRIMARY KEY CLUSTERED ([OEM_SHORT_NAME]);
END
GO

-- 2. Clean up orphan records in QMS_MEETING_PARTICIPANT_MAPPING
DELETE FROM [dbo].[QMS_MEETING_PARTICIPANT_MAPPING]
WHERE [EMPLOYEE_ID] IS NOT NULL
  AND [EMPLOYEE_ID] NOT IN (SELECT [ID] FROM [dbo].[HR_EMPLOYEE]);
GO

-- 3. Clean up orphan records in QMS_MEETING_SCHEDULE
UPDATE [dbo].[QMS_MEETING_SCHEDULE]
SET [SECONDARY_HOST_ID] = NULL
WHERE [SECONDARY_HOST_ID] IS NOT NULL
  AND [SECONDARY_HOST_ID] NOT IN (SELECT [ID] FROM [dbo].[HR_EMPLOYEE]);
GO

UPDATE [dbo].[QMS_MEETING_SCHEDULE]
SET [TERTIARY_HOST_ID] = NULL
WHERE [TERTIARY_HOST_ID] IS NOT NULL
  AND [TERTIARY_HOST_ID] NOT IN (SELECT [ID] FROM [dbo].[HR_EMPLOYEE]);
GO
