-- DDL/DML Migration Script for ATS Notifications

-- 1. Add REF_TYPE and REF_ID to SYS_APP_NOTIFICATION
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SYS_APP_NOTIFICATION') AND name = 'REF_TYPE')
BEGIN
    ALTER TABLE SYS_APP_NOTIFICATION ADD REF_TYPE NVARCHAR(100) NULL;
    PRINT 'Added REF_TYPE column to SYS_APP_NOTIFICATION';
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SYS_APP_NOTIFICATION') AND name = 'REF_ID')
BEGIN
    ALTER TABLE SYS_APP_NOTIFICATION ADD REF_ID BIGINT NULL;
    PRINT 'Added REF_ID column to SYS_APP_NOTIFICATION';
END

-- 2. Add REMINDER_SENT and READY_NOTIFICATION_SENT to HR_APPLICANT_INTERVIEW
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_APPLICANT_INTERVIEW') AND name = 'REMINDER_SENT')
BEGIN
    ALTER TABLE HR_APPLICANT_INTERVIEW ADD REMINDER_SENT BIT NOT NULL DEFAULT 0;
    PRINT 'Added REMINDER_SENT column to HR_APPLICANT_INTERVIEW';
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('HR_APPLICANT_INTERVIEW') AND name = 'READY_NOTIFICATION_SENT')
BEGIN
    ALTER TABLE HR_APPLICANT_INTERVIEW ADD READY_NOTIFICATION_SENT BIT NOT NULL DEFAULT 0;
    PRINT 'Added READY_NOTIFICATION_SENT column to HR_APPLICANT_INTERVIEW';
END

