IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'GROUP_NAME')
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD GROUP_NAME NVARCHAR(100) NULL;
END
