-- Ensure all existing group names in QMS_CHECKLIST_ASSIGNMENT are saved in UPPERCASE
UPDATE QMS_CHECKLIST_ASSIGNMENT 
SET GROUP_NAME = UPPER(TRIM(GROUP_NAME)) 
WHERE GROUP_NAME IS NOT NULL AND TRIM(GROUP_NAME) <> '';
