IF COL_LENGTH('NPD_PROCESS', 'STATUS') IS NOT NULL AND (SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NPD_PROCESS' AND COLUMN_NAME = 'STATUS') != 'bit'
BEGIN
    -- Add temporary column
    ALTER TABLE NPD_PROCESS ADD STATUS_BIT BIT DEFAULT 1;

    -- Update existing data
    EXEC('UPDATE NPD_PROCESS SET STATUS_BIT = CASE WHEN STATUS = ''ACTIVE'' OR STATUS = ''Active'' THEN 1 WHEN STATUS = ''INACTIVE'' OR STATUS = ''Inactive'' THEN 0 ELSE 1 END');

    -- Drop old constraints if any (like DEFAULT constraints on STATUS)
    DECLARE @ConstraintName nvarchar(200)
    SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS WHERE PARENT_OBJECT_ID = OBJECT_ID('NPD_PROCESS') AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns WHERE NAME = 'STATUS' AND object_id = OBJECT_ID('NPD_PROCESS'))
    IF @ConstraintName IS NOT NULL
        EXEC('ALTER TABLE NPD_PROCESS DROP CONSTRAINT ' + @ConstraintName)

    -- Drop the old column
    ALTER TABLE NPD_PROCESS DROP COLUMN STATUS;

    -- Rename new column
    EXEC sp_rename 'NPD_PROCESS.STATUS_BIT', 'STATUS', 'COLUMN';
END
GO

-- Drop IS_ACTIVE column
IF COL_LENGTH('NPD_PROCESS', 'IS_ACTIVE') IS NOT NULL
BEGIN
    DECLARE @IsActiveConstraintName nvarchar(200)
    SELECT @IsActiveConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS WHERE PARENT_OBJECT_ID = OBJECT_ID('NPD_PROCESS') AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns WHERE NAME = 'IS_ACTIVE' AND object_id = OBJECT_ID('NPD_PROCESS'))
    IF @IsActiveConstraintName IS NOT NULL
        EXEC('ALTER TABLE NPD_PROCESS DROP CONSTRAINT ' + @IsActiveConstraintName)
        
    ALTER TABLE NPD_PROCESS DROP COLUMN IS_ACTIVE;
END
GO
