-- V277__Add_Allow_Duplicate_Screens_Flag.sql

-- Add ALLOW_DUPLICATE_SCREENS column to AD_COMPANY_CREDENTIAL table if it does not exist
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ALLOW_DUPLICATE_SCREENS')
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ALLOW_DUPLICATE_SCREENS] BIT DEFAULT 0;
END
GO
