-- =========================================================================
-- Migration: V999__Seed_Missing_Levels_And_Designations.sql
-- Purpose: Seed levels and designations into the HR database if missing.
-- =========================================================================

-- 1. Seed HR_LEVEL
IF NOT EXISTS (SELECT 1 FROM HR_LEVEL WHERE LEVEL_NAME = 'L1')
    INSERT INTO HR_LEVEL (LEVEL_NAME, CREATED_BY, CREATED_DATE, IS_ACTIVE) VALUES ('L1', 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_LEVEL WHERE LEVEL_NAME = 'L2')
    INSERT INTO HR_LEVEL (LEVEL_NAME, CREATED_BY, CREATED_DATE, IS_ACTIVE) VALUES ('L2', 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_LEVEL WHERE LEVEL_NAME = 'L3')
    INSERT INTO HR_LEVEL (LEVEL_NAME, CREATED_BY, CREATED_DATE, IS_ACTIVE) VALUES ('L3', 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_LEVEL WHERE LEVEL_NAME = 'L4')
    INSERT INTO HR_LEVEL (LEVEL_NAME, CREATED_BY, CREATED_DATE, IS_ACTIVE) VALUES ('L4', 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_LEVEL WHERE LEVEL_NAME = 'L5')
    INSERT INTO HR_LEVEL (LEVEL_NAME, CREATED_BY, CREATED_DATE, IS_ACTIVE) VALUES ('L5', 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_LEVEL WHERE LEVEL_NAME = 'L6')
    INSERT INTO HR_LEVEL (LEVEL_NAME, CREATED_BY, CREATED_DATE, IS_ACTIVE) VALUES ('L6', 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_LEVEL WHERE LEVEL_NAME = 'L7')
    INSERT INTO HR_LEVEL (LEVEL_NAME, CREATED_BY, CREATED_DATE, IS_ACTIVE) VALUES ('L7', 'SUPER BOSS', GETDATE(), 1);
GO

-- 2. Seed HR_DESIGNATION_LEVEL
IF NOT EXISTS (SELECT 1 FROM HR_DESIGNATION_LEVEL WHERE LEVEL = 'L1')
    INSERT INTO HR_DESIGNATION_LEVEL (LEVEL, BASIC, DA, HRA, SCREENING_LEVEL, CREATED_BY, CREATED_DATE, IS_ACTIVE)
    VALUES ('L1', 15000.0, 3000.0, 4500.0, 1, 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_DESIGNATION_LEVEL WHERE LEVEL = 'L2')
    INSERT INTO HR_DESIGNATION_LEVEL (LEVEL, BASIC, DA, HRA, SCREENING_LEVEL, CREATED_BY, CREATED_DATE, IS_ACTIVE)
    VALUES ('L2', 25000.0, 5000.0, 7500.0, 2, 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_DESIGNATION_LEVEL WHERE LEVEL = 'L3')
    INSERT INTO HR_DESIGNATION_LEVEL (LEVEL, BASIC, DA, HRA, SCREENING_LEVEL, CREATED_BY, CREATED_DATE, IS_ACTIVE)
    VALUES ('L3', 40000.0, 8000.0, 12000.0, 3, 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_DESIGNATION_LEVEL WHERE LEVEL = 'L4')
    INSERT INTO HR_DESIGNATION_LEVEL (LEVEL, BASIC, DA, HRA, SCREENING_LEVEL, CREATED_BY, CREATED_DATE, IS_ACTIVE)
    VALUES ('L4', 60000.0, 12000.0, 18000.0, 4, 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_DESIGNATION_LEVEL WHERE LEVEL = 'L5')
    INSERT INTO HR_DESIGNATION_LEVEL (LEVEL, BASIC, DA, HRA, SCREENING_LEVEL, CREATED_BY, CREATED_DATE, IS_ACTIVE)
    VALUES ('L5', 90000.0, 18000.0, 27000.0, 5, 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_DESIGNATION_LEVEL WHERE LEVEL = 'L6')
    INSERT INTO HR_DESIGNATION_LEVEL (LEVEL, BASIC, DA, HRA, SCREENING_LEVEL, CREATED_BY, CREATED_DATE, IS_ACTIVE)
    VALUES ('L6', 120000.0, 24000.0, 36000.0, 6, 'SUPER BOSS', GETDATE(), 1);
IF NOT EXISTS (SELECT 1 FROM HR_DESIGNATION_LEVEL WHERE LEVEL = 'L7')
    INSERT INTO HR_DESIGNATION_LEVEL (LEVEL, BASIC, DA, HRA, SCREENING_LEVEL, CREATED_BY, CREATED_DATE, IS_ACTIVE)
    VALUES ('L7', 150000.0, 30000.0, 45000.0, 7, 'SUPER BOSS', GETDATE(), 1);
GO