package com.autonoma.erp.modules.platform.notification.service;

import com.autonoma.erp.modules.platform.notification.entity.EmailContent;
import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.Map;

/**
 * EmailDefaultTemplates — In-memory application default email templates.
 * Provides pre-populated default message bodies with standard placeholders when HR
 * creates a new Email Content entry in Email Content Master.
 *
 * NOTE: These templates contain ONLY the message body. Header, Interview Details,
 * Action Buttons, Instructions, and Footer are automatically generated by the Master Layout Engine.
 */
@Component
public class EmailDefaultTemplates {

    private final Map<String, EmailContent> defaultTemplatesMap = new HashMap<>();

    public EmailDefaultTemplates() {
        initDefaultTemplates();
    }

    private void initDefaultTemplates() {
        // 1. CALL LETTER
        EmailContent callLetter = new EmailContent();
        callLetter.setType("CALL LETTER");
        callLetter.setSubject("Interview Invitation - {{position}}");
        callLetter.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>Greetings from <strong>{{companyName}}</strong>.</p>" +
            "<p>We are pleased to inform you that your application for the position of <strong>{{position}}</strong> in our <strong>{{department}}</strong> department has been shortlisted.</p>" +
            "<p>We cordially invite you to attend the interview as per the schedule below.</p>"
        );
        callLetter.setYoursWindfully("Autonoma ERP Corp HR Team");
        callLetter.setIncludeCompanyFooter(false);
        callLetter.setIncludeWebsite(false);
        callLetter.setIncludeLocation(false);
        callLetter.setIsActive(true);
        defaultTemplatesMap.put("CALL LETTER", callLetter);

        // 2. OFFER LETTER
        EmailContent offerLetter = new EmailContent();
        offerLetter.setType("OFFER LETTER");
        offerLetter.setSubject("Job Offer: {{position}} at {{companyName}}");
        offerLetter.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>Congratulations!</p>" +
            "<p>Following your recent interview, we are delighted to extend a formal job offer for the position of <strong>{{position}}</strong> at <strong>{{companyName}}</strong>.</p>" +
            "<p>Please review the offer details and confirm your acceptance within <strong>48 hours</strong>.</p>" +
            "<p>We look forward to welcoming you aboard!</p>"
        );
        offerLetter.setYoursWindfully("Autonoma ERP Corp Recruitment Team");
        offerLetter.setIncludeCompanyFooter(false);
        offerLetter.setIncludeWebsite(false);
        offerLetter.setIncludeLocation(false);
        offerLetter.setIsActive(true);
        defaultTemplatesMap.put("OFFER LETTER", offerLetter);

        // 3. SHORTLISTED / INTERVIEW ASSIGN
        EmailContent shortlisted = new EmailContent();
        shortlisted.setType("SHORTLISTED");
        shortlisted.setSubject("Application Update: Shortlisted for {{position}}");
        shortlisted.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>Thank you for applying for the position of <strong>{{position}}</strong> at <strong>{{companyName}}</strong>.</p>" +
            "<p>We are pleased to inform you that your profile has been shortlisted for the next evaluation round. Our Talent Acquisition team will share the schedule details shortly.</p>"
        );
        shortlisted.setYoursWindfully("Autonoma ERP Corp Talent Acquisition");
        shortlisted.setIsActive(true);
        defaultTemplatesMap.put("SHORTLISTED", shortlisted);
        defaultTemplatesMap.put("INTERVIEW ASSIGN", shortlisted);

        // 4. REJECTED / REJECTION
        EmailContent rejected = new EmailContent();
        rejected.setType("REJECTION");
        rejected.setSubject("Application Status Update - {{position}}");
        rejected.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>Thank you for your interest in <strong>{{companyName}}</strong> and for taking the time to participate in our selection process for the position of <strong>{{position}}</strong>.</p>" +
            "<p>While your qualifications are commendable, after careful consideration, we have chosen to proceed with another candidate whose background more closely aligns with our current requirements.</p>" +
            "<p>We appreciate your time and wish you every success in your future career endeavors.</p>"
        );
        rejected.setYoursWindfully("{{companyName}}");
        rejected.setFooterHeader("Thanks & Regards");
        rejected.setFooterContent("{{companyName}}");
        rejected.setIsActive(true);
        defaultTemplatesMap.put("REJECTED", rejected);
        defaultTemplatesMap.put("REJECTION", rejected);

        // 5. APPOINTMENT LETTER / WELCOME MAIL
        EmailContent appointment = new EmailContent();
        appointment.setType("APPOINTMENT LETTER");
        appointment.setSubject("Welcome to {{companyName}} - Appointment Details");
        appointment.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>A warm welcome to <strong>{{companyName}}</strong>!</p>" +
            "<p>We are thrilled to officially welcome you as <strong>{{position}}</strong> in the <strong>{{department}}</strong> department.</p>" +
            "<p>Your formal appointment details are confirmed. Please report to the HR desk on your joining date with your original documents for verification.</p>"
        );
        appointment.setYoursWindfully("Autonoma ERP Corp HR Team");
        appointment.setIsActive(true);
        defaultTemplatesMap.put("APPOINTMENT LETTER", appointment);

        // 6. VISITOR PASS
        EmailContent visitorPass = new EmailContent();
        visitorPass.setType("VISITOR PASS");
        visitorPass.setSubject("Visitor Pass Confirmation - {{companyName}}");
        visitorPass.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>Your visitor pass for visiting <strong>{{companyName}}</strong> has been generated successfully.</p>" +
            "<p>Please present this confirmation email at our security gate upon arrival.</p>"
        );
        visitorPass.setYoursWindfully("Autonoma ERP Corp Security & HR");
        visitorPass.setIsActive(true);
        defaultTemplatesMap.put("VISITOR PASS", visitorPass);

        // 7. LTA APPLY
        EmailContent ltaApply = new EmailContent();
        ltaApply.setType("LTA APPLY");
        ltaApply.setSubject("Leave Travel Allowance Application Received");
        ltaApply.setBodyContent(
            "<p>Dear Employee,</p>" +
            "<p>Your application for Leave Travel Allowance (LTA) has been received and submitted for verification.</p>"
        );
        ltaApply.setYoursWindfully("Autonoma ERP Corp HR & Payroll");
        ltaApply.setIsActive(true);
        defaultTemplatesMap.put("LTA APPLY", ltaApply);

        // 8. ASSIGN INDUCTION
        EmailContent assignInduction = new EmailContent();
        assignInduction.setType("ASSIGN INDUCTION");
        assignInduction.setSubject("Induction Program Schedule - {{companyName}}");
        assignInduction.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>You have been assigned to the upcoming Employee Induction Program at <strong>{{companyName}}</strong>.</p>" +
            "<p>Please attend the session on schedule as instructed by your HR onboarding representative.</p>"
        );
        assignInduction.setYoursWindfully("Autonoma ERP Corp Training & Development");
        assignInduction.setIsActive(true);
        defaultTemplatesMap.put("ASSIGN INDUCTION", assignInduction);

        // 9. INDUCTION TRAINEE REJECT
        EmailContent inductionReject = new EmailContent();
        inductionReject.setType("INDUCTION TRAINEE REJECT");
        inductionReject.setSubject("Induction Assessment Update");
        inductionReject.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>Thank you for participating in the Employee Induction Program at <strong>{{companyName}}</strong>.</p>" +
            "<p>This is to inform you that you did not clear the required evaluation threshold for the induction program.</p>"
        );
        inductionReject.setYoursWindfully("Autonoma ERP Corp HR Team");
        inductionReject.setIsActive(true);
        defaultTemplatesMap.put("INDUCTION TRAINEE REJECT", inductionReject);

        // 10. INDUCTION TRAINEE COMPLETED
        EmailContent inductionCompleted = new EmailContent();
        inductionCompleted.setType("INDUCTION TRAINEE COMPLETED");
        inductionCompleted.setSubject("Congratulations on Completing Induction Program - {{companyName}}");
        inductionCompleted.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>Congratulations on successfully completing your Employee Induction Program at <strong>{{companyName}}</strong>!</p>" +
            "<p>You will now transition into your regular role as <strong>{{position}}</strong> in the <strong>{{department}}</strong> department.</p>"
        );
        inductionCompleted.setYoursWindfully("Autonoma ERP Corp Training & Development");
        inductionCompleted.setIsActive(true);
        defaultTemplatesMap.put("INDUCTION TRAINEE COMPLETED", inductionCompleted);

        // 11. BACKGROUND VERIFICATION
        EmailContent bgv = new EmailContent();
        bgv.setType("BACKGROUND VERIFICATION");
        bgv.setSubject("Applicant Reference Verification Request - {{candidateFullName}}");
        bgv.setBodyContent(
            "<p>Dear <strong>{{recipientName}}</strong>,</p>" +
            "<p>Greetings from <strong>{{companyName}}</strong>.</p>" +
            "<p><strong>{{candidateFullName}}</strong> has listed you as a reference contact for their employment application for the position of <strong>{{position}}</strong>.</p>" +
            "<p>We kindly request you to complete our brief reference verification form by clicking the link below. Your feedback will remain confidential.</p>"
        );
        bgv.setYoursWindfully("Autonoma ERP Corp HR Verification Team");
        bgv.setIsActive(true);
        defaultTemplatesMap.put("BACKGROUND VERIFICATION", bgv);

        // 12. DOCUMENT REUPLOAD / DOCUMENT VERIFICATION FAILED
        EmailContent docReupload = new EmailContent();
        docReupload.setType("DOCUMENT REUPLOAD");
        docReupload.setSubject("Action Required: Re-upload Rejected Onboarding Documents");
        docReupload.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>Thank you for submitting your verification details for <strong>{{companyName}}</strong>.</p>" +
            "<p>During our document verification check, the following document(s) could not be verified or accepted:</p>" +
            "{{rejectedDocumentsTable}}" +
            "<p>Please click the button below to upload clear, valid replacement document(s) at your earliest convenience before the link expires.</p>"
        );
        docReupload.setYoursWindfully("HR Onboarding Team");
        docReupload.setIsActive(true);
        defaultTemplatesMap.put("DOCUMENT REUPLOAD", docReupload);
        defaultTemplatesMap.put("DOCUMENT VERIFICATION FAILED", docReupload);

        // 13. EMPLOYEE MEMO
        EmailContent memo = new EmailContent();
        memo.setType("EMPLOYEE MEMO");
        memo.setSubject("Official Internal Memo: {{memoSubject}}");
        memo.setBodyContent(
            "<p>Dear Team,</p>" +
            "<p>Please review the official internal memo below issued by <strong>{{companyName}}</strong> HR Administration.</p>"
        );
        memo.setYoursWindfully("Autonoma ERP Corp HR Administration");
        memo.setIsActive(true);
        defaultTemplatesMap.put("EMPLOYEE MEMO", memo);

        // 14. CUSTOMER SATISFACTION (CSAT)
        EmailContent csat = new EmailContent();
        csat.setType("CUSTOMER SATISFACTION");
        csat.setSubject("We Value Your Feedback - {{companyName}} Customer Survey");
        csat.setBodyContent(
            "<p>Dear <strong>{{customerName}}</strong>,</p>" +
            "<p>Thank you for choosing <strong>{{companyName}}</strong> as your trusted business partner.</p>" +
            "<p>As part of our commitment to continuous service improvement, we invite you to complete our short Customer Satisfaction survey for cycle <strong>{{cycleName}}</strong>.</p>" +
            "<p>Your valuable insights help us serve you better.</p>"
        );
        csat.setYoursWindfully("Autonoma ERP Corp Quality Management System");
        csat.setIsActive(true);
        defaultTemplatesMap.put("CUSTOMER SATISFACTION", csat);

        // 15. VENDOR SATISFACTION (VSAT)
        EmailContent vsat = new EmailContent();
        vsat.setType("VENDOR SATISFACTION");
        vsat.setSubject("Vendor Feedback Survey - {{companyName}}");
        vsat.setBodyContent(
            "<p>Dear <strong>{{vendorName}}</strong>,</p>" +
            "<p>Greetings from <strong>{{companyName}}</strong>.</p>" +
            "<p>We appreciate your ongoing partnership. Please take a few moments to provide your feedback for cycle <strong>{{cycleName}}</strong> using the survey button below.</p>"
        );
        vsat.setYoursWindfully("Autonoma ERP Corp Supply Chain Management");
        vsat.setIsActive(true);
        defaultTemplatesMap.put("VENDOR SATISFACTION", vsat);

        // 16. EMPLOYEE SATISFACTION (ESAT)
        EmailContent esat = new EmailContent();
        esat.setType("EMPLOYEE SATISFACTION");
        esat.setSubject("Internal Employee Feedback Survey - {{cycleName}}");
        esat.setBodyContent(
            "<p>Dear <strong>{{employeeName}}</strong>,</p>" +
            "<p>Your voice matters to us at <strong>{{companyName}}</strong>.</p>" +
            "<p>Please take a few minutes to share your honest feedback for cycle <strong>{{cycleName}}</strong> using the survey portal link below.</p>"
        );
        esat.setYoursWindfully("Autonoma ERP Corp HR & People Operations");
        esat.setIsActive(true);
        defaultTemplatesMap.put("EMPLOYEE SATISFACTION", esat);

        // 17. SALES ENQUIRY
        EmailContent salesEnquiry = new EmailContent();
        salesEnquiry.setType("SALES ENQUIRY");
        salesEnquiry.setSubject("Sales Enquiry Details - {{enquiryNumber}}");
        salesEnquiry.setBodyContent(
            "<p>Dear <strong>{{contactName}}</strong>,</p>" +
            "<p>Thank you for reaching out to <strong>{{companyName}}</strong>.</p>" +
            "<p>Please find your enquiry details regarding <strong>{{enquiryNumber}}</strong> below. Our sales representative will be in touch with you shortly.</p>"
        );
        salesEnquiry.setYoursWindfully("Autonoma ERP Corp Sales Team");
        salesEnquiry.setIsActive(true);
        defaultTemplatesMap.put("SALES ENQUIRY", salesEnquiry);

        // 18. AUTOMATED REPORT
        EmailContent report = new EmailContent();
        report.setType("AUTOMATED REPORT");
        report.setSubject("Automated Report Delivery: {{reportName}}");
        report.setBodyContent(
            "<p>Dear Recipient,</p>" +
            "<p>Please find your automated business report <strong>{{reportName}}</strong> generated on {{currentDate}} below.</p>"
        );
        report.setYoursWindfully("Autonoma ERP Corp System Automation");
        report.setIsActive(true);
        defaultTemplatesMap.put("AUTOMATED REPORT", report);

        // 19. SMTP TEST
        EmailContent smtpTest = new EmailContent();
        smtpTest.setType("SMTP TEST");
        smtpTest.setSubject("SMTP Configuration Test Email - {{companyName}}");
        smtpTest.setBodyContent(
            "<p>Dear Administrator,</p>" +
            "<p>This is a test email sent from <strong>{{companyName}}</strong> to verify system SMTP connectivity.</p>" +
            "<p>If you are receiving this message, your mail server settings are configured correctly and active.</p>"
        );
        smtpTest.setYoursWindfully("Autonoma ERP Corp System Administrator");
        smtpTest.setIsActive(true);
        defaultTemplatesMap.put("SMTP TEST", smtpTest);

        // 20. GENERAL NOTIFICATION
        EmailContent notification = new EmailContent();
        notification.setType("GENERAL NOTIFICATION");
        notification.setSubject("System Notification - {{companyName}}");
        notification.setBodyContent(
            "<p>Dear User,</p>" +
            "<p>You have received a new notification from <strong>{{companyName}}</strong> system.</p>"
        );
        notification.setYoursWindfully("Autonoma ERP Corp Support");
        notification.setIsActive(true);
        defaultTemplatesMap.put("GENERAL NOTIFICATION", notification);
    }

    public EmailContent getDefaultTemplate(String type) {
        if (type == null) return createGenericDefault("GENERAL");
        String key = type.toUpperCase().trim();
        EmailContent template = defaultTemplatesMap.get(key);
        if (template != null) {
            EmailContent copy = new EmailContent();
            copy.setType(template.getType());
            copy.setSubject(template.getSubject());
            copy.setBodyContent(template.getBodyContent());
            copy.setYoursWindfully(template.getYoursWindfully());
            copy.setIncludeCompanyFooter(template.getIncludeCompanyFooter());
            copy.setIncludeWebsite(template.getIncludeWebsite());
            copy.setIncludeLocation(template.getIncludeLocation());
            copy.setIsActive(true);
            copy.setFooterHeader(template.getFooterHeader() != null ? template.getFooterHeader() : "Thanks & Regards");
            copy.setFooterContent(template.getFooterContent() != null ? template.getFooterContent() : "");
            copy.setUseCurrentUserCredentials(template.getUseCurrentUserCredentials() != null ? template.getUseCurrentUserCredentials() : false);
            return copy;
        }
        return createGenericDefault(type);
    }

    private EmailContent createGenericDefault(String type) {
        EmailContent template = new EmailContent();
        template.setType(type);
        template.setSubject(type + " Notification - {{candidateFirstName}}");
        template.setBodyContent(
            "<p>Dear <strong>{{candidateFirstName}}</strong>,</p>" +
            "<p>This is an automated notification regarding <strong>" + type + "</strong> from <strong>{{companyName}}</strong>.</p>"
        );
        template.setYoursWindfully("Autonoma ERP Corp HR Team");
        template.setFooterHeader("Thanks & Regards");
        template.setFooterContent("");
        template.setUseCurrentUserCredentials(false);
        template.setIsActive(true);
        return template;
    }
}
