import {
  IconDashboard,
  IconUsers,
  IconBriefcase,
  IconBuildingFactory,
  IconAward,
  IconTruckDelivery,
  IconReceiptTax,
  IconTool,
  IconServerCog,
  IconListCheck,
  IconReport,
  IconHelp,
  IconChecks,
  IconRocket,
  IconMapPin,
  IconCoins,
  IconChartBar,
  IconChartPie,
  IconCreditCard,
  IconSettings,
  IconWorld,
  IconHierarchy,
  IconUserCheck,
  IconUserPlus,
  IconClipboardCheck,
  IconReportAnalytics,
  IconMessage2,
  IconCalendarEvent,
  IconFileCheck,
  IconNotes,
  IconBuilding,
  IconCertificate,
  IconShieldCheck,
  IconTags,
  IconFileText,
  IconFileInvoice,
  IconBuildingBank,
  IconClock,
  IconCalendar,
  IconLock,
  IconGasStation,
  IconTruck,
  IconRuler2,
  IconChartDonut,
  IconPlaneTilt,
  IconTractor,
  IconMoodSmile,
  IconSearch,
  IconCategory,
  IconRotate2,
  IconTicTac,
  IconTicket,
  IconTicketOff,
  IconBrain,
  IconRobot,
  IconSparkles,
  IconCoin,
  IconCircleX,
  IconAlertTriangle,
  IconCash,
  IconMailForward,
  IconNotebook,
  IconTimeline,
  IconPackage,
  IconDatabase,
  IconUserShield,
  IconTarget,
  IconClipboardList,
  IconCpu,
  IconCalendarStats,
  IconForklift,
  IconBusinessplan,
  IconPencilCog,
  IconTools,
  IconLifebuoy,
  IconShoppingCart,
  IconList,
  IconShield,
  IconFlame
} from '@tabler/icons-react';

import {
  Storage,
  AdminPanelSettings,
  TrackChanges,
  Assignment,
  PrecisionManufacturing,
  LocalShipping,
  AccountBalance,
  Architecture,
  Handyman,
  Verified,
  Analytics,
  SupportAgent,
  ShoppingCart as ShoppingCartMui
} from '@mui/icons-material';

import { withMuiIcon } from 'utils/withMuiIcon.jsx';

const SolidIcons = {
  Master: withMuiIcon(Storage),
  HRA: withMuiIcon(AdminPanelSettings),
  Sales: withMuiIcon(TrackChanges),
  Planning: withMuiIcon(Assignment),
  Production: withMuiIcon(PrecisionManufacturing),
  Logistics: withMuiIcon(LocalShipping),
  Finance: withMuiIcon(AccountBalance),
  Design: withMuiIcon(Architecture),
  Maintenance: withMuiIcon(Handyman),
  QMS: withMuiIcon(Verified),
  Reports: withMuiIcon(Analytics),
  Support: withMuiIcon(SupportAgent),
  Order: withMuiIcon(ShoppingCartMui)
};

const icons = {
  IconList,
  IconShield,
  IconFlame,
  IconMailForward,
  IconNotebook,
  IconPackage,
  IconDashboard,
  IconCategory,
  IconAlertTriangle,
  IconUsers,
  IconBriefcase,
  IconBuildingFactory,
  IconAward,
  IconTruckDelivery,
  IconReceiptTax,
  IconTool,
  IconServerCog,
  IconListCheck,
  IconReport,
  IconHelp,
  IconChecks,
  IconRocket,
  IconMapPin,
  IconCoins,
  IconCoin,
  IconCircleX,
  IconChartBar,
  IconChartPie,
  IconCreditCard,
  IconSettings,
  IconWorld,
  IconHierarchy,
  IconUserCheck,
  IconUserPlus,
  IconClipboardCheck,
  IconReportAnalytics,
  IconMessage2,
  IconCalendarEvent,
  IconFileCheck,
  IconNotes,
  IconBuilding,
  IconCertificate,
  IconShieldCheck,
  IconTags,
  IconFileText,
  IconFileInvoice,
  IconBuildingBank,
  IconClock,
  IconCalendar,
  IconLock,
  IconGasStation,
  IconTruck,
  IconRuler2,
  IconChartDonut,
  IconPlaneTilt,
  IconTractor,
  IconMoodSmile,
  IconSearch,
  IconRotate2,
  IconBrain,
  IconRobot,
  IconSparkles,
  IconTimeline,
  IconCash,
  IconClipboardList,
  IconShoppingCart,
  IconCalendarStats
};

export const purchase = {
  id: 'pp',
  title: 'Planning & Purchase',
  caption: 'Planning & Purchase PP0000',
  type: 'group',
  icon: SolidIcons.Planning,
  children: [


    {
      id: 'purchase-request',
      title: 'Purchase Request',
      type: 'item',
      url: '/purchase/pr/list',
      icon: icons.IconClipboardList,
      pageCode: 'PP0104',
      breadcrumbs: false
    },
    {
      id: 'request-for-quotation',
      title: 'Request For Quotation',
      type: 'item',
      url: '/purchase/rfq/list',
      icon: icons.IconMailForward,
      pageCode: 'PP0105',
      breadcrumbs: false
    },
    {
      id: 'supplier-quotation',
      title: 'Supplier Quotation',
      type: 'item',
      url: '/purchase/quotation/list',
      icon: icons.IconFileInvoice,
      pageCode: 'PP0106',
      breadcrumbs: false
    },
    {
      id: 'quote-negotiation',
      title: 'Quote Negotiation',
      type: 'item',
      url: '/purchase/negotiation/list',
      icon: icons.IconMessage2,
      pageCode: 'PP0107',
      breadcrumbs: false
    },
    {
      id: 'quotation-comparison',
      title: 'Quotation Comparison',
      type: 'item',
      url: '/purchase/comparison',
      icon: icons.IconChartBar,
      pageCode: 'PP0108',
      breadcrumbs: false
    },
    {
      id: 'po',
      title: 'Purchase Order',
      type: 'item',
      url: '/purchase/po',
      icon: icons.IconShoppingCart,
      pageCode: 'PP0100',
      breadcrumbs: false
    },
    {
      id: 'po-schedule',
      title: 'Purchase Order Schedule',
      type: 'item',
      url: '/purchase/po-schedule',
      icon: icons.IconCalendarStats,
      pageCode: 'PP0101',
      breadcrumbs: false
    },


    {
      id: 'supplier-return',
      title: 'Supplier Return',
      type: 'item',
      url: '/purchase/supplier-return',
      icon: icons.IconRotate2,
      pageCode: 'PP0112',
      breadcrumbs: false
    }

  ]
};


