import {
  IconDashboard,
  IconUsers,
  IconBriefcase,
  IconBuildingFactory,
  IconAward,
  IconTruckDelivery,
  IconReceiptTax,
  IconTool,
  IconServerCog,
  IconListCheck,
  IconReport,
  IconHelp,
  IconChecks,
  IconRocket,
  IconMapPin,
  IconCoins,
  IconChartBar,
  IconChartPie,
  IconCreditCard,
  IconSettings,
  IconWorld,
  IconHierarchy,
  IconUserCheck,
  IconUserPlus,
  IconClipboardCheck,
  IconReportAnalytics,
  IconMessage2,
  IconCalendarEvent,
  IconFileCheck,
  IconNotes,
  IconBuilding,
  IconBuildingSkyscraper,
  IconCertificate,
  IconShieldCheck,
  IconTags,
  IconFileText,
  IconFileInvoice,
  IconBuildingBank,
  IconClock,
  IconCalendar,
  IconLock,
  IconGasStation,
  IconTruck,
  IconRuler2,
  IconChartDonut,
  IconPlaneTilt,
  IconTractor,
  IconMoodSmile,
  IconSearch,
  IconCategory,
  IconRotate2,
  IconTicTac,
  IconTicket,
  IconTicketOff,
  IconBrain,
  IconRobot,
  IconSparkles,
  IconCoin,
  IconCircleX,
  IconAlertTriangle,
  IconCash,
  IconMailForward,
  IconNotebook,
  IconTimeline,
  IconPackage,
  IconDatabase,
  IconUserShield,
  IconTarget,
  IconClipboardList,
  IconCpu,
  IconForklift,
  IconBusinessplan,
  IconPencilCog,
  IconTools,
  IconLifebuoy,
  IconShoppingCart,
  IconList,
  IconShield,
  IconFlame,
  IconChartLine
} from '@tabler/icons-react';

import {
  Storage,
  AdminPanelSettings,
  TrackChanges,
  Assignment,
  PrecisionManufacturing,
  LocalShipping,
  AccountBalance,
  Architecture,
  Handyman,
  Verified,
  Analytics,
  SupportAgent,
  ShoppingCart as ShoppingCartMui
} from '@mui/icons-material';

import { withMuiIcon } from 'utils/withMuiIcon.jsx';

const SolidIcons = {
  Master: withMuiIcon(Storage),
  HRA: withMuiIcon(AdminPanelSettings),
  Sales: withMuiIcon(TrackChanges),
  Planning: withMuiIcon(Assignment),
  Production: withMuiIcon(PrecisionManufacturing),
  Logistics: withMuiIcon(LocalShipping),
  Finance: withMuiIcon(AccountBalance),
  Design: withMuiIcon(Architecture),
  Maintenance: withMuiIcon(Handyman),
  QMS: withMuiIcon(Verified),
  Reports: withMuiIcon(Analytics),
  Support: withMuiIcon(SupportAgent),
  Order: withMuiIcon(ShoppingCartMui)
};

const icons = {
  IconList,
  IconShield,
  IconFlame,
  IconMailForward,
  IconNotebook,
  IconPackage,
  IconDashboard,
  IconCategory,
  IconAlertTriangle,
  IconUsers,
  IconBriefcase,
  IconBuildingFactory,
  IconAward,
  IconTruckDelivery,
  IconReceiptTax,
  IconTool,
  IconServerCog,
  IconListCheck,
  IconReport,
  IconHelp,
  IconChecks,
  IconRocket,
  IconMapPin,
  IconCoins,
  IconCoin,
  IconCircleX,
  IconChartBar,
  IconChartPie,
  IconCreditCard,
  IconSettings,
  IconWorld,
  IconHierarchy,
  IconUserCheck,
  IconUserPlus,
  IconClipboardCheck,
  IconReportAnalytics,
  IconMessage2,
  IconCalendarEvent,
  IconFileCheck,
  IconNotes,
  IconBuilding,
  IconBuildingSkyscraper,
  IconCertificate,
  IconShieldCheck,
  IconTags,
  IconFileText,
  IconFileInvoice,
  IconBuildingBank,
  IconClock,
  IconCalendar,
  IconLock,
  IconGasStation,
  IconTruck,
  IconRuler2,
  IconChartDonut,
  IconPlaneTilt,
  IconTractor,
  IconMoodSmile,
  IconSearch,
  IconRotate2,
  IconBrain,
  IconRobot,
  IconSparkles,
  IconTimeline,
  IconCash
};


export const sales = {
  id: 'sm',
  title: 'Sales & Marketing',
  caption: 'Sales & Marketing SM0000',
  type: 'group',
  icon: SolidIcons.Sales,
  children: [
    {
      id: 'sm-sales-submenu',
      title: 'Sales',
      type: 'collapse',
      icon: icons.IconBriefcase,
      children: [
        {
          id: 'sm-order-management',
          title: 'Customer Order',
          type: 'item',
          url: '/sm/sales/customer/order-management',
          icon: icons.IconPackage,
          pageCode: 'SM1160'
        },
        {
          id: 'sm-order-schedule',
          title: 'Customer Order Schedule',
          type: 'item',
          url: '/sm/sales/customer/order-schedule',
          icon: icons.IconCalendarEvent,
          pageCode: 'SM1170'
        },
        {
          id: 'sm-delivery-receipts',
          title: 'Delivery Chellan (DC)',
          type: 'item',
          url: '/sm/sales/customer/delivery-receipts',
          icon: icons.IconTruckDelivery,
          pageCode: 'SM1190'
        },
        {
          id: 'sm-invoice-list',
          title: 'Sales Invoice',
          type: 'item',
          url: '/sm/sales/customer/invoices',
          icon: icons.IconFileInvoice,
          pageCode: 'SM1180'
        }
      ]
    },
    {
      id: 'sm-marketing-submenu',
      title: 'Marketing',
      type: 'collapse',
      icon: icons.IconWorld,
      children: [
        {
          id: 'sm-ocr-dashboard',
          title: 'OCR Dashboard',
          type: 'item',
          url: '/sm/enquiry/dashboard',
          icon: icons.IconDashboard,
          pageCode: 'SM1110'
        },

        {
          id: 'sm-enquiry',
          title: 'Enquiry',
          type: 'item',
          url: '/sm/enquiries',
          icon: icons.IconListCheck,
          pageCode: 'SM1120'
        },
        {
          id: 'sm-price-master',
          title: 'Price Master',
          type: 'item',
          url: '/sm/price-master',
          icon: icons.IconCoins,
          pageCode: 'SM1130'
        },
        {
          id: 'sm-quotation',
          title: 'Quotation',
          type: 'item',
          url: '/sm/quotations',
          icon: icons.IconReport,
          pageCode: 'SM1140'
        },
        {
          id: 'sm-quotation-follow-up',
          title: 'Quotation Follow Up',
          type: 'item',
          url: '/sm/quotation-follow-up',
          icon: icons.IconChartPie,
          pageCode: 'SM1141'
        }
      ]
    }
  ]
};

